"""Type stubs for `outram_park.bedok`, generated from the Rust API.

Physical quantities cross this boundary as `float` in SI base units.
"""

class BedokError:
    @staticmethod
    def NanEncountered() -> BedokError: ...
    @staticmethod
    def UnexpectedComplex() -> BedokError: ...
    @staticmethod
    def NoCoordinateBranch() -> BedokError: ...
    @staticmethod
    def IterativeSolveNotTranslated(philenf: int, threshold: int) -> BedokError: ...
    def variant(self) -> str: ...

class A3:
    x: list[float]
    y: list[float]
    z: list[float]
    xfirst: list[float]
    yfirst: list[float]
    zfirst: list[float]
    def __init__(self, x: list[float] | None = None, y: list[float] | None = None, z: list[float] | None = None, xfirst: list[float] | None = None, yfirst: list[float] | None = None, zfirst: list[float] | None = None) -> None: ...
    @staticmethod
    def default() -> A3: ...

class Expansion:
    a1: A1
    a2: AxisField
    a3: A3
    a4: AxisField
    def __init__(self, a1: A1 | None = None, a2: AxisField | None = None, a3: A3 | None = None, a4: AxisField | None = None) -> None: ...
    @staticmethod
    def default() -> Expansion: ...

class A1:
    x: list[float]
    y: list[float]
    z: list[float]
    xfirst: list[float]
    yfirst: list[float]
    zfirst: list[float]
    def __init__(self, x: list[float] | None = None, y: list[float] | None = None, z: list[float] | None = None, xfirst: list[float] | None = None, yfirst: list[float] | None = None, zfirst: list[float] | None = None) -> None: ...
    @staticmethod
    def default() -> A1: ...

class AxisCoeffs:
    aa: list[float]
    bb: list[float]
    ee: list[float]
    ff: list[float]
    gg: list[float]
    hh: list[float]
    def __init__(self, aa: list[float] | None = None, bb: list[float] | None = None, ee: list[float] | None = None, ff: list[float] | None = None, gg: list[float] | None = None, hh: list[float] | None = None) -> None: ...
    @staticmethod
    def default() -> AxisCoeffs: ...

class Coeffs:
    x: AxisCoeffs
    y: AxisCoeffs
    z: AxisCoeffs
    def __init__(self, x: AxisCoeffs | None = None, y: AxisCoeffs | None = None, z: AxisCoeffs | None = None) -> None: ...
    @staticmethod
    def default() -> Coeffs: ...

class Buckling:
    x: SparseMatrix
    y: SparseMatrix
    z: SparseMatrix
    def __init__(self, x: SparseMatrix | None = None, y: SparseMatrix | None = None, z: SparseMatrix | None = None) -> None: ...
    @staticmethod
    def default() -> Buckling: ...

class BucklingCache:
    def __init__(self, ) -> None: ...
    def is_populated(self) -> bool: ...
    @staticmethod
    def default() -> BucklingCache: ...

class SaNodal:
    operator: SparseMatrix
    def __init__(self) -> None: ...
    @staticmethod
    def default() -> SaNodal: ...

class Leakage:
    x: list[float]
    y: list[float]
    z: list[float]
    def __init__(self, x: list[float] | None = None, y: list[float] | None = None, z: list[float] | None = None) -> None: ...
    @staticmethod
    def default() -> Leakage: ...

class IndexMode:
    @staticmethod
    def Plain() -> IndexMode: ...
    @staticmethod
    def DiamondDifference() -> IndexMode: ...
    def variant(self) -> str: ...

class Diagnostics:
    def __init__(self) -> None: ...
    @staticmethod
    def default() -> Diagnostics: ...

class DiffusionOutput:
    k_eff: float
    residual: float
    k_eff_residual: float
    scalar_flux: list[float]
    fission_source: list[float]
    pwrdens: list[float]
    iterations: int
    termination: Termination
    diagnostics: Diagnostics

class Termination:
    @staticmethod
    def Converged() -> Termination: ...
    @staticmethod
    def NonPositiveKeff() -> Termination: ...
    @staticmethod
    def NanKeff() -> Termination: ...
    @staticmethod
    def IterationCap() -> Termination: ...
    def variant(self) -> str: ...

class Extrapolation:
    @staticmethod
    def Applied() -> Extrapolation: ...
    @staticmethod
    def ZeroNorm() -> Extrapolation: ...
    @staticmethod
    def NotAsymptotic() -> Extrapolation: ...
    def variant(self) -> str: ...

class Solve:
    @staticmethod
    def Ok() -> Solve: ...
    @staticmethod
    def NotFinite() -> Solve: ...
    def variant(self) -> str: ...

class GradD:
    operator: SparseMatrix
    def __init__(self) -> None: ...
    @staticmethod
    def default() -> GradD: ...

class SigmaIndexMode:
    @staticmethod
    def Full() -> SigmaIndexMode: ...
    @staticmethod
    def HalfIndex() -> SigmaIndexMode: ...
    def variant(self) -> str: ...

class Decomposition:
    def __init__(self, a: SparseMatrix) -> None: ...
    def solve(self, rhs: list[float]) -> list[float]: ...
    @staticmethod
    def Singular() -> Decomposition: ...
    def variant(self) -> str: ...

class SparseMatrix:
    @staticmethod
    def zeros(rows: int, cols: int) -> SparseMatrix: ...
    @staticmethod
    def assemble(i: list[int], j: list[int], v: list[float], rows: int, cols: int) -> SparseMatrix: ...
    def rows(self) -> int: ...
    def cols(self) -> int: ...
    def add(self, i: int, j: int, value: float) -> None: ...
    def set(self, i: int, j: int, value: float) -> None: ...
    def nnz(self) -> int: ...
    def find(self) -> list[Triplet]: ...
    def diagonal(self) -> list[float]: ...
    def column_sums(self) -> list[float]: ...
    def mul_vec(self, x: list[float]) -> list[float]: ...
    def __init__(self) -> None: ...
    @staticmethod
    def default() -> SparseMatrix: ...

class Triplet:
    i: int
    j: int
    v: float
    def __init__(self, i: int, j: int, v: float) -> None: ...

class sanodaldiffusion_solverxyz_Diagnostics:
    def __init__(self) -> None: ...
    @staticmethod
    def default() -> sanodaldiffusion_solverxyz_Diagnostics: ...

class SaNodalOutput:
    k_eff: float
    residual: float
    k_eff_residual: float
    fission_source: list[float]
    pwrdens: list[float]
    iterations: int
    nodal_updates: int
    termination: sanodaldiffusion_solverxyz_Termination
    diagnostics: sanodaldiffusion_solverxyz_Diagnostics | None

class sanodaldiffusion_solverxyz_Termination:
    @staticmethod
    def Converged() -> sanodaldiffusion_solverxyz_Termination: ...
    @staticmethod
    def NonPositiveKeff() -> sanodaldiffusion_solverxyz_Termination: ...
    @staticmethod
    def NanKeff() -> sanodaldiffusion_solverxyz_Termination: ...
    @staticmethod
    def IterationCap() -> sanodaldiffusion_solverxyz_Termination: ...
    def variant(self) -> str: ...

class DeltaSigmaValues:
    reference: float
    def __init__(self) -> None: ...
    @staticmethod
    def default() -> DeltaSigmaValues: ...

class AxisField:
    x: list[float]
    y: list[float]
    z: list[float]
    def __init__(self, x: list[float] | None = None, y: list[float] | None = None, z: list[float] | None = None) -> None: ...
    @staticmethod
    def default() -> AxisField: ...

class BoundaryCondition:
    @staticmethod
    def Vacuum() -> BoundaryCondition: ...
    @staticmethod
    def ZeroFlux() -> BoundaryCondition: ...
    @staticmethod
    def Reflective() -> BoundaryCondition: ...
    def variant(self) -> str: ...
    @staticmethod
    def default() -> BoundaryCondition: ...

class Conductivity:
    def at(self, t: float) -> float: ...
    @staticmethod
    def Uo2Fuel() -> Conductivity: ...
    @staticmethod
    def ZircaloyClad() -> Conductivity: ...
    @staticmethod
    def Constant(a0: float) -> Conductivity: ...
    def variant(self) -> str: ...

class Coolant:
    inlettemp: float
    inletpress: float
    press: list[float]
    temps: list[float]
    enth: list[float]
    quality: list[float]
    alphag: list[float]
    vm: list[float]
    ldens: list[float]
    gdens: list[float]
    dens: list[float]
    kvis: list[float]
    pran: list[float]
    tcon: list[float]
    def __init__(self, inlettemp: float | None = None, inletpress: float | None = None, press: list[float] | None = None, temps: list[float] | None = None, enth: list[float] | None = None, quality: list[float] | None = None, alphag: list[float] | None = None, vm: list[float] | None = None, ldens: list[float] | None = None, gdens: list[float] | None = None, dens: list[float] | None = None, kvis: list[float] | None = None, pran: list[float] | None = None, tcon: list[float] | None = None) -> None: ...
    @staticmethod
    def default() -> Coolant: ...

class CoordinateMode:
    @staticmethod
    def Cylindrical() -> CoordinateMode: ...
    @staticmethod
    def Cartesian() -> CoordinateMode: ...
    @staticmethod
    def Generic() -> CoordinateMode: ...
    def variant(self) -> str: ...

class FuelGeometry:
    lr: list[float]
    ctr: list[float]
    vi: list[float]
    whichk: list[int]
    tcon: list[Conductivity]
    gap_conductance: float
    fuelrad: float
    rtot: float
    pitch: float
    subarea: float
    hydia: float
    doppleralpha: float
    def __init__(self, lr: list[float] | None = None, ctr: list[float] | None = None, vi: list[float] | None = None, whichk: list[int] | None = None, tcon: list[Conductivity] | None = None, gap_conductance: float | None = None, fuelrad: float | None = None, rtot: float | None = None, pitch: float | None = None, subarea: float | None = None, hydia: float | None = None, doppleralpha: float | None = None) -> None: ...
    @staticmethod
    def default() -> FuelGeometry: ...

class FuelParams:
    maxir: int
    fueln: int
    gapn: int
    cladn: int
    def __init__(self, maxir: int | None = None, fueln: int | None = None, gapn: int | None = None, cladn: int | None = None) -> None: ...
    @staticmethod
    def default() -> FuelParams: ...

class Geometry:
    xtot: float
    ytot: float
    lx: list[float]
    ly: list[float]
    lz: list[float]
    vi: list[float]
    xmin: BoundaryCondition
    xmax: BoundaryCondition
    ymin: BoundaryCondition
    ymax: BoundaryCondition
    zmin: BoundaryCondition
    zmax: BoundaryCondition
    def __init__(self) -> None: ...
    @staticmethod
    def default() -> Geometry: ...

class Params:
    maxir: int | None
    maxitheta: int | None
    maxix: int | None
    maxiy: int | None
    maxiz: int | None
    maxi1: int | None
    maxi2: int | None
    maxi3: int | None
    g: int
    nc: int | None
    max_num_cycles: int
    nodalupd: int
    fsexp: int
    innertol: float | None
    stop: int
    verb: int
    plotfig: int
    plot3d: int
    debugdump: int
    tend: float | None
    tgrid: list[float] | None
    timepicard: int | None
    nodalupdtime: int | None
    jfnkprecon: int
    jfnkrel: float
    jfnkverb: int
    def coordinate_mode_2d(self) -> CoordinateMode | None: ...
    def coordinate_mode_3d(self) -> CoordinateMode | None: ...
    def nc_or_zero(self) -> int: ...
    def __init__(self, maxir: int | None = None, maxitheta: int | None = None, maxix: int | None = None, maxiy: int | None = None, maxiz: int | None = None, maxi1: int | None = None, maxi2: int | None = None, maxi3: int | None = None, g: int | None = None, nc: int | None = None, max_num_cycles: int | None = None, nodalupd: int | None = None, fsexp: int | None = None, innertol: float | None = None, stop: int | None = None, verb: int | None = None, plotfig: int | None = None, plot3d: int | None = None, debugdump: int | None = None, tend: float | None = None, tgrid: list[float] | None = None, timepicard: int | None = None, nodalupdtime: int | None = None, jfnkprecon: int | None = None, jfnkrel: float | None = None, jfnkverb: int | None = None) -> None: ...
    @staticmethod
    def default() -> Params: ...

class Sigma:
    tot: SparseMatrix
    s: SparseMatrix
    f: SparseMatrix
    fp: SparseMatrix
    fb: SparseMatrix
    sd: SparseMatrix
    nu: list[float]
    def __init__(self) -> None: ...
    @staticmethod
    def default() -> Sigma: ...

class SigmaValues:
    def __init__(self) -> None: ...
    @staticmethod
    def default() -> SigmaValues: ...

class Th:
    coolant: Coolant
    heatflux: list[float]
    def __init__(self, coolant: Coolant | None = None, heatflux: list[float] | None = None) -> None: ...
    @staticmethod
    def default() -> Th: ...

class Chf:
    chf: list[float]
    dnbr: list[float]
    def __init__(self, chf: list[float] | None = None, dnbr: list[float] | None = None) -> None: ...
    @staticmethod
    def default() -> Chf: ...

def calc_1sttransleakagexyz(params: Params, geometry: Geometry, leakzero: Leakage, diffvalues: list[float]) -> Leakage: ...
def calc_2ndtransleakagexyz(params: Params, geometry: Geometry, leakzero: Leakage, diffvalues: list[float]) -> Leakage: ...
def calc_a1_expansionxyz(params: Params, geometry: Geometry, coeffs: Coeffs, phivec: list[float], a2: AxisField, a4: AxisField, leakone: Leakage, diffvalues: list[float], buck: Buckling) -> A1: ...
def calc_bucklingxyz(cache: BucklingCache, params: Params, geometry: Geometry, sigma: Sigma, diffvalues: list[float], keff: float) -> Buckling: ...
def convertindexc2d(params: Params, vec: list[float], frommode: IndexMode, tomode: IndexMode) -> list[float]: ...
def convertsparseformat2d(params: Params, mat: SparseMatrix, frommode: IndexMode, tomode: IndexMode) -> SparseMatrix: ...
def convertsparsekey3d(mat: SparseMatrix, key: list[int | None], lennew: int) -> SparseMatrix: ...
def fixinfnan(vector: list[float], use_min_abs: bool) -> list[float]: ...
def fixnegativematrix(mat: SparseMatrix) -> None: ...
def fuelrodheat_1dcylnd(fuel: FuelGeometry, maxir: int, temps: list[float], pwr: float, bc: float, modtemp: float) -> tuple[list[float], Solve]: ...
def handle2dcoords(params: Params) -> tuple[int, int]: ...
def handle3dcoords(params: Params) -> tuple[int, int, int]: ...
def h2bc_p(p: float) -> float: ...
def t1_ph(p: float, h: float) -> float: ...
def t2a_ph(p: float, h: float) -> float: ...
def t2b_ph(p: float, h: float) -> float: ...
def t2c_ph(p: float, h: float) -> float: ...
def t_ph(p: float, h: float) -> float: ...
def tb23_p(p: float) -> float: ...
def cp1_pt(p: float, t: float) -> float: ...
def cp2_pt(p: float, t: float) -> float: ...
def h1_pt(p: float, t: float) -> float: ...
def h2_pt(p: float, t: float) -> float: ...
def hfg_p(p: float) -> float: ...
def hl_p(p: float) -> float: ...
def hv_p(p: float) -> float: ...
def v1_pt(p: float, t: float) -> float: ...
def v2_pt(p: float, t: float) -> float: ...
def vl_p(p: float) -> float: ...
def vv_p(p: float) -> float: ...
def dgammadpi1_pt(p: float, t: float) -> float: ...
def dgammadpipi1_pt(p: float, t: float) -> float: ...
def dgammadpitau1_pt(p: float, t: float) -> float: ...
def dgammadtau1_pt(p: float, t: float) -> float: ...
def dgammadtautau1_pt(p: float, t: float) -> float: ...
def dgammadpi2_pt(p: float, t: float) -> float: ...
def dgammadpipi2_pt(p: float, t: float) -> float: ...
def dgammadpitau2_pt(p: float, t: float) -> float: ...
def dgammadtau2_pt(p: float, t: float) -> float: ...
def dgammadtautau2_pt(p: float, t: float) -> float: ...
def p_b13_sat() -> float: ...
def psat_t(t: float) -> float: ...
def tsat_p(p: float) -> float: ...
def makeheatlaplacian_1dcylnd(fuel: FuelGeometry, maxir: int, temps: list[float], bc: float) -> SparseMatrix: ...
def min_abs_finite(v: list[float]) -> float | None: ...
def norm1(v: list[float]) -> float: ...
def norm2(v: list[float]) -> float: ...
def solve_dense(a: list[float], b: list[float], n: int) -> list[float]: ...
def pauseonnan(input: list[float]) -> None: ...
def w3chf(fuel: FuelGeometry, th: Th) -> Chf: ...
MAX_ITER: int
SIZE_THRESH: int
TOL: float
P_CRIT: float
T_B13: float
T_CRIT: float
T_MIN: float
EXTRAP_HISTORY: int
HISTORY: int
MAX_ITER: int
SIZE_THRESH: int
