"""Type stubs for `outram_park.boon_lay`, generated from the Rust API.

Physical quantities cross this boundary as `float` in SI base units.
"""

class GpuContext:
    def adapter_name(self) -> str: ...

class GpuError:
    @staticmethod
    def Poll(a0: str) -> GpuError: ...
    @staticmethod
    def Map(a0: str) -> GpuError: ...
    @staticmethod
    def MapCallbackMissing() -> GpuError: ...
    def variant(self) -> str: ...

class OoRng64:
    @staticmethod
    def from_u128(seed: int) -> OoRng64: ...
    @staticmethod
    def from_u64(seed: int) -> OoRng64: ...
    def rand_float(self) -> float: ...
    def next_u64(self) -> int: ...

class EnsembleConfig:
    n_histories: int
    base_seed: int
    def __init__(self, n_histories: int, base_seed: int) -> None: ...

class LiveEnsemble:
    def reset(self) -> None: ...
    def sim_time(self) -> float: ...
    def cell(self) -> TrisoCell: ...
    def len(self) -> int: ...
    def is_empty(self) -> bool: ...
    def released_fraction(self) -> float: ...
    def snapshot(self) -> Snapshot: ...
    def advance_frame(self, compute: ComputeType, until: float) -> None: ...

class Snapshot:
    positions_xy_um: list[list[float]]
    released_fraction: float
    sim_time_s: float
    n_total: int
    def __init__(self) -> None: ...
    @staticmethod
    def default() -> Snapshot: ...

class HopOutcome:
    @staticmethod
    def Stepped() -> HopOutcome: ...
    @staticmethod
    def Released() -> HopOutcome: ...
    @staticmethod
    def ReachedInterface() -> HopOutcome: ...
    def variant(self) -> str: ...

class WalkParams:
    capture_eps: float
    reinsert_factor: float
    partition_k: float
    max_steps: int
    @staticmethod
    def crp6_default() -> WalkParams: ...
    def __init__(self, capture_eps: float, reinsert_factor: float, partition_k: float, max_steps: int) -> None: ...

class WoSWalker:
    position: list[float]
    time: float
    rng: OoRng64
    def decay_rate(self, decay_library: DecayLibrary) -> float: ...
    def decay_once(self, decay_library: DecayLibrary) -> bool: ...
    def advance_until(self, triso_cell: TrisoCell, params: WalkParams, decay_library: DecayLibrary, transmutation: Transmutation, until: float) -> DepletionOutcome: ...
    def radius(self) -> float: ...
    def hop(self, triso_cell: TrisoCell, capture_eps: float) -> HopOutcome: ...
    def walk_to_absorbing_sphere(self, sphere_radius: float, diffusion_coefficient: float, capture_eps: float) -> float: ...
    def step_multilayer(self, triso_cell: TrisoCell, params: WalkParams) -> HopOutcome: ...
    def diffuse_until(self, triso_cell: TrisoCell, params: WalkParams, until: float) -> bool: ...
    def walk_until_released(self, triso_cell: TrisoCell, params: WalkParams) -> float | None: ...

class Vec3:
    x: float
    y: float
    z: float
    def add(self, other: Vec3) -> Vec3: ...
    def scale(self, s: float) -> Vec3: ...
    def norm(self) -> float: ...
    def normalize(self) -> Vec3: ...
    def __init__(self, x: float, y: float, z: float) -> None: ...

class SingleParticleDiffusionSimulatorMC:
    position: tuple[float, float, float]
    rng: OoRng64
    def move_particle_using_tuple(self, length_tuple: tuple[float, float, float]) -> None: ...
    def move_particle_gaussian_sampling_u64(self, mean_free_path: float, no_of_collisions: int) -> None: ...
    def move_particle_gaussian_sampling_f64(self, mean_free_path: float, no_of_collisions: float) -> None: ...
    def get_gaussian_velocity_vector(self, mean_free_path: float, collision_rate: float) -> list[float]: ...
    def sample_isotropic_direction(self) -> list[float]: ...
    def sample_mean_free_path_given_sigma_s(self, sigma_s: float) -> float: ...
    def scatter_isotropically_using_macro_xs(self, sigma_s: float) -> None: ...
    def __init__(self, position: tuple[float, float, float], rng: OoRng64) -> None: ...

class DiffusionRandomCache:
    def __init__(self, cache_size: int) -> None: ...
    def get_normal(self) -> float: ...
    def get_normal_3d(self) -> tuple[float, float, float]: ...
    def get_displacement_3d(self, scale: float) -> tuple[float, float, float]: ...

class Region:
    def try_return_center_and_radius_of_sphere(self) -> tuple[list[float], float] | None: ...
    def variant(self) -> str: ...

class TrisoCell:
    def __init__(self, fuel_radius: float, buffer_radius: float, ipyc_radius: float, sic_radius: float, opyc_radius: float) -> None: ...
    @staticmethod
    def new_crp6_geometry() -> TrisoCell: ...
    def set_uniform_temperature(self, temp: float) -> None: ...
    def get_uniform_temperature(self) -> float: ...
    def get_fuel_radius(self) -> float: ...
    def get_buffer_radius(self) -> float: ...
    def get_ipyc_radius(self) -> float: ...
    def get_sic_radius(self) -> float: ...
    def get_opyc_radius(self) -> float: ...

class TrisoRegion:
    @staticmethod
    def Fuel() -> TrisoRegion: ...
    @staticmethod
    def Buffer() -> TrisoRegion: ...
    @staticmethod
    def IPyC() -> TrisoRegion: ...
    @staticmethod
    def SiC() -> TrisoRegion: ...
    @staticmethod
    def OPyC() -> TrisoRegion: ...
    @staticmethod
    def Outside() -> TrisoRegion: ...
    def variant(self) -> str: ...

class SphereCrossing:
    def time(self) -> float: ...
    @staticmethod
    def Entry(t: float) -> SphereCrossing: ...
    @staticmethod
    def Exit(t: float) -> SphereCrossing: ...
    def variant(self) -> str: ...

class TrisoPebbleLayerMaterial:
    @staticmethod
    def KernelUO2() -> TrisoPebbleLayerMaterial: ...
    @staticmethod
    def PyC() -> TrisoPebbleLayerMaterial: ...
    @staticmethod
    def SiC() -> TrisoPebbleLayerMaterial: ...
    @staticmethod
    def MatrixGraphite() -> TrisoPebbleLayerMaterial: ...
    @staticmethod
    def StructuralGraphite() -> TrisoPebbleLayerMaterial: ...
    @staticmethod
    def CrackedMaterial() -> TrisoPebbleLayerMaterial: ...
    @staticmethod
    def Buffer() -> TrisoPebbleLayerMaterial: ...
    def variant(self) -> str: ...

class DepletionOutcome:
    def variant(self) -> str: ...

class Transmutation:
    @staticmethod
    def None_() -> Transmutation: ...
    def variant(self) -> str: ...

class DecayData:
    decay_type: DecayType
    branching_ratio: float

class ComputeType:
    def label(self) -> str: ...
    def next(self) -> ComputeType: ...
    @staticmethod
    def CpuSingleThread() -> ComputeType: ...
    @staticmethod
    def CpuMultiThread(a0: ThreadCount) -> ComputeType: ...
    @staticmethod
    def Gpu() -> ComputeType: ...
    def variant(self) -> str: ...
    @staticmethod
    def default() -> ComputeType: ...

class DecayType:
    @staticmethod
    def parse_from_string(string: str) -> DecayType: ...
    @staticmethod
    def Alpha() -> DecayType: ...
    @staticmethod
    def ElectronCaptureBetaPlus() -> DecayType: ...
    @staticmethod
    def ElectronCaptureBetaPlusAndAlpha() -> DecayType: ...
    @staticmethod
    def BetaMinus() -> DecayType: ...
    @staticmethod
    def BetaMinusAndNeutron() -> DecayType: ...
    @staticmethod
    def BetaMinusAndTwoNeutron() -> DecayType: ...
    @staticmethod
    def BetaMinusAndThreeNeutron() -> DecayType: ...
    @staticmethod
    def BetaMinusAndFourNeutron() -> DecayType: ...
    @staticmethod
    def BetaMinusAndAlpha() -> DecayType: ...
    @staticmethod
    def DoubleBetaMinus() -> DecayType: ...
    @staticmethod
    def IsomericTransition() -> DecayType: ...
    @staticmethod
    def Proton() -> DecayType: ...
    @staticmethod
    def DoubleProton() -> DecayType: ...
    @staticmethod
    def ElectronCaptureBetaPlusAndProton() -> DecayType: ...
    @staticmethod
    def ElectronCaptureBetaPlusDoubleProton() -> DecayType: ...
    @staticmethod
    def SpontaneousFission() -> DecayType: ...
    @staticmethod
    def ElectronCaptureBetaPlusAndSpontaneousFission() -> DecayType: ...
    @staticmethod
    def Neutron() -> DecayType: ...
    @staticmethod
    def DoubleNeutron() -> DecayType: ...
    def variant(self) -> str: ...

class DiffusionMaterial:
    @staticmethod
    def Kernel() -> DiffusionMaterial: ...
    @staticmethod
    def Graphite() -> DiffusionMaterial: ...
    def variant(self) -> str: ...

class ElementGroup:
    @staticmethod
    def from_atomic_number(z: int) -> ElementGroup: ...
    @staticmethod
    def NobleGas() -> ElementGroup: ...
    @staticmethod
    def Halogen() -> ElementGroup: ...
    @staticmethod
    def SpecialMetal() -> ElementGroup: ...
    @staticmethod
    def Silver() -> ElementGroup: ...
    @staticmethod
    def Other() -> ElementGroup: ...
    def variant(self) -> str: ...

class FailureFractions:
    heavy_metal: float
    sic: float
    incremental: float
    incremental_sic: float
    def sum(self) -> float: ...
    def __init__(self, heavy_metal: float, sic: float, incremental: float, incremental_sic: float) -> None: ...

class HalfLifeAndDecayEnergyInfo:
    @staticmethod
    def Stable() -> HalfLifeAndDecayEnergyInfo: ...
    @staticmethod
    def Unstable(a0: float, a1: float) -> HalfLifeAndDecayEnergyInfo: ...
    def variant(self) -> str: ...

class KernelGraphiteDiffusion:
    kernel: float
    graphite: float
    def __init__(self, kernel: float, graphite: float) -> None: ...

class NodalActivities:
    release_rate: float
    source_rate: float
    graphite_activity: float
    circulating_activity: float
    plate_out_activity: float
    clean_up_activity: float
    def parent_pools(self) -> ParentPools: ...
    def to_curies(self, decay_constant: float) -> NodalActivitiesCurie: ...
    def __init__(self, release_rate: float, source_rate: float, graphite_activity: float, circulating_activity: float, plate_out_activity: float, clean_up_activity: float) -> None: ...

class NodalActivitiesCurie:
    release_rate: float
    source_rate: float
    graphite_activity: float
    circulating_activity: float
    plate_out_activity: float
    clean_up_activity: float
    def __init__(self, release_rate: float, source_rate: float, graphite_activity: float, circulating_activity: float, plate_out_activity: float, clean_up_activity: float) -> None: ...

class NodeState:
    core_temperature: float
    graphite_temperature: float
    def __init__(self, core_temperature: float, graphite_temperature: float) -> None: ...

class NuclideReactionAndDecayData:
    half_life_information: HalfLifeAndDecayEnergyInfo
    decay_information: list[DecayData]
    def try_get_half_life(self) -> float | None: ...
    def is_stable(self) -> bool: ...
    def is_unstable(self) -> bool: ...
    def get_decay_energy(self) -> float | None: ...

class ParentPools:
    circulating: float
    plate_out: float
    clean_up: float
    @staticmethod
    def none() -> ParentPools: ...
    def __init__(self, circulating: float | None = None, plate_out: float | None = None, clean_up: float | None = None) -> None: ...
    @staticmethod
    def default() -> ParentPools: ...

class PlantConstants:
    k_plate: float
    k_clean: float
    graphite_thickness: float
    grain_size: float
    sic_thickness: float
    kernel_radius: float
    run_time: float
    irradiation_time: float
    def __init__(self, k_plate: float, k_clean: float, graphite_thickness: float, grain_size: float, sic_thickness: float, kernel_radius: float, run_time: float, irradiation_time: float) -> None: ...

class ReleaseMaterial:
    @staticmethod
    def Kernel() -> ReleaseMaterial: ...
    @staticmethod
    def Graphite() -> ReleaseMaterial: ...
    def variant(self) -> str: ...

class SingleNuclideSimulatorMC:
    position: tuple[float, float, float]
    def get_time_to_next_decay(self) -> float: ...
    def get_time_to_live_vec(self) -> list[float]: ...
    def get_current_simulated_time(self) -> float: ...
    def get_current_elapsed_time(self) -> float: ...
    def get_current_half_life_info(self) -> HalfLifeAndDecayEnergyInfo: ...
    def get_current_half_life(self) -> float: ...
    def get_decay_constant(self) -> float: ...

class SourceAndGraphite:
    source_rate: float
    graphite_activity: float
    def __init__(self, source_rate: float, graphite_activity: float) -> None: ...

class ThreadCount:
    def resolve(self) -> int: ...
    @staticmethod
    def Auto() -> ThreadCount: ...
    @staticmethod
    def Fixed(a0: int) -> ThreadCount: ...
    @staticmethod
    def Fraction(a0: float) -> ThreadCount: ...
    def variant(self) -> str: ...
    @staticmethod
    def default() -> ThreadCount: ...

class TrisoAtopsNuclide:
    name: str
    z: int
    a: int
    half_life: float
    parents: list[str]
    def decay_constant(self) -> float: ...
    def element_group(self) -> ElementGroup: ...

class DecayLibrary:
    random_number_generator: outram_mc_libs.Lcg64
    def __init__(self, ) -> None: ...
    def get_random_number_and_rng(self) -> tuple[float, outram_mc_libs.Lcg64]: ...

def gpu_available() -> bool: ...
def probe() -> GpuContext | None: ...
def per_component_variance_exponential_for_3d_vector(no_of_collisions: float, mean_free_path: float) -> float: ...
def per_component_variance_exponential_for_3d_vector_u64(no_of_collisions: int, mean_free_path: float) -> float: ...
def per_component_variance_from_second_moment(no_of_collisions: float, e_s2: float) -> float: ...
def per_component_variance_from_second_moment_u64(no_of_collisions: int, e_s2: float) -> float: ...
def history_seed(base_seed: int, index: int) -> int: ...
def released_fraction(outcomes: list[DepletionOutcome]) -> float: ...
def transmission_probability(d_current: float, d_next: float, partition_k: float) -> float: ...
def micrometres(x: float) -> float: ...
def dimensionless_exit_time_table(m: int) -> list[float]: ...
def mean_first_passage_time(radius: float, diffusion_coefficient: float) -> float: ...
def survival_probability(theta: float) -> float: ...
def calculate_analytical_fraction_released(diffusion_coefficient: float, radius: float, time: float, num_terms: int) -> float: ...
def get_d1_for_ag(triso_layer: TrisoPebbleLayerMaterial) -> float: ...
def get_d1_for_cs(triso_layer: TrisoPebbleLayerMaterial, gamma_fast_neutron_fluence: float) -> float: ...
def get_d1_for_kr(triso_layer: TrisoPebbleLayerMaterial, temperature: float) -> float: ...
def get_d1_for_sr(triso_layer: TrisoPebbleLayerMaterial) -> float: ...
def get_d2_for_cs(triso_layer: TrisoPebbleLayerMaterial) -> float: ...
def get_d2_for_kr(triso_layer: TrisoPebbleLayerMaterial, temperature: float) -> float: ...
def get_d2_for_sr(triso_layer: TrisoPebbleLayerMaterial) -> float: ...
def get_q1_for_ag(triso_layer: TrisoPebbleLayerMaterial) -> float: ...
def get_q1_for_cs(triso_layer: TrisoPebbleLayerMaterial) -> float: ...
def get_q1_for_kr(triso_layer: TrisoPebbleLayerMaterial, temperature: float) -> float: ...
def get_q1_for_sr(triso_layer: TrisoPebbleLayerMaterial) -> float: ...
def get_q2_for_cs(triso_layer: TrisoPebbleLayerMaterial) -> float: ...
def get_q2_for_kr(triso_layer: TrisoPebbleLayerMaterial, temperature: float) -> float: ...
def get_q2_for_sr(triso_layer: TrisoPebbleLayerMaterial) -> float: ...
def expected_collisions_atomic_jumps(medium_temperature: float, particle_mass: float, mean_free_path: float, t: float) -> float: ...
def mean_speed(medium_temperature: float, particle_mass: float) -> float: ...
def sample_event_time(rate: float, u: float) -> float: ...
def activity_from_atom_count(count: float, decay_constant: float) -> float: ...
def atom_count_from_activity(activity: float, decay_constant: float) -> float: ...
def base_activities(element_group: ElementGroup, decay_constant: float, time: float, graphite_thickness: float, graphite_diffusion_coefficient: float, release_rate: float) -> SourceAndGraphite: ...
def becquerels_from_curies(curies: float) -> float: ...
def circulating(source_rate: float, k_plate: float, decay_constant: float, time: float, k_clean: float, circulating_parent: float) -> float: ...
def circulating_steadystate(source_rate: float, k_plate: float, decay_constant: float, k_clean: float, circulating_parent: float) -> float: ...
def clean_up(k_plate: float, source_rate: float, decay_constant: float, time: float, circulating: float, k_clean: float, clean_up_parent: float) -> float: ...
def clean_up_steadystate(k_plate: float, source_rate: float, decay_constant: float, k_clean: float, clean_up_parent: float) -> float: ...
def curies_from_becquerels(activity: float) -> float: ...
def diffusion_coefficient(z: int, kernel_temperature: float, graphite_temperature: float) -> KernelGraphiteDiffusion: ...
def diffusion_coefficient_sic_ag(sic_temperature: float) -> float: ...
def find_nuclide(name: str) -> TrisoAtopsNuclide | None: ...
def integrate_diffusion_over_time(z: int, times: list[float], temperatures: list[float], material: DiffusionMaterial) -> list[float]: ...
def normal_operation_node(nuclide: TrisoAtopsNuclide, short_lived: bool, inventory: float, fractions: FailureFractions, plant: PlantConstants, node: NodeState, hps_enabled: bool, parent: ParentPools) -> NodalActivities: ...
def plate_out(k_plate: float, source_rate: float, decay_constant: float, time: float, circulating: float, k_clean: float, plate_out_parent: float) -> float: ...
def plate_out_steadystate(k_plate: float, source_rate: float, decay_constant: float, k_clean: float, plate_out_parent: float) -> float: ...
def rb_fail(z: int, short_lived: bool, decay_constant: float, temperature: float, irradiation_time: float, grain_size: float, sic_thickness: float, kernel_radius: float, kernel_diffusion_coefficient: float) -> float: ...
def release_fraction_transient(z: int, element_group: ElementGroup, integrated_d: float, primary_thickness: float, secondary_thickness: float | None, material: ReleaseMaterial) -> float: ...
def release_rate(rb_fail: float, element_group: ElementGroup, fractions: FailureFractions, inventory: float, short_lived: bool, time: float, decay_constant: float) -> float: ...
def supported_nuclides() -> list[TrisoAtopsNuclide]: ...
def attenuation_factor(graphite_diffusion_coefficient: float, time: float, graphite_thickness: float) -> float: ...
def booth_longlived(diffusion_coefficient: float, time: float, equivalent_sphere_radius: float) -> float: ...
def booth_shortlived_fast_diffuse(diffusion_coefficient: float, decay_constant: float, equivalent_sphere_radius: float) -> float: ...
def breakthrough_model(diffusion_coefficient: float, time: float, layer_thickness: float, kernel_radius: float) -> float: ...
def rb_fail_noble_gases(z: int, decay_constant: float, temperature: float) -> float: ...
def booth_transient(integrated_d_prime: float) -> float: ...
def breakthrough_model_transient(integrated_d_prime: float, integrated_d: float, layer_thickness: float, kernel_radius: float) -> float: ...
def rf_graph(integrated_d: float, graphite_thickness: float) -> float: ...
BQ_PER_CI: float
TRISO_ATOPS_NUCLIDE_COUNT: int
OTHER_ATTENUATION_FACTOR: float
GAS_CONSTANT_J_PER_MOL_K: float
OTHER_METAL_RB_FAIL: float
ATTENUATION_FACTOR_CAP: float
ATTENUATION_SERIES_TERMS: int
BOOTH_SERIES_TERMS: int
BREAKTHROUGH_SERIES_TERMS: int
BOOTH_TRANSIENT_ZERO_FLOOR: float
RF_GRAPH_SERIES_TERMS: int
