"""Type stubs for `outram_park.chem_eng_real_time_process_control_simulator`, generated from the Rust API.

Physical quantities cross this boundary as `float` in SI base units.
"""

class AnalogController:
    @staticmethod
    def new_pi_controller(controller_gain: float, integral_time: float) -> AnalogController: ...
    @staticmethod
    def new_filtered_pid_controller(controller_gain: float, integral_time: float, derivative_time: float, alpha: float) -> AnalogController: ...
    @staticmethod
    def new_filtered_pd_controller(controller_gain: float, derivative_time: float, alpha: float) -> AnalogController: ...
    @staticmethod
    def PIDFiltered(a0: ProportionalController, a1: IntegralController, a2: FilteredDerivativeController) -> AnalogController: ...
    @staticmethod
    def PI(a0: ProportionalController, a1: IntegralController) -> AnalogController: ...
    @staticmethod
    def P(a0: ProportionalController) -> AnalogController: ...
    @staticmethod
    def PDFiltered(a0: ProportionalController, a1: FilteredDerivativeController) -> AnalogController: ...
    @staticmethod
    def IntegralStandalone(a0: IntegralController) -> AnalogController: ...
    @staticmethod
    def DerivativeFilteredStandalone(a0: FilteredDerivativeController) -> AnalogController: ...
    def variant(self) -> str: ...

class FilteredDerivativeController:
    transfer_fn: TransferFnFirstOrder
    def __init__(self, controller_gain: float, derivative_time: float, alpha: float) -> None: ...
    @staticmethod
    def default() -> FilteredDerivativeController: ...

class IntegralController:
    def __init__(self, controller_gain: float, integral_time: float) -> None: ...
    @staticmethod
    def default() -> IntegralController: ...

class ProportionalController:
    transfer_fn: TransferFnFirstOrder
    def __init__(self, controller_gain: float) -> None: ...
    @staticmethod
    def default() -> ProportionalController: ...

class RampResponse:
    def __init__(self, gradient_gain: float, start_time: float, user_input: float, current_time: float) -> None: ...
    def calculate_response(self, simulation_time: float) -> float: ...
    def is_started_for_1s(self) -> bool: ...
    @staticmethod
    def default() -> RampResponse: ...

class RampResponseRealTime:
    def __init__(self, integral_time: float, controller_gain: float) -> None: ...
    def set_user_input_and_calc(self, user_input: float, time_of_input: float) -> float: ...
    @staticmethod
    def default() -> RampResponseRealTime: ...

class ChemEngProcessControlSimulatorError:
    @staticmethod
    def GenericStringError(a0: str) -> ChemEngProcessControlSimulatorError: ...
    @staticmethod
    def UnstableDampingFactorForStableTransferFunction() -> ChemEngProcessControlSimulatorError: ...
    @staticmethod
    def WrongTransferFnType() -> ChemEngProcessControlSimulatorError: ...
    def variant(self) -> str: ...

class TransferFn:
    @staticmethod
    def FirstOrder(a0: TransferFnFirstOrder) -> TransferFn: ...
    @staticmethod
    def SecondOrder(a0: TransferFnSecondOrder) -> TransferFn: ...
    def variant(self) -> str: ...
    @staticmethod
    def default() -> TransferFn: ...

class TransferFnFirstOrder:
    def __init__(self, a1: float, b1: float, a2: float, b2: float) -> None: ...
    @staticmethod
    def Unstable() -> TransferFnFirstOrder: ...
    @staticmethod
    def ConstantValueUndamped() -> TransferFnFirstOrder: ...
    def variant(self) -> str: ...
    @staticmethod
    def default() -> TransferFnFirstOrder: ...

class TransferFnSecondOrder:
    @staticmethod
    def Unstable() -> TransferFnSecondOrder: ...
    @staticmethod
    def Undamped() -> TransferFnSecondOrder: ...
    def variant(self) -> str: ...
    @staticmethod
    def default() -> TransferFnSecondOrder: ...

class errors_ChemEngProcessControlSimulatorError:
    @staticmethod
    def GenericStringError(a0: str) -> errors_ChemEngProcessControlSimulatorError: ...
    @staticmethod
    def UnstableDampingFactorForStableTransferFunction() -> errors_ChemEngProcessControlSimulatorError: ...
    @staticmethod
    def WrongTransferFnType() -> errors_ChemEngProcessControlSimulatorError: ...
    def variant(self) -> str: ...

class transfer_fn_wrapper_and_enums_TransferFn:
    @staticmethod
    def FirstOrder(a0: transfer_fn_wrapper_and_enums_TransferFnFirstOrder) -> transfer_fn_wrapper_and_enums_TransferFn: ...
    @staticmethod
    def SecondOrder(a0: transfer_fn_wrapper_and_enums_TransferFnSecondOrder) -> transfer_fn_wrapper_and_enums_TransferFn: ...
    def variant(self) -> str: ...
    @staticmethod
    def default() -> transfer_fn_wrapper_and_enums_TransferFn: ...

class transfer_fn_wrapper_and_enums_TransferFnFirstOrder:
    def __init__(self, a1: float, b1: float, a2: float, b2: float) -> None: ...
    @staticmethod
    def Unstable() -> transfer_fn_wrapper_and_enums_TransferFnFirstOrder: ...
    @staticmethod
    def ConstantValueUndamped() -> transfer_fn_wrapper_and_enums_TransferFnFirstOrder: ...
    def variant(self) -> str: ...
    @staticmethod
    def default() -> transfer_fn_wrapper_and_enums_TransferFnFirstOrder: ...

class transfer_fn_wrapper_and_enums_TransferFnSecondOrder:
    @staticmethod
    def StableCriticallydamped() -> transfer_fn_wrapper_and_enums_TransferFnSecondOrder: ...
    @staticmethod
    def StableOverdamped() -> transfer_fn_wrapper_and_enums_TransferFnSecondOrder: ...
    @staticmethod
    def Unstable() -> transfer_fn_wrapper_and_enums_TransferFnSecondOrder: ...
    @staticmethod
    def Undamped() -> transfer_fn_wrapper_and_enums_TransferFnSecondOrder: ...
    def variant(self) -> str: ...
    @staticmethod
    def default() -> transfer_fn_wrapper_and_enums_TransferFnSecondOrder: ...

class C2dMethod:
    @staticmethod
    def Zoh() -> C2dMethod: ...
    @staticmethod
    def Tustin() -> C2dMethod: ...
    @staticmethod
    def TustinPrewarp(prewarp_frequency: float) -> C2dMethod: ...
    @staticmethod
    def MatchedPoleZero() -> C2dMethod: ...
    def variant(self) -> str: ...

class ContinuousTransferFn:
    def __init__(self, num: list[float], den: list[float]) -> None: ...
    @staticmethod
    def first_order(process_gain: float, process_time: float) -> ContinuousTransferFn: ...
    @staticmethod
    def second_order(process_gain: float, process_time: float, damping_ratio: float) -> ContinuousTransferFn: ...
    def numerator_ascending_s(self) -> list[float]: ...
    def denominator_ascending_s(self) -> list[float]: ...
    def order(self) -> int: ...
    def steady_state_gain(self) -> float: ...
    def to_discrete(self, sample_time: float, method: C2dMethod) -> DiscreteTransferFn: ...

class D2cMethod:
    @staticmethod
    def Tustin() -> D2cMethod: ...
    @staticmethod
    def TustinPrewarp(prewarp_frequency: float) -> D2cMethod: ...
    @staticmethod
    def MatchedPoleZero() -> D2cMethod: ...
    def variant(self) -> str: ...

class DiscreteTransferFn:
    @staticmethod
    def from_z_inverse_coefficients(num: list[float], den: list[float], sample_time: float) -> DiscreteTransferFn: ...
    @staticmethod
    def from_z_descending_coefficients(num_descending_z: list[float], den_descending_z: list[float], sample_time: float) -> DiscreteTransferFn: ...
    def advance_one_sample(self, input: float) -> float: ...
    def reset(self) -> None: ...
    def numerator_z_inverse(self) -> list[float]: ...
    def denominator_z_inverse(self) -> list[float]: ...
    def sample_time(self) -> float: ...
    def state_size(self) -> int: ...
    def to_continuous(self, method: D2cMethod) -> ContinuousTransferFn: ...

class ZDomainError:
    @staticmethod
    def ZeroDenominator() -> ZDomainError: ...
    @staticmethod
    def NonPositiveTimeConstant() -> ZDomainError: ...
    @staticmethod
    def NonPositiveDampingRatio() -> ZDomainError: ...
    @staticmethod
    def NonPositiveSampleTime() -> ZDomainError: ...
    @staticmethod
    def AcausalSystem() -> ZDomainError: ...
    @staticmethod
    def UnsupportedOrder(order: int) -> ZDomainError: ...
    @staticmethod
    def ImproperTransferFunction() -> ZDomainError: ...
    @staticmethod
    def MatchedPoleZeroAtOrigin() -> ZDomainError: ...
    @staticmethod
    def NonFinitePoleOrZero() -> ZDomainError: ...
    @staticmethod
    def InvalidPrewarpFrequency() -> ZDomainError: ...
    def variant(self) -> str: ...
