"""Type stubs for `outram_park.kovan_codegen`, generated from the Rust API.

Physical quantities cross this boundary as `float` in SI base units.
"""

class CodegenError:
    def variant(self) -> str: ...

class LinearSolver:
    @staticmethod
    def Jacobi() -> LinearSolver: ...
    @staticmethod
    def GaussSeidel() -> LinearSolver: ...
    @staticmethod
    def Sor() -> LinearSolver: ...
    @staticmethod
    def ConjugateGradient() -> LinearSolver: ...
    @staticmethod
    def BiCgStab() -> LinearSolver: ...
    @staticmethod
    def Gmres() -> LinearSolver: ...
    @staticmethod
    def Lu() -> LinearSolver: ...
    @staticmethod
    def Qr() -> LinearSolver: ...
    @staticmethod
    def Cholesky() -> LinearSolver: ...
    def variant(self) -> str: ...

class Method:
    @staticmethod
    def Root(a0: RootFinder) -> Method: ...
    @staticmethod
    def Linear(a0: LinearSolver) -> Method: ...
    @staticmethod
    def Nonlinear(a0: NonlinearSolver) -> Method: ...
    @staticmethod
    def Ode(a0: OdeSolver) -> Method: ...
    @staticmethod
    def Pde(a0: PdeScheme) -> Method: ...
    def variant(self) -> str: ...

class NonlinearSolver:
    @staticmethod
    def Newton() -> NonlinearSolver: ...
    @staticmethod
    def QuasiNewton() -> NonlinearSolver: ...
    @staticmethod
    def Broyden() -> NonlinearSolver: ...
    @staticmethod
    def TrustRegion() -> NonlinearSolver: ...
    def variant(self) -> str: ...

class OdeSolver:
    @staticmethod
    def Euler() -> OdeSolver: ...
    @staticmethod
    def Rk2() -> OdeSolver: ...
    @staticmethod
    def Rk4() -> OdeSolver: ...
    @staticmethod
    def DormandPrince() -> OdeSolver: ...
    @staticmethod
    def BackwardEuler() -> OdeSolver: ...
    @staticmethod
    def CrankNicolson() -> OdeSolver: ...
    def variant(self) -> str: ...

class PdeScheme:
    @staticmethod
    def Poisson1dFiniteDifference() -> PdeScheme: ...
    @staticmethod
    def Diffusion1dFiniteVolume() -> PdeScheme: ...
    @staticmethod
    def BoundaryConditionScaffold() -> PdeScheme: ...
    def variant(self) -> str: ...

class RootFinder:
    @staticmethod
    def Bisection() -> RootFinder: ...
    @staticmethod
    def RegulaFalsi() -> RootFinder: ...
    @staticmethod
    def Illinois() -> RootFinder: ...
    @staticmethod
    def Pegasus() -> RootFinder: ...
    @staticmethod
    def Secant() -> RootFinder: ...
    @staticmethod
    def NewtonRaphson() -> RootFinder: ...
    @staticmethod
    def Brent() -> RootFinder: ...
    def variant(self) -> str: ...

class MacroKind:
    @staticmethod
    def Declarative() -> MacroKind: ...
    @staticmethod
    def Derive() -> MacroKind: ...
    @staticmethod
    def Attribute() -> MacroKind: ...
    @staticmethod
    def Procedural() -> MacroKind: ...
    @staticmethod
    def BuildRs() -> MacroKind: ...
    def variant(self) -> str: ...

class EngineeringPattern:
    @staticmethod
    def RmsResidualNorm() -> EngineeringPattern: ...
    @staticmethod
    def UnderRelaxationUpdate() -> EngineeringPattern: ...
    @staticmethod
    def RelativeChange() -> EngineeringPattern: ...
    def variant(self) -> str: ...

def generate(method: Method) -> str: ...
def generate_artifact(method: Method, correlation_id: str | None, source_document_id: str | None) -> kovan_common.GeneratedArtifact: ...
def generate(method: LinearSolver) -> str: ...
def lu_solve(a: list[list[float]], b: list[float]) -> list[float] | None: ...
def generate_macro_scaffold(kind: MacroKind) -> str: ...
def generate(method: NonlinearSolver) -> str: ...
def generate_fixed_point() -> str: ...
def generate(method: OdeSolver) -> str: ...
def generate(pattern: EngineeringPattern) -> str: ...
def relative_change(new: float, old: float, floor: float) -> float: ...
def rms_residual_norm(residual: list[float]) -> float: ...
def under_relaxation_update(x_old: float, x_star: float, alpha: float) -> float: ...
def generate(scheme: PdeScheme) -> str: ...
def generate(method: RootFinder) -> str: ...
