"""Type stubs for `outram_park.kovan_semantics`, generated from the Rust API.

Physical quantities cross this boundary as `float` in SI base units.
"""

class Applicability:
    assumptions: list[str]
    validity_ranges: list[str]
    def __init__(self, ) -> None: ...
    def with_assumption(self, assumption: str) -> Applicability: ...
    def with_validity_range(self, range: str) -> Applicability: ...
    @staticmethod
    def default() -> Applicability: ...

class BundleReport:
    included: list[str]
    indexed: list[str]
    missing_api_docs: list[str]
    def total_bytes(self) -> int: ...
    def core_bytes(self) -> int: ...
    def core_estimated_tokens(self) -> int: ...
    def optional_files(self) -> list[tuple[str, int]]: ...
    def total_estimated_tokens(self) -> int: ...
    def exceeds_budget(self, budget_tokens: int) -> bool: ...
    def __init__(self) -> None: ...
    @staticmethod
    def default() -> BundleReport: ...

class Concept:
    id: str
    name: str
    aliases: list[str]
    origin: Origin
    def __init__(self, id: str, name: str, aliases: list[str], origin: Origin) -> None: ...

class ConceptEdge:
    source: str
    relation: Relation
    target: str
    status: RelationStatus
    detail: EdgeDetail
    def __init__(self, source: str, relation: Relation, target: str, status: RelationStatus, detail: EdgeDetail) -> None: ...

class ConceptGraph:
    def __init__(self, ) -> None: ...
    def relate(self, source: str, relation: Relation, target: str) -> None: ...
    def relate_with(self, source: str, relation: Relation, target: str, status: RelationStatus, detail: EdgeDetail) -> None: ...
    def concept(self, id: str) -> Concept | None: ...
    def edges(self) -> list[ConceptEdge]: ...
    def outgoing(self, id: str, relation: Relation | None) -> list[ConceptEdge]: ...
    def incoming(self, id: str, relation: Relation | None) -> list[ConceptEdge]: ...
    def len(self) -> int: ...
    def is_empty(self) -> bool: ...
    @staticmethod
    def default() -> ConceptGraph: ...

class CrateEntry:
    directory: str
    package: str
    api_md: str | None
    api_bytes: int
    def has_api_docs(self) -> bool: ...
    def bundle_filename(self) -> str: ...
    def index_filename(self) -> str: ...
    def __init__(self, directory: str, package: str, api_md: str | None, api_bytes: int) -> None: ...

class EdgeDetail:
    @staticmethod
    def None_() -> EdgeDetail: ...
    @staticmethod
    def Applicability(a0: Applicability) -> EdgeDetail: ...
    @staticmethod
    def Verification(a0: VerificationRecord) -> EdgeDetail: ...
    def variant(self) -> str: ...
    @staticmethod
    def default() -> EdgeDetail: ...

class ExtractedSymbol:
    name: str
    qualified_name: str
    kind: SymbolKind
    language: LanguageAdapter
    file: str
    line: int
    def into_kovan_symbol(self, repository_id: str) -> kovan_common.KovanSymbol: ...
    def __init__(self, name: str, qualified_name: str, kind: SymbolKind, language: LanguageAdapter, file: str, line: int) -> None: ...

class LanguageAdapter:
    def preferred_tool(self) -> str: ...
    def extensions(self) -> list[str]: ...
    def rough_definition_pattern(self) -> str: ...
    def file_kind(self) -> kovan_discovery.FileKind: ...
    def server_binary(self) -> str: ...
    @staticmethod
    def Rust() -> LanguageAdapter: ...
    @staticmethod
    def Cpp() -> LanguageAdapter: ...
    @staticmethod
    def Python() -> LanguageAdapter: ...
    @staticmethod
    def Fortran() -> LanguageAdapter: ...
    def variant(self) -> str: ...

class Neutronics:
    @staticmethod
    def Transport() -> Neutronics: ...
    @staticmethod
    def Diffusion() -> Neutronics: ...
    def variant(self) -> str: ...

class OntologyError:
    @staticmethod
    def UnknownConcept(a0: str) -> OntologyError: ...
    @staticmethod
    def DuplicateConcept(a0: str) -> OntologyError: ...
    def variant(self) -> str: ...

class Origin:
    @staticmethod
    def Core() -> Origin: ...
    @staticmethod
    def User() -> Origin: ...
    @staticmethod
    def Literature() -> Origin: ...
    def variant(self) -> str: ...

class Reactor:
    @staticmethod
    def NuclearReactor() -> Reactor: ...
    @staticmethod
    def GasCooledReactor() -> Reactor: ...
    @staticmethod
    def Htgr() -> Reactor: ...
    @staticmethod
    def Vhtr() -> Reactor: ...
    @staticmethod
    def Fhr() -> Reactor: ...
    @staticmethod
    def Msr() -> Reactor: ...
    def variant(self) -> str: ...

class Relation:
    def label(self) -> str: ...
    def is_approximation_family(self) -> bool: ...
    def is_verification_family(self) -> bool: ...
    @staticmethod
    def SpecializationOf() -> Relation: ...
    @staticmethod
    def DerivedFrom() -> Relation: ...
    @staticmethod
    def ApproximationOf() -> Relation: ...
    @staticmethod
    def Simplifies() -> Relation: ...
    @staticmethod
    def ReducedFrom() -> Relation: ...
    @staticmethod
    def SurrogateOf() -> Relation: ...
    @staticmethod
    def Represents() -> Relation: ...
    @staticmethod
    def ParameterizedBy() -> Relation: ...
    @staticmethod
    def CoupledWith() -> Relation: ...
    @staticmethod
    def Employs() -> Relation: ...
    @staticmethod
    def DiscretizedBy() -> Relation: ...
    @staticmethod
    def SolvedBy() -> Relation: ...
    @staticmethod
    def GeneratesData() -> Relation: ...
    @staticmethod
    def IdentifiedFrom() -> Relation: ...
    @staticmethod
    def ImplementedBy() -> Relation: ...
    @staticmethod
    def BenchmarkOf() -> Relation: ...
    @staticmethod
    def VerifiedAgainst() -> Relation: ...
    @staticmethod
    def ValidatedAgainst() -> Relation: ...
    @staticmethod
    def ComparedWith() -> Relation: ...
    @staticmethod
    def SupportedBy() -> Relation: ...
    @staticmethod
    def Contradicts() -> Relation: ...
    def variant(self) -> str: ...

class RelationStatus:
    @staticmethod
    def Established() -> RelationStatus: ...
    @staticmethod
    def Provisional() -> RelationStatus: ...
    def variant(self) -> str: ...

class SemanticsError:
    @staticmethod
    def Tool(a0: str) -> SemanticsError: ...
    def variant(self) -> str: ...

class SymbolKind:
    def as_str(self) -> str: ...
    @staticmethod
    def Function() -> SymbolKind: ...
    @staticmethod
    def Subroutine() -> SymbolKind: ...
    @staticmethod
    def Struct() -> SymbolKind: ...
    @staticmethod
    def Enum() -> SymbolKind: ...
    @staticmethod
    def Trait() -> SymbolKind: ...
    @staticmethod
    def Impl() -> SymbolKind: ...
    @staticmethod
    def Type() -> SymbolKind: ...
    @staticmethod
    def Union() -> SymbolKind: ...
    @staticmethod
    def Class() -> SymbolKind: ...
    @staticmethod
    def Namespace() -> SymbolKind: ...
    @staticmethod
    def Module() -> SymbolKind: ...
    def variant(self) -> str: ...

class ThermalHydraulics:
    @staticmethod
    def ConservationMass() -> ThermalHydraulics: ...
    @staticmethod
    def ConservationMomentum() -> ThermalHydraulics: ...
    @staticmethod
    def ConservationEnergy() -> ThermalHydraulics: ...
    @staticmethod
    def NaturalCirculation() -> ThermalHydraulics: ...
    @staticmethod
    def Boussinesq() -> ThermalHydraulics: ...
    def variant(self) -> str: ...

class VerificationRecord:
    benchmark: str
    result: str | None
    acceptance_criterion: str | None
    def __init__(self, benchmark: str) -> None: ...
    def with_result(self, result: str) -> VerificationRecord: ...
    def with_acceptance_criterion(self, criterion: str) -> VerificationRecord: ...

def condense_api_markdown(body: str) -> str: ...
def agents_markdown(report: BundleReport) -> str: ...
def catalogue_symbols(repo: str, adapter: LanguageAdapter) -> list[kovan_common.KovanSymbol]: ...
def catalogue_symbols_detailed(repo: str, adapter: LanguageAdapter) -> list[ExtractedSymbol]: ...
def condensed_index_markdown(entries: list[CrateEntry]) -> str: ...
def estimated_tokens(bytes: int) -> int: ...
def extract_from_text(adapter: LanguageAdapter, file: str, text: str) -> list[ExtractedSymbol]: ...
def repository_summary_markdown(repo: kovan_common.KovanRepository, symbols: list[kovan_common.KovanSymbol]) -> str: ...
def rough_definition_scan(repo: str, adapter: LanguageAdapter) -> list[tuple[str, kovan_discovery.SearchMatch]]: ...
def symbols_markdown(repo_name: str, symbols: list[kovan_common.KovanSymbol]) -> str: ...
BYTES_PER_ESTIMATED_TOKEN: int
