"""Type stubs for `outram_park.kovan_discovery`, generated from the Rust API.

Physical quantities cross this boundary as `float` in SI base units.
"""

class DiscoveryError:
    @staticmethod
    def BadPattern(a0: str) -> DiscoveryError: ...
    def variant(self) -> str: ...

class FileKind:
    def extensions(self) -> list[str]: ...
    @staticmethod
    def Source() -> FileKind: ...
    @staticmethod
    def Markdown() -> FileKind: ...
    @staticmethod
    def Pdf() -> FileKind: ...
    @staticmethod
    def Metadata() -> FileKind: ...
    def variant(self) -> str: ...

class SearchMatch:
    line: int
    column: int
    text: str
    def __init__(self, line: int, column: int, text: str) -> None: ...

class BackendKind:
    @staticmethod
    def Library() -> BackendKind: ...
    @staticmethod
    def Binary() -> BackendKind: ...
    def variant(self) -> str: ...

class CommitInfo:
    id: str
    short_id: str
    summary: str
    author_name: str
    author_email: str
    committed_unix_seconds: int
    def __init__(self, id: str, short_id: str, summary: str, author_name: str, author_email: str, committed_unix_seconds: int) -> None: ...

class GitError:
    @staticmethod
    def NotARepository(a0: str) -> GitError: ...
    @staticmethod
    def Open(a0: str) -> GitError: ...
    @staticmethod
    def UnbornHead() -> GitError: ...
    @staticmethod
    def Backend(a0: str) -> GitError: ...
    @staticmethod
    def BinaryUnavailableOnTarget() -> GitError: ...
    @staticmethod
    def BinaryFailed(a0: str) -> GitError: ...
    def variant(self) -> str: ...

class GixCliBackend:
    def __init__(self, root: str) -> None: ...
    @staticmethod
    def with_program(root: str, program: str) -> GixCliBackend: ...
    def is_available(self) -> bool: ...
    def version(self) -> str: ...

class HeadInfo:
    branch: str | None
    detached: bool
    commit: CommitInfo
    def __init__(self, branch: str | None, detached: bool, commit: CommitInfo) -> None: ...

def discover_kind(root: str, kind: FileKind) -> list[str]: ...
def search_file(path: str, pattern: str) -> list[SearchMatch]: ...
def search_repository(root: str, kind: FileKind, pattern: str) -> list[tuple[str, SearchMatch]]: ...
