"""Type stubs for `outram_park.kovan_metrics`, generated from the Rust API.

Physical quantities cross this boundary as `float` in SI base units.
"""

class Date:
    year: int
    month: int
    day: int
    def __init__(self, year: int, month: int, day: int) -> None: ...
    @staticmethod
    def parse_ddmmyy(s: str) -> Date: ...
    def iso(self) -> str: ...
    def ddmmyy(self) -> str: ...
    def human(self) -> str: ...
    def to_epoch_days(self) -> int: ...
    @staticmethod
    def from_epoch_days(days: int) -> Date: ...
    @staticmethod
    def today() -> Date: ...

class DateError:
    @staticmethod
    def NotSixDigits(a0: str) -> DateError: ...
    @staticmethod
    def NotACalendarDate(a0: int, a1: int, a2: int) -> DateError: ...
    def variant(self) -> str: ...

class CommitRecord:
    short: str
    date: str
    subject: str
    body: str
    def __init__(self, short: str, date: str, subject: str, body: str) -> None: ...

class NumStat:
    added: int
    removed: int
    rs_added: int
    rs_removed: int
    per_crate_added: list[tuple[str, int]]
    def __init__(self, added: int, removed: int, rs_added: int, rs_removed: int, per_crate_added: list[tuple[str, int]]) -> None: ...
    @staticmethod
    def default() -> NumStat: ...

class AgenticSummary:
    missing: bool
    n_crates: int
    unclassified: list[str]
    stale: list[str]
    total_rust_code: int
    agentic_total: int
    active_days: int
    head: str
    reference: str
    def rate(self) -> float | None: ...
    def subtotal(self, class_: Provenance) -> int: ...
    @staticmethod
    def default() -> AgenticSummary: ...

class BaselineTotals:
    lines: LineCount
    first: str
    last: str
    tuas_net: TuasNet | None
    missing: list[str]
    def active_days(self) -> int: ...
    def rate(self) -> float | None: ...
    def as_of(self) -> str: ...
    @staticmethod
    def default() -> BaselineTotals: ...

class CrateStats:
    name: str
    display: str
    upstream: str | None
    total_lines: int
    code_lines: int
    raw_code_lines: int
    baseline_code_lines: int
    description: str

class LineCount:
    total: int
    code: int
    files: int
    def add_file(self, contents: str) -> None: ...
    def merge(self, other: LineCount) -> LineCount: ...
    def __init__(self, total: int, code: int, files: int) -> None: ...
    @staticmethod
    def default() -> LineCount: ...

class Options:
    out_dir: str
    search_dirs: list[str]
    vendor_dir: str
    github_only: bool
    check: bool
    figure: bool
    def __init__(self, out_dir: str) -> None: ...

class Outcome:
    report: str
    written: list[str]
    missing: list[str]
    def __init__(self, report: str, written: list[str], missing: list[str]) -> None: ...

class Provenance:
    def key(self) -> str: ...
    def label(self) -> str: ...
    def tex_section(self) -> str: ...
    def tex_subtotal(self) -> str: ...
    @staticmethod
    def Translated() -> Provenance: ...
    @staticmethod
    def Original() -> Provenance: ...
    @staticmethod
    def Extension() -> Provenance: ...
    def variant(self) -> str: ...

class RepoStats:
    key: str
    label: str
    note: str
    marker: str
    cite: str
    path: str | None
    lines: LineCount
    head_lines: LineCount
    first: str
    last: str
    reference: str
    missing: bool
    def rate(self) -> float | None: ...
    @staticmethod
    def default() -> RepoStats: ...

class RepoSpec:
    key: str
    label: str
    note: str
    marker: str
    cite: str
    measure_ref: str | None

class TuasNet:
    head: LineCount
    imported: LineCount
    net: LineCount
    abandoned_code: int
    def __init__(self, head: LineCount, imported: LineCount, net: LineCount, abandoned_code: int) -> None: ...
    @staticmethod
    def default() -> TuasNet: ...

class QueryResult:
    branch: str
    to: Date | None
    commits_total: int
    commits_with_data: int
    totals: TokenCounts
    grand_total: int
    rows: list[QueryRow]
    def to_json(self, per_commit: bool) -> str: ...
    def print(self, per_commit: bool) -> None: ...

class QueryRow:
    date: str
    commit: str
    subject: str
    total: int | None
    def __init__(self, date: str, commit: str, subject: str, total: int | None) -> None: ...

class ParsedTrailer:
    counts: TokenCounts
    total: int
    source: str
    def has_data(self) -> bool: ...
    def __init__(self, counts: TokenCounts, total: int, source: str) -> None: ...

class TokenCounts:
    input: int
    output: int
    cache_read: int
    cache_write: int
    def total(self) -> int: ...
    def add(self, other: TokenCounts) -> None: ...
    def saturating_sub(self, baseline: TokenCounts) -> TokenCounts: ...
    def __init__(self, input: int, output: int, cache_read: int, cache_write: int) -> None: ...
    @staticmethod
    def default() -> TokenCounts: ...

class Cumulative:
    counts: TokenCounts
    records: int
    source: Source
    def __init__(self, counts: TokenCounts, records: int, source: Source) -> None: ...
    @staticmethod
    def default() -> Cumulative: ...

class Source:
    def as_str(self) -> str: ...
    @staticmethod
    def SessionTranscript() -> Source: ...
    @staticmethod
    def None_() -> Source: ...
    def variant(self) -> str: ...

def load() -> TokenCounts | None: ...
def path() -> str: ...
def save(counts: TokenCounts, records: int) -> None: ...
def git_dir() -> str: ...
def numstat(sha: str) -> NumStat: ...
def parse_records(raw: str) -> list[CommitRecord]: ...
def record_format() -> str: ...
def ref_for_branch(branch: str) -> str: ...
def repo_root() -> str: ...
def default_output_path(root: str, from_: Date | None, to: Date | None, base: str) -> str: ...
def generate(from_: Date | None, to: Date | None, branch: str, base: str, outfile: str | None) -> tuple[str, int]: ...
def all_repo_keys() -> list[str]: ...
def provenance_of(crate_name: str) -> tuple[Provenance, str | None] | None: ...
def productivity_svg(base_stats: list[RepoStats], base_totals: BaselineTotals, agentic: AgenticSummary) -> str: ...
def find_repo(options: Options, key: str) -> str | None: ...
def agentic_csv(crate_rows: list[CrateStats]) -> str: ...
def agentic_table_tex(crate_rows: list[CrateStats], agentic: AgenticSummary) -> str: ...
def baseline_csv(base_stats: list[RepoStats]) -> str: ...
def baseline_table_tex(base_stats: list[RepoStats], base_totals: BaselineTotals) -> str: ...
def rate_table_tex(base_stats: list[RepoStats], base_totals: BaselineTotals, agentic: AgenticSummary) -> str: ...
def tex_month(date: str) -> str: ...
def tex_name(crate_name: str) -> str: ...
def tex_num(n: int) -> str: ...
def head_date(repo: str, reference: str) -> str: ...
def list_dir(repo: str, reference: str, path: str) -> list[str]: ...
def read_blob(repo: str, reference: str, path: str) -> str | None: ...
def ref_exists(repo: str, reference: str) -> bool: ...
def rust_files_at(repo: str, reference: str, prefix: str) -> list[str]: ...
def select_ref(repo: str) -> str: ...
def repo_url(key: str) -> str: ...
def report(base_stats: list[RepoStats], base_totals: BaselineTotals, crate_rows: list[CrateStats], agentic: AgenticSummary, check: bool) -> str: ...
def fmt(n: int) -> str: ...
def is_rust_source(path: str) -> bool: ...
def is_rust_source_path(path: str) -> bool: ...
def is_skipped(path: str) -> bool: ...
def strip_rust_comments(src: str) -> str: ...
def init() -> None: ...
def query(from_: Date | None, to: Date | None, branch: str) -> QueryResult: ...
def record() -> None: ...
def report() -> None: ...
def show() -> None: ...
def stamp_trailer(msgfile: str) -> None: ...
def format(delta: TokenCounts, cumulative: TokenCounts, source: str) -> str: ...
def group(n: int) -> str: ...
def parse(body: str) -> ParsedTrailer | None: ...
def project_transcript_dir(repo_root: str) -> str | None: ...
def read_cumulative(repo_root: str) -> Cumulative: ...
def slug_for_path(path: str) -> str: ...
REPORT_DIR_REL: str
AGENTIC_KEY: str
GITHUB_USER: str
AGENTIC_LABEL: str
AGENTIC_SINCE: str
AGENTIC_UNTIL: str
GENERATED_BY: str
TUAS_IMPORT_REF: str
TUAS_KEY: str
TUAS_PREDECESSOR_KEY: str
LEDGER_REL: str
CUMULATIVE_KEY: str
TRAILER_KEY: str
