"""Type stubs for `outram_park.kovan_literature`, generated from the Rust API.

Physical quantities cross this boundary as `float` in SI base units.
"""

class BibEntry:
    entry_type: str
    cite_key: str

class BibParseError:
    @staticmethod
    def UnterminatedEntry(entry_type: str, near: str) -> BibParseError: ...
    @staticmethod
    def MissingCiteKey(entry_type: str) -> BibParseError: ...
    def variant(self) -> str: ...

class Heading:
    level: int
    text: str
    def __init__(self, level: int, text: str) -> None: ...

class LiteratureError:
    @staticmethod
    def Io(a0: str) -> LiteratureError: ...
    def variant(self) -> str: ...

def extract_assets(pdf: str, out_dir: str) -> list[str]: ...
def extract_metadata(pdf: str) -> kovan_common.KovanDocument: ...
def extract_pdf_text(pdf: str) -> str: ...
def markdown_outline(markdown: str) -> list[Heading]: ...
def parse_bib_entries(input: str) -> list[BibEntry]: ...
def pdf_to_markdown(pdf: str) -> str: ...
def render_entries(entries: list[BibEntry]) -> str: ...
def render_entry(entry: BibEntry) -> str: ...
def split_markdown_by_page_limit(markdown: str, max_pages: int) -> list[str]: ...
def document_type_from_path(path: str) -> kovan_common.DocumentType: ...
def generated_dir_for(base: str, kind: str, visibility: kovan_common.Visibility) -> str: ...
def root_for(base: str, visibility: kovan_common.Visibility) -> str: ...
def visibility_from_path(path: str) -> kovan_common.Visibility: ...
def text_to_markdown(raw: str) -> str: ...
def to_bibtex(doc: kovan_common.KovanDocument) -> str: ...
MAX_MARKDOWN_PAGES: int
PAGE_SEPARATOR: str
ASSETS_DIR: str
BIBTEX_DIR: str
GENERATED_ROOT: str
MARKDOWN_DIR: str
OPEN_ROOT: str
PROPRIETARY_ROOT: str
