"""Type stubs for `outram_park.kovan`, generated from the Rust API.

Physical quantities cross this boundary as `float` in SI base units.
"""

class BranchInfo:
    name: str
    is_current: bool
    def __init__(self, name: str, is_current: bool) -> None: ...

class RemoteError:
    @staticmethod
    def GitUnavailable() -> RemoteError: ...
    @staticmethod
    def Failed(command: str, stderr: str) -> RemoteError: ...
    def variant(self) -> str: ...

class RemoteInfo:
    name: str
    url: str
    def __init__(self, name: str, url: str) -> None: ...

class Artifact:
    heading: str
    level: int
    line: int
    toml: ArtifactToml
    body: str
    def id(self) -> str: ...
    def kind(self) -> ArtifactKind: ...
    def is_reviewed(self) -> bool: ...
    def csv_block(self) -> str | None: ...
    def __init__(self, heading: str, level: int, line: int, toml: ArtifactToml, body: str) -> None: ...

class ArtifactError:
    @staticmethod
    def Malformed(heading: str, line: int, message: str) -> ArtifactError: ...
    @staticmethod
    def BadAnchor(heading: str, line: int, message: str) -> ArtifactError: ...
    def variant(self) -> str: ...

class ArtifactKind:
    @staticmethod
    def Note() -> ArtifactKind: ...
    @staticmethod
    def Annotation() -> ArtifactKind: ...
    @staticmethod
    def SourceReference() -> ArtifactKind: ...
    @staticmethod
    def Formula() -> ArtifactKind: ...
    @staticmethod
    def DigitisedTable() -> ArtifactKind: ...
    @staticmethod
    def DigitisedGraph() -> ArtifactKind: ...
    def variant(self) -> str: ...

class ArtifactMeta:
    id: str
    kind: ArtifactKind
    created: str
    modified: str
    reviewed: str | None
    def __init__(self, id: str, kind: ArtifactKind, created: str, modified: str, reviewed: str | None) -> None: ...

class ArtifactToml:
    kovan: ArtifactMeta
    source: SourceAnchor | None
    classification: Classification
    extraction: Extraction | None
    def __init__(self, kovan: ArtifactMeta, source: SourceAnchor | None, classification: Classification, extraction: Extraction | None) -> None: ...

class Extraction:
    method: str
    engine: str | None
    def __init__(self, method: str, engine: str | None) -> None: ...

class ParsedDocument:
    artifacts: list[Artifact]
    problems: list[ArtifactError]
    def get(self, id: str) -> Artifact | None: ...
    def anchored_to_page(self, page: int) -> list[Artifact]: ...
    def __init__(self, artifacts: list[Artifact] | None = None, problems: list[ArtifactError] | None = None) -> None: ...
    @staticmethod
    def default() -> ParsedDocument: ...

class Region:
    x0: float
    y0: float
    x1: float
    y1: float
    def is_valid(self) -> bool: ...
    def __init__(self, x0: float, y0: float, x1: float, y1: float) -> None: ...

class SourceAnchor:
    page: int | None
    pages: list[int] | None
    region: Region | None
    def validate(self) -> None: ...
    def covers_page(self, page: int) -> bool: ...
    def first_page(self) -> int | None: ...
    def __init__(self) -> None: ...
    @staticmethod
    def default() -> SourceAnchor: ...

class Candidate:
    label: str
    insert_text: str
    detail: str
    def __init__(self, label: str, insert_text: str, detail: str) -> None: ...

class ClassifyError:
    @staticmethod
    def NoUsableId() -> ClassifyError: ...
    @staticmethod
    def UnknownId(a0: str) -> ClassifyError: ...
    @staticmethod
    def BadAnchor(a0: str) -> ClassifyError: ...
    @staticmethod
    def Render(a0: str) -> ClassifyError: ...
    def variant(self) -> str: ...

class KindArg:
    @staticmethod
    def Source() -> KindArg: ...
    @staticmethod
    def Markdown() -> KindArg: ...
    @staticmethod
    def Pdf() -> KindArg: ...
    @staticmethod
    def Metadata() -> KindArg: ...
    def variant(self) -> str: ...

class LangArg:
    def display_name(self) -> str: ...
    @staticmethod
    def Rust() -> LangArg: ...
    @staticmethod
    def Cpp() -> LangArg: ...
    @staticmethod
    def Python() -> LangArg: ...
    @staticmethod
    def Fortran() -> LangArg: ...
    def variant(self) -> str: ...

class Scope:
    @staticmethod
    def Existing() -> Scope: ...
    @staticmethod
    def All() -> Scope: ...
    def variant(self) -> str: ...

class LitCommand:
    @staticmethod
    def Import(pdf: str, json_out: str | None, markdown_out: str | None) -> LitCommand: ...
    @staticmethod
    def Bibtex(input: str) -> LitCommand: ...
    @staticmethod
    def Outline(pdf: str) -> LitCommand: ...
    def variant(self) -> str: ...

class ProjectCommand:
    @staticmethod
    def Regen(root: str) -> ProjectCommand: ...
    def variant(self) -> str: ...

class GenCommand:
    @staticmethod
    def Root(method: RootFinderArg, out: str | None) -> GenCommand: ...
    @staticmethod
    def Linear(method: LinearSolverArg, out: str | None) -> GenCommand: ...
    @staticmethod
    def Nonlinear(method: NonlinearSolverArg, out: str | None) -> GenCommand: ...
    @staticmethod
    def Ode(method: OdeSolverArg, out: str | None) -> GenCommand: ...
    @staticmethod
    def Pde(method: PdeSchemeArg, out: str | None) -> GenCommand: ...
    def variant(self) -> str: ...

class LinearSolverArg:
    @staticmethod
    def Jacobi() -> LinearSolverArg: ...
    @staticmethod
    def GaussSeidel() -> LinearSolverArg: ...
    @staticmethod
    def Sor() -> LinearSolverArg: ...
    @staticmethod
    def ConjugateGradient() -> LinearSolverArg: ...
    @staticmethod
    def BiCgStab() -> LinearSolverArg: ...
    @staticmethod
    def Gmres() -> LinearSolverArg: ...
    @staticmethod
    def Lu() -> LinearSolverArg: ...
    @staticmethod
    def Qr() -> LinearSolverArg: ...
    @staticmethod
    def Cholesky() -> LinearSolverArg: ...
    def variant(self) -> str: ...

class NonlinearSolverArg:
    @staticmethod
    def Newton() -> NonlinearSolverArg: ...
    @staticmethod
    def QuasiNewton() -> NonlinearSolverArg: ...
    @staticmethod
    def Broyden() -> NonlinearSolverArg: ...
    @staticmethod
    def TrustRegion() -> NonlinearSolverArg: ...
    def variant(self) -> str: ...

class OdeSolverArg:
    @staticmethod
    def Euler() -> OdeSolverArg: ...
    @staticmethod
    def Rk2() -> OdeSolverArg: ...
    @staticmethod
    def Rk4() -> OdeSolverArg: ...
    @staticmethod
    def DormandPrince() -> OdeSolverArg: ...
    @staticmethod
    def BackwardEuler() -> OdeSolverArg: ...
    @staticmethod
    def CrankNicolson() -> OdeSolverArg: ...
    def variant(self) -> str: ...

class PdeSchemeArg:
    @staticmethod
    def Poisson1dFiniteDifference() -> PdeSchemeArg: ...
    @staticmethod
    def Diffusion1dFiniteVolume() -> PdeSchemeArg: ...
    @staticmethod
    def BoundaryConditionScaffold() -> PdeSchemeArg: ...
    def variant(self) -> str: ...

class RootFinderArg:
    @staticmethod
    def Bisection() -> RootFinderArg: ...
    @staticmethod
    def RegulaFalsi() -> RootFinderArg: ...
    @staticmethod
    def Illinois() -> RootFinderArg: ...
    @staticmethod
    def Pegasus() -> RootFinderArg: ...
    @staticmethod
    def Secant() -> RootFinderArg: ...
    @staticmethod
    def NewtonRaphson() -> RootFinderArg: ...
    @staticmethod
    def Brent() -> RootFinderArg: ...
    def variant(self) -> str: ...

class Action:
    @staticmethod
    def Skip() -> Action: ...
    @staticmethod
    def Install() -> Action: ...
    def variant(self) -> str: ...

class ToolSpec:
    crate_name: str
    binary_name: str
    description: str

class TokensCommand:
    @staticmethod
    def Trailer(msgfile: str) -> TokensCommand: ...
    @staticmethod
    def Record() -> TokensCommand: ...
    @staticmethod
    def Report() -> TokensCommand: ...
    @staticmethod
    def Init() -> TokensCommand: ...
    @staticmethod
    def Show() -> TokensCommand: ...
    @staticmethod
    def Query(from: str | None, to: str | None, branch: str, per_commit: bool, json: bool) -> TokensCommand: ...
    def variant(self) -> str: ...

class DigitiserError:
    @staticmethod
    def Image(a0: str) -> DigitiserError: ...
    @staticmethod
    def Calibration(a0: str) -> DigitiserError: ...
    @staticmethod
    def Detection(a0: str) -> DigitiserError: ...
    @staticmethod
    def Trace(a0: str) -> DigitiserError: ...
    @staticmethod
    def Io(a0: str) -> DigitiserError: ...
    @staticmethod
    def Ocr(a0: str) -> DigitiserError: ...
    def variant(self) -> str: ...

class AutoDigitiseConfig:
    x: AxisValueSpec
    y: AxisValueSpec
    detect: DetectConfig
    trace: TraceConfig
    def __init__(self, x: AxisValueSpec, y: AxisValueSpec, detect: DetectConfig, trace: TraceConfig) -> None: ...

class AxisPixelRefs:
    @staticmethod
    def FrameEdges(min_value: float, max_value: float) -> AxisPixelRefs: ...
    @staticmethod
    def Explicit(r1: AxisRef, r2: AxisRef) -> AxisPixelRefs: ...
    def variant(self) -> str: ...

class AxisValueSpec:
    scale: AxisScale
    refs: AxisPixelRefs
    def __init__(self, scale: AxisScale, refs: AxisPixelRefs) -> None: ...

class AxisCalibration:
    scale: AxisScale
    r1: AxisRef
    r2: AxisRef
    def __init__(self, scale: AxisScale, r1: AxisRef, r2: AxisRef) -> None: ...
    def value_at(self, pixel: float) -> float: ...
    def pixel_at(self, value: float) -> float | None: ...

class AxisRef:
    pixel: float
    value: float
    def __init__(self, pixel: float, value: float) -> None: ...

class AxisScale:
    @staticmethod
    def Linear() -> AxisScale: ...
    @staticmethod
    def Logarithmic() -> AxisScale: ...
    def variant(self) -> str: ...

class ParallelogramCalibration:
    pixel_corners: list[PixelPoint]
    x_scale: AxisScale
    x_value_at_left: float
    x_value_at_right: float
    y_scale: AxisScale
    y_value_at_top: float
    y_value_at_bottom: float
    def point_at(self, x_px: float, y_px: float) -> tuple[float, float]: ...
    def pixel_at(self, x: float, y: float) -> tuple[float, float] | None: ...

class PixelPoint:
    x: float
    y: float
    def __init__(self, x: float, y: float) -> None: ...

class PlotCalibration:
    def point_at(self, x_px: float, y_px: float) -> tuple[float, float]: ...
    def pixel_at(self, x: float, y: float) -> tuple[float, float] | None: ...
    @staticmethod
    def AxisAligned(x: AxisCalibration, y: AxisCalibration) -> PlotCalibration: ...
    @staticmethod
    def Parallelogram(a0: ParallelogramCalibration) -> PlotCalibration: ...
    def variant(self) -> str: ...

class DigitisedDataset:
    schema_version: int
    source: FigureSource
    calibration: PlotCalibration
    x_label: str
    y_label: str
    digitised_by: str
    digitised_at: str
    trace: TraceRecord | None
    review: ReviewStatus
    points: list[DigitisedPoint]
    @staticmethod
    def from_pixel_trace(source: FigureSource, calibration: PlotCalibration, x_label: str, y_label: str, digitised_by: str, digitised_at: str, trace_record: TraceRecord, trace_points: list[PixelTracePoint]) -> DigitisedDataset: ...
    def to_json_string(self) -> str: ...
    @staticmethod
    def from_json_str(json: str) -> DigitisedDataset: ...
    def write_json(self, path: str) -> None: ...
    @staticmethod
    def read_json(path: str) -> DigitisedDataset: ...
    def to_csv_string(self) -> str: ...
    def write_csv(self, path: str) -> None: ...
    def record_review(self, by: str, at: str, interface: ReviewInterface) -> None: ...
    def __init__(self, schema_version: int, source: FigureSource, calibration: PlotCalibration, x_label: str, y_label: str, digitised_by: str, digitised_at: str, trace: TraceRecord | None, review: ReviewStatus, points: list[DigitisedPoint]) -> None: ...

class DigitisedPoint:
    x: float
    y: float
    x_minus: float
    x_plus: float
    y_minus: float
    y_plus: float
    x_px: float | None
    y_px: float | None
    origin: PointOrigin
    def __init__(self, x: float, y: float, x_minus: float, x_plus: float, y_minus: float, y_plus: float, x_px: float | None, y_px: float | None, origin: PointOrigin) -> None: ...

class FigureSource:
    document_id: str | None
    document_title: str | None
    figure: str
    page: int | None
    image_path: str | None
    image_sha256: str | None
    notes: str | None
    def __init__(self, figure: str) -> None: ...

class PointOrigin:
    @staticmethod
    def AutoTraced() -> PointOrigin: ...
    @staticmethod
    def HandPlaced(by: str) -> PointOrigin: ...
    @staticmethod
    def HandCorrected(by: str) -> PointOrigin: ...
    def variant(self) -> str: ...

class ReviewInterface:
    @staticmethod
    def Tui() -> ReviewInterface: ...
    @staticmethod
    def Gui() -> ReviewInterface: ...
    @staticmethod
    def External() -> ReviewInterface: ...
    def variant(self) -> str: ...

class ReviewStatus:
    @staticmethod
    def Unreviewed() -> ReviewStatus: ...
    @staticmethod
    def Reviewed(by: str, at: str, interface: ReviewInterface) -> ReviewStatus: ...
    def variant(self) -> str: ...

class TraceRecord:
    engine: str
    config: TraceConfig
    frame: PixelRect
    frame_auto_detected: bool
    def __init__(self, engine: str, config: TraceConfig, frame: PixelRect, frame_auto_detected: bool) -> None: ...

class DetectConfig:
    dark_threshold: int
    min_line_fraction: float
    def __init__(self, dark_threshold: int | None = None, min_line_fraction: float | None = None) -> None: ...
    @staticmethod
    def default() -> DetectConfig: ...

class PixelRect:
    left: int
    right: int
    top: int
    bottom: int
    def width(self) -> int: ...
    def height(self) -> int: ...
    def __init__(self, left: int, right: int, top: int, bottom: int) -> None: ...

class AutoArgs:
    image: str
    x_scale: str
    y_scale: str
    x_range: str | None
    y_range: str | None
    x_ref: list[str]
    y_ref: list[str]
    figure: str
    document_id: str | None
    document_title: str | None
    page: int | None
    notes: str | None
    x_label: str
    y_label: str
    operator: str
    timestamp: str | None
    strategy: str
    step: int
    threshold: int
    curve_rgb: str | None
    curve_tolerance: int
    inset: int
    max_column_fill: float
    dark_threshold: int
    min_line_fraction: float
    def run(self) -> tuple[PlotRaster, DigitisedDataset]: ...
    def pipeline_config(self) -> AutoDigitiseConfig: ...
    def __init__(self, image: str, x_scale: str, y_scale: str, x_range: str | None, y_range: str | None, x_ref: list[str], y_ref: list[str], figure: str, document_id: str | None, document_title: str | None, page: int | None, notes: str | None, x_label: str, y_label: str, operator: str, timestamp: str | None, strategy: str, step: int, threshold: int, curve_rgb: str | None, curve_tolerance: int, inset: int, max_column_fill: float, dark_threshold: int, min_line_fraction: float) -> None: ...

class PlotRaster:
    @staticmethod
    def from_path(path: str) -> PlotRaster: ...
    @staticmethod
    def from_bytes(bytes: list[int]) -> PlotRaster: ...
    def width(self) -> int: ...
    def height(self) -> int: ...
    def rgb(self, x: int, y: int) -> list[int]: ...
    def luminance(self, x: int, y: int) -> int: ...
    def source_sha256(self) -> str | None: ...
    def to_png_bytes(self) -> list[int]: ...

class SyntheticPlotSpec:
    width: int
    height: int
    frame: PixelRect
    x_scale: AxisScale
    x_min: float
    x_max: float
    y_scale: AxisScale
    y_min: float
    y_max: float
    curve_half_thickness: int

class RecognizedTable:
    schema_version: int
    source_image_sha256: str | None
    source_note: str | None
    engine: str
    recognized_by: str
    recognized_at: str
    review: ReviewStatus
    rows: list[list[str]]
    def record_review(self, by: str, at: str, interface: ReviewInterface) -> None: ...
    def to_json_string(self) -> str: ...
    def write_json(self, path: str) -> None: ...
    def to_csv_string(self) -> str: ...
    def write_csv(self, path: str) -> None: ...
    def __init__(self, schema_version: int, source_image_sha256: str | None, source_note: str | None, engine: str, recognized_by: str, recognized_at: str, review: ReviewStatus, rows: list[list[str]]) -> None: ...

class CurveSelector:
    def matches(self, raster: PlotRaster, x: int, y: int) -> bool: ...
    @staticmethod
    def DarkestBand(max_luminance: int) -> CurveSelector: ...
    def variant(self) -> str: ...

class PixelTracePoint:
    x_px: float
    y_px: float
    thickness_px: float
    def __init__(self, x_px: float, y_px: float, thickness_px: float) -> None: ...

class TraceConfig:
    selector: CurveSelector
    strategy: TraceStrategy
    column_step: int
    inset: int
    max_column_fill: float
    def __init__(self, selector: CurveSelector | None = None, strategy: TraceStrategy | None = None, column_step: int | None = None, inset: int | None = None, max_column_fill: float | None = None) -> None: ...
    @staticmethod
    def default() -> TraceConfig: ...

class TraceStrategy:
    @staticmethod
    def ColumnCentroid() -> TraceStrategy: ...
    @staticmethod
    def LargestRun() -> TraceStrategy: ...
    @staticmethod
    def ContinuityNearest() -> TraceStrategy: ...
    def variant(self) -> str: ...

class Access:
    def is_committable(self) -> bool: ...
    @staticmethod
    def Open() -> Access: ...
    @staticmethod
    def Restricted() -> Access: ...
    def variant(self) -> str: ...
    @staticmethod
    def default() -> Access: ...

class CiteKey:
    @staticmethod
    def parse(raw: str) -> CiteKey: ...
    @staticmethod
    def sanitise(raw: str) -> CiteKey: ...
    def as_str(self) -> str: ...

class Classification:
    topics: list[str]
    projects: list[str]
    @staticmethod
    def unsorted() -> Classification: ...
    def is_empty(self) -> bool: ...
    def len(self) -> int: ...
    def __init__(self, topics: list[str] | None = None, projects: list[str] | None = None) -> None: ...
    @staticmethod
    def default() -> Classification: ...

class EntityConfig:
    schema_version: int
    id: str
    kind: EntityKind
    name: str | None
    source: SourceRef | None
    classification: Classification
    @staticmethod
    def paper(id: CiteKey, access: Access) -> EntityConfig: ...
    def with_storage(self, storage: StorageMode) -> EntityConfig: ...
    @staticmethod
    def topic(id: str, name: str) -> EntityConfig: ...
    @staticmethod
    def project(id: str, name: str) -> EntityConfig: ...
    def with_pdf(self, pdf: str) -> EntityConfig: ...
    def validate(self) -> None: ...
    def to_toml(self) -> str: ...
    @staticmethod
    def is_entity(dir: str) -> bool: ...
    @staticmethod
    def load(dir: str) -> EntityConfig: ...
    def save_paper(self, dir: str) -> None: ...
    def save(self, dir: str) -> None: ...
    def __init__(self, schema_version: int, id: str, kind: EntityKind, name: str | None, source: SourceRef | None, classification: Classification) -> None: ...

class EntityError:
    @staticmethod
    def NotAnEntity(path: str) -> EntityError: ...
    @staticmethod
    def Toml(path: str, message: str) -> EntityError: ...
    @staticmethod
    def UnsupportedSchema(path: str, found: int, supported: int) -> EntityError: ...
    @staticmethod
    def UnsafeCiteKey(raw: str, reason: str) -> EntityError: ...
    @staticmethod
    def Unclassified(id: str) -> EntityError: ...
    @staticmethod
    def KindMismatch(id: str, message: str) -> EntityError: ...
    @staticmethod
    def UnsafeStorage(id: str) -> EntityError: ...
    def variant(self) -> str: ...

class EntityKind:
    def is_collection(self) -> bool: ...
    def conventional_dir(self) -> str: ...
    @staticmethod
    def Paper() -> EntityKind: ...
    @staticmethod
    def Topic() -> EntityKind: ...
    @staticmethod
    def Project() -> EntityKind: ...
    def variant(self) -> str: ...

class SourceRef:
    access: Access
    storage: StorageMode
    pdf: str | None
    def __init__(self, access: Access | None = None, storage: StorageMode | None = None, pdf: str | None = None) -> None: ...
    @staticmethod
    def default() -> SourceRef: ...

class StorageMode:
    @staticmethod
    def MainRepo() -> StorageMode: ...
    @staticmethod
    def PrivateSubmodule() -> StorageMode: ...
    @staticmethod
    def Local() -> StorageMode: ...
    def variant(self) -> str: ...
    @staticmethod
    def default() -> StorageMode: ...

class Edge:
    to: str
    kind: EdgeKind

class EdgeKind:
    @staticmethod
    def Classification() -> EdgeKind: ...
    @staticmethod
    def WikiLink() -> EdgeKind: ...
    @staticmethod
    def Cites() -> EdgeKind: ...
    def variant(self) -> str: ...

class GraphError:
    @staticmethod
    def Toml(path: str, message: str) -> GraphError: ...
    def variant(self) -> str: ...

class KnowledgeGraph:
    schema_version: int
    edges: list[Edge]
    @staticmethod
    def rebuild(root: KovanRoot, index: KnowledgeIndex) -> KnowledgeGraph: ...
    def save_cache(self, root: KovanRoot) -> None: ...
    @staticmethod
    def load_cache(root: KovanRoot) -> KnowledgeGraph | None: ...
    @staticmethod
    def load_or_rebuild(root: KovanRoot, index: KnowledgeIndex) -> KnowledgeGraph: ...
    def backlinks(self, target: str) -> list[Edge]: ...
    def outlinks(self, source: str) -> list[Edge]: ...
    def __init__(self, schema_version: int | None = None, edges: list[Edge] | None = None) -> None: ...
    @staticmethod
    def default() -> KnowledgeGraph: ...

class WikiLinkRef:
    citekey: str
    artifact: str | None
    def __init__(self, citekey: str, artifact: str | None) -> None: ...

class CollectionEntry:
    path: str
    kind: EntityKind
    name: str
    def __init__(self, path: str, kind: EntityKind, name: str) -> None: ...

class IndexError:
    @staticmethod
    def Toml(path: str, message: str) -> IndexError: ...
    def variant(self) -> str: ...

class KnowledgeIndex:
    schema_version: int
    papers: list[PaperEntry]
    collections: list[CollectionEntry]
    @staticmethod
    def rebuild(root: KovanRoot) -> KnowledgeIndex: ...
    def save_cache(self, root: KovanRoot) -> None: ...
    @staticmethod
    def load_cache(root: KovanRoot) -> KnowledgeIndex | None: ...
    @staticmethod
    def load_or_rebuild(root: KovanRoot) -> KnowledgeIndex: ...
    def children_of(self, parent_path: str) -> list[CollectionEntry]: ...
    def papers_in(self, path: str) -> list[PaperEntry]: ...
    def has_paper(self, citekey: str) -> bool: ...
    def __init__(self, schema_version: int | None = None, papers: list[PaperEntry] | None = None, collections: list[CollectionEntry] | None = None) -> None: ...
    @staticmethod
    def default() -> KnowledgeIndex: ...

class PaperEntry:
    citekey: str
    access: Access
    topics: list[str]
    projects: list[str]
    def __init__(self, citekey: str, access: Access, topics: list[str], projects: list[str]) -> None: ...

class IngestChoice:
    citekey: str
    access: Access
    topics: list[str]
    projects: list[str]
    def __init__(self, citekey: str, access: Access, topics: list[str], projects: list[str]) -> None: ...

class IngestError:
    @staticmethod
    def Metadata(path: str, message: str) -> IngestError: ...
    @staticmethod
    def CiteKeyTaken(citekey: str) -> IngestError: ...
    @staticmethod
    def Bib(path: str, message: str) -> IngestError: ...
    def variant(self) -> str: ...

class IngestPreview:
    source_pdf: str
    suggested_citekey: str
    title: str
    authors: str
    year: int | None
    doi: str | None
    bib_entry: kovan_literature.BibEntry
    already_exists: bool
    def __init__(self, source_pdf: str, suggested_citekey: str, title: str, authors: str, year: int | None, doi: str | None, bib_entry: kovan_literature.BibEntry, already_exists: bool) -> None: ...

class LiteratureCard:
    title_or_citekey: str
    author_year: str
    topics: list[str]
    projects: list[str]
    note_count: int
    formula_count: int
    table_count: int
    graph_count: int
    citation_count: int
    backlink_count: int
    summary: str
    def __init__(self, title_or_citekey: str | None = None, author_year: str | None = None, topics: list[str] | None = None, projects: list[str] | None = None, note_count: int | None = None, formula_count: int | None = None, table_count: int | None = None, graph_count: int | None = None, citation_count: int | None = None, backlink_count: int | None = None, summary: str | None = None) -> None: ...
    @staticmethod
    def default() -> LiteratureCard: ...

class MindmapAction:
    @staticmethod
    def OpenPaper(a0: str) -> MindmapAction: ...
    def variant(self) -> str: ...

class MindmapState:
    def __init__(self) -> None: ...
    @staticmethod
    def default() -> MindmapState: ...

class DocumentEntry:
    id: str
    pdf: str
    markdown: str
    sections: SectionRanges
    def __init__(self, id: str, pdf: str, markdown: str, sections: SectionRanges) -> None: ...

class ProjectError:
    @staticmethod
    def Toml(a0: str) -> ProjectError: ...
    @staticmethod
    def UnknownSection(markdown: str, name: str, line: int) -> ProjectError: ...
    @staticmethod
    def DuplicateSection(markdown: str, name: str) -> ProjectError: ...
    @staticmethod
    def AmbiguousOrMissingBibFile(root: str, found: list[str]) -> ProjectError: ...
    @staticmethod
    def Bib(path: str, source: kovan_literature.BibParseError) -> ProjectError: ...
    @staticmethod
    def StaleSectionRange(markdown: str, name: str) -> ProjectError: ...
    def variant(self) -> str: ...

class ProjectIndex:
    schema_version: int
    bib_file: str
    documents: list[DocumentEntry]
    def __init__(self, schema_version: int, bib_file: str, documents: list[DocumentEntry]) -> None: ...

class SectionContent:
    marker_line: str
    heading_line: str
    body: str
    def __init__(self, marker_line: str, heading_line: str, body: str) -> None: ...

class SectionRanges:
    ai_summary: list[int] | None
    author_summary: list[int] | None
    full_text: list[int] | None
    table_csvs: list[int] | None
    graph_csvs: list[int] | None
    annotations: list[int] | None
    def get(self, name: str) -> list[int] | None: ...
    def __init__(self) -> None: ...
    @staticmethod
    def default() -> SectionRanges: ...

class RepositoryError:
    @staticmethod
    def NotAGitRepository(path: str) -> RepositoryError: ...
    @staticmethod
    def Git(a0: str) -> RepositoryError: ...
    def variant(self) -> str: ...

class SaveSummary:
    added: list[str]
    changed: list[str]
    removed: list[str]
    def is_empty(self) -> bool: ...
    def total(self) -> int: ...
    def to_commit_message(self) -> str: ...
    def __init__(self, added: list[str] | None = None, changed: list[str] | None = None, removed: list[str] | None = None) -> None: ...
    @staticmethod
    def default() -> SaveSummary: ...

class ResearchRecordIndex:
    @staticmethod
    def from_session(session: PaperSession) -> ResearchRecordIndex: ...
    def refresh(self, session: PaperSession) -> None: ...
    def citekey(self) -> str: ...
    def artifacts(self) -> list[Artifact]: ...
    def problems(self) -> list[ArtifactError]: ...
    def get(self, id: str) -> Artifact | None: ...
    def anchored_to_page(self, page: int) -> list[Artifact]: ...

class KovanRoot:
    @staticmethod
    def is_root(dir: str) -> bool: ...
    @staticmethod
    def open(dir: str) -> KovanRoot: ...
    @staticmethod
    def discover(start: str) -> KovanRoot: ...
    @staticmethod
    def create(dir: str, config: RootConfig, init_git: bool) -> KovanRoot: ...
    def path(self) -> str: ...
    def config(self) -> RootConfig: ...
    def marker_path(self) -> str: ...
    def has_git(self) -> bool: ...
    def bibliography_path(self) -> str: ...
    def papers_dir(self) -> str: ...
    def topics_dir(self) -> str: ...
    def projects_dir(self) -> str: ...
    def open_sources_dir(self) -> str: ...
    def restricted_sources_dir(self) -> str: ...
    def private_submodule(self) -> PrivateSubmoduleConfig | None: ...
    def private_submodule_ready(self) -> bool: ...
    def state_dir(self) -> str: ...
    def paper_dir(self, citekey: str) -> str: ...
    def paper_markdown(self, citekey: str) -> str: ...

class LibraryMeta:
    id: str
    name: str
    def __init__(self, id: str, name: str) -> None: ...

class PrivateSubmoduleConfig:
    remote: str
    def __init__(self, remote: str) -> None: ...

class RootConfig:
    schema_version: int
    library: LibraryMeta
    paths: RootPaths
    private_submodule: PrivateSubmoduleConfig | None
    def __init__(self, id: str, name: str) -> None: ...
    def with_private_submodule(self, remote: str) -> RootConfig: ...
    def to_toml(self) -> str: ...

class RootError:
    @staticmethod
    def NotAKovanRoot(start: str) -> RootError: ...
    @staticmethod
    def Toml(path: str, message: str) -> RootError: ...
    @staticmethod
    def UnsupportedSchema(path: str, found: int, supported: int) -> RootError: ...
    @staticmethod
    def AlreadyALibrary(path: str) -> RootError: ...
    @staticmethod
    def GitInit(path: str, message: str) -> RootError: ...
    def variant(self) -> str: ...

class RootPaths:
    bibliography: str
    papers: str
    topics: str
    projects: str
    open_sources: str
    restricted_sources: str
    def __init__(self, bibliography: str | None = None, papers: str | None = None, topics: str | None = None, projects: str | None = None, open_sources: str | None = None, restricted_sources: str | None = None) -> None: ...
    @staticmethod
    def default() -> RootPaths: ...

class PaperSession:
    @staticmethod
    def open(root: KovanRoot, citekey: str) -> PaperSession: ...
    def citekey(self) -> str: ...
    def markdown_path(self) -> str: ...
    def markdown(self) -> str: ...
    def is_dirty(self) -> bool: ...
    def set_markdown(self, text: str) -> None: ...
    def append_block(self, heading_and_block: str) -> None: ...
    def save_document(self) -> None: ...

class SessionError:
    @staticmethod
    def NotFound(citekey: str) -> SessionError: ...
    def variant(self) -> str: ...

class PdfJumpTarget:
    page: int
    region: Region | None
    def __init__(self, page: int, region: Region | None) -> None: ...

class SyncController:
    def __init__(self, ) -> None: ...
    def set_editing_active(self, active: bool) -> None: ...
    def allow_follow(self) -> bool: ...
    def follow_page(self, index: ResearchRecordIndex, page: int) -> list[Artifact]: ...
    @staticmethod
    def jump_to_source(artifact: Artifact) -> PdfJumpTarget | None: ...
    @staticmethod
    def artifact_at_editor_line(index: ResearchRecordIndex, editor_line: int) -> Artifact | None: ...
    @staticmethod
    def default() -> SyncController: ...

class Tab:
    @staticmethod
    def Overview() -> Tab: ...
    @staticmethod
    def Browser() -> Tab: ...
    @staticmethod
    def Symbols() -> Tab: ...
    @staticmethod
    def Methods() -> Tab: ...
    @staticmethod
    def Literature() -> Tab: ...
    @staticmethod
    def Ingest() -> Tab: ...
    @staticmethod
    def Digitiser() -> Tab: ...
    def variant(self) -> str: ...
    @staticmethod
    def default() -> Tab: ...

def fetch(root: KovanRoot, remote: str) -> str: ...
def history(root: KovanRoot, max: int) -> list[kovan_discovery.CommitInfo]: ...
def list_remotes(root: KovanRoot) -> list[RemoteInfo]: ...
def local_branches(root: KovanRoot) -> list[BranchInfo]: ...
def pull(root: KovanRoot, remote: str, branch: str) -> str: ...
def push(root: KovanRoot, remote: str, branch: str) -> str: ...
def save(root: KovanRoot) -> SaveSummary | None: ...
def status(root: KovanRoot) -> SaveSummary: ...
def system_git_available() -> bool: ...
def parse_document(markdown: str) -> ParsedDocument: ...
def render_artifact_block(level: int, heading: str, payload: ArtifactToml, body: str) -> str: ...
def artifact_candidates(index: ResearchRecordIndex, query: str) -> list[Candidate]: ...
def citation_candidates(root: KovanRoot, query: str) -> list[Candidate]: ...
def wiki_candidates(index: KnowledgeIndex, query: str) -> list[Candidate]: ...
def classify_selection(session: PaperSession, index: ResearchRecordIndex, heading: str, kind: ArtifactKind, anchor: SourceAnchor, classification: Classification, body: str) -> Artifact: ...
def insert_artifact(session: PaperSession, index: ResearchRecordIndex, heading: str, kind: ArtifactKind, anchor: SourceAnchor | None, classification: Classification, extraction: Extraction | None, body: str) -> Artifact: ...
def replace_artifact_body(session: PaperSession, id: str, new_body: str) -> Artifact: ...
def sort_artifacts_by_page(session: PaperSession) -> bool: ...
def run(path: str, by_line: bool) -> None: ...
def run(root: str, kind: KindArg | None) -> None: ...
def run(from_: str | None, to: str | None, branch: str, base: str, outfile: str | None) -> None: ...
def default_out_dir(root: str) -> str: ...
def serve(root: str) -> None: ...
def stop(root: str) -> None: ...
def run() -> None: ...
def run(path: str, lang: kovan_semantics.LanguageAdapter) -> None: ...
def run(root: str, lang: LangArg) -> None: ...
def run(path: str | None, root: str | None, kind: KindArg | None, pattern: str) -> None: ...
def run_def(symbol: str, file: str, root: str) -> None: ...
def run_refs(symbol: str, file: str, root: str) -> None: ...
def run_sig(symbol: str, file: str, root: str) -> None: ...
def decide(present: bool, force: bool) -> Action: ...
def run(dry_run: bool, force: bool) -> None: ...
def run(out: str | None) -> None: ...
def run(path: str, start: int, end: int) -> None: ...
def run_summary(root: str, lang: LangArg, id: str | None, name: str | None, out: str | None) -> None: ...
def run_symbols(root: str, lang: LangArg, markdown: bool, out: str | None, name: str | None) -> None: ...
def is_workspace_root(path: str) -> bool: ...
def auto_digitise(raster: PlotRaster, config: AutoDigitiseConfig, source: FigureSource, x_label: str, y_label: str, digitised_by: str, digitised_at: str) -> DigitisedDataset: ...
def uncertainty_interval(axis: AxisCalibration, pixel: float, half_pixels: float) -> tuple[float, float]: ...
def utc_now_iso8601() -> str: ...
def xy_uncertainty_interval(cal: PlotCalibration, x_px: float, y_px: float, half_px_x: float, half_px_y: float) -> tuple[tuple[float, float], tuple[float, float]]: ...
def detect_plot_frame(raster: PlotRaster, config: DetectConfig) -> PixelRect: ...
def parse_scale(s: str) -> AxisScale: ...
def parse_strategy(s: str) -> TraceStrategy: ...
def run(image_arg: str | None) -> None: ...
def render_synthetic_plot(spec: SyntheticPlotSpec) -> tuple[PlotRaster, PlotCalibration]: ...
def trace_curve(raster: PlotRaster, frame: PixelRect, config: TraceConfig) -> list[PixelTracePoint]: ...
def ensure_classification_paths(root: KovanRoot, topics: list[str], projects: list[str]) -> None: ...
def ensure_collection_path(root: KovanRoot, kind: EntityKind, path: str) -> None: ...
def artifact_node(citekey: str, id: str) -> str: ...
def collection_node(path: str) -> str: ...
def extract_citations(markdown: str) -> list[str]: ...
def extract_wiki_links(markdown: str) -> list[WikiLinkRef]: ...
def paper_node(citekey: str) -> str: ...
def ingest(root: KovanRoot, preview: IngestPreview, choice: IngestChoice) -> None: ...
def preview(root: KovanRoot, pdf_path: str) -> IngestPreview: ...
def literature_card(root: KovanRoot, index: KnowledgeIndex, graph: KnowledgeGraph, citekey: str) -> LiteratureCard: ...
def append_to_section(root: str, markdown_rel: str, section_name: str, block: str) -> ProjectIndex: ...
def regenerate(root: str) -> ProjectIndex: ...
def regenerate_and_write(root: str) -> ProjectIndex: ...
def scan_markdown_sections(markdown_path: str, markdown_text: str) -> SectionRanges: ...
def write_index(root: str, index: ProjectIndex) -> None: ...
def save_repository(root: KovanRoot) -> SaveSummary | None: ...
def status(root: KovanRoot) -> SaveSummary: ...
def gitignore_for(paths: RootPaths, private_submodule: PrivateSubmoduleConfig | None) -> str: ...
DEFAULT_OUT: str
DATASET_SCHEMA_VERSION: int
TABLE_SCHEMA_VERSION: int
ENTITY_MARKER: str
SCHEMA_VERSION: int
UNSORTED: str
GRAPH_SCHEMA_VERSION: int
INDEX_SCHEMA_VERSION: int
PROJECT_SCHEMA_VERSION: int
ROOT_MARKER: str
SCHEMA_VERSION: int
STATE_DIR: str
