"""Type stubs for `outram_park.nee_soon`, generated from the Rust API.

Physical quantities cross this boundary as `float` in SI base units.
"""

class NeeSoon:
    def new_prompt_excursion_model(self, prompt_neutron_generation_time: float, delayed_neutron_fraction: float, fuel_heat_capacity: float, fuel_feedback_coefficient: float, fuel_reference_temperature: float, initial_fuel_temperature: float, initial_power: float) -> teh_o_prke.NordheimFuchsExactTimestepper: ...
    def __init__(self) -> None: ...
    @staticmethod
    def default() -> NeeSoon: ...

class WorkflowError:
    def variant(self) -> str: ...

class WorkflowStage:
    @staticmethod
    def MgxsGeneration() -> WorkflowStage: ...
    @staticmethod
    def MeshAndMonteCarlo() -> WorkflowStage: ...
    @staticmethod
    def Sp3Multiphysics() -> WorkflowStage: ...
    @staticmethod
    def Fig429Validation() -> WorkflowStage: ...
    def variant(self) -> str: ...

class XinWangSp3Workflow:
    def __init__(self, ) -> None: ...
    def mgxs(self) -> MgxsGenerationStage: ...
    def mesh_mc(self) -> MeshMonteCarloStage: ...
    def sp3_multiphysics(self) -> Sp3MultiphysicsStage: ...
    def validation(self) -> Fig429ValidationStage: ...
    def run(self) -> None: ...
    @staticmethod
    def default() -> XinWangSp3Workflow: ...

class ControlRodRemovalTransient:
    total_control_rods: int
    rods_removed: int
    all_rods_out_excess_reactivity: float
    duration: float
    @staticmethod
    def fig_4_29() -> ControlRodRemovalTransient: ...
    def __init__(self, total_control_rods: int, rods_removed: int, all_rods_out_excess_reactivity: float, duration: float) -> None: ...

class Fig429Point:
    time: float
    max_fuel_temperature: float
    def __init__(self, time: float, max_fuel_temperature: float) -> None: ...

class Mk1DesignPoint:
    thermal_power: float
    coolant_inlet_temperature: float
    coolant_outlet_temperature: float
    coolant_mass_flow: float
    fuel_enrichment: float
    pebble_packing_fraction: float
    triso_packing_fraction: float
    @staticmethod
    def nominal() -> Mk1DesignPoint: ...
    def __init__(self, thermal_power: float, coolant_inlet_temperature: float, coolant_outlet_temperature: float, coolant_mass_flow: float, fuel_enrichment: float, pebble_packing_fraction: float, triso_packing_fraction: float) -> None: ...

class MeshMonteCarloStage:
    def __init__(self, ) -> None: ...
    def geometry(self) -> Mk1CoreGeometry: ...
    def pebble_packing_fraction(self) -> float: ...
    def triso_per_pebble(self) -> int: ...
    def run(self) -> None: ...
    @staticmethod
    def default() -> MeshMonteCarloStage: ...

class Mk1CoreGeometry:
    center_reflector_radius: float
    fuel_region_outer_radius: float
    blanket_outer_radius: float
    outer_reflector_radius: float
    vessel_outer_radius: float
    pebble_diameter: float
    @staticmethod
    def reference() -> Mk1CoreGeometry: ...
    def __init__(self, center_reflector_radius: float, fuel_region_outer_radius: float, blanket_outer_radius: float, outer_reflector_radius: float, vessel_outer_radius: float, pebble_diameter: float) -> None: ...

class MgxsGenerationStage:
    def __init__(self, ) -> None: ...
    def group_lower_bounds(self) -> list[float]: ...
    def run(self) -> None: ...
    @staticmethod
    def default() -> MgxsGenerationStage: ...

class Mk1MaterialRegion:
    @staticmethod
    def all() -> list[Mk1MaterialRegion]: ...
    @staticmethod
    def FuelPebble() -> Mk1MaterialRegion: ...
    @staticmethod
    def BlanketPebble() -> Mk1MaterialRegion: ...
    @staticmethod
    def CenterReflector() -> Mk1MaterialRegion: ...
    @staticmethod
    def OuterReflector() -> Mk1MaterialRegion: ...
    @staticmethod
    def ControlRod() -> Mk1MaterialRegion: ...
    @staticmethod
    def StainlessSteel() -> Mk1MaterialRegion: ...
    @staticmethod
    def Flibe() -> Mk1MaterialRegion: ...
    def variant(self) -> str: ...

class PorousMediaClosures:
    ergun_e1: float
    ergun_e2: float
    forchheimer_cf: float
    @staticmethod
    def mk1() -> PorousMediaClosures: ...
    def __init__(self, ergun_e1: float, ergun_e2: float, forchheimer_cf: float) -> None: ...

class Sp3MultiphysicsStage:
    def __init__(self, ) -> None: ...
    def energy_groups(self) -> int: ...
    def delayed_groups(self) -> int: ...
    def porous_media_closures(self) -> PorousMediaClosures: ...
    def transient(self) -> ControlRodRemovalTransient: ...
    def target_neutronics_kind(self) -> outram_foam_appbuilder_lib.NeutronicsModelKind: ...
    def run(self) -> None: ...
    @staticmethod
    def default() -> Sp3MultiphysicsStage: ...

class Fig429Target:
    peak_max_fuel_temperature_celsius: float
    end_max_fuel_temperature_celsius: float
    peak_power_fraction_above_initial: float
    initial_power: float
    @staticmethod
    def digitised() -> Fig429Target: ...
    def __init__(self, peak_max_fuel_temperature_celsius: float, end_max_fuel_temperature_celsius: float, peak_power_fraction_above_initial: float, initial_power: float) -> None: ...

class Fig429ValidationStage:
    def __init__(self, ) -> None: ...
    def reference_curve(self) -> list[Fig429Point]: ...
    def target(self) -> Fig429Target: ...
    def run(self) -> None: ...
    @staticmethod
    def default() -> Fig429ValidationStage: ...

def energy_group_lower_bounds() -> list[float]: ...
def fig_4_29_reference_curve() -> list[Fig429Point]: ...
def fuel_safety_limit() -> float: ...
NUM_DELAYED_GROUPS: int
NUM_ENERGY_GROUPS: int
STAGE_BEAD: str
NJOY_API_BEAD: str
STAGE_BEAD: str
GENFOAM_COUPLING_BEAD: str
GENFOAM_SP3_PORT_BEAD: str
STAGE_BEAD: str
STAGE_BEAD: str
