"""Type stubs for `outram_park.outram_blender`, generated from the Rust API.

Physical quantities cross this boundary as `float` in SI base units.
"""

class ArapError:
    @staticmethod
    def NoConstraints() -> ArapError: ...
    @staticmethod
    def Assembly() -> ArapError: ...
    @staticmethod
    def NotPositiveDefinite() -> ArapError: ...
    def variant(self) -> str: ...

class ArrayCaps:
    start: Mesh | None
    end: Mesh | None
    def __init__(self, start: Mesh | None = None, end: Mesh | None = None) -> None: ...
    @staticmethod
    def default() -> ArrayCaps: ...

class MeshAttributes:
    def __init__(self, _mesh: Mesh) -> None: ...
    def mark_sharp(self, edges: list[EdgeId]) -> None: ...
    def clear_sharp(self, edges: list[EdgeId]) -> None: ...
    def is_sharp(self, e: EdgeId) -> bool: ...
    def mark_seam(self, edges: list[EdgeId]) -> None: ...
    def clear_seam(self, edges: list[EdgeId]) -> None: ...
    def is_seam(self, e: EdgeId) -> bool: ...
    def set_crease(self, edges: list[EdgeId], value: float) -> None: ...
    def crease(self, e: EdgeId) -> float: ...
    def set_edge_bevel_weight(self, edges: list[EdgeId], value: float) -> None: ...
    def edge_bevel_weight(self, e: EdgeId) -> float: ...
    def shade_smooth(self, mesh: Mesh, faces: list[FaceId]) -> None: ...
    def shade_flat(self, mesh: Mesh, faces: list[FaceId]) -> None: ...
    def is_smooth(self, f: FaceId) -> bool: ...
    def set_material(self, faces: list[FaceId], index: int) -> None: ...
    def material(self, f: FaceId) -> int: ...
    def auto_smooth(self, mesh: Mesh, angle: float) -> None: ...
    @staticmethod
    def default() -> MeshAttributes: ...

class BevelOptions:
    amount: float
    segments: int
    profile: float
    width_type: WidthType
    clamp_overlap: bool
    def __init__(self, amount: float | None = None, segments: int | None = None, profile: float | None = None, width_type: WidthType | None = None, clamp_overlap: bool | None = None) -> None: ...
    @staticmethod
    def default() -> BevelOptions: ...

class WidthType:
    @staticmethod
    def Offset() -> WidthType: ...
    @staticmethod
    def Width() -> WidthType: ...
    @staticmethod
    def Depth() -> WidthType: ...
    @staticmethod
    def Percent() -> WidthType: ...
    def variant(self) -> str: ...

class BoolBrush:
    mesh: Mesh
    op: BrushOp
    enabled: bool
    def __init__(self, mesh: Mesh, op: BrushOp) -> None: ...

class BoolStack:
    brushes: list[BoolBrush]
    def __init__(self, ) -> None: ...
    def push(self, brush: BoolBrush) -> None: ...
    def bake(self, base: Mesh) -> Mesh: ...
    def carve(self, base: Mesh) -> tuple[Mesh, list[int]]: ...
    @staticmethod
    def default() -> BoolStack: ...

class BrushOp:
    @staticmethod
    def Difference() -> BrushOp: ...
    @staticmethod
    def Union() -> BrushOp: ...
    @staticmethod
    def Intersect() -> BrushOp: ...
    @staticmethod
    def Slice() -> BrushOp: ...
    def variant(self) -> str: ...

class BooleanError:
    def variant(self) -> str: ...

class PointClass:
    @staticmethod
    def Inside() -> PointClass: ...
    @staticmethod
    def Outside() -> PointClass: ...
    @staticmethod
    def OnBoundary() -> PointClass: ...
    def variant(self) -> str: ...

class Vec2:
    x: float
    y: float
    def __init__(self, x: float, y: float) -> None: ...

class BridgeOptions:
    twist: int
    cuts: int
    flip: bool
    merge_distance: float
    def __init__(self, twist: int | None = None, cuts: int | None = None, flip: bool | None = None, merge_distance: float | None = None) -> None: ...
    @staticmethod
    def default() -> BridgeOptions: ...

class HullError:
    @staticmethod
    def NotEnoughPoints(a0: int) -> HullError: ...
    @staticmethod
    def Collinear() -> HullError: ...
    @staticmethod
    def Coplanar() -> HullError: ...
    def variant(self) -> str: ...

class Cursor3D:
    position: Vec3
    basis: TransformBasis
    def to_grid(self, step: float) -> None: ...
    def to_selected(self, mesh: Mesh, verts: list[VertexId]) -> None: ...
    def to_active(self, mesh: Mesh, active: VertexId) -> None: ...
    def to_world_origin(self) -> None: ...
    def __init__(self, position: Vec3 | None = None, basis: TransformBasis | None = None) -> None: ...
    @staticmethod
    def default() -> Cursor3D: ...

class PivotPoint:
    @staticmethod
    def BoundingBoxCenter() -> PivotPoint: ...
    @staticmethod
    def Cursor() -> PivotPoint: ...
    @staticmethod
    def IndividualOrigins() -> PivotPoint: ...
    @staticmethod
    def MedianPoint() -> PivotPoint: ...
    @staticmethod
    def ActiveElement(a0: VertexId) -> PivotPoint: ...
    def variant(self) -> str: ...

class ControlPoint:
    position: Vec3
    handle_left: Vec3
    handle_right: Vec3
    type_left: HandleType
    type_right: HandleType
    radius: float
    tilt: float
    weight: float
    def __init__(self, position: Vec3) -> None: ...

class HandleType:
    @staticmethod
    def Automatic() -> HandleType: ...
    @staticmethod
    def Vector() -> HandleType: ...
    @staticmethod
    def Aligned() -> HandleType: ...
    @staticmethod
    def Free() -> HandleType: ...
    def variant(self) -> str: ...

class Spline:
    spline_type: SplineType
    points: list[ControlPoint]
    cyclic: bool
    resolution: int
    order: int
    @staticmethod
    def poly(positions: list[Vec3]) -> Spline: ...
    @staticmethod
    def bezier(positions: list[Vec3]) -> Spline: ...
    @staticmethod
    def nurbs(positions: list[Vec3], order: int) -> Spline: ...
    def push(self, position: Vec3) -> None: ...
    def toggle_cyclic(self) -> None: ...
    def set_type(self, ty: SplineType) -> None: ...
    def subdivide(self) -> None: ...
    def recalculate_handles(self) -> None: ...
    def sample(self) -> list[Vec3]: ...
    def sample_with_frames(self) -> list[SplineSample]: ...
    def __init__(self, spline_type: SplineType, points: list[ControlPoint], cyclic: bool, resolution: int, order: int) -> None: ...

class SplineSample:
    position: Vec3
    radius: float
    tangent: Vec3
    normal: Vec3
    def __init__(self, position: Vec3, radius: float, tangent: Vec3, normal: Vec3) -> None: ...

class SplineType:
    @staticmethod
    def Poly() -> SplineType: ...
    @staticmethod
    def Bezier() -> SplineType: ...
    @staticmethod
    def Nurbs() -> SplineType: ...
    def variant(self) -> str: ...

class Bevel:
    @staticmethod
    def None_() -> Bevel: ...
    @staticmethod
    def Round(depth: float, segments: int) -> Bevel: ...
    def variant(self) -> str: ...

class CurveGeometry:
    bevel: Bevel
    taper: Spline | None
    fill: FillMode
    caps: bool
    def __init__(self, bevel: Bevel | None = None, taper: Spline | None = None, fill: FillMode | None = None, caps: bool | None = None) -> None: ...
    @staticmethod
    def default() -> CurveGeometry: ...

class FillMode:
    @staticmethod
    def None_() -> FillMode: ...
    @staticmethod
    def Full() -> FillMode: ...
    def variant(self) -> str: ...

class DecimateResult:
    mesh: Mesh
    stop_reason: StopReason
    def __init__(self, mesh: Mesh, stop_reason: StopReason) -> None: ...

class StopReason:
    @staticmethod
    def ReachedTarget() -> StopReason: ...
    @staticmethod
    def NoLegalCollapse() -> StopReason: ...
    def variant(self) -> str: ...

class Lattice:
    dims: list[int]
    rest_min: Vec3
    rest_max: Vec3
    points: list[Vec3]

class ShrinkMode:
    @staticmethod
    def NearestSurfacePoint() -> ShrinkMode: ...
    @staticmethod
    def ProjectAlongNormal() -> ShrinkMode: ...
    @staticmethod
    def NearestVertex() -> ShrinkMode: ...
    def variant(self) -> str: ...

class CastTarget:
    @staticmethod
    def Sphere(a0: float) -> CastTarget: ...
    @staticmethod
    def Cylinder(radius: float, axis: Axis) -> CastTarget: ...
    @staticmethod
    def Cuboid(a0: Vec3) -> CastTarget: ...
    def variant(self) -> str: ...

class SimpleDeform:
    @staticmethod
    def Twist(a0: float) -> SimpleDeform: ...
    @staticmethod
    def Bend(a0: float) -> SimpleDeform: ...
    @staticmethod
    def Taper(a0: float) -> SimpleDeform: ...
    @staticmethod
    def Stretch(a0: float) -> SimpleDeform: ...
    def variant(self) -> str: ...

class DeleteMode:
    @staticmethod
    def Vertices() -> DeleteMode: ...
    @staticmethod
    def Edges() -> DeleteMode: ...
    @staticmethod
    def Faces() -> DeleteMode: ...
    @staticmethod
    def OnlyFaces() -> DeleteMode: ...
    @staticmethod
    def Collapse() -> DeleteMode: ...
    def variant(self) -> str: ...

class DrawGesture:
    def __init__(self, plane: WorkPlane, kind: DrawKind) -> None: ...
    def stage(self) -> Stage: ...
    def push_point(self, world: Vec3) -> None: ...
    def push_depth_point(self, world: Vec3) -> None: ...
    def set_depth(self, depth: float) -> None: ...
    def resolve(self) -> Mesh | None: ...

class DrawKind:
    @staticmethod
    def Box() -> DrawKind: ...
    @staticmethod
    def Cylinder(segments: int) -> DrawKind: ...
    @staticmethod
    def Cone(segments: int) -> DrawKind: ...
    def variant(self) -> str: ...

class Stage:
    @staticmethod
    def PickBase() -> Stage: ...
    @staticmethod
    def DragFootprint() -> Stage: ...
    @staticmethod
    def DragDepth() -> Stage: ...
    @staticmethod
    def Done() -> Stage: ...
    def variant(self) -> str: ...

class WorkPlane:
    origin: Vec3
    u: Vec3
    v: Vec3
    normal: Vec3
    @staticmethod
    def xy() -> WorkPlane: ...
    @staticmethod
    def xz() -> WorkPlane: ...
    @staticmethod
    def yz() -> WorkPlane: ...
    @staticmethod
    def from_origin_normal(origin: Vec3, normal: Vec3) -> WorkPlane: ...
    def point(self, a: float, b: float, h: float) -> Vec3: ...
    def project(self, p: Vec3) -> tuple[float, float]: ...
    def __init__(self, origin: Vec3, u: Vec3, v: Vec3, normal: Vec3) -> None: ...

class CsgDescription:
    surfaces: list[CsgSurface]
    region: list[RegionToken]
    def contains(self, p: Vec3) -> bool: ...
    def __init__(self, surfaces: list[CsgSurface], region: list[RegionToken]) -> None: ...

class CsgSurface:
    def signed_value(self, p: Vec3) -> float: ...
    @staticmethod
    def XPlane(x0: float) -> CsgSurface: ...
    @staticmethod
    def YPlane(y0: float) -> CsgSurface: ...
    @staticmethod
    def ZPlane(z0: float) -> CsgSurface: ...
    @staticmethod
    def Sphere(x0: float, y0: float, z0: float, r: float) -> CsgSurface: ...
    @staticmethod
    def ZCylinder(x0: float, y0: float, r: float) -> CsgSurface: ...
    @staticmethod
    def Plane(a: float, b: float, c: float, d: float) -> CsgSurface: ...
    def variant(self) -> str: ...

class ExportError:
    @staticmethod
    def NotClosedSurface(tri: int, a: int, b: int) -> ExportError: ...
    @staticmethod
    def NonManifoldSurface(tri: int, other_tri: int, a: int, b: int) -> ExportError: ...
    @staticmethod
    def DegenerateTriangle(tri: int, a: int, b: int, c: int) -> ExportError: ...
    def variant(self) -> str: ...

class FacetedSolid:
    positions: list[Vec3]
    triangles: list[list[int]]
    def triangle_count(self) -> int: ...
    def check_closed_manifold(self) -> None: ...
    def contains(self, p: Vec3) -> bool: ...
    def __init__(self) -> None: ...
    @staticmethod
    def default() -> FacetedSolid: ...

class IndexedTriangles:
    positions: list[Vec3]
    indices: list[int]
    def triangle_count(self) -> int: ...
    def __init__(self, positions: list[Vec3] | None = None, indices: list[int] | None = None) -> None: ...
    @staticmethod
    def default() -> IndexedTriangles: ...

class PolyMeshText:
    points: str
    faces: str
    owner: str
    neighbour: str
    boundary: str
    def __init__(self, points: str, faces: str, owner: str, neighbour: str, boundary: str) -> None: ...

class RegionToken:
    @staticmethod
    def Halfspace(surface: int, sense: Sense) -> RegionToken: ...
    @staticmethod
    def Intersection() -> RegionToken: ...
    @staticmethod
    def Union() -> RegionToken: ...
    @staticmethod
    def Complement() -> RegionToken: ...
    def variant(self) -> str: ...

class Sense:
    @staticmethod
    def Positive() -> Sense: ...
    @staticmethod
    def Negative() -> Sense: ...
    def variant(self) -> str: ...

class GpuError:
    @staticmethod
    def Poll(a0: str) -> GpuError: ...
    @staticmethod
    def Map(a0: str) -> GpuError: ...
    @staticmethod
    def MapCallbackMissing() -> GpuError: ...
    def variant(self) -> str: ...

class Chord:
    face: FaceId
    to: KnifePoint

class KnifePoint:
    @staticmethod
    def Vertex(a0: VertexId) -> KnifePoint: ...
    @staticmethod
    def EdgeSplit(edge: EdgeId, t: float) -> KnifePoint: ...
    def variant(self) -> str: ...

class KnifeResult:
    mesh: Mesh
    cut_vertices: list[VertexId]
    def __init__(self, mesh: Mesh, cut_vertices: list[VertexId]) -> None: ...

class LaplacianError:
    @staticmethod
    def Assembly() -> LaplacianError: ...
    @staticmethod
    def NotPositiveDefinite() -> LaplacianError: ...
    def variant(self) -> str: ...

class LaplacianWeighting:
    @staticmethod
    def Uniform() -> LaplacianWeighting: ...
    @staticmethod
    def Cotangent() -> LaplacianWeighting: ...
    def variant(self) -> str: ...

class LoopCutResult:
    mesh: Mesh
    new_loops: list[list[VertexId]]
    closed: bool
    def __init__(self, mesh: Mesh, new_loops: list[list[VertexId]], closed: bool) -> None: ...

class Vec3:
    x: float
    y: float
    z: float
    def __init__(self, x: float, y: float, z: float) -> None: ...
    def add(self, other: Vec3) -> Vec3: ...
    def sub(self, other: Vec3) -> Vec3: ...
    def scale(self, s: float) -> Vec3: ...
    def dot(self, other: Vec3) -> float: ...
    def cross(self, other: Vec3) -> Vec3: ...
    def length(self) -> float: ...
    def normalize(self) -> Vec3: ...

class Protractor:
    a: Vec3
    vertex: Vec3
    b: Vec3
    def angle(self) -> float: ...
    def __init__(self, a: Vec3, vertex: Vec3, b: Vec3) -> None: ...

class Ruler:
    a: Vec3
    b: Vec3
    def distance(self) -> float: ...
    def __init__(self, a: Vec3, b: Vec3) -> None: ...

class MergeTarget:
    @staticmethod
    def Center() -> MergeTarget: ...
    @staticmethod
    def Point(a0: Vec3) -> MergeTarget: ...
    @staticmethod
    def First() -> MergeTarget: ...
    @staticmethod
    def Last() -> MergeTarget: ...
    def variant(self) -> str: ...

class Edge:
    verts: list[VertexId]

class Face:
    loop_start: LoopId
    len: int
    def __init__(self, loop_start: LoopId, len: int) -> None: ...

class Loop:
    vert: VertexId
    edge: EdgeId
    face: FaceId
    next: LoopId
    prev: LoopId
    def __init__(self, vert: VertexId, edge: EdgeId, face: FaceId, next: LoopId, prev: LoopId) -> None: ...

class Mesh:
    def __init__(self, ) -> None: ...
    def add_vertex(self, position: Vec3) -> VertexId: ...
    def add_face(self, verts: list[VertexId]) -> FaceId: ...
    def vertex_count(self) -> int: ...
    def edge_count(self) -> int: ...
    def loop_count(self) -> int: ...
    def face_count(self) -> int: ...
    def vertex(self, id: VertexId) -> Vertex | None: ...
    def edge(self, id: EdgeId) -> Edge | None: ...
    def loop_at(self, id: LoopId) -> Loop | None: ...
    def face(self, id: FaceId) -> Face | None: ...
    def face_vertices(self, face: FaceId) -> list[VertexId]: ...
    def euler_characteristic(self) -> int: ...
    def positions(self) -> list[Vec3]: ...
    def polygons(self) -> list[list[VertexId]]: ...
    @staticmethod
    def from_polygons(positions: list[Vec3], faces: list[list[int]]) -> Mesh: ...
    def face_normal(self, face: FaceId) -> Vec3: ...
    def face_centroid(self, face: FaceId) -> Vec3: ...
    @staticmethod
    def default() -> Mesh: ...

class Vertex:
    position: Vec3
    loop_id: LoopId | None
    def __init__(self, position: Vec3, loop_id: LoopId | None) -> None: ...

class MirrorAxes:
    x: bool
    y: bool
    z: bool
    def __init__(self, x: bool | None = None, y: bool | None = None, z: bool | None = None) -> None: ...
    @staticmethod
    def default() -> MirrorAxes: ...

class Modifier:
    def evaluate(self, input: Mesh) -> Mesh: ...
    @staticmethod
    def Subsurf(levels: int) -> Modifier: ...
    @staticmethod
    def Mirror(axes: MirrorAxes) -> Modifier: ...
    @staticmethod
    def Bevel(options: BevelOptions) -> Modifier: ...
    @staticmethod
    def Boolean(operand: Mesh, op: BooleanMode) -> Modifier: ...
    @staticmethod
    def Solidify(thickness: float) -> Modifier: ...
    @staticmethod
    def Weld(distance: float) -> Modifier: ...
    @staticmethod
    def Wireframe(thickness: float) -> Modifier: ...
    @staticmethod
    def EdgeSplit(angle: float) -> Modifier: ...
    @staticmethod
    def Triangulate() -> Modifier: ...
    @staticmethod
    def Mask(keep: list[VertexId], invert: bool) -> Modifier: ...
    @staticmethod
    def Remesh(voxel_size: float, smooth_iterations: int) -> Modifier: ...
    @staticmethod
    def Screw(axis: Axis, turns: float, steps: int, screw_offset: float) -> Modifier: ...
    @staticmethod
    def Skin(radius: float) -> Modifier: ...
    @staticmethod
    def Build(factor: float) -> Modifier: ...
    @staticmethod
    def Multires(levels: int) -> Modifier: ...
    @staticmethod
    def Decimate(ratio: float) -> Modifier: ...
    @staticmethod
    def SimpleDeform(mode: SimpleDeform, axis: Axis) -> Modifier: ...
    @staticmethod
    def Cast(target: CastTarget, factor: float) -> Modifier: ...
    @staticmethod
    def Displace(direction: Vec3, strength: float, noise_scale: float, seed: int) -> Modifier: ...
    @staticmethod
    def Wave(axis: Axis, amplitude: float, wavelength: float, speed: float, time: float) -> Modifier: ...
    def variant(self) -> str: ...

class ModifierEntry:
    modifier: Modifier
    show_viewport: bool
    show_render: bool
    show_in_editmode: bool
    on_cage: bool
    def __init__(self, modifier: Modifier) -> None: ...

class ModifierError:
    @staticmethod
    def Failed(a0: str) -> ModifierError: ...
    def variant(self) -> str: ...

class ModifierStack:
    modifiers: list[ModifierEntry]
    def __init__(self, ) -> None: ...
    def push(self, m: Modifier) -> ModifierStack: ...
    def push_entry(self, e: ModifierEntry) -> ModifierStack: ...
    def move_up(self, i: int) -> None: ...
    def move_down(self, i: int) -> None: ...
    def remove(self, i: int) -> None: ...
    def duplicate(self, i: int) -> None: ...
    def evaluate(self, base: Mesh) -> Mesh: ...
    def evaluate_render(self, base: Mesh) -> Mesh: ...
    def apply_first(self, base: Mesh) -> Mesh: ...
    def apply_all(self, base: Mesh) -> Mesh: ...
    def apply_as_shape_key(self, base: Mesh) -> list[Vec3]: ...
    @staticmethod
    def default() -> ModifierStack: ...

class NormalWeight:
    @staticmethod
    def Uniform() -> NormalWeight: ...
    @staticmethod
    def FaceArea() -> NormalWeight: ...
    @staticmethod
    def CornerAngle() -> NormalWeight: ...
    def variant(self) -> str: ...

class SplitNormals:
    normals: list[list[Vec3]]
    @staticmethod
    def flat(mesh: Mesh) -> SplitNormals: ...
    def __init__(self, normals: list[list[Vec3]] | None = None) -> None: ...
    @staticmethod
    def default() -> SplitNormals: ...

class NurbsSurface:
    nu: int
    nv: int
    order_u: int
    order_v: int
    control: list[Vec3]
    weights: list[float]
    cyclic_u: bool
    cyclic_v: bool
    def move_control(self, u: int, v: int, delta: Vec3) -> None: ...
    def evaluate(self, u: float, v: float) -> Vec3: ...
    def to_mesh(self, res_u: int, res_v: int) -> Mesh: ...
    @staticmethod
    def plane(nu: int, nv: int) -> NurbsSurface: ...
    @staticmethod
    def sphere(radius: float) -> NurbsSurface: ...
    @staticmethod
    def cylinder(radius: float, height: float) -> NurbsSurface: ...
    @staticmethod
    def torus(r: float, t: float) -> NurbsSurface: ...
    def __init__(self, nu: int, nv: int, order_u: int, order_v: int, control: list[Vec3], weights: list[float], cyclic_u: bool, cyclic_v: bool) -> None: ...

class AlignMode:
    @staticmethod
    def Min() -> AlignMode: ...
    @staticmethod
    def Center() -> AlignMode: ...
    @staticmethod
    def Max() -> AlignMode: ...
    def variant(self) -> str: ...

class OriginMode:
    @staticmethod
    def GeometryMedian() -> OriginMode: ...
    @staticmethod
    def CenterOfMassSurface() -> OriginMode: ...
    @staticmethod
    def CenterOfMassVolume() -> OriginMode: ...
    @staticmethod
    def Cursor(world: Vec3) -> OriginMode: ...
    def variant(self) -> str: ...

class SceneObject:
    mesh: Mesh
    transform: Affine3
    def __init__(self, mesh: Mesh) -> None: ...
    def world_mesh(self) -> Mesh: ...
    def world_origin(self) -> Vec3: ...
    def duplicate(self) -> SceneObject: ...
    def linked_duplicate(self) -> SceneObject: ...
    def shares_mesh_with(self, other: SceneObject) -> bool: ...
    def apply_transform(self) -> SceneObject: ...
    def set_origin(self, mode: OriginMode) -> SceneObject: ...

class SnapObjectsTo:
    @staticmethod
    def Cursor(world: Vec3) -> SnapObjectsTo: ...
    @staticmethod
    def Grid(step: float) -> SnapObjectsTo: ...
    @staticmethod
    def Active(index: int) -> SnapObjectsTo: ...
    def variant(self) -> str: ...

class BooleanMode:
    @staticmethod
    def Union() -> BooleanMode: ...
    @staticmethod
    def Difference() -> BooleanMode: ...
    @staticmethod
    def Intersect() -> BooleanMode: ...
    def variant(self) -> str: ...

class MeshOp:
    def apply(self, mesh: Mesh) -> Mesh: ...
    @staticmethod
    def Extrude(offset: Vec3) -> MeshOp: ...
    @staticmethod
    def Subdivide(iterations: int) -> MeshOp: ...
    @staticmethod
    def Bevel(width: float, segments: int) -> MeshOp: ...
    @staticmethod
    def Boolean(other: Mesh, mode: BooleanMode) -> MeshOp: ...
    @staticmethod
    def Smooth(weighting: LaplacianWeighting, lambda: float, iterations: int) -> MeshOp: ...
    @staticmethod
    def Taubin(weighting: LaplacianWeighting, lambda: float, mu: float, iterations: int) -> MeshOp: ...
    @staticmethod
    def Arap(handles: list[tuple[VertexId, Vec3]], iterations: int) -> MeshOp: ...
    @staticmethod
    def Decimate(target_faces: int) -> MeshOp: ...
    @staticmethod
    def LoopSubdivide(iterations: int) -> MeshOp: ...
    @staticmethod
    def ConvexHull() -> MeshOp: ...
    @staticmethod
    def Weld(distance: float) -> MeshOp: ...
    @staticmethod
    def FillHoles() -> MeshOp: ...
    @staticmethod
    def Solidify(thickness: float) -> MeshOp: ...
    @staticmethod
    def RecalculateNormals() -> MeshOp: ...
    @staticmethod
    def Triangulate() -> MeshOp: ...
    @staticmethod
    def Inset(amount: float) -> MeshOp: ...
    @staticmethod
    def Bisect(point: Vec3, normal: Vec3) -> MeshOp: ...
    @staticmethod
    def BevelEdges(width: float) -> MeshOp: ...
    def variant(self) -> str: ...

class MeshOpError:
    def variant(self) -> str: ...

class BoundaryShape:
    @staticmethod
    def Circle() -> BoundaryShape: ...
    @staticmethod
    def Square() -> BoundaryShape: ...
    def variant(self) -> str: ...

class ParamError:
    @staticmethod
    def NoBoundary() -> ParamError: ...
    @staticmethod
    def MultipleBoundaries() -> ParamError: ...
    @staticmethod
    def NonManifoldBoundary() -> ParamError: ...
    @staticmethod
    def NotADisk() -> ParamError: ...
    @staticmethod
    def Assembly() -> ParamError: ...
    @staticmethod
    def NotPositiveDefinite() -> ParamError: ...
    def variant(self) -> str: ...

class Placement:
    def resolve(self) -> Vec3: ...
    @staticmethod
    def Absolute(coord: Vec3) -> Placement: ...
    @staticmethod
    def Delta(from: Vec3, delta: Vec3) -> Placement: ...
    @staticmethod
    def Polar(from: Vec3, plane: WorkPlane, distance: float, angle: float) -> Placement: ...
    @staticmethod
    def Percent(a: Vec3, b: Vec3, percent: float) -> Placement: ...
    def variant(self) -> str: ...

class QuadMethod:
    @staticmethod
    def ShortestDiagonal() -> QuadMethod: ...
    @staticmethod
    def Fixed() -> QuadMethod: ...
    @staticmethod
    def FixedAlternate() -> QuadMethod: ...
    @staticmethod
    def Beauty() -> QuadMethod: ...
    def variant(self) -> str: ...

class AddMeshOptions:
    location: Vec3
    rotation_euler: Vec3
    scale: float
    @staticmethod
    def at(location: Vec3) -> AddMeshOptions: ...
    def place(self, mesh: Mesh) -> Mesh: ...
    def __init__(self, location: Vec3 | None = None, rotation_euler: Vec3 | None = None, scale: float | None = None) -> None: ...
    @staticmethod
    def default() -> AddMeshOptions: ...

class GeometryGraph:
    def __init__(self, ) -> None: ...
    def add(self, node: GeometryNode) -> NodeId: ...
    def node(self, id: NodeId) -> GeometryNode | None: ...
    def len(self) -> int: ...
    def is_empty(self) -> bool: ...
    def evaluate(self) -> Mesh: ...
    @staticmethod
    def default() -> GeometryGraph: ...

class GeometryNode:
    @staticmethod
    def Primitive(a0: PrimitiveKind) -> GeometryNode: ...
    @staticmethod
    def Join(a: NodeId, b: NodeId) -> GeometryNode: ...
    @staticmethod
    def Subdivide(input: NodeId, levels: int) -> GeometryNode: ...
    @staticmethod
    def Boolean(a: NodeId, b: NodeId, mode: BooleanMode) -> GeometryNode: ...
    @staticmethod
    def OutputMesh(input: NodeId) -> GeometryNode: ...
    def variant(self) -> str: ...

class PrimitiveKind:
    @staticmethod
    def Cube(size: float) -> PrimitiveKind: ...
    @staticmethod
    def UvSphere(segments: int, rings: int, radius: float) -> PrimitiveKind: ...
    @staticmethod
    def Cylinder(segments: int, radius: float, height: float) -> PrimitiveKind: ...
    def variant(self) -> str: ...

class ProceduralError:
    @staticmethod
    def NoOutput() -> ProceduralError: ...
    @staticmethod
    def BadNode(a0: NodeId) -> ProceduralError: ...
    @staticmethod
    def Cycle(a0: NodeId) -> ProceduralError: ...
    def variant(self) -> str: ...

class Falloff:
    def weight(self, t: float) -> float: ...
    @staticmethod
    def Smooth() -> Falloff: ...
    @staticmethod
    def Sphere() -> Falloff: ...
    @staticmethod
    def Root() -> Falloff: ...
    @staticmethod
    def InverseSquare() -> Falloff: ...
    @staticmethod
    def Sharp() -> Falloff: ...
    @staticmethod
    def Linear() -> Falloff: ...
    @staticmethod
    def Constant() -> Falloff: ...
    @staticmethod
    def Random() -> Falloff: ...
    def variant(self) -> str: ...

class Htr10Conus:
    discharge_tube_radius: float
    discharge_tube_height: float
    conus_height: float
    def __init__(self, discharge_tube_radius: float, discharge_tube_height: float, conus_height: float) -> None: ...

class Htr10CoreDimensions:
    cavity_radius: float
    cavity_height: float
    side_reflector_thickness: float
    conus: Htr10Conus | None
    @staticmethod
    def iaea_benchmark() -> Htr10CoreDimensions: ...
    @staticmethod
    def illustrative_with_conus(conus: Htr10Conus) -> Htr10CoreDimensions: ...
    def __init__(self, cavity_radius: float, cavity_height: float, side_reflector_thickness: float, conus: Htr10Conus | None) -> None: ...

class VoxelGrid:
    origin: Vec3
    cell: float
    dims: list[int]
    occ: list[bool]
    def get(self, x: int, y: int, z: int) -> bool: ...
    def cell_center(self, x: int, y: int, z: int) -> Vec3: ...
    def occupied_count(self) -> int: ...

class Axis:
    @staticmethod
    def X() -> Axis: ...
    @staticmethod
    def Y() -> Axis: ...
    @staticmethod
    def Z() -> Axis: ...
    def variant(self) -> str: ...

class Element:
    @staticmethod
    def Vertex(a0: VertexId) -> Element: ...
    @staticmethod
    def Edge(a0: EdgeId) -> Element: ...
    @staticmethod
    def Face(a0: FaceId) -> Element: ...
    def variant(self) -> str: ...

class NonManifoldKinds:
    wire: bool
    boundary: bool
    multiple_faces: bool
    @staticmethod
    def all() -> NonManifoldKinds: ...
    def __init__(self, wire: bool | None = None, boundary: bool | None = None, multiple_faces: bool | None = None) -> None: ...
    @staticmethod
    def default() -> NonManifoldKinds: ...

class NumberCompare:
    @staticmethod
    def Equal() -> NumberCompare: ...
    @staticmethod
    def NotEqual() -> NumberCompare: ...
    @staticmethod
    def Less() -> NumberCompare: ...
    @staticmethod
    def Greater() -> NumberCompare: ...
    def variant(self) -> str: ...

class RegionMode:
    @staticmethod
    def Touching() -> RegionMode: ...
    @staticmethod
    def Enclosed() -> RegionMode: ...
    def variant(self) -> str: ...

class SelectMode:
    @staticmethod
    def Vertex() -> SelectMode: ...
    @staticmethod
    def Edge() -> SelectMode: ...
    @staticmethod
    def Face() -> SelectMode: ...
    def variant(self) -> str: ...

class Selection:
    def __init__(self, mode: SelectMode) -> None: ...
    @staticmethod
    def all(mesh: Mesh, mode: SelectMode) -> Selection: ...
    def mode(self) -> SelectMode: ...
    def vertex_count(self) -> int: ...
    def edge_count(self) -> int: ...
    def face_count(self) -> int: ...
    def is_empty(self) -> bool: ...
    def is_selected(self, e: Element) -> bool: ...
    def select(self, mesh: Mesh, e: Element) -> None: ...
    def deselect(self, mesh: Mesh, e: Element) -> None: ...
    def toggle(self, mesh: Mesh, e: Element) -> None: ...
    def select_all(self, mesh: Mesh) -> None: ...
    def deselect_all(self) -> None: ...
    def invert(self, mesh: Mesh) -> None: ...
    def set_mode(self, mesh: Mesh, mode: SelectMode) -> None: ...
    def union(self, mesh: Mesh, other: Selection) -> None: ...
    def subtract(self, mesh: Mesh, other: Selection) -> None: ...
    def intersect(self, mesh: Mesh, other: Selection) -> None: ...
    def select_in_box(self, mesh: Mesh, min: Vec3, max: Vec3, region: RegionMode) -> None: ...
    def select_in_sphere(self, mesh: Mesh, center: Vec3, radius: float, region: RegionMode) -> None: ...
    def select_linked(self, mesh: Mesh) -> None: ...
    def select_linked_from(self, mesh: Mesh, seed: Element) -> None: ...
    def select_edge_loop(self, mesh: Mesh, seed: EdgeId) -> None: ...
    def select_edge_ring(self, mesh: Mesh, seed: EdgeId) -> None: ...
    def select_face_loop(self, mesh: Mesh, seed: EdgeId) -> None: ...
    def select_boundary_loop(self, mesh: Mesh, seed: EdgeId) -> None: ...
    def select_shortest_path(self, mesh: Mesh, from_: Element, to: Element) -> None: ...
    def select_more(self, mesh: Mesh) -> None: ...
    def select_less(self, mesh: Mesh) -> None: ...
    def select_similar(self, mesh: Mesh, trait_: SimilarTrait, threshold: float) -> None: ...
    def checker_deselect(self, mesh: Mesh, selected: int, deselected: int, offset: int) -> None: ...
    def select_non_manifold(self, mesh: Mesh, kinds: NonManifoldKinds) -> None: ...
    def select_loose(self, mesh: Mesh) -> None: ...
    def select_interior_faces(self, mesh: Mesh) -> None: ...
    def select_faces_by_sides(self, mesh: Mesh, sides: int, cmp: NumberCompare) -> None: ...
    def select_mirror(self, mesh: Mesh, axis: Axis, merge_dist: float, extend: bool) -> None: ...

class SimilarTrait:
    @staticmethod
    def VertexValence() -> SimilarTrait: ...
    @staticmethod
    def EdgeLength() -> SimilarTrait: ...
    @staticmethod
    def EdgeDirection() -> SimilarTrait: ...
    @staticmethod
    def EdgeFaceCount() -> SimilarTrait: ...
    @staticmethod
    def FaceArea() -> SimilarTrait: ...
    @staticmethod
    def FaceSides() -> SimilarTrait: ...
    @staticmethod
    def FacePerimeter() -> SimilarTrait: ...
    @staticmethod
    def FaceNormal() -> SimilarTrait: ...
    @staticmethod
    def FaceCoplanar() -> SimilarTrait: ...
    def variant(self) -> str: ...

class SnapBase:
    @staticmethod
    def Closest() -> SnapBase: ...
    @staticmethod
    def Center() -> SnapBase: ...
    @staticmethod
    def Median() -> SnapBase: ...
    @staticmethod
    def Active(a0: VertexId) -> SnapBase: ...
    def variant(self) -> str: ...

class SnapElement:
    @staticmethod
    def Vertex(a0: VertexId) -> SnapElement: ...
    @staticmethod
    def Edge(a0: EdgeId) -> SnapElement: ...
    @staticmethod
    def Face(a0: FaceId) -> SnapElement: ...
    def variant(self) -> str: ...

class SnapHit:
    position: Vec3
    element: SnapElement | None
    def __init__(self, position: Vec3, element: SnapElement | None) -> None: ...

class SnapTarget:
    @staticmethod
    def Increment(a0: float) -> SnapTarget: ...
    @staticmethod
    def Vertex() -> SnapTarget: ...
    @staticmethod
    def EdgeMidpoint() -> SnapTarget: ...
    @staticmethod
    def EdgeNearest() -> SnapTarget: ...
    @staticmethod
    def FaceNearest() -> SnapTarget: ...
    def variant(self) -> str: ...

class LinePoint:
    position: Vec3
    on: SnapElement | None
    def __init__(self, position: Vec3, on: SnapElement | None) -> None: ...

class LineTool:
    def __init__(self, ) -> None: ...
    def points(self) -> list[LinePoint]: ...
    def is_closed(self) -> bool: ...
    def add_raw(self, position: Vec3) -> None: ...
    def add_snapped(self, mesh: Mesh, cursor: Vec3, target: SnapTarget, max_dist: float) -> None: ...
    def add_polar(self, plane: WorkPlane, length: float, angle: float) -> None: ...
    def add_constrained(self, mesh: Mesh, cursor: Vec3, target: SnapTarget, max_dist: float, plane: WorkPlane, length: float | None, angle: float | None) -> None: ...
    def undo(self) -> None: ...
    def close(self) -> None: ...
    def segment_count(self) -> int: ...
    def commit_wire(self, base: Mesh) -> Mesh: ...
    def auto_cut_chords(self, mesh: Mesh) -> list[Chord]: ...
    @staticmethod
    def default() -> LineTool: ...

class StlError:
    @staticmethod
    def Truncated(a0: int) -> StlError: ...
    @staticmethod
    def BadBinaryLength(got: int, expected: int) -> StlError: ...
    @staticmethod
    def Parse(a0: str) -> StlError: ...
    def variant(self) -> str: ...

class SubdivideOptions:
    cuts: int
    smoothness: float
    fractal: float
    seed: int
    def __init__(self, cuts: int | None = None, smoothness: float | None = None, fractal: float | None = None, seed: int | None = None) -> None: ...
    @staticmethod
    def default() -> SubdivideOptions: ...

class Font:
    default_advance: float
    def glyph(self, c: str) -> Glyph | None: ...
    @staticmethod
    def builtin_stroke() -> Font: ...
    def __init__(self) -> None: ...
    @staticmethod
    def default() -> Font: ...

class Glyph:
    contours: list[list[list[float]]]
    advance: float

class TextGeometry:
    size: float
    tracking: float
    extrude: float
    bevel: float
    def __init__(self, size: float | None = None, tracking: float | None = None, extrude: float | None = None, bevel: float | None = None) -> None: ...
    @staticmethod
    def default() -> TextGeometry: ...

class MeshTopology:
    def __init__(self, mesh: Mesh) -> None: ...
    def edge_faces(self, e: EdgeId) -> list[FaceId]: ...
    def vertex_edges(self, v: VertexId) -> list[EdgeId]: ...
    def vertex_faces(self, v: VertexId) -> list[FaceId]: ...
    def is_boundary_edge(self, e: EdgeId) -> bool: ...
    def is_manifold_edge(self, e: EdgeId) -> bool: ...
    def edge_between(self, a: VertexId, b: VertexId) -> EdgeId | None: ...
    def other_end(self, mesh: Mesh, e: EdgeId, v: VertexId) -> VertexId | None: ...
    def is_quad(self, mesh: Mesh, f: FaceId) -> bool: ...
    def face_edges(self, mesh: Mesh, f: FaceId) -> list[EdgeId]: ...
    def opposite_edge_in_face(self, mesh: Mesh, f: FaceId, e: EdgeId) -> EdgeId | None: ...
    def edge_loop_step(self, edge: EdgeId, pivot: VertexId) -> EdgeId | None: ...
    def edge_ring_step(self, mesh: Mesh, edge: EdgeId, face: FaceId) -> tuple[EdgeId, FaceId | None] | None: ...

class Affine3:
    linear: list[list[float]]
    translation: Vec3
    @staticmethod
    def scale(sx: float, sy: float, sz: float) -> Affine3: ...
    def transform_point(self, p: Vec3) -> Vec3: ...
    def transform_points(self, positions: list[Vec3]) -> list[Vec3]: ...
    def transform_points_best_effort(self, positions: list[Vec3]) -> list[Vec3]: ...

class Constraint:
    @staticmethod
    def Free() -> Constraint: ...
    @staticmethod
    def Axis(a0: int) -> Constraint: ...
    @staticmethod
    def Plane(a0: int) -> Constraint: ...
    def variant(self) -> str: ...

class NumericEntry:
    x: float | None
    y: float | None
    z: float | None
    @staticmethod
    def parse(s: str) -> NumericEntry | None: ...
    def __init__(self, x: float | None = None, y: float | None = None, z: float | None = None) -> None: ...
    @staticmethod
    def default() -> NumericEntry: ...

class TransformBasis:
    x: Vec3
    y: Vec3
    z: Vec3
    @staticmethod
    def from_normal(normal: Vec3) -> TransformBasis: ...
    def __init__(self, x: Vec3, y: Vec3, z: Vec3) -> None: ...

class transform_ops_Axis:
    @staticmethod
    def X() -> transform_ops_Axis: ...
    @staticmethod
    def Y() -> transform_ops_Axis: ...
    @staticmethod
    def Z() -> transform_ops_Axis: ...
    def variant(self) -> str: ...

def arap_deform(mesh: Mesh, handles: list[tuple[VertexId, Vec3]], iterations: int) -> Mesh: ...
def arap_energy(rest: Mesh, deformed: list[Vec3]) -> float: ...
def array_along_curve(mesh: Mesh, spline: Spline, count: int, align_axis: Axis) -> Mesh: ...
def array_along_curve_capped(mesh: Mesh, spline: Spline, count: int, align_axis: Axis, caps: ArrayCaps) -> Mesh: ...
def circular_array(mesh: Mesh, count: int, axis: Vec3, center: Vec3) -> Mesh: ...
def object_offset_array(mesh: Mesh, count: int, offset: Affine3) -> Mesh: ...
def object_offset_array_capped(mesh: Mesh, count: int, offset: Affine3, caps: ArrayCaps) -> Mesh: ...
def radial_array(mesh: Mesh, count: int, step_angle: float, axis: Vec3, center: Vec3) -> Mesh: ...
def radial_array_capped(mesh: Mesh, count: int, step_angle: float, axis: Vec3, center: Vec3, caps: ArrayCaps) -> Mesh: ...
def bevel(mesh: Mesh, opts: BevelOptions) -> Mesh: ...
def bisect(mesh: Mesh, point: Vec3, normal: Vec3) -> Mesh: ...
def boolean(a: Mesh, b: Mesh, mode: BooleanMode) -> Mesh: ...
def classify_point(mesh: Mesh, p: Vec3) -> PointClass: ...
def winding_number(mesh: Mesh, p: Vec3) -> float: ...
def boolean_general(a: Mesh, b: Mesh, mode: BooleanMode) -> Mesh: ...
def incircle(a: Vec2, b: Vec2, c: Vec2, d: Vec2) -> int: ...
def incircle_fast(a: Vec2, b: Vec2, c: Vec2, d: Vec2) -> int: ...
def insphere(a: Vec3, b: Vec3, c: Vec3, d: Vec3, e: Vec3) -> int: ...
def insphere_fast(a: Vec3, b: Vec3, c: Vec3, d: Vec3, e: Vec3) -> int: ...
def orient2d(a: Vec2, b: Vec2, c: Vec2) -> int: ...
def orient2d_fast(a: Vec2, b: Vec2, c: Vec2) -> int: ...
def orient3d(a: Vec3, b: Vec3, c: Vec3, d: Vec3) -> int: ...
def orient3d_fast(a: Vec3, b: Vec3, c: Vec3, d: Vec3) -> int: ...
def align_by_nearest(mesh: Mesh, ring_a: list[VertexId], ring_b: list[VertexId]) -> list[VertexId]: ...
def bridge_edge_loops(mesh: Mesh, ring_a: list[VertexId], ring_b: list[VertexId], closed: bool, opts: BridgeOptions) -> Mesh: ...
def ordered_ring(mesh: Mesh, edges: list[EdgeId]) -> tuple[list[VertexId], bool] | None: ...
def common_face(mesh: Mesh, a: VertexId, b: VertexId) -> FaceId | None: ...
def connect_vertex_pairs(mesh: Mesh, pairs: list[tuple[VertexId, VertexId]]) -> Mesh: ...
def connect_vertex_path(mesh: Mesh, path: list[VertexId]) -> Mesh: ...
def convex_hull(points: list[Vec3]) -> Mesh: ...
def orientation_from_selection(mesh: Mesh, verts: list[VertexId], edges: list[EdgeId], faces: list[FaceId]) -> TransformBasis | None: ...
def pivot_position(mesh: Mesh, verts: list[VertexId], pivot: PivotPoint, cursor: Vec3) -> Vec3: ...
def rotate_about_pivot(mesh: Mesh, verts: list[VertexId], pivot: PivotPoint, axis: Axis, angle: float, cursor: Vec3) -> Mesh: ...
def scale_about_pivot(mesh: Mesh, verts: list[VertexId], pivot: PivotPoint, factor: float, cursor: Vec3) -> Mesh: ...
def selection_to_cursor(mesh: Mesh, verts: list[VertexId], cursor: Vec3) -> Vec3: ...
def boundary_to_splines(mesh: Mesh) -> list[Spline]: ...
def is_poly(s: Spline) -> bool: ...
def mesh_to_splines(mesh: Mesh) -> list[Spline]: ...
def skin_spline(spline: Spline, radius: float, segments: int) -> Mesh: ...
def spline_deform_mesh(mesh: Mesh, spline: Spline, axis: Axis) -> Mesh: ...
def spline_to_mesh(spline: Spline, tube_radius: float | None) -> Mesh: ...
def curve_to_mesh(spline: Spline, opts: CurveGeometry) -> Mesh: ...
def decimate(mesh: Mesh, target_faces: int) -> Mesh: ...
def decimate_with_reason(mesh: Mesh, target_faces: int) -> DecimateResult: ...
def bind_to_surface(mesh: Mesh, target: Mesh) -> SurfaceBind: ...
def curve_deform(mesh: Mesh, curve: list[Vec3], axis: Axis) -> Mesh: ...
def hook(mesh: Mesh, verts: list[VertexId], from_: Vec3, to: Vec3, falloff_radius: float) -> Mesh: ...
def laplacian_deform(mesh: Mesh, handles: list[tuple[VertexId, Vec3]], iterations: int) -> Mesh: ...
def lattice_deform(mesh: Mesh, lat: Lattice) -> Mesh: ...
def shrinkwrap(mesh: Mesh, target: Mesh, mode: ShrinkMode, factor: float) -> Mesh: ...
def surface_deform(mesh: Mesh, bind: SurfaceBind, deformed_target: Mesh) -> Mesh: ...
def cast(mesh: Mesh, verts: list[VertexId], target: CastTarget, factor: float) -> Mesh: ...
def displace(mesh: Mesh, verts: list[VertexId], direction: Vec3, strength: float, noise_scale: float, seed: int) -> Mesh: ...
def simple_deform(mesh: Mesh, verts: list[VertexId], mode: SimpleDeform, axis: Axis) -> Mesh: ...
def warp(mesh: Mesh, verts: list[VertexId], from_: Vec3, from2: Vec3, to: Vec3, to2: Vec3, falloff_radius: float) -> Mesh: ...
def wave(mesh: Mesh, verts: list[VertexId], axis: Axis, amplitude: float, wavelength: float, speed: float, time: float) -> Mesh: ...
def delete(mesh: Mesh, mode: DeleteMode, verts: list[VertexId], edges: list[EdgeId], faces: list[FaceId]) -> Mesh: ...
def dissolve_edges(mesh: Mesh, edges: list[EdgeId]) -> Mesh: ...
def dissolve_faces(mesh: Mesh, faces: list[FaceId]) -> Mesh: ...
def dissolve_vertices(mesh: Mesh, verts: list[VertexId]) -> Mesh: ...
def limited_dissolve(mesh: Mesh, angle: float) -> Mesh: ...
def box_from_drag(plane: WorkPlane, corner_a: Vec3, corner_b: Vec3, depth: float) -> Mesh: ...
def circle_from_drag(plane: WorkPlane, center: Vec3, rim: Vec3, depth: float, segments: int) -> Mesh: ...
def cone_from_drag(plane: WorkPlane, center: Vec3, rim: Vec3, depth: float, segments: int) -> Mesh: ...
def eval_dimension(s: str) -> float | None: ...
def snap_input(mesh: Mesh, p: Vec3, target: SnapTarget, max_dist: float) -> Vec3: ...
def bevel_edges(mesh: Mesh, width: float) -> Mesh: ...
def edge_split(mesh: Mesh, edges: list[EdgeId]) -> Mesh: ...
def rotate_edge(mesh: Mesh, edge: EdgeId, cw: bool) -> Mesh: ...
def set_edge_flow(mesh: Mesh, loop_edges: list[EdgeId], iterations: int, strength: float) -> Mesh: ...
def to_csg_primitive(mesh: Mesh) -> CsgDescription: ...
def to_faceted_solid(mesh: Mesh) -> FacetedSolid: ...
def to_faceted_solid_checked(mesh: Mesh) -> FacetedSolid: ...
def to_polymesh_text(mesh: Mesh) -> PolyMeshText: ...
def triangulate(mesh: Mesh) -> IndexedTriangles: ...
def capsule(radius: float, length: float, segments: int, rings: int) -> Mesh: ...
def elbow(outer: float, wall: float, bend_radius: float, angle: float, arc_segments: int, tube_segments: int) -> Mesh: ...
def honeycomb(rows: int, cols: int, cell_radius: float) -> Mesh: ...
def pipe(outer: float, wall: float, length: float, segments: int) -> Mesh: ...
def rounded_cube(size: float, radius: float, segments: int) -> Mesh: ...
def spur_gear(teeth: int, root_radius: float, tooth_height: float, width: float, tooth_frac: float) -> Mesh: ...
def star(points: int, outer_radius: float, inner_radius: float, depth: float) -> Mesh: ...
def wedge(size_x: float, size_y: float, size_z: float) -> Mesh: ...
def extrude_faces_along_normals(mesh: Mesh, faces: list[FaceId], amount: float) -> Mesh: ...
def extrude_faces_individual(mesh: Mesh, faces: list[FaceId], amount: float) -> Mesh: ...
def extrude_manifold(mesh: Mesh, faces: list[FaceId], offset: Vec3) -> Mesh: ...
def extrude_vertices(mesh: Mesh, verts: list[VertexId], offset: Vec3) -> Mesh: ...
def selection_boundary_edges(mesh: Mesh, faces: list[FaceId]) -> list[EdgeId]: ...
def beauty_fill(mesh: Mesh) -> Mesh: ...
def grid_fill(mesh: Mesh, boundary: list[VertexId], span: int) -> Mesh: ...
def make_face(mesh: Mesh, verts: list[VertexId]) -> Mesh: ...
def auto_mirror(mesh: Mesh, plane: WorkPlane, weld_dist: float) -> Mesh: ...
def bsurfaces(strokes: list[list[Vec3]], cols: int) -> Mesh: ...
def f2_fill(mesh: Mesh, edge: EdgeId) -> Mesh: ...
def fill_holes(mesh: Mesh) -> Mesh: ...
def probe() -> GpuContext | None: ...
def inset_faces(mesh: Mesh, amount: float) -> Mesh: ...
def knife(mesh: Mesh, chords: list[Chord]) -> KnifeResult: ...
def boundary_vertices(mesh: Mesh) -> list[bool]: ...
def laplacian_smooth(mesh: Mesh, weighting: LaplacianWeighting, lambda_: float, iterations: int) -> Mesh: ...
def laplacian_triplets(mesh: Mesh, weighting: LaplacianWeighting) -> tuple[int, list[tuple[int, int, float]]]: ...
def taubin_smooth(mesh: Mesh, weighting: LaplacianWeighting, lambda_: float, mu: float, iterations: int) -> Mesh: ...
def loop_cut(mesh: Mesh, seed: EdgeId, cuts: int, factor: float) -> LoopCutResult: ...
def loop_subdivide(mesh: Mesh, iterations: int) -> Mesh: ...
def bridge(mesh: Mesh, loop_a: list[VertexId], loop_b: list[VertexId], cyclic: bool) -> Mesh: ...
def circle(mesh: Mesh, loop_verts: list[VertexId], _cyclic: bool) -> Mesh: ...
def curve(mesh: Mesh, loop_verts: list[VertexId], cyclic: bool, keep: int, factor: float) -> Mesh: ...
def flatten(mesh: Mesh, loop_verts: list[VertexId]) -> Mesh: ...
def gstretch(mesh: Mesh, loop_verts: list[VertexId], stroke: list[Vec3], cyclic: bool) -> Mesh: ...
def relax(mesh: Mesh, loop_verts: list[VertexId], cyclic: bool, iterations: int, factor: float) -> Mesh: ...
def space(mesh: Mesh, loop_verts: list[VertexId], cyclic: bool) -> Mesh: ...
def subdivide(mesh: Mesh, loop_verts: list[VertexId], cyclic: bool) -> Mesh: ...
def bounding_box(mesh: Mesh) -> tuple[Vec3, Vec3]: ...
def corner_angle(mesh: Mesh, f: FaceId, v: VertexId) -> float | None: ...
def dihedral_angle(mesh: Mesh, e: EdgeId) -> float | None: ...
def dimensions(mesh: Mesh) -> Vec3: ...
def distortion(mesh: Mesh, f: FaceId) -> float: ...
def edge_length(mesh: Mesh, e: EdgeId) -> float: ...
def face_area(mesh: Mesh, f: FaceId) -> float: ...
def face_perimeter(mesh: Mesh, f: FaceId) -> float: ...
def overhang(mesh: Mesh, f: FaceId, up: Vec3) -> float: ...
def self_intersections(mesh: Mesh) -> list[tuple[FaceId, FaceId]]: ...
def sharp_edges(mesh: Mesh, angle: float) -> list[EdgeId]: ...
def signed_volume(mesh: Mesh) -> float: ...
def thickness(mesh: Mesh, f: FaceId) -> float | None: ...
def total_edge_length(mesh: Mesh) -> float: ...
def total_surface_area(mesh: Mesh) -> float: ...
def merge_by_distance(mesh: Mesh, verts: list[VertexId], threshold: float) -> Mesh: ...
def merge_edges(mesh: Mesh, edges: list[EdgeId]) -> Mesh: ...
def merge_vertices(mesh: Mesh, verts: list[VertexId], target: MergeTarget) -> Mesh: ...
def flip_faces(mesh: Mesh, faces: list[FaceId]) -> Mesh: ...
def harden_normals(mesh: Mesh, faces: list[FaceId], angle: float) -> SplitNormals: ...
def point_normals_to_target(mesh: Mesh, target: Vec3, invert: bool) -> list[Vec3]: ...
def recalculate(mesh: Mesh, outside: bool) -> Mesh: ...
def split_normals_by_angle(mesh: Mesh, angle: float) -> SplitNormals: ...
def vertex_normals(mesh: Mesh, weight: NormalWeight) -> list[Vec3]: ...
def align(objects: list[SceneObject], axis: Axis, mode: AlignMode) -> list[SceneObject]: ...
def cursor_to_objects(objects: list[SceneObject]) -> Vec3: ...
def join(objects: list[SceneObject]) -> SceneObject: ...
def separate_loose_parts(object: SceneObject) -> list[SceneObject]: ...
def snap_objects(objects: list[SceneObject], to: SnapObjectsTo) -> list[SceneObject]: ...
def bevel_vertices(mesh: Mesh, width: float) -> Mesh: ...
def bevel_vertices_rounded(mesh: Mesh, width: float, segments: int) -> Mesh: ...
def extrude_edges(mesh: Mesh, edges: list[EdgeId], offset: Vec3) -> Mesh: ...
def extrude_faces(mesh: Mesh, faces: list[FaceId], offset: Vec3) -> Mesh: ...
def subdivide(mesh: Mesh, iterations: int) -> Mesh: ...
def flatten_to_plane(mesh: Mesh, weighting: LaplacianWeighting, boundary: BoundaryShape) -> Mesh: ...
def parameterize(mesh: Mesh, weighting: LaplacianWeighting, boundary: BoundaryShape) -> list[tuple[float, float]]: ...
def angle_between(a: Vec3, vertex: Vec3, b: Vec3) -> float: ...
def fillet(prev: Vec3, corner: Vec3, next: Vec3, radius: float, segments: int) -> list[Vec3]: ...
def line_line_intersection(a0: Vec3, a1: Vec3, b0: Vec3, b1: Vec3) -> Vec3 | None: ...
def mirror_point(p: Vec3, plane: WorkPlane) -> Vec3: ...
def mirror_vertices(mesh: Mesh, verts: list[VertexId], plane: WorkPlane) -> Mesh: ...
def offset_polyline(pts: list[Vec3], plane_normal: Vec3, distance: float, cyclic: bool) -> list[Vec3]: ...
def place_vertex(mesh: Mesh, placement: Placement) -> tuple[Mesh, VertexId]: ...
def taper(points: list[Vec3], axis: Vec3, rate: float, pivot: Vec3) -> list[Vec3]: ...
def three_point_arc(p0: Vec3, p1: Vec3, p2: Vec3, segments: int) -> list[Vec3]: ...
def three_point_circle(p0: Vec3, p1: Vec3, p2: Vec3) -> tuple[Vec3, float, Vec3] | None: ...
def poke_faces(mesh: Mesh, offset: float) -> Mesh: ...
def triangulate_quads(mesh: Mesh, method: QuadMethod) -> Mesh: ...
def tris_to_quads(mesh: Mesh, max_angle: float) -> Mesh: ...
def cube(size: float) -> Mesh: ...
def cylinder(segments: int, radius: float, height: float) -> Mesh: ...
def grid(nx: int, ny: int, size: float) -> Mesh: ...
def uv_sphere(segments: int, rings: int, radius: float) -> Mesh: ...
def circle(segments: int, radius: float, fill: bool) -> Mesh: ...
def cone(segments: int, radius1: float, radius2: float, height: float) -> Mesh: ...
def icosphere(subdivisions: int, radius: float) -> Mesh: ...
def plane(size: float) -> Mesh: ...
def torus(major_segments: int, minor_segments: int, major_radius: float, minor_radius: float) -> Mesh: ...
def proportional_move(mesh: Mesh, grabbed: list[tuple[VertexId, Vec3]], radius: float, falloff: Falloff, connected_only: bool, seed: int) -> Mesh: ...
def htr10_core_envelope(dims: Htr10CoreDimensions, segments: int) -> Mesh: ...
def recalculate_normals(mesh: Mesh) -> Mesh: ...
def mesh_to_volume(mesh: Mesh, cell: float) -> VoxelGrid: ...
def volume_to_mesh(grid: VoxelGrid) -> Mesh: ...
def voxel_remesh(mesh: Mesh, cell: float, smooth_iters: int) -> Mesh: ...
def revolve(profile: list[Vec3], axis_point: Vec3, axis_dir: Vec3, segments: int, angle: float) -> Mesh: ...
def rip_edges(mesh: Mesh, edges: list[EdgeId]) -> Mesh: ...
def separate_loose_parts(mesh: Mesh) -> list[Mesh]: ...
def separate_selection(mesh: Mesh, faces: list[FaceId]) -> tuple[Mesh, Mesh]: ...
def split_faces(mesh: Mesh, faces: list[FaceId]) -> Mesh: ...
def edge_slide(mesh: Mesh, edges: list[EdgeId], factor: float) -> Mesh: ...
def vertex_slide(mesh: Mesh, vert: VertexId, along_edge: EdgeId, factor: float) -> Mesh: ...
def align_rotation_target(mesh: Mesh, hit: SnapHit) -> Vec3 | None: ...
def snap_point(mesh: Mesh, query: Vec3, target: SnapTarget, max_dist: float, exclude: list[VertexId]) -> SnapHit | None: ...
def snap_translation(mesh: Mesh, moving: list[VertexId], raw_delta: Vec3, base: SnapBase, target: SnapTarget, max_dist: float) -> Vec3: ...
def solidify(mesh: Mesh, thickness: float) -> Mesh: ...
def screw(mesh: Mesh, profile: list[VertexId], center: Vec3, axis: Axis, screw_offset: float, turns: float, steps: int) -> Mesh: ...
def spin(mesh: Mesh, profile: list[VertexId], center: Vec3, axis: Axis, angle: float, steps: int, use_duplicates: bool) -> Mesh: ...
def from_stl_ascii(text: str) -> Mesh: ...
def from_stl_binary(bytes: list[int]) -> Mesh: ...
def from_stl_bytes(bytes: list[int]) -> Mesh: ...
def read_stl(path: str) -> Mesh: ...
def to_stl_ascii(mesh: Mesh) -> str: ...
def to_stl_binary(mesh: Mesh) -> list[int]: ...
def subdivide(mesh: Mesh, opts: SubdivideOptions) -> Mesh: ...
def un_subdivide(mesh: Mesh, iterations: int) -> Mesh: ...
def catmull_clark(mesh: Mesh, levels: int) -> Mesh: ...
def mirror_selection(mesh: Mesh, verts: list[VertexId], axis: Axis, tolerance: float) -> list[VertexId]: ...
def snap_to_symmetry(mesh: Mesh, axis: Axis, match_threshold: float) -> Mesh: ...
def symmetrize(mesh: Mesh, axis: Axis, keep_positive: bool, merge_threshold: float) -> Mesh: ...
def text_to_contours(text: str, font: Font, size: float, tracking: float) -> list[list[list[float]]]: ...
def text_to_mesh(text: str, font: Font, opts: TextGeometry) -> Mesh: ...
def boundary_loop(topo: MeshTopology, mesh: Mesh, seed: EdgeId) -> list[EdgeId]: ...
def edge_loop(topo: MeshTopology, mesh: Mesh, seed: EdgeId) -> list[EdgeId]: ...
def edge_ring(topo: MeshTopology, mesh: Mesh, seed: EdgeId) -> list[EdgeId]: ...
def face_loop(topo: MeshTopology, mesh: Mesh, seed: EdgeId) -> list[FaceId]: ...
def shortest_vertex_path(topo: MeshTopology, mesh: Mesh, from_: VertexId, to: VertexId) -> list[VertexId]: ...
def apply_translation(mesh: Mesh, verts: list[VertexId], delta: Vec3) -> Mesh: ...
def eval_expr(s: str) -> float | None: ...
def resolve_translation(raw_delta: Vec3, constraint: Constraint, basis: TransformBasis, numeric: NumericEntry, increment: float | None) -> Vec3: ...
def bend(mesh: Mesh, verts: list[VertexId], center: Vec3, along: transform_ops_Axis, axis: transform_ops_Axis, angle: float) -> Mesh: ...
def push_pull(mesh: Mesh, verts: list[VertexId], center: Vec3, distance: float) -> Mesh: ...
def randomize(mesh: Mesh, verts: list[VertexId], amount: float, seed: int, uniform: bool) -> Mesh: ...
def shear(mesh: Mesh, verts: list[VertexId], measure_axis: transform_ops_Axis, shear_axis: transform_ops_Axis, factor: float) -> Mesh: ...
def shrink_fatten(mesh: Mesh, verts: list[VertexId], offset: float) -> Mesh: ...
def to_sphere(mesh: Mesh, verts: list[VertexId], center: Vec3, radius: float, factor: float) -> Mesh: ...
def warp(mesh: Mesh, verts: list[VertexId], center: Vec3, along: transform_ops_Axis, axis: transform_ops_Axis, angle: float) -> Mesh: ...
def triangulate(mesh: Mesh) -> Mesh: ...
def weld(mesh: Mesh, distance: float) -> Mesh: ...
DEFAULT_SEGMENTS: int
