"""Type stubs for `outram_park.outram_park_mpi`, generated from the Rust API.

Physical quantities cross this boundary as `float` in SI base units.
"""

class CartesianComm:
    def comm(self) -> Communicator: ...
    def dims(self) -> list[int]: ...
    def periods(self) -> list[bool]: ...
    def my_coords(self) -> list[int]: ...
    def coords(self, rank: int) -> list[int]: ...
    def rank(self, coords: list[int]) -> int | None: ...
    def shift(self, direction: int, disp: int) -> tuple[int | None, int | None]: ...

class Communicator:
    def cart_create(self, dims: list[int], periods: list[bool]) -> CartesianComm | None: ...
    def group(self) -> Group: ...
    def create_from_group(self, group: Group) -> Communicator | None: ...
    def rank(self) -> int: ...
    def size(self) -> int: ...
    def dup(self) -> Communicator: ...
    def split(self, color: int, key: int) -> Communicator | None: ...
    def barrier(self) -> None: ...

class Datatype:
    def size(self) -> int: ...
    @staticmethod
    def I8() -> Datatype: ...
    @staticmethod
    def I16() -> Datatype: ...
    @staticmethod
    def I32() -> Datatype: ...
    @staticmethod
    def I64() -> Datatype: ...
    @staticmethod
    def U8() -> Datatype: ...
    @staticmethod
    def U16() -> Datatype: ...
    @staticmethod
    def U32() -> Datatype: ...
    @staticmethod
    def U64() -> Datatype: ...
    @staticmethod
    def F32() -> Datatype: ...
    @staticmethod
    def F64() -> Datatype: ...
    def variant(self) -> str: ...

class Group:
    def world_ranks(self) -> list[int]: ...
    def size(self) -> int: ...
    def rank_of(self, world_rank: int) -> int | None: ...
    def incl(self, indices: list[int]) -> Group: ...
    def excl(self, indices: list[int]) -> Group: ...
    def union(self, other: Group) -> Group: ...
    def intersection(self, other: Group) -> Group: ...
    def difference(self, other: Group) -> Group: ...
    def translate_ranks(self, ranks: list[int], other: Group) -> list[int | None]: ...

class MpiError:
    @staticmethod
    def InvalidRank(rank: int, size: int) -> MpiError: ...
    @staticmethod
    def Truncated(buffer: int, message: int) -> MpiError: ...
    @staticmethod
    def TypeMismatch(expected: Datatype, actual: Datatype) -> MpiError: ...
    @staticmethod
    def InvalidArgument(a0: str) -> MpiError: ...
    @staticmethod
    def Transport(a0: str) -> MpiError: ...
    def variant(self) -> str: ...

class ReduceOp:
    @staticmethod
    def Sum() -> ReduceOp: ...
    @staticmethod
    def Product() -> ReduceOp: ...
    @staticmethod
    def Max() -> ReduceOp: ...
    @staticmethod
    def Min() -> ReduceOp: ...
    def variant(self) -> str: ...

class Status:
    source: int
    tag: int
    count: int
    def __init__(self, source: int, tag: int, count: int) -> None: ...

ANY_SOURCE: int
ANY_TAG: int
