"""Type stubs for `outram_park.outram_foam_basic_lib`, generated from the Rust API.

Physical quantities cross this boundary as `float` in SI base units.
"""

class ComputeBackend:
    def is_available(self) -> bool: ...
    def resolve(self) -> ComputeBackend: ...
    def label(self) -> str: ...
    @staticmethod
    def Serial() -> ComputeBackend: ...
    @staticmethod
    def CpuMulti() -> ComputeBackend: ...
    @staticmethod
    def Gpu() -> ComputeBackend: ...
    def variant(self) -> str: ...
    @staticmethod
    def default() -> ComputeBackend: ...

class ThreadCount:
    def resolve(self) -> int: ...
    @staticmethod
    def Auto() -> ThreadCount: ...
    @staticmethod
    def Fixed(a0: int) -> ThreadCount: ...
    @staticmethod
    def Fraction(a0: float) -> ThreadCount: ...
    def variant(self) -> str: ...
    @staticmethod
    def default() -> ThreadCount: ...

class Limiter:
    @staticmethod
    def Upwind() -> Limiter: ...
    @staticmethod
    def Linear() -> Limiter: ...
    @staticmethod
    def VanLeer() -> Limiter: ...
    @staticmethod
    def Minmod() -> Limiter: ...
    def variant(self) -> str: ...

class CellSelection:
    @staticmethod
    def zone(cells: list[int]) -> CellSelection: ...
    def cells(self, n_cells: int) -> list[int]: ...
    def len(self, n_cells: int) -> int: ...
    def is_empty(self, n_cells: int) -> bool: ...
    @staticmethod
    def All() -> CellSelection: ...
    def variant(self) -> str: ...

class FvModel:
    def name(self) -> str: ...
    def contributes_to(self, field: str) -> bool: ...
    @staticmethod
    def SemiImplicit(a0: SemiImplicitSource) -> FvModel: ...
    @staticmethod
    def SolidificationMelting(a0: SolidificationMelting) -> FvModel: ...
    @staticmethod
    def SolidificationPorosity(a0: SolidificationPorosity) -> FvModel: ...
    @staticmethod
    def VofSolidificationMelting(a0: VofSolidificationMelting) -> FvModel: ...
    def variant(self) -> str: ...

class FvModels:
    def __init__(self, ) -> None: ...
    def push(self, model: FvModel) -> None: ...
    def models(self) -> list[FvModel]: ...
    def contributes_to(self, field: str) -> bool: ...
    def advance_time(self) -> None: ...
    @staticmethod
    def default() -> FvModels: ...

class MomentumEquationForm:
    @staticmethod
    def Kinematic() -> MomentumEquationForm: ...
    @staticmethod
    def DensityWeighted() -> MomentumEquationForm: ...
    def variant(self) -> str: ...

class SemiImplicitSource:
    def name(self) -> str: ...
    def field_name(self) -> str: ...
    def selection(self) -> CellSelection: ...
    def contribution(self) -> SourceContribution: ...

class SolidificationMelting:
    def name(self) -> str: ...
    def velocity_name(self) -> str: ...
    def energy_name(self) -> str: ...
    def selection(self) -> CellSelection: ...
    def liquid_fraction(self) -> list[float]: ...
    def effective_liquidus(self, liquid_fraction: float) -> float: ...
    def advance_time(self) -> None: ...
    def darcy_coefficient(self, liquid_fraction: float) -> float: ...

class SolidificationMeltingCoefficients:
    solidus: float
    liquidus: float
    latent_heat: float
    eutectic_fraction: float
    darcy_coefficient: float
    darcy_regularisation: float
    thermal_expansion: float
    reference_density: float
    relaxation: float
    specific_heat: float
    def __init__(self, solidus: float, liquidus: float, latent_heat: float, specific_heat: float, reference_density: float, thermal_expansion: float) -> None: ...

class SolidificationPorosity:
    def name(self) -> str: ...
    def velocity_name(self) -> str: ...
    def phase_fraction_name(self) -> str | None: ...
    def selection(self) -> CellSelection: ...
    def drag_table(self) -> TemperatureTable: ...
    def form(self) -> MomentumEquationForm: ...

class SourceContribution:
    explicit: float
    implicit: float
    def __init__(self, explicit: float, implicit: float) -> None: ...
    @staticmethod
    def default() -> SourceContribution: ...

class TemperatureTable:
    def __init__(self, temperatures: list[float], values: list[float]) -> None: ...
    @staticmethod
    def two_knot(t_cold: float, t_hot: float, cold_value: float, hot_value: float) -> TemperatureTable: ...
    def value(self, t: float) -> float: ...
    def temperatures(self) -> list[float]: ...
    def values(self) -> list[float]: ...

class VofSolidificationMelting:
    def with_coefficients(self, relaxation: float, darcy_coefficient: float, darcy_regularisation: float) -> VofSolidificationMelting: ...
    def name(self) -> str: ...
    def velocity_name(self) -> str: ...
    def energy_name(self) -> str: ...
    def selection(self) -> CellSelection: ...
    def solid_fraction(self) -> list[float]: ...
    def advance_time(self) -> None: ...
    def darcy_coefficient(self, fluid_fraction: float) -> float: ...

class Dimensioned:
    dims: list[float]
    value: list[FoamValue]

class FoamCase:
    root: str
    system: list[tuple[str, FoamFile]]
    poly_mesh: PolyMesh | None
    time_dir: str
    fields: list[CaseField]
    skipped_fields: list[tuple[str, str]]
    def system_dict(self, name: str) -> FoamFile | None: ...

class FoamDict:
    def __init__(self, ) -> None: ...
    def get(self, keyword: str) -> FoamEntry | None: ...
    def get_dict(self, keyword: str) -> FoamDict | None: ...
    def get_scalar(self, keyword: str) -> float | None: ...
    def get_word(self, keyword: str) -> str | None: ...
    def len(self) -> int: ...
    def is_empty(self) -> bool: ...
    @staticmethod
    def default() -> FoamDict: ...

class FoamEntry:
    @staticmethod
    def Scalar(a0: float) -> FoamEntry: ...
    @staticmethod
    def Word(a0: str) -> FoamEntry: ...
    @staticmethod
    def Str(a0: str) -> FoamEntry: ...
    @staticmethod
    def Tokens(a0: list[FoamValue]) -> FoamEntry: ...
    @staticmethod
    def List(a0: list[FoamValue]) -> FoamEntry: ...
    @staticmethod
    def Dimensioned(a0: Dimensioned) -> FoamEntry: ...
    @staticmethod
    def SubDict(a0: FoamDict) -> FoamEntry: ...
    def variant(self) -> str: ...

class FoamHeader:
    def __init__(self, ) -> None: ...
    @staticmethod
    def standard(class_: str, object: str) -> FoamHeader: ...
    @staticmethod
    def standard_with_location(class_: str, location: str, object: str) -> FoamHeader: ...
    def get(self, keyword: str) -> str | None: ...
    def object(self) -> str | None: ...
    @staticmethod
    def default() -> FoamHeader: ...

class FoamValue:
    def as_vector3(self) -> Vector3 | None: ...
    def as_scalar(self) -> float | None: ...
    def as_word(self) -> str | None: ...
    @staticmethod
    def Scalar(a0: float) -> FoamValue: ...
    @staticmethod
    def Word(a0: str) -> FoamValue: ...
    @staticmethod
    def Str(a0: str) -> FoamValue: ...
    @staticmethod
    def List(a0: list[FoamValue]) -> FoamValue: ...
    def variant(self) -> str: ...

class IoError:
    @staticmethod
    def Parse(context: str, message: str) -> IoError: ...
    @staticmethod
    def Unsupported(kind: str, name: str, context: str) -> IoError: ...
    @staticmethod
    def Mesh(a0: str) -> IoError: ...
    def variant(self) -> str: ...

class MeshFace:
    verts: list[int]
    owner: int
    neighbour: int | None
    def __init__(self, verts: list[int], owner: int, neighbour: int | None) -> None: ...

class PolyMesh:
    points: list[Vector3]
    faces: list[MeshFace]
    n_internal_faces: int
    n_cells: int
    patches: list[BoundaryPatch]
    def n_points(self) -> int: ...
    def n_faces(self) -> int: ...
    def n_boundary_faces(self) -> int: ...
    def total_volume(self) -> float: ...
    def to_fv_mesh(self) -> FvMesh: ...
    def __init__(self, points: list[Vector3], faces: list[MeshFace], n_internal_faces: int, n_cells: int, patches: list[BoundaryPatch]) -> None: ...

class CaseField:
    def name(self) -> str: ...
    def variant(self) -> str: ...

class FoamFile:
    header: FoamHeader | None
    dict: FoamDict
    @staticmethod
    def parse(text: str) -> FoamFile: ...
    def to_foam_string(self) -> str: ...
    def __init__(self, header: FoamHeader | None, dict: FoamDict) -> None: ...

class Ilu0Preconditioner:
    def __init__(self, a: LduMatrix) -> None: ...

class JacobiPreconditioner:
    def __init__(self, a: LduMatrix) -> None: ...

class KrylovResult:
    n_iterations: int
    final_residual: float
    converged: bool
    def __init__(self, n_iterations: int, final_residual: float, converged: bool) -> None: ...

class KrylovSettings:
    tolerance: float
    max_iter: int
    restart: int
    def __init__(self, tolerance: float, max_iter: int, restart: int) -> None: ...
    @staticmethod
    def default() -> KrylovSettings: ...

class Preconditioner:
    @staticmethod
    def identity() -> Preconditioner: ...
    @staticmethod
    def jacobi(a: LduMatrix) -> Preconditioner: ...
    @staticmethod
    def ilu0(a: LduMatrix) -> Preconditioner: ...
    @staticmethod
    def Identity() -> Preconditioner: ...
    def variant(self) -> str: ...

class FvMatrix:
    ldu: LduMatrix
    def add_face_coeff(self, face: int, coeff: float) -> None: ...
    def set_reference(self, cell: int, value: float) -> None: ...

class FvVectorMatrix:
    ldu: LduMatrix
    def set_reference(self, cell: int, value: Vector3) -> None: ...

class HybridLdu:
    def auto_backend(self) -> ComputeBackend: ...
    def spmv(self, x: list[float], backend: ComputeBackend) -> list[float]: ...
    def residual(self, x: list[float], b: list[float], backend: ComputeBackend) -> list[float]: ...
    def normalised_residual(self, x: list[float], b: list[float], backend: ComputeBackend) -> float: ...
    def diagonal_reciprocal(self, backend: ComputeBackend) -> list[float]: ...

class KrylovMethod:
    @staticmethod
    def BiCGStab() -> KrylovMethod: ...
    @staticmethod
    def Gmres() -> KrylovMethod: ...
    def variant(self) -> str: ...
    @staticmethod
    def default() -> KrylovMethod: ...

class KrylovOptions:
    preconditioner: PreconditionerKind
    restart: int
    backend: ComputeBackend
    @staticmethod
    def with_preconditioner(preconditioner: PreconditionerKind) -> KrylovOptions: ...
    @staticmethod
    def on_backend(backend: ComputeBackend) -> KrylovOptions: ...
    def __init__(self, preconditioner: PreconditionerKind, restart: int, backend: ComputeBackend) -> None: ...
    @staticmethod
    def default() -> KrylovOptions: ...

class LduMatrix:
    n_cells: int
    n_internal_faces: int
    diag: list[float]
    lower: list[float]
    upper: list[float]
    owner: list[int]
    neighbour: list[int]
    def __init__(self, n_cells: int, owner: list[int], neighbour: list[int]) -> None: ...
    def multiply(self, x: list[float]) -> list[float]: ...
    def residual(self, x: list[float], b: list[float]) -> list[float]: ...
    def normalised_residual(self, x: list[float], b: list[float]) -> float: ...

class LduTopology:
    @staticmethod
    def from_matrix(matrix: LduMatrix) -> LduTopology: ...
    def n_cells(self) -> int: ...
    def n_internal_faces(self) -> int: ...
    def incident_face_count(self, c: int) -> int: ...
    def index_bytes(self) -> int: ...
    def matches(self, matrix: LduMatrix) -> bool: ...

class PreconditionerKind:
    def build(self, a: LduMatrix) -> Preconditioner: ...
    @staticmethod
    def None_() -> PreconditionerKind: ...
    @staticmethod
    def Jacobi() -> PreconditionerKind: ...
    @staticmethod
    def Ilu0() -> PreconditionerKind: ...
    def variant(self) -> str: ...
    @staticmethod
    def default() -> PreconditionerKind: ...

class SolverPerformance:
    n_iterations: int
    final_residual: float
    converged: bool
    def __init__(self, n_iterations: int, final_residual: float, converged: bool) -> None: ...

class SolverSettings:
    tolerance: float
    max_iter: int
    def __init__(self, tolerance: float, max_iter: int) -> None: ...
    @staticmethod
    def default() -> SolverSettings: ...

class FluxLimiter:
    def psi(self, r: float) -> float: ...
    def is_tvd(self) -> bool: ...
    def is_symmetric(self) -> bool: ...
    @staticmethod
    def Upwind() -> FluxLimiter: ...
    @staticmethod
    def Linear() -> FluxLimiter: ...
    @staticmethod
    def VanLeer() -> FluxLimiter: ...
    @staticmethod
    def VanAlbada() -> FluxLimiter: ...
    @staticmethod
    def Minmod() -> FluxLimiter: ...
    @staticmethod
    def SuperBee() -> FluxLimiter: ...
    @staticmethod
    def Muscl() -> FluxLimiter: ...
    @staticmethod
    def Umist() -> FluxLimiter: ...
    @staticmethod
    def Ospre() -> FluxLimiter: ...
    @staticmethod
    def LimitedLinear(a0: float) -> FluxLimiter: ...
    def variant(self) -> str: ...

class DerivativeBatch:
    def solutions(self) -> list[DerivativeSolution]: ...
    def into_solutions(self) -> list[DerivativeSolution]: ...
    def len(self) -> int: ...
    def is_empty(self) -> bool: ...
    def get(self, i: int) -> DerivativeSolution | None: ...
    def all_ok(self) -> bool: ...
    def failure_count(self) -> int: ...
    def first_failure(self) -> tuple[int, DerivativeSolution] | None: ...
    def failures(self) -> list[tuple[int, DerivativeSolution]]: ...
    def values(self) -> list[float]: ...

class DerivativeSolution:
    def derivative(self) -> float | None: ...
    def raw_value(self) -> float: ...
    def realised_step(self) -> float: ...
    def status(self) -> DiffStatus: ...
    def is_ok(self) -> bool: ...

class DiffBatchFailure:
    total: int
    failure_count: int
    first_index: int
    first_status: DiffStatus
    def __init__(self, total: int, failure_count: int, first_index: int, first_status: DiffStatus) -> None: ...

class DiffScheme:
    def default_relative_step(self) -> float: ...
    def evaluations_per_derivative(self) -> int: ...
    def evaluations_per_jacobian(self, n: int) -> int: ...
    def label(self) -> str: ...
    @staticmethod
    def Forward() -> DiffScheme: ...
    @staticmethod
    def Backward() -> DiffScheme: ...
    @staticmethod
    def Central() -> DiffScheme: ...
    @staticmethod
    def Central4th() -> DiffScheme: ...
    def variant(self) -> str: ...
    @staticmethod
    def default() -> DiffScheme: ...

class DiffSettings:
    scheme: DiffScheme
    relative_step: float
    min_scale: float
    @staticmethod
    def with_scheme(scheme: DiffScheme) -> DiffSettings: ...
    @staticmethod
    def forward() -> DiffSettings: ...
    @staticmethod
    def backward() -> DiffSettings: ...
    @staticmethod
    def central() -> DiffSettings: ...
    @staticmethod
    def central_4th() -> DiffSettings: ...
    def step_for(self, x: float) -> float: ...
    def __init__(self, scheme: DiffScheme, relative_step: float, min_scale: float) -> None: ...
    @staticmethod
    def default() -> DiffSettings: ...

class DiffStatus:
    def is_ok(self) -> bool: ...
    def label(self) -> str: ...
    @staticmethod
    def Ok() -> DiffStatus: ...
    @staticmethod
    def InvalidPoint() -> DiffStatus: ...
    @staticmethod
    def NotFinite() -> DiffStatus: ...
    @staticmethod
    def DegenerateStep() -> DiffStatus: ...
    @staticmethod
    def DimensionMismatch() -> DiffStatus: ...
    def variant(self) -> str: ...

class JacobianBatch:
    def solutions(self) -> list[JacobianSolution]: ...
    def into_solutions(self) -> list[JacobianSolution]: ...
    def len(self) -> int: ...
    def is_empty(self) -> bool: ...
    def get(self, i: int) -> JacobianSolution | None: ...
    def all_ok(self) -> bool: ...
    def failure_count(self) -> int: ...
    def first_failure(self) -> tuple[int, DiffStatus] | None: ...
    def matrices(self) -> list[SquareMatrix]: ...

class JacobianSolution:
    def matrix(self) -> SquareMatrix | None: ...
    def into_matrix(self) -> SquareMatrix | None: ...
    def raw_matrix(self) -> SquareMatrix: ...
    def status(self) -> DiffStatus: ...
    def is_ok(self) -> bool: ...
    def first_bad_column(self) -> int: ...

class MinBatch:
    def solutions(self) -> list[MinSolution]: ...
    def into_solutions(self) -> list[MinSolution]: ...
    def len(self) -> int: ...
    def is_empty(self) -> bool: ...
    def get(self, i: int) -> MinSolution | None: ...
    def all_converged(self) -> bool: ...
    def failure_count(self) -> int: ...
    def first_failure(self) -> tuple[int, MinSolution] | None: ...
    def failures(self) -> list[tuple[int, MinSolution]]: ...
    def extrema(self) -> list[float]: ...
    def extremal_values(self) -> list[float]: ...

class MinBatchFailure:
    total: int
    failure_count: int
    first_index: int
    first_status: MinStatus
    first_iterations: int
    def __init__(self, total: int, failure_count: int, first_index: int, first_status: MinStatus, first_iterations: int) -> None: ...

class MinProblem:
    lo: float
    hi: float
    def __init__(self, lo: float, hi: float) -> None: ...
    def width(self) -> float: ...

class MinSettings:
    x_tol_abs: float
    x_tol_rel: float
    max_iterations: int
    def bracket_tolerance(self, x: float) -> float: ...
    def __init__(self, x_tol_abs: float, x_tol_rel: float, max_iterations: int) -> None: ...
    @staticmethod
    def default() -> MinSettings: ...

class MinSolution:
    def extremum(self) -> float | None: ...
    def extremal_value(self) -> float | None: ...
    def last_iterate(self) -> float: ...
    def last_value(self) -> float: ...
    def bracket_width(self) -> float: ...
    def iterations(self) -> int: ...
    def status(self) -> MinStatus: ...
    def converged(self) -> bool: ...

class MinStatus:
    def is_converged(self) -> bool: ...
    def label(self) -> str: ...
    @staticmethod
    def Converged() -> MinStatus: ...
    @staticmethod
    def MaxIterations() -> MinStatus: ...
    @staticmethod
    def InvalidBracket() -> MinStatus: ...
    @staticmethod
    def NotFinite() -> MinStatus: ...
    def variant(self) -> str: ...

class RootBatch:
    def solutions(self) -> list[RootSolution]: ...
    def into_solutions(self) -> list[RootSolution]: ...
    def len(self) -> int: ...
    def is_empty(self) -> bool: ...
    def get(self, i: int) -> RootSolution | None: ...
    def all_converged(self) -> bool: ...
    def failure_count(self) -> int: ...
    def first_failure(self) -> tuple[int, RootSolution] | None: ...
    def failures(self) -> list[tuple[int, RootSolution]]: ...
    def roots(self) -> list[float]: ...

class RootBatchFailure:
    total: int
    failure_count: int
    first_index: int
    first_status: RootStatus
    first_iterations: int
    def __init__(self, total: int, failure_count: int, first_index: int, first_status: RootStatus, first_iterations: int) -> None: ...

class RootMethod:
    @staticmethod
    def Bisection() -> RootMethod: ...
    @staticmethod
    def Brent() -> RootMethod: ...
    def variant(self) -> str: ...
    @staticmethod
    def default() -> RootMethod: ...

class RootProblem:
    lo: float
    hi: float
    guess: float
    def __init__(self, lo: float, hi: float) -> None: ...
    @staticmethod
    def with_guess(lo: float, hi: float, guess: float) -> RootProblem: ...

class RootSettings:
    x_tol_abs: float
    x_tol_rel: float
    f_tol: float
    max_iterations: int
    def __init__(self, x_tol_abs: float, x_tol_rel: float, f_tol: float, max_iterations: int) -> None: ...
    @staticmethod
    def default() -> RootSettings: ...

class RootSolution:
    def root(self) -> float | None: ...
    def last_iterate(self) -> float: ...
    def residual(self) -> float: ...
    def bracket_width(self) -> float: ...
    def iterations(self) -> int: ...
    def status(self) -> RootStatus: ...
    def converged(self) -> bool: ...

class RootStatus:
    def is_converged(self) -> bool: ...
    def label(self) -> str: ...
    @staticmethod
    def Converged() -> RootStatus: ...
    @staticmethod
    def MaxIterations() -> RootStatus: ...
    @staticmethod
    def NotBracketed() -> RootStatus: ...
    @staticmethod
    def InvalidBracket() -> RootStatus: ...
    @staticmethod
    def NotFinite() -> RootStatus: ...
    def variant(self) -> str: ...

class Sense:
    def is_better(self, candidate: float, incumbent: float) -> bool: ...
    def label(self) -> str: ...
    @staticmethod
    def Minimise() -> Sense: ...
    @staticmethod
    def Maximise() -> Sense: ...
    def variant(self) -> str: ...
    @staticmethod
    def default() -> Sense: ...

class MatrixError:
    @staticmethod
    def Singular(col: int) -> MatrixError: ...
    def variant(self) -> str: ...

class SquareMatrix:
    def __init__(self, n: int) -> None: ...
    def n(self) -> int: ...
    def get(self, i: int, j: int) -> float: ...
    def set(self, i: int, j: int, v: float) -> None: ...
    def add(self, i: int, j: int, v: float) -> None: ...
    def fill_zero(self) -> None: ...
    def lu_decompose(self) -> list[int]: ...
    def solve(self, rhs: list[float]) -> list[float]: ...

class AmiCoupling:
    target_face: int
    target_cell: int
    target_patch: int
    source_patch: int
    local: int
    weights: list[AmiWeight]
    def weight_sum(self) -> float: ...
    def __init__(self, target_face: int, target_cell: int, target_patch: int, source_patch: int, local: int, weights: list[AmiWeight]) -> None: ...

class AmiOverlap:
    source: int
    overlap_area: float
    weight: float
    def __init__(self, source: int, overlap_area: float, weight: float) -> None: ...

class AmiWeight:
    source_face: int
    source_cell: int
    weight: float
    overlap_area: float
    def __init__(self, source_face: int, source_cell: int, weight: float, overlap_area: float) -> None: ...

class MeshError:
    @staticmethod
    def PatchStartMismatch(name: str, expected: int, got: int) -> MeshError: ...
    @staticmethod
    def PatchCoverageMismatch(covered: int, n_faces: int) -> MeshError: ...
    @staticmethod
    def NonPositiveCellCount(got: int) -> MeshError: ...
    def variant(self) -> str: ...

class RegionInterface:
    patch_a: int
    patch_b: int
    face_map: list[int]

class AdaptiveSettings:
    abs_tol: float
    rel_tol: float
    max_subdivisions: int
    def __init__(self, abs_tol: float, rel_tol: float, max_subdivisions: int) -> None: ...
    @staticmethod
    def default() -> AdaptiveSettings: ...

class DynSystemIntegrator:
    solver: OdeSolver

class Euler:
    config: OdeSolverConfig
    def __init__(self, n: int, abs_tol: float, rel_tol: float) -> None: ...

class GaussOrder:
    def points(self) -> int: ...
    def exact_degree(self) -> int: ...
    @staticmethod
    def G2() -> GaussOrder: ...
    @staticmethod
    def G3() -> GaussOrder: ...
    @staticmethod
    def G4() -> GaussOrder: ...
    @staticmethod
    def G5() -> GaussOrder: ...
    @staticmethod
    def G8() -> GaussOrder: ...
    def variant(self) -> str: ...
    @staticmethod
    def default() -> GaussOrder: ...

class NoTypedSystem:
    @staticmethod
    def default() -> NoTypedSystem: ...

class OdeEnsemble:
    def lanes(self) -> list[OdeLaneSolution]: ...
    def into_lanes(self) -> list[OdeLaneSolution]: ...
    def len(self) -> int: ...
    def is_empty(self) -> bool: ...
    def get(self, i: int) -> OdeLaneSolution | None: ...
    def all_completed(self) -> bool: ...
    def failure_count(self) -> int: ...
    def first_failure(self) -> tuple[int, OdeLaneSolution] | None: ...
    def failures(self) -> list[tuple[int, OdeLaneSolution]]: ...
    def total_steps(self) -> int: ...
    def max_steps_taken(self) -> int: ...
    def states(self) -> list[list[float]]: ...
    def into_states(self) -> list[list[float]]: ...

class OdeEnsembleFailure:
    total: int
    failure_count: int
    first_index: int
    first_status: OdeLaneStatus
    first_steps: int
    first_x_reached: float
    def __init__(self, total: int, failure_count: int, first_index: int, first_status: OdeLaneStatus, first_steps: int, first_x_reached: float) -> None: ...

class OdeError:
    @staticmethod
    def StepSizeUnderflow() -> OdeError: ...
    @staticmethod
    def MaxStepsExceeded(a0: int) -> OdeError: ...
    @staticmethod
    def NonFiniteState() -> OdeError: ...
    def variant(self) -> str: ...

class OdeLaneSolution:
    def state(self) -> list[float] | None: ...
    def last_state(self) -> list[float]: ...
    def x_reached(self) -> float: ...
    def dx_final(self) -> float: ...
    def steps(self) -> int: ...
    def status(self) -> OdeLaneStatus: ...
    def completed(self) -> bool: ...

class OdeLaneStatus:
    def is_completed(self) -> bool: ...
    def label(self) -> str: ...
    @staticmethod
    def Completed() -> OdeLaneStatus: ...
    @staticmethod
    def MaxStepsExceeded() -> OdeLaneStatus: ...
    @staticmethod
    def StepSizeUnderflow() -> OdeLaneStatus: ...
    @staticmethod
    def NotFinite() -> OdeLaneStatus: ...
    @staticmethod
    def InvalidLane() -> OdeLaneStatus: ...
    def variant(self) -> str: ...

class OdeSolver:
    @staticmethod
    def euler(n: int, abs_tol: float, rel_tol: float) -> OdeSolver: ...
    @staticmethod
    def rkf45(n: int, abs_tol: float, rel_tol: float) -> OdeSolver: ...
    @staticmethod
    def rosenbrock23(n: int, abs_tol: float, rel_tol: float) -> OdeSolver: ...
    def name(self) -> str: ...
    def requires_jacobian(self) -> bool: ...
    def config(self) -> OdeSolverConfig: ...
    @staticmethod
    def Euler(a0: Euler) -> OdeSolver: ...
    @staticmethod
    def Rkf45(a0: Rkf45) -> OdeSolver: ...
    @staticmethod
    def Rosenbrock23(a0: Rosenbrock23) -> OdeSolver: ...
    def variant(self) -> str: ...

class OdeSolverConfig:
    abs_tol: float
    rel_tol: float
    safe_scale: float
    alpha_inc: float
    alpha_dec: float
    min_scale: float
    max_scale: float
    max_steps: int
    def __init__(self, abs_tol: float, rel_tol: float, safe_scale: float, alpha_inc: float, alpha_dec: float, min_scale: float, max_scale: float, max_steps: int) -> None: ...
    @staticmethod
    def default() -> OdeSolverConfig: ...

class QuadratureBatch:
    def solutions(self) -> list[QuadratureSolution]: ...
    def into_solutions(self) -> list[QuadratureSolution]: ...
    def len(self) -> int: ...
    def is_empty(self) -> bool: ...
    def get(self, i: int) -> QuadratureSolution | None: ...
    def all_evaluated(self) -> bool: ...
    def failure_count(self) -> int: ...
    def first_failure(self) -> tuple[int, QuadratureSolution] | None: ...
    def failures(self) -> list[tuple[int, QuadratureSolution]]: ...
    def total_evaluations(self) -> int: ...
    def values(self) -> list[float]: ...

class QuadratureBatchFailure:
    total: int
    failure_count: int
    first_index: int
    first_status: QuadratureStatus
    first_evaluations: int
    def __init__(self, total: int, failure_count: int, first_index: int, first_status: QuadratureStatus, first_evaluations: int) -> None: ...

class QuadratureInterval:
    a: float
    b: float
    def __init__(self, a: float, b: float) -> None: ...

class QuadratureRule:
    def evaluations(self) -> int: ...
    def label(self) -> str: ...
    @staticmethod
    def Trapezoid(panels: int) -> QuadratureRule: ...
    @staticmethod
    def Simpson(panels: int) -> QuadratureRule: ...
    @staticmethod
    def GaussLegendre(order: GaussOrder, panels: int) -> QuadratureRule: ...
    def variant(self) -> str: ...

class QuadratureSolution:
    def value(self) -> float | None: ...
    def last_value(self) -> float: ...
    def error_estimate(self) -> float: ...
    def evaluations(self) -> int: ...
    def status(self) -> QuadratureStatus: ...
    def evaluated(self) -> bool: ...

class QuadratureStatus:
    def is_evaluated(self) -> bool: ...
    def label(self) -> str: ...
    @staticmethod
    def Evaluated() -> QuadratureStatus: ...
    @staticmethod
    def ToleranceNotMet() -> QuadratureStatus: ...
    @staticmethod
    def NotFinite() -> QuadratureStatus: ...
    @staticmethod
    def InvalidInterval() -> QuadratureStatus: ...
    def variant(self) -> str: ...

class Rkf45:
    config: OdeSolverConfig
    def __init__(self, n: int, abs_tol: float, rel_tol: float) -> None: ...

class Rosenbrock23:
    config: OdeSolverConfig
    def __init__(self, n: int, abs_tol: float, rel_tol: float) -> None: ...

class CubicEqn:
    a: float
    b: float
    c: float
    d: float
    def __init__(self, a: float, b: float, c: float, d: float) -> None: ...
    def value(self, x: float) -> float: ...
    def derivative(self, x: float) -> float: ...
    def error(self, x: float) -> float: ...

class LinearEqn:
    a: float
    b: float
    def __init__(self, a: float, b: float) -> None: ...
    def value(self, x: float) -> float: ...
    def derivative(self, _x: float) -> float: ...
    def error(self, x: float) -> float: ...

class QuadraticEqn:
    a: float
    b: float
    c: float
    def __init__(self, a: float, b: float, c: float) -> None: ...
    def value(self, x: float) -> float: ...
    def derivative(self, x: float) -> float: ...
    def error(self, x: float) -> float: ...

class RootType:
    @staticmethod
    def Real() -> RootType: ...
    @staticmethod
    def Complex() -> RootType: ...
    @staticmethod
    def PosInf() -> RootType: ...
    @staticmethod
    def NegInf() -> RootType: ...
    @staticmethod
    def Nan() -> RootType: ...
    def variant(self) -> str: ...

class BoundaryPatch:
    name: str
    start: int
    size: int
    kind: PatchKind
    cyclic_partner: int | None
    def end(self) -> int: ...
    def contains_face(self, f: int) -> bool: ...
    def __init__(self, name: str, start: int, size: int, kind: PatchKind, cyclic_partner: int | None) -> None: ...

class CyclicCoupling:
    owner: int
    neighbour: int
    face_a: int
    face_b: int
    patch_a: int
    patch_b: int
    local: int
    def __init__(self, owner: int, neighbour: int, face_a: int, face_b: int, patch_a: int, patch_b: int, local: int) -> None: ...

class FvMesh:
    n_cells: int
    n_internal_faces: int
    n_faces: int
    owner: list[int]
    neighbour: list[int]
    patches: list[BoundaryPatch]
    cyclic_couplings: list[CyclicCoupling]
    ami_couplings: list[AmiCoupling]
    cell_volumes: list[float]
    cell_centres: list[Vector3]
    face_area_vectors: list[Vector3]
    face_areas: list[float]
    face_centres: list[Vector3]
    def n_boundary_faces(self) -> int: ...
    def n_patches(self) -> int: ...
    def is_internal_face(self, f: int) -> bool: ...
    def patch_for_face(self, f: int) -> tuple[int, int] | None: ...
    def n_cyclic_couplings(self) -> int: ...
    def cyclic_coupling_face(self, i: int) -> int: ...
    def cyclic_partner_face(self, global_face: int) -> int | None: ...
    @staticmethod
    def periodic_1d(n: int, length: float, area: float) -> FvMesh: ...
    def ami_ldu_start(self) -> int: ...
    def n_ami_faces(self) -> int: ...
    @staticmethod
    def periodic_ring_ami(n_a: int, n_b: int, lx: float, ly: float, depth: float) -> FvMesh: ...
    def __init__(self, n_cells: int, n_internal_faces: int, n_faces: int, owner: list[int], neighbour: list[int], patches: list[BoundaryPatch], cyclic_couplings: list[CyclicCoupling], ami_couplings: list[AmiCoupling], cell_volumes: list[float], cell_centres: list[Vector3], face_area_vectors: list[Vector3], face_areas: list[float], face_centres: list[Vector3]) -> None: ...

class FvMeshBuilder:
    def __init__(self, ) -> None: ...
    @staticmethod
    def default() -> FvMeshBuilder: ...

class NonOrthoGeometry:
    delta_coeff: float
    corr_vec: Vector3
    angle_deg: float
    def __init__(self, delta_coeff: float, corr_vec: Vector3, angle_deg: float) -> None: ...

class NonOrthoScheme:
    def correction_fraction(self) -> float: ...
    @staticmethod
    def Orthogonal() -> NonOrthoScheme: ...
    @staticmethod
    def Corrected() -> NonOrthoScheme: ...
    @staticmethod
    def Limited(a0: float) -> NonOrthoScheme: ...
    def variant(self) -> str: ...
    @staticmethod
    def default() -> NonOrthoScheme: ...

class PatchKind:
    @staticmethod
    def Patch() -> PatchKind: ...
    @staticmethod
    def Wall() -> PatchKind: ...
    @staticmethod
    def Symmetry() -> PatchKind: ...
    @staticmethod
    def Empty() -> PatchKind: ...
    @staticmethod
    def Wedge() -> PatchKind: ...
    @staticmethod
    def Cyclic() -> PatchKind: ...
    @staticmethod
    def CyclicAmi() -> PatchKind: ...
    @staticmethod
    def Processor() -> PatchKind: ...
    def variant(self) -> str: ...

class SphericalTensor:
    ii: float
    def __init__(self, ii: float) -> None: ...
    def tr(self) -> float: ...
    def mag_sqr(self) -> float: ...
    def mag(self) -> float: ...
    def diag_sqr(self) -> float: ...
    def det(self) -> float: ...
    def inv(self) -> SphericalTensor: ...
    def double_inner(self, rhs: SphericalTensor) -> float: ...
    @staticmethod
    def lerp(a: SphericalTensor, b: SphericalTensor, t: float) -> SphericalTensor: ...
    @staticmethod
    def default() -> SphericalTensor: ...

class SymmTensor:
    xx: float
    xy: float
    xz: float
    yy: float
    yz: float
    zz: float
    def __init__(self, xx: float, xy: float, xz: float, yy: float, yz: float, zz: float) -> None: ...
    @staticmethod
    def from_diag(xx: float, yy: float, zz: float) -> SymmTensor: ...
    def row_x(self) -> Vector3: ...
    def row_y(self) -> Vector3: ...
    def row_z(self) -> Vector3: ...
    def diag(self) -> Vector3: ...
    def tr(self) -> float: ...
    def sph(self) -> SphericalTensor: ...
    def dev(self) -> SymmTensor: ...
    def dev2(self) -> SymmTensor: ...
    def det(self) -> float: ...
    def adjunct(self) -> SymmTensor: ...
    def inv(self) -> SymmTensor: ...
    def safe_inv(self) -> SymmTensor: ...
    def mag_sqr(self) -> float: ...
    def mag(self) -> float: ...
    def diag_sqr(self) -> float: ...
    def inner_sqr(self) -> SymmTensor: ...
    def double_inner(self, rhs: SymmTensor) -> float: ...
    def mat_vec(self, v: Vector3) -> Vector3: ...
    def hodge_dual(self) -> Vector3: ...
    @staticmethod
    def from_outer(v: Vector3) -> SymmTensor: ...
    def invariant_i(self) -> float: ...
    def invariant_ii(self) -> float: ...
    def invariant_iii(self) -> float: ...
    @staticmethod
    def lerp(a: SymmTensor, b: SymmTensor, t: float) -> SymmTensor: ...
    def is_identity(self, tol: float) -> bool: ...
    @staticmethod
    def default() -> SymmTensor: ...

class Tensor:
    xx: float
    xy: float
    xz: float
    yx: float
    yy: float
    yz: float
    zx: float
    zy: float
    zz: float
    def __init__(self, xx: float, xy: float, xz: float, yx: float, yy: float, yz: float, zx: float, zy: float, zz: float) -> None: ...
    @staticmethod
    def from_rows(x: Vector3, y: Vector3, z: Vector3) -> Tensor: ...
    @staticmethod
    def from_cols(x: Vector3, y: Vector3, z: Vector3) -> Tensor: ...
    def row_x(self) -> Vector3: ...
    def row_y(self) -> Vector3: ...
    def row_z(self) -> Vector3: ...
    def col_x(self) -> Vector3: ...
    def col_y(self) -> Vector3: ...
    def col_z(self) -> Vector3: ...
    def diag(self) -> Vector3: ...
    def tr(self) -> float: ...
    def diag_sqr(self) -> float: ...
    def transpose(self) -> Tensor: ...
    def det(self) -> float: ...
    def adjunct(self) -> Tensor: ...
    def cof(self) -> Tensor: ...
    def inv(self) -> Tensor: ...
    def safe_inv(self) -> Tensor: ...
    def mat_mul(self, t: Tensor) -> Tensor: ...
    def schur(self, t: Tensor) -> Tensor: ...
    def mat_vec(self, v: Vector3) -> Vector3: ...
    @staticmethod
    def vec_mat(v: Vector3, t: Tensor) -> Vector3: ...
    def double_inner(self, t: Tensor) -> float: ...
    def symm(self) -> SymmTensor: ...
    def two_symm(self) -> SymmTensor: ...
    def skew(self) -> Tensor: ...
    def dev(self) -> Tensor: ...
    def dev2(self) -> Tensor: ...
    def dev_symm(self) -> SymmTensor: ...
    def dev_two_symm(self) -> SymmTensor: ...
    def hodge_dual(self) -> Vector3: ...
    def invariant_i(self) -> float: ...
    def invariant_ii(self) -> float: ...
    def invariant_iii(self) -> float: ...
    def is_identity(self, tol: float) -> bool: ...
    @staticmethod
    def lerp(a: Tensor, b: Tensor, t: float) -> Tensor: ...
    @staticmethod
    def default() -> Tensor: ...

class ThermoError:
    @staticmethod
    def NonConvergent(max_iter: int, last_t: float) -> ThermoError: ...
    def variant(self) -> str: ...

class Vector3:
    x: float
    y: float
    z: float
    def __init__(self, x: float, y: float, z: float) -> None: ...
    def mag_sqr(self) -> float: ...
    def mag(self) -> float: ...
    def dist_sqr(self, other: Vector3) -> float: ...
    def dist(self, other: Vector3) -> float: ...
    def dot(self, other: Vector3) -> float: ...
    def cross(self, other: Vector3) -> Vector3: ...
    def normalise(self, tol: float) -> Vector3: ...
    def remove_collinear(self, unit_vec: Vector3) -> Vector3: ...
    @staticmethod
    def lerp(a: Vector3, b: Vector3, t: float) -> Vector3: ...
    @staticmethod
    def default() -> Vector3: ...

class PengRobinsonGas:
    def __init__(self, mol_weight: float, tc: float, pc: float, omega: float) -> None: ...

class PerfectGas:
    def __init__(self, mol_weight: float) -> None: ...

class RhoConst:
    def __init__(self, mol_weight: float, rho0: float) -> None: ...

def gpu_adapter_present() -> bool: ...
def select_backend(work_items: int) -> ComputeBackend: ...
def field_parallel_crossover() -> int: ...
def should_parallelise(backend: ComputeBackend, n: int) -> bool: ...
def derived_name(op: str, operand: str) -> str: ...
def derived_name2(op: str, first: str, second: str) -> str: ...
def is_derived(name: str) -> bool: ...
def create_one_d_mesh(l: float, xs_area: float, number_of_cells: int) -> FvMesh: ...
def interpolate_spline_xy(x: float, xs: list[float], ys: list[float]) -> float: ...
def interpolate_xy(x: float, xs: list[float], ys: list[float]) -> float: ...
def dot(a: list[float], b: list[float]) -> float: ...
def nrm2(x: list[float]) -> float: ...
def derivative_backend_for(requested: ComputeBackend, n: int) -> ComputeBackend: ...
def erf_inv(y: float) -> float: ...
def inc_gamma_p(a: float, x: float) -> float: ...
def inc_gamma_q(a: float, x: float) -> float: ...
def inc_gamma_ratio_p(a: float, x: float) -> float: ...
def inc_gamma_ratio_q(a: float, x: float) -> float: ...
def inv_inc_gamma(a: float, p: float) -> float: ...
def jacobian_batch_backend_for(requested: ComputeBackend, n: int) -> ComputeBackend: ...
def jacobian_column_backend_for(requested: ComputeBackend, dimension: int) -> ComputeBackend: ...
def minimise_backend_for(requested: ComputeBackend, n: int) -> ComputeBackend: ...
def poly_roots_backend_for(requested: ComputeBackend, n: int) -> ComputeBackend: ...
def root_batch_backend_for(requested: ComputeBackend, n: int) -> ComputeBackend: ...
def ensemble_backend_for(requested: ComputeBackend, n: int) -> ComputeBackend: ...
def quadrature_backend_for(requested: ComputeBackend, n: int) -> ComputeBackend: ...
def eigen_values(t: Tensor) -> Vector3: ...
def eigen_values_checked(t: Tensor) -> tuple[Vector3, bool]: ...
def eigen_values_symm(t: SymmTensor) -> Vector3: ...
def eigen_vectors(t: Tensor) -> Tensor: ...
def eigen_vectors_symm(t: SymmTensor) -> Tensor: ...
def eigen_vectors_symm_with(t: SymmTensor, lambdas: Vector3) -> Tensor: ...
def eigen_vectors_with(t: Tensor, lambdas: Vector3) -> Tensor: ...
def dot(a: list[float], b: list[float], backend: ComputeBackend) -> float: ...
def norm_l1(x: list[float], backend: ComputeBackend) -> float: ...
def norm_l2(x: list[float], backend: ComputeBackend) -> float: ...
def max_non_orthogonality_deg(mesh: FvMesh) -> float: ...
def non_ortho_geometry(sf: Vector3, d: Vector3) -> NonOrthoGeometry | None: ...
def overlap_weights_1d(target_spans: list[tuple[float, float]], source_spans: list[tuple[float, float]], depth: float) -> list[list[AmiOverlap]]: ...
def spmv_backend_for(requested: ComputeBackend, n_cells: int) -> ComputeBackend: ...
def vecop_backend_for(requested: ComputeBackend, n: int) -> ComputeBackend: ...
def det(st: SphericalTensor) -> float: ...
def inv(st: SphericalTensor) -> SphericalTensor: ...
def lerp(a: SphericalTensor, b: SphericalTensor, t: float) -> SphericalTensor: ...
def mag_sqr(st: SphericalTensor) -> float: ...
def tr(st: SphericalTensor) -> float: ...
def det(st: SymmTensor) -> float: ...
def dev(st: SymmTensor) -> SymmTensor: ...
def dev2(st: SymmTensor) -> SymmTensor: ...
def dev_symm(st: SymmTensor) -> SymmTensor: ...
def dev_two_symm(st: SymmTensor) -> SymmTensor: ...
def inv(st: SymmTensor) -> SymmTensor: ...
def lerp(a: SymmTensor, b: SymmTensor, t: float) -> SymmTensor: ...
def mag_sqr(st: SymmTensor) -> float: ...
def sqr(v: Vector3) -> SymmTensor: ...
def symm(st: SymmTensor) -> SymmTensor: ...
def tr(st: SymmTensor) -> float: ...
def two_symm(st: SymmTensor) -> SymmTensor: ...
def det(t: Tensor) -> float: ...
def dev(t: Tensor) -> Tensor: ...
def dev2(t: Tensor) -> Tensor: ...
def dev_symm(t: Tensor) -> SymmTensor: ...
def dev_two_symm(t: Tensor) -> SymmTensor: ...
def hodge_dual_of_vec(v: Vector3) -> Tensor: ...
def inv(t: Tensor) -> Tensor: ...
def lerp(a: Tensor, b: Tensor, t: float) -> Tensor: ...
def outer(v: Vector3, w: Vector3) -> Tensor: ...
def skew(t: Tensor) -> Tensor: ...
def symm(t: Tensor) -> SymmTensor: ...
def tr(t: Tensor) -> float: ...
def two_symm(t: Tensor) -> SymmTensor: ...
def cross(a: Vector3, b: Vector3) -> Vector3: ...
def dot(a: Vector3, b: Vector3) -> float: ...
def lerp(a: Vector3, b: Vector3, t: float) -> Vector3: ...
def mag(v: Vector3) -> float: ...
def mag_sqr(v: Vector3) -> float: ...
CPU_MULTI_MIN_WORK_ITEMS: int
GPU_MIN_WORK_ITEMS: int
ELIDED_OPERAND: str
CBRT_EPSILON: float
DERIVATIVE_BATCH_MIN_POINTS: int
FIFTH_ROOT_EPSILON: float
GOLDEN_RATIO: float
JACOBIAN_BATCH_MIN_PROBLEMS: int
JACOBIAN_COLUMN_MIN_DIMENSION: int
MINIMISE_BATCH_MIN_PROBLEMS: int
SQRT_EPSILON: float
POLY_BLOCK: int
POLY_ROOTS_MIN_EQUATIONS: int
ROOT_BATCH_MIN_PROBLEMS: int
MAX_ADAPTIVE_DEPTH: int
CELL_BLOCK: int
FIELD_PARALLEL_CROSSOVER: int
ODE_ENSEMBLE_MIN_LANES: int
QUADRATURE_MIN_INTERVALS: int
REDUCTION_BLOCK: int
REDUCTION_CHUNK: int
SPMV_MIN_CELLS: int
VECOP_MIN_ELEMENTS: int
P_REF: float
R_UNIVERSAL: float
T_MAX: float
T_MIN: float
T_STD: float
