"""Type stubs for `outram_park.outram_foam_appbuilder_lib`, generated from the Rust API.

Physical quantities cross this boundary as `float` in SI base units.
"""

class AppBuilderError:
    @staticmethod
    def Parse(file: str, line: int, msg: str) -> AppBuilderError: ...
    @staticmethod
    def Diverged(iter: int, residual: float) -> AppBuilderError: ...
    @staticmethod
    def TimeLimitReached(t: float) -> AppBuilderError: ...
    def variant(self) -> str: ...

class InterpolateTableError:
    @staticmethod
    def LengthMismatch(xs: int, ys: int) -> InterpolateTableError: ...
    @staticmethod
    def TooFewPoints(a0: int) -> InterpolateTableError: ...
    @staticmethod
    def NonAscendingAbscissae(index: int, prev: float, next: float) -> InterpolateTableError: ...
    @staticmethod
    def OutOfBounds(x: float, lo: float, hi: float) -> InterpolateTableError: ...
    def variant(self) -> str: ...

class InterpolationMethod:
    @staticmethod
    def Step() -> InterpolationMethod: ...
    @staticmethod
    def Linear() -> InterpolationMethod: ...
    def variant(self) -> str: ...

class OutOfBounds:
    @staticmethod
    def Error() -> OutOfBounds: ...
    @staticmethod
    def Extrapolation() -> OutOfBounds: ...
    @staticmethod
    def Fixed() -> OutOfBounds: ...
    def variant(self) -> str: ...

class ScalarInterpolateTable:
    def __init__(self, xs: list[float], ys: list[float], method: InterpolationMethod, out_of_bounds: OutOfBounds) -> None: ...
    def method(self) -> InterpolationMethod: ...
    def out_of_bounds(self) -> OutOfBounds: ...
    def interpolate(self, x: float) -> float: ...
    def integral(self, k: float) -> float: ...
    def next_point(self, x: float) -> float: ...
    def last_point(self) -> float: ...
    def first_point(self) -> float: ...

class TimeProfile:
    @staticmethod
    def constant(value: float) -> TimeProfile: ...
    @staticmethod
    def table(times: list[float], values: list[float]) -> TimeProfile: ...
    def with_start_time(self, start_time: float) -> TimeProfile: ...
    def start_time(self) -> float: ...
    def valid(self) -> bool: ...
    def value(self, t: float) -> float: ...

class TimeProfileError:
    @staticmethod
    def LengthMismatch(times: int, values: int) -> TimeProfileError: ...
    @staticmethod
    def TooFewPoints(a0: int) -> TimeProfileError: ...
    @staticmethod
    def NonAscendingTimes(index: int, prev: float, next: float) -> TimeProfileError: ...
    def variant(self) -> str: ...

class CouplingError:
    @staticmethod
    def UnknownRegion(a0: str) -> CouplingError: ...
    @staticmethod
    def DuplicateRegion(a0: str) -> CouplingError: ...
    @staticmethod
    def MissingField(region: str, field: str) -> CouplingError: ...
    def variant(self) -> str: ...

class CouplingField:
    source: str
    target: str
    kind: FieldKind
    combine: MapCombine
    @staticmethod
    def scalar(source: str, target: str) -> CouplingField: ...
    @staticmethod
    def vector(source: str, target: str) -> CouplingField: ...
    def accumulating(self) -> CouplingField: ...
    def __init__(self, source: str, target: str, kind: FieldKind, combine: MapCombine) -> None: ...

class CouplingLoopError:
    @staticmethod
    def MissingField(region: str, field: str) -> CouplingLoopError: ...
    @staticmethod
    def PointKinetics(a0: PointKineticsError) -> CouplingLoopError: ...
    @staticmethod
    def Neutronics(a0: str) -> CouplingLoopError: ...
    @staticmethod
    def NotConverged(residual: float, iterations: int) -> CouplingLoopError: ...
    def variant(self) -> str: ...

class CouplingRegion:
    def name(self) -> str: ...

class DopplerLaw:
    @staticmethod
    def Linear() -> DopplerLaw: ...
    @staticmethod
    def Logarithmic() -> DopplerLaw: ...
    def variant(self) -> str: ...

class FeedbackTerm:
    def field_name(self) -> str: ...
    @staticmethod
    def Density(field: str, coeff: float, rho_ref: float) -> FeedbackTerm: ...
    def variant(self) -> str: ...

class FieldKind:
    @staticmethod
    def Scalar() -> FieldKind: ...
    @staticmethod
    def Vector() -> FieldKind: ...
    def variant(self) -> str: ...

class ImportanceWeight:
    @staticmethod
    def Volume() -> ImportanceWeight: ...
    @staticmethod
    def Field(a0: str) -> ImportanceWeight: ...
    def variant(self) -> str: ...

class LumpedNeutronics:
    def fission_power(self) -> float: ...
    def begin_step(self) -> None: ...

class LumpedThermal:
    def __init__(self, region_name: str, heat_capacity: float, conductance: float, t_coolant: float, t_initial: float, volume: float) -> None: ...
    def fuel_temperature(self) -> float: ...
    def begin_step(self) -> None: ...

class MapCombine:
    @staticmethod
    def Replace() -> MapCombine: ...
    @staticmethod
    def Accumulate() -> MapCombine: ...
    def variant(self) -> str: ...

class MappingMethod:
    @staticmethod
    def NearestCell() -> MappingMethod: ...
    @staticmethod
    def InverseDistance(n_neighbours: int) -> MappingMethod: ...
    @staticmethod
    def CellVolumeWeight() -> MappingMethod: ...
    def variant(self) -> str: ...

class MeshNeutronics:
    def k_eff(self) -> float: ...
    def fission_power(self) -> float: ...
    def model(self) -> DiffusionNeutronics: ...
    def feedback_reactivity(self, region: CouplingRegion) -> float: ...

class MeshThermalHydraulics:
    def __init__(self, region_name: str, n_cells: int, rho_cp: float, tau: float, t_coolant: float, t_initial: float) -> None: ...
    def temperatures(self) -> list[float]: ...
    def mean_temperature(self) -> float: ...
    def begin_step(self) -> None: ...

class MeshToMesh:
    def method(self) -> MappingMethod: ...

class PolyharmonicMode:
    def as_mode(self) -> int: ...
    @staticmethod
    def Linear() -> PolyharmonicMode: ...
    @staticmethod
    def ThinPlate() -> PolyharmonicMode: ...
    @staticmethod
    def Cubic() -> PolyharmonicMode: ...
    @staticmethod
    def ThinPlate4() -> PolyharmonicMode: ...
    def variant(self) -> str: ...

class PrescribedRegion:
    def __init__(self, region_name: str) -> None: ...

class RbfMapError:
    @staticmethod
    def EmptyOrMismatched(n_points: int, n_values: int) -> RbfMapError: ...
    @staticmethod
    def Singular() -> RbfMapError: ...
    def variant(self) -> str: ...

class ReactivityFeedback:
    def __init__(self, ) -> None: ...
    def with_weight(self, weight: ImportanceWeight) -> ReactivityFeedback: ...
    def with_density(self, field: str, coeff: float, rho_ref: float) -> ReactivityFeedback: ...
    def terms(self) -> list[FeedbackTerm]: ...
    def weighted_mean(self, region: CouplingRegion, field: str) -> float: ...
    @staticmethod
    def default() -> ReactivityFeedback: ...

class RegionModel:
    def begin_step(self) -> None: ...
    def region_name(self) -> str: ...
    def correct_only_energy(self) -> bool: ...
    @staticmethod
    def Neutronics(a0: LumpedNeutronics) -> RegionModel: ...
    @staticmethod
    def ThermalHydraulics(a0: LumpedThermal) -> RegionModel: ...
    @staticmethod
    def Prescribed(a0: PrescribedRegion) -> RegionModel: ...
    @staticmethod
    def MeshNeutronics(a0: MeshNeutronics) -> RegionModel: ...
    @staticmethod
    def MeshThermalHydraulics(a0: MeshThermalHydraulics) -> RegionModel: ...
    def variant(self) -> str: ...

class DiffusionSettings:
    k_tolerance: float
    flux_tolerance: float
    max_outer_iterations: int
    @staticmethod
    def default() -> DiffusionSettings: ...

class EigenvalueReport:
    k_eff: float
    outer_iterations: int
    k_residual: float
    flux_residual: float
    converged: bool
    def __init__(self, k_eff: float, outer_iterations: int, k_residual: float, flux_residual: float, converged: bool) -> None: ...

class NeutronicsError:
    @staticmethod
    def PointKinetics(a0: PointKineticsError) -> NeutronicsError: ...
    @staticmethod
    def PatchCountMismatch(given: int, patches: int) -> NeutronicsError: ...
    @staticmethod
    def NoFissionSource() -> NeutronicsError: ...
    @staticmethod
    def NotConverged(outer_iterations: int, k_residual: float, flux_residual: float) -> NeutronicsError: ...
    @staticmethod
    def NonPositiveTimeStep(a0: float) -> NeutronicsError: ...
    @staticmethod
    def ModelNotImplemented(a0: NeutronicsModelKind) -> NeutronicsError: ...
    def variant(self) -> str: ...

class NeutronicsModelKind:
    @staticmethod
    def PointKinetics() -> NeutronicsModelKind: ...
    @staticmethod
    def Diffusion() -> NeutronicsModelKind: ...
    @staticmethod
    def Sp3() -> NeutronicsModelKind: ...
    @staticmethod
    def Sn() -> NeutronicsModelKind: ...
    def variant(self) -> str: ...

class PointKineticsModel:
    def __init__(self, params: PointKineticsParameters, state: PointKineticsState) -> None: ...
    def params(self) -> PointKineticsParameters: ...
    def state(self) -> PointKineticsState: ...

class SnNeutronics:
    def state(self) -> NeutronicsState: ...
    def settings(self) -> SnSettings: ...
    def quadrature(self) -> AngularQuadrature | None: ...
    def energy_groups(self) -> int: ...
    def solve_eigenvalue(self) -> EigenvalueReport: ...

class Sp3Neutronics:
    def solve_eigenvalue(self) -> EigenvalueReport: ...
    def state(self) -> NeutronicsState: ...
    def xs_fields(self) -> Sp3XsFields | None: ...
    def settings(self) -> Sp3Settings: ...
    def energy_groups(self) -> int: ...
    def prec_groups(self) -> int: ...

class DiffusionXsFields:
    energy_groups: int
    prec_groups: int

class AngularQuadrature:
    @staticmethod
    def level_symmetric(order: QuadratureOrder) -> AngularQuadrature: ...
    def order(self) -> QuadratureOrder: ...
    def direction_count(self) -> int: ...
    def weights(self) -> list[float]: ...
    def weight_sum(self) -> float: ...

class QuadratureOrder:
    def n(self) -> int: ...
    def direction_count(self) -> int: ...
    @staticmethod
    def S2() -> QuadratureOrder: ...
    @staticmethod
    def S4() -> QuadratureOrder: ...
    @staticmethod
    def S6() -> QuadratureOrder: ...
    def variant(self) -> str: ...

class SnSettings:
    k_tolerance: float
    flux_tolerance: float
    max_outer_iterations: int
    max_inner_iterations: int
    inner_tolerance: float
    @staticmethod
    def default() -> SnSettings: ...

class Sp3Settings:
    k_tolerance: float
    flux_tolerance: float
    max_outer_iterations: int
    @staticmethod
    def default() -> Sp3Settings: ...

class Sp3XsFields:
    base: DiffusionXsFields
    def energy_groups(self) -> int: ...
    def prec_groups(self) -> int: ...

class NuclearDataInput:
    energy_groups: int
    prec_groups: int
    legendre_moments: int
    poly_spline_mode: int
    fast_neutrons: bool
    xs_variables: list[XsVariable]
    do_not_parametrize: list[int]
    states: list[StateInput]
    def __init__(self, energy_groups: int, prec_groups: int, legendre_moments: int, poly_spline_mode: int, fast_neutrons: bool, xs_variables: list[XsVariable], do_not_parametrize: list[int], states: list[StateInput]) -> None: ...

class NuclearDataOneEnergy:
    def __init__(self, poly_spline_mode: int, n_parameters: int) -> None: ...
    def add_data(self, value: float, parameters: list[float]) -> None: ...
    def get_ref(self) -> float: ...
    def get(self, parameters: list[float], is_parametrize: bool) -> float: ...
    def data_len(self) -> int: ...

class StateInput:
    name: str
    zones: list[ZoneStateInput]

class VariableLaw:
    @staticmethod
    def from_keyword(keyword: str) -> VariableLaw | None: ...
    def keyword(self) -> str: ...
    def transform(self, value: float) -> float: ...
    @staticmethod
    def Linear() -> VariableLaw: ...
    @staticmethod
    def Log() -> VariableLaw: ...
    @staticmethod
    def Sqrt() -> VariableLaw: ...
    def variant(self) -> str: ...

class XsError:
    @staticmethod
    def NoStates() -> XsError: ...
    @staticmethod
    def ReferenceStateNotFirst(found: str) -> XsError: ...
    @staticmethod
    def MissingReferenceVariable(name: str) -> XsError: ...
    @staticmethod
    def UnknownVariableLaw(name: str, law: str) -> XsError: ...
    @staticmethod
    def MissingZoneConstants(zone: str) -> XsError: ...
    @staticmethod
    def SingularRbfMatrix(detail: str) -> XsError: ...
    def variant(self) -> str: ...

class XsVariable:
    name: str
    law: VariableLaw
    def __init__(self, name: str, law: VariableLaw) -> None: ...

class ZoneConstantsInput:
    fuel_fraction: float
    secondary_power_volume_fraction: float
    fraction_to_secondary_power: float
    df_adjust: bool
    iv: list[float]
    disc_factor: list[float]
    integral_flux: list[float]
    beta: list[float]
    @staticmethod
    def default() -> ZoneConstantsInput: ...

class ZoneNuclearData:
    @staticmethod
    def new_reference(zone: ZoneStateInput, energy_groups: int, prec_groups: int, legendre_moments: int, poly_spline_mode: int, n_parameters: int) -> ZoneNuclearData: ...
    def name(self) -> str: ...
    def energy_groups(self) -> int: ...
    def prec_groups(self) -> int: ...
    def legendre_moments(self) -> int: ...
    def fuel_fraction(self) -> float: ...
    def secondary_power_volume_fraction(self) -> float: ...
    def fraction_to_secondary_power(self) -> float: ...
    def df_adjust(self) -> bool: ...
    def diffusion_coefficient(self, group: int, parameters: list[float], parametrize: bool) -> float: ...
    def nu_sigma_f(self, group: int, parameters: list[float], parametrize: bool) -> float: ...
    def sigma_pow(self, group: int, parameters: list[float], parametrize: bool) -> float: ...
    def sigma_removal(self, group: int, parameters: list[float], parametrize: bool) -> float: ...
    def chi_prompt(self, group: int, parameters: list[float], parametrize: bool) -> float: ...
    def chi_delayed(self, group: int, parameters: list[float], parametrize: bool) -> float: ...
    def scattering(self, moment: int, energy_j: int, energy_i: int, parameters: list[float], parametrize: bool) -> float: ...
    def diffusion_coefficient_ref(self, group: int) -> float: ...
    def inverse_velocity(self, group: int) -> float: ...
    def disc_factor(self, group: int) -> float: ...
    def integral_flux(self, group: int) -> float: ...
    def beta(self, prec: int) -> float: ...
    def beta_tot(self) -> float: ...

class ZoneStateInput:
    name: str
    d: list[float]
    nu_sigma_eff: list[float]
    sigma_pow: list[float]
    sigma_removal: list[float]
    chi_prompt: list[float]
    chi_delayed: list[float]
    scattering: list[list[list[float]]]
    constants: ZoneConstantsInput | None
    def __init__(self, name: str, d: list[float], nu_sigma_eff: list[float], sigma_pow: list[float], sigma_removal: list[float], chi_prompt: list[float], chi_delayed: list[float], scattering: list[list[list[float]]], constants: ZoneConstantsInput | None) -> None: ...

class BaffleSide:
    @staticmethod
    def Master() -> BaffleSide: ...
    @staticmethod
    def Slave() -> BaffleSide: ...
    def variant(self) -> str: ...

class BlackBodyRadiationBc:
    emissivity: float
    kappa: float
    ambient_temperature: float
    def __init__(self, emissivity: float, kappa: float, ambient_temperature: float) -> None: ...
    def update_face_temperature(self, current_face_temperature: float, cell_temperature: float, cell_to_face_distance: float) -> float: ...

class NusseltCorrelationCoefficients:
    const_term: float
    coeff: float
    exp_reynolds: float
    exp_prandtl: float
    def __init__(self, const_term: float, coeff: float, exp_reynolds: float, exp_prandtl: float) -> None: ...

class NusseltThermalBaffle1DBc:
    thickness: float
    wall_conductivity: float
    master_correlation: NusseltCorrelationCoefficients
    slave_correlation: NusseltCorrelationCoefficients
    def __init__(self, thickness: float, wall_conductivity: float, master_correlation: NusseltCorrelationCoefficients, slave_correlation: NusseltCorrelationCoefficients) -> None: ...

class TimeFieldTable:
    def __init__(self, times: list[float], values: list[list[float]]) -> None: ...
    def n_faces(self) -> int: ...
    def value(self, t: float) -> list[float]: ...

class TimeFieldTableError:
    @staticmethod
    def LengthMismatch(times: int, rows: int) -> TimeFieldTableError: ...
    @staticmethod
    def InconsistentRowLength(index: int, expected: int, got: int) -> TimeFieldTableError: ...
    @staticmethod
    def Table(a0: InterpolateTableError) -> TimeFieldTableError: ...
    def variant(self) -> str: ...

class VelocityRundownBc:
    const_a: float
    coeff_b: float
    exp_c: float
    start_time: float
    def __init__(self, const_a: float, coeff_b: float, exp_c: float, start_time: float) -> None: ...
    def rundown_factor(self, t: float) -> float: ...

class FfDragCoefficient:
    def drag_coefficient(self, state: FfInterfacialState) -> float: ...
    @staticmethod
    def no_kazimi_from_geometry(pin_pitch: float, pin_diameter: float) -> FfDragCoefficient: ...
    @staticmethod
    def Wallis() -> FfDragCoefficient: ...
    @staticmethod
    def SchillerNaumann() -> FfDragCoefficient: ...
    @staticmethod
    def Bestion() -> FfDragCoefficient: ...
    @staticmethod
    def BestionTrace() -> FfDragCoefficient: ...
    @staticmethod
    def Autruffe() -> FfDragCoefficient: ...
    @staticmethod
    def NoKazimi(a: float) -> FfDragCoefficient: ...
    def variant(self) -> str: ...

class FfInterfacialState:
    vapour_fraction: float
    rho_vapour: float
    rho_liquid: float
    rho_continuous: float
    dh_dispersed: float
    dh_continuous: float
    u_vapour: float
    u_liquid: float
    u_relative: float

class TwoPhaseDragMultiplier:
    def multiplier(self, phase_fraction: float, x_lm: float) -> float: ...
    @staticmethod
    def ChenKalish() -> TwoPhaseDragMultiplier: ...
    @staticmethod
    def Constant(phi2: float) -> TwoPhaseDragMultiplier: ...
    @staticmethod
    def Kaiser74() -> TwoPhaseDragMultiplier: ...
    @staticmethod
    def Kaiser88() -> TwoPhaseDragMultiplier: ...
    @staticmethod
    def KottowskiSavatteri() -> TwoPhaseDragMultiplier: ...
    @staticmethod
    def LockhartMartinelli(c: float, max_phi2: float) -> TwoPhaseDragMultiplier: ...
    @staticmethod
    def LottesFlinn(exp: float) -> TwoPhaseDragMultiplier: ...
    @staticmethod
    def LottesFlinnNguyen(exp: float) -> TwoPhaseDragMultiplier: ...
    def variant(self) -> str: ...

class FsWallFriction:
    @staticmethod
    def rehme_from_geometry(number_of_pins: float, pin_diameter: float, wire_diameter: float, wire_lead_length: float, wetted_wrap_perimeter: float) -> FsWallFriction: ...
    @staticmethod
    def baxi_dalle_donne_from_geometry(pin_diameter: float, wire_diameter: float, wire_lead_length: float) -> FsWallFriction: ...
    @staticmethod
    def no_kazimi_from_geometry(pin_diameter: float, wire_diameter: float, wire_lead_length: float) -> FsWallFriction: ...
    @staticmethod
    def Churchill(surface_roughness: float) -> FsWallFriction: ...
    @staticmethod
    def Colebrook(coeff: float, constant: float, exp: float) -> FsWallFriction: ...
    @staticmethod
    def ReynoldsPower(coeff: float, exp: float, constant: float) -> FsWallFriction: ...
    @staticmethod
    def Rehme(a: float, b1: float, b2: float) -> FsWallFriction: ...
    @staticmethod
    def Engel() -> FsWallFriction: ...
    @staticmethod
    def ModifiedEngel() -> FsWallFriction: ...
    @staticmethod
    def BaxiDalleDonne(a: float, b: float, c: float) -> FsWallFriction: ...
    @staticmethod
    def NoKazimi(a: float, b: float, c: float) -> FsWallFriction: ...
    def variant(self) -> str: ...

class MultiRegimeBoilingInputs:
    t_wall: float
    t_fluid: float
    t_sat: float
    vapour_void_fraction: float
    suppression_factor: float | None
    t_onset_nucleate_boiling: float | None
    superposition_exponent: float
    heat_flux_superposition: bool

class CriticalHeatFlux:
    def variant(self) -> str: ...

class FlowEnhancementFactor:
    def value(self, inputs: FlowEnhancementInputs) -> float: ...
    @staticmethod
    def Chen(max_value: float) -> FlowEnhancementFactor: ...
    @staticmethod
    def RezkallahSims(exponent: float, max_value: float) -> FlowEnhancementFactor: ...
    @staticmethod
    def CobraTf(max_value: float) -> FlowEnhancementFactor: ...
    def variant(self) -> str: ...

class FlowEnhancementInputs:
    inverse_lockhart_martinelli: float
    liquid_void_fraction: float

class LeidenfrostTemperature:
    def temperature(self, pressure: float, t_sat: float) -> float: ...
    @staticmethod
    def GroeneveldStewart(critical_pressure: float) -> LeidenfrostTemperature: ...
    def variant(self) -> str: ...

class OnsetOfNucleateBoilingTemperature:
    @staticmethod
    def Basu(surface_tension: float, contact_angle: float) -> OnsetOfNucleateBoilingTemperature: ...
    def variant(self) -> str: ...

class SubcooledBoilingFraction:
    @staticmethod
    def Constant(value: float) -> SubcooledBoilingFraction: ...
    @staticmethod
    def SahaZuber() -> SubcooledBoilingFraction: ...
    def variant(self) -> str: ...

class SuppressionFactor:
    def value(self, inputs: SuppressionInputs) -> float: ...
    @staticmethod
    def Chen() -> SuppressionFactor: ...
    @staticmethod
    def CobraTf() -> SuppressionFactor: ...
    def variant(self) -> str: ...

class SuppressionInputs:
    t_fluid: float
    t_wall: float
    t_sat: float

class FfForcedConvectionHtc:
    @staticmethod
    def Nusselt(a: float, b: float, c: float, d: float) -> FfForcedConvectionHtc: ...
    def variant(self) -> str: ...

class FsForcedConvectionHtc:
    @staticmethod
    def Nusselt(a: float, b: float, c: float, d: float, e: float) -> FsForcedConvectionHtc: ...
    def variant(self) -> str: ...

class PoolBoilingHtc:
    @staticmethod
    def Shah() -> PoolBoilingHtc: ...
    @staticmethod
    def Gorenflo(surface_roughness: float) -> PoolBoilingHtc: ...
    def variant(self) -> str: ...

class InterfacialArea:
    @staticmethod
    def no_kazimi_from_geometry(pin_diameter_m: float, pin_pitch_m: float) -> InterfacialArea: ...
    @staticmethod
    def schor_from_geometry(pin_diameter_m: float, pin_pitch_m: float, cutoff_alpha: float, min_area_at_large_alpha: float) -> InterfacialArea: ...
    @staticmethod
    def Spherical(cutoff_alpha: float) -> InterfacialArea: ...
    @staticmethod
    def Annular(cutoff_alpha: float) -> InterfacialArea: ...
    @staticmethod
    def NoKazimi(a_const: float, pin_diameter_m: float) -> InterfacialArea: ...
    @staticmethod
    def Schor(pin_diameter_m: float, a_const: float, cutoff_alpha: float, min_area_at_large_alpha: float, ia1: float, ia2: float) -> InterfacialArea: ...
    def variant(self) -> str: ...

class ContactPartition:
    def value(self, input: float) -> float: ...
    @staticmethod
    def Linear() -> ContactPartition: ...
    @staticmethod
    def Complementary() -> ContactPartition: ...
    def variant(self) -> str: ...

class BubbleDiameter:
    @staticmethod
    def IsomolarBubble(d0_m: float, p0_pa: float, t0_k: float) -> BubbleDiameter: ...
    @staticmethod
    def IsothermalBubble(d0_m: float, p0_pa: float) -> BubbleDiameter: ...
    def variant(self) -> str: ...

class FilmDiameter:
    @staticmethod
    def PipeFilm(residual_alpha: float) -> FilmDiameter: ...
    @staticmethod
    def WallisFilm(residual_alpha: float) -> FilmDiameter: ...
    def variant(self) -> str: ...

class TurbulentDispersion:
    @staticmethod
    def constant_for_fluid1(dict_value: float, dispersed_phase_is_fluid1: bool) -> TurbulentDispersion: ...
    def value_for_fluid1(self) -> float: ...
    def value_for_fluid2(self) -> float: ...
    @staticmethod
    def Constant(value_for_fluid1: float) -> TurbulentDispersion: ...
    def variant(self) -> str: ...

class RegimeBound:
    name: str
    lower: float
    upper: float
    def __init__(self, name: str, lower: float, upper: float) -> None: ...

class RegimeInterpolationMode:
    @staticmethod
    def Linear() -> RegimeInterpolationMode: ...
    @staticmethod
    def Quadratic() -> RegimeInterpolationMode: ...
    def variant(self) -> str: ...

class RegimeMap1D:
    def __init__(self, regimes: list[RegimeBound], interpolation_mode: RegimeInterpolationMode) -> None: ...
    def regime_weights(self, parameter: float) -> list[tuple[str, float]]: ...

class VirtualMassCoefficient:
    @staticmethod
    def constant(cvm: float) -> VirtualMassCoefficient: ...
    def coefficient(self) -> float: ...
    @staticmethod
    def Constant(cvm: float) -> VirtualMassCoefficient: ...
    def variant(self) -> str: ...

class LatentHeatModel:
    @staticmethod
    def FinkLeibowitz() -> LatentHeatModel: ...
    @staticmethod
    def Water() -> LatentHeatModel: ...
    @staticmethod
    def FromThermophysicalProperties() -> LatentHeatModel: ...
    def variant(self) -> str: ...

class PhaseChangeRateModel:
    @staticmethod
    def HeatDrivenConductionLimited() -> PhaseChangeRateModel: ...
    @staticmethod
    def HeatDrivenTwoPhaseDriven() -> PhaseChangeRateModel: ...
    @staticmethod
    def HeatDrivenOnePhaseDriven(driving_is_phase1: bool) -> PhaseChangeRateModel: ...
    @staticmethod
    def HeatDrivenMixedDriven(driving_is_phase1: bool) -> PhaseChangeRateModel: ...
    def variant(self) -> str: ...

class SaturationModel:
    def t_sat(self, p: float) -> float: ...
    def p_sat(self, t: float, p: float) -> float: ...
    def ln_p_sat(self, t: float, p: float) -> float: ...
    @staticmethod
    def ConstantTemperature(t_sat: float) -> SaturationModel: ...
    @staticmethod
    def Water() -> SaturationModel: ...
    @staticmethod
    def WaterTrace() -> SaturationModel: ...
    @staticmethod
    def BrowningPotter() -> SaturationModel: ...
    def variant(self) -> str: ...

class LaheyBubbleClosure:
    cp: float
    cmub: float
    c3: float
    alpha_inversion: float
    @staticmethod
    def new_default() -> LaheyBubbleClosure: ...
    def __init__(self, cp: float, cmub: float, c3: float, alpha_inversion: float) -> None: ...

class MixtureKEpsilonClosure:
    cmu: float
    cp: float
    c3: float
    @staticmethod
    def new_default() -> MixtureKEpsilonClosure: ...
    @staticmethod
    def effective_gas_density(rho_gas: float, virtual_mass_coefficient: float, rho_liquid: float) -> float: ...
    def __init__(self, cmu: float, cp: float, c3: float) -> None: ...

class PorousKEpsilon2PhaseClosure:
    base: PorousKEpsilonClosure
    turbulence_intensity_alpha_coeff: float
    def __init__(self, base: PorousKEpsilonClosure, turbulence_intensity_alpha_coeff: float) -> None: ...

class PorousKEpsilonClosure:
    cmu: float
    turbulence_intensity_coeff: float
    turbulence_intensity_exp: float
    turbulence_length_scale_coeff: float
    def __init__(self, cmu: float, turbulence_intensity_coeff: float, turbulence_intensity_exp: float, turbulence_length_scale_coeff: float) -> None: ...

class MassFlowRegion:
    @staticmethod
    def Patch(a0: int) -> MassFlowRegion: ...
    @staticmethod
    def Faces(a0: list[int]) -> MassFlowRegion: ...
    def variant(self) -> str: ...

class PatchReduceOp:
    @staticmethod
    def Sum() -> PatchReduceOp: ...
    @staticmethod
    def Average() -> PatchReduceOp: ...
    @staticmethod
    def Min() -> PatchReduceOp: ...
    @staticmethod
    def Max() -> PatchReduceOp: ...
    @staticmethod
    def Integral() -> PatchReduceOp: ...
    def variant(self) -> str: ...

class StopDecision:
    stop: bool
    max_diff: float
    def __init__(self, stop: bool, max_diff: float) -> None: ...

class PhaseBase:
    def name(self) -> str: ...

class OnePhaseSolver:
    fluid: Fluid
    drag: PorousDrag
    solve_pressure: bool
    p_ref_cell: int
    p_ref_value: float
    n_outer: int
    n_inner: int

class PorousDrag:
    friction: FsWallFriction
    min_mag_u: float
    def __init__(self, friction: FsWallFriction) -> None: ...
    def with_min_mag_u(self, min_mag_u: float) -> PorousDrag: ...

class ThermalHydraulicsSolver:
    def variant(self) -> str: ...

class FieldReduction:
    @staticmethod
    def Max() -> FieldReduction: ...
    @staticmethod
    def Min() -> FieldReduction: ...
    def variant(self) -> str: ...

class FixedPower:
    def with_power_profile(self, profile: TimeProfile) -> FixedPower: ...
    def surface_temperature(self) -> float: ...
    def power_off(self) -> None: ...

class FixedTemperature:
    def with_temperature_profile(self, profile: TimeProfile) -> FixedTemperature: ...
    def surface_temperature_at(self, t: float) -> float: ...

class PassiveStructure:
    def surface_temperature(self) -> float: ...

class PowerOffCriterion:
    @staticmethod
    def timer(trigger_time: float) -> PowerOffCriterion: ...
    @staticmethod
    def field_value(reduction: FieldReduction, direction: ThresholdDirection, threshold: float) -> PowerOffCriterion: ...
    def with_time_delay(self, delay: float) -> PowerOffCriterion: ...
    def check(self, t: float, field_extremum: float) -> bool: ...
    @staticmethod
    def Timer(trigger_time: float) -> PowerOffCriterion: ...
    @staticmethod
    def FieldValue(reduction: FieldReduction, direction: ThresholdDirection, threshold: float, time_delay: float, first_crossing: float | None) -> PowerOffCriterion: ...
    def variant(self) -> str: ...

class Pump:
    def with_time_profile(self, profile: TimeProfile) -> Pump: ...
    def time_dependent(self) -> bool: ...

class StructureCell:
    power_model: PowerModel
    passive: PassiveStructure | None
    pump: Pump | None
    power_off: PowerOffCriterion | None
    def __init__(self, power_model: PowerModel) -> None: ...
    def with_passive(self, passive: PassiveStructure) -> StructureCell: ...
    def with_pump(self, pump: Pump) -> StructureCell: ...
    def with_power_off(self, criterion: PowerOffCriterion) -> StructureCell: ...

class StructureThermalState:
    active_surface_temperature: float
    passive_surface_temperature: float | None
    wall_temperature: float
    powered_off: bool

class ThresholdDirection:
    @staticmethod
    def Above() -> ThresholdDirection: ...
    @staticmethod
    def Below() -> ThresholdDirection: ...
    def variant(self) -> str: ...

class BespokeFluidPropertyModel:
    @staticmethod
    def Hydrogen() -> BespokeFluidPropertyModel: ...
    def variant(self) -> str: ...
    @staticmethod
    def default() -> BespokeFluidPropertyModel: ...

class DisplacementReport:
    n_correctors: int
    final_change: float
    converged: bool
    max_displacement: float
    def __init__(self, n_correctors: int, final_change: float, converged: bool, max_displacement: float) -> None: ...

class ElasticMaterial:
    def poisson_ratio(self) -> float: ...
    def density(self) -> float: ...
    def specific_heat(self) -> float: ...
    def conductivity(self) -> float: ...

class MaterialError:
    @staticmethod
    def NonPositiveYoungsModulus(a0: float) -> MaterialError: ...
    @staticmethod
    def NonPositiveDensity(a0: float) -> MaterialError: ...
    @staticmethod
    def NonPositiveSpecificHeat(a0: float) -> MaterialError: ...
    @staticmethod
    def PoissonRatioOutOfRange(a0: float) -> MaterialError: ...
    def variant(self) -> str: ...

class RheologyOption:
    @staticmethod
    def PlaneStrain() -> RheologyOption: ...
    @staticmethod
    def PlaneStress() -> RheologyOption: ...
    def variant(self) -> str: ...
    @staticmethod
    def default() -> RheologyOption: ...

class ThermoMechanicsModel:
    @staticmethod
    def Legacy(a0: LegacyThermoMechanics) -> ThermoMechanicsModel: ...
    def variant(self) -> str: ...

class InterpolationScheme:
    @staticmethod
    def Linear() -> InterpolationScheme: ...
    @staticmethod
    def Upwind(a0: str) -> InterpolationScheme: ...
    @staticmethod
    def Harmonic() -> InterpolationScheme: ...
    def variant(self) -> str: ...

class ControlDict:
    application: str
    start: StartControl
    stop: StopControl
    delta_t: float
    write_control: WriteControl
    write_interval: float
    purge_write: int
    write_format: WriteFormat
    write_precision: int
    run_time_modifiable: bool
    adjust_time_step: bool
    max_co: float
    max_delta_t: float
    @staticmethod
    def read(path: str) -> ControlDict: ...
    def __init__(self, application: str, start: StartControl, stop: StopControl, delta_t: float, write_control: WriteControl, write_interval: float, purge_write: int, write_format: WriteFormat, write_precision: int, run_time_modifiable: bool, adjust_time_step: bool, max_co: float, max_delta_t: float) -> None: ...
    @staticmethod
    def default() -> ControlDict: ...

class CrossSectionData:
    @staticmethod
    def from_input(input: NuclearDataInput) -> CrossSectionData: ...
    def transform_parameters(self, raw_parameters: list[float]) -> list[float]: ...
    def energy_groups(self) -> int: ...
    def prec_groups(self) -> int: ...
    def legendre_moments(self) -> int: ...
    def fast_neutrons(self) -> bool: ...
    def variable_names(self) -> list[str]: ...
    def variables(self) -> list[XsVariable]: ...
    def zone_count(self) -> int: ...
    def zone_index(self, name: str) -> int | None: ...
    def zone(self, index: int) -> ZoneNuclearData | None: ...
    def evaluate_group_constants(self, zone: int, group: int, raw_parameters: list[float]) -> GroupConstants: ...
    def reference_group_constants(self, zone: int, group: int) -> GroupConstants: ...
    def precursor_constants(self, zone: int) -> PrecursorConstants: ...

class DdtScheme:
    @staticmethod
    def Euler() -> DdtScheme: ...
    @staticmethod
    def Backward() -> DdtScheme: ...
    @staticmethod
    def CrankNicolson(a0: float) -> DdtScheme: ...
    @staticmethod
    def LocalEuler() -> DdtScheme: ...
    @staticmethod
    def SteadyState() -> DdtScheme: ...
    def variant(self) -> str: ...

class DiffusionNeutronics:
    def state(self) -> NeutronicsState: ...
    def xs_fields(self) -> DiffusionXsFields: ...
    def settings(self) -> DiffusionSettings: ...
    def energy_groups(self) -> int: ...
    def prec_groups(self) -> int: ...
    def solve_eigenvalue(self) -> EigenvalueReport: ...

class DivScheme:
    @staticmethod
    def GaussLinear() -> DivScheme: ...
    @staticmethod
    def GaussUpwind() -> DivScheme: ...
    @staticmethod
    def GaussLinearUpwind(a0: str) -> DivScheme: ...
    @staticmethod
    def GaussVanLeer() -> DivScheme: ...
    @staticmethod
    def GaussMUSCL() -> DivScheme: ...
    @staticmethod
    def GaussLimitedLinear(a0: float) -> DivScheme: ...
    def variant(self) -> str: ...

class Fluid:
    def name(self) -> str: ...
    def base(self) -> PhaseBase: ...
    def state_of_matter(self) -> StateOfMatter: ...
    def is_liquid(self) -> bool: ...
    def is_gas(self) -> bool: ...
    def min_xlm(self) -> float: ...
    def max_xlm(self) -> float: ...
    def is_boussinesq(self) -> bool: ...
    def set_boussinesq(self, value: bool) -> None: ...
    def cumulative_continuity_error(self) -> float: ...
    def set_cumulative_continuity_error(self, value: float) -> None: ...
    def correct_mag_velocity(self) -> None: ...
    def correct_alpha_rho_mag_u(self) -> None: ...
    def correct_thermo_residual_markers(self) -> None: ...

class FvSchemes:
    ddt: DdtScheme
    default_grad: GradScheme
    default_div: DivScheme
    default_laplacian: LaplacianScheme
    default_sn_grad: SnGradScheme
    default_interpolation: InterpolationScheme
    @staticmethod
    def read(path: str) -> FvSchemes: ...
    def __init__(self, ddt: DdtScheme, default_grad: GradScheme, default_div: DivScheme, default_laplacian: LaplacianScheme, default_sn_grad: SnGradScheme, default_interpolation: InterpolationScheme) -> None: ...
    @staticmethod
    def default() -> FvSchemes: ...

class FvSolution:
    pimple: PimpleControl
    @staticmethod
    def read(path: str) -> FvSolution: ...
    @staticmethod
    def default() -> FvSolution: ...

class GradScheme:
    @staticmethod
    def GaussLinear() -> GradScheme: ...
    @staticmethod
    def LeastSquares() -> GradScheme: ...
    @staticmethod
    def FourthOrder() -> GradScheme: ...
    def variant(self) -> str: ...

class HrmFoam:
    control: ControlDict
    schemes: FvSchemes
    solution: FvSolution
    model: HrmModelConfig
    @staticmethod
    def relaxation_time(psi: float, x: float) -> float: ...
    def relaxation_time_with_config(self, psi: float, x: float) -> float: ...

class HrmModelConfig:
    theta_0: float
    pressure_undershoot_exp: float
    liquid_fraction_exp: float
    theta_floor: float
    rho_min: float
    solve_gas_fraction: bool
    adiabatic: bool
    def relaxation_time(self, psi: float, x: float) -> float: ...
    def __init__(self, theta_0: float, pressure_undershoot_exp: float, liquid_fraction_exp: float, theta_floor: float, rho_min: float, solve_gas_fraction: bool, adiabatic: bool) -> None: ...
    @staticmethod
    def default() -> HrmModelConfig: ...

class InterfacialHeatTransfer:
    def nusselt(self, re: float, pr: float) -> float: ...
    @staticmethod
    def Spherical() -> InterfacialHeatTransfer: ...
    @staticmethod
    def RanzMarshall() -> InterfacialHeatTransfer: ...
    @staticmethod
    def ConstantNu(a0: float) -> InterfacialHeatTransfer: ...
    def variant(self) -> str: ...

class InterfacialMassTransfer:
    @staticmethod
    def None_() -> InterfacialMassTransfer: ...
    @staticmethod
    def ConstantRate(a0: float) -> InterfacialMassTransfer: ...
    def variant(self) -> str: ...

class LaplacianScheme:
    @staticmethod
    def GaussLinearCorrected() -> LaplacianScheme: ...
    @staticmethod
    def GaussLinearUncorrected() -> LaplacianScheme: ...
    @staticmethod
    def GaussLinearLimited(a0: float) -> LaplacianScheme: ...
    def variant(self) -> str: ...

class LegacyThermoMechanics:
    def __init__(self, material: ElasticMaterial, rheology: RheologyOption) -> None: ...
    def material(self) -> ElasticMaterial: ...
    def rheology(self) -> RheologyOption: ...

class LinearSolverConfig:
    solver: LinearSolverType
    preconditioner: str | None
    tolerance: float
    rel_tol: float
    max_iter: int
    smoother: str | None
    n_sweep: int
    def __init__(self, solver: LinearSolverType, preconditioner: str | None, tolerance: float, rel_tol: float, max_iter: int, smoother: str | None, n_sweep: int) -> None: ...
    @staticmethod
    def default() -> LinearSolverConfig: ...

class LinearSolverType:
    @staticmethod
    def Pcg() -> LinearSolverType: ...
    @staticmethod
    def PbicgStab() -> LinearSolverType: ...
    @staticmethod
    def Gamg() -> LinearSolverType: ...
    @staticmethod
    def GaussSeidel() -> LinearSolverType: ...
    @staticmethod
    def Diagonal() -> LinearSolverType: ...
    @staticmethod
    def SmoothSolver() -> LinearSolverType: ...
    def variant(self) -> str: ...

class MechanicsMeshSolver:
    def set_corrector_control(self, n_correctors: int, tol: float) -> None: ...
    def solve_displacement(self, quasi_static: bool) -> DisplacementReport: ...
    def advance_time(self) -> None: ...

class MeltFoam:
    control: ControlDict
    schemes: FvSchemes
    solution: FvSolution
    pressure_solver: PressureSolver
    def liquid_fraction(self) -> list[float] | None: ...

class MeshHandler:
    def __init__(self, ) -> None: ...
    def region(self, name: str) -> CouplingRegion | None: ...
    def scalar_integral(self, region: str, field: str) -> float: ...
    @staticmethod
    def default() -> MeshHandler: ...

class MultiPhysicsSolver:
    def __init__(self, handler: MeshHandler, models: list[RegionModel], min_residual: float, max_iterations: int) -> None: ...
    def handler(self) -> MeshHandler: ...
    def model(self, i: int) -> RegionModel | None: ...
    def residual_history(self) -> list[float]: ...
    def solve(self, dt: float) -> int: ...

class NeutronicsModel:
    def kind(self) -> NeutronicsModelKind: ...
    def power(self) -> float: ...
    @staticmethod
    def PointKinetics(a0: PointKineticsModel) -> NeutronicsModel: ...
    @staticmethod
    def Diffusion(a0: DiffusionNeutronics) -> NeutronicsModel: ...
    @staticmethod
    def Sp3(a0: Sp3Neutronics) -> NeutronicsModel: ...
    @staticmethod
    def Sn(a0: SnNeutronics) -> NeutronicsModel: ...
    def variant(self) -> str: ...

class NeutronicsState:
    def energy_groups(self) -> int: ...
    def prec_groups(self) -> int: ...
    def k_eff_raw(self) -> float: ...
    def set_k_eff_raw(self, k_eff: float) -> None: ...
    def total_power(self) -> float: ...
    def set_total_power_raw(self, watts: float) -> None: ...
    def total_power_raw(self) -> float: ...

class PhaseSelector:
    @staticmethod
    def Dispersed() -> PhaseSelector: ...
    @staticmethod
    def Continuous() -> PhaseSelector: ...
    def variant(self) -> str: ...

class PhaseSpecies:
    phase: PhaseSelector
    names: list[str]
    diffusivity: float
    def mean_mass_fraction(self, i: int) -> float: ...

class PhaseThermo:
    cp: float
    kappa: float
    def mean_temperature(self) -> float: ...

class PimpleControl:
    n_outer_correctors: int
    n_correctors: int
    n_non_orthogonal_correctors: int
    consistent: bool
    correct_phi: bool
    def __init__(self, n_outer_correctors: int, n_correctors: int, n_non_orthogonal_correctors: int, consistent: bool, correct_phi: bool) -> None: ...
    @staticmethod
    def default() -> PimpleControl: ...

class PimpleFoam:
    control: ControlDict
    schemes: FvSchemes
    solution: FvSolution
    pressure_solver: PressureSolver

class PointKineticsError:
    @staticmethod
    def MismatchedGroups(betas: int, lambdas: int) -> PointKineticsError: ...
    @staticmethod
    def NoDelayedGroups() -> PointKineticsError: ...
    @staticmethod
    def NonPositivePromptGenerationTime(a0: float) -> PointKineticsError: ...
    @staticmethod
    def NonPositiveDecayConstant(group: int, value: float) -> PointKineticsError: ...
    @staticmethod
    def NonPositiveTimeStep(a0: float) -> PointKineticsError: ...
    @staticmethod
    def SingularSystem(col: int) -> PointKineticsError: ...
    def variant(self) -> str: ...

class PointKineticsParameters:
    def delayed_group_count(self) -> int: ...

class PointKineticsState:
    @staticmethod
    def new_equilibrium(params: PointKineticsParameters, fission_power: float) -> PointKineticsState: ...
    def __init__(self, fission_power: float, precursor_powers: list[float]) -> None: ...
    def fission_power(self) -> float: ...
    def precursor_powers(self) -> list[float]: ...
    def external_source_power(self) -> float: ...

class PowerModel:
    def surface_temperature(self, t: float) -> float: ...
    def power_off(self) -> None: ...
    @staticmethod
    def FixedPower(a0: FixedPower) -> PowerModel: ...
    @staticmethod
    def FixedTemperature(a0: FixedTemperature) -> PowerModel: ...
    def variant(self) -> str: ...

class PressureSolver:
    @staticmethod
    def Pcg() -> PressureSolver: ...
    @staticmethod
    def Gamg() -> PressureSolver: ...
    def variant(self) -> str: ...
    @staticmethod
    def default() -> PressureSolver: ...

class ReactingTwoPhaseEulerFoam:
    heat_transfer: InterfacialHeatTransfer
    mass_transfer: InterfacialMassTransfer
    reaction: ReactionSource
    reaction_mechanism: ReactionMechanism
    latent_heat: float
    residual_alpha: float
    n_energy_correctors: int
    control: ControlDict
    schemes: FvSchemes
    solution: FvSolution
    time: float

class ReactionMechanism:
    @staticmethod
    def None_() -> ReactionMechanism: ...
    @staticmethod
    def Arrhenius(fuel: int, product: int, a_pre: float, e_act: float, delta_h: float) -> ReactionMechanism: ...
    def variant(self) -> str: ...

class ReactionSource:
    @staticmethod
    def None_() -> ReactionSource: ...
    @staticmethod
    def VolumetricHeat(phase: PhaseSelector, q: float) -> ReactionSource: ...
    def variant(self) -> str: ...

class RhoCentralFoam:
    control: ControlDict
    schemes: FvSchemes
    solution: FvSolution
    psi_limit: float

class RhoPimpleFoam:
    control: ControlDict
    schemes: FvSchemes
    solution: FvSolution

class SnGradScheme:
    @staticmethod
    def Corrected() -> SnGradScheme: ...
    @staticmethod
    def Uncorrected() -> SnGradScheme: ...
    @staticmethod
    def Limited(a0: float) -> SnGradScheme: ...
    def variant(self) -> str: ...

class SonicFoam:
    control: ControlDict
    schemes: FvSchemes
    solution: FvSolution

class StartControl:
    @staticmethod
    def StartTime(a0: float) -> StartControl: ...
    @staticmethod
    def LatestTime() -> StartControl: ...
    @staticmethod
    def FirstTime() -> StartControl: ...
    def variant(self) -> str: ...

class StateOfMatter:
    def is_liquid(self) -> bool: ...
    def is_gas(self) -> bool: ...
    def name(self) -> str: ...
    @staticmethod
    def Undetermined() -> StateOfMatter: ...
    @staticmethod
    def Liquid() -> StateOfMatter: ...
    @staticmethod
    def Gas() -> StateOfMatter: ...
    def variant(self) -> str: ...
    @staticmethod
    def default() -> StateOfMatter: ...

class StopControl:
    @staticmethod
    def EndTime(a0: float) -> StopControl: ...
    @staticmethod
    def WriteNow() -> StopControl: ...
    @staticmethod
    def NoWriteNow() -> StopControl: ...
    @staticmethod
    def NextWrite() -> StopControl: ...
    def variant(self) -> str: ...

class TurbulenceClosure:
    def name(self) -> str: ...
    def is_laminar(self) -> bool: ...
    def correct(self) -> None: ...
    def turbulent_prandtl(self) -> float: ...
    def set_k_omega_uniform(self, k: float, scale: float) -> bool: ...
    @staticmethod
    def Laminar() -> TurbulenceClosure: ...
    def variant(self) -> str: ...
    @staticmethod
    def default() -> TurbulenceClosure: ...

class WriteControl:
    @staticmethod
    def TimeStep(a0: int) -> WriteControl: ...
    @staticmethod
    def RunTime(a0: float) -> WriteControl: ...
    @staticmethod
    def AdjustableRunTime(a0: float) -> WriteControl: ...
    @staticmethod
    def CpuTime(a0: float) -> WriteControl: ...
    @staticmethod
    def ClockTime(a0: float) -> WriteControl: ...
    def variant(self) -> str: ...

class WriteFormat:
    @staticmethod
    def Ascii() -> WriteFormat: ...
    @staticmethod
    def Binary() -> WriteFormat: ...
    def variant(self) -> str: ...

def polyharmonic_spline(weights: list[float], x_list: list[list[float]], x_input: list[float], mode: int) -> float: ...
def polyharmonic_spline_function(r_square: float, mode: int) -> float: ...
def solve_polyharmonic_spline(x_list: list[list[float]], v_list: list[float], mode: int) -> list[float]: ...
def multi_regime_boiling_htc(inputs: MultiRegimeBoilingInputs) -> MultiRegimeBoilingResult: ...
def contact_angle_from_degrees(degrees: float) -> float: ...
def read_vol_scalar_field(path: str, n_cells: int) -> list[float]: ...
def parse_faces(text: str, file: str) -> list[list[int]]: ...
def parse_index_list(text: str, file: str) -> list[int]: ...
def parse_points(text: str, file: str) -> list[list[float]]: ...
DZ_A: float
DZ_B: float
THETA_0: float
