"""Type stubs for `outram_park.outram_foam_appbuilder_lib`, generated from the Rust API.

Physical quantities cross this boundary as `float` in SI base units.
"""

class CaseRun:
    case_dir: str
    time: float
    start_time: float
    end_time: float
    delta_t: float
    n_steps: int
    @staticmethod
    def from_case(case_dir: str, kind: SolverKind) -> CaseRun: ...
    def is_done(self) -> bool: ...
    def step(self) -> float: ...
    def run_to_end(self) -> CaseSummary: ...
    def write_fields(self) -> CaseSummary: ...
    def summary(self, output_dir: str) -> CaseSummary: ...

class CaseSummary:
    solver: SolverKind
    n_cells: int
    start_time: float
    end_time: float
    delta_t: float
    n_steps: int
    output_dir: str
    def __init__(self, solver: SolverKind, n_cells: int, start_time: float, end_time: float, delta_t: float, n_steps: int, output_dir: str) -> None: ...

class SolverKind:
    def name(self) -> str: ...
    @staticmethod
    def from_name(name: str) -> SolverKind | None: ...
    def is_case_wired(self) -> bool: ...
    @staticmethod
    def PimpleFoam() -> SolverKind: ...
    @staticmethod
    def RhoCentralFoam() -> SolverKind: ...
    @staticmethod
    def RhoPimpleFoam() -> SolverKind: ...
    @staticmethod
    def SonicFoam() -> SolverKind: ...
    def variant(self) -> str: ...

class SolverState:
    def kind(self) -> SolverKind: ...
    def n_cells(self) -> int: ...
    def step(self) -> None: ...
    def variant(self) -> str: ...

class AppBuilderError:
    @staticmethod
    def Parse(file: str, line: int, msg: str) -> AppBuilderError: ...
    @staticmethod
    def Diverged(iter: int, residual: float) -> AppBuilderError: ...
    @staticmethod
    def TimeLimitReached(t: float) -> AppBuilderError: ...
    @staticmethod
    def Case(case: str, msg: str) -> AppBuilderError: ...
    def variant(self) -> str: ...

class InterpolateTableError:
    @staticmethod
    def LengthMismatch(xs: int, ys: int) -> InterpolateTableError: ...
    @staticmethod
    def TooFewPoints(a0: int) -> InterpolateTableError: ...
    @staticmethod
    def NonAscendingAbscissae(index: int, prev: float, next: float) -> InterpolateTableError: ...
    @staticmethod
    def OutOfBounds(x: float, lo: float, hi: float) -> InterpolateTableError: ...
    def variant(self) -> str: ...

class InterpolationMethod:
    @staticmethod
    def Step() -> InterpolationMethod: ...
    @staticmethod
    def Linear() -> InterpolationMethod: ...
    def variant(self) -> str: ...

class OutOfBounds:
    @staticmethod
    def Error() -> OutOfBounds: ...
    @staticmethod
    def Extrapolation() -> OutOfBounds: ...
    @staticmethod
    def Fixed() -> OutOfBounds: ...
    def variant(self) -> str: ...

class ScalarInterpolateTable:
    def __init__(self, xs: list[float], ys: list[float], method: InterpolationMethod, out_of_bounds: OutOfBounds) -> None: ...
    def method(self) -> InterpolationMethod: ...
    def out_of_bounds(self) -> OutOfBounds: ...
    def interpolate(self, x: float) -> float: ...
    def integral(self, k: float) -> float: ...
    def next_point(self, x: float) -> float: ...
    def last_point(self) -> float: ...
    def first_point(self) -> float: ...

class TimeProfile:
    @staticmethod
    def constant(value: float) -> TimeProfile: ...
    @staticmethod
    def table(times: list[float], values: list[float]) -> TimeProfile: ...
    def with_start_time(self, start_time: float) -> TimeProfile: ...
    def start_time(self) -> float: ...
    def valid(self) -> bool: ...
    def value(self, t: float) -> float: ...

class TimeProfileError:
    @staticmethod
    def LengthMismatch(times: int, values: int) -> TimeProfileError: ...
    @staticmethod
    def TooFewPoints(a0: int) -> TimeProfileError: ...
    @staticmethod
    def NonAscendingTimes(index: int, prev: float, next: float) -> TimeProfileError: ...
    def variant(self) -> str: ...

class CouplingError:
    @staticmethod
    def UnknownRegion(a0: str) -> CouplingError: ...
    @staticmethod
    def DuplicateRegion(a0: str) -> CouplingError: ...
    @staticmethod
    def MissingField(region: str, field: str) -> CouplingError: ...
    def variant(self) -> str: ...

class CouplingField:
    source: str
    target: str
    kind: FieldKind
    combine: MapCombine
    @staticmethod
    def scalar(source: str, target: str) -> CouplingField: ...
    @staticmethod
    def vector(source: str, target: str) -> CouplingField: ...
    def accumulating(self) -> CouplingField: ...
    def __init__(self, source: str, target: str, kind: FieldKind, combine: MapCombine) -> None: ...

class CouplingLoopError:
    @staticmethod
    def MissingField(region: str, field: str) -> CouplingLoopError: ...
    @staticmethod
    def PointKinetics(a0: PointKineticsError) -> CouplingLoopError: ...
    @staticmethod
    def Neutronics(a0: str) -> CouplingLoopError: ...
    @staticmethod
    def NotConverged(residual: float, iterations: int) -> CouplingLoopError: ...
    def variant(self) -> str: ...

class CouplingRegion:
    def __init__(self, name: str, mesh: outram_foam_basic_lib.FvMesh) -> None: ...
    def name(self) -> str: ...
    def mesh(self) -> outram_foam_basic_lib.FvMesh: ...
    def insert_scalar(self, field: outram_foam_basic_lib.VolScalarField) -> None: ...
    def insert_vector(self, field: outram_foam_basic_lib.VolVectorField) -> None: ...
    def scalar(self, name: str) -> outram_foam_basic_lib.VolScalarField | None: ...
    def vector(self, name: str) -> outram_foam_basic_lib.VolVectorField | None: ...

class DopplerLaw:
    @staticmethod
    def Linear() -> DopplerLaw: ...
    @staticmethod
    def Logarithmic() -> DopplerLaw: ...
    def variant(self) -> str: ...

class FeedbackTerm:
    def field_name(self) -> str: ...
    @staticmethod
    def Doppler(field: str, coeff: float, t_ref: float, law: DopplerLaw) -> FeedbackTerm: ...
    @staticmethod
    def Expansion(field: str, coeff: float, t_ref: float) -> FeedbackTerm: ...
    @staticmethod
    def Density(field: str, coeff: float, rho_ref: float) -> FeedbackTerm: ...
    def variant(self) -> str: ...

class FieldKind:
    @staticmethod
    def Scalar() -> FieldKind: ...
    @staticmethod
    def Vector() -> FieldKind: ...
    def variant(self) -> str: ...

class ImportanceWeight:
    @staticmethod
    def Volume() -> ImportanceWeight: ...
    @staticmethod
    def Field(a0: str) -> ImportanceWeight: ...
    def variant(self) -> str: ...

class LumpedNeutronics:
    def __init__(self, region_name: str, params: PointKineticsParameters, initial_power: float, rho_ext: float, alpha: float, t_ref: float, volume: float) -> None: ...
    def fission_power(self) -> float: ...
    def begin_step(self) -> None: ...

class LumpedThermal:
    def __init__(self, region_name: str, heat_capacity: float, conductance: float, t_coolant: float, t_initial: float, volume: float) -> None: ...
    def fuel_temperature(self) -> float: ...
    def begin_step(self) -> None: ...

class MapCombine:
    @staticmethod
    def Replace() -> MapCombine: ...
    @staticmethod
    def Accumulate() -> MapCombine: ...
    def variant(self) -> str: ...

class MappingMethod:
    @staticmethod
    def NearestCell() -> MappingMethod: ...
    @staticmethod
    def InverseDistance(n_neighbours: int) -> MappingMethod: ...
    @staticmethod
    def CellVolumeWeight() -> MappingMethod: ...
    def variant(self) -> str: ...

class MeshNeutronics:
    def k_eff(self) -> float: ...
    def fission_power(self) -> float: ...
    def model(self) -> DiffusionNeutronics: ...
    def feedback_reactivity(self, region: CouplingRegion) -> float: ...

class MeshThermalHydraulics:
    def __init__(self, region_name: str, n_cells: int, rho_cp: float, tau: float, t_coolant: float, t_initial: float) -> None: ...
    def temperatures(self) -> list[float]: ...
    def mean_temperature(self) -> float: ...
    def begin_step(self) -> None: ...

class MeshToMesh:
    def __init__(self, source: outram_foam_basic_lib.FvMesh, target: outram_foam_basic_lib.FvMesh, method: MappingMethod) -> None: ...
    def source(self) -> outram_foam_basic_lib.FvMesh: ...
    def target(self) -> outram_foam_basic_lib.FvMesh: ...
    def method(self) -> MappingMethod: ...
    def interpolate_scalar(self, source_field: outram_foam_basic_lib.VolScalarField, name: str) -> outram_foam_basic_lib.VolScalarField: ...
    @staticmethod
    def integral(mesh: outram_foam_basic_lib.FvMesh, field: outram_foam_basic_lib.VolScalarField) -> float: ...

class PolyharmonicMode:
    def as_mode(self) -> int: ...
    @staticmethod
    def Linear() -> PolyharmonicMode: ...
    @staticmethod
    def ThinPlate() -> PolyharmonicMode: ...
    @staticmethod
    def Cubic() -> PolyharmonicMode: ...
    @staticmethod
    def ThinPlate4() -> PolyharmonicMode: ...
    def variant(self) -> str: ...

class PrescribedRegion:
    def __init__(self, region_name: str) -> None: ...

class RbfFieldMap:
    @staticmethod
    def build(sample_points: list[outram_foam_basic_lib.Vector3], values: list[float], mode: PolyharmonicMode) -> RbfFieldMap: ...
    def evaluate(self, point: outram_foam_basic_lib.Vector3) -> float: ...
    def map_onto(self, target: outram_foam_basic_lib.FvMesh, name: str) -> outram_foam_basic_lib.VolScalarField: ...

class RbfMapError:
    @staticmethod
    def EmptyOrMismatched(n_points: int, n_values: int) -> RbfMapError: ...
    @staticmethod
    def Singular() -> RbfMapError: ...
    def variant(self) -> str: ...

class ReactivityFeedback:
    def __init__(self, ) -> None: ...
    def with_weight(self, weight: ImportanceWeight) -> ReactivityFeedback: ...
    def with_doppler(self, field: str, coeff: float, t_ref: float, law: DopplerLaw) -> ReactivityFeedback: ...
    def with_expansion(self, field: str, coeff: float, t_ref: float) -> ReactivityFeedback: ...
    def with_density(self, field: str, coeff: float, rho_ref: float) -> ReactivityFeedback: ...
    def terms(self) -> list[FeedbackTerm]: ...
    def reactivity(self, region: CouplingRegion) -> float: ...
    def weighted_mean(self, region: CouplingRegion, field: str) -> float: ...
    @staticmethod
    def default() -> ReactivityFeedback: ...

class RegionModel:
    def begin_step(self) -> None: ...
    def region_name(self) -> str: ...
    def correct_only_energy(self) -> bool: ...
    @staticmethod
    def Neutronics(a0: LumpedNeutronics) -> RegionModel: ...
    @staticmethod
    def ThermalHydraulics(a0: LumpedThermal) -> RegionModel: ...
    @staticmethod
    def Prescribed(a0: PrescribedRegion) -> RegionModel: ...
    @staticmethod
    def MeshNeutronics(a0: MeshNeutronics) -> RegionModel: ...
    @staticmethod
    def MeshThermalHydraulics(a0: MeshThermalHydraulics) -> RegionModel: ...
    def variant(self) -> str: ...

class DiffusionSettings:
    k_tolerance: float
    flux_tolerance: float
    max_outer_iterations: int
    linear: outram_foam_basic_lib.SolverSettings
    def __init__(self, k_tolerance: float | None = None, flux_tolerance: float | None = None, max_outer_iterations: int | None = None, linear: outram_foam_basic_lib.SolverSettings | None = None) -> None: ...
    @staticmethod
    def default() -> DiffusionSettings: ...

class EigenvalueReport:
    k_eff: float
    outer_iterations: int
    k_residual: float
    flux_residual: float
    converged: bool
    def __init__(self, k_eff: float, outer_iterations: int, k_residual: float, flux_residual: float, converged: bool) -> None: ...

class NeutronicsError:
    @staticmethod
    def PointKinetics(a0: PointKineticsError) -> NeutronicsError: ...
    @staticmethod
    def PatchCountMismatch(given: int, patches: int) -> NeutronicsError: ...
    @staticmethod
    def NoFissionSource() -> NeutronicsError: ...
    @staticmethod
    def NotConverged(outer_iterations: int, k_residual: float, flux_residual: float) -> NeutronicsError: ...
    @staticmethod
    def NonPositiveTimeStep(a0: float) -> NeutronicsError: ...
    @staticmethod
    def ModelNotImplemented(a0: NeutronicsModelKind) -> NeutronicsError: ...
    def variant(self) -> str: ...

class NeutronicsModelKind:
    @staticmethod
    def PointKinetics() -> NeutronicsModelKind: ...
    @staticmethod
    def Diffusion() -> NeutronicsModelKind: ...
    @staticmethod
    def Sp3() -> NeutronicsModelKind: ...
    @staticmethod
    def Sn() -> NeutronicsModelKind: ...
    def variant(self) -> str: ...

class PointKineticsModel:
    def __init__(self, params: PointKineticsParameters, state: PointKineticsState) -> None: ...
    def params(self) -> PointKineticsParameters: ...
    def state(self) -> PointKineticsState: ...
    def step(self, dt: float, reactivity: float, external_source_power: float) -> None: ...

class SnNeutronics:
    def __init__(self, mesh: outram_foam_basic_lib.FvMesh, energy_groups: int, prec_groups: int) -> None: ...
    def state(self) -> NeutronicsState: ...
    def settings(self) -> SnSettings: ...
    def quadrature(self) -> AngularQuadrature | None: ...
    def energy_groups(self) -> int: ...
    def solve_eigenvalue(self) -> EigenvalueReport: ...

class Sp3Neutronics:
    def step(self, dt: float) -> None: ...
    def solve_eigenvalue(self) -> EigenvalueReport: ...
    def __init__(self, mesh: outram_foam_basic_lib.FvMesh, energy_groups: int, prec_groups: int) -> None: ...
    def state(self) -> NeutronicsState: ...
    def xs_fields(self) -> Sp3XsFields | None: ...
    def settings(self) -> Sp3Settings: ...
    def flux_star(self) -> list[outram_foam_basic_lib.VolScalarField]: ...
    def flux_star2(self) -> list[outram_foam_basic_lib.VolScalarField]: ...
    def energy_groups(self) -> int: ...
    def prec_groups(self) -> int: ...

class DiffusionXsFields:
    energy_groups: int
    prec_groups: int
    d: list[outram_foam_basic_lib.VolScalarField]
    d_face: list[outram_foam_basic_lib.SurfaceScalarField]
    nu_sigma_f: list[outram_foam_basic_lib.VolScalarField]
    sigma_pow: list[outram_foam_basic_lib.VolScalarField]
    sigma_removal: list[outram_foam_basic_lib.VolScalarField]
    chi_prompt: list[outram_foam_basic_lib.VolScalarField]
    chi_delayed: list[outram_foam_basic_lib.VolScalarField]
    inv_velocity: list[outram_foam_basic_lib.VolScalarField]
    scattering: list[list[outram_foam_basic_lib.VolScalarField]]
    beta: list[outram_foam_basic_lib.VolScalarField]
    beta_tot: outram_foam_basic_lib.VolScalarField
    @staticmethod
    def materialize(mesh: outram_foam_basic_lib.FvMesh, xs: CrossSectionData, zone_of_cell: list[int], raw_parameters: list[float]) -> DiffusionXsFields: ...

class AngularQuadrature:
    @staticmethod
    def level_symmetric(order: QuadratureOrder) -> AngularQuadrature: ...
    def order(self) -> QuadratureOrder: ...
    def direction_count(self) -> int: ...
    def directions(self) -> list[outram_foam_basic_lib.Vector3]: ...
    def weights(self) -> list[float]: ...
    def weight_sum(self) -> float: ...
    def face_phi(self, mesh: outram_foam_basic_lib.FvMesh, direction: int) -> outram_foam_basic_lib.SurfaceScalarField: ...

class QuadratureOrder:
    def n(self) -> int: ...
    def direction_count(self) -> int: ...
    @staticmethod
    def S2() -> QuadratureOrder: ...
    @staticmethod
    def S4() -> QuadratureOrder: ...
    @staticmethod
    def S6() -> QuadratureOrder: ...
    def variant(self) -> str: ...

class SnSettings:
    k_tolerance: float
    flux_tolerance: float
    max_outer_iterations: int
    max_inner_iterations: int
    inner_tolerance: float
    linear: outram_foam_basic_lib.SolverSettings
    def __init__(self, k_tolerance: float | None = None, flux_tolerance: float | None = None, max_outer_iterations: int | None = None, max_inner_iterations: int | None = None, inner_tolerance: float | None = None, linear: outram_foam_basic_lib.SolverSettings | None = None) -> None: ...
    @staticmethod
    def default() -> SnSettings: ...

class Sp3Settings:
    k_tolerance: float
    flux_tolerance: float
    max_outer_iterations: int
    linear: outram_foam_basic_lib.SolverSettings
    def __init__(self, k_tolerance: float | None = None, flux_tolerance: float | None = None, max_outer_iterations: int | None = None, linear: outram_foam_basic_lib.SolverSettings | None = None) -> None: ...
    @staticmethod
    def default() -> Sp3Settings: ...

class Sp3XsFields:
    base: DiffusionXsFields
    sigma_total: list[outram_foam_basic_lib.VolScalarField]
    d2: list[outram_foam_basic_lib.VolScalarField]
    d2_face: list[outram_foam_basic_lib.SurfaceScalarField]
    second_moment_removal: list[outram_foam_basic_lib.VolScalarField]
    @staticmethod
    def materialize(mesh: outram_foam_basic_lib.FvMesh, xs: CrossSectionData, zone_of_cell: list[int], raw_parameters: list[float]) -> Sp3XsFields: ...
    def energy_groups(self) -> int: ...
    def prec_groups(self) -> int: ...
    def __init__(self, base: DiffusionXsFields, sigma_total: list[outram_foam_basic_lib.VolScalarField], d2: list[outram_foam_basic_lib.VolScalarField], d2_face: list[outram_foam_basic_lib.SurfaceScalarField], second_moment_removal: list[outram_foam_basic_lib.VolScalarField]) -> None: ...

class GroupConstants:
    diffusion_coefficient: float
    nu_sigma_f: float
    sigma_removal: float
    chi_prompt: float
    chi_delayed: float
    disc_factor: float

class NuclearDataInput:
    energy_groups: int
    prec_groups: int
    legendre_moments: int
    poly_spline_mode: int
    fast_neutrons: bool
    xs_variables: list[XsVariable]
    do_not_parametrize: list[int]
    states: list[StateInput]
    def __init__(self, energy_groups: int, prec_groups: int, legendre_moments: int, poly_spline_mode: int, fast_neutrons: bool, xs_variables: list[XsVariable], do_not_parametrize: list[int], states: list[StateInput]) -> None: ...

class NuclearDataOneEnergy:
    def __init__(self, poly_spline_mode: int, n_parameters: int) -> None: ...
    def add_data(self, value: float, parameters: list[float]) -> None: ...
    def build(self) -> None: ...
    def get_ref(self) -> float: ...
    def get(self, parameters: list[float], is_parametrize: bool) -> float: ...
    def data_len(self) -> int: ...

class PrecursorConstants:
    beta: list[float]
    beta_tot: float

class StateInput:
    name: str
    zones: list[ZoneStateInput]

class VariableLaw:
    @staticmethod
    def from_keyword(keyword: str) -> VariableLaw | None: ...
    def keyword(self) -> str: ...
    def transform(self, value: float) -> float: ...
    @staticmethod
    def Linear() -> VariableLaw: ...
    @staticmethod
    def Log() -> VariableLaw: ...
    @staticmethod
    def Sqrt() -> VariableLaw: ...
    def variant(self) -> str: ...

class XsError:
    @staticmethod
    def NoStates() -> XsError: ...
    @staticmethod
    def ReferenceStateNotFirst(found: str) -> XsError: ...
    @staticmethod
    def MissingReferenceVariable(name: str) -> XsError: ...
    @staticmethod
    def UnknownVariableLaw(name: str, law: str) -> XsError: ...
    @staticmethod
    def MissingZoneConstants(zone: str) -> XsError: ...
    @staticmethod
    def SingularRbfMatrix(detail: str) -> XsError: ...
    def variant(self) -> str: ...

class XsVariable:
    name: str
    law: VariableLaw
    def __init__(self, name: str, law: VariableLaw) -> None: ...

class ZoneConstantsInput:
    fuel_fraction: float
    secondary_power_volume_fraction: float
    fraction_to_secondary_power: float
    df_adjust: bool
    iv: list[float]
    disc_factor: list[float]
    integral_flux: list[float]
    beta: list[float]
    def __init__(self) -> None: ...
    @staticmethod
    def default() -> ZoneConstantsInput: ...

class ZoneNuclearData:
    @staticmethod
    def new_reference(zone: ZoneStateInput, energy_groups: int, prec_groups: int, legendre_moments: int, poly_spline_mode: int, n_parameters: int) -> ZoneNuclearData: ...
    def add_state_data(self, zone: ZoneStateInput, parameters: list[float]) -> None: ...
    def build(self) -> None: ...
    def name(self) -> str: ...
    def energy_groups(self) -> int: ...
    def prec_groups(self) -> int: ...
    def legendre_moments(self) -> int: ...
    def fuel_fraction(self) -> float: ...
    def secondary_power_volume_fraction(self) -> float: ...
    def fraction_to_secondary_power(self) -> float: ...
    def df_adjust(self) -> bool: ...
    def diffusion_coefficient(self, group: int, parameters: list[float], parametrize: bool) -> float: ...
    def nu_sigma_f(self, group: int, parameters: list[float], parametrize: bool) -> float: ...
    def sigma_pow(self, group: int, parameters: list[float], parametrize: bool) -> float: ...
    def sigma_removal(self, group: int, parameters: list[float], parametrize: bool) -> float: ...
    def chi_prompt(self, group: int, parameters: list[float], parametrize: bool) -> float: ...
    def chi_delayed(self, group: int, parameters: list[float], parametrize: bool) -> float: ...
    def scattering(self, moment: int, energy_j: int, energy_i: int, parameters: list[float], parametrize: bool) -> float: ...
    def diffusion_coefficient_ref(self, group: int) -> float: ...
    def inverse_velocity(self, group: int) -> float: ...
    def disc_factor(self, group: int) -> float: ...
    def integral_flux(self, group: int) -> float: ...
    def beta(self, prec: int) -> float: ...
    def beta_tot(self) -> float: ...

class ZoneStateInput:
    name: str
    d: list[float]
    nu_sigma_eff: list[float]
    sigma_pow: list[float]
    sigma_removal: list[float]
    chi_prompt: list[float]
    chi_delayed: list[float]
    scattering: list[list[list[float]]]
    constants: ZoneConstantsInput | None
    def __init__(self, name: str, d: list[float], nu_sigma_eff: list[float], sigma_pow: list[float], sigma_removal: list[float], chi_prompt: list[float], chi_delayed: list[float], scattering: list[list[list[float]]], constants: ZoneConstantsInput | None) -> None: ...

class BaffleSide:
    @staticmethod
    def Master() -> BaffleSide: ...
    @staticmethod
    def Slave() -> BaffleSide: ...
    def variant(self) -> str: ...

class BlackBodyRadiationBc:
    emissivity: float
    kappa: float
    ambient_temperature: float
    def __init__(self, emissivity: float, kappa: float, ambient_temperature: float) -> None: ...
    def fourier_heat_flux(self, face_temperature: float, cell_temperature: float, cell_to_face_distance: float) -> float: ...
    def face_temperature_from_flux(self, heat_flux: float) -> float: ...
    def update_face_temperature(self, current_face_temperature: float, cell_temperature: float, cell_to_face_distance: float) -> float: ...

class NusseltCorrelationCoefficients:
    const_term: float
    coeff: float
    exp_reynolds: float
    exp_prandtl: float
    def __init__(self, const_term: float, coeff: float, exp_reynolds: float, exp_prandtl: float) -> None: ...

class NusseltThermalBaffle1DBc:
    thickness: float
    wall_conductivity: float
    master_correlation: NusseltCorrelationCoefficients
    slave_correlation: NusseltCorrelationCoefficients
    def __init__(self, thickness: float, wall_conductivity: float, master_correlation: NusseltCorrelationCoefficients, slave_correlation: NusseltCorrelationCoefficients) -> None: ...
    def convective_htc(self, _side: BaffleSide, _reynolds: float, _prandtl: float, _fluid_conductivity: float, _hydraulic_diameter: float) -> float: ...
    def coupled_wall_temperatures(self, _master_fluid_temperature: float, _slave_fluid_temperature: float, _master_htc: float, _slave_htc: float) -> tuple[float, float]: ...

class TimeFieldTable:
    def __init__(self, times: list[float], values: list[list[float]]) -> None: ...
    def n_faces(self) -> int: ...
    def value(self, t: float) -> list[float]: ...

class TimeFieldTableError:
    @staticmethod
    def LengthMismatch(times: int, rows: int) -> TimeFieldTableError: ...
    @staticmethod
    def InconsistentRowLength(index: int, expected: int, got: int) -> TimeFieldTableError: ...
    @staticmethod
    def Table(a0: InterpolateTableError) -> TimeFieldTableError: ...
    def variant(self) -> str: ...

class VelocityRundownBc:
    const_a: float
    coeff_b: float
    exp_c: float
    start_time: float
    def __init__(self, const_a: float, coeff_b: float, exp_c: float, start_time: float) -> None: ...
    def rundown_factor(self, t: float) -> float: ...
    def velocity(self, reference_velocity: outram_foam_basic_lib.Vector3, t: float) -> outram_foam_basic_lib.Vector3: ...

class FfDragCoefficient:
    def drag_coefficient(self, state: FfInterfacialState) -> float: ...
    @staticmethod
    def no_kazimi_from_geometry(pin_pitch: float, pin_diameter: float) -> FfDragCoefficient: ...
    @staticmethod
    def Wallis() -> FfDragCoefficient: ...
    @staticmethod
    def SchillerNaumann() -> FfDragCoefficient: ...
    @staticmethod
    def Bestion() -> FfDragCoefficient: ...
    @staticmethod
    def BestionTrace() -> FfDragCoefficient: ...
    @staticmethod
    def Autruffe() -> FfDragCoefficient: ...
    @staticmethod
    def NoKazimi(a: float) -> FfDragCoefficient: ...
    def variant(self) -> str: ...

class FfInterfacialState:
    vapour_fraction: float
    reynolds_number: float
    rho_vapour: float
    rho_liquid: float
    rho_continuous: float
    dh_dispersed: float
    dh_continuous: float
    u_vapour: float
    u_liquid: float
    u_relative: float
    def __init__(self, vapour_fraction: float, reynolds_number: float, rho_vapour: float, rho_liquid: float, rho_continuous: float, dh_dispersed: float, dh_continuous: float, u_vapour: float, u_liquid: float, u_relative: float) -> None: ...

class TwoPhaseDragMultiplier:
    def multiplier(self, phase_fraction: float, x_lm: float) -> float: ...
    @staticmethod
    def ChenKalish() -> TwoPhaseDragMultiplier: ...
    @staticmethod
    def Constant(phi2: float) -> TwoPhaseDragMultiplier: ...
    @staticmethod
    def Kaiser74() -> TwoPhaseDragMultiplier: ...
    @staticmethod
    def Kaiser88() -> TwoPhaseDragMultiplier: ...
    @staticmethod
    def KottowskiSavatteri() -> TwoPhaseDragMultiplier: ...
    @staticmethod
    def LockhartMartinelli(c: float, max_phi2: float) -> TwoPhaseDragMultiplier: ...
    @staticmethod
    def LottesFlinn(exp: float) -> TwoPhaseDragMultiplier: ...
    @staticmethod
    def LottesFlinnNguyen(exp: float) -> TwoPhaseDragMultiplier: ...
    def variant(self) -> str: ...

class FsWallFriction:
    def friction_factor(self, re: float) -> float: ...
    @staticmethod
    def rehme_from_geometry(number_of_pins: float, pin_diameter: float, wire_diameter: float, wire_lead_length: float, wetted_wrap_perimeter: float) -> FsWallFriction: ...
    @staticmethod
    def baxi_dalle_donne_from_geometry(pin_diameter: float, wire_diameter: float, wire_lead_length: float) -> FsWallFriction: ...
    @staticmethod
    def no_kazimi_from_geometry(pin_diameter: float, wire_diameter: float, wire_lead_length: float) -> FsWallFriction: ...
    @staticmethod
    def Churchill(surface_roughness: float) -> FsWallFriction: ...
    @staticmethod
    def Colebrook(coeff: float, constant: float, exp: float) -> FsWallFriction: ...
    @staticmethod
    def ReynoldsPower(coeff: float, exp: float, constant: float) -> FsWallFriction: ...
    @staticmethod
    def Rehme(a: float, b1: float, b2: float) -> FsWallFriction: ...
    @staticmethod
    def Engel() -> FsWallFriction: ...
    @staticmethod
    def ModifiedEngel() -> FsWallFriction: ...
    @staticmethod
    def BaxiDalleDonne(a: float, b: float, c: float) -> FsWallFriction: ...
    @staticmethod
    def NoKazimi(a: float, b: float, c: float) -> FsWallFriction: ...
    def variant(self) -> str: ...

class MultiRegimeBoilingInputs:
    t_wall: float
    t_fluid: float
    t_sat: float
    vapour_void_fraction: float
    htc_forced_convection_enhanced: float
    htc_pool_boiling: float
    htc_film_condensation: float | None
    suppression_factor: float | None
    t_onset_nucleate_boiling: float | None
    htc_pool_boiling_at_onset: float | None
    superposition_exponent: float
    heat_flux_superposition: bool
    def __init__(self, t_wall: float, t_fluid: float, t_sat: float, vapour_void_fraction: float, htc_forced_convection_enhanced: float, htc_pool_boiling: float, htc_film_condensation: float | None, suppression_factor: float | None, t_onset_nucleate_boiling: float | None, htc_pool_boiling_at_onset: float | None, superposition_exponent: float, heat_flux_superposition: bool) -> None: ...

class MultiRegimeBoilingResult:
    htc: float
    nucleate_boiling_heat_flux: float | None
    forced_convection_heat_flux: float | None
    def __init__(self, htc: float, nucleate_boiling_heat_flux: float | None, forced_convection_heat_flux: float | None) -> None: ...

class CriticalHeatFlux:
    def value(self) -> float: ...
    @staticmethod
    def Constant(a0: float) -> CriticalHeatFlux: ...
    def variant(self) -> str: ...

class FlowEnhancementFactor:
    def value(self, inputs: FlowEnhancementInputs) -> float: ...
    @staticmethod
    def Chen(max_value: float) -> FlowEnhancementFactor: ...
    @staticmethod
    def RezkallahSims(exponent: float, max_value: float) -> FlowEnhancementFactor: ...
    @staticmethod
    def CobraTf(max_value: float) -> FlowEnhancementFactor: ...
    def variant(self) -> str: ...

class FlowEnhancementInputs:
    inverse_lockhart_martinelli: float
    liquid_void_fraction: float
    mixture_reynolds_number: float
    single_phase_reynolds_number: float
    def __init__(self, inverse_lockhart_martinelli: float, liquid_void_fraction: float, mixture_reynolds_number: float, single_phase_reynolds_number: float) -> None: ...

class LeidenfrostTemperature:
    def temperature(self, pressure: float, t_sat: float) -> float: ...
    @staticmethod
    def GroeneveldStewart(critical_pressure: float) -> LeidenfrostTemperature: ...
    def variant(self) -> str: ...

class OnsetOfNucleateBoilingTemperature:
    def temperature(self, htc_forced_convection_enhanced: float, t_fluid: float, t_sat: float, other_phase_density: float, latent_heat: float, thermal_conductivity: float) -> float: ...
    @staticmethod
    def Basu(surface_tension: float, contact_angle: float) -> OnsetOfNucleateBoilingTemperature: ...
    def variant(self) -> str: ...

class SubcooledBoilingFraction:
    def fraction(self, heat_flux: float, thermal_conductivity: float, hydraulic_diameter: float, re: float, pr: float, t_sat: float, t_fluid: float) -> float: ...
    @staticmethod
    def Constant(value: float) -> SubcooledBoilingFraction: ...
    @staticmethod
    def SahaZuber() -> SubcooledBoilingFraction: ...
    def variant(self) -> str: ...

class SuppressionFactor:
    def value(self, inputs: SuppressionInputs) -> float: ...
    @staticmethod
    def Chen() -> SuppressionFactor: ...
    @staticmethod
    def CobraTf() -> SuppressionFactor: ...
    def variant(self) -> str: ...

class SuppressionInputs:
    mixture_reynolds_number: float
    t_fluid: float
    t_wall: float
    t_sat: float
    def __init__(self, mixture_reynolds_number: float, t_fluid: float, t_wall: float, t_sat: float) -> None: ...

class FfForcedConvectionHtc:
    def heat_transfer_coefficient(self, re: float, pr: float, k: float, d_h: float) -> float: ...
    @staticmethod
    def Nusselt(a: float, b: float, c: float, d: float) -> FfForcedConvectionHtc: ...
    def variant(self) -> str: ...

class FsForcedConvectionHtc:
    def heat_transfer_coefficient(self, re: float, pr: float, k: float, d_h: float, wall_fluid_temperatures: tuple[float, float] | None) -> float: ...
    @staticmethod
    def Nusselt(a: float, b: float, c: float, d: float, e: float) -> FsForcedConvectionHtc: ...
    @staticmethod
    def NusseltAndWall(a: float, b: float, c: float, d: float, h_wall: float) -> FsForcedConvectionHtc: ...
    def variant(self) -> str: ...

class PoolBoilingHtc:
    def heat_transfer_coefficient_from_delta_t(self, delta_t: float, pressure: float) -> float: ...
    def heat_transfer_coefficient_from_heat_flux(self, heat_flux: float, pressure: float) -> float: ...
    @staticmethod
    def Shah() -> PoolBoilingHtc: ...
    @staticmethod
    def Gorenflo(surface_roughness: float) -> PoolBoilingHtc: ...
    def variant(self) -> str: ...

class InterfacialArea:
    def area_concentration(self, alpha_dispersed: float, alpha_continuous: float, dispersed_diameter: float) -> float: ...
    @staticmethod
    def no_kazimi_from_geometry(pin_diameter_m: float, pin_pitch_m: float) -> InterfacialArea: ...
    @staticmethod
    def schor_from_geometry(pin_diameter_m: float, pin_pitch_m: float, cutoff_alpha: float, min_area_at_large_alpha: float) -> InterfacialArea: ...
    @staticmethod
    def Spherical(cutoff_alpha: float) -> InterfacialArea: ...
    @staticmethod
    def Annular(cutoff_alpha: float) -> InterfacialArea: ...
    @staticmethod
    def NoKazimi(a_const: float, pin_diameter_m: float) -> InterfacialArea: ...
    @staticmethod
    def Schor(pin_diameter_m: float, a_const: float, cutoff_alpha: float, min_area_at_large_alpha: float, ia1: float, ia2: float) -> InterfacialArea: ...
    def variant(self) -> str: ...

class ContactPartition:
    def value(self, input: float) -> float: ...
    @staticmethod
    def Linear() -> ContactPartition: ...
    @staticmethod
    def Complementary() -> ContactPartition: ...
    def variant(self) -> str: ...

class BubbleDiameter:
    def diameter(self, pressure: float, temperature: float) -> float: ...
    @staticmethod
    def IsomolarBubble(d0_m: float, p0_pa: float, t0_k: float) -> BubbleDiameter: ...
    @staticmethod
    def IsothermalBubble(d0_m: float, p0_pa: float) -> BubbleDiameter: ...
    def variant(self) -> str: ...

class FilmDiameter:
    def diameter(self, alpha_normalized: float, structure_hydraulic_diameter: float) -> float: ...
    @staticmethod
    def PipeFilm(residual_alpha: float) -> FilmDiameter: ...
    @staticmethod
    def WallisFilm(residual_alpha: float) -> FilmDiameter: ...
    def variant(self) -> str: ...

class TurbulentDispersion:
    @staticmethod
    def constant_for_fluid1(dict_value: float, dispersed_phase_is_fluid1: bool) -> TurbulentDispersion: ...
    def value_for_fluid1(self) -> float: ...
    def value_for_fluid2(self) -> float: ...
    @staticmethod
    def Constant(value_for_fluid1: float) -> TurbulentDispersion: ...
    def variant(self) -> str: ...

class RegimeBound:
    name: str
    lower: float
    upper: float
    def __init__(self, name: str, lower: float, upper: float) -> None: ...

class RegimeInterpolationMode:
    @staticmethod
    def Linear() -> RegimeInterpolationMode: ...
    @staticmethod
    def Quadratic() -> RegimeInterpolationMode: ...
    def variant(self) -> str: ...

class RegimeMap1D:
    def __init__(self, regimes: list[RegimeBound], interpolation_mode: RegimeInterpolationMode) -> None: ...
    def regime_weights(self, parameter: float) -> list[tuple[str, float]]: ...

class VirtualMassCoefficient:
    @staticmethod
    def constant(cvm: float) -> VirtualMassCoefficient: ...
    def coefficient(self) -> float: ...
    @staticmethod
    def Constant(cvm: float) -> VirtualMassCoefficient: ...
    def variant(self) -> str: ...

class LatentHeatModel:
    def latent_heat(self, t: float, h_vapour: float, h_liquid: float) -> float: ...
    @staticmethod
    def FinkLeibowitz() -> LatentHeatModel: ...
    @staticmethod
    def Water() -> LatentHeatModel: ...
    @staticmethod
    def FromThermophysicalProperties() -> LatentHeatModel: ...
    def variant(self) -> str: ...

class PhaseChangeRateModel:
    @staticmethod
    def HeatDrivenConductionLimited() -> PhaseChangeRateModel: ...
    @staticmethod
    def HeatDrivenTwoPhaseDriven() -> PhaseChangeRateModel: ...
    @staticmethod
    def HeatDrivenOnePhaseDriven(driving_is_phase1: bool) -> PhaseChangeRateModel: ...
    @staticmethod
    def HeatDrivenMixedDriven(driving_is_phase1: bool) -> PhaseChangeRateModel: ...
    def variant(self) -> str: ...

class SaturationModel:
    def t_sat(self, p: float) -> float: ...
    def p_sat(self, t: float, p: float) -> float: ...
    def ln_p_sat(self, t: float, p: float) -> float: ...
    @staticmethod
    def ConstantTemperature(t_sat: float) -> SaturationModel: ...
    @staticmethod
    def Water() -> SaturationModel: ...
    @staticmethod
    def WaterTrace() -> SaturationModel: ...
    @staticmethod
    def BrowningPotter() -> SaturationModel: ...
    def variant(self) -> str: ...

class LaheyBubbleClosure:
    cp: float
    cmub: float
    c3: float
    alpha_inversion: float
    @staticmethod
    def new_default() -> LaheyBubbleClosure: ...
    def bubble_induced_eddy_viscosity(self, dh_gas: float, alpha_gas: float, relative_velocity: float) -> float: ...
    def bubble_induced_production(self, drag_coefficient: float, alpha_gas: float, relative_velocity: float, dh_gas: float) -> float: ...
    def phase_transfer_rate(self, alpha_gas: float, gas_k: float, gas_epsilon: float, timestep: float) -> float: ...
    def k_production_rate(self, alpha_gas: float, bubble_induced_production: float, phase_transfer_rate: float, gas_k: float, local_k: float) -> float: ...
    def __init__(self, cp: float, cmub: float, c3: float, alpha_inversion: float) -> None: ...

class MixtureKEpsilonClosure:
    cmu: float
    cp: float
    c3: float
    @staticmethod
    def new_default() -> MixtureKEpsilonClosure: ...
    @staticmethod
    def effective_gas_density(rho_gas: float, virtual_mass_coefficient: float, rho_liquid: float) -> float: ...
    @staticmethod
    def mixture_density(alpha_liquid: float, rho_liquid_eff: float, alpha_gas: float, rho_gas_eff: float) -> float: ...
    @staticmethod
    def mix_k(alpha_liquid: float, rho_liquid_eff: float, liquid_k: float, alpha_gas: float, rho_gas_eff: float, gas_k: float) -> float: ...
    @staticmethod
    def mix_epsilon(alpha_liquid: float, rho_liquid_eff: float, liquid_epsilon: float, alpha_gas: float, rho_gas_eff: float, gas_epsilon: float) -> float: ...
    def __init__(self, cmu: float, cp: float, c3: float) -> None: ...

class PorousKEpsilon2PhaseClosure:
    base: PorousKEpsilonClosure
    turbulence_intensity_alpha_coeff: float
    def equilibrium_k(self, speed: float, reynolds_number: float, relative_alpha: float) -> float: ...
    def __init__(self, base: PorousKEpsilonClosure, turbulence_intensity_alpha_coeff: float) -> None: ...

class PorousKEpsilonClosure:
    cmu: float
    turbulence_intensity_coeff: float
    turbulence_intensity_exp: float
    turbulence_length_scale_coeff: float
    def equilibrium_k(self, speed: float, reynolds_number: float) -> float: ...
    def equilibrium_epsilon(self, equilibrium_k: float, structure_dh: float) -> float: ...
    @staticmethod
    def nut_stabilization(speed: float, dh_struct: float, laminar_re_struct: float) -> float: ...
    def __init__(self, cmu: float, turbulence_intensity_coeff: float, turbulence_intensity_exp: float, turbulence_length_scale_coeff: float) -> None: ...

class Extents:
    min: outram_foam_basic_lib.Vector3
    max: outram_foam_basic_lib.Vector3
    def __init__(self, min: outram_foam_basic_lib.Vector3, max: outram_foam_basic_lib.Vector3) -> None: ...

class MassFlowRegion:
    @staticmethod
    def Patch(a0: int) -> MassFlowRegion: ...
    @staticmethod
    def Faces(a0: list[int]) -> MassFlowRegion: ...
    def variant(self) -> str: ...

class PatchReduceOp:
    @staticmethod
    def Sum() -> PatchReduceOp: ...
    @staticmethod
    def Average() -> PatchReduceOp: ...
    @staticmethod
    def Min() -> PatchReduceOp: ...
    @staticmethod
    def Max() -> PatchReduceOp: ...
    @staticmethod
    def Integral() -> PatchReduceOp: ...
    def variant(self) -> str: ...

class StopDecision:
    stop: bool
    max_diff: float
    def __init__(self, stop: bool, max_diff: float) -> None: ...

class PhaseBase:
    def __init__(self, mesh: outram_foam_basic_lib.FvMesh, name: str) -> None: ...
    def name(self) -> str: ...
    def mesh(self) -> outram_foam_basic_lib.FvMesh: ...
    def alpha(self) -> outram_foam_basic_lib.VolScalarField: ...
    def residual_alpha(self) -> float: ...
    def set_residual_alpha(self, value: float) -> None: ...

class OnePhaseSolver:
    fluid: Fluid
    p: outram_foam_basic_lib.VolScalarField
    drag: PorousDrag
    nu_eff: outram_foam_basic_lib.VolScalarField
    alpha_eff: outram_foam_basic_lib.VolScalarField
    cp: outram_foam_basic_lib.VolScalarField
    wall_htc: outram_foam_basic_lib.VolScalarField
    wall_area: outram_foam_basic_lib.VolScalarField
    wall_temperature: outram_foam_basic_lib.VolScalarField
    body_force: outram_foam_basic_lib.Vector3
    solve_pressure: bool
    p_ref_cell: int
    p_ref_value: float
    n_outer: int
    n_inner: int
    def __init__(self, mesh: outram_foam_basic_lib.FvMesh, fluid: Fluid, drag: PorousDrag) -> None: ...
    def mesh(self) -> outram_foam_basic_lib.FvMesh: ...
    def temperature(self) -> outram_foam_basic_lib.VolScalarField: ...
    def step(self, dt: float) -> None: ...
    def correct_fluid_mechanics(self, dt: float) -> None: ...
    def correct_energy(self, dt: float) -> None: ...

class PorousDrag:
    friction: FsWallFriction
    min_mag_u: float
    min_reynolds: float
    def __init__(self, friction: FsWallFriction) -> None: ...
    def with_min_mag_u(self, min_mag_u: float) -> PorousDrag: ...
    def assemble_kd(self, fluid: Fluid) -> outram_foam_basic_lib.VolScalarField: ...

class ThermalHydraulicsSolver:
    def step(self, dt: float) -> None: ...
    def variant(self) -> str: ...

class FieldReduction:
    @staticmethod
    def Max() -> FieldReduction: ...
    @staticmethod
    def Min() -> FieldReduction: ...
    def variant(self) -> str: ...

class FixedPower:
    def __init__(self, alpha: float, interfacial_area: float, power_density_initial: float, alpha_rho_cp: float, initial_temperature: float) -> None: ...
    def with_power_profile(self, profile: TimeProfile) -> FixedPower: ...
    def power_density(self, t: float) -> float: ...
    def surface_temperature(self) -> float: ...
    def interfacial_area(self) -> float: ...
    def correct(self, h_sum: float, ht_sum: float, dt: float, t: float) -> float: ...
    def power_off(self) -> None: ...

class FixedTemperature:
    def __init__(self, interfacial_area: float, temperature_initial: float) -> None: ...
    def with_temperature_profile(self, profile: TimeProfile) -> FixedTemperature: ...
    def surface_temperature_at(self, t: float) -> float: ...
    def interfacial_area(self) -> float: ...

class PassiveStructure:
    def __init__(self, interfacial_area: float, alpha_rho_cp: float, initial_temperature: float) -> None: ...
    def surface_temperature(self) -> float: ...
    def interfacial_area(self) -> float: ...
    def correct(self, h_sum: float, ht_sum: float, dt: float) -> float: ...

class PowerOffCriterion:
    @staticmethod
    def timer(trigger_time: float) -> PowerOffCriterion: ...
    @staticmethod
    def field_value(reduction: FieldReduction, direction: ThresholdDirection, threshold: float) -> PowerOffCriterion: ...
    def with_time_delay(self, delay: float) -> PowerOffCriterion: ...
    def check(self, t: float, field_extremum: float) -> bool: ...
    @staticmethod
    def Timer(trigger_time: float) -> PowerOffCriterion: ...
    @staticmethod
    def FieldValue(reduction: FieldReduction, direction: ThresholdDirection, threshold: float, time_delay: float, first_crossing: float | None) -> PowerOffCriterion: ...
    def variant(self) -> str: ...

class Pump:
    def __init__(self, base_source: outram_foam_basic_lib.Vector3) -> None: ...
    def with_time_profile(self, profile: TimeProfile) -> Pump: ...
    def time_dependent(self) -> bool: ...
    def momentum_source(self, t: float) -> outram_foam_basic_lib.Vector3: ...

class StructureCell:
    power_model: PowerModel
    passive: PassiveStructure | None
    pump: Pump | None
    power_off: PowerOffCriterion | None
    def __init__(self, power_model: PowerModel) -> None: ...
    def with_passive(self, passive: PassiveStructure) -> StructureCell: ...
    def with_pump(self, pump: Pump) -> StructureCell: ...
    def with_power_off(self, criterion: PowerOffCriterion) -> StructureCell: ...
    def momentum_source(self, t: float) -> outram_foam_basic_lib.Vector3: ...
    def correct(self, h_sum: float, ht_sum: float, dt: float, t: float, scram_field_extremum: float) -> StructureThermalState: ...

class StructureThermalState:
    active_surface_temperature: float
    passive_surface_temperature: float | None
    wall_temperature: float
    heat_source_to_fluid: float
    wall_heat_flux: float
    powered_off: bool
    def __init__(self, active_surface_temperature: float, passive_surface_temperature: float | None, wall_temperature: float, heat_source_to_fluid: float, wall_heat_flux: float, powered_off: bool) -> None: ...

class ThresholdDirection:
    @staticmethod
    def Above() -> ThresholdDirection: ...
    @staticmethod
    def Below() -> ThresholdDirection: ...
    def variant(self) -> str: ...

class BespokeFluidPropertyModel:
    def density(self, p: float, t: float) -> float: ...
    def specific_heat_capacity(self, p: float, t: float) -> float: ...
    def specific_heat_capacity_cv(self, p: float, t: float) -> float: ...
    def dynamic_viscosity(self, p: float, t: float) -> float: ...
    def thermal_conductivity(self, p: float, t: float) -> float: ...
    def specific_enthalpy(self, p: float, t: float) -> float: ...
    def specific_entropy(self, p: float, t: float) -> float: ...
    def prandtl_number(self, p: float, t: float) -> float: ...
    def dissociated_mole_fraction(self, p: float, t: float) -> float: ...
    def dissociated_mass_fraction(self, p: float, t: float) -> float: ...
    def second_virial_coefficient(self, p: float, t: float) -> float: ...
    def kappa_over_cp(self, p: float, t: float) -> float: ...
    @staticmethod
    def Hydrogen() -> BespokeFluidPropertyModel: ...
    def variant(self) -> str: ...
    @staticmethod
    def default() -> BespokeFluidPropertyModel: ...

class DisplacementReport:
    n_correctors: int
    final_change: float
    converged: bool
    max_displacement: float
    def __init__(self, n_correctors: int, final_change: float, converged: bool, max_displacement: float) -> None: ...

class ElasticMaterial:
    def __init__(self, youngs_modulus: float, poisson_ratio: float, thermal_expansion: float, density: float, specific_heat: float, conductivity: float) -> None: ...
    def youngs_modulus(self) -> float: ...
    def poisson_ratio(self) -> float: ...
    def thermal_expansion(self) -> float: ...
    def density(self) -> float: ...
    def specific_heat(self) -> float: ...
    def conductivity(self) -> float: ...
    def shear_modulus(self) -> float: ...
    def lame_lambda(self, rheology: RheologyOption) -> float: ...
    def bulk_modulus_three_k(self, rheology: RheologyOption) -> float: ...
    def thermal_diffusivity(self) -> float: ...

class MaterialError:
    @staticmethod
    def NonPositiveYoungsModulus(a0: float) -> MaterialError: ...
    @staticmethod
    def NonPositiveDensity(a0: float) -> MaterialError: ...
    @staticmethod
    def NonPositiveSpecificHeat(a0: float) -> MaterialError: ...
    @staticmethod
    def PoissonRatioOutOfRange(a0: float) -> MaterialError: ...
    def variant(self) -> str: ...

class RheologyOption:
    @staticmethod
    def PlaneStrain() -> RheologyOption: ...
    @staticmethod
    def PlaneStress() -> RheologyOption: ...
    def variant(self) -> str: ...
    @staticmethod
    def default() -> RheologyOption: ...

class ThermoMechanicsModel:
    def stress(self, strain: outram_foam_basic_lib.SymmTensor, delta_t: float) -> outram_foam_basic_lib.SymmTensor: ...
    def von_mises(self, strain: outram_foam_basic_lib.SymmTensor, delta_t: float) -> float: ...
    @staticmethod
    def Legacy(a0: LegacyThermoMechanics) -> ThermoMechanicsModel: ...
    def variant(self) -> str: ...

class InterpolationScheme:
    @staticmethod
    def Linear() -> InterpolationScheme: ...
    @staticmethod
    def Upwind(a0: str) -> InterpolationScheme: ...
    @staticmethod
    def Harmonic() -> InterpolationScheme: ...
    def variant(self) -> str: ...

class ControlDict:
    application: str
    start: StartControl
    stop: StopControl
    delta_t: float
    write_control: WriteControl
    write_interval: float
    purge_write: int
    write_format: WriteFormat
    write_precision: int
    run_time_modifiable: bool
    adjust_time_step: bool
    max_co: float
    max_delta_t: float
    @staticmethod
    def read(path: str) -> ControlDict: ...
    def __init__(self, application: str | None = None, start: StartControl | None = None, stop: StopControl | None = None, delta_t: float | None = None, write_control: WriteControl | None = None, write_interval: float | None = None, purge_write: int | None = None, write_format: WriteFormat | None = None, write_precision: int | None = None, run_time_modifiable: bool | None = None, adjust_time_step: bool | None = None, max_co: float | None = None, max_delta_t: float | None = None) -> None: ...
    @staticmethod
    def default() -> ControlDict: ...

class CrossSectionData:
    @staticmethod
    def from_input(input: NuclearDataInput) -> CrossSectionData: ...
    def transform_parameters(self, raw_parameters: list[float]) -> list[float]: ...
    def energy_groups(self) -> int: ...
    def prec_groups(self) -> int: ...
    def legendre_moments(self) -> int: ...
    def fast_neutrons(self) -> bool: ...
    def variable_names(self) -> list[str]: ...
    def variables(self) -> list[XsVariable]: ...
    def zone_count(self) -> int: ...
    def zone_index(self, name: str) -> int | None: ...
    def zone(self, index: int) -> ZoneNuclearData | None: ...
    def evaluate_group_constants(self, zone: int, group: int, raw_parameters: list[float]) -> GroupConstants: ...
    def reference_group_constants(self, zone: int, group: int) -> GroupConstants: ...
    def scattering_matrix(self, zone: int, moment: int, raw_parameters: list[float]) -> outram_foam_basic_lib.SquareMatrix: ...
    def precursor_constants(self, zone: int) -> PrecursorConstants: ...

class DdtScheme:
    @staticmethod
    def Euler() -> DdtScheme: ...
    @staticmethod
    def Backward() -> DdtScheme: ...
    @staticmethod
    def CrankNicolson(a0: float) -> DdtScheme: ...
    @staticmethod
    def LocalEuler() -> DdtScheme: ...
    @staticmethod
    def SteadyState() -> DdtScheme: ...
    def variant(self) -> str: ...

class DiffusionNeutronics:
    def state(self) -> NeutronicsState: ...
    def xs_fields(self) -> DiffusionXsFields: ...
    def settings(self) -> DiffusionSettings: ...
    def energy_groups(self) -> int: ...
    def prec_groups(self) -> int: ...
    def solve_eigenvalue(self) -> EigenvalueReport: ...
    def step(self, dt: float) -> None: ...

class DivScheme:
    @staticmethod
    def GaussLinear() -> DivScheme: ...
    @staticmethod
    def GaussUpwind() -> DivScheme: ...
    @staticmethod
    def GaussLinearUpwind(a0: str) -> DivScheme: ...
    @staticmethod
    def GaussVanLeer() -> DivScheme: ...
    @staticmethod
    def GaussMUSCL() -> DivScheme: ...
    @staticmethod
    def GaussLimitedLinear(a0: float) -> DivScheme: ...
    def variant(self) -> str: ...

class Fluid:
    def __init__(self, mesh: outram_foam_basic_lib.FvMesh, name: str, state_of_matter: StateOfMatter) -> None: ...
    def name(self) -> str: ...
    def mesh(self) -> outram_foam_basic_lib.FvMesh: ...
    def base(self) -> PhaseBase: ...
    def alpha(self) -> outram_foam_basic_lib.VolScalarField: ...
    def state_of_matter(self) -> StateOfMatter: ...
    def is_liquid(self) -> bool: ...
    def is_gas(self) -> bool: ...
    def velocity(self) -> outram_foam_basic_lib.VolVectorField: ...
    def mag_velocity(self) -> outram_foam_basic_lib.VolScalarField: ...
    def phi(self) -> outram_foam_basic_lib.SurfaceScalarField: ...
    def alpha_phi(self) -> outram_foam_basic_lib.SurfaceScalarField: ...
    def alpha_rho_phi(self) -> outram_foam_basic_lib.SurfaceScalarField: ...
    def alpha_rho_mag_u(self) -> outram_foam_basic_lib.VolScalarField: ...
    def dgdt(self) -> outram_foam_basic_lib.VolScalarField: ...
    def normalized(self) -> outram_foam_basic_lib.VolScalarField: ...
    def density(self) -> outram_foam_basic_lib.VolScalarField: ...
    def temperature(self) -> outram_foam_basic_lib.VolScalarField: ...
    def enthalpy(self) -> outram_foam_basic_lib.VolScalarField: ...
    def kappa(self) -> outram_foam_basic_lib.VolScalarField: ...
    def cp(self) -> outram_foam_basic_lib.VolScalarField: ...
    def mu(self) -> outram_foam_basic_lib.VolScalarField: ...
    def prandtl(self) -> outram_foam_basic_lib.VolScalarField: ...
    def hydraulic_diameter(self) -> outram_foam_basic_lib.VolScalarField: ...
    def flow_quality(self) -> outram_foam_basic_lib.VolScalarField: ...
    def lockhart_martinelli(self) -> outram_foam_basic_lib.VolScalarField: ...
    def dispersion(self) -> outram_foam_basic_lib.VolScalarField: ...
    def power_density(self) -> outram_foam_basic_lib.VolScalarField: ...
    def continuity_error(self) -> outram_foam_basic_lib.VolScalarField: ...
    def above_thermo_residual_alpha(self) -> outram_foam_basic_lib.VolScalarField: ...
    def below_thermo_residual_alpha(self) -> outram_foam_basic_lib.VolScalarField: ...
    def reference_density(self) -> outram_foam_basic_lib.VolScalarField: ...
    def min_xlm(self) -> float: ...
    def max_xlm(self) -> float: ...
    def thermo_residual_alpha(self) -> float: ...
    def set_thermo_residual_alpha(self, value: float) -> None: ...
    def is_boussinesq(self) -> bool: ...
    def set_boussinesq(self, value: bool) -> None: ...
    def rho(self, variable_if_boussinesq: bool) -> outram_foam_basic_lib.VolScalarField: ...
    def cumulative_continuity_error(self) -> float: ...
    def set_cumulative_continuity_error(self, value: float) -> None: ...
    def correct_mag_velocity(self) -> None: ...
    def correct_alpha_rho_mag_u(self) -> None: ...
    def correct_thermo_residual_markers(self) -> None: ...
    def nu(self) -> outram_foam_basic_lib.VolScalarField: ...

class FvSchemes:
    ddt: DdtScheme
    default_grad: GradScheme
    default_div: DivScheme
    default_laplacian: LaplacianScheme
    default_sn_grad: SnGradScheme
    default_interpolation: InterpolationScheme
    @staticmethod
    def read(path: str) -> FvSchemes: ...
    def __init__(self, ddt: DdtScheme | None = None, default_grad: GradScheme | None = None, default_div: DivScheme | None = None, default_laplacian: LaplacianScheme | None = None, default_sn_grad: SnGradScheme | None = None, default_interpolation: InterpolationScheme | None = None) -> None: ...
    @staticmethod
    def default() -> FvSchemes: ...

class FvSolution:
    pimple: PimpleControl
    @staticmethod
    def read(path: str) -> FvSolution: ...
    def __init__(self) -> None: ...
    @staticmethod
    def default() -> FvSolution: ...

class GradScheme:
    @staticmethod
    def GaussLinear() -> GradScheme: ...
    @staticmethod
    def LeastSquares() -> GradScheme: ...
    @staticmethod
    def FourthOrder() -> GradScheme: ...
    def variant(self) -> str: ...

class HeatExchanger:
    def __init__(self, wall_conductance: float) -> None: ...
    def wall_conductance(self) -> float: ...
    def wall_temperature(self, h_sum_primary: float, ht_sum_primary: float, h_sum_secondary: float, ht_sum_secondary: float) -> float: ...

class HrmFoam:
    mesh: outram_foam_basic_lib.FvMesh
    control: ControlDict
    schemes: FvSchemes
    solution: FvSolution
    u: outram_foam_basic_lib.VolVectorField
    p: outram_foam_basic_lib.VolScalarField
    rho: outram_foam_basic_lib.VolScalarField
    h: outram_foam_basic_lib.VolScalarField
    x: outram_foam_basic_lib.VolScalarField
    y: outram_foam_basic_lib.VolScalarField
    x_eq: outram_foam_basic_lib.VolScalarField
    mu: outram_foam_basic_lib.VolScalarField
    alpha_h: outram_foam_basic_lib.VolScalarField
    gas_diffusivity: outram_foam_basic_lib.VolScalarField
    p_sat: outram_foam_basic_lib.VolScalarField
    phi: outram_foam_basic_lib.SurfaceScalarField
    model: HrmModelConfig
    def step(self) -> None: ...
    def run(self) -> None: ...
    def __init__(self, mesh: outram_foam_basic_lib.FvMesh, control: ControlDict, schemes: FvSchemes, solution: FvSolution) -> None: ...
    @staticmethod
    def with_model_config(mesh: outram_foam_basic_lib.FvMesh, control: ControlDict, schemes: FvSchemes, solution: FvSolution, model: HrmModelConfig) -> HrmFoam: ...
    @staticmethod
    def relaxation_time(psi: float, x: float) -> float: ...
    def relaxation_time_with_config(self, psi: float, x: float) -> float: ...

class HrmModelConfig:
    theta_0: float
    pressure_undershoot_exp: float
    liquid_fraction_exp: float
    theta_floor: float
    rho_min: float
    solve_gas_fraction: bool
    adiabatic: bool
    def relaxation_time(self, psi: float, x: float) -> float: ...
    def __init__(self, theta_0: float | None = None, pressure_undershoot_exp: float | None = None, liquid_fraction_exp: float | None = None, theta_floor: float | None = None, rho_min: float | None = None, solve_gas_fraction: bool | None = None, adiabatic: bool | None = None) -> None: ...
    @staticmethod
    def default() -> HrmModelConfig: ...

class InterfacialHeatTransfer:
    def nusselt(self, re: float, pr: float) -> float: ...
    @staticmethod
    def Spherical() -> InterfacialHeatTransfer: ...
    @staticmethod
    def RanzMarshall() -> InterfacialHeatTransfer: ...
    @staticmethod
    def ConstantNu(a0: float) -> InterfacialHeatTransfer: ...
    def variant(self) -> str: ...

class InterfacialMassTransfer:
    @staticmethod
    def None_() -> InterfacialMassTransfer: ...
    @staticmethod
    def ConstantRate(a0: float) -> InterfacialMassTransfer: ...
    def variant(self) -> str: ...

class LaplacianScheme:
    @staticmethod
    def GaussLinearCorrected() -> LaplacianScheme: ...
    @staticmethod
    def GaussLinearUncorrected() -> LaplacianScheme: ...
    @staticmethod
    def GaussLinearLimited(a0: float) -> LaplacianScheme: ...
    def variant(self) -> str: ...

class LegacyThermoMechanics:
    def __init__(self, material: ElasticMaterial, rheology: RheologyOption) -> None: ...
    def material(self) -> ElasticMaterial: ...
    def rheology(self) -> RheologyOption: ...
    def stress(self, strain: outram_foam_basic_lib.SymmTensor, delta_t: float) -> outram_foam_basic_lib.SymmTensor: ...
    def von_mises(self, strain: outram_foam_basic_lib.SymmTensor, delta_t: float) -> float: ...
    def free_axial_expansion(self, delta_t: float, length: float) -> float: ...
    def axial_expansion_profile(self, delta_t: list[float], cell_height: list[float]) -> list[float]: ...
    def mesh_displacement(self, disp: outram_foam_basic_lib.Vector3, axial: float, pin_direction: outram_foam_basic_lib.Vector3) -> outram_foam_basic_lib.Vector3: ...

class LinearSolverConfig:
    solver: LinearSolverType
    preconditioner: str | None
    tolerance: float
    rel_tol: float
    max_iter: int
    smoother: str | None
    n_sweep: int
    def __init__(self, solver: LinearSolverType | None = None, preconditioner: str | None = None, tolerance: float | None = None, rel_tol: float | None = None, max_iter: int | None = None, smoother: str | None = None, n_sweep: int | None = None) -> None: ...
    @staticmethod
    def default() -> LinearSolverConfig: ...

class LinearSolverType:
    @staticmethod
    def Pcg() -> LinearSolverType: ...
    @staticmethod
    def PbicgStab() -> LinearSolverType: ...
    @staticmethod
    def Gamg() -> LinearSolverType: ...
    @staticmethod
    def GaussSeidel() -> LinearSolverType: ...
    @staticmethod
    def Diagonal() -> LinearSolverType: ...
    @staticmethod
    def SmoothSolver() -> LinearSolverType: ...
    def variant(self) -> str: ...

class MechanicsMeshSolver:
    def __init__(self, model: LegacyThermoMechanics, t_struct_ref: float, dt: float, settings: outram_foam_basic_lib.SolverSettings, disp: outram_foam_basic_lib.VolVectorField, t_struct: outram_foam_basic_lib.VolScalarField) -> None: ...
    def set_corrector_control(self, n_correctors: int, tol: float) -> None: ...
    def displacement(self) -> outram_foam_basic_lib.VolVectorField: ...
    def temperature(self) -> outram_foam_basic_lib.VolScalarField: ...
    def stress(self) -> outram_foam_basic_lib.VolSymmTensorField: ...
    def solve_displacement(self, quasi_static: bool) -> DisplacementReport: ...
    def advance_time(self) -> None: ...
    def mesh_displacement(self, pin_direction: outram_foam_basic_lib.Vector3, axial: outram_foam_basic_lib.VolScalarField) -> outram_foam_basic_lib.VolVectorField: ...

class MeltFoam:
    mesh: outram_foam_basic_lib.FvMesh
    control: ControlDict
    schemes: FvSchemes
    solution: FvSolution
    u: outram_foam_basic_lib.VolVectorField
    p: outram_foam_basic_lib.VolScalarField
    t: outram_foam_basic_lib.VolScalarField
    phi: outram_foam_basic_lib.SurfaceScalarField
    nu: outram_foam_basic_lib.VolScalarField
    alpha_thermal: outram_foam_basic_lib.VolScalarField
    fv_models: outram_foam_basic_lib.FvModels
    pressure_solver: PressureSolver
    temperature_solver: outram_foam_basic_lib.SolverSettings
    def __init__(self, mesh: outram_foam_basic_lib.FvMesh, control: ControlDict, schemes: FvSchemes, solution: FvSolution) -> None: ...
    @staticmethod
    def boussinesq_coefficients(solidus: float, liquidus: float, latent_heat: float, specific_heat: float, density: float, thermal_expansion: float, darcy_coefficient_force: float) -> outram_foam_basic_lib.SolidificationMeltingCoefficients: ...
    def step(self) -> None: ...
    def run(self) -> None: ...
    def liquid_fraction(self) -> list[float] | None: ...

class MeshHandler:
    def __init__(self, ) -> None: ...
    def add_region(self, region: CouplingRegion) -> None: ...
    def region(self, name: str) -> CouplingRegion | None: ...
    def add_mapping(self, target: str, source: str, method: MappingMethod, fields: list[CouplingField]) -> None: ...
    def interpolate_coupling_fields(self) -> None: ...
    def scalar_integral(self, region: str, field: str) -> float: ...
    @staticmethod
    def default() -> MeshHandler: ...

class MultiPhysicsSolver:
    def __init__(self, handler: MeshHandler, models: list[RegionModel], min_residual: float, max_iterations: int) -> None: ...
    def handler(self) -> MeshHandler: ...
    def model(self, i: int) -> RegionModel | None: ...
    def residual_history(self) -> list[float]: ...
    def solve(self, dt: float) -> int: ...

class NeutronicsModel:
    def kind(self) -> NeutronicsModelKind: ...
    def power(self) -> float: ...
    def k_eff(self) -> float | None: ...
    @staticmethod
    def PointKinetics(a0: PointKineticsModel) -> NeutronicsModel: ...
    @staticmethod
    def Diffusion(a0: DiffusionNeutronics) -> NeutronicsModel: ...
    @staticmethod
    def Sp3(a0: Sp3Neutronics) -> NeutronicsModel: ...
    @staticmethod
    def Sn(a0: SnNeutronics) -> NeutronicsModel: ...
    def variant(self) -> str: ...

class NeutronicsState:
    def __init__(self, mesh: outram_foam_basic_lib.FvMesh, energy_groups: int, prec_groups: int) -> None: ...
    def mesh(self) -> outram_foam_basic_lib.FvMesh: ...
    def energy_groups(self) -> int: ...
    def prec_groups(self) -> int: ...
    def flux(self) -> list[outram_foam_basic_lib.VolScalarField]: ...
    def precursors(self) -> list[outram_foam_basic_lib.VolScalarField]: ...
    def power_density(self) -> outram_foam_basic_lib.VolScalarField: ...
    def one_group_flux(self) -> outram_foam_basic_lib.VolScalarField: ...
    def k_eff(self) -> float: ...
    def set_k_eff(self, k_eff: float) -> None: ...
    def k_eff_raw(self) -> float: ...
    def set_k_eff_raw(self, k_eff: float) -> None: ...
    def total_power(self) -> float: ...
    def set_total_power_raw(self, watts: float) -> None: ...
    def total_power_raw(self) -> float: ...

class PhaseSelector:
    @staticmethod
    def Dispersed() -> PhaseSelector: ...
    @staticmethod
    def Continuous() -> PhaseSelector: ...
    def variant(self) -> str: ...

class PhaseSpecies:
    phase: PhaseSelector
    names: list[str]
    y: list[outram_foam_basic_lib.VolScalarField]
    y_old: list[outram_foam_basic_lib.VolScalarField]
    diffusivity: float
    def __init__(self, mesh: outram_foam_basic_lib.FvMesh, phase: PhaseSelector, names: list[str], y0: list[float], diffusivity: float) -> None: ...
    def mass_fraction(self, i: int) -> outram_foam_basic_lib.VolScalarField: ...
    def mean_mass_fraction(self, i: int) -> float: ...

class PhaseThermo:
    he: outram_foam_basic_lib.VolScalarField
    he_old: outram_foam_basic_lib.VolScalarField
    cp: float
    kappa: float
    def __init__(self, mesh: outram_foam_basic_lib.FvMesh, name: str, cp: float, kappa: float, t0: float) -> None: ...
    def temperature(self) -> outram_foam_basic_lib.VolScalarField: ...
    def mean_temperature(self) -> float: ...

class PimpleControl:
    n_outer_correctors: int
    n_correctors: int
    n_non_orthogonal_correctors: int
    consistent: bool
    correct_phi: bool
    def __init__(self, n_outer_correctors: int | None = None, n_correctors: int | None = None, n_non_orthogonal_correctors: int | None = None, consistent: bool | None = None, correct_phi: bool | None = None) -> None: ...
    @staticmethod
    def default() -> PimpleControl: ...

class PimpleFoam:
    mesh: outram_foam_basic_lib.FvMesh
    control: ControlDict
    schemes: FvSchemes
    solution: FvSolution
    u: outram_foam_basic_lib.VolVectorField
    p: outram_foam_basic_lib.VolScalarField
    phi: outram_foam_basic_lib.SurfaceScalarField
    nu: outram_foam_basic_lib.VolScalarField
    pressure_solver: PressureSolver
    u_old_old: outram_foam_basic_lib.VolVectorField | None
    def __init__(self, mesh: outram_foam_basic_lib.FvMesh, control: ControlDict, schemes: FvSchemes, solution: FvSolution) -> None: ...
    def step(self) -> None: ...
    def run(self) -> None: ...

class PointKineticsError:
    @staticmethod
    def MismatchedGroups(betas: int, lambdas: int) -> PointKineticsError: ...
    @staticmethod
    def NoDelayedGroups() -> PointKineticsError: ...
    @staticmethod
    def NonPositivePromptGenerationTime(a0: float) -> PointKineticsError: ...
    @staticmethod
    def NonPositiveDecayConstant(group: int, value: float) -> PointKineticsError: ...
    @staticmethod
    def NonPositiveTimeStep(a0: float) -> PointKineticsError: ...
    @staticmethod
    def SingularSystem(col: int) -> PointKineticsError: ...
    def variant(self) -> str: ...

class PointKineticsParameters:
    def __init__(self, delayed_fractions: list[float], decay_constants: list[float], prompt_generation_time: float) -> None: ...
    @staticmethod
    def with_subcritical_index(delayed_fractions: list[float], decay_constants: list[float], prompt_generation_time: float, subcritical_index: float) -> PointKineticsParameters: ...
    def delayed_group_count(self) -> int: ...
    def delayed_fractions(self) -> list[float]: ...
    def decay_constants(self) -> list[float]: ...
    def prompt_generation_time(self) -> float: ...
    def subcritical_index(self) -> float: ...
    def total_delayed_fraction(self) -> float: ...

class PointKineticsState:
    @staticmethod
    def new_equilibrium(params: PointKineticsParameters, fission_power: float) -> PointKineticsState: ...
    def __init__(self, fission_power: float, precursor_powers: list[float]) -> None: ...
    def fission_power(self) -> float: ...
    def precursor_powers(self) -> list[float]: ...
    def external_source_power(self) -> float: ...
    def step(self, params: PointKineticsParameters, dt: float, reactivity: float, external_source_power: float) -> None: ...

class PowerModel:
    def correct(self, h_sum: float, ht_sum: float, dt: float, t: float) -> float: ...
    def surface_temperature(self, t: float) -> float: ...
    def interfacial_area(self) -> float: ...
    def power_off(self) -> None: ...
    @staticmethod
    def FixedPower(a0: FixedPower) -> PowerModel: ...
    @staticmethod
    def FixedTemperature(a0: FixedTemperature) -> PowerModel: ...
    def variant(self) -> str: ...

class PressureSolver:
    @staticmethod
    def Pcg() -> PressureSolver: ...
    @staticmethod
    def Gamg() -> PressureSolver: ...
    def variant(self) -> str: ...
    @staticmethod
    def default() -> PressureSolver: ...

class ReactingTwoPhaseEulerFoam:
    heat_transfer: InterfacialHeatTransfer
    mass_transfer: InterfacialMassTransfer
    reaction: ReactionSource
    reaction_mechanism: ReactionMechanism
    latent_heat: float
    residual_alpha: float
    n_energy_correctors: int
    control: ControlDict
    schemes: FvSchemes
    solution: FvSolution
    time: float
    def dispersed_temperature(self) -> outram_foam_basic_lib.VolScalarField: ...
    def continuous_temperature(self) -> outram_foam_basic_lib.VolScalarField: ...
    def solve_timestep(self, dt: float) -> None: ...
    def thermophysical_predictor(self, dt: float) -> None: ...
    def composition_predictor(self, dt: float) -> None: ...
    def apply_mass_transfer(self, dt: float) -> None: ...
    def run(self) -> None: ...

class ReactionMechanism:
    @staticmethod
    def None_() -> ReactionMechanism: ...
    @staticmethod
    def Arrhenius(fuel: int, product: int, a_pre: float, e_act: float, delta_h: float) -> ReactionMechanism: ...
    def variant(self) -> str: ...

class ReactionSource:
    @staticmethod
    def None_() -> ReactionSource: ...
    @staticmethod
    def VolumetricHeat(phase: PhaseSelector, q: float) -> ReactionSource: ...
    def variant(self) -> str: ...

class RhoCentralFoam:
    mesh: outram_foam_basic_lib.FvMesh
    control: ControlDict
    schemes: FvSchemes
    solution: FvSolution
    u: outram_foam_basic_lib.VolVectorField
    p: outram_foam_basic_lib.VolScalarField
    rho: outram_foam_basic_lib.VolScalarField
    e: outram_foam_basic_lib.VolScalarField
    psi_limit: float
    phi: outram_foam_basic_lib.SurfaceScalarField
    def __init__(self, mesh: outram_foam_basic_lib.FvMesh, control: ControlDict, schemes: FvSchemes, solution: FvSolution) -> None: ...
    def step(self) -> None: ...
    def run(self) -> None: ...

class RhoPimpleFoam:
    mesh: outram_foam_basic_lib.FvMesh
    control: ControlDict
    schemes: FvSchemes
    solution: FvSolution
    u: outram_foam_basic_lib.VolVectorField
    p: outram_foam_basic_lib.VolScalarField
    rho: outram_foam_basic_lib.VolScalarField
    t: outram_foam_basic_lib.VolScalarField
    he: outram_foam_basic_lib.VolScalarField
    mu: outram_foam_basic_lib.VolScalarField
    alpha_h: outram_foam_basic_lib.VolScalarField
    psi: outram_foam_basic_lib.VolScalarField
    phi: outram_foam_basic_lib.SurfaceScalarField
    def __init__(self, mesh: outram_foam_basic_lib.FvMesh, control: ControlDict, schemes: FvSchemes, solution: FvSolution) -> None: ...
    def step(self) -> None: ...
    def run(self) -> None: ...

class SnGradScheme:
    @staticmethod
    def Corrected() -> SnGradScheme: ...
    @staticmethod
    def Uncorrected() -> SnGradScheme: ...
    @staticmethod
    def Limited(a0: float) -> SnGradScheme: ...
    def variant(self) -> str: ...

class SonicFoam:
    mesh: outram_foam_basic_lib.FvMesh
    control: ControlDict
    schemes: FvSchemes
    solution: FvSolution
    u: outram_foam_basic_lib.VolVectorField
    p: outram_foam_basic_lib.VolScalarField
    rho: outram_foam_basic_lib.VolScalarField
    e: outram_foam_basic_lib.VolScalarField
    psi: outram_foam_basic_lib.VolScalarField
    mu: outram_foam_basic_lib.VolScalarField
    phi: outram_foam_basic_lib.SurfaceScalarField
    def __init__(self, mesh: outram_foam_basic_lib.FvMesh, control: ControlDict, schemes: FvSchemes, solution: FvSolution) -> None: ...
    def step(self) -> None: ...
    def run(self) -> None: ...

class StartControl:
    @staticmethod
    def StartTime(a0: float) -> StartControl: ...
    @staticmethod
    def LatestTime() -> StartControl: ...
    @staticmethod
    def FirstTime() -> StartControl: ...
    def variant(self) -> str: ...

class StateOfMatter:
    def is_liquid(self) -> bool: ...
    def is_gas(self) -> bool: ...
    def name(self) -> str: ...
    @staticmethod
    def Undetermined() -> StateOfMatter: ...
    @staticmethod
    def Liquid() -> StateOfMatter: ...
    @staticmethod
    def Gas() -> StateOfMatter: ...
    def variant(self) -> str: ...
    @staticmethod
    def default() -> StateOfMatter: ...

class StopControl:
    @staticmethod
    def EndTime(a0: float) -> StopControl: ...
    @staticmethod
    def WriteNow() -> StopControl: ...
    @staticmethod
    def NoWriteNow() -> StopControl: ...
    @staticmethod
    def NextWrite() -> StopControl: ...
    def variant(self) -> str: ...

class TurbulenceClosure:
    @staticmethod
    def k_omega_sst(mesh: outram_foam_basic_lib.FvMesh) -> TurbulenceClosure: ...
    @staticmethod
    def k_epsilon(mesh: outram_foam_basic_lib.FvMesh) -> TurbulenceClosure: ...
    @staticmethod
    def k_omega(mesh: outram_foam_basic_lib.FvMesh) -> TurbulenceClosure: ...
    @staticmethod
    def spalart_allmaras(mesh: outram_foam_basic_lib.FvMesh) -> TurbulenceClosure: ...
    @staticmethod
    def smagorinsky(mesh: outram_foam_basic_lib.FvMesh) -> TurbulenceClosure: ...
    def name(self) -> str: ...
    def is_laminar(self) -> bool: ...
    def sync_inputs(self, u: outram_foam_basic_lib.VolVectorField, phi: outram_foam_basic_lib.SurfaceScalarField, nu: outram_foam_basic_lib.VolScalarField, dt: float) -> None: ...
    def correct(self) -> None: ...
    def div_dev_reff(self, u: outram_foam_basic_lib.VolVectorField, nu: outram_foam_basic_lib.VolScalarField) -> outram_foam_basic_lib.FvVectorMatrix: ...
    def nu_t(self) -> outram_foam_basic_lib.VolScalarField | None: ...
    def nu_eff(self, nu: outram_foam_basic_lib.VolScalarField) -> outram_foam_basic_lib.VolScalarField: ...
    def mu_eff(self, mu: outram_foam_basic_lib.VolScalarField, rho: outram_foam_basic_lib.VolScalarField) -> outram_foam_basic_lib.VolScalarField: ...
    def alpha_eff_compressible(self, alpha: outram_foam_basic_lib.VolScalarField, rho: outram_foam_basic_lib.VolScalarField) -> outram_foam_basic_lib.VolScalarField: ...
    def turbulent_prandtl(self) -> float: ...
    def set_k_omega_uniform(self, k: float, scale: float) -> bool: ...
    @staticmethod
    def volumetric_flux(mass_flux: outram_foam_basic_lib.SurfaceScalarField, rho: outram_foam_basic_lib.VolScalarField) -> outram_foam_basic_lib.SurfaceScalarField: ...
    @staticmethod
    def Laminar() -> TurbulenceClosure: ...
    def variant(self) -> str: ...
    @staticmethod
    def default() -> TurbulenceClosure: ...

class WriteControl:
    @staticmethod
    def TimeStep(a0: int) -> WriteControl: ...
    @staticmethod
    def RunTime(a0: float) -> WriteControl: ...
    @staticmethod
    def AdjustableRunTime(a0: float) -> WriteControl: ...
    @staticmethod
    def CpuTime(a0: float) -> WriteControl: ...
    @staticmethod
    def ClockTime(a0: float) -> WriteControl: ...
    def variant(self) -> str: ...

class WriteFormat:
    @staticmethod
    def Ascii() -> WriteFormat: ...
    @staticmethod
    def Binary() -> WriteFormat: ...
    def variant(self) -> str: ...

def control_from_case(case_: outram_foam_basic_lib.FoamCase) -> ControlDict: ...
def find_scalar(case_: outram_foam_basic_lib.FoamCase, name: str) -> outram_foam_basic_lib.VolScalarField | None: ...
def find_vector(case_: outram_foam_basic_lib.FoamCase, name: str) -> outram_foam_basic_lib.VolVectorField | None: ...
def format_time(t: float) -> str: ...
def run_case(case_dir: str, kind: SolverKind) -> CaseSummary: ...
def time_span(ctrl: ControlDict) -> tuple[float, float, float]: ...
def polyharmonic_spline(weights: list[float], x_list: list[list[float]], x_input: list[float], mode: int) -> float: ...
def polyharmonic_spline_function(r_square: float, mode: int) -> float: ...
def solve_polyharmonic_spline(x_list: list[list[float]], v_list: list[float], mode: int) -> list[float]: ...
def lumped_cell_mesh(volume: float) -> outram_foam_basic_lib.FvMesh: ...
def diffusion_coefficient(metres: float) -> float: ...
def dimensionless(ratio: float) -> float: ...
def macroscopic_cross_section(per_metre: float) -> float: ...
def precursor_decay_constant(per_second: float) -> float: ...
def multi_regime_boiling_htc(inputs: MultiRegimeBoilingInputs) -> MultiRegimeBoilingResult: ...
def superposition_nucleate_boiling_htc(htc_forced_convection: float, flow_enhancement_factor: float, htc_pool_boiling: float, suppression_factor: float) -> float: ...
def contact_angle_from_degrees(degrees: float) -> float: ...
def two_phase_mixture_reynolds_number(alpha_1: float, rho_1: float, u_1: float, mu_1: float, alpha_2: float, rho_2: float, u_2: float, mu_2: float, hydraulic_diameter: float) -> float: ...
def fluid_diameter(value_m: float) -> float: ...
def interfacial_area_concentration(value_per_metre: float) -> float: ...
def cell_mask(field: outram_foam_basic_lib.VolScalarField, mask_field: outram_foam_basic_lib.VolScalarField) -> list[bool]: ...
def internal_extents(mesh: outram_foam_basic_lib.FvMesh, mask: list[bool], reference_position: outram_foam_basic_lib.Vector3) -> Extents: ...
def patch_extents(mesh: outram_foam_basic_lib.FvMesh, patch_index: int, mask: list[bool], reference_position: outram_foam_basic_lib.Vector3) -> Extents: ...
def patch_mask(field: outram_foam_basic_lib.VolScalarField, mask_field: outram_foam_basic_lib.VolScalarField, patch_index: int) -> list[bool]: ...
def volume_integral(mesh: outram_foam_basic_lib.FvMesh, field: outram_foam_basic_lib.VolScalarField) -> float: ...
def volume_integral_over_cells(mesh: outram_foam_basic_lib.FvMesh, field: outram_foam_basic_lib.VolScalarField, cells: list[int]) -> float: ...
def region_area(mesh: outram_foam_basic_lib.FvMesh, region: MassFlowRegion) -> float: ...
def total_mass_flow(alpha_rho_phi: outram_foam_basic_lib.SurfaceScalarField, region: MassFlowRegion) -> float: ...
def patch_field_values(field: outram_foam_basic_lib.VolScalarField, patch_index: int) -> list[float]: ...
def reduce_patch_scalar_field(mesh: outram_foam_basic_lib.FvMesh, field: outram_foam_basic_lib.VolScalarField, patch_index: int, op: PatchReduceOp) -> float: ...
def patch_average_pressure(mesh: outram_foam_basic_lib.FvMesh, p: outram_foam_basic_lib.VolScalarField, patch_index: int) -> float: ...
def pressure_drop(mesh: outram_foam_basic_lib.FvMesh, p: outram_foam_basic_lib.VolScalarField, upstream_patch: int, downstream_patch: int) -> float: ...
def pressure_drop_vs_reference(mesh: outram_foam_basic_lib.FvMesh, p: outram_foam_basic_lib.VolScalarField, patch_index: int, p_reference: float) -> float: ...
def evaluate_stop_if_max_field_diff(field1: outram_foam_basic_lib.VolScalarField, field2: outram_foam_basic_lib.VolScalarField) -> StopDecision: ...
def bulk_temperature(patch_index: int, temperature: outram_foam_basic_lib.VolScalarField, specific_heat: outram_foam_basic_lib.VolScalarField, alpha_rho_phi: outram_foam_basic_lib.SurfaceScalarField) -> float: ...
def ff_relative_velocity_magnitude(u1: outram_foam_basic_lib.VolVectorField, u2: outram_foam_basic_lib.VolVectorField) -> outram_foam_basic_lib.VolScalarField: ...
def ff_reynolds(mag_ur: outram_foam_basic_lib.VolScalarField, dh_dispersed: outram_foam_basic_lib.VolScalarField, nu_continuous: outram_foam_basic_lib.VolScalarField, min_re: float) -> outram_foam_basic_lib.VolScalarField: ...
def fs_reynolds(normalized_alpha: outram_foam_basic_lib.VolScalarField, mag_u: outram_foam_basic_lib.VolScalarField, dh: outram_foam_basic_lib.VolScalarField, nu: outram_foam_basic_lib.VolScalarField, min_re: float) -> outram_foam_basic_lib.VolScalarField: ...
def volume_fraction(value: float) -> float: ...
def explicit_heat_source(interfacial_area: float, h_sum: float, ht_sum: float, t_struct: float) -> float: ...
def hx_wall_temperature(wall_conductance: float, h_sum_primary: float, ht_sum_primary: float, h_sum_secondary: float, ht_sum_secondary: float) -> float: ...
def wall_heat_flux(h_sum: float, ht_sum: float, t_wall: float) -> float: ...
def friction_factor_value(f: float) -> float: ...
def reynolds_number(value: float) -> float: ...
def assemble_mesh_displacement(disp: outram_foam_basic_lib.Vector3, axial: float, pin_direction: outram_foam_basic_lib.Vector3) -> outram_foam_basic_lib.Vector3: ...
def axial_expansion_profile(alpha: float, delta_t: list[float], cell_height: list[float]) -> list[float]: ...
def deviatoric_plus_volumetric_stress(strain: outram_foam_basic_lib.SymmTensor, mu: float, lambda_: float) -> outram_foam_basic_lib.SymmTensor: ...
def free_axial_expansion(alpha: float, delta_t: float, length: float) -> float: ...
def hydrostatic_stress(sigma: outram_foam_basic_lib.SymmTensor) -> float: ...
def thermal_stress(strain: outram_foam_basic_lib.SymmTensor, mu: float, lambda_: float, three_k: float, alpha: float, delta_t: float) -> outram_foam_basic_lib.SymmTensor: ...
def von_mises_stress(sigma: outram_foam_basic_lib.SymmTensor) -> float: ...
def read_vol_scalar_field(path: str, n_cells: int) -> list[float]: ...
def read_vol_scalar_field_full(path: str, mesh: outram_foam_basic_lib.FvMesh) -> outram_foam_basic_lib.VolScalarField: ...
def read_vol_vector_field(path: str, n_cells: int) -> list[outram_foam_basic_lib.Vector3]: ...
def read_vol_vector_field_full(path: str, mesh: outram_foam_basic_lib.FvMesh) -> outram_foam_basic_lib.VolVectorField: ...
def write_vector_field(time_dir: str, field: outram_foam_basic_lib.VolVectorField, dimensions: str) -> None: ...
def parse_boundary(text: str, file: str) -> list[outram_foam_basic_lib.BoundaryPatch]: ...
def parse_faces(text: str, file: str) -> list[list[int]]: ...
def parse_index_list(text: str, file: str) -> list[int]: ...
def parse_points(text: str, file: str) -> list[list[float]]: ...
def read_poly_mesh(poly_mesh_dir: str) -> outram_foam_basic_lib.FvMesh: ...
def write_scalar_field(time_dir: str, field: outram_foam_basic_lib.VolScalarField, dimensions: str) -> None: ...
def div_vec_scheme(scheme: DivScheme, phi: outram_foam_basic_lib.SurfaceScalarField, u: outram_foam_basic_lib.VolVectorField, mesh: outram_foam_basic_lib.FvMesh) -> outram_foam_basic_lib.FvVectorMatrix: ...
DZ_A: float
DZ_B: float
THETA_0: float
