"""Type stubs for `outram_park.outram_foam_multiphase`, generated from the Rust API.

Physical quantities cross this boundary as `float` in SI base units.
"""

class MultiphaseError:
    @staticmethod
    def InvalidInput(a0: str) -> MultiphaseError: ...
    @staticmethod
    def NotImplemented(a0: str) -> MultiphaseError: ...
    @staticmethod
    def Solver(a0: str) -> MultiphaseError: ...
    def variant(self) -> str: ...

class Biasi:
    def __init__(self, ) -> None: ...
    @staticmethod
    def default() -> Biasi: ...

class Bowring:
    def __init__(self, h_fg: float) -> None: ...
    def h_fg(self) -> float: ...

class ChfCorrelation:
    @staticmethod
    def Biasi(a0: Biasi) -> ChfCorrelation: ...
    def variant(self) -> str: ...

class GroeneveldLut:
    def to_csv(self) -> str: ...
    @staticmethod
    def from_csv(text: str) -> GroeneveldLut: ...
    @staticmethod
    def sample() -> GroeneveldLut: ...
    def __init__(self, pressures: list[float], mass_fluxes: list[float], qualities: list[float], chf: list[float], reference_diameter: float) -> None: ...
    def n_nodes(self) -> int: ...
    def reference_diameter(self) -> float: ...
    def lookup(self, pressure_pa: float, mass_flux: float, quality: float) -> float: ...
    def diameter_factor(self, diameter_m: float) -> float: ...

class W3:
    def __init__(self, subcooling: float) -> None: ...
    def subcooling(self) -> float: ...

class DriftFlux:
    mesh: outram_foam_basic_lib.FvMesh
    phi: outram_foam_basic_lib.SurfaceScalarField
    u_m: outram_foam_basic_lib.VolVectorField
    dt: float
    def drift_velocity(self) -> list[outram_foam_basic_lib.Vector3]: ...
    def advance_alpha(self) -> None: ...

class DriftFluxMixture:
    mesh: outram_foam_basic_lib.FvMesh
    def __init__(self, mesh: outram_foam_basic_lib.FvMesh, rho_d: float, rho_c: float, mu_d: float, mu_c: float, alpha0: float) -> None: ...
    def rho_dispersed(self) -> float: ...
    def rho_continuous(self) -> float: ...
    def mu_dispersed(self) -> float: ...
    def mu_continuous(self) -> float: ...
    def alpha(self) -> outram_foam_basic_lib.VolScalarField: ...
    def rho_mixture(self) -> outram_foam_basic_lib.VolScalarField: ...
    def mu_mixture(self) -> outram_foam_basic_lib.VolScalarField: ...

class SlipModel:
    def drift_velocity(self, u_m: outram_foam_basic_lib.VolVectorField, alpha: outram_foam_basic_lib.VolScalarField) -> list[outram_foam_basic_lib.Vector3]: ...
    @staticmethod
    def ZuberFindlay(c0: float, vgj: outram_foam_basic_lib.Vector3) -> SlipModel: ...
    @staticmethod
    def TerminalVelocity(u_t: outram_foam_basic_lib.Vector3, hindrance_exp: float) -> SlipModel: ...
    @staticmethod
    def UserDefined(a0: list[outram_foam_basic_lib.Vector3]) -> SlipModel: ...
    def variant(self) -> str: ...

class DryoutConditions:
    quality: float
    void_fraction: float
    mass_flux: float
    wall_temperature: float
    def __init__(self, quality: float, void_fraction: float, mass_flux: float, wall_temperature: float) -> None: ...

class DryoutIndicator:
    dried_out: bool
    margin: float
    def __init__(self, dried_out: bool, margin: float) -> None: ...

class DryoutOnsetModel:
    @staticmethod
    def CriticalVoidFraction(alpha_crit: float) -> DryoutOnsetModel: ...
    @staticmethod
    def CriticalHeatFlux() -> DryoutOnsetModel: ...
    @staticmethod
    def LiquidFilmDepletion() -> DryoutOnsetModel: ...
    def variant(self) -> str: ...

class PostDryoutConditions:
    mass_flux: float
    quality: float
    hydraulic_diameter: float
    wall_temperature: float
    vapor: VaporProperties
    def __init__(self, mass_flux: float, quality: float, hydraulic_diameter: float, wall_temperature: float, vapor: VaporProperties) -> None: ...

class PostDryoutModel:
    @staticmethod
    def FilmBoilingDougallRohsenow() -> PostDryoutModel: ...
    @staticmethod
    def FilmBoilingMechanistic() -> PostDryoutModel: ...
    @staticmethod
    def TransitionBoiling() -> PostDryoutModel: ...
    @staticmethod
    def ChfRecovery() -> PostDryoutModel: ...
    def variant(self) -> str: ...

class VaporProperties:
    density: float
    liquid_density: float
    dynamic_viscosity: float
    thermal_conductivity: float
    prandtl: float
    def __init__(self, density: float, liquid_density: float, dynamic_viscosity: float, thermal_conductivity: float, prandtl: float) -> None: ...

class InterfacialHeatTransfer:
    def volumetric_coefficient_si(self, alpha_dispersed: float, alpha_continuous: float, kappa_continuous: float, kappa_dispersed: float, diameter: float, reynolds: float, prandtl: float, residual_alpha: float) -> float: ...
    def nusselt(self, alpha_continuous: float, reynolds: float, prandtl: float, residual_alpha: float) -> float: ...
    def resistance_side(self) -> ResistanceSide: ...
    def volumetric_coefficient(self, alpha_dispersed: float, alpha_continuous: float, kappa_continuous: float, kappa_dispersed: float, diameter: float, reynolds: float, prandtl: float, residual_alpha: float) -> float: ...
    @staticmethod
    def RanzMarshall() -> InterfacialHeatTransfer: ...
    @staticmethod
    def Spherical() -> InterfacialHeatTransfer: ...
    @staticmethod
    def Gunn() -> InterfacialHeatTransfer: ...
    def variant(self) -> str: ...

class ResistanceSide:
    @staticmethod
    def Continuous() -> ResistanceSide: ...
    @staticmethod
    def Dispersed() -> ResistanceSide: ...
    def variant(self) -> str: ...

class DriftFluxPimple:
    mesh: outram_foam_basic_lib.FvMesh
    p: outram_foam_basic_lib.VolScalarField
    gravity: outram_foam_basic_lib.Vector3
    n_correctors: int
    n_outer_correctors: int
    p_ref_cell: int
    p_ref_value: float
    solver_settings: outram_foam_basic_lib.SolverSettings
    def solve_timestep(self, dt: float) -> None: ...

class DragModel:
    @staticmethod
    def SchillerNaumann() -> DragModel: ...
    @staticmethod
    def WenYu() -> DragModel: ...
    @staticmethod
    def Constant(k_d: float) -> DragModel: ...
    def variant(self) -> str: ...

class InterfacialForce:
    @staticmethod
    def Lift() -> InterfacialForce: ...
    @staticmethod
    def VirtualMass() -> InterfacialForce: ...
    @staticmethod
    def WallLubrication() -> InterfacialForce: ...
    @staticmethod
    def TurbulentDispersion() -> InterfacialForce: ...
    def variant(self) -> str: ...

class Phase:
    mesh: outram_foam_basic_lib.FvMesh
    def __init__(self, mesh: outram_foam_basic_lib.FvMesh, name: str, rho: float, mu: float, d: float, alpha0: float) -> None: ...
    def name(self) -> str: ...
    def rho(self) -> float: ...
    def mu(self) -> float: ...
    def nu(self) -> float: ...
    def diameter(self) -> float: ...
    def alpha(self) -> outram_foam_basic_lib.VolScalarField: ...
    def u(self) -> outram_foam_basic_lib.VolVectorField: ...

class TwoFluidSystem:
    mesh: outram_foam_basic_lib.FvMesh
    def enforce_alpha_constraint(self) -> None: ...
    def reynolds_number(self) -> outram_foam_basic_lib.VolScalarField: ...
    def advance_dispersed_alpha(self, dt: float) -> None: ...

class TwoFluidPimple:
    mesh: outram_foam_basic_lib.FvMesh
    p: outram_foam_basic_lib.VolScalarField
    phi_d: outram_foam_basic_lib.SurfaceScalarField
    phi_c: outram_foam_basic_lib.SurfaceScalarField
    gravity: outram_foam_basic_lib.Vector3
    n_correctors: int
    n_outer_correctors: int
    p_ref_cell: int
    p_ref_value: float
    solver_settings: outram_foam_basic_lib.SolverSettings
    def solve_timestep(self, dt: float) -> None: ...

class ChfModel:
    def __init__(self) -> None: ...
    @staticmethod
    def default() -> ChfModel: ...

class ChfSubCoolModel:
    def __init__(self) -> None: ...
    @staticmethod
    def default() -> ChfSubCoolModel: ...

class DryoutModel:
    def __init__(self) -> None: ...
    @staticmethod
    def default() -> DryoutModel: ...

class FilmBoilingModel:
    def __init__(self) -> None: ...
    @staticmethod
    def default() -> FilmBoilingModel: ...

class HeatFluxPartition:
    convective: float
    quenching: float
    evaporative: float
    total: float
    nucleation_site_density: float
    departure_diameter: float
    departure_frequency: float
    area_fraction_convective: float
    area_fraction_boiling: float
    def __init__(self, convective: float, quenching: float, evaporative: float, total: float, nucleation_site_density: float, departure_diameter: float, departure_frequency: float, area_fraction_convective: float, area_fraction_boiling: float) -> None: ...

class RpiPartitioning:
    cn: float
    n_ref: float
    delta_t_ref: float
    nucleation_exponent: float
    d_ref: float
    d_max: float
    d_min: float
    subcooling_scale: float
    min_density_difference: float
    bubble_waiting_time_ratio: float
    def nucleation_site_density(self, delta_t_superheat: float) -> float: ...
    def departure_diameter(self, delta_t_subcooling: float) -> float: ...
    def departure_frequency(self, departure_diameter: float, rho_liquid: float, rho_vapour: float, gravity: float) -> float: ...
    def __init__(self, cn: float | None = None, n_ref: float | None = None, delta_t_ref: float | None = None, nucleation_exponent: float | None = None, d_ref: float | None = None, d_max: float | None = None, d_min: float | None = None, subcooling_scale: float | None = None, min_density_difference: float | None = None, bubble_waiting_time_ratio: float | None = None) -> None: ...
    @staticmethod
    def default() -> RpiPartitioning: ...

class WallBoilingConditions:
    t_wall: float
    t_liquid: float
    t_sat: float
    rho_liquid: float
    rho_vapour: float
    cp_liquid: float
    k_liquid: float
    latent_heat: float
    h_convective: float
    gravity: float
    def __init__(self, t_wall: float, t_liquid: float, t_sat: float, rho_liquid: float, rho_vapour: float, cp_liquid: float, k_liquid: float, latent_heat: float, h_convective: float, gravity: float) -> None: ...

class WallBoilingModel:
    def partition(self, conditions: WallBoilingConditions) -> HeatFluxPartition: ...
    @staticmethod
    def NucleateBoiling(a0: RpiPartitioning) -> WallBoilingModel: ...
    @staticmethod
    def Chf(a0: ChfModel) -> WallBoilingModel: ...
    @staticmethod
    def ChfSubCool(a0: ChfSubCoolModel) -> WallBoilingModel: ...
    @staticmethod
    def Dryout(a0: DryoutModel) -> WallBoilingModel: ...
    @staticmethod
    def FilmBoiling(a0: FilmBoilingModel) -> WallBoilingModel: ...
    def variant(self) -> str: ...

RESIDUAL_ALPHA: float
