"""Type stubs for `outram_park.outram_park_fork_cfmesh`, generated from the Rust API.

Physical quantities cross this boundary as `float` in SI base units.
"""

class QualityReport:
    max_non_orthogonality_deg: float
    max_skewness: float
    max_aspect_ratio: float
    min_face_area: float
    min_cell_volume: float
    n_negative_volume_cells: int
    min_face_pyramid_volume: float
    n_negative_pyramid_faces: int
    min_cell_determinant: float
    def is_solvable(self) -> bool: ...
    def __init__(self, max_non_orthogonality_deg: float, max_skewness: float, max_aspect_ratio: float, min_face_area: float, min_cell_volume: float, n_negative_volume_cells: int, min_face_pyramid_volume: float, n_negative_pyramid_faces: int, min_cell_determinant: float) -> None: ...

class Vec3:
    x: float
    y: float
    z: float
    def __init__(self, x: float, y: float, z: float) -> None: ...
    def add(self, other: Vec3) -> Vec3: ...
    def sub(self, other: Vec3) -> Vec3: ...
    def scale(self, s: float) -> Vec3: ...
    def dot(self, other: Vec3) -> float: ...
    def cross(self, other: Vec3) -> Vec3: ...
    def length(self) -> float: ...
    def normalize(self) -> Vec3: ...

class SurfaceRegions:
    names: list[str]
    region_of_tri: list[int]
    @staticmethod
    def single(name: str, n_tris: int) -> SurfaceRegions: ...
    def region_count(self) -> int: ...
    def validate(self, n_tris: int) -> None: ...
    def __init__(self, names: list[str], region_of_tri: list[int]) -> None: ...

class TetDualOptions:
    cell_size: float
    refinement_levels: int
    refinement_band: float
    snap: bool
    delaunay: bool
    max_flips: int
    dual: bool
    dual_min_faces: bool
    smooth_passes: int
    n_layers: int
    first_layer_thickness: float
    expansion: float
    wall_patch: str
    def __init__(self, cell_size: float | None = None, refinement_levels: int | None = None, refinement_band: float | None = None, snap: bool | None = None, delaunay: bool | None = None, max_flips: int | None = None, dual: bool | None = None, dual_min_faces: bool | None = None, smooth_passes: int | None = None, n_layers: int | None = None, first_layer_thickness: float | None = None, expansion: float | None = None, wall_patch: str | None = None) -> None: ...
    @staticmethod
    def default() -> TetDualOptions: ...

class TetDualReport:
    stage_notes: list[str]
    cell_count: int
    total_volume: float
    valid: bool
    max_non_orthogonality_deg: float
    max_skewness: float
    n_negative_volume_cells: int
    def __init__(self, stage_notes: list[str], cell_count: int, total_volume: float, valid: bool, max_non_orthogonality_deg: float, max_skewness: float, n_negative_volume_cells: int) -> None: ...

class BoundaryPatch:
    name: str
    start_face: int
    n_faces: int
    def __init__(self, name: str, start_face: int, n_faces: int) -> None: ...

class VolumeMesh:
    points: list[Vec3]
    faces: list[list[int]]
    owner: list[int]
    neighbour: list[int | None]
    n_cells: int
    patches: list[BoundaryPatch]
    def point_count(self) -> int: ...
    def face_count(self) -> int: ...
    def cell_count(self) -> int: ...
    def n_internal_faces(self) -> int: ...
    def n_boundary_faces(self) -> int: ...
    def face_area_vector(self, f: int) -> Vec3: ...
    def face_centroid(self, f: int) -> Vec3: ...
    def total_volume(self) -> float: ...
    def validate(self) -> None: ...
    def __init__(self, points: list[Vec3], faces: list[list[int]], owner: list[int], neighbour: list[int | None], n_cells: int, patches: list[BoundaryPatch]) -> None: ...

def check_quality(mesh: VolumeMesh) -> QualityReport: ...
def flip_to_delaunay(mesh: VolumeMesh, max_flips: int) -> VolumeMesh: ...
def insphere(a: Vec3, b: Vec3, c: Vec3, d: Vec3, e: Vec3) -> float: ...
def orient3d(a: Vec3, b: Vec3, c: Vec3, d: Vec3) -> float: ...
def polyhedral_dual(mesh: VolumeMesh) -> VolumeMesh: ...
def polyhedral_dual_min_faces(mesh: VolumeMesh) -> VolumeMesh: ...
def add_boundary_layers(mesh: VolumeMesh, patch_name: str, n_layers: int, first_thickness: float, expansion: float) -> VolumeMesh: ...
def add_boundary_layers_adaptive(mesh: VolumeMesh, patch_name: str, n_layers: int, first_thickness: float, expansion: float) -> VolumeMesh: ...
def box_tet_dual(min: Vec3, max: Vec3, opts: TetDualOptions) -> tuple[VolumeMesh, TetDualReport]: ...
def cylinder_tet_dual(base: Vec3, radius: float, height: float, n_seg: int, opts: TetDualOptions) -> tuple[VolumeMesh, TetDualReport]: ...
def sphere_tet_dual(centre: Vec3, radius: float, n_lat: int, n_lon: int, opts: TetDualOptions) -> tuple[VolumeMesh, TetDualReport]: ...
def laplacian_smooth(mesh: VolumeMesh, passes: int) -> VolumeMesh: ...
def tetrahedralize(mesh: VolumeMesh) -> VolumeMesh: ...
def cells_faces(mesh: VolumeMesh) -> list[list[list[int]]]: ...
def from_cell_faces(points: list[Vec3], cells: list[list[list[int]]]) -> VolumeMesh: ...
