"""Type stubs for `outram_park.outram_park_fork_onix`, generated from the Rust API.

Physical quantities cross this boundary as `float` in SI base units.
"""

class BurnupMatrix:
    @staticmethod
    def zeros(n: int) -> BurnupMatrix: ...
    def dim(self) -> int: ...
    def get(self, i: int, j: int) -> float: ...
    def set(self, i: int, j: int, v: float) -> None: ...
    def add(self, i: int, j: int, v: float) -> None: ...
    def as_slice(self) -> list[float]: ...
    def mul_vec(self, x: list[float]) -> list[float]: ...
    def column_sums(self) -> list[float]: ...

class CramError:
    @staticmethod
    def DimensionMismatch(expected: int, got: int) -> CramError: ...
    @staticmethod
    def SingularResolvent(column: int) -> CramError: ...
    def variant(self) -> str: ...

class DecayData:
    lambda_total: float
    branches: list[tuple[DecayMode, float]]
    @staticmethod
    def stable() -> DecayData: ...
    @staticmethod
    def from_half_life(half_life_s: float, branches: list[tuple[DecayMode, float]]) -> DecayData: ...
    @staticmethod
    def single_mode(lambda_: float, mode: DecayMode) -> DecayData: ...
    def __init__(self, lambda_total: float, branches: list[tuple[DecayMode, float]]) -> None: ...

class DecayMode:
    def delta(self) -> tuple[int, int, int]: ...
    def daughter(self, parent: Nuclide) -> Nuclide | None: ...
    @staticmethod
    def BetaMinus() -> DecayMode: ...
    @staticmethod
    def BetaPlus() -> DecayMode: ...
    @staticmethod
    def Alpha() -> DecayMode: ...
    @staticmethod
    def NeutronEmission() -> DecayMode: ...
    @staticmethod
    def ProtonEmission() -> DecayMode: ...
    @staticmethod
    def IsomericTransition() -> DecayMode: ...
    def variant(self) -> str: ...

class DepletionError:
    def variant(self) -> str: ...

class DepletionSystem:
    def __init__(self, ) -> None: ...
    def len(self) -> int: ...
    def is_empty(self) -> bool: ...
    def nuclides(self) -> list[Nuclide]: ...
    def set_reaction_rates(self, nuclide: Nuclide, rates: ReactionRates) -> None: ...
    def build_matrix(self) -> BurnupMatrix: ...
    def inventory_vector(self, densities: list[tuple[Nuclide, float]]) -> list[float]: ...
    def deplete(self, n0: list[float], dt: float) -> list[float]: ...
    def deplete_multi(self, n0: list[float], steps: list[float]) -> list[float]: ...
    @staticmethod
    def default() -> DepletionSystem: ...

class FissionYields:
    products: list[tuple[Nuclide, float]]
    @staticmethod
    def empty() -> FissionYields: ...
    @staticmethod
    def from_percent(products_percent: list[tuple[Nuclide, float]]) -> FissionYields: ...
    def __init__(self, products: list[tuple[Nuclide, float]] | None = None) -> None: ...
    @staticmethod
    def default() -> FissionYields: ...

class Nuclide:
    z: int
    a: int
    m: int
    def __init__(self, z: int, a: int, m: int) -> None: ...
    def neutron_number(self) -> int | None: ...
    def is_physical(self) -> bool: ...
    def apply_delta(self, dz: int, da: int, dm: int) -> Nuclide | None: ...

class ReactionChannel:
    def delta(self) -> tuple[int, int, int] | None: ...
    def is_fission(self) -> bool: ...
    def daughter(self, parent: Nuclide) -> Nuclide | None: ...
    @staticmethod
    def NGamma() -> ReactionChannel: ...
    @staticmethod
    def N2n() -> ReactionChannel: ...
    @staticmethod
    def N3n() -> ReactionChannel: ...
    @staticmethod
    def Np() -> ReactionChannel: ...
    @staticmethod
    def NAlpha() -> ReactionChannel: ...
    @staticmethod
    def NT() -> ReactionChannel: ...
    @staticmethod
    def Fission() -> ReactionChannel: ...
    def variant(self) -> str: ...

class ReactionRates:
    channels: list[tuple[ReactionChannel, float]]
    @staticmethod
    def none() -> ReactionRates: ...
    @staticmethod
    def from_xs_flux(channels_barns: list[tuple[ReactionChannel, float]], flux: float) -> ReactionRates: ...
    def total_removal(self) -> float: ...
    def fission_rate(self) -> float: ...
    def __init__(self, channels: list[tuple[ReactionChannel, float]] | None = None) -> None: ...
    @staticmethod
    def default() -> ReactionRates: ...

def cram16(a: BurnupMatrix, dt: float, n0: list[float]) -> list[float]: ...
