"""Type stubs for `outram_park.outram_park_fork_pflotran`, generated from the Rust API.

Physical quantities cross this boundary as `float` in SI base units.
"""

class FlowMode:
    def name(self) -> str: ...
    def variant(self) -> str: ...

class PflotranError:
    @staticmethod
    def InvalidInput(a0: str) -> PflotranError: ...
    @staticmethod
    def Convergence(a0: str) -> PflotranError: ...
    @staticmethod
    def Io(a0: str) -> PflotranError: ...
    def variant(self) -> str: ...

class RichardsSimulation:
    @staticmethod
    def from_input_deck(deck: InputDeck) -> RichardsSimulation: ...
    def pressure(self) -> list[float]: ...
    def saturation(self) -> list[float]: ...
    def current_time(self) -> float: ...
    def total_mass(self) -> float: ...
    def flow_field(self) -> FlowField: ...
    def step(self) -> StepReport: ...
    def run(self) -> RunReport: ...

class ActivityModel:
    @staticmethod
    def ionic_strength(charges: list[float], concentrations: list[float]) -> float: ...
    def log10_gamma(self, charge: float, ionic_strength: float) -> float: ...
    def gamma(self, charge: float, ionic_strength: float) -> float: ...
    @staticmethod
    def a_constant() -> float: ...
    @staticmethod
    def Ideal() -> ActivityModel: ...
    @staticmethod
    def DebyeHuckel(ion_size_angstrom: float, bdot: float) -> ActivityModel: ...
    @staticmethod
    def Davies() -> ActivityModel: ...
    def variant(self) -> str: ...

class DecayChain:
    def __init__(self, nuclides: list[Nuclide]) -> None: ...
    def n_nuclides(self) -> int: ...
    def decay_constant(self, i: int) -> float: ...
    def nuclide(self, i: int) -> Nuclide: ...
    def bateman_linear(self, head_initial: float, t: float) -> list[float]: ...

class Nuclide:
    name: str
    half_life_seconds: float
    daughters: list[tuple[int, float]]
    def __init__(self, name: str, half_life_seconds: float, daughters: list[tuple[int, float]]) -> None: ...

class CharacteristicCurveBlock:
    name: str
    saturation_function: str
    alpha: float
    m: float
    liquid_residual_saturation: float
    def __init__(self, name: str, saturation_function: str, alpha: float, m: float, liquid_residual_saturation: float) -> None: ...

class deck_FlowMode:
    @staticmethod
    def Richards() -> deck_FlowMode: ...
    @staticmethod
    def Th() -> deck_FlowMode: ...
    @staticmethod
    def General() -> deck_FlowMode: ...
    @staticmethod
    def Unknown(a0: str) -> deck_FlowMode: ...
    def variant(self) -> str: ...

class GridBlock:
    structured: bool
    nx: int
    ny: int
    nz: int
    bounds_min: list[float]
    bounds_max: list[float]

class MaterialProperty:
    name: str
    id: int
    porosity: float
    permeability_iso: float
    def __init__(self, name: str, id: int, porosity: float, permeability_iso: float) -> None: ...

class PflotranDeck:
    simulation_mode: deck_FlowMode
    grid: GridBlock
    materials: list[MaterialProperty]
    characteristic_curves: list[CharacteristicCurveBlock]
    time: TimeBlock
    def __init__(self, simulation_mode: deck_FlowMode, grid: GridBlock, materials: list[MaterialProperty], characteristic_curves: list[CharacteristicCurveBlock], time: TimeBlock) -> None: ...

class TimeBlock:
    final_time_s: float
    initial_dt_s: float
    max_dt_s: float
    def __init__(self, final_time_s: float, initial_dt_s: float, max_dt_s: float) -> None: ...

class Decomposition1D:
    n_global: int
    n_ranks: int
    rank: int
    start: int
    local_len: int
    left: int | None
    right: int | None
    def __init__(self, n_global: int, comm: outram_park_mpi.Communicator) -> None: ...
    def global_index(self, local: int) -> int: ...

class Halo:
    left: float | None
    right: float | None
    def __init__(self, left: float | None, right: float | None) -> None: ...

class Decomposition2D:
    nx_global: int
    ny_global: int
    cart: outram_park_mpi.CartesianComm
    x0: int
    y0: int
    lx: int
    ly: int
    left: int | None
    right: int | None
    down: int | None
    up: int | None
    def __init__(self, nx_global: int, ny_global: int, cart: outram_park_mpi.CartesianComm) -> None: ...
    def local_len(self) -> int: ...

class Halo2D:
    left: list[float]
    right: list[float]
    down: list[float]
    up: list[float]
    def __init__(self, left: list[float] | None = None, right: list[float] | None = None, down: list[float] | None = None, up: list[float] | None = None) -> None: ...
    @staticmethod
    def default() -> Halo2D: ...

class DistributedLduMatrix1D:
    @staticmethod
    def from_rows(decomp: Decomposition1D, diag: list[float], west: list[float], east: list[float]) -> DistributedLduMatrix1D: ...
    @staticmethod
    def from_global(decomp: Decomposition1D, ldu: outram_foam_basic_lib.LduMatrix) -> DistributedLduMatrix1D: ...

class DiffusionOperator1D:
    def diagonal(self) -> list[float]: ...

class DistributedTransport1D:
    def __init__(self, decomp: Decomposition1D, storage_v: list[float], west_q: list[float], east_q: list[float], west_d: list[float], east_d: list[float], dt: float) -> None: ...
    @staticmethod
    def uniform(decomp: Decomposition1D, storage_cell: float, q: float, d: float, dt: float) -> DistributedTransport1D: ...
    @staticmethod
    def from_global_flow(decomp: Decomposition1D, water_content: list[float], face_flux: list[float], molecular_diffusion: float, longitudinal_dispersivity: float, area: float, geom: float, storage_v: list[float], dt: float) -> DistributedTransport1D: ...
    @staticmethod
    def from_energy_flow(decomp: Decomposition1D, water_content: list[float], face_flux: list[float], rho_cw: float, rock_heat_capacity: float, effective_conductivity: float, geom: float, cell_volume: float, dt: float) -> DistributedTransport1D: ...

class EndCondition:
    @staticmethod
    def Closed() -> EndCondition: ...
    @staticmethod
    def Flux(a0: float) -> EndCondition: ...
    @staticmethod
    def Dirichlet(flux: float, dispersion: float, concentration: float) -> EndCondition: ...
    def variant(self) -> str: ...

class EnergyBoundaryCondition:
    location: BoundaryLocation

class EnergyBoundaryKind:
    @staticmethod
    def DirichletTemperature(a0: float) -> EnergyBoundaryKind: ...
    def variant(self) -> str: ...

class EnergyTransport:
    def set_timestep(self, dt: float) -> None: ...
    def set_previous(self, t_old: list[float]) -> None: ...
    def n_cells(self) -> int: ...
    def total_energy(self, t: list[float]) -> float: ...

class ThermalParameters:
    water_density: float
    water_specific_heat: float
    water_conductivity: float
    rock_density: float
    rock_specific_heat: float
    rock_conductivity: float
    porosity: float
    def __init__(self, water_density: float, water_specific_heat: float, water_conductivity: float, rock_density: float, rock_specific_heat: float, rock_conductivity: float, porosity: float) -> None: ...
    @staticmethod
    def water_rock_defaults() -> ThermalParameters: ...

class Brine:
    nacl_mass_fraction: float
    def __init__(self, nacl_mass_fraction: float) -> None: ...
    def density(self, temperature_c: float, pressure_mpa: float) -> float: ...
    def viscosity(self, temperature_c: float, pressure_mpa: float) -> float: ...

class Co2Properties:
    @staticmethod
    def compressibility(temperature_k: float, pressure_pa: float) -> float: ...
    @staticmethod
    def density(temperature_k: float, pressure_pa: float) -> float: ...
    @staticmethod
    def viscosity(temperature_k: float, pressure_pa: float) -> float: ...
    def __init__(self) -> None: ...
    @staticmethod
    def default() -> Co2Properties: ...

class IapwsWater:
    def __init__(self, ) -> None: ...
    def density(self, pressure_pa: float, temperature_k: float) -> float: ...
    def viscosity(self, pressure_pa: float, temperature_k: float) -> float: ...
    def enthalpy(self, pressure_pa: float, temperature_k: float) -> float: ...
    def internal_energy(self, pressure_pa: float, temperature_k: float) -> float: ...
    def specific_heat(self, pressure_pa: float, temperature_k: float) -> float: ...
    @staticmethod
    def default() -> IapwsWater: ...

class BoundaryCondition:
    location: BoundaryLocation

class BoundaryConditionKind:
    @staticmethod
    def DirichletPressure(a0: float) -> BoundaryConditionKind: ...
    @staticmethod
    def NeumannFlux(a0: float) -> BoundaryConditionKind: ...
    def variant(self) -> str: ...

class RichardsProblem:
    def set_timestep(self, dt: float) -> None: ...
    def set_previous(self, p_old: list[float]) -> None: ...
    def set_source(self, source: list[float]) -> None: ...
    def grid(self) -> CartesianGrid: ...
    def total_mass(self, p: list[float]) -> float: ...
    def flow_field(self, p: list[float]) -> FlowField: ...

class RunReport:
    steps: int
    final_time: float
    total_newton_iterations: int
    def __init__(self, steps: int, final_time: float, total_newton_iterations: int) -> None: ...

class StepReport:
    time: float
    dt: float
    newton_iterations: int
    converged: bool
    def __init__(self, time: float, dt: float, newton_iterations: int, converged: bool) -> None: ...

class TimeControls:
    final_time: float
    initial_dt: float
    max_dt: float
    min_dt: float
    growth_factor: float
    cut_factor: float
    @staticmethod
    def from_time_spec(final_time: float, initial_dt: float, max_dt: float) -> TimeControls: ...
    def __init__(self, final_time: float, initial_dt: float, max_dt: float, min_dt: float, growth_factor: float, cut_factor: float) -> None: ...

class GeneralBoundaryCondition:
    location: BoundaryLocation
    kind: GeneralBoundaryKind
    def __init__(self, location: BoundaryLocation, kind: GeneralBoundaryKind) -> None: ...

class GeneralBoundaryKind:
    @staticmethod
    def Dirichlet(liquid_pressure: float, liquid_saturation: float, temperature: float) -> GeneralBoundaryKind: ...
    @staticmethod
    def NoFlow() -> GeneralBoundaryKind: ...
    def variant(self) -> str: ...

class GeneralFlow:
    def __init__(self, grid: CartesianGrid, fluids: GeneralFluids, curves: CharacteristicCurves, porosity: float, permeability: float, gravity: float, boundary: list[GeneralBoundaryCondition]) -> None: ...
    def set_timestep(self, dt: float) -> None: ...
    def set_previous(self, state: list[float]) -> None: ...
    def grid(self) -> CartesianGrid: ...
    def fluids(self) -> GeneralFluids: ...
    def total_water_mass(self, x: list[float]) -> float: ...
    def total_gas_mass(self, x: list[float]) -> float: ...
    def total_energy(self, x: list[float]) -> float: ...
    def capillary_pressure(self, s_l: float) -> float: ...

class GeneralFluids:
    water: ThermalWaterProperties
    gas_density: float
    gas_viscosity: float
    gas_specific_heat: float
    rock: RockThermalProperties
    reference_temperature: float
    @staticmethod
    def air_water() -> GeneralFluids: ...
    def __init__(self, water: ThermalWaterProperties, gas_density: float, gas_viscosity: float, gas_specific_heat: float, rock: RockThermalProperties, reference_temperature: float) -> None: ...
    def liquid_specific_heat(self) -> float: ...
    def liquid_density(self, p_l: float, t: float) -> float: ...
    def liquid_viscosity(self, t: float) -> float: ...
    def liquid_enthalpy(self, t: float) -> float: ...
    def gas_enthalpy(self, t: float) -> float: ...

class GeneralSimulation:
    def step(self, dt: float) -> BlockNewtonReport: ...
    def time(self) -> float: ...
    def liquid_pressure(self) -> list[float]: ...
    def liquid_saturation(self) -> list[float]: ...
    def temperature(self) -> list[float]: ...
    def state(self) -> list[float]: ...

class ReactionNetwork:
    def __init__(self, primary: list[str], secondary: list[str], stoich: list[list[float]], log10_k: list[float]) -> None: ...
    def n_primary(self) -> int: ...
    def n_secondary(self) -> int: ...
    def primary_names(self) -> list[str]: ...
    def secondary_names(self) -> list[str]: ...

class Speciation:
    primary: list[float]
    secondary: list[float]
    iterations: int
    def __init__(self, primary: list[float], secondary: list[float], iterations: int) -> None: ...

class GpuError:
    @staticmethod
    def Poll(a0: str) -> GpuError: ...
    @staticmethod
    def Map(a0: str) -> GpuError: ...
    @staticmethod
    def MapCallbackMissing() -> GpuError: ...
    def variant(self) -> str: ...

class Axis:
    @staticmethod
    def X() -> Axis: ...
    @staticmethod
    def Y() -> Axis: ...
    @staticmethod
    def Z() -> Axis: ...
    def variant(self) -> str: ...

class BoundaryFace:
    cell: int
    location: BoundaryLocation
    area: float
    distance: float
    axis: Axis
    def __init__(self, cell: int, location: BoundaryLocation, area: float, distance: float, axis: Axis) -> None: ...

class BoundaryLocation:
    @staticmethod
    def XMin() -> BoundaryLocation: ...
    @staticmethod
    def XMax() -> BoundaryLocation: ...
    @staticmethod
    def YMin() -> BoundaryLocation: ...
    @staticmethod
    def YMax() -> BoundaryLocation: ...
    @staticmethod
    def ZMin() -> BoundaryLocation: ...
    @staticmethod
    def ZMax() -> BoundaryLocation: ...
    def variant(self) -> str: ...

class CartesianGrid:
    @staticmethod
    def uniform(nx: int, ny: int, nz: int, dx: float, dy: float, dz: float) -> CartesianGrid: ...
    @staticmethod
    def rectilinear(dx: list[float], dy: list[float], dz: list[float]) -> CartesianGrid: ...
    def dims(self) -> tuple[int, int, int]: ...
    def n_cells(self) -> int: ...
    def cell_index(self, i: int, j: int, k: int) -> int: ...
    def cell_ijk(self, cell: int) -> tuple[int, int, int]: ...
    def cell_volume(self, cell: int) -> float: ...
    def cell_center(self, cell: int) -> list[float]: ...
    def connections(self) -> list[Connection]: ...
    def boundary_faces(self) -> list[BoundaryFace]: ...
    def ldu_addressing(self) -> tuple[list[int], list[int]]: ...

class Connection:
    owner: int
    neighbour: int
    area: float
    distance: float
    geometric_transmissibility: float
    axis: Axis
    def __init__(self, owner: int, neighbour: int, area: float, distance: float, geometric_transmissibility: float, axis: Axis) -> None: ...

class Hdf5Snapshot:
    dims: list[int]
    x: list[float]
    y: list[float]
    z: list[float]
    time: float
    fields: list[tuple[str, list[float]]]
    @staticmethod
    def from_grid_fields(grid: CartesianGrid, time: float, fields: list[tuple[str, list[float]]]) -> Hdf5Snapshot: ...
    def to_bytes(self) -> list[int]: ...
    @staticmethod
    def from_bytes(bytes: list[int]) -> Hdf5Snapshot: ...

class BoundaryConditionSpec:
    location: BoundaryLocationSpec
    kind: BoundaryKindSpec
    def __init__(self, location: BoundaryLocationSpec, kind: BoundaryKindSpec) -> None: ...

class BoundaryKindSpec:
    @staticmethod
    def DirichletPressure(a0: float) -> BoundaryKindSpec: ...
    @staticmethod
    def NeumannFlux(a0: float) -> BoundaryKindSpec: ...
    def variant(self) -> str: ...

class BoundaryLocationSpec:
    @staticmethod
    def XMin() -> BoundaryLocationSpec: ...
    @staticmethod
    def XMax() -> BoundaryLocationSpec: ...
    @staticmethod
    def YMin() -> BoundaryLocationSpec: ...
    @staticmethod
    def YMax() -> BoundaryLocationSpec: ...
    @staticmethod
    def ZMin() -> BoundaryLocationSpec: ...
    @staticmethod
    def ZMax() -> BoundaryLocationSpec: ...
    def variant(self) -> str: ...

class CurveModel:
    @staticmethod
    def VanGenuchten() -> CurveModel: ...
    @staticmethod
    def BrooksCorey() -> CurveModel: ...
    def variant(self) -> str: ...

class CurveSpec:
    model: CurveModel
    alpha: float
    n_or_lambda: float
    residual_saturation: float
    def __init__(self, model: CurveModel, alpha: float, n_or_lambda: float, residual_saturation: float) -> None: ...

class GridSpec:
    nx: int
    ny: int
    nz: int
    dx: float
    dy: float
    dz: float
    def __init__(self, nx: int, ny: int, nz: int, dx: float, dy: float, dz: float) -> None: ...

class InputDeck:
    grid: GridSpec
    material: MaterialSpec
    curves: CurveSpec
    boundary_conditions: list[BoundaryConditionSpec]
    time: TimeSpec
    initial_pressure: float
    def __init__(self, grid: GridSpec, material: MaterialSpec, curves: CurveSpec, boundary_conditions: list[BoundaryConditionSpec], time: TimeSpec, initial_pressure: float) -> None: ...

class MaterialSpec:
    porosity: float
    permeability: float
    def __init__(self, porosity: float, permeability: float) -> None: ...

class TimeSpec:
    final_time: float
    initial_dt: float
    max_dt: float
    def __init__(self, final_time: float, initial_dt: float, max_dt: float) -> None: ...

class KineticMineral:
    name: str
    stoich: list[float]
    log10_ksp: float
    rate_constant: float
    surface_area: float
    def __init__(self, name: str, stoich: list[float], log10_ksp: float, rate_constant: float, surface_area: float) -> None: ...

class KineticSystem:
    def __init__(self, network: ReactionNetwork, minerals: list[KineticMineral]) -> None: ...
    def n_minerals(self) -> int: ...
    def n_primary(self) -> int: ...
    def network(self) -> ReactionNetwork: ...
    def minerals(self) -> list[KineticMineral]: ...
    def saturation_index(self, mineral: int, primary: list[float]) -> float: ...

class MicrobialSystem:
    def __init__(self, n_species: int, reactions: list[MonodReaction]) -> None: ...
    def n_species(self) -> int: ...
    def n_reactions(self) -> int: ...
    def reactions(self) -> list[MonodReaction]: ...
    def rate(self, reaction: int, concentrations: list[float], biomass: list[float]) -> float: ...

class MonodReaction:
    name: str
    donor: int
    acceptor: int
    k_max: float
    half_sat_donor: float
    half_sat_acceptor: float
    stoichiometry: list[float]
    inhibition: list[tuple[int, float]]
    biomass_yield: float
    biomass_decay: float
    def __init__(self, name: str, donor: int, acceptor: int, k_max: float, half_sat_donor: float, half_sat_acceptor: float, stoichiometry: list[float], inhibition: list[tuple[int, float]], biomass_yield: float, biomass_decay: float) -> None: ...

class TwoPhaseBoundaryCondition:
    location: BoundaryLocation
    kind: TwoPhaseBoundaryKind
    def __init__(self, location: BoundaryLocation, kind: TwoPhaseBoundaryKind) -> None: ...

class TwoPhaseBoundaryKind:
    @staticmethod
    def Dirichlet(liquid_pressure: float, liquid_saturation: float) -> TwoPhaseBoundaryKind: ...
    @staticmethod
    def NoFlow() -> TwoPhaseBoundaryKind: ...
    def variant(self) -> str: ...

class TwoPhaseFlow:
    def __init__(self, grid: CartesianGrid, curves: CharacteristicCurves, fluids: TwoPhaseFluids, porosity: float, permeability: float, gravity: float, boundary: list[TwoPhaseBoundaryCondition]) -> None: ...
    def set_timestep(self, dt: float) -> None: ...
    def set_previous(self, state: list[float]) -> None: ...
    def grid(self) -> CartesianGrid: ...
    def total_water_mass(self, x: list[float]) -> float: ...
    def total_gas_mass(self, x: list[float]) -> float: ...
    def capillary_pressure(self, s_l: float) -> float: ...

class TwoPhaseFluids:
    liquid_density: float
    liquid_viscosity: float
    gas_density: float
    gas_viscosity: float
    @staticmethod
    def air_water() -> TwoPhaseFluids: ...
    def __init__(self, liquid_density: float, liquid_viscosity: float, gas_density: float, gas_viscosity: float) -> None: ...

class TwoPhaseSimulation:
    def step(self, dt: float) -> BlockNewtonReport: ...
    def time(self) -> float: ...
    def liquid_pressure(self) -> list[float]: ...
    def liquid_saturation(self) -> list[float]: ...
    def state(self) -> list[float]: ...

class PitzerBinaryParams:
    beta0: float
    beta1: float
    c_phi: float
    z_cation: float
    z_anion: float
    nu_cation: float
    nu_anion: float
    @staticmethod
    def nacl() -> PitzerBinaryParams: ...
    @staticmethod
    def cacl2() -> PitzerBinaryParams: ...
    def ionic_strength(self, molality: float) -> float: ...
    def mean_activity_coefficient(self, molality: float) -> float: ...
    def osmotic_coefficient(self, molality: float) -> float: ...
    def __init__(self, beta0: float, beta1: float, c_phi: float, z_cation: float, z_anion: float, nu_cation: float, nu_anion: float) -> None: ...

class BrooksCorey:
    alpha: float
    sr: float
    def __init__(self, alpha: float, lambda_: float, sr: float) -> None: ...

class CharacteristicCurves:
    def effective_saturation(self, pc: float) -> float: ...
    def d_se_d_pc(self, pc: float) -> float: ...
    def relative_permeability(self, se: float) -> float: ...
    def d_kr_d_se(self, se: float) -> float: ...
    def residual_saturation(self) -> float: ...
    @staticmethod
    def VanGenuchten(a0: VanGenuchten) -> CharacteristicCurves: ...
    @staticmethod
    def BrooksCorey(a0: BrooksCorey) -> CharacteristicCurves: ...
    @staticmethod
    def Haverkamp(a0: Haverkamp) -> CharacteristicCurves: ...
    def variant(self) -> str: ...

class Haverkamp:
    alpha: float
    beta: float
    a: float
    gamma: float
    theta_r: float
    theta_s: float
    cm_per_pa: float
    def __init__(self, alpha: float, beta: float, a: float, gamma: float, theta_r: float, theta_s: float) -> None: ...
    @staticmethod
    def with_conversion(alpha: float, beta: float, a: float, gamma: float, theta_r: float, theta_s: float, cm_per_pa: float) -> Haverkamp: ...
    @staticmethod
    def celia_1977_sand() -> Haverkamp: ...

class LiquidWaterEos:
    reference_density: float
    reference_pressure: float
    compressibility: float
    viscosity: float
    @staticmethod
    def water() -> LiquidWaterEos: ...
    def __init__(self, reference_density: float, reference_pressure: float, compressibility: float, viscosity: float) -> None: ...
    def density(self, p: float) -> float: ...
    def d_density_d_pressure(self, p: float) -> float: ...

class RockThermalProperties:
    density: float
    specific_heat: float
    thermal_conductivity: float
    @staticmethod
    def generic_rock() -> RockThermalProperties: ...
    def __init__(self, density: float, specific_heat: float, thermal_conductivity: float) -> None: ...

class ThermalWaterProperties:
    reference_density: float
    reference_pressure: float
    reference_temperature: float
    compressibility: float
    thermal_expansion: float
    reference_viscosity: float
    specific_heat: float
    thermal_conductivity: float
    @staticmethod
    def water() -> ThermalWaterProperties: ...
    def __init__(self, reference_density: float, reference_pressure: float, reference_temperature: float, compressibility: float, thermal_expansion: float, reference_viscosity: float, specific_heat: float, thermal_conductivity: float) -> None: ...
    def density(self, p: float, t: float) -> float: ...
    def d_density_d_temperature(self, p: float, t: float) -> float: ...
    def viscosity(self, t: float) -> float: ...

class VanGenuchten:
    alpha: float
    n: float
    m: float
    sr: float
    def __init__(self, alpha: float, n: float, sr: float) -> None: ...

class ReactiveBoundaryCondition:
    location: BoundaryLocation
    inflow_totals: list[float]
    def __init__(self, location: BoundaryLocation, inflow_totals: list[float]) -> None: ...

class ReactiveTransport:
    def set_timestep(self, dt: float) -> None: ...
    def n_cells(self) -> int: ...
    def n_components(self) -> int: ...
    def step(self) -> None: ...
    def totals(self, component: int) -> list[float]: ...
    def speciate_cell(self, cell: int) -> Speciation: ...
    def component_mass(self, component: int) -> float: ...

class BlockLduMatrix:
    n_cells: int
    nb: int
    n_internal_faces: int
    diag: list[float]
    upper: list[float]
    lower: list[float]
    owner: list[int]
    neighbour: list[int]
    def __init__(self, n_cells: int, nb: int, owner: list[int], neighbour: list[int]) -> None: ...
    def zero(self) -> None: ...
    def multiply(self, x: list[float]) -> list[float]: ...
    def add_diag(self, cell: int, i: int, j: int, v: float) -> None: ...
    def add_upper(self, face: int, i: int, j: int, v: float) -> None: ...
    def add_lower(self, face: int, i: int, j: int, v: float) -> None: ...

class BlockNewtonConfig:
    max_iterations: int
    abs_tol: float
    rel_tol: float
    linear_tolerance: float
    linear_max_iter: int
    max_backtracks: int
    def __init__(self, max_iterations: int | None = None, abs_tol: float | None = None, rel_tol: float | None = None, linear_tolerance: float | None = None, linear_max_iter: int | None = None, max_backtracks: int | None = None) -> None: ...
    @staticmethod
    def default() -> BlockNewtonConfig: ...

class BlockNewtonReport:
    iterations: int
    converged: bool
    final_residual_norm: float
    residual_history: list[float]
    def __init__(self, iterations: int, converged: bool, final_residual_norm: float, residual_history: list[float]) -> None: ...

class LinearSolverKind:
    @staticmethod
    def BiCGStab() -> LinearSolverKind: ...
    @staticmethod
    def Gmres() -> LinearSolverKind: ...
    def variant(self) -> str: ...

class NewtonConfig:
    max_iterations: int
    abs_tol: float
    rel_tol: float
    linear: LinearSolverKind
    preconditioner: PreconditionerKind
    linear_settings: outram_foam_basic_lib.KrylovSettings
    max_backtracks: int
    def __init__(self, max_iterations: int | None = None, abs_tol: float | None = None, rel_tol: float | None = None, linear: LinearSolverKind | None = None, preconditioner: PreconditionerKind | None = None, linear_settings: outram_foam_basic_lib.KrylovSettings | None = None, max_backtracks: int | None = None) -> None: ...
    @staticmethod
    def default() -> NewtonConfig: ...

class NewtonReport:
    iterations: int
    converged: bool
    final_residual_norm: float
    residual_history: list[float]
    def __init__(self, iterations: int, converged: bool, final_residual_norm: float, residual_history: list[float]) -> None: ...

class PreconditionerKind:
    @staticmethod
    def Identity() -> PreconditionerKind: ...
    @staticmethod
    def Jacobi() -> PreconditionerKind: ...
    @staticmethod
    def Ilu0() -> PreconditionerKind: ...
    def variant(self) -> str: ...

class IonExchange:
    def __init__(self, cec: float, charges: list[float], log10_selectivity: list[float]) -> None: ...
    def n_cations(self) -> int: ...
    def cec(self) -> float: ...
    def exchange_fractions(self, aqueous: list[float]) -> list[float]: ...
    def sorbed_amounts(self, aqueous: list[float]) -> list[float]: ...

class SorptionIsotherm:
    def sorbed(self, c: float) -> float: ...
    def d_sorbed_d_c(self, c: float) -> float: ...
    def retardation(self, c: float, bulk_density: float, water_content: float) -> float: ...
    @staticmethod
    def new_langmuir(s_max: float, k: float) -> SorptionIsotherm: ...
    @staticmethod
    def new_freundlich(kf: float, n: float) -> SorptionIsotherm: ...
    @staticmethod
    def Linear(kd: float) -> SorptionIsotherm: ...
    @staticmethod
    def Langmuir(s_max: float, k: float) -> SorptionIsotherm: ...
    @staticmethod
    def Freundlich(kf: float, n: float) -> SorptionIsotherm: ...
    def variant(self) -> str: ...

class SurfaceComplex:
    log_k: float
    metal_charge: float
    def __init__(self, log_k: float, metal_charge: float) -> None: ...

class SurfaceComplexationModel:
    def validate(self) -> None: ...
    @staticmethod
    def NonElectrostatic() -> SurfaceComplexationModel: ...
    @staticmethod
    def ConstantCapacitance(capacitance: float) -> SurfaceComplexationModel: ...
    @staticmethod
    def DiffuseLayer(ionic_strength: float) -> SurfaceComplexationModel: ...
    def variant(self) -> str: ...

class SurfaceSite:
    log_k_a1: float
    log_k_a2: float
    site_density: float
    specific_surface_area: float
    solid_concentration: float
    def __init__(self, log_k_a1: float, log_k_a2: float, site_density: float, specific_surface_area: float, solid_concentration: float) -> None: ...
    def point_of_zero_charge_ph(self) -> float: ...
    def speciate(self, ph: float, metal_molarity: float, model: SurfaceComplexationModel, complex: SurfaceComplex) -> SurfaceSpeciation: ...
    def sorption_edge(self, ph_values: list[float], metal_molarity: float, model: SurfaceComplexationModel, complex: SurfaceComplex) -> list[tuple[float, float]]: ...

class SurfaceSpeciation:
    soh: float
    soh2: float
    so_minus: float
    som: float
    surface_potential: float
    fraction_metal_sorbed: float
    def net_surface_charge(self, metal_charge: float) -> float: ...
    def __init__(self, soh: float, soh2: float, so_minus: float, som: float, surface_potential: float, fraction_metal_sorbed: float) -> None: ...

class AdaptiveStepReport:
    substeps: int
    cuts: int
    min_substep_dt: float
    max_newton_iterations: int
    def __init__(self, substeps: int, cuts: int, min_substep_dt: float, max_newton_iterations: int) -> None: ...

class ConvectionBoundaryCondition:
    location: BoundaryLocation
    kind: ConvectionBoundaryKind
    def __init__(self, location: BoundaryLocation, kind: ConvectionBoundaryKind) -> None: ...

class ConvectionBoundaryKind:
    @staticmethod
    def Insulated() -> ConvectionBoundaryKind: ...
    @staticmethod
    def FixedTemperature(a0: float) -> ConvectionBoundaryKind: ...
    @staticmethod
    def Dirichlet(pressure: float, temperature: float) -> ConvectionBoundaryKind: ...
    def variant(self) -> str: ...

class ConvectionParameters:
    permeability: float
    porosity: float
    fluid_viscosity: float
    fluid_compressibility: float
    reference_density: float
    thermal_expansion: float
    reference_temperature: float
    fluid_specific_heat: float
    rock_volumetric_heat_capacity: float
    bulk_conductivity: float
    gravity: float
    @staticmethod
    def water_saturated() -> ConvectionParameters: ...
    def __init__(self, permeability: float, porosity: float, fluid_viscosity: float, fluid_compressibility: float, reference_density: float, thermal_expansion: float, reference_temperature: float, fluid_specific_heat: float, rock_volumetric_heat_capacity: float, bulk_conductivity: float, gravity: float) -> None: ...
    def fluid_density(self, t: float) -> float: ...

class ThermalConvection:
    def __init__(self, grid: CartesianGrid, params: ConvectionParameters, boundary: list[ConvectionBoundaryCondition]) -> None: ...
    def set_timestep(self, dt: float) -> None: ...
    def set_previous(self, state: list[float]) -> None: ...
    def grid(self) -> CartesianGrid: ...
    def params(self) -> ConvectionParameters: ...
    def total_energy(self, x: list[float]) -> float: ...
    def peak_velocity(self, x: list[float]) -> float: ...

class ThermalConvectionSimulation:
    def step(self, dt: float) -> BlockNewtonReport: ...
    def step_adaptive(self, dt: float, min_dt: float) -> AdaptiveStepReport: ...
    def time(self) -> float: ...
    def temperature(self) -> list[float]: ...
    def pressure(self) -> list[float]: ...
    def peak_velocity(self) -> float: ...
    def total_energy(self) -> float: ...
    def state(self) -> list[float]: ...

class DispersionModel:
    molecular_diffusion: float
    longitudinal_dispersivity: float
    def __init__(self, molecular_diffusion: float, longitudinal_dispersivity: float) -> None: ...

class FlowField:
    face_flux: list[float]
    boundary_flux: list[float]
    water_content: list[float]
    def __init__(self, face_flux: list[float], boundary_flux: list[float], water_content: list[float]) -> None: ...

class SoluteTransport:
    def set_flux_limiter(self, limiter: outram_foam_basic_lib.FluxLimiter) -> None: ...
    def set_decay_constant(self, lambda_: float) -> None: ...
    def set_linear_sorption(self, isotherm: SorptionIsotherm, bulk_density: float) -> None: ...
    def set_timestep(self, dt: float) -> None: ...
    def set_previous(self, c_old: list[float]) -> None: ...
    def n_cells(self) -> int: ...
    def total_mass(self, c: list[float]) -> float: ...

class TransportBoundaryCondition:
    location: BoundaryLocation

class TransportBoundaryKind:
    @staticmethod
    def InflowConcentration(a0: float) -> TransportBoundaryKind: ...
    def variant(self) -> str: ...

class CellId:
    def index(self) -> int: ...

class UnstructuredBoundaryFace:
    cell: int
    area: float
    normal: list[float]
    centroid: list[float]

class UnstructuredConnection:
    cell_a: int
    cell_b: int
    area: float
    transmissibility_geom: float
    def __init__(self, cell_a: int, cell_b: int, area: float, transmissibility_geom: float) -> None: ...

class UnstructuredGrid:
    @staticmethod
    def uniform_column(n: int, length: float, area: float) -> UnstructuredGrid: ...
    def n_cells(self) -> int: ...
    def cell_volume(self, cell: int) -> float: ...
    def cell_centroid(self, cell: int) -> list[float]: ...
    def connections(self) -> list[UnstructuredConnection]: ...
    def boundary_faces(self) -> list[UnstructuredBoundaryFace]: ...
    def ldu_addressing(self) -> tuple[list[int], list[int]]: ...

class AdvancedBc:
    @staticmethod
    def time_varying(table: list[tuple[float, float]]) -> AdvancedBc: ...
    def value(self, z: float, cell_pressure: float, time: float) -> float: ...
    @staticmethod
    def Hydrostatic(pressure_datum: float, z_datum: float, density: float, gravity: float) -> AdvancedBc: ...
    @staticmethod
    def SeepageFace(atmospheric_pressure: float) -> AdvancedBc: ...
    @staticmethod
    def TimeVarying(table: list[tuple[float, float]]) -> AdvancedBc: ...
    def variant(self) -> str: ...

class PeacemanWell:
    cells: list[int]
    radius: float
    skin: float
    control: WellControl
    def __init__(self, cells: list[int], radius: float, skin: float, control: WellControl) -> None: ...
    @staticmethod
    def well_index(dx: float, dy: float, dz: float, permeability: float, r_w: float, skin: float) -> float: ...
    def cell_rates(self, grid: CartesianGrid, permeability: float, mobility: float, cell_pressure: list[float]) -> list[float]: ...

class SourceSink:
    def cell(self) -> int: ...
    def volumetric_rate(self, density: float) -> float: ...
    @staticmethod
    def Volumetric(cell: int, rate: float) -> SourceSink: ...
    @staticmethod
    def Mass(cell: int, rate: float) -> SourceSink: ...
    def variant(self) -> str: ...

class WellControl:
    @staticmethod
    def BottomHolePressure(a0: float) -> WellControl: ...
    @staticmethod
    def VolumetricRate(a0: float) -> WellControl: ...
    def variant(self) -> str: ...

def parse_fortran_float(token: str) -> float: ...
def parse_pflotran_deck(input: str) -> PflotranDeck: ...
def time_to_seconds(value: float, unit: str) -> float: ...
def serial_poisson_2d_cg(nx: int, ny: int, b: list[float], shift: float, tol: float, max_iter: int) -> tuple[list[float], int]: ...
def jacobi_smooth_serial(n_global: int, left_bc: float, right_bc: float, iterations: int) -> list[float]: ...
def serial_cg(n_global: int, b: list[float], shift: float, tol: float, max_iter: int) -> tuple[list[float], int]: ...
def assemble_advection_diffusion_ldu(grid: CartesianGrid, k: list[float], velocity: float, shift: float) -> outram_foam_basic_lib.LduMatrix: ...
def assemble_diffusion_ldu(grid: CartesianGrid, k: list[float], shift: float) -> outram_foam_basic_lib.LduMatrix: ...
def serial_ldu_bicgstab(ldu: outram_foam_basic_lib.LduMatrix, b: list[float], tol: float, max_iter: int) -> tuple[list[float], int]: ...
def serial_ldu_cg(ldu: outram_foam_basic_lib.LduMatrix, b: list[float], tol: float, max_iter: int) -> tuple[list[float], int]: ...
def serial_diffusion_cg(n_global: int, k: list[float], b: list[float], shift: float, tol: float, max_iter: int) -> tuple[list[float], int]: ...
def serial_diffusion_matvec(n_global: int, k: list[float], u: list[float], shift: float) -> list[float]: ...
def probe() -> GpuContext | None: ...
def van_genuchten_se_best_effort(alpha: float, n: float, m: float, pc: list[float]) -> list[float]: ...
def van_genuchten_se_cpu(alpha: float, n: float, m: float, pc: list[float]) -> list[float]: ...
def parse_deck(input: str) -> InputDeck: ...
def write_results_csv(nx: int, ny: int, nz: int, dx: float, dy: float, dz: float, pressure: list[float], saturation: list[float]) -> str: ...
def write_vtk_structured(nx: int, ny: int, nz: int, dx: float, dy: float, dz: float, pressure: list[float], saturation: list[float]) -> str: ...
def rayleigh_number(params: ConvectionParameters, delta_t: float, height: float) -> float: ...
ATMOSPHERIC_PRESSURE: float
STANDARD_GRAVITY: float
STANDARD_GRAVITY: float
STANDARD_GRAVITY: float
A_PHI_25C: float
CRITICAL_RAYLEIGH_NUMBER: float
STANDARD_GRAVITY: float
