"""Type stubs for `outram_park.outram_foam_cli`, generated from the Rust API.

Physical quantities cross this boundary as `float` in SI base units.
"""

class CaseArgs:
    def case_dir(self) -> str: ...

class CliError:
    @staticmethod
    def CaseNotFound(a0: str) -> CliError: ...
    @staticmethod
    def Io(a0: str) -> CliError: ...
    @staticmethod
    def Tool(a0: str) -> CliError: ...
    def variant(self) -> str: ...

def openfoam_args() -> CaseArgs: ...
