"""Type stubs for `outram_park.outram_park_fork_coolprop`, generated from the Rust API.

Physical quantities cross this boundary as `float` in SI base units.
"""

class FlashError:
    @staticmethod
    def NonConvergent() -> FlashError: ...
    @staticmethod
    def NonPhysicalInput() -> FlashError: ...
    def variant(self) -> str: ...

class Fluid:
    def eos(self) -> FluidEos: ...
    def ancillaries(self) -> FluidAncillaries | None: ...
    def transport(self) -> FluidTransport | None: ...
    def name(self) -> str: ...
    @staticmethod
    def Acetone() -> Fluid: ...
    @staticmethod
    def Air() -> Fluid: ...
    @staticmethod
    def Ammonia() -> Fluid: ...
    @staticmethod
    def Argon() -> Fluid: ...
    @staticmethod
    def Benzene() -> Fluid: ...
    @staticmethod
    def CarbonDioxide() -> Fluid: ...
    @staticmethod
    def CarbonMonoxide() -> Fluid: ...
    @staticmethod
    def CarbonylSulfide() -> Fluid: ...
    @staticmethod
    def Chlorine() -> Fluid: ...
    @staticmethod
    def Cis2Butene() -> Fluid: ...
    @staticmethod
    def CycloHexane() -> Fluid: ...
    @staticmethod
    def CycloPropane() -> Fluid: ...
    @staticmethod
    def Cyclopentane() -> Fluid: ...
    @staticmethod
    def D4() -> Fluid: ...
    @staticmethod
    def D5() -> Fluid: ...
    @staticmethod
    def D6() -> Fluid: ...
    @staticmethod
    def Deuterium() -> Fluid: ...
    @staticmethod
    def Dichloroethane() -> Fluid: ...
    @staticmethod
    def DiethylEther() -> Fluid: ...
    @staticmethod
    def DimethylCarbonate() -> Fluid: ...
    @staticmethod
    def DimethylEther() -> Fluid: ...
    @staticmethod
    def Ethane() -> Fluid: ...
    @staticmethod
    def Ethanol() -> Fluid: ...
    @staticmethod
    def EthylBenzene() -> Fluid: ...
    @staticmethod
    def Ethylene() -> Fluid: ...
    @staticmethod
    def EthyleneOxide() -> Fluid: ...
    @staticmethod
    def F1Butene() -> Fluid: ...
    @staticmethod
    def Fluorine() -> Fluid: ...
    @staticmethod
    def HFE143m() -> Fluid: ...
    @staticmethod
    def HeavyWater() -> Fluid: ...
    @staticmethod
    def Helium() -> Fluid: ...
    @staticmethod
    def Hydrogen() -> Fluid: ...
    @staticmethod
    def HydrogenChloride() -> Fluid: ...
    @staticmethod
    def HydrogenSulfide() -> Fluid: ...
    @staticmethod
    def IsoButane() -> Fluid: ...
    @staticmethod
    def IsoButene() -> Fluid: ...
    @staticmethod
    def Isohexane() -> Fluid: ...
    @staticmethod
    def Isopentane() -> Fluid: ...
    @staticmethod
    def Krypton() -> Fluid: ...
    @staticmethod
    def MD2M() -> Fluid: ...
    @staticmethod
    def MD3M() -> Fluid: ...
    @staticmethod
    def MD4M() -> Fluid: ...
    @staticmethod
    def MDM() -> Fluid: ...
    @staticmethod
    def MM() -> Fluid: ...
    @staticmethod
    def MXylene() -> Fluid: ...
    @staticmethod
    def Methane() -> Fluid: ...
    @staticmethod
    def Methanol() -> Fluid: ...
    @staticmethod
    def MethylLinoleate() -> Fluid: ...
    @staticmethod
    def MethylLinolenate() -> Fluid: ...
    @staticmethod
    def MethylOleate() -> Fluid: ...
    @staticmethod
    def MethylPalmitate() -> Fluid: ...
    @staticmethod
    def MethylStearate() -> Fluid: ...
    @staticmethod
    def NButane() -> Fluid: ...
    @staticmethod
    def NDecane() -> Fluid: ...
    @staticmethod
    def NDodecane() -> Fluid: ...
    @staticmethod
    def NHeptane() -> Fluid: ...
    @staticmethod
    def NHexane() -> Fluid: ...
    @staticmethod
    def NNonane() -> Fluid: ...
    @staticmethod
    def NOctane() -> Fluid: ...
    @staticmethod
    def NPentane() -> Fluid: ...
    @staticmethod
    def NPerfluorobutane() -> Fluid: ...
    @staticmethod
    def NPerfluorohexane() -> Fluid: ...
    @staticmethod
    def NPerfluoropentane() -> Fluid: ...
    @staticmethod
    def NPropane() -> Fluid: ...
    @staticmethod
    def NUndecane() -> Fluid: ...
    @staticmethod
    def Neon() -> Fluid: ...
    @staticmethod
    def Neopentane() -> Fluid: ...
    @staticmethod
    def Nitrogen() -> Fluid: ...
    @staticmethod
    def NitrousOxide() -> Fluid: ...
    @staticmethod
    def Novec649() -> Fluid: ...
    @staticmethod
    def OXylene() -> Fluid: ...
    @staticmethod
    def OrthoDeuterium() -> Fluid: ...
    @staticmethod
    def OrthoHydrogen() -> Fluid: ...
    @staticmethod
    def Oxygen() -> Fluid: ...
    @staticmethod
    def PXylene() -> Fluid: ...
    @staticmethod
    def ParaDeuterium() -> Fluid: ...
    @staticmethod
    def ParaHydrogen() -> Fluid: ...
    @staticmethod
    def Propylene() -> Fluid: ...
    @staticmethod
    def PropyleneGlycol() -> Fluid: ...
    @staticmethod
    def Propyne() -> Fluid: ...
    @staticmethod
    def R11() -> Fluid: ...
    @staticmethod
    def R1123() -> Fluid: ...
    @staticmethod
    def R113() -> Fluid: ...
    @staticmethod
    def R1130E() -> Fluid: ...
    @staticmethod
    def R1132E() -> Fluid: ...
    @staticmethod
    def R1132a() -> Fluid: ...
    @staticmethod
    def R114() -> Fluid: ...
    @staticmethod
    def R115() -> Fluid: ...
    @staticmethod
    def R116() -> Fluid: ...
    @staticmethod
    def R12() -> Fluid: ...
    @staticmethod
    def R1224ydZ() -> Fluid: ...
    @staticmethod
    def R123() -> Fluid: ...
    @staticmethod
    def R1233zdE() -> Fluid: ...
    @staticmethod
    def R1234yf() -> Fluid: ...
    @staticmethod
    def R1234zeE() -> Fluid: ...
    @staticmethod
    def R1234zeZ() -> Fluid: ...
    @staticmethod
    def R124() -> Fluid: ...
    @staticmethod
    def R1243zf() -> Fluid: ...
    @staticmethod
    def R125() -> Fluid: ...
    @staticmethod
    def R13() -> Fluid: ...
    @staticmethod
    def R1336mzzE() -> Fluid: ...
    @staticmethod
    def R1336mzzZ() -> Fluid: ...
    @staticmethod
    def R134a() -> Fluid: ...
    @staticmethod
    def R13I1() -> Fluid: ...
    @staticmethod
    def R14() -> Fluid: ...
    @staticmethod
    def R141b() -> Fluid: ...
    @staticmethod
    def R142b() -> Fluid: ...
    @staticmethod
    def R143a() -> Fluid: ...
    @staticmethod
    def R152A() -> Fluid: ...
    @staticmethod
    def R161() -> Fluid: ...
    @staticmethod
    def R21() -> Fluid: ...
    @staticmethod
    def R218() -> Fluid: ...
    @staticmethod
    def R22() -> Fluid: ...
    @staticmethod
    def R227EA() -> Fluid: ...
    @staticmethod
    def R23() -> Fluid: ...
    @staticmethod
    def R236EA() -> Fluid: ...
    @staticmethod
    def R236FA() -> Fluid: ...
    @staticmethod
    def R245ca() -> Fluid: ...
    @staticmethod
    def R245fa() -> Fluid: ...
    @staticmethod
    def R32() -> Fluid: ...
    @staticmethod
    def R365MFC() -> Fluid: ...
    @staticmethod
    def R40() -> Fluid: ...
    @staticmethod
    def R404A() -> Fluid: ...
    @staticmethod
    def R407C() -> Fluid: ...
    @staticmethod
    def R41() -> Fluid: ...
    @staticmethod
    def R410A() -> Fluid: ...
    @staticmethod
    def R507A() -> Fluid: ...
    @staticmethod
    def RC318() -> Fluid: ...
    @staticmethod
    def SES36() -> Fluid: ...
    @staticmethod
    def SulfurDioxide() -> Fluid: ...
    @staticmethod
    def SulfurHexafluoride() -> Fluid: ...
    @staticmethod
    def Tetrahydrofuran() -> Fluid: ...
    @staticmethod
    def Toluene() -> Fluid: ...
    @staticmethod
    def Trans2Butene() -> Fluid: ...
    @staticmethod
    def VinylChloride() -> Fluid: ...
    @staticmethod
    def Water() -> Fluid: ...
    @staticmethod
    def Xenon() -> Fluid: ...
    def variant(self) -> str: ...

class FluidAncillaries:
    p_sat: SatAncillary
    rho_l: SatAncillary
    rho_v: SatAncillary
    def __init__(self, p_sat: SatAncillary, rho_l: SatAncillary, rho_v: SatAncillary) -> None: ...

class FluidEos:
    name: str
    molar_mass: float
    gas_constant: float
    t_reducing: float
    rho_reducing: float
    t_critical: float
    rho_critical: float
    p_critical: float
    t_triple: float
    t_max: float
    p_max: float
    acentric: float
    residual: list[ResidualTerm]
    ideal: list[IdealTerm]
    def residual_derivs(self, delta: float, tau: float) -> HelmholtzDerivs: ...
    def ideal_derivs(self, delta: float, tau: float) -> HelmholtzDerivs: ...

class FluidState:
    temperature: float
    density: float
    pressure: float
    internal_energy: float
    enthalpy: float
    entropy: float
    cv: float
    cp: float
    speed_of_sound: float
    def __init__(self, temperature: float, density: float, pressure: float, internal_energy: float, enthalpy: float, entropy: float, cv: float, cp: float, speed_of_sound: float) -> None: ...

class FluidTransport:
    viscosity: ViscosityModel | None
    conductivity: ConductivityModel | None
    def __init__(self, viscosity: ViscosityModel | None, conductivity: ConductivityModel | None) -> None: ...

class HelmholtzDerivs:
    a: float
    ad: float
    at: float
    add: float
    att: float
    adt: float
    def __init__(self, a: float, ad: float, at: float, add: float, att: float, adt: float) -> None: ...
    @staticmethod
    def default() -> HelmholtzDerivs: ...

class IdealTerm:
    @staticmethod
    def Lead(a1: float, a2: float) -> IdealTerm: ...
    @staticmethod
    def LogTau(a: float) -> IdealTerm: ...
    @staticmethod
    def EnthalpyEntropyOffset(a1: float, a2: float) -> IdealTerm: ...
    @staticmethod
    def CP0Constant(cp_over_r: float, tau0: float) -> IdealTerm: ...
    def variant(self) -> str: ...

class OPCPFluidArray:
    fluid: Fluid
    delta_t: float
    n_outer_correctors: int
    n_inner_correctors: int
    p_under_relaxation: float
    u_under_relaxation: float
    p_min: float
    p_max: float
    h_min: float
    h_max: float
    h_clamp_events: int
    he_convection_scheme: EnergyConvectionScheme
    he_balance_mode: EnergyBalanceMode
    mode: SolverMode
    ma_blend_lo: float
    ma_blend_hi: float
    hybrid_rho_taper_lo: float
    hybrid_rho_taper_hi: float
    xs_area: float
    wetted_perimeter: float
    incline_angle: float
    mass_flowrate: float
    inlet_mass_flowrate: float | None
    pressure_loss: float
    internal_pressure_source: float
    lateral_adjacent_array_temperature_vector: list[list[float]]
    lateral_adjacent_array_conductance_vector: list[list[float]]
    q_vector: list[float]
    q_fraction_vector: list[list[float]]
    def clear_vectors(self) -> None: ...
    def get_hydraulic_diameter(self) -> float: ...
    def clear_inlet_mass_flowrate(self) -> None: ...
    def get_inlet_mass_flowrate_actual(self) -> float: ...
    def get_outlet_mass_flowrate_actual(self) -> float: ...
    def get_temperature_vector(self) -> list[float]: ...
    def set_inlet_velocity(self, velocity: float) -> None: ...
    def set_inlet_enthalpy(self, h: float) -> None: ...
    def set_outlet_enthalpy(self, h: float) -> None: ...
    def get_inlet_advected_enthalpy(self) -> float: ...
    def get_outlet_advected_enthalpy(self) -> float: ...
    def set_outlet_pressure(self, p: float) -> None: ...
    def get_outlet_pressure(self) -> float: ...
    def get_outlet_enthalpy(self) -> float: ...
    def get_outlet_temperature(self) -> float: ...
    def __init__(self, fluid: Fluid, length: float, xs_area: float, number_of_cells: int, delta_t: float) -> None: ...
    def correct_thermo(self) -> None: ...
    def correct_transport(self) -> None: ...
    def step(self) -> None: ...
    def run(self, n_steps: int) -> None: ...
    def get_pressure_under_relaxation(self) -> float: ...
    def set_pressure_under_relaxation(self, alpha: float) -> None: ...
    def get_velocity_under_relaxation(self) -> float: ...
    def set_velocity_under_relaxation(self, alpha: float) -> None: ...
    def set_piso_algorithm(self, n_correctors: int) -> None: ...
    def set_simple_algorithm(self, n_outer_iterations: int) -> None: ...
    def set_pimple_algorithm(self, n_outer_correctors: int, n_inner_correctors: int, pressure_under_relaxation: float, velocity_under_relaxation: float) -> None: ...
    def get_pressure_bounds(self) -> tuple[float, float]: ...
    def set_pressure_bounds(self, p_min: float, p_max: float) -> None: ...
    def get_solver_mode(self) -> SolverMode: ...
    def set_solver_mode(self, mode: SolverMode) -> None: ...
    def get_mach_blend_window(self) -> tuple[float, float]: ...
    def set_mach_blend_window(self, lo: float, hi: float) -> None: ...
    def get_rho_taper_window(self) -> tuple[float, float]: ...
    def set_rho_taper_window(self, lo: float, hi: float) -> None: ...
    def get_enthalpy_bounds(self) -> tuple[float, float]: ...
    def set_enthalpy_bounds(self, h_min: float, h_max: float) -> None: ...

class OPCPFluidArrayError:
    @staticmethod
    def InvalidTimestep(seconds: float) -> OPCPFluidArrayError: ...
    def variant(self) -> str: ...

class OPCPFluidSingleCV:
    @staticmethod
    def new_from_trho(fluid: Fluid, temperature: float, density: float, volume: float) -> OPCPFluidSingleCV: ...
    @staticmethod
    def try_new_from_pt(fluid: Fluid, pressure: float, temperature: float, volume: float) -> OPCPFluidSingleCV: ...
    @staticmethod
    def try_new_from_ph(fluid: Fluid, pressure: float, specific_enthalpy: float, volume: float) -> OPCPFluidSingleCV: ...
    @staticmethod
    def try_new_from_ps(fluid: Fluid, pressure: float, specific_entropy: float, volume: float) -> OPCPFluidSingleCV: ...
    def set_trho(self, temperature: float, density: float) -> None: ...
    def get_fluid(self) -> Fluid: ...
    def get_pressure(self) -> float: ...
    def get_temperature(self) -> float: ...
    def get_density(self) -> float: ...
    def get_specific_volume(self) -> float: ...
    def get_specific_internal_energy(self) -> float: ...
    def get_specific_enthalpy(self) -> float: ...
    def get_specific_entropy(self) -> float: ...
    def get_cv(self) -> float: ...
    def get_cp(self) -> float: ...
    def get_specific_heat_ratio(self) -> float: ...
    def get_speed_of_sound(self) -> float: ...
    def get_volume(self) -> float: ...
    def get_mass(self) -> float: ...
    def get_quality(self) -> float | None: ...
    def is_two_phase(self) -> bool: ...
    def get_viscosity(self) -> float | None: ...
    def get_thermal_conductivity(self) -> float | None: ...

class PhaseAtPh:
    @staticmethod
    def SinglePhase() -> PhaseAtPh: ...
    @staticmethod
    def TwoPhase(temperature: float, quality: float, density: float) -> PhaseAtPh: ...
    def variant(self) -> str: ...

class ResidualTerm:
    def variant(self) -> str: ...

class SatAncillary:
    reducing_value: float
    t_r: float
    using_tau_r: bool
    exponential: bool
    n: list[float]
    t: list[float]
    def evaluate(self, t: float) -> float: ...

class SaturationState:
    temperature: float
    pressure: float
    rho_liquid: float
    rho_vapour: float
    def __init__(self, temperature: float, pressure: float, rho_liquid: float, rho_vapour: float) -> None: ...

class HumidAirError:
    @staticmethod
    def UnsupportedInputs() -> HumidAirError: ...
    @staticmethod
    def NonConvergent() -> HumidAirError: ...
    @staticmethod
    def OutOfRange() -> HumidAirError: ...
    def variant(self) -> str: ...

class HumidAirParam:
    @staticmethod
    def TDryBulb() -> HumidAirParam: ...
    @staticmethod
    def Pressure() -> HumidAirParam: ...
    @staticmethod
    def HumidityRatio() -> HumidAirParam: ...
    @staticmethod
    def RelativeHumidity() -> HumidAirParam: ...
    @staticmethod
    def WaterMoleFraction() -> HumidAirParam: ...
    @staticmethod
    def TWetBulb() -> HumidAirParam: ...
    @staticmethod
    def TDewPoint() -> HumidAirParam: ...
    @staticmethod
    def Enthalpy() -> HumidAirParam: ...
    @staticmethod
    def Entropy() -> HumidAirParam: ...
    @staticmethod
    def Volume() -> HumidAirParam: ...
    @staticmethod
    def WaterPartialPressure() -> HumidAirParam: ...
    @staticmethod
    def EnthalpyHumidAir() -> HumidAirParam: ...
    @staticmethod
    def EntropyHumidAir() -> HumidAirParam: ...
    @staticmethod
    def VolumeHumidAir() -> HumidAirParam: ...
    @staticmethod
    def InternalEnergy() -> HumidAirParam: ...
    @staticmethod
    def InternalEnergyHumidAir() -> HumidAirParam: ...
    @staticmethod
    def IsobaricHeatCapacity() -> HumidAirParam: ...
    @staticmethod
    def IsobaricHeatCapacityHumidAir() -> HumidAirParam: ...
    @staticmethod
    def IsochoricHeatCapacity() -> HumidAirParam: ...
    @staticmethod
    def IsochoricHeatCapacityHumidAir() -> HumidAirParam: ...
    @staticmethod
    def CompressibilityFactor() -> HumidAirParam: ...
    def variant(self) -> str: ...

class HumidAirState:
    t_dry_bulb: float
    pressure: float
    water_mole_fraction: float
    humidity_ratio: float
    relative_humidity: float
    enthalpy: float
    entropy: float
    volume: float
    def __init__(self, t_dry_bulb: float, pressure: float, water_mole_fraction: float, humidity_ratio: float, relative_humidity: float, enthalpy: float, entropy: float, volume: float) -> None: ...

class Incompressible:
    def density(self, t: float, _p: float, x: float) -> float: ...
    def heat_capacity(self, t: float, _p: float, x: float) -> float: ...
    def conductivity(self, t: float, _p: float, x: float) -> float: ...
    def viscosity(self, t: float, _p: float, x: float) -> float: ...
    def enthalpy(self, t: float, _p: float, x: float) -> float: ...
    def temperature_from_enthalpy(self, h: float, p: float, x: float) -> float: ...
    def t_freeze(self, x: float) -> float: ...
    def saturation_pressure(self, t: float, x: float) -> float: ...
    def entropy(self, t: float, _p: float, x: float) -> float: ...
    def internal_energy(self, t: float, p: float, x: float) -> float: ...
    def name(self) -> str: ...
    def data(self) -> IncompressibleFluid: ...
    @staticmethod
    def AEG() -> Incompressible: ...
    @staticmethod
    def AKF() -> Incompressible: ...
    @staticmethod
    def AL() -> Incompressible: ...
    @staticmethod
    def AN() -> Incompressible: ...
    @staticmethod
    def APG() -> Incompressible: ...
    @staticmethod
    def AS10() -> Incompressible: ...
    @staticmethod
    def AS20() -> Incompressible: ...
    @staticmethod
    def AS30() -> Incompressible: ...
    @staticmethod
    def AS40() -> Incompressible: ...
    @staticmethod
    def AS55() -> Incompressible: ...
    @staticmethod
    def Acetone() -> Incompressible: ...
    @staticmethod
    def Air() -> Incompressible: ...
    @staticmethod
    def DEB() -> Incompressible: ...
    @staticmethod
    def DSF() -> Incompressible: ...
    @staticmethod
    def DowJ() -> Incompressible: ...
    @staticmethod
    def DowJ2() -> Incompressible: ...
    @staticmethod
    def DowQ() -> Incompressible: ...
    @staticmethod
    def DowQ2() -> Incompressible: ...
    @staticmethod
    def Ethanol() -> Incompressible: ...
    @staticmethod
    def ExampleDigital() -> Incompressible: ...
    @staticmethod
    def ExampleDigitalPure() -> Incompressible: ...
    @staticmethod
    def ExampleMelinder() -> Incompressible: ...
    @staticmethod
    def ExamplePure() -> Incompressible: ...
    @staticmethod
    def ExampleSecCool() -> Incompressible: ...
    @staticmethod
    def ExampleSolution() -> Incompressible: ...
    @staticmethod
    def FRE() -> Incompressible: ...
    @staticmethod
    def FoodAsh() -> Incompressible: ...
    @staticmethod
    def FoodCarbohydrate() -> Incompressible: ...
    @staticmethod
    def FoodFat() -> Incompressible: ...
    @staticmethod
    def FoodFiber() -> Incompressible: ...
    @staticmethod
    def FoodIce() -> Incompressible: ...
    @staticmethod
    def FoodProtein() -> Incompressible: ...
    @staticmethod
    def FoodWater() -> Incompressible: ...
    @staticmethod
    def GKN() -> Incompressible: ...
    @staticmethod
    def HC10() -> Incompressible: ...
    @staticmethod
    def HC20() -> Incompressible: ...
    @staticmethod
    def HC30() -> Incompressible: ...
    @staticmethod
    def HC40() -> Incompressible: ...
    @staticmethod
    def HC50() -> Incompressible: ...
    @staticmethod
    def HCB() -> Incompressible: ...
    @staticmethod
    def HCM() -> Incompressible: ...
    @staticmethod
    def HFE() -> Incompressible: ...
    @staticmethod
    def HFE2() -> Incompressible: ...
    @staticmethod
    def HY20() -> Incompressible: ...
    @staticmethod
    def HY30() -> Incompressible: ...
    @staticmethod
    def HY40() -> Incompressible: ...
    @staticmethod
    def HY45() -> Incompressible: ...
    @staticmethod
    def HY50() -> Incompressible: ...
    @staticmethod
    def Hexane() -> Incompressible: ...
    @staticmethod
    def IceEA() -> Incompressible: ...
    @staticmethod
    def IceNA() -> Incompressible: ...
    @staticmethod
    def IcePG() -> Incompressible: ...
    @staticmethod
    def LiBr() -> Incompressible: ...
    @staticmethod
    def LiqNa() -> Incompressible: ...
    @staticmethod
    def MAM() -> Incompressible: ...
    @staticmethod
    def MAM2() -> Incompressible: ...
    @staticmethod
    def MCA() -> Incompressible: ...
    @staticmethod
    def MCA2() -> Incompressible: ...
    @staticmethod
    def MEA() -> Incompressible: ...
    @staticmethod
    def MEA2() -> Incompressible: ...
    @staticmethod
    def MEG() -> Incompressible: ...
    @staticmethod
    def MEG2() -> Incompressible: ...
    @staticmethod
    def MGL() -> Incompressible: ...
    @staticmethod
    def MGL2() -> Incompressible: ...
    @staticmethod
    def MITSW() -> Incompressible: ...
    @staticmethod
    def MKA() -> Incompressible: ...
    @staticmethod
    def MKA2() -> Incompressible: ...
    @staticmethod
    def MKC() -> Incompressible: ...
    @staticmethod
    def MKC2() -> Incompressible: ...
    @staticmethod
    def MKF() -> Incompressible: ...
    @staticmethod
    def MLI() -> Incompressible: ...
    @staticmethod
    def MMA() -> Incompressible: ...
    @staticmethod
    def MMA2() -> Incompressible: ...
    @staticmethod
    def MMG() -> Incompressible: ...
    @staticmethod
    def MMG2() -> Incompressible: ...
    @staticmethod
    def MNA() -> Incompressible: ...
    @staticmethod
    def MNA2() -> Incompressible: ...
    @staticmethod
    def MPG() -> Incompressible: ...
    @staticmethod
    def MPG2() -> Incompressible: ...
    @staticmethod
    def NBS() -> Incompressible: ...
    @staticmethod
    def NaK() -> Incompressible: ...
    @staticmethod
    def PBB() -> Incompressible: ...
    @staticmethod
    def PCL() -> Incompressible: ...
    @staticmethod
    def PCR() -> Incompressible: ...
    @staticmethod
    def PGLT() -> Incompressible: ...
    @staticmethod
    def PHE() -> Incompressible: ...
    @staticmethod
    def PHR() -> Incompressible: ...
    @staticmethod
    def PK2() -> Incompressible: ...
    @staticmethod
    def PKL() -> Incompressible: ...
    @staticmethod
    def PLR() -> Incompressible: ...
    @staticmethod
    def PMR() -> Incompressible: ...
    @staticmethod
    def PMS1() -> Incompressible: ...
    @staticmethod
    def PMS2() -> Incompressible: ...
    @staticmethod
    def PNF() -> Incompressible: ...
    @staticmethod
    def PNF2() -> Incompressible: ...
    @staticmethod
    def S800() -> Incompressible: ...
    @staticmethod
    def SAB() -> Incompressible: ...
    @staticmethod
    def T66() -> Incompressible: ...
    @staticmethod
    def T72() -> Incompressible: ...
    @staticmethod
    def TCO() -> Incompressible: ...
    @staticmethod
    def TD12() -> Incompressible: ...
    @staticmethod
    def TVP1() -> Incompressible: ...
    @staticmethod
    def TVP1869() -> Incompressible: ...
    @staticmethod
    def TX22() -> Incompressible: ...
    @staticmethod
    def TY10() -> Incompressible: ...
    @staticmethod
    def TY15() -> Incompressible: ...
    @staticmethod
    def TY20() -> Incompressible: ...
    @staticmethod
    def TY24() -> Incompressible: ...
    @staticmethod
    def VCA() -> Incompressible: ...
    @staticmethod
    def VKC() -> Incompressible: ...
    @staticmethod
    def VMA() -> Incompressible: ...
    @staticmethod
    def VMG() -> Incompressible: ...
    @staticmethod
    def VNA() -> Incompressible: ...
    @staticmethod
    def Water() -> Incompressible: ...
    @staticmethod
    def XLT() -> Incompressible: ...
    @staticmethod
    def XLT2() -> Incompressible: ...
    @staticmethod
    def ZAC() -> Incompressible: ...
    @staticmethod
    def ZFC() -> Incompressible: ...
    @staticmethod
    def ZLC() -> Incompressible: ...
    @staticmethod
    def ZM() -> Incompressible: ...
    @staticmethod
    def ZMC() -> Incompressible: ...
    @staticmethod
    def ZS10() -> Incompressible: ...
    @staticmethod
    def ZS25() -> Incompressible: ...
    @staticmethod
    def ZS40() -> Incompressible: ...
    @staticmethod
    def ZS45() -> Incompressible: ...
    @staticmethod
    def ZS55() -> Incompressible: ...
    def variant(self) -> str: ...

class IncompressibleError:
    @staticmethod
    def OutOfRange() -> IncompressibleError: ...
    @staticmethod
    def CompositionMismatch() -> IncompressibleError: ...
    @staticmethod
    def PropertyUnavailable() -> IncompressibleError: ...
    def variant(self) -> str: ...

class IncompressibleFluid:
    name: str
    kind: IncompressibleKind
    t_range: tuple[float, float]
    x_range: tuple[float, float]
    t_base: float
    x_base: float
    density: PropertyFit
    heat_capacity: PropertyFit
    conductivity: PropertyFit | None
    viscosity: PropertyFit | None
    t_freeze: PropertyFit | None
    p_sat: PropertyFit | None
    t_min_psat: float

class IncompressibleKind:
    @staticmethod
    def Pure() -> IncompressibleKind: ...
    @staticmethod
    def MassBased() -> IncompressibleKind: ...
    @staticmethod
    def VolumeBased() -> IncompressibleKind: ...
    def variant(self) -> str: ...

class PropertyFit:
    form: PropertyForm
    coeffs: list[list[float]]

class PropertyForm:
    @staticmethod
    def Polynomial() -> PropertyForm: ...
    @staticmethod
    def ExpPolynomial() -> PropertyForm: ...
    @staticmethod
    def Exponential() -> PropertyForm: ...
    @staticmethod
    def LogExponential() -> PropertyForm: ...
    def variant(self) -> str: ...

class Mixture:
    components: list[Fluid]
    mole_fractions: list[float]
    @staticmethod
    def air() -> Mixture: ...
    @staticmethod
    def r410a() -> Mixture: ...
    def __init__(self, components: list[Fluid], mole_fractions: list[float]) -> None: ...
    def reducing_temperature(self) -> float: ...
    def reducing_density(self) -> float: ...
    def residual_derivs(self, delta: float, tau: float) -> HelmholtzDerivs: ...
    def state_trho_molar(self, t: float, rho_molar: float) -> MixtureState: ...

class MixtureError:
    @staticmethod
    def MalformedComposition() -> MixtureError: ...
    @staticmethod
    def InvalidMoleFraction() -> MixtureError: ...
    @staticmethod
    def UnnormalizedComposition() -> MixtureError: ...
    @staticmethod
    def MissingBinaryPair() -> MixtureError: ...
    @staticmethod
    def NonConvergent() -> MixtureError: ...
    def variant(self) -> str: ...

class MixtureState:
    temperature: float
    rho_molar: float
    pressure: float
    internal_energy: float
    enthalpy: float
    entropy: float
    cv: float
    cp: float
    speed_of_sound: float
    def __init__(self, temperature: float, rho_molar: float, pressure: float, internal_energy: float, enthalpy: float, entropy: float, cv: float, cp: float, speed_of_sound: float) -> None: ...

class BinaryPair:
    a: Fluid
    b: Fluid
    beta_gamma_t: tuple[float, float]
    beta_gamma_v: tuple[float, float]
    f_departure: float
    departure_terms: list[DepartureTerm]

class DepartureTerm:
    @staticmethod
    def Power(n: float, d: float, t: float, l: float) -> DepartureTerm: ...
    @staticmethod
    def Gaussian(n: float, d: float, t: float, eta: float, epsilon: float, beta: float, gamma: float) -> DepartureTerm: ...
    @staticmethod
    def GergExponential(n: float, d: float, t: float, eta: float, epsilon: float, beta: float, gamma: float) -> DepartureTerm: ...
    def variant(self) -> str: ...

class EnergyBalanceMode:
    @staticmethod
    def Explicit() -> EnergyBalanceMode: ...
    @staticmethod
    def Implicit() -> EnergyBalanceMode: ...
    def variant(self) -> str: ...
    @staticmethod
    def default() -> EnergyBalanceMode: ...

class EnergyConvectionScheme:
    @staticmethod
    def VanLeer() -> EnergyConvectionScheme: ...
    @staticmethod
    def Minmod() -> EnergyConvectionScheme: ...
    @staticmethod
    def Upwind() -> EnergyConvectionScheme: ...
    @staticmethod
    def Linear() -> EnergyConvectionScheme: ...
    def variant(self) -> str: ...
    @staticmethod
    def default() -> EnergyConvectionScheme: ...

class SolverMode:
    @staticmethod
    def Pimple() -> SolverMode: ...
    @staticmethod
    def HybridAllMach() -> SolverMode: ...
    def variant(self) -> str: ...
    @staticmethod
    def default() -> SolverMode: ...

class ConductivityDilute:
    @staticmethod
    def CO2HuberJPCRD2016() -> ConductivityDilute: ...
    @staticmethod
    def EthaneHardcoded() -> ConductivityDilute: ...
    def variant(self) -> str: ...

class ConductivityModel:
    @staticmethod
    def Correlation(dilute: ConductivityDilute, residual: ConductivityResidual, critical: CriticalConductivity | None) -> ConductivityModel: ...
    @staticmethod
    def Hardcoded(a0: HardcodedConductivity) -> ConductivityModel: ...
    def variant(self) -> str: ...

class ConductivityResidual:
    def variant(self) -> str: ...

class CriticalConductivity:
    @staticmethod
    def SimplifiedOlchowySengers(r0: float, gamma: float, big_gamma: float, zeta0: float, qd: float, t_ref: float) -> CriticalConductivity: ...
    @staticmethod
    def R123() -> CriticalConductivity: ...
    @staticmethod
    def Ammonia() -> CriticalConductivity: ...
    def variant(self) -> str: ...

class HardcodedConductivity:
    @staticmethod
    def Helium() -> HardcodedConductivity: ...
    @staticmethod
    def Water() -> HardcodedConductivity: ...
    @staticmethod
    def HeavyWater() -> HardcodedConductivity: ...
    @staticmethod
    def R23(molar_mass: float) -> HardcodedConductivity: ...
    @staticmethod
    def Methane() -> HardcodedConductivity: ...
    def variant(self) -> str: ...

class HardcodedViscosity:
    @staticmethod
    def Helium() -> HardcodedViscosity: ...
    @staticmethod
    def Water() -> HardcodedViscosity: ...
    @staticmethod
    def HeavyWater() -> HardcodedViscosity: ...
    @staticmethod
    def OXylene(molar_mass: float) -> HardcodedViscosity: ...
    @staticmethod
    def MXylene(molar_mass: float) -> HardcodedViscosity: ...
    @staticmethod
    def PXylene(molar_mass: float) -> HardcodedViscosity: ...
    @staticmethod
    def R23(molar_mass: float) -> HardcodedViscosity: ...
    @staticmethod
    def Methanol(molar_mass: float) -> HardcodedViscosity: ...
    def variant(self) -> str: ...

class ViscosityDilute:
    @staticmethod
    def CO2LaeseckeJPCRD2017() -> ViscosityDilute: ...
    @staticmethod
    def Ethane() -> ViscosityDilute: ...
    @staticmethod
    def Cyclohexane() -> ViscosityDilute: ...
    @staticmethod
    def KineticTheory(molar_mass: float, epsilon_over_k: float, sigma_eta: float) -> ViscosityDilute: ...
    def variant(self) -> str: ...

class ViscosityHigherOrder:
    @staticmethod
    def CO2LaeseckeJPCRD2017(ttriple: float, gas_constant: float, molar_mass: float) -> ViscosityHigherOrder: ...
    @staticmethod
    def Hydrogen(molar_mass: float) -> ViscosityHigherOrder: ...
    @staticmethod
    def Toluene(molar_mass: float) -> ViscosityHigherOrder: ...
    @staticmethod
    def Benzene(molar_mass: float) -> ViscosityHigherOrder: ...
    @staticmethod
    def Hexane(molar_mass: float) -> ViscosityHigherOrder: ...
    @staticmethod
    def Heptane(molar_mass: float) -> ViscosityHigherOrder: ...
    @staticmethod
    def Ethane() -> ViscosityHigherOrder: ...
    def variant(self) -> str: ...

class ViscosityInitial:
    def variant(self) -> str: ...

class ViscosityModel:
    def eval(self, fluid: Fluid, t: float, rho: float) -> float: ...
    @staticmethod
    def Correlation(dilute: ViscosityDilute, initial: ViscosityInitial | None, higher_order: ViscosityHigherOrder) -> ViscosityModel: ...
    @staticmethod
    def Hardcoded(a0: HardcodedViscosity) -> ViscosityModel: ...
    @staticmethod
    def Chung(dipole_moment_d: float) -> ViscosityModel: ...
    def variant(self) -> str: ...

class CorrStatesModel:
    @staticmethod
    def Chung() -> CorrStatesModel: ...
    @staticmethod
    def Ecs() -> CorrStatesModel: ...
    @staticmethod
    def RhosrCs() -> CorrStatesModel: ...
    def variant(self) -> str: ...

def saturated_liquid_density_ancillary(fluid: Fluid, t: float) -> float | None: ...
def saturated_vapour_density_ancillary(fluid: Fluid, t: float) -> float | None: ...
def saturation_pressure_ancillary(fluid: Fluid, t: float) -> float | None: ...
def conductivity(fluid: Fluid, t: float, rho: float) -> float | None: ...
def density_pt(fluid: Fluid, t: float, p: float) -> float: ...
def drho_dp_t(fluid: Fluid, t: float, rho: float) -> float: ...
def state_hrho(fluid: Fluid, rho: float, h: float) -> FluidState: ...
def temperature_hrho(fluid: Fluid, rho: float, h: float) -> float: ...
def enhancement_factor(t: float, p: float) -> float: ...
def henry_constant(t: float) -> float: ...
def p_ws(t: float) -> float: ...
def b_aa(t: float) -> float: ...
def b_aw(t: float) -> float: ...
def b_mix(t: float, psi_w: float) -> float: ...
def b_ww(t: float) -> float: ...
def c_aaa(t: float) -> float: ...
def c_aaw(t: float) -> float: ...
def c_aww(t: float) -> float: ...
def c_mix(t: float, psi_w: float) -> float: ...
def c_www(t: float) -> float: ...
def d_b_mix_dt(t: float, psi_w: float) -> float: ...
def d_c_mix_dt(t: float, psi_w: float) -> float: ...
def lookup(a: Fluid, b: Fluid) -> BinaryPair | None: ...
def reducing_density(mix: Mixture) -> float: ...
def reducing_temperature(mix: Mixture) -> float: ...
def phase_at_ph(fluid: Fluid, p: float, h: float) -> PhaseAtPh: ...
def pressure_trho(fluid: Fluid, t: float, rho: float) -> float: ...
def saturation_at_temperature(fluid: Fluid, t: float) -> SaturationState | None: ...
def saturation_temperature(fluid: Fluid, p: float) -> float | None: ...
def state_ph(fluid: Fluid, p: float, h: float) -> FluidState: ...
def state_ps(fluid: Fluid, p: float, s: float) -> FluidState: ...
def state_pt(fluid: Fluid, t: float, p: float) -> FluidState: ...
def state_trho(fluid: Fluid, t: float, rho: float) -> FluidState: ...
def corresponding_states_viscosity(fluid: Fluid, t: float, rho: float) -> float | None: ...
def viscosity(fluid: Fluid, t: float, rho: float) -> float | None: ...
