"""Type stubs for `outram_park.outram_park_digital_twin_engine`, generated from the Rust API.

Physical quantities cross this boundary as `float` in SI base units.
"""

class ControlRodDrive:
    def __init__(self, initial_insertion_fraction: float, stroke: float, speed: float) -> None: ...
    @staticmethod
    def htr10(initial_insertion_fraction: float) -> ControlRodDrive: ...
    def insertion_fraction(self) -> float: ...
    def motion(self) -> RodDriveMotion: ...
    def advance(self, commanded: float, dt: float) -> None: ...
    def snap_to(self, fraction: float) -> None: ...
    def fraction_per_second(self) -> float: ...

class FlowDirection:
    @staticmethod
    def Forward() -> FlowDirection: ...
    @staticmethod
    def Reverse() -> FlowDirection: ...
    @staticmethod
    def Stagnant() -> FlowDirection: ...
    def variant(self) -> str: ...

class RodDriveMotion:
    @staticmethod
    def Inserting() -> RodDriveMotion: ...
    @staticmethod
    def Withdrawing() -> RodDriveMotion: ...
    @staticmethod
    def AtRest() -> RodDriveMotion: ...
    def variant(self) -> str: ...

class TracerPulse:
    def __init__(self, min_interval: float) -> None: ...
    def advance(self, dt: float, residence_time: float, mass_flow: float) -> None: ...
    def position(self, residence_time: float) -> float | None: ...
    def direction(self) -> FlowDirection: ...

class TracerTrain:
    def __init__(self, count: int) -> None: ...
    def advance(self, dt: float, residence_time: float, mass_flow: float) -> None: ...
    def phase(self) -> float: ...
    def count(self) -> int: ...
    def direction(self) -> FlowDirection: ...

class CrashModalOutcome:
    def is_crashed(self) -> bool: ...
    @staticmethod
    def Healthy() -> CrashModalOutcome: ...
    @staticmethod
    def Showing() -> CrashModalOutcome: ...
    @staticmethod
    def RestartRequested() -> CrashModalOutcome: ...
    def variant(self) -> str: ...

class CrashReport:
    thread_name: str
    message: str
    location: str | None
    component: str | None
    def summary(self) -> str: ...

class CsvLogger:
    def path(self) -> str: ...

class CsvLoggerError:
    def variant(self) -> str: ...

class CsvSnapshotPanel:
    def __init__(self, ) -> None: ...
    def display_interval_seconds(self) -> float: ...
    @staticmethod
    def default() -> CsvSnapshotPanel: ...

class GuiFrameMetrics:
    def begin_frame(self) -> None: ...
    def update_cpu_time_ms(self) -> float: ...
    def peak_update_cpu_time_ms(self) -> float: ...
    def frame_interval_ms(self) -> float: ...
    def frames_per_second(self) -> float: ...
    @staticmethod
    def default() -> GuiFrameMetrics: ...

class RealTimePacer:
    def set_simulated_per_tick(self, simulated_per_tick: float) -> None: ...
    def measured_real_time_ratio(self) -> float | None: ...
    def is_behind_real_time(self) -> bool: ...

class ThreadHealth:
    def __init__(self, ) -> None: ...
    def has_crashed(self) -> bool: ...
    def is_running(self) -> bool: ...
    def retire(self) -> None: ...
    def crash_report(self) -> CrashReport | None: ...
    @staticmethod
    def default() -> ThreadHealth: ...

class TickPacing:
    ahead_of_real_time: bool
    def is_over_budget(self) -> bool: ...

class CietControl:
    def index(self) -> int: ...
    def node_identifier(self) -> str: ...
    def browse_name(self) -> str: ...
    def display_name(self) -> str: ...
    def unit(self) -> str: ...
    def valid_range(self) -> tuple[float, float]: ...
    def read(self, state: CietState) -> float: ...
    @staticmethod
    def HeaterPowerKw() -> CietControl: ...
    @staticmethod
    def CtahPumpPressurePascals() -> CietControl: ...
    @staticmethod
    def Bt41CtahOutletSetPointDegC() -> CietControl: ...
    @staticmethod
    def Bt66TchxOutletSetPointDegC() -> CietControl: ...
    @staticmethod
    def HeaterSteadyStatePowerKw() -> CietControl: ...
    @staticmethod
    def FrequencyResponseAmplitudeKw() -> CietControl: ...
    @staticmethod
    def FrequencyResponseAngularVelocityRadPerS() -> CietControl: ...
    @staticmethod
    def TimestepSeconds() -> CietControl: ...
    def variant(self) -> str: ...

class CietNode:
    @staticmethod
    def Signal(a0: CietSignal) -> CietNode: ...
    @staticmethod
    def Control(a0: CietControl) -> CietNode: ...
    @staticmethod
    def Switch(a0: CietSwitch) -> CietNode: ...
    def variant(self) -> str: ...

class CietSignal:
    def node_identifier(self) -> str: ...
    def browse_name(self) -> str: ...
    def display_name(self) -> str: ...
    def unit(self) -> str: ...
    def read(self, state: CietState) -> float: ...
    @staticmethod
    def HeaterPowerKw() -> CietSignal: ...
    @staticmethod
    def Bt11HeaterInletDegC() -> CietSignal: ...
    @staticmethod
    def Bt12HeaterOutletDegC() -> CietSignal: ...
    @staticmethod
    def Bt43CtahInletDegC() -> CietSignal: ...
    @staticmethod
    def Bt41CtahOutletDegC() -> CietSignal: ...
    @staticmethod
    def Bt60DhxTubeInletDegC() -> CietSignal: ...
    @staticmethod
    def Bt21DhxTubeOutletDegC() -> CietSignal: ...
    @staticmethod
    def Bt21DhxShellInletDegC() -> CietSignal: ...
    @staticmethod
    def Bt27DhxShellOutletDegC() -> CietSignal: ...
    @staticmethod
    def Bt65TchxInletDegC() -> CietSignal: ...
    @staticmethod
    def Bt66TchxOutletDegC() -> CietSignal: ...
    @staticmethod
    def Fm40CtahBranchKgPerS() -> CietSignal: ...
    @staticmethod
    def Fm20DhxBranchKgPerS() -> CietSignal: ...
    @staticmethod
    def Fm60DracsKgPerS() -> CietSignal: ...
    @staticmethod
    def CtahHtcWattPerM2K() -> CietSignal: ...
    @staticmethod
    def TchxHtcWattPerM2K() -> CietSignal: ...
    @staticmethod
    def TopMixingNodeDegC() -> CietSignal: ...
    @staticmethod
    def BottomMixingNodeDegC() -> CietSignal: ...
    @staticmethod
    def SimulationTimeSeconds() -> CietSignal: ...
    @staticmethod
    def ElapsedTimeSeconds() -> CietSignal: ...
    @staticmethod
    def CalcTimeMs() -> CietSignal: ...
    def variant(self) -> str: ...

class CietState:
    simulation_time_seconds: float
    elapsed_time_seconds: float
    calc_time_ms: float
    heater_power_kilowatts: float
    ctah_pump_temp_degc: float
    bt_41_ctah_outlet_set_pt_deg_c: float
    bt_66_tchx_outlet_set_pt_deg_c: float
    pipe_18_temp_degc: float
    pipe_1a_temp_degc: float
    bt_11_heater_inlet_deg_c: float
    bt_12_heater_outlet_deg_c: float
    pipe_1b_temp_degc: float
    pipe_2a_temp_degc: float
    pipe_2_temp_degc: float
    pipe_3_temp_degc: float
    pipe_4_temp_degc: float
    pipe_5a_temp_degc: float
    pipe_26_temp_degc: float
    pipe_25_temp_degc: float
    pipe_25a_temp_degc: float
    bt_21_dhx_shell_inlet_deg_c: float
    pipe_23_temp_degc: float
    bt_27_dhx_shell_outlet_deg_c: float
    pipe_23a_temp_degc: float
    pipe_22_temp_degc: float
    fm20_label_21a_temp_degc: float
    fm20_dhx_branch_kg_per_s: float
    pipe_21_temp_degc: float
    pipe_20_temp_degc: float
    pipe_19_temp_degc: float
    pipe_17b_temp_degc: float
    bt_21_dhx_tube_outlet_deg_c: float
    pipe_30b_temp_degc: float
    pipe_31a_temp_degc: float
    pipe_31_temp_degc: float
    pipe_32_temp_degc: float
    pipe_33_temp_degc: float
    pipe_34_temp_degc: float
    bt_65_tchx_inlet_deg_c: float
    bt_66_tchx_outlet_deg_c: float
    tchx_htc_watt_per_m2_kelvin: float
    pipe_36a_temp_degc: float
    pipe_36_temp_degc: float
    pipe_37_temp_degc: float
    fm_60_dracs_kg_per_s: float
    fm60_label_37a_temp_degc: float
    pipe_38_temp_degc: float
    pipe_39_temp_degc: float
    pipe_30a_temp_degc: float
    bt_60_dhx_tube_inlet_deg_c: float
    pipe_5b_temp_degc: float
    pipe_6a_temp_degc: float
    pipe_6_temp_degc: float
    bt_43_ctah_inlet_deg_c: float
    bt_41_ctah_outlet_deg_c: float
    ctah_htc_watt_per_m2_kelvin: float
    pipe_8a_temp_degc: float
    pipe_8_temp_degc: float
    pipe_9_temp_degc: float
    pipe_10_temp_degc: float
    pipe_11_temp_degc: float
    pipe_12_temp_degc: float
    pipe_13_temp_degc: float
    pipe_14_temp_degc: float
    fm40_label_14a_temp_degc: float
    fm40_ctah_branch_kg_per_s: float
    pipe_15_temp_degc: float
    pipe_16_temp_degc: float
    pipe_17a_temp_degc: float
    top_mixing_node_5a_5b_4_temp_degc: float
    bottom_mixing_node_17a_17b_18_temp_degc: float
    timestep_seconds: float
    fast_forward_settings_turned_on: bool
    slow_motion_settings_turned_on: bool
    ctah_pump_pressure_pascals: float
    is_ctah_branch_blocked: bool
    is_dhx_branch_blocked: bool
    current_heater_type: HeaterType
    heater_control: HeaterControlSettings
    def overwrite_state(self, ciet_state: CietState) -> None: ...
    def get_heater_outlet_temp_degc(self) -> float: ...
    def get_heater_inlet_temp_degc(self) -> float: ...
    def get_dhx_shell_outlet_temp_degc(self) -> float: ...
    def get_dhx_shell_inlet_temp_degc(self) -> float: ...
    def get_dhx_tube_outlet_temp_degc(self) -> float: ...
    def get_dhx_tube_inlet_temp_degc(self) -> float: ...
    def get_tchx_outlet_temp_degc(self) -> float: ...
    def get_tchx_inlet_temp_degc(self) -> float: ...
    def get_ctah_outlet_temp_degc(self) -> float: ...
    def get_ctah_inlet_temp_degc(self) -> float: ...
    def is_fast_fwd_on(self) -> bool: ...
    def get_ctah_pump_pressure_f64(self) -> float: ...
    def __init__(self, simulation_time_seconds: float, elapsed_time_seconds: float, calc_time_ms: float, heater_power_kilowatts: float, ctah_pump_temp_degc: float, bt_41_ctah_outlet_set_pt_deg_c: float, bt_66_tchx_outlet_set_pt_deg_c: float, pipe_18_temp_degc: float, pipe_1a_temp_degc: float, bt_11_heater_inlet_deg_c: float, bt_12_heater_outlet_deg_c: float, pipe_1b_temp_degc: float, pipe_2a_temp_degc: float, pipe_2_temp_degc: float, pipe_3_temp_degc: float, pipe_4_temp_degc: float, pipe_5a_temp_degc: float, pipe_26_temp_degc: float, pipe_25_temp_degc: float, pipe_25a_temp_degc: float, bt_21_dhx_shell_inlet_deg_c: float, pipe_23_temp_degc: float, bt_27_dhx_shell_outlet_deg_c: float, pipe_23a_temp_degc: float, pipe_22_temp_degc: float, fm20_label_21a_temp_degc: float, fm20_dhx_branch_kg_per_s: float, pipe_21_temp_degc: float, pipe_20_temp_degc: float, pipe_19_temp_degc: float, pipe_17b_temp_degc: float, bt_21_dhx_tube_outlet_deg_c: float, pipe_30b_temp_degc: float, pipe_31a_temp_degc: float, pipe_31_temp_degc: float, pipe_32_temp_degc: float, pipe_33_temp_degc: float, pipe_34_temp_degc: float, bt_65_tchx_inlet_deg_c: float, bt_66_tchx_outlet_deg_c: float, tchx_htc_watt_per_m2_kelvin: float, pipe_36a_temp_degc: float, pipe_36_temp_degc: float, pipe_37_temp_degc: float, fm_60_dracs_kg_per_s: float, fm60_label_37a_temp_degc: float, pipe_38_temp_degc: float, pipe_39_temp_degc: float, pipe_30a_temp_degc: float, bt_60_dhx_tube_inlet_deg_c: float, pipe_5b_temp_degc: float, pipe_6a_temp_degc: float, pipe_6_temp_degc: float, bt_43_ctah_inlet_deg_c: float, bt_41_ctah_outlet_deg_c: float, ctah_htc_watt_per_m2_kelvin: float, pipe_8a_temp_degc: float, pipe_8_temp_degc: float, pipe_9_temp_degc: float, pipe_10_temp_degc: float, pipe_11_temp_degc: float, pipe_12_temp_degc: float, pipe_13_temp_degc: float, pipe_14_temp_degc: float, fm40_label_14a_temp_degc: float, fm40_ctah_branch_kg_per_s: float, pipe_15_temp_degc: float, pipe_16_temp_degc: float, pipe_17a_temp_degc: float, top_mixing_node_5a_5b_4_temp_degc: float, bottom_mixing_node_17a_17b_18_temp_degc: float, timestep_seconds: float, fast_forward_settings_turned_on: bool, slow_motion_settings_turned_on: bool, ctah_pump_pressure_pascals: float, is_ctah_branch_blocked: bool, is_dhx_branch_blocked: bool, current_heater_type: HeaterType, heater_control: HeaterControlSettings) -> None: ...
    @staticmethod
    def default() -> CietState: ...

class CietSwitch:
    def index(self) -> int: ...
    def node_identifier(self) -> str: ...
    def browse_name(self) -> str: ...
    def display_name(self) -> str: ...
    def read(self, state: CietState) -> bool: ...
    @staticmethod
    def AdvancedHeaterControlOn() -> CietSwitch: ...
    @staticmethod
    def FrequencyResponseOn() -> CietSwitch: ...
    @staticmethod
    def CtahBranchBlocked() -> CietSwitch: ...
    @staticmethod
    def DhxBranchBlocked() -> CietSwitch: ...
    @staticmethod
    def FastForwardOn() -> CietSwitch: ...
    @staticmethod
    def SlowMotionOn() -> CietSwitch: ...
    @staticmethod
    def CoarseHeaterMesh() -> CietSwitch: ...
    def variant(self) -> str: ...

class HeaterControlSettings:
    advanced_heater_control_switched_on: bool
    frequency_response_switched_on: bool
    steady_state_power_kw: float
    total_amplitude_kw: float
    angular_velocity_rad_per_s: float
    def demanded_power(self, current_sim_time: float) -> float: ...
    def sine_wave_label(self) -> str: ...
    def __init__(self, advanced_heater_control_switched_on: bool, frequency_response_switched_on: bool, steady_state_power_kw: float, total_amplitude_kw: float, angular_velocity_rad_per_s: float) -> None: ...
    @staticmethod
    def default() -> HeaterControlSettings: ...

class HeaterType:
    def axial_node_count(self) -> int: ...
    @staticmethod
    def InsulatedHeaterV1Fine15Mesh() -> HeaterType: ...
    @staticmethod
    def InsulatedHeaterV1Coarse8Mesh() -> HeaterType: ...
    def variant(self) -> str: ...

class CietUserControls:
    def __init__(self, ) -> None: ...
    def request_control(self, control: CietControl, value: float) -> None: ...
    def request_switch(self, switch: CietSwitch, value: bool) -> None: ...
    def pending_control(self, control: CietControl) -> float | None: ...
    def pending_switch(self, switch: CietSwitch) -> bool | None: ...
    def has_pending_requests(self) -> bool: ...
    def applied_request_count(self) -> int: ...
    def clear_without_applying(self) -> None: ...
    @staticmethod
    def default() -> CietUserControls: ...

class ApproachVerdict:
    @staticmethod
    def Feasible() -> ApproachVerdict: ...
    @staticmethod
    def TemperatureCross() -> ApproachVerdict: ...
    @staticmethod
    def Impossible() -> ApproachVerdict: ...
    def variant(self) -> str: ...

class CondenserDisplayRange:
    min_temp: float
    max_temp: float
    def __init__(self, min_temp: float, max_temp: float) -> None: ...

class CondenserKind:
    def label(self) -> str: ...
    def description(self) -> str: ...
    def cooling_water_path(self) -> str: ...
    def passes(self) -> int: ...
    def native_aspect_ratio(self) -> float: ...
    @staticmethod
    def TwoPass() -> CondenserKind: ...
    @staticmethod
    def SinglePass() -> CondenserKind: ...
    def variant(self) -> str: ...

class CondenserScalars:
    exhaust_quality: float
    condensing_temp: float
    condensate_temp: float
    cooling_water_inlet_temp: float
    cooling_water_outlet_temp: float
    hotwell_level_frac: float | None
    def __init__(self, exhaust_quality: float, condensing_temp: float, condensate_temp: float, cooling_water_inlet_temp: float, cooling_water_outlet_temp: float, hotwell_level_frac: float | None) -> None: ...

class CondenserVisual:
    def kind(self) -> CondenserKind: ...
    def state(self) -> CondenserVisualState: ...
    def scalars(self) -> CondenserScalars | None: ...
    def operating_pressure(self) -> float | None: ...
    def target_outlet_quality(self) -> float | None: ...

class CondenserVisualState:
    @staticmethod
    def Scalars(a0: CondenserScalars, a1: CondenserDisplayRange) -> CondenserVisualState: ...
    def variant(self) -> str: ...

class CoolingTowerVisual:
    def kind(self) -> CoolingTowerKind: ...
    def state(self) -> CoolingTowerVisualState: ...
    def scalars(self) -> CoolingTowerScalars | None: ...
    def fan_angle(self) -> float | None: ...
    def approach(self) -> float | None: ...
    def target_approach(self) -> float | None: ...
    def cooling_range(self) -> float | None: ...

class ExcursionOverlay:
    def trigger(self) -> ExcursionTrigger: ...
    def intensity(self) -> float: ...
    def stage(self) -> ExcursionStage: ...
    def phase(self) -> float: ...
    def overshoot_kelvin(self) -> float | None: ...
    def named_species(self) -> list[ReleaseSpecies]: ...

class ExcursionStage:
    @staticmethod
    def from_intensity(intensity: float) -> ExcursionStage: ...
    def is_drawn(self) -> bool: ...
    def label(self) -> str: ...
    def caption(self) -> str: ...
    def mechanism(self) -> str: ...
    @staticmethod
    def Quiescent() -> ExcursionStage: ...
    @staticmethod
    def LimitExceeded() -> ExcursionStage: ...
    @staticmethod
    def FissionProductRelease() -> ExcursionStage: ...
    def variant(self) -> str: ...

class ExcursionTrigger:
    @staticmethod
    def htr10_fuel_temperature(fuel: float) -> ExcursionTrigger: ...
    def intensity(self) -> float: ...
    def fuel_temperature(self) -> float | None: ...
    def limit(self) -> float | None: ...
    @staticmethod
    def Intensity(a0: float) -> ExcursionTrigger: ...
    @staticmethod
    def FuelTemperature(fuel: float, limit: float, full_intensity_at: float) -> ExcursionTrigger: ...
    def variant(self) -> str: ...

class FhrReactorVesselVisual:
    def hotness(self, temp: float) -> float: ...
    def set_min_temp(self, min_temp: float) -> None: ...
    def set_max_temp(self, max_temp: float) -> None: ...
    def set_left_cr_frac(self, left_control_rod_insertion_frac: float) -> None: ...
    def set_right_cr_frac(self, right_control_rod_insertion_frac: float) -> None: ...

class HeatExchangerConstruction:
    def label(self) -> str: ...
    def description(self) -> str: ...
    def hot_stream_location(self) -> str: ...
    def native_aspect_ratio(self) -> float: ...
    @staticmethod
    def ShellAndTube() -> HeatExchangerConstruction: ...
    @staticmethod
    def PlateFrame() -> HeatExchangerConstruction: ...
    def variant(self) -> str: ...

class HeatExchangerDisplayRange:
    min_temp: float
    max_temp: float
    def __init__(self, min_temp: float, max_temp: float) -> None: ...

class HeatExchangerKind:
    def label(self) -> str: ...
    def description(self) -> str: ...
    def cold_stream_path(self) -> str: ...
    def permits_temperature_cross(self) -> bool: ...
    def cold_stream_direction(self) -> float: ...
    @staticmethod
    def CounterFlow() -> HeatExchangerKind: ...
    @staticmethod
    def ParallelFlow() -> HeatExchangerKind: ...
    def variant(self) -> str: ...

class HeatExchangerScalars:
    hot_inlet_temp: float
    hot_outlet_temp: float
    cold_inlet_temp: float
    cold_outlet_temp: float
    duty: float | None
    def __init__(self, hot_inlet_temp: float, hot_outlet_temp: float, cold_inlet_temp: float, cold_outlet_temp: float, duty: float | None) -> None: ...

class HeatExchangerVisual:
    def kind(self) -> HeatExchangerKind: ...
    def construction(self) -> HeatExchangerConstruction: ...
    def state(self) -> HeatExchangerVisualState: ...
    def scalars(self) -> HeatExchangerScalars | None: ...
    def heat_transfer_area(self) -> float | None: ...
    def overall_coefficient(self) -> float | None: ...
    def duty(self) -> float | None: ...
    def approaches(self) -> tuple[float, float] | None: ...
    def verdict(self) -> ApproachVerdict | None: ...

class HeatExchangerVisualState:
    @staticmethod
    def Scalars(a0: HeatExchangerScalars, a1: HeatExchangerDisplayRange) -> HeatExchangerVisualState: ...
    def variant(self) -> str: ...

class Htr10ReactorVesselVisual:
    def set_control_rod_frac(self, frac: float) -> None: ...

class InstrumentationVisual:
    label: str
    value: str

class LegendUnit:
    @staticmethod
    def Kelvin() -> LegendUnit: ...
    @staticmethod
    def Celsius() -> LegendUnit: ...
    def variant(self) -> str: ...
    @staticmethod
    def default() -> LegendUnit: ...

class PipeBendVisual:
    thickness: float
    upstream_temperature: float
    downstream_temperature: float
    min_temp: float
    max_temp: float
    shade: PipePhaseShade
    turn_sense: TurnSense
    sweep_override: float | None
    def mean_temperature(self) -> float: ...
    def signed_sweep(self) -> float: ...
    def turn_angle(self) -> float: ...

class PipeComponent:
    min_temp: float
    max_temp: float
    scale: PipeScale
    wall_alarm_temp: float | None
    tracer: TracerPulse
    velocity: float
    def residence_time(self) -> float: ...

class PipePhaseShade:
    @staticmethod
    def Liquid() -> PipePhaseShade: ...
    @staticmethod
    def Gas() -> PipePhaseShade: ...
    @staticmethod
    def TwoPhase() -> PipePhaseShade: ...
    def variant(self) -> str: ...

class PipeScalars:
    temperature: float
    mass_flow: float
    residence_time: float
    def __init__(self, temperature: float, mass_flow: float, residence_time: float) -> None: ...

class PipeScale:
    points_per_metre: float
    points_per_square_metre: float
    min_thickness_points: float
    def __init__(self, points_per_metre: float, points_per_square_metre: float, min_thickness_points: float) -> None: ...
    @staticmethod
    def default() -> PipeScale: ...

class PipeVisual:
    state: PipeVisualState
    min_temp: float
    max_temp: float
    scale: PipeScale
    wall_alarm_temp: float | None
    mark_at: float | None
    tracer: TracerTrain | None
    def cross_sectional_area(self) -> float | None: ...
    def run_length(self) -> float | None: ...
    def inclination(self) -> float | None: ...
    def wall_temperatures(self) -> list[float] | None: ...
    def peak_wall_temperature(self) -> float | None: ...
    def phase_shade(self) -> PipePhaseShade: ...
    def drawn_size(self) -> tuple[float, float]: ...
    def cell_temperatures(self) -> list[float]: ...

class PipeVisualState:
    @staticmethod
    def Scalars(a0: PipeScalars) -> PipeVisualState: ...
    def variant(self) -> str: ...

class PumpVisual:
    kind: PumpKind
    shaft_speed: float
    simulation_time: float
    fluid_temperature: float | None
    min_temp: float
    max_temp: float
    def rotor_angle(self) -> float: ...
    def is_turning(self) -> bool: ...

class ReactorArchetype:
    def label(self) -> str: ...
    def description(self) -> str: ...
    def coolant(self) -> str: ...
    def secondary(self) -> str: ...
    def approximate_thermal_power_mw(self) -> float: ...
    def scoping_doc(self) -> str: ...
    @staticmethod
    def Htr10() -> ReactorArchetype: ...
    @staticmethod
    def Msre() -> ReactorArchetype: ...
    @staticmethod
    def IntegralPwr() -> ReactorArchetype: ...
    @staticmethod
    def Bwr() -> ReactorArchetype: ...
    @staticmethod
    def Fhr() -> ReactorArchetype: ...
    @staticmethod
    def EbrII() -> ReactorArchetype: ...
    def variant(self) -> str: ...

class ReactorArchetypeVisual:
    archetype: ReactorArchetype
    min_temp: float
    max_temp: float
    core_temp: float
    inlet_temp: float
    outlet_temp: float
    control_rod_insertion_frac: float
    show_labels: bool

class ReactorVesselVisual:
    min_temp: float
    max_temp: float

class StageAngles:
    stator_deg: float
    rotor_deg: float
    reaction: float
    def __init__(self, stator_deg: float, rotor_deg: float, reaction: float) -> None: ...

class SteamGeneratorVisual:
    def kind(self) -> SteamGeneratorKind: ...
    def scalars(self) -> SteamGeneratorScalars: ...

class TemperatureLegend:
    min_temp: float
    max_temp: float
    ticks: int
    unit: LegendUnit
    caption: str | None
    def __init__(self, min_temp: float, max_temp: float) -> None: ...

class TurbineFlowPath:
    @staticmethod
    def DoubleFlow() -> TurbineFlowPath: ...
    @staticmethod
    def SingleFlow() -> TurbineFlowPath: ...
    def variant(self) -> str: ...
    @staticmethod
    def default() -> TurbineFlowPath: ...

class TurbineVisual:
    state: TurbineVisualState
    flow_path: TurbineFlowPath
    simulation_time: float
    min_temp: float
    max_temp: float
    def stage_quality(self, stage_fraction: float) -> float: ...
    def stage_angles(self, stage_fraction: float) -> StageAngles: ...
    def rotor_angle(self) -> float: ...
    def casing_temperature(self) -> float | None: ...

class TurbineVisualState:
    def variant(self) -> str: ...

class TurnSense:
    @staticmethod
    def Auto() -> TurnSense: ...
    @staticmethod
    def Clockwise() -> TurnSense: ...
    @staticmethod
    def Anticlockwise() -> TurnSense: ...
    def variant(self) -> str: ...
    @staticmethod
    def default() -> TurnSense: ...

class CoolingTowerKind:
    def label(self) -> str: ...
    def draught(self) -> str: ...
    def description(self) -> str: ...
    def has_fan(self) -> bool: ...
    def native_aspect_ratio(self) -> float: ...
    @staticmethod
    def NaturalDraught() -> CoolingTowerKind: ...
    @staticmethod
    def InducedDraught() -> CoolingTowerKind: ...
    def variant(self) -> str: ...

class CoolingTowerScalars:
    inlet_wet_bulb: float
    water_inlet_temp: float
    water_outlet_temp: float
    water_flow_rate: float

class CoolingTowerVisualState:
    @staticmethod
    def Scalars(a0: CoolingTowerScalars) -> CoolingTowerVisualState: ...
    def variant(self) -> str: ...

class ReleaseSpecies:
    symbol: str
    nuclide: str
    note: str

class PackedPebble:
    x: float
    y: float
    z: float
    def __init__(self, x: float, y: float, z: float) -> None: ...
    def depth(self) -> float: ...

class PumpKind:
    def native_aspect_ratio(self) -> float: ...
    def label(self) -> str: ...
    def description(self) -> str: ...
    def typical_service(self) -> str: ...
    @staticmethod
    def Centrifugal() -> PumpKind: ...
    @staticmethod
    def VerticalCannedRotor() -> PumpKind: ...
    @staticmethod
    def AxialPropeller() -> PumpKind: ...
    def variant(self) -> str: ...
    @staticmethod
    def default() -> PumpKind: ...

class SteamGeneratorKind:
    def label(self) -> str: ...
    def description(self) -> str: ...
    def circulation(self) -> str: ...
    def has_water_level(self) -> bool: ...
    def native_aspect_ratio(self) -> float: ...
    @staticmethod
    def VerticalUTube() -> SteamGeneratorKind: ...
    @staticmethod
    def HorizontalUTube() -> SteamGeneratorKind: ...
    @staticmethod
    def HelicalCoil() -> SteamGeneratorKind: ...
    def variant(self) -> str: ...

class SteamGeneratorPhysicsState:
    primary_inlet_temp: float
    primary_outlet_temp: float
    feedwater_temp: float
    water_level_frac: float

class SteamGeneratorScalars:
    primary_inlet_temp: float
    primary_outlet_temp: float
    feedwater_temp: float
    steam_temp: float
    water_level_frac: float
    def __init__(self, primary_inlet_temp: float, primary_outlet_temp: float, feedwater_temp: float, steam_temp: float, water_level_frac: float) -> None: ...

class SteamGeneratorVisualState:
    def resolve(self) -> SteamGeneratorScalars: ...
    @staticmethod
    def Scalars(a0: SteamGeneratorScalars) -> SteamGeneratorVisualState: ...
    @staticmethod
    def Physics(a0: SteamGeneratorPhysicsState) -> SteamGeneratorVisualState: ...
    def variant(self) -> str: ...

class Htr10DesignPoint:
    thermal_power: float
    primary_pressure: float
    core_diameter: float
    average_core_height: float
    core_volume: float
    helium_outlet_phase1: float
    helium_inlet_phase1: float
    helium_outlet_phase2: float
    helium_inlet_phase2: float
    helium_mass_flow: float
    main_steam_pressure: float
    main_steam_temperature: float
    feedwater_temperature: float
    main_steam_mass_flow: float
    fuel_element_count: int
    pebble_diameter: float
    fuelled_zone_diameter: float
    graphite_density: float
    heavy_metal_per_ball: float
    enrichment: float
    fuel_kernel_radius: float
    uo2_density: float
    filling_fraction: float
    side_reflector_thickness: float
    rpv_inner_diameter: float
    rpv_height: float
    @staticmethod
    def iaea_benchmark() -> Htr10DesignPoint: ...
    def bed_porosity(self) -> float: ...
    def __init__(self, thermal_power: float, primary_pressure: float, core_diameter: float, average_core_height: float, core_volume: float, helium_outlet_phase1: float, helium_inlet_phase1: float, helium_outlet_phase2: float, helium_inlet_phase2: float, helium_mass_flow: float, main_steam_pressure: float, main_steam_temperature: float, feedwater_temperature: float, main_steam_mass_flow: float, fuel_element_count: int, pebble_diameter: float, fuelled_zone_diameter: float, graphite_density: float, heavy_metal_per_ball: float, enrichment: float, fuel_kernel_radius: float, uo2_density: float, filling_fraction: float, side_reflector_thickness: float, rpv_inner_diameter: float, rpv_height: float) -> None: ...

class Htr10FuelTemperatureLimits:
    max_fuel_temperature_at_120_percent_overload: float
    fuel_temperature_limit: float
    max_bypass_flow_fraction: float
    min_core_flow_fraction: float
    @staticmethod
    def gao_shi_2002() -> Htr10FuelTemperatureLimits: ...
    def __init__(self, max_fuel_temperature_at_120_percent_overload: float, fuel_temperature_limit: float, max_bypass_flow_fraction: float, min_core_flow_fraction: float) -> None: ...

class AccessTier:
    @staticmethod
    def Open() -> AccessTier: ...
    @staticmethod
    def Proprietary() -> AccessTier: ...
    def variant(self) -> str: ...

class BenchmarkProblem:
    @staticmethod
    def B1InitialCriticality() -> BenchmarkProblem: ...
    @staticmethod
    def B21FullCore20C() -> BenchmarkProblem: ...
    @staticmethod
    def B22FullCore120C() -> BenchmarkProblem: ...
    @staticmethod
    def B23FullCore250C() -> BenchmarkProblem: ...
    @staticmethod
    def B31TenRodsFullCore() -> BenchmarkProblem: ...
    @staticmethod
    def B32OneRodFullCore() -> BenchmarkProblem: ...
    @staticmethod
    def B41TenRodsInitialCore() -> BenchmarkProblem: ...
    @staticmethod
    def B42OneRodDifferential() -> BenchmarkProblem: ...
    @staticmethod
    def InfinitePebbleBedKinf() -> BenchmarkProblem: ...
    def variant(self) -> str: ...

class BenchmarkVariant:
    def dummy_pebble(self) -> DummyPebbleSpec: ...
    def atmosphere(self) -> CoreAtmosphere: ...
    def definition_temperature(self) -> float: ...
    @staticmethod
    def Original() -> BenchmarkVariant: ...
    @staticmethod
    def Deviated() -> BenchmarkVariant: ...
    def variant(self) -> str: ...

class ControlRodWorth:
    problem: BenchmarkProblem
    variant: BenchmarkVariant
    code: NeutronicsCode
    worth: float
    source: LiteratureSource
    def __init__(self, problem: BenchmarkProblem, variant: BenchmarkVariant, code: NeutronicsCode, worth: float, source: LiteratureSource) -> None: ...

class CoreAtmosphere:
    @staticmethod
    def Helium() -> CoreAtmosphere: ...
    @staticmethod
    def HumidAir(a0: HumidAirComposition) -> CoreAtmosphere: ...
    def variant(self) -> str: ...

class DummyPebbleSpec:
    diameter: float
    graphite_density: float
    equivalent_boron_ppm: float
    def __init__(self, diameter: float, graphite_density: float, equivalent_boron_ppm: float) -> None: ...

class FirstCriticalityMeasurement:
    total_balls: int
    fuel_balls: int
    dummy_balls: int
    loading_height: float
    temperature: float
    atmosphere: CoreAtmosphere
    @staticmethod
    def iaea_reported() -> FirstCriticalityMeasurement: ...
    def fuel_ball_fraction(self) -> float: ...
    def __init__(self, total_balls: int, fuel_balls: int, dummy_balls: int, loading_height: float, temperature: float, atmosphere: CoreAtmosphere) -> None: ...

class FuelPebbleSpec:
    diameter: float
    fuelled_zone_diameter: float
    graphite_density: float
    heavy_metal_loading: float
    equivalent_boron_ppm_in_uranium: float
    equivalent_boron_ppm_in_graphite: float
    particle: TrisoParticle
    @staticmethod
    def iaea_benchmark() -> FuelPebbleSpec: ...
    def fuelled_zone_radius(self) -> float: ...
    def __init__(self, diameter: float, fuelled_zone_diameter: float, graphite_density: float, heavy_metal_loading: float, equivalent_boron_ppm_in_uranium: float, equivalent_boron_ppm_in_graphite: float, particle: TrisoParticle) -> None: ...

class Htr10CoreGeometry:
    core_diameter: float
    mean_core_height: float
    full_core_volume: float
    side_reflector_thickness: float
    reflector_graphite_density: float
    reflector_equivalent_boron_ppm: float
    boronated_carbon_brick_density: float
    boronated_brick_b4c_weight_fraction: float
    control_rod_channel_count: int
    control_rod_channel_diameter: float
    control_rod_channel_radius: float
    absorber_ball_channel_count: int
    irradiation_channel_count: int
    helium_channel_count: int
    helium_channel_diameter: float
    helium_channel_radius: float
    helium_channel_bottom: float
    helium_channel_top: float
    @staticmethod
    def iaea_benchmark() -> Htr10CoreGeometry: ...
    def core_radius(self) -> float: ...
    def pebble_count_for_loading_height(self, loading_height: float, pebble_diameter: float, filling_fraction: float) -> float: ...
    def __init__(self, core_diameter: float, mean_core_height: float, full_core_volume: float, side_reflector_thickness: float, reflector_graphite_density: float, reflector_equivalent_boron_ppm: float, boronated_carbon_brick_density: float, boronated_brick_b4c_weight_fraction: float, control_rod_channel_count: int, control_rod_channel_diameter: float, control_rod_channel_radius: float, absorber_ball_channel_count: int, irradiation_channel_count: int, helium_channel_count: int, helium_channel_diameter: float, helium_channel_radius: float, helium_channel_bottom: float, helium_channel_top: float) -> None: ...

class HumidAirComposition:
    pressure: float
    air_density: float
    water_vapour_density: float
    oxygen_fraction: float
    nitrogen_fraction: float
    @staticmethod
    def iaea_deviated() -> HumidAirComposition: ...
    def unaccounted_fraction(self) -> float: ...
    def __init__(self, pressure: float, air_density: float, water_vapour_density: float, oxygen_fraction: float, nitrogen_fraction: float) -> None: ...

class LiteratureSource:
    def access_tier(self) -> AccessTier: ...
    @staticmethod
    def IaeaHtgrBenchmark() -> LiteratureSource: ...
    @staticmethod
    def ChooXiao2024() -> LiteratureSource: ...
    @staticmethod
    def Wang2014() -> LiteratureSource: ...
    @staticmethod
    def Tantillo2020() -> LiteratureSource: ...
    def variant(self) -> str: ...

class LoadingCurvePoint:
    loading_height: float
    fuel_balls: int
    dummy_balls: int
    keff: float
    keff_standard_deviation: float | None
    def __init__(self, loading_height: float, fuel_balls: int, dummy_balls: int, keff: float, keff_standard_deviation: float | None) -> None: ...

class NeutronicsCode:
    @staticmethod
    def Vsop() -> NeutronicsCode: ...
    @staticmethod
    def Mcnp4a() -> NeutronicsCode: ...
    @staticmethod
    def Mcnp5() -> NeutronicsCode: ...
    @staticmethod
    def Serpent2() -> NeutronicsCode: ...
    @staticmethod
    def HtrCodePackage() -> NeutronicsCode: ...
    @staticmethod
    def Scale6ContinuousEnergy() -> NeutronicsCode: ...
    @staticmethod
    def Scale6Multigroup(a0: UnitCellTreatment) -> NeutronicsCode: ...
    def variant(self) -> str: ...

class PublishedKeff:
    problem: BenchmarkProblem
    variant: BenchmarkVariant
    code: NeutronicsCode
    keff: float
    standard_deviation: float | None
    source: LiteratureSource
    def __init__(self, problem: BenchmarkProblem, variant: BenchmarkVariant, code: NeutronicsCode, keff: float, standard_deviation: float | None, source: LiteratureSource) -> None: ...

class TrisoParticle:
    kernel_radius: float
    kernel_density: float
    buffer_thickness: float
    buffer_density: float
    inner_pyc_thickness: float
    inner_pyc_density: float
    sic_thickness: float
    sic_density: float
    outer_pyc_thickness: float
    outer_pyc_density: float
    particles_per_pebble: int
    enrichment: float
    @staticmethod
    def iaea_benchmark() -> TrisoParticle: ...
    def outer_radius(self) -> float: ...
    def kernel_volume(self) -> float: ...
    def particle_volume(self) -> float: ...
    def uranium_molar_mass_g_per_mol(self) -> float: ...
    def uranium_mass_fraction_of_uo2(self) -> float: ...
    def heavy_metal_per_pebble(self) -> float: ...
    def packing_fraction_in_fuel_zone(self, fuel_zone_radius: float) -> float: ...
    def __init__(self, kernel_radius: float, kernel_density: float, buffer_thickness: float, buffer_density: float, inner_pyc_thickness: float, inner_pyc_density: float, sic_thickness: float, sic_density: float, outer_pyc_thickness: float, outer_pyc_density: float, particles_per_pebble: int, enrichment: float) -> None: ...

class UnitCellTreatment:
    @staticmethod
    def InfHomMedium() -> UnitCellTreatment: ...
    @staticmethod
    def LatticeCell() -> UnitCellTreatment: ...
    @staticmethod
    def MultiRegion() -> UnitCellTreatment: ...
    @staticmethod
    def LatticeCellCellMix() -> UnitCellTreatment: ...
    @staticmethod
    def MultiRegionCellMix() -> UnitCellTreatment: ...
    @staticmethod
    def DoubleHet() -> UnitCellTreatment: ...
    def variant(self) -> str: ...

class DiscoveredSimulator:
    instance_name: str
    host: str
    port: int
    endpoint_url: str

class DiscoveryError:
    @staticmethod
    def DaemonStart(a0: str) -> DiscoveryError: ...
    @staticmethod
    def Register(a0: str) -> DiscoveryError: ...
    @staticmethod
    def Browse(a0: str) -> DiscoveryError: ...
    def variant(self) -> str: ...

class MdnsAdvertisement:
    def instance_name(self) -> str: ...
    def fullname(self) -> str: ...

class OpcuaEndpointInfo:
    loopback_url: str
    lan_url: str | None
    bound_to_all_interfaces: bool
    namespace_uri: str
    node_count: int
    pki_dir_display: str
    def primary_url(self) -> str: ...

class OpcuaFolder:
    @staticmethod
    def Outputs() -> OpcuaFolder: ...
    @staticmethod
    def Controls() -> OpcuaFolder: ...
    def variant(self) -> str: ...

class OpcuaServerConfig:
    bind_address: str
    port: int
    advertise_over_mdns: bool
    application_name: str
    def is_loopback_only(self) -> bool: ...
    def binds_all_interfaces(self) -> bool: ...
    def __init__(self, bind_address: str, port: int, advertise_over_mdns: bool, application_name: str) -> None: ...

class OpcuaServerError:
    @staticmethod
    def Build(a0: str) -> OpcuaServerError: ...
    @staticmethod
    def NodeManagerUnavailable() -> OpcuaServerError: ...
    @staticmethod
    def AddressSpace(a0: str) -> OpcuaServerError: ...
    @staticmethod
    def Runtime(a0: str) -> OpcuaServerError: ...
    @staticmethod
    def StartupAborted() -> OpcuaServerError: ...
    def variant(self) -> str: ...

class OpcuaServerHandle:
    def endpoint_info(self) -> OpcuaEndpointInfo: ...
    def shutdown(self) -> None: ...

class OpcuaSimulatorProfile:
    namespace_uri: str
    application_uri: str
    endpoint_path: str
    default_application_name: str
    default_port: int
    node_manager_name: str
    outputs_folder_name: str
    outputs_folder_node_id: str
    controls_folder_name: str
    controls_folder_node_id: str
    pki_dir_name: str
    mdns_instance_prefix: str
    mdns_product_marker: str
    log_prefix: str

def htr10_illustrative_rod_drive_speed() -> float: ...
def infinite_residence_time() -> float: ...
def residence_time_from_flow(fluid_inventory: float, mass_flow: float) -> float: ...
def residence_time_from_velocity(length: float, velocity: float) -> float: ...
def cap_row_count(rows: list[list[str]], max_rows: int) -> list[list[str]]: ...
def filter_rows_by_time_interval(rows: list[list[str]], interval_seconds: float) -> list[list[str]]: ...
def total_node_count() -> int: ...
def ciet_v2_instance_pki_dir(instance_tag: str) -> str: ...
def ciet_v2_pki_dir() -> str: ...
def describe_pki_location() -> str: ...
def outram_park_home() -> str: ...
def outram_park_home_path() -> str: ...
def unique_instance_tag() -> str: ...
def default_ciet_server_config() -> OpcuaServerConfig: ...
def cooling_water_path_span(kind: CondenserKind, row: int, rows: int) -> tuple[float, float]: ...
def drawn_hotwell_level(frac: float | None) -> float | None: ...
def approach_to_wet_bulb(water_outlet: float, wet_bulb: float) -> float: ...
def cooling_range(water_inlet: float, water_outlet: float) -> float: ...
def hyperboloid_half_width(f: float, throat_fraction: float, throat_half: float, flare: float) -> float: ...
def plume_opacity(relative_humidity: float) -> float: ...
def banner_pulse(elapsed: float) -> float: ...
def excursion_intensity(fuel: float, limit: float, full_intensity_at: float) -> float: ...
def release_phase(elapsed: float) -> float: ...
def release_reach(phase: float, max_reach: float) -> float: ...
def species_visible(index: int, phase: float) -> bool: ...
def approach_verdict(kind: HeatExchangerKind, hot_inlet_temp: float, hot_outlet_temp: float, cold_inlet_temp: float, cold_outlet_temp: float) -> ApproachVerdict: ...
def lerp_temperature(from_: float, to: float, t: float) -> float: ...
def path_fractions(kind: HeatExchangerKind, s: float) -> tuple[float, float]: ...
def profile_temperature_bounds(scalars: HeatExchangerScalars) -> tuple[float, float]: ...
def terminal_approaches(kind: HeatExchangerKind, hot_inlet_temp: float, hot_outlet_temp: float, cold_inlet_temp: float, cold_outlet_temp: float) -> tuple[float, float]: ...
def depth_fraction(z: float) -> float: ...
def vessel_half_width(y: float) -> float: ...
def drawn_water_level(kind: SteamGeneratorKind, frac: float) -> float | None: ...
def hotness(temp: float, min_temp: float, max_temp: float) -> float: ...
def generic_coated_particle_retention_limit() -> float: ...
def kta_friction_factor(reynolds: float, porosity: float) -> float: ...
def b42_differential_rod_worth_curve() -> list[tuple[float, float, float]]: ...
def choo_xiao_2024_results() -> list[PublishedKeff]: ...
def critical_height_from_two_points(low: LoadingCurvePoint, high: LoadingCurvePoint) -> float | None: ...
def inet_b2_results() -> list[PublishedKeff]: ...
def inet_control_rod_worths() -> list[ControlRodWorth]: ...
def mcnp_deviated_loading_curve_27c() -> list[LoadingCurvePoint]: ...
def mcnp_original_loading_curve_27c() -> list[LoadingCurvePoint]: ...
def measured_s3_rod_worth() -> float: ...
def rod_calibration_loading_height() -> float: ...
def tantillo_2020_infinite_pebble_bed() -> list[PublishedKeff]: ...
def vsop_deviated_loading_curve_27c() -> list[LoadingCurvePoint]: ...
def vsop_original_loading_curve_20c() -> list[LoadingCurvePoint]: ...
def vsop_original_loading_curve_27c() -> list[LoadingCurvePoint]: ...
def vsop_temperature_corrected_prediction() -> tuple[int, float]: ...
def wang_2014_continuous_energy() -> list[PublishedKeff]: ...
def wang_2014_unit_cell_bias() -> list[tuple[UnitCellTreatment, float, float]]: ...
def zbs_effective_conductivity(temperature: float) -> float: ...
def describe_pki_location(dir_name: str) -> str: ...
def instance_pki_dir(dir_name: str, instance_tag: str) -> str: ...
def pki_dir(dir_name: str) -> str: ...
HTR10_ILLUSTRATIVE_FULL_TRAVEL_SECONDS: float
HTR10_ROD_STROKE_METRES: float
DEFAULT_CSV_DISPLAY_INTERVAL_SECONDS: float
MAX_CSV_ROWS: int
CIET_NAMESPACE_URI: str
DEFAULT_OPCUA_PORT: int
ENDPOINT_PATH: str
CIET_MDNS_INSTANCE_PREFIX: str
CIET_PRODUCT_TXT_VALUE: str
PATH_TXT_KEY: str
PRODUCT_TXT_KEY: str
CONTROLS_FOLDER_NAME: str
OUTPUTS_FOLDER_NAME: str
CIET_V2_PKI_DIR_NAME: str
CIET_APPLICATION_URI: str
CIET_CONTROLS_FOLDER_NODE_ID: str
CIET_DEFAULT_APPLICATION_NAME: str
CIET_LOG_PREFIX: str
CIET_NODE_MANAGER_NAME: str
CIET_OUTPUTS_FOLDER_NODE_ID: str
CTAH_PUMP_PRESSURE_LIMIT_PASCALS: float
HEATER_POWER_LIMIT_KILOWATTS: float
MAX_TIMESTEP_SECONDS: float
SURFACE_CONDENSER_ASPECT_RATIO: float
MAX_ANIMATION_TIMESTEP_SECONDS: float
HYPERBOLOID_FLARE: float
HYPERBOLOID_THROAT_FRACTION: float
INDUCED_DRAUGHT_ASPECT_RATIO: float
NATURAL_DRAUGHT_ASPECT_RATIO: float
PLUME_VISIBLE_RH_MIN: float
BANNER_PULSE_HZ: float
RELEASE_INTENSITY: float
RELEASE_RAMP_SECONDS: float
NATIVE_ASPECT_RATIO: float
PLATE_FRAME_ASPECT_RATIO: float
SHELL_AND_TUBE_ASPECT_RATIO: float
NATIVE_ASPECT_RATIO: float
BARREL_HEIGHT: float
BED_TOP: float
CHUTE_RADIUS: float
CONE_HEIGHT: float
DEPTH_WINDOW: float
SPHERE_RADIUS: float
HELICAL_COIL_ASPECT_RATIO: float
HORIZONTAL_U_TUBE_ASPECT_RATIO: float
VERTICAL_U_TUBE_ASPECT_RATIO: float
OXYGEN_MOLAR_MASS_G_PER_MOL: float
U235_MOLAR_MASS_G_PER_MOL: float
U238_MOLAR_MASS_G_PER_MOL: float
ZBS_TABLE_LEN: int
OPCUA_MDNS_SERVICE_TYPE: str
UNIX_HOME_DIR_NAME: str
