"""Type stubs for `outram_park.outram_park_fork_liggghts`, generated from the Rust API.

Physical quantities cross this boundary as `float` in SI base units.
"""

class DemError:
    @staticmethod
    def InvalidInput(a0: str) -> DemError: ...
    @staticmethod
    def NotImplemented(a0: str) -> DemError: ...
    def variant(self) -> str: ...

class Bond:
    def __init__(self, k_n: float, k_s: float, radius: float, sigma_c: float, tau_c: float) -> None: ...
    def area(self) -> float: ...
    def bending_inertia(self) -> float: ...
    def polar_inertia(self) -> float: ...
    def normal_force(self) -> float: ...
    def shear_force(self) -> Vec3: ...
    def twist_moment(self) -> float: ...
    def bend_moment(self) -> Vec3: ...
    def tensile_stress(self) -> float: ...
    def shear_stress(self) -> float: ...
    def is_broken(self) -> bool: ...
    def update_bond(self, a: Particle, b: Particle, dt: float) -> BondForce: ...

class BondForce:
    force_on_a: Vec3
    force_on_b: Vec3
    torque_on_a: Vec3
    torque_on_b: Vec3
    @staticmethod
    def zero() -> BondForce: ...
    def __init__(self, force_on_a: Vec3, force_on_b: Vec3, torque_on_a: Vec3, torque_on_b: Vec3) -> None: ...

class BondModel:
    def update_bond(self, a: Particle, b: Particle, dt: float) -> BondForce: ...
    def is_broken(self) -> bool: ...
    @staticmethod
    def ParallelBond(a0: Bond) -> BondModel: ...
    @staticmethod
    def None_() -> BondModel: ...
    def variant(self) -> str: ...

class Boundary:
    @staticmethod
    def plane(point: Vec3, normal: Vec3) -> Boundary: ...
    @staticmethod
    def wall(point: Vec3, normal: Vec3) -> Boundary: ...
    @staticmethod
    def aabb(min: Vec3, max: Vec3) -> Boundary: ...
    @staticmethod
    def cylinder(axis_point: Vec3, axis_dir: Vec3, radius: float) -> Boundary: ...
    def signed_distance(self, point: Vec3) -> float: ...
    def particle_overlap(self, p: Particle) -> Contact | None: ...
    @staticmethod
    def Plane(point: Vec3, normal: Vec3) -> Boundary: ...
    @staticmethod
    def Wall(point: Vec3, normal: Vec3) -> Boundary: ...
    @staticmethod
    def Box(min: Vec3, max: Vec3) -> Boundary: ...
    @staticmethod
    def Cylinder(axis_point: Vec3, axis_dir: Vec3, radius: float) -> Boundary: ...
    def variant(self) -> str: ...

class Contact:
    overlap: float
    normal: Vec3
    point: Vec3
    def __init__(self, overlap: float, normal: Vec3, point: Vec3) -> None: ...

class ContactForce:
    force_on_a: Vec3
    force_on_b: Vec3
    torque_on_a: Vec3
    torque_on_b: Vec3
    overlap: float
    normal: Vec3
    def __init__(self, force_on_a: Vec3, force_on_b: Vec3, torque_on_a: Vec3, torque_on_b: Vec3, overlap: float, normal: Vec3) -> None: ...

class ContactModel:
    def contact_force(self, a: Particle, b: Particle) -> ContactForce | None: ...
    @staticmethod
    def Hooke(a0: HookeContact) -> ContactModel: ...
    @staticmethod
    def Hertz(a0: HertzContact) -> ContactModel: ...
    def variant(self) -> str: ...

class HertzContact:
    youngs_modulus: float
    poisson_ratio: float
    restitution: float
    friction: float
    def __init__(self, youngs_modulus: float, poisson_ratio: float, restitution: float, friction: float) -> None: ...
    def effective_modulus(self) -> float: ...
    def effective_shear_modulus(self) -> float: ...
    def damping_beta(self) -> float: ...

class HookeContact:
    normal_stiffness: float
    normal_damping: float
    tangential_stiffness: float
    tangential_damping: float
    friction: float
    def __init__(self, normal_stiffness: float, normal_damping: float, tangential_stiffness: float, tangential_damping: float, friction: float) -> None: ...

class CouplingExchange:
    drag_force: Vec3
    particle_volume_fraction: float
    def __init__(self, drag_force: Vec3, particle_volume_fraction: float) -> None: ...

class CouplingScheme:
    @staticmethod
    def OneWay() -> CouplingScheme: ...
    @staticmethod
    def TwoWay() -> CouplingScheme: ...
    @staticmethod
    def VolumeFiltered() -> CouplingScheme: ...
    def variant(self) -> str: ...

class LocalFluidState:
    velocity: Vec3
    pressure_gradient: Vec3
    void_fraction: float
    def __init__(self, velocity: Vec3, pressure_gradient: Vec3, void_fraction: float) -> None: ...

class ReservedCoupling:
    scheme: CouplingScheme
    def __init__(self, scheme: CouplingScheme) -> None: ...

class ReservedDragModel:
    def __init__(self) -> None: ...
    @staticmethod
    def default() -> ReservedDragModel: ...

class ReservedFluidSource:
    def __init__(self) -> None: ...
    @staticmethod
    def default() -> ReservedFluidSource: ...

class MeshWall:
    triangles: list[Triangle]
    def __init__(self, triangles: list[Triangle]) -> None: ...
    def particle_overlap(self, p: Particle) -> Contact | None: ...

class MovingBoundary:
    geometry: WallGeometry
    velocity: Vec3
    angular_velocity: Vec3
    pivot: Vec3
    def __init__(self, geometry: WallGeometry, velocity: Vec3, angular_velocity: Vec3, pivot: Vec3) -> None: ...
    def surface_velocity(self, point: Vec3) -> Vec3: ...
    def particle_overlap(self, p: Particle) -> Contact | None: ...
    def advance(self, dt: float) -> None: ...

class Triangle:
    a: Vec3
    b: Vec3
    c: Vec3
    def __init__(self, a: Vec3, b: Vec3, c: Vec3) -> None: ...
    def normal(self) -> Vec3: ...
    def closest_point(self, p: Vec3) -> Vec3: ...

class WallGeometry:
    def particle_overlap(self, p: Particle) -> Contact | None: ...
    @staticmethod
    def Analytic(a0: Boundary) -> WallGeometry: ...
    @staticmethod
    def Mesh(a0: MeshWall) -> WallGeometry: ...
    def variant(self) -> str: ...

class Particle:
    position: Vec3
    velocity: Vec3
    angular_velocity: Vec3
    mass: float
    radius: float
    temperature: float
    def __init__(self, position: Vec3, velocity: Vec3, angular_velocity: Vec3, mass: float, radius: float, temperature: float) -> None: ...
    def volume(self) -> float: ...
    def moment_of_inertia(self) -> float: ...
    def integrate(self, force: Vec3, torque: Vec3, dt: float) -> None: ...

class Vec3:
    x: float
    y: float
    z: float
    def __init__(self, x: float, y: float, z: float) -> None: ...
    @staticmethod
    def zero() -> Vec3: ...
    def add(self, other: Vec3) -> Vec3: ...
    def sub(self, other: Vec3) -> Vec3: ...
    def scale(self, s: float) -> Vec3: ...
    def dot(self, other: Vec3) -> float: ...
    def cross(self, other: Vec3) -> Vec3: ...
    def norm_squared(self) -> float: ...
    def norm(self) -> float: ...

class CohesionModel:
    @staticmethod
    def none() -> CohesionModel: ...
    @staticmethod
    def linear(k_c: float, max_gap: float) -> CohesionModel: ...
    @staticmethod
    def jkr(surface_energy: float) -> CohesionModel: ...
    def max_attractive_force(self, r_eff: float) -> float: ...
    def cohesive_force(self, overlap: float, r_eff: float) -> float: ...
    @staticmethod
    def None_() -> CohesionModel: ...
    @staticmethod
    def LinearCohesion(k_c: float, max_gap: float) -> CohesionModel: ...
    @staticmethod
    def Jkr(surface_energy: float) -> CohesionModel: ...
    def variant(self) -> str: ...

class RollingModel:
    @staticmethod
    def none() -> RollingModel: ...
    @staticmethod
    def constant_directional_torque(mu_r: float) -> RollingModel: ...
    @staticmethod
    def viscous(c_r: float) -> RollingModel: ...
    def rolling_torque(self, normal_force: float, r_eff: float, omega_rel: Vec3) -> RollingTorque: ...
    @staticmethod
    def None_() -> RollingModel: ...
    @staticmethod
    def ConstantDirectionalTorque(mu_r: float) -> RollingModel: ...
    @staticmethod
    def ViscousRolling(c_r: float) -> RollingModel: ...
    def variant(self) -> str: ...

class RollingTorque:
    torque_on_a: Vec3
    torque_on_b: Vec3
    @staticmethod
    def zero() -> RollingTorque: ...
    def __init__(self, torque_on_a: Vec3, torque_on_b: Vec3) -> None: ...

class DemSimulation:
    def __init__(self, particles: list[Particle], boundaries: list[Boundary], contact_model: ContactModel, gravity: Vec3, dt: float) -> None: ...
    def particles(self) -> list[Particle]: ...
    def boundaries(self) -> list[Boundary]: ...
    def contact_model(self) -> ContactModel: ...
    def gravity(self) -> Vec3: ...
    def dt(self) -> float: ...
    def time(self) -> float: ...
    def num_particles(self) -> int: ...
    def kinetic_energy(self) -> float: ...
    def total_momentum(self) -> Vec3: ...
    def step(self) -> None: ...
    def run(self, n_steps: int) -> None: ...

class ThermalModel:
    def conductance(self, contact_radius: float) -> float: ...
    @staticmethod
    def ContactConduction(k_i: float, k_j: float) -> ThermalModel: ...
    @staticmethod
    def Constant(a0: float) -> ThermalModel: ...
    def variant(self) -> str: ...

class RadiationModel:
    def effective_emissivity(self) -> float: ...
    @staticmethod
    def GreyBody(emissivity: float) -> RadiationModel: ...
    @staticmethod
    def GreyPair(emissivity_i: float, emissivity_j: float) -> RadiationModel: ...
    def variant(self) -> str: ...

def conductive_heat_rate(h_c: float, t_into: float, t_from: float) -> float: ...
def effective_radius(r_i: float, r_j: float) -> float: ...
def explicit_euler_temperature(temperature: float, net_heat_rate: float, mass: float, specific_heat: float, dt: float) -> float: ...
def harmonic_mean_conductivity(k_i: float, k_j: float) -> float: ...
def hertzian_contact_radius(r_i: float, r_j: float, overlap: float) -> float: ...
def particle_pair_heat_rate(model: ThermalModel, contact_radius: float, particle_i: Particle, particle_j: Particle) -> float: ...
def sphere_wall_effective_radius(r: float) -> float: ...
def wall_heat_rate(model: ThermalModel, contact_radius: float, particle: Particle, wall_temperature: float) -> float: ...
def gas_gap_conductance(k_g: float, r_i: float, r_j: float, gap: float, outer_radius: float) -> float: ...
def gas_gap_heat_rate(k_g: float, gap: float, outer_radius: float, particle_i: Particle, particle_j: Particle) -> float: ...
def gas_gap_wall_heat_rate(k_g: float, gap: float, outer_radius: float, particle: Particle, wall_temperature: float) -> float: ...
def gas_wall_gap_conductance(k_g: float, r: float, gap: float, outer_radius: float) -> float: ...
def net_radiative_heat_rate(model: RadiationModel, exchange_area: float, particle_i: Particle, particle_j: Particle) -> float: ...
def radiative_heat_rate(eps_eff: float, area: float, t_into: float, t_from: float) -> float: ...
def radiative_wall_heat_rate(model: RadiationModel, exchange_area: float, particle: Particle, wall_temperature: float) -> float: ...
STEFAN_BOLTZMANN: float
