"""Type stubs for `outram_park.outram_foam_mesh`, generated from the Rust API.

Physical quantities cross this boundary as `float` in SI base units.
"""

class GeneratedMesh:
    mesh: outram_foam_basic_lib.PolyMesh
    quality: MeshQualityReport
    phases_run: MeshingPhases
    layers: LayerOutcome
    n_cells_castellated: int
    def write_case(self, case_dir: str) -> None: ...
    def __init__(self, mesh: outram_foam_basic_lib.PolyMesh, quality: MeshQualityReport, phases_run: MeshingPhases, layers: LayerOutcome, n_cells_castellated: int) -> None: ...

class KeepRegion:
    @staticmethod
    def Outside() -> KeepRegion: ...
    @staticmethod
    def Inside() -> KeepRegion: ...
    @staticmethod
    def At(a0: outram_foam_basic_lib.Vector3) -> KeepRegion: ...
    def variant(self) -> str: ...

class LayerOutcome:
    @staticmethod
    def NotRequested() -> LayerOutcome: ...
    @staticmethod
    def NoneAdded() -> LayerOutcome: ...
    @staticmethod
    def InsertedInterior() -> LayerOutcome: ...
    @staticmethod
    def ExtrudedOutward() -> LayerOutcome: ...
    def variant(self) -> str: ...

class MeshError:
    @staticmethod
    def DictParse(a0: str) -> MeshError: ...
    @staticmethod
    def NotImplemented(a0: str) -> MeshError: ...
    @staticmethod
    def Construction(a0: str) -> MeshError: ...
    @staticmethod
    def Io(a0: str) -> MeshError: ...
    def variant(self) -> str: ...

class MeshQualityReport:
    n_cells: int
    n_points: int
    n_faces: int
    n_internal_faces: int
    n_boundary_faces: int
    total_volume: float
    min_cell_volume: float
    max_cell_volume: float
    n_negative_volume_cells: int
    max_non_ortho_deg: float
    mean_non_ortho_deg: float
    n_severely_non_ortho_faces: int
    max_skewness: float
    max_boundary_skewness: float
    max_aspect_ratio: float
    mean_aspect_ratio: float
    def verdict(self) -> QualityVerdict: ...
    def summary(self) -> str: ...
    def __init__(self, n_cells: int, n_points: int, n_faces: int, n_internal_faces: int, n_boundary_faces: int, total_volume: float, min_cell_volume: float, max_cell_volume: float, n_negative_volume_cells: int, max_non_ortho_deg: float, mean_non_ortho_deg: float, n_severely_non_ortho_faces: int, max_skewness: float, max_boundary_skewness: float, max_aspect_ratio: float, mean_aspect_ratio: float) -> None: ...

class MeshingControls:
    domain: Bounds | None
    domain_margin: float
    background_divisions: list[int]
    refinement_level: int
    keep: KeepRegion
    phases: MeshingPhases
    surface_patch_name: str
    snap: SnapControls
    layers: LayerControls
    def with_phases(self, phases: MeshingPhases) -> MeshingControls: ...
    def with_domain(self, domain: Bounds) -> MeshingControls: ...
    def with_snap(self, snap: SnapControls) -> MeshingControls: ...
    def with_layers(self, layers: LayerControls) -> MeshingControls: ...
    def __init__(self) -> None: ...
    @staticmethod
    def default() -> MeshingControls: ...

class MeshingPhases:
    @staticmethod
    def Castellate() -> MeshingPhases: ...
    @staticmethod
    def CastellateSnap() -> MeshingPhases: ...
    @staticmethod
    def CastellateSnapLayers() -> MeshingPhases: ...
    def variant(self) -> str: ...

class QualityVerdict:
    @staticmethod
    def Good() -> QualityVerdict: ...
    @staticmethod
    def Marginal() -> QualityVerdict: ...
    @staticmethod
    def Unusable() -> QualityVerdict: ...
    def variant(self) -> str: ...

class Block:
    vertices: list[int]
    cells: list[int]
    grading: list[Grading]
    edge_grading: list[Grading] | None

class BlockMeshDict:
    convert_to_meters: float
    vertices: list[outram_foam_basic_lib.Vector3]
    blocks: list[Block]
    patches: list[PatchDef]
    @staticmethod
    def parse(text: str) -> BlockMeshDict: ...
    def build(self) -> PolyMesh: ...
    def __init__(self, convert_to_meters: float, vertices: list[outram_foam_basic_lib.Vector3], blocks: list[Block], patches: list[PatchDef]) -> None: ...

class Grading:
    @staticmethod
    def Uniform(a0: float) -> Grading: ...
    @staticmethod
    def Multi(a0: list[GradingSegment]) -> Grading: ...
    def variant(self) -> str: ...

class GradingSegment:
    fraction_length: float
    fraction_cells: float
    expansion: float
    def __init__(self, fraction_length: float, fraction_cells: float, expansion: float) -> None: ...

class MeshFace:
    verts: list[int]
    owner: int
    neighbour: int | None
    def __init__(self, verts: list[int], owner: int, neighbour: int | None) -> None: ...

class PatchDef:
    name: str
    kind: outram_foam_basic_lib.PatchKind
    faces: list[list[int]]

class PolyMesh:
    points: list[outram_foam_basic_lib.Vector3]
    faces: list[MeshFace]
    n_internal_faces: int
    n_cells: int
    patches: list[outram_foam_basic_lib.BoundaryPatch]
    def n_points(self) -> int: ...
    def n_faces(self) -> int: ...
    def n_boundary_faces(self) -> int: ...
    def total_volume(self) -> float: ...
    def to_foam_poly_mesh(self) -> outram_foam_basic_lib.PolyMesh: ...
    def to_fv_mesh(self) -> outram_foam_basic_lib.FvMesh: ...
    def __init__(self, points: list[outram_foam_basic_lib.Vector3], faces: list[MeshFace], n_internal_faces: int, n_cells: int, patches: list[outram_foam_basic_lib.BoundaryPatch]) -> None: ...

class UnvPolyMesh:
    points: list[outram_foam_basic_lib.Vector3]
    faces: list[list[int]]
    fv_mesh: outram_foam_basic_lib.FvMesh
    n_skipped_elements: int
    def total_volume(self) -> float: ...
    def __init__(self, points: list[outram_foam_basic_lib.Vector3], faces: list[list[int]], fv_mesh: outram_foam_basic_lib.FvMesh, n_skipped_elements: int) -> None: ...

class DualMesh:
    points: list[outram_foam_basic_lib.Vector3]
    faces: list[list[int]]
    owner: list[int]
    neighbour: list[int | None]
    face_patch: list[int | None]
    n_cells: int
    cell_is_interior: list[bool]
    def n_interior_cells(self) -> int: ...
    def total_volume(self) -> float: ...
    def max_closure_residual(self) -> float: ...
    def first_bad_euler(self) -> tuple[int, int] | None: ...
    def to_foam_poly_mesh(self, patch_names: list[str]) -> outram_foam_basic_lib.PolyMesh: ...
    def to_fv_mesh(self, patch_names: list[str]) -> outram_foam_basic_lib.FvMesh: ...
    def __init__(self, points: list[outram_foam_basic_lib.Vector3], faces: list[list[int]], owner: list[int], neighbour: list[int | None], face_patch: list[int | None], n_cells: int, cell_is_interior: list[bool]) -> None: ...

class poly_dual_mesh_PolyMesh:
    points: list[outram_foam_basic_lib.Vector3]
    faces: list[list[int]]
    owner: list[int]
    neighbour: list[int]
    n_internal_faces: int
    patches: list[outram_foam_basic_lib.BoundaryPatch]
    n_cells: int
    def n_points(self) -> int: ...
    def is_internal_face(self, f: int) -> bool: ...
    def total_volume(self) -> float: ...
    @staticmethod
    def structured_hex_block(nx: int, ny: int, nz: int, lx: float, ly: float, lz: float) -> poly_dual_mesh_PolyMesh: ...
    def __init__(self, points: list[outram_foam_basic_lib.Vector3], faces: list[list[int]], owner: list[int], neighbour: list[int], n_internal_faces: int, patches: list[outram_foam_basic_lib.BoundaryPatch], n_cells: int) -> None: ...

class BackgroundMesh:
    bounds: Bounds
    nx: int
    ny: int
    nz: int
    @staticmethod
    def uniform(bounds: Bounds, nx: int, ny: int, nz: int) -> BackgroundMesh: ...
    def n_cells(self) -> int: ...
    def cell_size(self) -> outram_foam_basic_lib.Vector3: ...
    def __init__(self, bounds: Bounds, nx: int, ny: int, nz: int) -> None: ...

class Bounds:
    min: outram_foam_basic_lib.Vector3
    max: outram_foam_basic_lib.Vector3
    def __init__(self, a: outram_foam_basic_lib.Vector3, b: outram_foam_basic_lib.Vector3) -> None: ...
    def expanded(self, pad: float) -> Bounds: ...
    def centre(self) -> outram_foam_basic_lib.Vector3: ...
    def span(self) -> outram_foam_basic_lib.Vector3: ...
    def volume(self) -> float: ...
    def diagonal(self) -> float: ...

class CastellatedMesh:
    fv_mesh: outram_foam_basic_lib.FvMesh
    points: list[outram_foam_basic_lib.Vector3]
    topology: PolyPatchMesh
    surface_faces: list[SurfaceFace]
    cells_by_level: list[int]
    max_level: int
    def n_cells(self) -> int: ...
    def __init__(self, fv_mesh: outram_foam_basic_lib.FvMesh, points: list[outram_foam_basic_lib.Vector3], topology: PolyPatchMesh, surface_faces: list[SurfaceFace], cells_by_level: list[int], max_level: int) -> None: ...

class CastellationControls:
    background: BackgroundMesh
    surface_level: int
    refinement_distance: float | None
    keep_point: outram_foam_basic_lib.Vector3
    surface_patch_name: str
    cyclic_axes: list[bool]
    def __init__(self, background: BackgroundMesh, surface_level: int, keep_point: outram_foam_basic_lib.Vector3) -> None: ...
    def with_cyclic_axis(self, axis: int) -> CastellationControls: ...

class CyclicError:
    @staticmethod
    def UnresolvedPartner(patch: int, name: str) -> CyclicError: ...
    @staticmethod
    def AsymmetricPartner(patch: int, partner: int) -> CyclicError: ...
    @staticmethod
    def SizeMismatch(patch: int, size: int, partner: int, partner_size: int) -> CyclicError: ...
    @staticmethod
    def FaceShapeMismatch(local: int, n_a: int, n_b: int) -> CyclicError: ...
    @staticmethod
    def NotTranslational(patch: int) -> CyclicError: ...
    def variant(self) -> str: ...

class CyclicPair:
    patch_a: int
    patch_b: int
    separation: outram_foam_basic_lib.Vector3
    def plane_normal(self) -> outram_foam_basic_lib.Vector3: ...
    def __init__(self, patch_a: int, patch_b: int, separation: outram_foam_basic_lib.Vector3) -> None: ...

class CyclicPointConstraints:
    def is_constrained(self, point: int) -> bool: ...
    def n_pairings(self) -> int: ...
    @staticmethod
    def build(topo: PolyPatchMesh, tol: float) -> CyclicPointConstraints: ...
    def __init__(self) -> None: ...
    @staticmethod
    def default() -> CyclicPointConstraints: ...

class LayerControls:
    n_surface_layers: int
    expansion_ratio: float
    first_layer_thickness: float
    final_layer_thickness: float | None
    max_thickness_fraction: float
    medial_axis_thickness_ratio: float
    quality_limits: QualityLimits
    def first_thickness(self) -> float: ...
    def __init__(self, n_surface_layers: int | None = None, expansion_ratio: float | None = None, first_layer_thickness: float | None = None, final_layer_thickness: float | None = None, max_thickness_fraction: float | None = None, medial_axis_thickness_ratio: float | None = None, quality_limits: QualityLimits | None = None) -> None: ...
    @staticmethod
    def default() -> LayerControls: ...

class MeshQuality:
    max_non_ortho_deg: float
    max_skewness: float
    min_cell_volume: float
    n_negative_volume_cells: int
    def __init__(self, max_non_ortho_deg: float, max_skewness: float, min_cell_volume: float, n_negative_volume_cells: int) -> None: ...

class PolyPatchMesh:
    points: list[outram_foam_basic_lib.Vector3]
    faces: list[list[int]]
    owner: list[int]
    neighbour: list[int]
    n_internal_faces: int
    n_cells: int
    patches: list[outram_foam_basic_lib.BoundaryPatch]
    def n_faces(self) -> int: ...
    def n_boundary_faces(self) -> int: ...
    def face_geometry(self) -> tuple[list[outram_foam_basic_lib.Vector3], list[outram_foam_basic_lib.Vector3]]: ...
    def cell_geometry(self, face_areas: list[outram_foam_basic_lib.Vector3], face_centres: list[outram_foam_basic_lib.Vector3]) -> tuple[list[outram_foam_basic_lib.Vector3], list[float]]: ...
    def build_fvmesh(self) -> outram_foam_basic_lib.FvMesh: ...
    def quality(self) -> MeshQuality: ...
    def to_foam_poly_mesh(self) -> outram_foam_basic_lib.PolyMesh: ...
    def patch_point_ids(self, patch_index: int) -> list[int]: ...
    def boundary_point_flags(self) -> list[bool]: ...
    def point_faces(self) -> list[list[int]]: ...
    def __init__(self, points: list[outram_foam_basic_lib.Vector3], faces: list[list[int]], owner: list[int], neighbour: list[int], n_internal_faces: int, n_cells: int, patches: list[outram_foam_basic_lib.BoundaryPatch]) -> None: ...

class QualityLimits:
    max_non_ortho_deg: float
    max_skewness: float
    min_vol: float
    def accepts(self, q: MeshQuality) -> bool: ...
    def __init__(self, max_non_ortho_deg: float | None = None, max_skewness: float | None = None, min_vol: float | None = None) -> None: ...
    @staticmethod
    def default() -> QualityLimits: ...

class SnapControls:
    n_solve_iter: int
    n_smooth_patch: int
    tolerance: float
    quality: QualityLimits
    feature_snap: bool
    feature_angle_deg: float
    def __init__(self, n_solve_iter: int | None = None, n_smooth_patch: int | None = None, tolerance: float | None = None, quality: QualityLimits | None = None, feature_snap: bool | None = None, feature_angle_deg: float | None = None) -> None: ...
    @staticmethod
    def default() -> SnapControls: ...

class SnappyHexMeshControls:
    castellation: CastellationControls
    snap: SnapControls | None
    layers: LayerControls | None
    @staticmethod
    def castellation_only(castellation: CastellationControls) -> SnappyHexMeshControls: ...
    def with_snap(self, snap: SnapControls) -> SnappyHexMeshControls: ...
    def with_layers(self, layers: LayerControls) -> SnappyHexMeshControls: ...
    def __init__(self, castellation: CastellationControls, snap: SnapControls | None, layers: LayerControls | None) -> None: ...

class SurfaceFace:
    owner_cell: int
    corners: list[int]

class Triangle:
    a: outram_foam_basic_lib.Vector3
    b: outram_foam_basic_lib.Vector3
    c: outram_foam_basic_lib.Vector3
    def __init__(self, a: outram_foam_basic_lib.Vector3, b: outram_foam_basic_lib.Vector3, c: outram_foam_basic_lib.Vector3) -> None: ...
    def normal(self) -> outram_foam_basic_lib.Vector3: ...
    def area(self) -> float: ...
    def centroid(self) -> outram_foam_basic_lib.Vector3: ...
    def closest_point(self, p: outram_foam_basic_lib.Vector3) -> outram_foam_basic_lib.Vector3: ...
    def ray_intersection(self, origin: outram_foam_basic_lib.Vector3, dir: outram_foam_basic_lib.Vector3) -> float | None: ...

class TriangleSoup:
    triangles: list[Triangle]
    name: str
    def __init__(self, name: str, triangles: list[Triangle]) -> None: ...
    @staticmethod
    def uv_sphere(centre: outram_foam_basic_lib.Vector3, r: float, n_lat: int, n_lon: int) -> TriangleSoup: ...
    @staticmethod
    def cuboid(min: outram_foam_basic_lib.Vector3, max: outram_foam_basic_lib.Vector3) -> TriangleSoup: ...
    def len(self) -> int: ...
    def is_empty(self) -> bool: ...
    def bounding_box(self) -> tuple[outram_foam_basic_lib.Vector3, outram_foam_basic_lib.Vector3] | None: ...
    def nearest_point(self, p: outram_foam_basic_lib.Vector3) -> outram_foam_basic_lib.Vector3 | None: ...
    def distance_to(self, p: outram_foam_basic_lib.Vector3) -> float: ...
    def contains_point(self, p: outram_foam_basic_lib.Vector3) -> bool: ...
    @staticmethod
    def default() -> TriangleSoup: ...

def assess_quality(mesh: outram_foam_basic_lib.PolyMesh) -> MeshQualityReport: ...
def block_mesh(dict_text: str) -> PolyMesh: ...
def block_mesh_from_file(path: str) -> PolyMesh: ...
def convert(unv_text: str) -> UnvPolyMesh: ...
def convert_file(path: str) -> UnvPolyMesh: ...
def convert_scaled(unv_text: str, scale: float) -> UnvPolyMesh: ...
def mesh_from_surface(surface: TriangleSoup, controls: MeshingControls) -> GeneratedMesh: ...
def poly_dual_mesh(primal: poly_dual_mesh_PolyMesh, feature_angle_deg: float) -> DualMesh: ...
def add_layers(mesh: CastellatedMesh, controls: LayerControls) -> CastellatedMesh: ...
def castellate(surface: TriangleSoup, controls: CastellationControls) -> CastellatedMesh: ...
def check_conformity(topo: PolyPatchMesh, tol: float) -> None: ...
def face_area_and_centre(face: list[int], points: list[outram_foam_basic_lib.Vector3]) -> tuple[outram_foam_basic_lib.Vector3, outram_foam_basic_lib.Vector3]: ...
def generate(surface: TriangleSoup, controls: SnappyHexMeshControls) -> CastellatedMesh: ...
def layer_thicknesses(controls: LayerControls) -> list[float]: ...
def raw_surface_displacements(mesh: CastellatedMesh, surface: TriangleSoup) -> list[outram_foam_basic_lib.Vector3]: ...
def read_stl(path: str) -> TriangleSoup: ...
def read_stl_ascii_str(text: str) -> TriangleSoup: ...
def read_stl_binary(bytes: list[int]) -> TriangleSoup: ...
def read_stl_bytes(bytes: list[int]) -> TriangleSoup: ...
def resolve_pairs(topo: PolyPatchMesh) -> list[CyclicPair]: ...
def snap(mesh: CastellatedMesh, surface: TriangleSoup, controls: SnapControls) -> CastellatedMesh: ...
def total_layer_thickness(controls: LayerControls) -> float: ...
BOUNDARY_SKEWNESS_LIMIT: float
NON_ORTHO_OK_DEG: float
NON_ORTHO_SEVERE_DEG: float
SKEWNESS_LIMIT: float
DEFAULT_CYCLIC_TOL: float
