"""Type stubs for `outram_park.outram_park_fork_offbeat`, generated from the Rust API.

Physical quantities cross this boundary as `float` in SI base units.
"""

class OffbeatError:
    @staticmethod
    def MechanicsNotConverged(residual: float, tolerance: float, iterations: int) -> OffbeatError: ...
    @staticmethod
    def ConstitutiveNotConverged(cell: int, residual: float, iterations: int) -> OffbeatError: ...
    @staticmethod
    def Mesh(a0: str) -> OffbeatError: ...
    def variant(self) -> str: ...

class BurnupAccumulator:
    def __init__(self, basis: HeavyMetalBasis) -> None: ...
    def burnup_mwd_per_kg_hm(self) -> float: ...
    def burnup_mwd_per_tonne_hm(self) -> float: ...
    def burnup_mwd_per_tonne_oxide(self) -> float: ...
    def burnup_joules_per_kg_hm(self) -> float: ...
    def burnup_percent_fima(self) -> float: ...
    def fast_fluence_per_m2(self) -> float: ...
    def fast_fluence_per_cm2(self) -> float: ...
    def basis(self) -> HeavyMetalBasis: ...
    def elapsed_time(self) -> float: ...
    def last_burnup_increment(self) -> float: ...

class FastFluxHistory:
    def flux_at(self, t: float) -> float: ...
    def times(self) -> list[float]: ...
    def fluxes(self) -> list[float]: ...
    def interpolation(self) -> TimeInterpolation: ...

class FastFluxModel:
    def flux_at(self, t: float) -> float: ...
    def upstream_name(self) -> str: ...
    @staticmethod
    def Disabled() -> FastFluxModel: ...
    @staticmethod
    def Constant(a0: float) -> FastFluxModel: ...
    @staticmethod
    def Tabulated(a0: FastFluxHistory) -> FastFluxModel: ...
    def variant(self) -> str: ...
    @staticmethod
    def default() -> FastFluxModel: ...

class HeavyMetalBasis:
    def fuel_density(self) -> float: ...
    def heavy_metal_fraction(self) -> float: ...
    def heavy_metal_density(self) -> float: ...

class TimeInterpolation:
    @staticmethod
    def Linear() -> TimeInterpolation: ...
    @staticmethod
    def Step() -> TimeInterpolation: ...
    def variant(self) -> str: ...
    @staticmethod
    def default() -> TimeInterpolation: ...

class AccelerationOutcome:
    @staticmethod
    def Stored() -> AccelerationOutcome: ...
    @staticmethod
    def Accelerated() -> AccelerationOutcome: ...
    @staticmethod
    def Degenerate() -> AccelerationOutcome: ...
    def variant(self) -> str: ...

class AccelerationScheme:
    def reset(self) -> None: ...
    def min_iterations(self) -> int: ...
    @staticmethod
    def None_() -> AccelerationScheme: ...
    @staticmethod
    def Anderson(a0: AndersonMixing) -> AccelerationScheme: ...
    def variant(self) -> str: ...

class AndersonMixing:
    def __init__(self, order: int) -> None: ...
    @staticmethod
    def with_parameters(order: int, alpha: float, diagonal_factor: float) -> AndersonMixing: ...
    def order(self) -> int: ...
    def alpha(self) -> float: ...
    def diagonal_factor(self) -> float: ...
    def stored_snapshots(self) -> int: ...
    def reset(self) -> None: ...

class CorrosionModel:
    @staticmethod
    def zircaloy_outer_default() -> CorrosionModel: ...
    def with_hydrogen_pickup(self, hydrogen: HydrogenPickupModel) -> CorrosionModel: ...
    def step(self, state: CorrosionState) -> CorrosionStep: ...
    @staticmethod
    def metal_loss(oxide_growth: float) -> float: ...
    def kinetics(self) -> OxidationKinetics | None: ...
    def hydrogen_pickup(self) -> HydrogenPickupModel: ...
    @staticmethod
    def Constant() -> CorrosionModel: ...
    @staticmethod
    def ZircaloyOuter(kinetics: OxidationKinetics, hydrogen: HydrogenPickupModel) -> CorrosionModel: ...
    def variant(self) -> str: ...

class CorrosionState:
    interface_temperature: float
    oxide_thickness: float
    fast_flux: float
    time_step: float
    @staticmethod
    def fresh(interface_temperature: float, time_step: float) -> CorrosionState: ...
    def advanced(self, step: CorrosionStep) -> CorrosionState: ...
    def __init__(self, interface_temperature: float, oxide_thickness: float, fast_flux: float, time_step: float) -> None: ...

class CorrosionStep:
    oxide_thickness: float
    oxide_growth: float
    metal_loss: float
    hydrogen_pickup: float
    @staticmethod
    def unchanged(oxide_thickness: float) -> CorrosionStep: ...
    def __init__(self, oxide_thickness: float, oxide_growth: float, metal_loss: float, hydrogen_pickup: float) -> None: ...

class FixedPointReport:
    iterations: int
    residual: float
    converged: bool
    accelerations: int
    def __init__(self, iterations: int, residual: float, converged: bool, accelerations: int) -> None: ...

class HydrogenPickupModel:
    @staticmethod
    def zircaloy_4(inner_radius: float, outer_radius: float) -> HydrogenPickupModel: ...
    def pickup(self, oxide_thickness_before: float, oxide_growth: float) -> float: ...
    def ingress_flux(self, oxide_thickness_before: float, oxide_growth: float, time_step: float) -> float: ...
    @staticmethod
    def None_() -> HydrogenPickupModel: ...
    @staticmethod
    def OxidePickupFraction(pickup_fraction: float, inner_radius: float, outer_radius: float, scaling: PickupScaling) -> HydrogenPickupModel: ...
    def variant(self) -> str: ...

class OxidationKinetics:
    def thickness(self, previous_thickness: float, interface_temperature: float, fast_flux: float, time_step: float) -> float: ...
    def growth(self, previous_thickness: float, interface_temperature: float, fast_flux: float, time_step: float) -> float: ...
    def growth_rate(self, previous_thickness: float, interface_temperature: float, fast_flux: float, time_step: float) -> float: ...
    @staticmethod
    def EpriKwuCe() -> OxidationKinetics: ...
    @staticmethod
    def CathcartPawel() -> OxidationKinetics: ...
    @staticmethod
    def EpriKwuCeCathcartPawel() -> OxidationKinetics: ...
    def variant(self) -> str: ...

class OxideThermalCoupling:
    interface_temperature: float
    boundary_conductivity: float
    blending_factor: float
    def __init__(self, interface_temperature: float, boundary_conductivity: float, blending_factor: float) -> None: ...

class PickupScaling:
    def factor(self, mean_oxide_thickness: float, inner_radius: float, outer_radius: float) -> float: ...
    @staticmethod
    def Uniform() -> PickupScaling: ...
    @staticmethod
    def UpstreamVolumeFactor() -> PickupScaling: ...
    def variant(self) -> str: ...

class FissionGasInventory:
    gas_in_grain: float
    gas_at_boundary: float
    gas_released: float
    helium_in_grain: float
    helium_at_boundary: float
    helium_released: float
    intragranular_swelling: float
    intergranular_swelling: float
    def total_fission_gas(self) -> float: ...
    def total_helium(self) -> float: ...
    def __init__(self, gas_in_grain: float | None = None, gas_at_boundary: float | None = None, gas_released: float | None = None, helium_in_grain: float | None = None, helium_at_boundary: float | None = None, helium_released: float | None = None, intragranular_swelling: float | None = None, intergranular_swelling: float | None = None) -> None: ...
    @staticmethod
    def default() -> FissionGasInventory: ...

class FissionGasReleaseModel:
    def upstream_name(self) -> str: ...
    def is_implemented(self) -> bool: ...
    @staticmethod
    def Disabled() -> FissionGasReleaseModel: ...
    @staticmethod
    def TransientVenting(a0: TransientVentingThresholds) -> FissionGasReleaseModel: ...
    @staticmethod
    def Sciantix() -> FissionGasReleaseModel: ...
    def variant(self) -> str: ...

class FuelCellConditions:
    temperature: float
    burnup: float
    damage: float
    @staticmethod
    def fresh(temperature: float) -> FuelCellConditions: ...
    def __init__(self, temperature: float, burnup: float, damage: float) -> None: ...

class GasReleaseOutcome:
    gas_released: float
    helium_released: float
    intragranular_swelling: float
    intergranular_swelling: float
    def __init__(self, gas_released: float | None = None, helium_released: float | None = None, intragranular_swelling: float | None = None, intergranular_swelling: float | None = None) -> None: ...
    @staticmethod
    def default() -> GasReleaseOutcome: ...

class ReleasedGasMoles:
    xenon: float
    krypton: float
    helium: float
    def total(self) -> float: ...
    def volume_at_reference_conditions(self) -> float: ...
    def __init__(self, xenon: float | None = None, krypton: float | None = None, helium: float | None = None) -> None: ...
    @staticmethod
    def default() -> ReleasedGasMoles: ...

class TransientVentingThresholds:
    release_hbs: bool
    hbs_burnup_threshold: float
    hbs_temperature_threshold: float
    damage_threshold: float
    def __init__(self, release_hbs: bool | None = None, hbs_burnup_threshold: float | None = None, hbs_temperature_threshold: float | None = None, damage_threshold: float | None = None) -> None: ...
    @staticmethod
    def default() -> TransientVentingThresholds: ...

class AxialSlicing:
    def n_slices(self) -> int | None: ...
    def total_height(self) -> float | None: ...
    def slice_index(self, height_above_bottom: float) -> int | None: ...
    def assign(self, axial_coordinates: list[float], material_bottom: float) -> list[int | None]: ...
    @staticmethod
    def None_() -> AxialSlicing: ...
    @staticmethod
    def ByMaterial(slice_heights: list[float]) -> AxialSlicing: ...
    @staticmethod
    def ByPellets(pellet_heights: list[float]) -> AxialSlicing: ...
    @staticmethod
    def AutoAxial(precision: float) -> AxialSlicing: ...
    def variant(self) -> str: ...

class FreeVolumeRegion:
    def name(self) -> str: ...
    def volume(self) -> float: ...
    def v_over_t(self) -> float: ...
    def effective_temperature(self) -> float: ...

class GapConductance:
    gas: float
    radiation: float
    contact: float
    def total(self) -> float: ...
    def contact_fraction(self) -> float: ...
    def __init__(self, gas: float | None = None, radiation: float | None = None, contact: float | None = None) -> None: ...
    @staticmethod
    def default() -> GapConductance: ...

class GapConductanceModel:
    def evaluate(self, gas: GapGasMixture, gas_pressure: float, surfaces: GapSurfaces) -> GapConductance: ...
    @staticmethod
    def Fixed(coefficient: float) -> GapConductanceModel: ...
    @staticmethod
    def FuelRodFrapcon(radial_gap_width: float, scaling: GapConductanceScaling) -> GapConductanceModel: ...
    @staticmethod
    def TrisoSpherical(reference_radius: float, inner_radius: float, outer_radius: float, jump_distance: TrisoJumpDistance) -> GapConductanceModel: ...
    def variant(self) -> str: ...

class GapConductanceScaling:
    gas_factor: float
    gas_offset: float
    radiation_factor: float
    radiation_offset: float
    contact_factor: float
    contact_offset: float
    def __init__(self, gas_factor: float | None = None, gas_offset: float | None = None, radiation_factor: float | None = None, radiation_offset: float | None = None, contact_factor: float | None = None, contact_offset: float | None = None) -> None: ...
    @staticmethod
    def default() -> GapConductanceScaling: ...

class GapGasMixture:
    def mass_fraction(self, species: GapGasSpecies) -> float: ...
    def mole_fraction(self, species: GapGasSpecies) -> float: ...
    def mass_fractions(self) -> list[float]: ...
    def mole_fractions(self) -> list[float]: ...
    def mass(self) -> float: ...
    def moles(self) -> float: ...
    def specific_gas_constant(self) -> float: ...
    def density(self, p: float, t: float) -> float: ...
    def conductivity(self, t: float) -> float: ...
    def accommodation_coefficient(self, t: float) -> float: ...

class GapGasSpecies:
    def index(self) -> int: ...
    def symbol(self) -> str: ...
    def molar_mass_g_per_mol(self) -> float: ...
    def molar_mass(self) -> float: ...
    def conductivity_coefficients(self) -> tuple[float, float]: ...
    def has_placeholder_conductivity(self) -> bool: ...
    def conductivity(self, t: float) -> float: ...
    @staticmethod
    def Helium() -> GapGasSpecies: ...
    @staticmethod
    def Neon() -> GapGasSpecies: ...
    @staticmethod
    def Argon() -> GapGasSpecies: ...
    @staticmethod
    def Krypton() -> GapGasSpecies: ...
    @staticmethod
    def Xenon() -> GapGasSpecies: ...
    @staticmethod
    def Radon() -> GapGasSpecies: ...
    def variant(self) -> str: ...

class GapSurfaces:
    fuel_temperature: float
    clad_temperature: float
    fuel_roughness: float
    clad_roughness: float
    fuel_emissivity: float
    clad_emissivity: float
    fuel_conductivity: float
    clad_conductivity: float
    interface_pressure: float
    meyer_hardness: float
    @staticmethod
    def lwr_open_gap(fuel_temperature: float, clad_temperature: float) -> GapSurfaces: ...
    def mean_temperature(self) -> float: ...
    def __init__(self, fuel_temperature: float, clad_temperature: float, fuel_roughness: float, clad_roughness: float, fuel_emissivity: float, clad_emissivity: float, fuel_conductivity: float, clad_conductivity: float, interface_pressure: float, meyer_hardness: float) -> None: ...

class GasPressureModel:
    def pressure(self, time: float, free_volume: RodFreeVolume, moles: float) -> float: ...
    @staticmethod
    def FromFreeVolume() -> GasPressureModel: ...
    @staticmethod
    def Fixed(a0: float) -> GasPressureModel: ...
    @staticmethod
    def Tabulated(a0: list[tuple[float, float]]) -> GasPressureModel: ...
    def variant(self) -> str: ...

class PenaltyContact:
    penalty_scale: float
    penetration_tolerance: float
    relaxation: float
    def penalty_factor(self, fuel_stiffness: float, clad_stiffness: float) -> float: ...
    def interface_pressure(self, signed_radial_gap: float, penalty_factor: float, average_cell_spacing: float, previous: float) -> float: ...
    def interface_pressure_no_latch(self, signed_radial_gap: float, penalty_factor: float, average_cell_spacing: float, previous: float) -> float: ...
    def __init__(self, penalty_scale: float | None = None, penetration_tolerance: float | None = None, relaxation: float | None = None) -> None: ...
    @staticmethod
    def default() -> PenaltyContact: ...

class RodFreeVolume:
    def __init__(self, ) -> None: ...
    def with_region(self, region: FreeVolumeRegion) -> RodFreeVolume: ...
    def push(self, region: FreeVolumeRegion) -> None: ...
    def regions(self) -> list[FreeVolumeRegion]: ...
    def total_volume(self) -> float: ...
    def total_v_over_t(self) -> float: ...
    def effective_temperature(self) -> float: ...
    def volume_weighted_temperature(self) -> float: ...
    def pressure(self, moles: float) -> float: ...
    def initial_mass(self, gas: GapGasMixture, p: float) -> float: ...
    @staticmethod
    def default() -> RodFreeVolume: ...

class SliceAverage:
    def means(self) -> list[float]: ...
    def slice_volumes(self) -> list[float]: ...
    def n_slices(self) -> int: ...
    def mean(self, s: int) -> float | None: ...
    def slice_volume(self, s: int) -> float | None: ...
    def empty_slices(self) -> list[int]: ...

class TrisoJumpDistance:
    @staticmethod
    def Frapcon() -> TrisoJumpDistance: ...
    @staticmethod
    def Prescribed(inner: float, outer: float) -> TrisoJumpDistance: ...
    def variant(self) -> str: ...

class MaterialState:
    temperature: float
    burnup: float
    fast_fluence: float
    porosity: float
    swelling: float
    densification: float
    pu_fraction: float
    oxygen_deviation: float
    gadolinia_fraction: float
    cold_work: float
    oxygen_content: float
    hydrogen_content: float
    @staticmethod
    def fresh(temperature: float) -> MaterialState: ...
    def density_fraction(self) -> float: ...
    def linear_swelling(self) -> float: ...
    def __init__(self, temperature: float, burnup: float, fast_fluence: float, porosity: float, swelling: float, densification: float, pu_fraction: float, oxygen_deviation: float, gadolinia_fraction: float, cold_work: float, oxygen_content: float, hydrogen_content: float) -> None: ...

class DensificationModel:
    def value(self, state: MaterialState) -> float: ...
    def linear(self, state: MaterialState) -> float: ...
    @staticmethod
    def Zero() -> DensificationModel: ...
    @staticmethod
    def Empirical(density_fraction: float, density_change: float, saturation_burnup: float) -> DensificationModel: ...
    @staticmethod
    def Uo2Frapcon(density_fraction: float, resintering_density_change: float, sintering_temperature: float) -> DensificationModel: ...
    def variant(self) -> str: ...

class FrapconRelocationForm:
    @staticmethod
    def Modified() -> FrapconRelocationForm: ...
    @staticmethod
    def Legacy() -> FrapconRelocationForm: ...
    def variant(self) -> str: ...
    @staticmethod
    def default() -> FrapconRelocationForm: ...

class RelocationModel:
    def value(self, state: MaterialState) -> float: ...
    def gap_closure_fraction(self, state: MaterialState) -> float: ...
    def radial_displacement(self, state: MaterialState) -> float: ...
    @staticmethod
    def Zero() -> RelocationModel: ...
    @staticmethod
    def Uo2Frapcon(cold_gap: float, cold_pellet_diameter: float, linear_power: float, form: FrapconRelocationForm) -> RelocationModel: ...
    def variant(self) -> str: ...

class BisonZircaloyCladType:
    def coefficients(self) -> tuple[float, float]: ...
    @staticmethod
    def Sra() -> BisonZircaloyCladType: ...
    @staticmethod
    def Rxa() -> BisonZircaloyCladType: ...
    @staticmethod
    def Pra() -> BisonZircaloyCladType: ...
    @staticmethod
    def Zirlo() -> BisonZircaloyCladType: ...
    @staticmethod
    def Escore() -> BisonZircaloyCladType: ...
    @staticmethod
    def M5() -> BisonZircaloyCladType: ...
    def variant(self) -> str: ...
    @staticmethod
    def default() -> BisonZircaloyCladType: ...

class SwellingModel:
    def strain(self, state: MaterialState) -> SwellingStrain: ...
    def value(self, state: MaterialState) -> float: ...
    @staticmethod
    def Zero() -> SwellingModel: ...
    @staticmethod
    def Constant(swelling_rate: float) -> SwellingModel: ...
    @staticmethod
    def Uo2Frapcon(theoretical_density: float) -> SwellingModel: ...
    @staticmethod
    def Uo2Matpro(theoretical_density: float) -> SwellingModel: ...
    @staticmethod
    def FbrMox(gap_open: bool) -> SwellingModel: ...
    @staticmethod
    def FeCrAl(rate: float) -> SwellingModel: ...
    @staticmethod
    def GrowthBisonZircaloy(clad_type: BisonZircaloyCladType) -> SwellingModel: ...
    @staticmethod
    def GrowthAim11515Ti() -> SwellingModel: ...
    @staticmethod
    def GrowthGeneralized1515Ti() -> SwellingModel: ...
    @staticmethod
    def WrightShamHastelloyN() -> SwellingModel: ...
    def variant(self) -> str: ...

class SwellingStrain:
    radial: float
    hoop: float
    axial: float
    def __init__(self, radial: float, hoop: float, axial: float) -> None: ...
    @staticmethod
    def isotropic(volumetric: float) -> SwellingStrain: ...
    def volumetric(self) -> float: ...

class ConductivityModel:
    @staticmethod
    def parfume_buffer_default() -> ConductivityModel: ...
    def name(self) -> str: ...
    def temperature_range(self) -> tuple[float, float]: ...
    def value(self, state: MaterialState) -> float: ...
    @staticmethod
    def Constant(a0: float) -> ConductivityModel: ...
    @staticmethod
    def MatproUo2() -> ConductivityModel: ...
    @staticmethod
    def NfirUo2() -> ConductivityModel: ...
    @staticmethod
    def Ifa601Uo2() -> ConductivityModel: ...
    @staticmethod
    def BrancheriaMox() -> ConductivityModel: ...
    @staticmethod
    def KatoMox(americium_atom_fraction: float, neptunium_atom_fraction: float) -> ConductivityModel: ...
    @staticmethod
    def LanningBeyerMox() -> ConductivityModel: ...
    @staticmethod
    def MagniMamox(americium_atom_fraction: float, neptunium_atom_fraction: float) -> ConductivityModel: ...
    @staticmethod
    def PhilipponneauMox() -> ConductivityModel: ...
    @staticmethod
    def RelapZircaloy() -> ConductivityModel: ...
    @staticmethod
    def Molybdenum() -> ConductivityModel: ...
    @staticmethod
    def SwindemanHastelloyN() -> ConductivityModel: ...
    @staticmethod
    def Tobbe1515Ti() -> ConductivityModel: ...
    @staticmethod
    def ParfumeBuffer(initial_density: float, theoretical_density: float, initial_conductivity: float, theoretical_conductivity: float) -> ConductivityModel: ...
    @staticmethod
    def ParfumeSiC() -> ConductivityModel: ...
    def variant(self) -> str: ...

class DensityModel:
    def name(self) -> str: ...
    def validity_range(self) -> tuple[float, float]: ...
    def value(self, state: MaterialState) -> float: ...
    @staticmethod
    def Constant(density: float) -> DensityModel: ...
    @staticmethod
    def UO2(theoretical_density: float) -> DensityModel: ...
    @staticmethod
    def UPuO2(theoretical_density: float) -> DensityModel: ...
    @staticmethod
    def Molybdenum(density: float) -> DensityModel: ...
    @staticmethod
    def IAEAZy() -> DensityModel: ...
    @staticmethod
    def Schumann1515Ti(reference_density: float) -> DensityModel: ...
    def variant(self) -> str: ...

class EmissivityModel:
    def name(self) -> str: ...
    def validity_range(self) -> tuple[float, float]: ...
    def value(self, state: MaterialState) -> float: ...
    @staticmethod
    def Constant(emissivity: float) -> EmissivityModel: ...
    @staticmethod
    def RelapUO2() -> EmissivityModel: ...
    @staticmethod
    def Zy(emissivity: float) -> EmissivityModel: ...
    @staticmethod
    def Molybdenum(emissivity: float) -> EmissivityModel: ...
    def variant(self) -> str: ...

class HeatCapacityModel:
    def name(self) -> str: ...
    def temperature_range(self) -> tuple[float, float]: ...
    def value(self, state: MaterialState) -> float: ...
    @staticmethod
    def Constant(a0: float) -> HeatCapacityModel: ...
    @staticmethod
    def MatproUo2() -> HeatCapacityModel: ...
    @staticmethod
    def MatproMox() -> HeatCapacityModel: ...
    @staticmethod
    def FinkMox() -> HeatCapacityModel: ...
    @staticmethod
    def MatproZircaloy() -> HeatCapacityModel: ...
    @staticmethod
    def IaeaZircaloy() -> HeatCapacityModel: ...
    @staticmethod
    def Banerjee1515Ti() -> HeatCapacityModel: ...
    @staticmethod
    def Molybdenum() -> HeatCapacityModel: ...
    @staticmethod
    def SneadSiC() -> HeatCapacityModel: ...
    def variant(self) -> str: ...

class PoissonRatioModel:
    def name(self) -> str: ...
    def temperature_range(self) -> tuple[float, float]: ...
    def value(self, state: MaterialState) -> float: ...
    def is_admissible(self, state: MaterialState) -> bool: ...
    @staticmethod
    def Constant(a0: float) -> PoissonRatioModel: ...
    @staticmethod
    def MatproUo2() -> PoissonRatioModel: ...
    @staticmethod
    def MatproMox() -> PoissonRatioModel: ...
    @staticmethod
    def ConstantZircaloy() -> PoissonRatioModel: ...
    @staticmethod
    def ConstantMolybdenum() -> PoissonRatioModel: ...
    @staticmethod
    def MatproZircaloy() -> PoissonRatioModel: ...
    @staticmethod
    def Tobbe1515Ti() -> PoissonRatioModel: ...
    def variant(self) -> str: ...

class ThermalExpansionModel:
    def name(self) -> str: ...
    def validity_range(self) -> tuple[float, float]: ...
    def reference_temperature(self) -> float | None: ...
    def strain(self, state: MaterialState) -> float: ...
    def principal_strains(self, state: MaterialState) -> list[float]: ...
    def coefficient(self, state: MaterialState) -> float: ...
    def principal_coefficients(self, state: MaterialState) -> list[float]: ...
    @staticmethod
    def Constant(alpha: float, t_ref: float) -> ThermalExpansionModel: ...
    @staticmethod
    def RelapUO2(t_ref: float) -> ThermalExpansionModel: ...
    @staticmethod
    def MatproUPuO2() -> ThermalExpansionModel: ...
    @staticmethod
    def MartinUPuO2(t_ref: float) -> ThermalExpansionModel: ...
    @staticmethod
    def LemehovUPuO2() -> ThermalExpansionModel: ...
    @staticmethod
    def MAMOX(t_ref: float) -> ThermalExpansionModel: ...
    @staticmethod
    def MatproZy(t_ref: float) -> ThermalExpansionModel: ...
    @staticmethod
    def Gehr1515Ti() -> ThermalExpansionModel: ...
    @staticmethod
    def Molybdenum() -> ThermalExpansionModel: ...
    @staticmethod
    def SneadSiC(t_stress_free: float) -> ThermalExpansionModel: ...
    @staticmethod
    def SwindemanHastelloyN(t_ref: float) -> ThermalExpansionModel: ...
    @staticmethod
    def PARFUMEBuffer(t_ref: float) -> ThermalExpansionModel: ...
    @staticmethod
    def PARFUMEPyC(t_ref: float, anisotropy_factor: float) -> ThermalExpansionModel: ...
    @staticmethod
    def PARFUMESiC(alpha: float, t_ref: float) -> ThermalExpansionModel: ...
    def variant(self) -> str: ...

class YoungModulusModel:
    def name(self) -> str: ...
    def temperature_range(self) -> tuple[float, float]: ...
    def value(self, state: MaterialState) -> float: ...
    @staticmethod
    def Constant(a0: float) -> YoungModulusModel: ...
    @staticmethod
    def MatproUo2() -> YoungModulusModel: ...
    @staticmethod
    def MatproMox() -> YoungModulusModel: ...
    @staticmethod
    def SckCenMox() -> YoungModulusModel: ...
    @staticmethod
    def MatproZircaloy() -> YoungModulusModel: ...
    @staticmethod
    def HofmanD9() -> YoungModulusModel: ...
    @staticmethod
    def BisonMolybdenum() -> YoungModulusModel: ...
    @staticmethod
    def Tobbe1515Ti() -> YoungModulusModel: ...
    @staticmethod
    def WatrousHastelloyN() -> YoungModulusModel: ...
    @staticmethod
    def SneadSiC(porosity_coefficient: float) -> YoungModulusModel: ...
    @staticmethod
    def ParfumeBuffer(density: float) -> YoungModulusModel: ...
    @staticmethod
    def ParfumePyC(density: float, bacon_anisotropy_factor: float, crystallite_diameter: float) -> YoungModulusModel: ...
    @staticmethod
    def ParfumeSiC() -> YoungModulusModel: ...
    def variant(self) -> str: ...

class CreepStepReport:
    mechanics: MechanicsReport
    max_equivalent_inelastic_increment: float
    average_equivalent_inelastic_increment: float
    max_equivalent_creep_increment: float
    max_equivalent_plastic_increment: float
    yielding_cells: int
    suggested_next_time_step: float
    def __init__(self, mechanics: MechanicsReport, max_equivalent_inelastic_increment: float, average_equivalent_inelastic_increment: float, max_equivalent_creep_increment: float, max_equivalent_plastic_increment: float, yielding_cells: int, suggested_next_time_step: float) -> None: ...

class Eigenstrain:
    thermal: float
    swelling: float
    densification: float
    relocation: float
    def total(self) -> float: ...
    def __init__(self, thermal: float | None = None, swelling: float | None = None, densification: float | None = None, relocation: float | None = None) -> None: ...
    @staticmethod
    def default() -> Eigenstrain: ...

class LinearElastic:
    young: float
    poisson: float
    def shear_modulus(self) -> float: ...
    def lame_lambda(self) -> float: ...
    def three_k(self) -> float: ...
    def two_mu_plus_lambda(self) -> float: ...
    def __init__(self, young: float, poisson: float) -> None: ...

class MechanicsReport:
    iterations: int
    final_change: float
    converged: bool
    max_displacement: float
    def __init__(self, iterations: int, final_change: float, converged: bool, max_displacement: float) -> None: ...

class MechanicsSolver:
    def set_linear_solver(self, settings: outram_foam_basic_lib.SolverSettings) -> None: ...
    def set_corrector_control(self, n_correctors: int, tolerance: float) -> None: ...
    def set_density(self, density: float) -> None: ...
    def set_uniform_eigenstrain(self, eigenstrain: Eigenstrain) -> None: ...
    def set_eigenstrain_field(self, values: list[float]) -> None: ...
    def set_uniform_material_state(self, state: MaterialState) -> None: ...
    def set_material_state_field(self, values: list[MaterialState]) -> None: ...
    def set_uniform_irradiation(self, irradiation: IrradiationState) -> None: ...
    def set_irradiation_field(self, values: list[IrradiationState]) -> None: ...
    def set_creep_time_step_control(self, control: CreepTimeStepControl) -> None: ...
    def set_inelastic_tolerance(self, tolerance: float) -> None: ...
    def rheology_state(self, cell: int) -> RheologyState: ...
    def inelastic_strain(self, cell: int) -> outram_foam_basic_lib.SymmTensor: ...
    def displacement(self) -> outram_foam_basic_lib.VolVectorField: ...
    def stress(self) -> outram_foam_basic_lib.VolSymmTensorField: ...
    def material(self) -> LinearElastic: ...
    def solve_quasi_static(self) -> MechanicsReport: ...
    def solve_transient(self, dt: float) -> MechanicsReport: ...
    def advance_time(self) -> None: ...

class ConstitutiveLaw:
    @staticmethod
    def perfectly_plastic(sigma_y: float) -> ConstitutiveLaw: ...
    def creep_model(self) -> CreepModel: ...
    @staticmethod
    def Elastic() -> ConstitutiveLaw: ...
    @staticmethod
    def MisesPlasticity(yield_stress: YieldStressModel) -> ConstitutiveLaw: ...
    @staticmethod
    def MisesPlasticCreep(yield_stress: YieldStressModel, creep: CreepModel) -> ConstitutiveLaw: ...
    def variant(self) -> str: ...

class CreepIncrement:
    equivalent: float
    equivalent_primary: float
    von_mises_stress: float
    iterations: int
    def __init__(self, equivalent: float, equivalent_primary: float, von_mises_stress: float, iterations: int) -> None: ...

class CreepModel:
    @staticmethod
    def None_() -> CreepModel: ...
    @staticmethod
    def PowerLaw(b: float, sigma_c: float, n: float) -> CreepModel: ...
    @staticmethod
    def Limback(clad_type: ZircaloyCladType) -> CreepModel: ...
    @staticmethod
    def Matpro(sakai_correction: bool) -> CreepModel: ...
    def variant(self) -> str: ...

class CreepTimeStepControl:
    max_average_increment: float
    max_maximum_increment: float
    def next_time_step(self, average_increment: float, max_increment: float, previous_dt: float) -> float: ...
    def __init__(self, max_average_increment: float | None = None, max_maximum_increment: float | None = None) -> None: ...
    @staticmethod
    def default() -> CreepTimeStepControl: ...

class HardeningCurve:
    def yield_stress(self, eq_plastic_strain: float) -> float: ...
    def slope(self, eq_plastic_strain: float) -> float: ...

class IrradiationState:
    fast_flux: float
    fission_rate: float
    grain_radius: float
    def __init__(self, fast_flux: float | None = None, fission_rate: float | None = None, grain_radius: float | None = None) -> None: ...
    @staticmethod
    def default() -> IrradiationState: ...

class Rheology:
    def n_cells(self) -> int: ...
    @staticmethod
    def ByMaterial(a0: RheologyByMaterial) -> Rheology: ...
    def variant(self) -> str: ...

class RheologyByMaterial:
    def n_materials(self) -> int: ...
    def n_cells(self) -> int: ...

class RheologyInputs:
    elastic: LinearElastic
    mechanical_strain: outram_foam_basic_lib.SymmTensor
    material: MaterialState
    irradiation: IrradiationState
    dt: float
    equivalent_strain_rate: float
    @staticmethod
    def quasi_static(elastic: LinearElastic, mechanical_strain: outram_foam_basic_lib.SymmTensor, material: MaterialState) -> RheologyInputs: ...
    def __init__(self, elastic: LinearElastic, mechanical_strain: outram_foam_basic_lib.SymmTensor, material: MaterialState, irradiation: IrradiationState, dt: float, equivalent_strain_rate: float) -> None: ...

class RheologyState:
    plastic_strain: outram_foam_basic_lib.SymmTensor
    equivalent_plastic_strain: float
    creep_strain: outram_foam_basic_lib.SymmTensor
    equivalent_creep_strain: float
    equivalent_primary_creep_strain: float
    yield_stress: float
    @staticmethod
    def pristine() -> RheologyState: ...
    def advance(self, correction: StressCorrection) -> None: ...
    def inelastic_strain(self) -> outram_foam_basic_lib.SymmTensor: ...
    def __init__(self, plastic_strain: outram_foam_basic_lib.SymmTensor | None = None, equivalent_plastic_strain: float | None = None, creep_strain: outram_foam_basic_lib.SymmTensor | None = None, equivalent_creep_strain: float | None = None, equivalent_primary_creep_strain: float | None = None, yield_stress: float | None = None) -> None: ...
    @staticmethod
    def default() -> RheologyState: ...

class StressCorrection:
    stress: outram_foam_basic_lib.SymmTensor
    elastic_strain: outram_foam_basic_lib.SymmTensor
    plastic_strain_increment: outram_foam_basic_lib.SymmTensor
    equivalent_plastic_strain_increment: float
    creep_strain_increment: outram_foam_basic_lib.SymmTensor
    equivalent_creep_strain_increment: float
    equivalent_primary_creep_strain_increment: float
    yield_stress: float
    yielding: bool
    iterations: int
    def von_mises_stress(self) -> float: ...
    def hydrostatic_stress(self) -> float: ...
    def __init__(self, stress: outram_foam_basic_lib.SymmTensor, elastic_strain: outram_foam_basic_lib.SymmTensor, plastic_strain_increment: outram_foam_basic_lib.SymmTensor, equivalent_plastic_strain_increment: float, creep_strain_increment: outram_foam_basic_lib.SymmTensor, equivalent_creep_strain_increment: float, equivalent_primary_creep_strain_increment: float, yield_stress: float, yielding: bool, iterations: int) -> None: ...

class YieldStressModel:
    @staticmethod
    def Constant(sigma_y: float) -> YieldStressModel: ...
    @staticmethod
    def Hardening(curve: HardeningCurve) -> YieldStressModel: ...
    @staticmethod
    def Fraptran() -> YieldStressModel: ...
    def variant(self) -> str: ...

class ZircaloyCladType:
    def thermal_prefactor(self) -> float: ...
    def activation_energy(self) -> float: ...
    def irradiation_coefficient(self) -> float: ...
    def stress_exponent(self, von_mises_stress: float) -> float: ...
    @staticmethod
    def Sra() -> ZircaloyCladType: ...
    @staticmethod
    def Rxa() -> ZircaloyCladType: ...
    @staticmethod
    def Pra() -> ZircaloyCladType: ...
    @staticmethod
    def Zirlo() -> ZircaloyCladType: ...
    def variant(self) -> str: ...
    @staticmethod
    def default() -> ZircaloyCladType: ...

class AsterBehaviour:
    def aster_name(self) -> str: ...
    def num_lc(self) -> int: ...
    def n_state_variables(self) -> int: ...
    def state_variable_names(self) -> list[str]: ...
    def lc_types(self) -> list[str]: ...
    def deformations(self) -> list[str]: ...
    def integration_algorithms(self) -> list[str]: ...
    def modelisations(self) -> list[str]: ...
    def material_keywords(self) -> list[str]: ...
    def is_mfront(self) -> bool: ...
    def has_declared_state_variables(self) -> bool: ...
    def is_mechanical(self) -> bool: ...
    @staticmethod
    def from_aster_name(name: str) -> AsterBehaviour | None: ...
    @staticmethod
    def from_num_lc(num_lc: int) -> AsterBehaviour | None: ...
    @staticmethod
    def Acier() -> AsterBehaviour: ...
    @staticmethod
    def AcierMeca() -> AsterBehaviour: ...
    @staticmethod
    def AcierRevenu() -> AsterBehaviour: ...
    @staticmethod
    def Analytique() -> AsterBehaviour: ...
    @staticmethod
    def Arme() -> AsterBehaviour: ...
    @staticmethod
    def AsseCorn() -> AsterBehaviour: ...
    @staticmethod
    def Cable() -> AsterBehaviour: ...
    @staticmethod
    def ChocElasTrac() -> AsterBehaviour: ...
    @staticmethod
    def ChocEndo() -> AsterBehaviour: ...
    @staticmethod
    def ChocEndoPena() -> AsterBehaviour: ...
    @staticmethod
    def CritRupt() -> AsterBehaviour: ...
    @staticmethod
    def Dashpot() -> AsterBehaviour: ...
    @staticmethod
    def DdiPlasEndo() -> AsterBehaviour: ...
    @staticmethod
    def Deborst() -> AsterBehaviour: ...
    @staticmethod
    def Dhrc() -> AsterBehaviour: ...
    @staticmethod
    def DisBiliElas() -> AsterBehaviour: ...
    @staticmethod
    def DisChoc() -> AsterBehaviour: ...
    @staticmethod
    def DisContact() -> AsterBehaviour: ...
    @staticmethod
    def DisEcroCine() -> AsterBehaviour: ...
    @staticmethod
    def DisEcroTrac() -> AsterBehaviour: ...
    @staticmethod
    def DisGouj2eElas() -> AsterBehaviour: ...
    @staticmethod
    def DisGouj2ePlas() -> AsterBehaviour: ...
    @staticmethod
    def DisGricra() -> AsterBehaviour: ...
    @staticmethod
    def DisVisc() -> AsterBehaviour: ...
    @staticmethod
    def ElasMembraneNh() -> AsterBehaviour: ...
    @staticmethod
    def ElasMembraneSv() -> AsterBehaviour: ...
    @staticmethod
    def ElasPoutreGr() -> AsterBehaviour: ...
    @staticmethod
    def Fondation() -> AsterBehaviour: ...
    @staticmethod
    def GdefLog() -> AsterBehaviour: ...
    @staticmethod
    def GlrcDamage() -> AsterBehaviour: ...
    @staticmethod
    def GlrcDm() -> AsterBehaviour: ...
    @staticmethod
    def GreenLagrange() -> AsterBehaviour: ...
    @staticmethod
    def GrilleCineLine() -> AsterBehaviour: ...
    @staticmethod
    def GrilleIsotLine() -> AsterBehaviour: ...
    @staticmethod
    def GrotGdep() -> AsterBehaviour: ...
    @staticmethod
    def HoekBrownTot() -> AsterBehaviour: ...
    @staticmethod
    def Hydr() -> AsterBehaviour: ...
    @staticmethod
    def HydrEndo() -> AsterBehaviour: ...
    @staticmethod
    def HydrTabbal() -> AsterBehaviour: ...
    @staticmethod
    def HydrUtil() -> AsterBehaviour: ...
    @staticmethod
    def HydrVgc() -> AsterBehaviour: ...
    @staticmethod
    def HydrVgm() -> AsterBehaviour: ...
    @staticmethod
    def JointBandis() -> AsterBehaviour: ...
    @staticmethod
    def JoncEndoPlas() -> AsterBehaviour: ...
    @staticmethod
    def KitCg() -> AsterBehaviour: ...
    @staticmethod
    def KitH() -> AsterBehaviour: ...
    @staticmethod
    def KitHh() -> AsterBehaviour: ...
    @staticmethod
    def KitHh2() -> AsterBehaviour: ...
    @staticmethod
    def KitHh2m() -> AsterBehaviour: ...
    @staticmethod
    def KitHhm() -> AsterBehaviour: ...
    @staticmethod
    def KitHm() -> AsterBehaviour: ...
    @staticmethod
    def KitThh() -> AsterBehaviour: ...
    @staticmethod
    def KitThh2() -> AsterBehaviour: ...
    @staticmethod
    def KitThh2m() -> AsterBehaviour: ...
    @staticmethod
    def KitThhm() -> AsterBehaviour: ...
    @staticmethod
    def KitThm() -> AsterBehaviour: ...
    @staticmethod
    def KitThv() -> AsterBehaviour: ...
    @staticmethod
    def MetaGCine() -> AsterBehaviour: ...
    @staticmethod
    def MetaGCinePt() -> AsterBehaviour: ...
    @staticmethod
    def MetaGCinePtre() -> AsterBehaviour: ...
    @staticmethod
    def MetaGCineRe() -> AsterBehaviour: ...
    @staticmethod
    def MetaGIsot() -> AsterBehaviour: ...
    @staticmethod
    def MetaGIsotPt() -> AsterBehaviour: ...
    @staticmethod
    def MetaGIsotPtre() -> AsterBehaviour: ...
    @staticmethod
    def MetaGIsotRe() -> AsterBehaviour: ...
    @staticmethod
    def MetaPCineLine() -> AsterBehaviour: ...
    @staticmethod
    def MetaPIsotLine() -> AsterBehaviour: ...
    @staticmethod
    def MetaPIsotTrac() -> AsterBehaviour: ...
    @staticmethod
    def MetaVCineLine() -> AsterBehaviour: ...
    @staticmethod
    def MetaVIsotLine() -> AsterBehaviour: ...
    @staticmethod
    def MetaVIsotTrac() -> AsterBehaviour: ...
    @staticmethod
    def Multifibre() -> AsterBehaviour: ...
    @staticmethod
    def Petit() -> AsterBehaviour: ...
    @staticmethod
    def PetitReac() -> AsterBehaviour: ...
    @staticmethod
    def Pmf() -> AsterBehaviour: ...
    @staticmethod
    def ReguViscElas() -> AsterBehaviour: ...
    @staticmethod
    def RestEcroCine() -> AsterBehaviour: ...
    @staticmethod
    def RestEcroEcmi() -> AsterBehaviour: ...
    @staticmethod
    def RestEcroIsot() -> AsterBehaviour: ...
    @staticmethod
    def RuptFrag() -> AsterBehaviour: ...
    @staticmethod
    def SechBazant() -> AsterBehaviour: ...
    @staticmethod
    def SechGranger() -> AsterBehaviour: ...
    @staticmethod
    def SechMensi() -> AsterBehaviour: ...
    @staticmethod
    def SechNappe() -> AsterBehaviour: ...
    @staticmethod
    def SechRft() -> AsterBehaviour: ...
    @staticmethod
    def TherHydr() -> AsterBehaviour: ...
    @staticmethod
    def TherNl() -> AsterBehaviour: ...
    @staticmethod
    def Vide() -> AsterBehaviour: ...
    @staticmethod
    def ViscMaxwellMt() -> AsterBehaviour: ...
    @staticmethod
    def Zirc() -> AsterBehaviour: ...
    @staticmethod
    def ZircMeca() -> AsterBehaviour: ...
    @staticmethod
    def Edgar() -> AsterBehaviour: ...
    @staticmethod
    def Elas() -> AsterBehaviour: ...
    @staticmethod
    def InterfPouElas() -> AsterBehaviour: ...
    @staticmethod
    def LiquSatu() -> AsterBehaviour: ...
    @staticmethod
    def Ther() -> AsterBehaviour: ...
    @staticmethod
    def Gaz() -> AsterBehaviour: ...
    @staticmethod
    def InterfPouCine() -> AsterBehaviour: ...
    @staticmethod
    def ViscIsotLine() -> AsterBehaviour: ...
    @staticmethod
    def ViscIsotTrac() -> AsterBehaviour: ...
    @staticmethod
    def VmisIsotLine() -> AsterBehaviour: ...
    @staticmethod
    def VmisIsotPuis() -> AsterBehaviour: ...
    @staticmethod
    def VmisIsotTrac() -> AsterBehaviour: ...
    @staticmethod
    def Waeckel() -> AsterBehaviour: ...
    @staticmethod
    def Jma() -> AsterBehaviour: ...
    @staticmethod
    def LiquVape() -> AsterBehaviour: ...
    @staticmethod
    def VmisCineGc() -> AsterBehaviour: ...
    @staticmethod
    def VmisCineLine() -> AsterBehaviour: ...
    @staticmethod
    def VmisEcmiLine() -> AsterBehaviour: ...
    @staticmethod
    def VmisEcmiTrac() -> AsterBehaviour: ...
    @staticmethod
    def LiquVapeGaz() -> AsterBehaviour: ...
    @staticmethod
    def ViscCin1Chab() -> AsterBehaviour: ...
    @staticmethod
    def ViscCin2Chab() -> AsterBehaviour: ...
    @staticmethod
    def ViscCin2Memo() -> AsterBehaviour: ...
    @staticmethod
    def ViscCin2Nrad() -> AsterBehaviour: ...
    @staticmethod
    def ViscMemoNrad() -> AsterBehaviour: ...
    @staticmethod
    def VmisCin1Chab() -> AsterBehaviour: ...
    @staticmethod
    def VmisCin2Chab() -> AsterBehaviour: ...
    @staticmethod
    def VmisCin2Memo() -> AsterBehaviour: ...
    @staticmethod
    def VmisCin2Nrad() -> AsterBehaviour: ...
    @staticmethod
    def VmisMemoNrad() -> AsterBehaviour: ...
    @staticmethod
    def LiquGaz() -> AsterBehaviour: ...
    @staticmethod
    def LiquGazAtm() -> AsterBehaviour: ...
    @staticmethod
    def EndoOrthBeton() -> AsterBehaviour: ...
    @staticmethod
    def Mazars() -> AsterBehaviour: ...
    @staticmethod
    def MazarsUnil() -> AsterBehaviour: ...
    @staticmethod
    def BetonReglePr() -> AsterBehaviour: ...
    @staticmethod
    def LiquAdGazVape() -> AsterBehaviour: ...
    @staticmethod
    def CzmExpReg() -> AsterBehaviour: ...
    @staticmethod
    def LiquAdGaz() -> AsterBehaviour: ...
    @staticmethod
    def CzmLinReg() -> AsterBehaviour: ...
    @staticmethod
    def JointBa() -> AsterBehaviour: ...
    @staticmethod
    def KitMeta() -> AsterBehaviour: ...
    @staticmethod
    def DruckPrager() -> AsterBehaviour: ...
    @staticmethod
    def NortonHoff() -> AsterBehaviour: ...
    @staticmethod
    def ViscTaheri() -> AsterBehaviour: ...
    @staticmethod
    def ElasHyper() -> AsterBehaviour: ...
    @staticmethod
    def BetonUmlv() -> AsterBehaviour: ...
    @staticmethod
    def CamClay() -> AsterBehaviour: ...
    @staticmethod
    def Cjs() -> AsterBehaviour: ...
    @staticmethod
    def CorrAcier() -> AsterBehaviour: ...
    @staticmethod
    def Rankine() -> AsterBehaviour: ...
    @staticmethod
    def BetonGranger() -> AsterBehaviour: ...
    @staticmethod
    def BetonGrangerV() -> AsterBehaviour: ...
    @staticmethod
    def GranIrraLog() -> AsterBehaviour: ...
    @staticmethod
    def LemaitreIrra() -> AsterBehaviour: ...
    @staticmethod
    def LemaSeuil() -> AsterBehaviour: ...
    @staticmethod
    def ViscIrraLog() -> AsterBehaviour: ...
    @staticmethod
    def Lemaitre() -> AsterBehaviour: ...
    @staticmethod
    def Irrad3m() -> AsterBehaviour: ...
    @staticmethod
    def RoussPr() -> AsterBehaviour: ...
    @staticmethod
    def RoussVisc() -> AsterBehaviour: ...
    @staticmethod
    def Vendochab() -> AsterBehaviour: ...
    @staticmethod
    def ViscEndoLema() -> AsterBehaviour: ...
    @staticmethod
    def Hayhurst() -> AsterBehaviour: ...
    @staticmethod
    def Norton() -> AsterBehaviour: ...
    @staticmethod
    def Viscochab() -> AsterBehaviour: ...
    @staticmethod
    def HoekBrown() -> AsterBehaviour: ...
    @staticmethod
    def HoekBrownEff() -> AsterBehaviour: ...
    @staticmethod
    def Laigle() -> AsterBehaviour: ...
    @staticmethod
    def Hujeux() -> AsterBehaviour: ...
    @staticmethod
    def Letk() -> AsterBehaviour: ...
    @staticmethod
    def EndoIsotBeton() -> AsterBehaviour: ...
    @staticmethod
    def Rousselier() -> AsterBehaviour: ...
    @staticmethod
    def Sans() -> AsterBehaviour: ...
    @staticmethod
    def CzmOuvMix() -> AsterBehaviour: ...
    @staticmethod
    def DruckPragNA() -> AsterBehaviour: ...
    @staticmethod
    def CzmTacMix() -> AsterBehaviour: ...
    @staticmethod
    def ViscDrucPrag() -> AsterBehaviour: ...
    @staticmethod
    def CzmFatMix() -> AsterBehaviour: ...
    @staticmethod
    def JointMecaRupt() -> AsterBehaviour: ...
    @staticmethod
    def CzmTuron() -> AsterBehaviour: ...
    @staticmethod
    def EndoScalaire() -> AsterBehaviour: ...
    @staticmethod
    def EndoHeterogene() -> AsterBehaviour: ...
    @staticmethod
    def JointMecaEndo() -> AsterBehaviour: ...
    @staticmethod
    def JointMecaFrot() -> AsterBehaviour: ...
    @staticmethod
    def CzmTraMix() -> AsterBehaviour: ...
    @staticmethod
    def Umat() -> AsterBehaviour: ...
    @staticmethod
    def CzmLabMix() -> AsterBehaviour: ...
    @staticmethod
    def VmisJohnCook() -> AsterBehaviour: ...
    @staticmethod
    def MohrCoulomb() -> AsterBehaviour: ...
    @staticmethod
    def CzmExpMix() -> AsterBehaviour: ...
    @staticmethod
    def EndoFissExp() -> AsterBehaviour: ...
    @staticmethod
    def BetonAgeing() -> AsterBehaviour: ...
    @staticmethod
    def BetonBurger() -> AsterBehaviour: ...
    @staticmethod
    def Barcelone() -> AsterBehaviour: ...
    @staticmethod
    def Cssm() -> AsterBehaviour: ...
    @staticmethod
    def CzmMfront() -> AsterBehaviour: ...
    @staticmethod
    def ElasHyperVisc() -> AsterBehaviour: ...
    @staticmethod
    def Gonfelas() -> AsterBehaviour: ...
    @staticmethod
    def HyperHill() -> AsterBehaviour: ...
    @staticmethod
    def Iwan() -> AsterBehaviour: ...
    @staticmethod
    def Mcc() -> AsterBehaviour: ...
    @staticmethod
    def MetaLemaAni() -> AsterBehaviour: ...
    @staticmethod
    def Mfront() -> AsterBehaviour: ...
    @staticmethod
    def MetaacierepilPt() -> AsterBehaviour: ...
    @staticmethod
    def Mohrcoulombas() -> AsterBehaviour: ...
    @staticmethod
    def NlhCsrm() -> AsterBehaviour: ...
    @staticmethod
    def ViscIsotPlas() -> AsterBehaviour: ...
    @staticmethod
    def Lkr() -> AsterBehaviour: ...
    @staticmethod
    def EndoLocaExp() -> AsterBehaviour: ...
    @staticmethod
    def ViscMaxwell() -> AsterBehaviour: ...
    @staticmethod
    def Gtn() -> AsterBehaviour: ...
    @staticmethod
    def ViscGtn() -> AsterBehaviour: ...
    @staticmethod
    def ViscIsotNl() -> AsterBehaviour: ...
    @staticmethod
    def VmisIsotNl() -> AsterBehaviour: ...
    @staticmethod
    def CzmElasMix() -> AsterBehaviour: ...
    @staticmethod
    def KicheninNl() -> AsterBehaviour: ...
    @staticmethod
    def CzmFrotMix() -> AsterBehaviour: ...
    @staticmethod
    def ElasVmisLine() -> AsterBehaviour: ...
    @staticmethod
    def ElasVmisPuis() -> AsterBehaviour: ...
    @staticmethod
    def ElasVmisTrac() -> AsterBehaviour: ...
    @staticmethod
    def EndoLocaTc() -> AsterBehaviour: ...
    @staticmethod
    def RelaxAcier() -> AsterBehaviour: ...
    @staticmethod
    def VmisAsymLine() -> AsterBehaviour: ...
    @staticmethod
    def ElasIsotEner() -> AsterBehaviour: ...
    @staticmethod
    def ElasIsotIncr() -> AsterBehaviour: ...
    @staticmethod
    def BetonDoubleDp() -> AsterBehaviour: ...
    @staticmethod
    def Monocristal() -> AsterBehaviour: ...
    @staticmethod
    def Polycristal() -> AsterBehaviour: ...
    @staticmethod
    def BetonRag() -> AsterBehaviour: ...
    @staticmethod
    def CableGaineFrot() -> AsterBehaviour: ...
    @staticmethod
    def FluaPoroBeton() -> AsterBehaviour: ...
    @staticmethod
    def EndoPoroBeton() -> AsterBehaviour: ...
    @staticmethod
    def FluaEndoPoro() -> AsterBehaviour: ...
    @staticmethod
    def RgiBeton() -> AsterBehaviour: ...
    @staticmethod
    def RgiBetonBa() -> AsterBehaviour: ...
    @staticmethod
    def SimoMiehe() -> AsterBehaviour: ...
    @staticmethod
    def KitDdi() -> AsterBehaviour: ...
    def variant(self) -> str: ...

class AsterVoigt:
    def components(self) -> list[float]: ...
    @staticmethod
    def from_tensor(t: outram_foam_basic_lib.SymmTensor) -> AsterVoigt: ...
    def to_tensor(self) -> outram_foam_basic_lib.SymmTensor: ...
    def dot(self, other: AsterVoigt) -> float: ...
    def norm(self) -> float: ...
    def __init__(self) -> None: ...
    @staticmethod
    def default() -> AsterVoigt: ...

class BackStress:
    alpha1: outram_foam_basic_lib.SymmTensor
    alpha2: outram_foam_basic_lib.SymmTensor
    @staticmethod
    def zero() -> BackStress: ...
    def stress(self, c1: float, c2: float) -> outram_foam_basic_lib.SymmTensor: ...
    def equivalent_stress(self, c1: float, c2: float) -> float: ...
    def __init__(self, alpha1: outram_foam_basic_lib.SymmTensor | None = None, alpha2: outram_foam_basic_lib.SymmTensor | None = None) -> None: ...
    @staticmethod
    def default() -> BackStress: ...

class ChabocheIncrement:
    stress: outram_foam_basic_lib.SymmTensor
    state: ChabocheState
    plastic_strain_increment: outram_foam_basic_lib.SymmTensor
    equivalent_increment: float
    iterations: int
    yielded: bool
    def __init__(self, stress: outram_foam_basic_lib.SymmTensor, state: ChabocheState, plastic_strain_increment: outram_foam_basic_lib.SymmTensor, equivalent_increment: float, iterations: int, yielded: bool) -> None: ...

class ChabocheLaw:
    def parameters(self) -> ChabocheParameters: ...
    def behaviour(self) -> AsterBehaviour: ...
    def aster_name(self) -> str: ...
    def back_stress_count(self) -> int: ...
    def is_rate_dependent(self) -> bool: ...
    def has_strain_memory(self) -> bool: ...
    def kinematic_moduli(self, p: float) -> tuple[float, float]: ...
    def recovery_coefficients(self, p: float) -> tuple[float, float]: ...
    def isotropic_radius(self, p: float) -> float: ...
    def start_radius(self, state: ChabocheState) -> float: ...
    def local_state(self, predictor: ChabochePredictor, dp: float) -> ChabocheLocalState: ...
    @staticmethod
    def VmisCin1Chab(a0: ChabocheParameters) -> ChabocheLaw: ...
    @staticmethod
    def VmisCin2Chab(a0: ChabocheParameters) -> ChabocheLaw: ...
    @staticmethod
    def ViscCin1Chab(a0: ChabocheParameters) -> ChabocheLaw: ...
    @staticmethod
    def ViscCin2Chab(a0: ChabocheParameters) -> ChabocheLaw: ...
    @staticmethod
    def VmisCin2Memo(a0: ChabocheParameters) -> ChabocheLaw: ...
    @staticmethod
    def ViscCin2Memo(a0: ChabocheParameters) -> ChabocheLaw: ...
    def variant(self) -> str: ...

class ChabocheLocalState:
    increment: float
    effective_deviator: outram_foam_basic_lib.SymmTensor
    effective_equivalent: float
    flow_direction: outram_foam_basic_lib.SymmTensor
    plastic_strain_increment: outram_foam_basic_lib.SymmTensor
    kinematic_modulus: list[float]
    non_radial_factor: list[float]
    recovery_coefficient: list[float]
    isotropic_radius: float
    memory: StrainMemory
    residual: float

class ChabocheParameters:
    r0: float
    r_asymptotic: float
    b: float
    c1_asymptotic: float
    gamma1_initial: float
    c2_asymptotic: float
    gamma2_initial: float
    k: float
    w: float
    a_asymptotic: float
    delta1: float
    delta2: float
    viscous_exponent: float
    viscous_stress: float
    memory_eta: float
    memory_q0: float
    memory_qm: float
    memory_mu: float
    @staticmethod
    def armstrong_frederick(r0: float, c1: float, gamma1: float) -> ChabocheParameters: ...
    def __init__(self, r0: float, r_asymptotic: float, b: float, c1_asymptotic: float, gamma1_initial: float, c2_asymptotic: float, gamma2_initial: float, k: float, w: float, a_asymptotic: float, delta1: float, delta2: float, viscous_exponent: float, viscous_stress: float, memory_eta: float, memory_q0: float, memory_qm: float, memory_mu: float) -> None: ...

class ChabochePredictor:
    trial_deviator: outram_foam_basic_lib.SymmTensor
    mean_stress: float
    yield_function: float
    twice_shear_modulus: float
    normalisation: float
    start_state: ChabocheState
    dt: float
    def __init__(self, trial_deviator: outram_foam_basic_lib.SymmTensor, mean_stress: float, yield_function: float, twice_shear_modulus: float, normalisation: float, start_state: ChabocheState, dt: float) -> None: ...

class ChabocheState:
    accumulated_plastic_strain: float
    back_stress: BackStress
    memory: StrainMemory
    local_iterations: int
    @staticmethod
    def zero() -> ChabocheState: ...
    def __init__(self, accumulated_plastic_strain: float | None = None, back_stress: BackStress | None = None, memory: StrainMemory | None = None, local_iterations: int | None = None) -> None: ...
    @staticmethod
    def default() -> ChabocheState: ...

class CrackOpeningMode:
    def number(self) -> int: ...
    @staticmethod
    def Opening() -> CrackOpeningMode: ...
    @staticmethod
    def InPlaneShear() -> CrackOpeningMode: ...
    @staticmethod
    def AntiPlaneShear() -> CrackOpeningMode: ...
    def variant(self) -> str: ...

class CrackPlaneState:
    def aster_name(self) -> str: ...
    def is_plane_strain_like(self) -> bool: ...
    @staticmethod
    def PlaneStrain() -> CrackPlaneState: ...
    @staticmethod
    def PlaneStress() -> CrackPlaneState: ...
    @staticmethod
    def Axisymmetric() -> CrackPlaneState: ...
    @staticmethod
    def ThreeDimensional() -> CrackPlaneState: ...
    def variant(self) -> str: ...

class CrackTipBasis:
    def propagation_direction(self) -> outram_foam_basic_lib.Vector3: ...
    def crack_plane_normal(self) -> outram_foam_basic_lib.Vector3: ...
    def front_tangent(self) -> outram_foam_basic_lib.Vector3: ...
    def local_to_global_vector(self, v: outram_foam_basic_lib.Vector3) -> outram_foam_basic_lib.Vector3: ...
    def global_to_local_vector(self, v: outram_foam_basic_lib.Vector3) -> outram_foam_basic_lib.Vector3: ...
    def local_to_global_gradient(self, g: outram_foam_basic_lib.Tensor) -> outram_foam_basic_lib.Tensor: ...
    def global_to_local_gradient(self, g: outram_foam_basic_lib.Tensor) -> outram_foam_basic_lib.Tensor: ...
    def field_to_global(self, field: NearTipField) -> NearTipField: ...

class aster_CreepIncrement:
    equivalent_increment: float
    strain_increment: outram_foam_basic_lib.SymmTensor
    stress: outram_foam_basic_lib.SymmTensor
    equivalent_stress: float
    iterations: int
    def __init__(self, equivalent_increment: float, strain_increment: outram_foam_basic_lib.SymmTensor, stress: outram_foam_basic_lib.SymmTensor, equivalent_stress: float, iterations: int) -> None: ...

class DamageOutcome:
    @staticmethod
    def Elastic() -> DamageOutcome: ...
    @staticmethod
    def Converged() -> DamageOutcome: ...
    @staticmethod
    def Saturated() -> DamageOutcome: ...
    def variant(self) -> str: ...

class DeformationGradient:
    @staticmethod
    def identity() -> DeformationGradient: ...
    def tensor(self) -> outram_foam_basic_lib.Tensor: ...
    def jacobian(self) -> float: ...
    def right_cauchy_green(self) -> outram_foam_basic_lib.SymmTensor: ...
    def green_lagrange_strain(self) -> outram_foam_basic_lib.SymmTensor: ...

class ElasticModuli:
    young: float
    poisson: float
    def twice_shear_modulus(self) -> float: ...
    def three_times_bulk_modulus(self) -> float: ...
    def __init__(self, young: float, poisson: float) -> None: ...

class GtnIncrement:
    stress: outram_foam_basic_lib.SymmTensor
    equivalent_stress: float
    mean_stress: float
    flow_stress: float
    damage: float
    state: GtnState
    outcome: GtnOutcome
    iterations: int
    def __init__(self, stress: outram_foam_basic_lib.SymmTensor, equivalent_stress: float, mean_stress: float, flow_stress: float, damage: float, state: GtnState, outcome: GtnOutcome, iterations: int) -> None: ...

class GtnNucleation:
    gaussian_porosity: float
    gaussian_mean_strain: float
    gaussian_std_dev: float
    ramp_porosity: float
    ramp_start: float
    ramp_end: float
    linear_slope: float
    linear_start: float
    @staticmethod
    def none() -> GtnNucleation: ...
    def porosity(self, kappa: float, cumulated_plastic_strain: float) -> float: ...
    def __init__(self, gaussian_porosity: float, gaussian_mean_strain: float, gaussian_std_dev: float, ramp_porosity: float, ramp_start: float, ramp_end: float, linear_slope: float, linear_start: float) -> None: ...

class GtnOutcome:
    @staticmethod
    def Elastic() -> GtnOutcome: ...
    @staticmethod
    def Plastic() -> GtnOutcome: ...
    @staticmethod
    def Broken() -> GtnOutcome: ...
    def variant(self) -> str: ...

class GtnParameters:
    q1: float
    q2: float
    initial_porosity: float
    coalescence_porosity: float
    coalescence_slope: float
    rupture_porosity: float
    nucleation: GtnNucleation
    broken_damage: float
    @staticmethod
    def rupture_porosity_from_slope(q1: float, coalescence_porosity: float, slope: float) -> float: ...
    def __init__(self, q1: float, q2: float, initial_porosity: float, coalescence_porosity: float, coalescence_slope: float, rupture_porosity: float, nucleation: GtnNucleation, broken_damage: float) -> None: ...

class GtnState:
    plastic_strain: outram_foam_basic_lib.SymmTensor
    hardening_variable: float
    growth_porosity: float
    nucleation_porosity: float
    coalescence_damage: float
    cumulated_plastic_strain: float
    @staticmethod
    def initial(params: GtnParameters) -> GtnState: ...
    def porosity(self) -> float: ...
    def __init__(self, plastic_strain: outram_foam_basic_lib.SymmTensor, hardening_variable: float, growth_porosity: float, nucleation_porosity: float, coalescence_damage: float, cumulated_plastic_strain: float) -> None: ...

class GursonTvergaardNeedleman:
    def aster_name(self) -> str: ...
    def behaviour(self) -> AsterBehaviour: ...
    def parameters(self) -> GtnParameters: ...
    def star_porosity(self, porosity: float) -> float: ...
    def yield_function(self, equivalent_stress: float, mean_stress: float, flow_stress: float, damage: float) -> float: ...
    def overstress(self, dkappa: float, dt: float) -> float: ...
    @staticmethod
    def RateIndependent(a0: GtnParameters) -> GursonTvergaardNeedleman: ...
    @staticmethod
    def Viscous(a0: GtnParameters, a1: NortonOverstress) -> GursonTvergaardNeedleman: ...
    def variant(self) -> str: ...

class HillAnisotropy:
    m_xx: float
    m_yy: float
    m_zz: float
    m_xy: float
    m_xz: float
    m_yz: float
    @staticmethod
    def from_aster_3d(m_rr_rr: float, m_tt_tt: float, m_zz_zz: float, m_rt_rt: float, m_rz_rz: float, m_tz_tz: float) -> HillAnisotropy: ...
    def fgh(self) -> tuple[float, float, float]: ...
    def contract(self, sigma: outram_foam_basic_lib.SymmTensor) -> outram_foam_basic_lib.SymmTensor: ...
    def equivalent_stress(self, sigma: outram_foam_basic_lib.SymmTensor) -> float: ...
    def flow_direction(self, sigma: outram_foam_basic_lib.SymmTensor) -> outram_foam_basic_lib.SymmTensor: ...
    def blend(self, other: HillAnisotropy, za: float) -> HillAnisotropy: ...
    def __init__(self, m_xx: float, m_yy: float, m_zz: float, m_xy: float, m_xz: float, m_yz: float) -> None: ...

class Irrad3m:
    parameters: Irrad3mParameters
    hardening: Irrad3mHardening
    def aster_name(self) -> str: ...
    def irradiation_creep_increment(self, equivalent_stress_start: float, equivalent_stress_end: float, driver_start: float, dose_increment: float) -> tuple[float, float]: ...
    def __init__(self, parameters: Irrad3mParameters, hardening: Irrad3mHardening) -> None: ...

class Irrad3mHardening:
    coefficient: float
    exponent: float
    strain_offset: float
    stress_at_proof_strain: float
    slope_at_proof_strain: float
    plateau_strain: float
    plateau_stress: float
    used_fallback: bool
    def flow_stress(self, p: float) -> float: ...
    def strain_at_flow_stress(self, sigma: float) -> float: ...
    def __init__(self, coefficient: float, exponent: float, strain_offset: float, stress_at_proof_strain: float, slope_at_proof_strain: float, plateau_strain: float, plateau_stress: float, used_fallback: bool) -> None: ...

class Irrad3mIncrement:
    plastic_increment: float
    irradiation_creep_increment: float
    creep_driver_increment: float
    strain_increment: outram_foam_basic_lib.SymmTensor
    stress: outram_foam_basic_lib.SymmTensor
    equivalent_stress: float
    iterations: int
    def __init__(self, plastic_increment: float, irradiation_creep_increment: float, creep_driver_increment: float, strain_increment: outram_foam_basic_lib.SymmTensor, stress: outram_foam_basic_lib.SymmTensor, equivalent_stress: float, iterations: int) -> None: ...

class Irrad3mParameters:
    yield_strength: float
    uniform_elongation: float
    ultimate_strength: float
    creep_compliance: float
    creep_threshold: float
    swelling_rate: float
    swelling_sharpness: float
    swelling_onset_dose: float
    yield_plateau_factor: float
    creep_scale: float
    swelling_scale: float
    def swelling_strain(self, dose: float) -> float: ...
    def swelling_strain_increment(self, dose_start: float, dose_end: float) -> outram_foam_basic_lib.SymmTensor: ...
    def __init__(self, yield_strength: float, uniform_elongation: float, ultimate_strength: float, creep_compliance: float, creep_threshold: float, swelling_rate: float, swelling_sharpness: float, swelling_onset_dose: float, yield_plateau_factor: float, creep_scale: float, swelling_scale: float) -> None: ...

class Irrad3mState:
    plastic_strain: float
    creep_driver: float
    irradiation_creep_strain: float
    swelling_strain: float
    def advanced(self, increment: Irrad3mIncrement, swelling_increment: float) -> Irrad3mState: ...
    def __init__(self, plastic_strain: float | None = None, creep_driver: float | None = None, irradiation_creep_strain: float | None = None, swelling_strain: float | None = None) -> None: ...
    @staticmethod
    def default() -> Irrad3mState: ...

class IrradiationGrowthDirection:
    azimuth: float
    elevation: float
    def unit_vector(self) -> outram_foam_basic_lib.Vector3: ...
    def strain_increment(self, growth_strain_increment: float) -> outram_foam_basic_lib.SymmTensor: ...
    def strain_increment_rank_one(self, growth_strain_increment: float) -> outram_foam_basic_lib.SymmTensor: ...
    def __init__(self, azimuth: float, elevation: float) -> None: ...

class IsotropicElasticity:
    shear_modulus: float
    bulk_modulus: float
    def young(self) -> float: ...
    def poisson(self) -> float: ...
    def __init__(self, shear_modulus: float, bulk_modulus: float) -> None: ...

class IsotropicHardening:
    def return_residual(self, delta_p: float, trial_equivalent_stress: float, three_shear_moduli: float, accumulated_strain: float) -> float: ...
    def value(self, p: float) -> float: ...
    def slope(self, p: float) -> float: ...
    def yield_stress(self) -> float: ...
    def aster_name_suffix(self) -> str | None: ...
    @staticmethod
    def Perfect(yield_stress: float) -> IsotropicHardening: ...
    @staticmethod
    def Linear(yield_stress: float, modulus: float) -> IsotropicHardening: ...
    @staticmethod
    def Ludwik(yield_stress: float, coefficient: float, exponent: float) -> IsotropicHardening: ...
    @staticmethod
    def AsterPower(yield_stress: float, youngs_modulus: float, alpha: float, exponent: float) -> IsotropicHardening: ...
    @staticmethod
    def EcroNl(r0: float, rh: float, r1: float, gamma_1: float, r2: float, gamma_2: float, rk: float, p0: float, gamma_m: float) -> IsotropicHardening: ...
    def variant(self) -> str: ...

class LemaitreChabocheIncrement:
    stress: outram_foam_basic_lib.SymmTensor
    effective_equivalent_stress: float
    damage_equivalent_stress: float
    state: LemaitreChabocheState
    outcome: DamageOutcome
    rate_linearised: bool
    damage_iterations: int
    flow_iterations: int
    def __init__(self, stress: outram_foam_basic_lib.SymmTensor, effective_equivalent_stress: float, damage_equivalent_stress: float, state: LemaitreChabocheState, outcome: DamageOutcome, rate_linearised: bool, damage_iterations: int, flow_iterations: int) -> None: ...

class LemaitreChabocheLaw:
    def aster_name(self) -> str: ...
    def behaviour(self) -> AsterBehaviour: ...
    def parameters(self) -> LemaitreChabocheParameters: ...
    def damage_equivalent_stress(self, stress: outram_foam_basic_lib.SymmTensor, damage: float) -> float: ...
    def damage_rate(self, chi: float, damage: float) -> float: ...
    def hardening_rate(self, effective_equivalent_stress: float, hardening_variable: float, dt: float) -> tuple[float, bool]: ...
    @staticmethod
    def Vendochab(a0: LemaitreChabocheParameters) -> LemaitreChabocheLaw: ...
    @staticmethod
    def ViscEndoLema(a0: LemaitreChabocheParameters) -> LemaitreChabocheLaw: ...
    def variant(self) -> str: ...

class LemaitreChabocheParameters:
    n: float
    m: float
    k: float
    yield_stress: float
    principal_weight: float
    trace_weight: float
    damage_exponent: float
    damage_strength: float
    damage_closure_exponent: float
    def __init__(self, n: float, m: float, k: float, yield_stress: float, principal_weight: float, trace_weight: float, damage_exponent: float, damage_strength: float, damage_closure_exponent: float) -> None: ...

class LemaitreChabocheState:
    viscoplastic_strain: outram_foam_basic_lib.SymmTensor
    equivalent_viscoplastic_strain: float
    hardening_variable: float
    damage: float
    @staticmethod
    def pristine() -> LemaitreChabocheState: ...
    def __init__(self, viscoplastic_strain: outram_foam_basic_lib.SymmTensor, equivalent_viscoplastic_strain: float, hardening_variable: float, damage: float) -> None: ...

class LemaitreParameters:
    k: float
    n: float
    m: float
    def __init__(self, k: float, n: float, m: float) -> None: ...

class LinearElasticConstants:
    young: float
    poisson: float
    def shear_modulus(self) -> float: ...
    def kolosov_kappa(self, state: CrackPlaneState) -> float: ...
    def effective_modulus(self, state: CrackPlaneState) -> float: ...
    def plane_lame_lambda(self, state: CrackPlaneState) -> float: ...
    def __init__(self, young: float, poisson: float) -> None: ...

class LocalSolution:
    root: float
    residual: float
    iterations: int
    bisection_steps: int
    def __init__(self, root: float, residual: float, iterations: int, bisection_steps: int) -> None: ...

class LogarithmicIrradiationLaw:
    def aster_name(self) -> str: ...
    def creep_parameters(self) -> LogarithmicIrradiationParameters: ...
    def growth_strain_increment(self, growth_strain_increment: float) -> outram_foam_basic_lib.SymmTensor: ...
    @staticmethod
    def Creep(a0: LogarithmicIrradiationParameters) -> LogarithmicIrradiationLaw: ...
    @staticmethod
    def CreepAndGrowth(creep: LogarithmicIrradiationParameters, growth: IrradiationGrowthDirection) -> LogarithmicIrradiationLaw: ...
    def variant(self) -> str: ...

class LogarithmicIrradiationParameters:
    primary_compliance: float
    secondary_compliance: float
    primary_fluence_constant: float
    activation_temperature: float
    def __init__(self, primary_compliance: float, secondary_compliance: float, primary_fluence_constant: float, activation_temperature: float) -> None: ...

class LogarithmicStrain:
    def log_strain(self) -> outram_foam_basic_lib.SymmTensor: ...
    def gradient(self) -> DeformationGradient: ...
    def principal_stretches(self) -> outram_foam_basic_lib.Vector3: ...
    def second_piola_from_conjugate(self, t: outram_foam_basic_lib.SymmTensor) -> outram_foam_basic_lib.SymmTensor: ...
    def cauchy_from_second_piola(self, s: outram_foam_basic_lib.SymmTensor) -> outram_foam_basic_lib.SymmTensor: ...
    def cauchy_from_conjugate(self, t: outram_foam_basic_lib.SymmTensor) -> outram_foam_basic_lib.SymmTensor: ...

class MetaLemaAni:
    alpha: MetaLemaAniPhase
    mixed: MetaLemaAniPhase
    beta: MetaLemaAniPhase
    alpha_anisotropy: HillAnisotropy
    beta_anisotropy: HillAnisotropy
    def aster_name(self) -> str: ...
    @staticmethod
    def phase_weights(za: float) -> tuple[float, float, float]: ...
    def anisotropy_at(self, beta_fraction: float) -> HillAnisotropy: ...
    def viscous_stress(self, beta_fraction: float, temperature: float, accumulated_strain: float, strain_rate: float) -> float: ...
    def __init__(self, alpha: MetaLemaAniPhase, mixed: MetaLemaAniPhase, beta: MetaLemaAniPhase, alpha_anisotropy: HillAnisotropy, beta_anisotropy: HillAnisotropy) -> None: ...

class MetaLemaAniIncrement:
    equivalent_increment: float
    strain_increment: outram_foam_basic_lib.SymmTensor
    stress: outram_foam_basic_lib.SymmTensor
    equivalent_stress: float
    iterations: int
    def __init__(self, equivalent_increment: float, strain_increment: outram_foam_basic_lib.SymmTensor, stress: outram_foam_basic_lib.SymmTensor, equivalent_stress: float, iterations: int) -> None: ...

class MetaLemaAniPhase:
    amplitude: float
    hardening_exponent: float
    stress_exponent: float
    activation_temperature: float
    def reference_stress(self, temperature: float) -> float: ...
    def viscous_stress(self, temperature: float, accumulated_strain: float, strain_rate: float) -> float: ...
    def __init__(self, amplitude: float, hardening_exponent: float, stress_exponent: float, activation_temperature: float) -> None: ...

class ModeEnergyRelease:
    mode_i: float
    mode_ii: float
    mode_iii: float
    total: float
    def __init__(self, mode_i: float | None = None, mode_ii: float | None = None, mode_iii: float | None = None, total: float | None = None) -> None: ...
    @staticmethod
    def default() -> ModeEnergyRelease: ...

class NearTipField:
    displacement: outram_foam_basic_lib.Vector3
    gradient: outram_foam_basic_lib.Tensor
    def scaled(self, k: float) -> NearTipField: ...
    def small_strain(self) -> outram_foam_basic_lib.SymmTensor: ...
    def small_strain_mandel(self) -> AsterVoigt: ...
    def __init__(self, displacement: outram_foam_basic_lib.Vector3, gradient: outram_foam_basic_lib.Tensor) -> None: ...

class NortonHoffLimitAnalysis:
    yield_stress: float
    def __init__(self, yield_stress: float) -> None: ...
    def aster_name(self) -> str: ...
    @staticmethod
    def exponent(pseudo_time: float) -> float: ...

class NortonOverstress:
    n: float
    k: float
    def stress(self, dkappa: float, dt: float) -> float: ...
    def __init__(self, n: float, k: float) -> None: ...

class NortonParameters:
    k: float
    n: float
    def __init__(self, k: float, n: float) -> None: ...

class PlanarCrackTipResult:
    g: float
    mode_i_root: float
    mode_ii_root: float
    k1: float
    k2: float
    def g_irwin(self) -> float: ...
    def with_symmetric_half_model(self) -> PlanarCrackTipResult: ...
    def stress_intensity_factors(self) -> StressIntensityFactors: ...
    def __init__(self, g: float | None = None, mode_i_root: float | None = None, mode_ii_root: float | None = None, k1: float | None = None, k2: float | None = None) -> None: ...
    @staticmethod
    def default() -> PlanarCrackTipResult: ...

class RousselierIncrement:
    stress: outram_foam_basic_lib.SymmTensor
    reduced_equivalent_stress: float
    reduced_mean_stress: float
    plastic_strain_increment: float
    porosity_increment: float
    state: RousselierState
    outcome: RousselierOutcome
    iterations: int
    def __init__(self, stress: outram_foam_basic_lib.SymmTensor, reduced_equivalent_stress: float, reduced_mean_stress: float, plastic_strain_increment: float, porosity_increment: float, state: RousselierState, outcome: RousselierOutcome, iterations: int) -> None: ...

class RousselierLaw:
    def aster_name(self) -> str: ...
    def behaviour(self) -> AsterBehaviour: ...
    def parameters(self) -> RousselierParameters: ...
    def nucleation_rate(self) -> float: ...
    def yield_function(self, reduced_equivalent: float, reduced_mean: float, porosity: float, flow_stress: float) -> float: ...
    def viscous_overstress(self, plastic_increment: float, dt: float) -> float: ...
    @staticmethod
    def Plastic(a0: RousselierParameters) -> RousselierLaw: ...
    @staticmethod
    def Viscous(a0: RousselierParameters, a1: ViscousSinhParameters) -> RousselierLaw: ...
    def variant(self) -> str: ...

class RousselierOutcome:
    @staticmethod
    def Elastic() -> RousselierOutcome: ...
    @staticmethod
    def VonMises() -> RousselierOutcome: ...
    @staticmethod
    def Coupled() -> RousselierOutcome: ...
    @staticmethod
    def Broken() -> RousselierOutcome: ...
    def variant(self) -> str: ...

class RousselierParameters:
    d: float
    sigma_1: float
    initial_porosity: float
    critical_porosity: float
    acceleration: float
    limit_porosity: float
    broken_unloading_slope: float
    nucleation_rate: float
    stored_energy_fraction: float
    def __init__(self, d: float, sigma_1: float, initial_porosity: float, critical_porosity: float, acceleration: float, limit_porosity: float, broken_unloading_slope: float, nucleation_rate: float, stored_energy_fraction: float) -> None: ...

class RousselierState:
    equivalent_plastic_strain: float
    porosity: float
    dissipation: float
    blocked_energy: float
    @staticmethod
    def initial(params: RousselierParameters) -> RousselierState: ...
    def __init__(self, equivalent_plastic_strain: float, porosity: float, dissipation: float, blocked_energy: float) -> None: ...

class RuptureCriterion:
    critical_stress: float
    stiffness_divisor: float
    def aster_name(self) -> str: ...
    def behaviour(self) -> AsterBehaviour: ...
    def degraded_young_modulus(self, young: float, broken: bool) -> float: ...
    def __init__(self, critical_stress: float, stiffness_divisor: float) -> None: ...

class RuptureState:
    plastic_strain_rate: float
    dissipated_energy: float
    cumulated_dissipated_energy: float
    dissipated_power: float
    cumulated_dissipated_power: float
    broken: bool
    @staticmethod
    def pristine() -> RuptureState: ...
    def __init__(self, plastic_strain_rate: float, dissipated_energy: float, cumulated_dissipated_energy: float, dissipated_power: float, cumulated_dissipated_power: float, broken: bool) -> None: ...

class ScalarAlgorithm:
    def aster_name(self) -> str: ...
    def needs_derivative(self) -> bool: ...
    @staticmethod
    def Analytic() -> ScalarAlgorithm: ...
    @staticmethod
    def Newton() -> ScalarAlgorithm: ...
    @staticmethod
    def NewtonPerturbed() -> ScalarAlgorithm: ...
    @staticmethod
    def Secant() -> ScalarAlgorithm: ...
    @staticmethod
    def Brent() -> ScalarAlgorithm: ...
    def variant(self) -> str: ...

class SolverControl:
    max_iter: int
    residual_tol: float
    step_tol: float
    def __init__(self, max_iter: int | None = None, residual_tol: float | None = None, step_tol: float | None = None) -> None: ...
    @staticmethod
    def default() -> SolverControl: ...

class StrainMemory:
    isotropic_increment: float
    memory_radius: float
    memory_centre: outram_foam_basic_lib.SymmTensor
    plastic_strain: outram_foam_basic_lib.SymmTensor
    @staticmethod
    def zero() -> StrainMemory: ...
    def __init__(self, isotropic_increment: float | None = None, memory_radius: float | None = None, memory_centre: outram_foam_basic_lib.SymmTensor | None = None, plastic_strain: outram_foam_basic_lib.SymmTensor | None = None) -> None: ...
    @staticmethod
    def default() -> StrainMemory: ...

class StressIntensityFactors:
    k1: float
    k2: float
    k3: float
    @staticmethod
    def mode_i(k1: float) -> StressIntensityFactors: ...
    def __init__(self, k1: float, k2: float, k3: float) -> None: ...
    @staticmethod
    def default() -> StressIntensityFactors: ...

class ThermoElasticStep:
    start: ElasticModuli
    end: ElasticModuli
    thermal_strain_increment: float
    dt: float
    @staticmethod
    def isothermal(moduli: ElasticModuli, dt: float) -> ThermoElasticStep: ...
    def __init__(self, start: ElasticModuli, end: ElasticModuli, thermal_strain_increment: float, dt: float) -> None: ...

class ViscoplasticChabocheParameters:
    drag_stress: float
    drag_hardening_coupling: float
    threshold_hardening_multiplier: float
    initial_threshold: float
    flow_exponent: float
    exponential_flow_coefficient: float
    isotropic_rate: float
    static_recovery_exponent_r: float
    static_recovery_rate_r: float
    memory_saturation_rate: float
    hardening_saturation_max: float
    hardening_saturation_min: float
    recovery_target_offset: float
    memory_split: float
    back_stress_modulus_1: float
    static_recovery_exponent_x1: float
    back_stress_recovery_split_1: float
    static_recovery_rate_x1: float
    dynamic_recovery_1: float
    back_stress_modulus_2: float
    static_recovery_exponent_x2: float
    back_stress_recovery_split_2: float
    static_recovery_rate_x2: float
    dynamic_recovery_2: float
    dynamic_recovery_floor: float
    def to_aster_coefficients(self) -> list[float]: ...
    def __init__(self, drag_stress: float, drag_hardening_coupling: float, threshold_hardening_multiplier: float, initial_threshold: float, flow_exponent: float, exponential_flow_coefficient: float, isotropic_rate: float, static_recovery_exponent_r: float, static_recovery_rate_r: float, memory_saturation_rate: float, hardening_saturation_max: float, hardening_saturation_min: float, recovery_target_offset: float, memory_split: float, back_stress_modulus_1: float, static_recovery_exponent_x1: float, back_stress_recovery_split_1: float, static_recovery_rate_x1: float, dynamic_recovery_1: float, back_stress_modulus_2: float, static_recovery_exponent_x2: float, back_stress_recovery_split_2: float, static_recovery_rate_x2: float, dynamic_recovery_2: float, dynamic_recovery_floor: float) -> None: ...

class ViscoplasticChabocheRates:
    viscoplastic_strain_rate: AsterVoigt
    back_strain_1_rate: AsterVoigt
    back_strain_2_rate: AsterVoigt
    memory_centre_rate: AsterVoigt
    isotropic_hardening_rate: float
    memory_radius_rate: float
    accumulated_strain_rate: float
    def __init__(self, viscoplastic_strain_rate: AsterVoigt | None = None, back_strain_1_rate: AsterVoigt | None = None, back_strain_2_rate: AsterVoigt | None = None, memory_centre_rate: AsterVoigt | None = None, isotropic_hardening_rate: float | None = None, memory_radius_rate: float | None = None, accumulated_strain_rate: float | None = None) -> None: ...
    @staticmethod
    def default() -> ViscoplasticChabocheRates: ...

class ViscoplasticChabocheState:
    viscoplastic_strain: AsterVoigt
    back_strain_1: AsterVoigt
    back_strain_2: AsterVoigt
    memory_centre: AsterVoigt
    isotropic_hardening: float
    memory_radius: float
    accumulated_strain: float
    @staticmethod
    def undeformed() -> ViscoplasticChabocheState: ...
    @staticmethod
    def from_ode_state(y: list[float]) -> ViscoplasticChabocheState: ...
    def to_ode_state(self) -> list[float]: ...
    def __init__(self, viscoplastic_strain: AsterVoigt | None = None, back_strain_1: AsterVoigt | None = None, back_strain_2: AsterVoigt | None = None, memory_centre: AsterVoigt | None = None, isotropic_hardening: float | None = None, memory_radius: float | None = None, accumulated_strain: float | None = None) -> None: ...
    @staticmethod
    def default() -> ViscoplasticChabocheState: ...

class ViscoplasticChabocheSystem:
    law: ViscoplasticChabocheWithMemory
    young_modulus: float
    poisson_ratio: float
    total_strain_start: AsterVoigt
    total_strain_increment: AsterVoigt
    step_duration: float
    def stress_at(self, x: float, viscoplastic_strain: AsterVoigt) -> AsterVoigt: ...
    def __init__(self, law: ViscoplasticChabocheWithMemory, young_modulus: float, poisson_ratio: float, total_strain_start: AsterVoigt, total_strain_increment: AsterVoigt, step_duration: float) -> None: ...

class ViscoplasticChabocheWithMemory:
    parameters: ViscoplasticChabocheParameters
    def aster_name(self) -> str: ...
    def effective_deviator(self, stress: AsterVoigt, state: ViscoplasticChabocheState) -> tuple[AsterVoigt, float]: ...
    def overstress(self, stress: AsterVoigt, state: ViscoplasticChabocheState) -> float: ...
    def flow_rate(self, overstress: float, isotropic_hardening: float) -> float: ...
    def internal_variable_rates(self, stress: AsterVoigt, state: ViscoplasticChabocheState) -> ViscoplasticChabocheRates: ...
    def __init__(self, parameters: ViscoplasticChabocheParameters) -> None: ...

class ViscoplasticLaw:
    def aster_name(self) -> str: ...
    def equivalent_strain_rate(self, sigma_eq: float, accumulated_strain: float) -> float: ...
    def rate_derivative_wrt_stress(self, sigma_eq: float, accumulated_strain: float) -> float: ...
    @staticmethod
    def Norton(a0: NortonParameters) -> ViscoplasticLaw: ...
    @staticmethod
    def Lemaitre(a0: LemaitreParameters) -> ViscoplasticLaw: ...
    @staticmethod
    def LemaitreIrradiation(a0: LemaitreIrradiationParameters) -> ViscoplasticLaw: ...
    def variant(self) -> str: ...

class ViscousSinhParameters:
    sigma_0: float
    reference_strain_rate: float
    exponent: float
    def __init__(self, sigma_0: float, reference_strain_rate: float, exponent: float) -> None: ...

class LemaitreIrradiationParameters:
    n: float
    m: float
    flux_coefficient: float
    reference_flux: float
    flux_exponent: float
    athermal_term: float
    activation_temperature: float
    def __init__(self, n: float, m: float, flux_coefficient: float, reference_flux: float, flux_exponent: float, athermal_term: float, activation_temperature: float) -> None: ...

def hydrogen_liberated(oxide_growth: float, inner_radius: float, outer_radius: float) -> float: ...
def surface_to_volume(inner_radius: float, outer_radius: float) -> float: ...
def oxide_conductivity(temperature: float) -> float: ...
def oxide_thermal_coupling(surface_temperature: float, first_cell_temperature: float, metal_conductivity: float, cell_to_face_distance: float, mean_oxide_thickness: float) -> OxideThermalCoupling: ...
def average_across_interface(owner: float, neighbour: float) -> float: ...
def contact_conductance(surfaces: GapSurfaces) -> float: ...
def effective_roughness_distance(fuel_roughness: float, clad_roughness: float, interface_pressure: float) -> float: ...
def radiative_conductance(surfaces: GapSurfaces) -> float: ...
def series_conductance(fuel_wall: float, clad_wall: float, gap: float) -> float: ...
def spherical_gap_conduction_length(reference_radius: float, inner_radius: float, outer_radius: float) -> float: ...
def temperature_jump_distance(conductivity: float, temperature: float, gas_pressure: float, accommodation: float) -> float: ...
def under_relax(new: float, previous: float, factor: float) -> float: ...
def wall_conductance(conductivity: float, wall_distance: float) -> float: ...
def boundary_shear_stiffness(shear_modulus: float, face_area: float, cell_volume: float) -> float: ...
def boundary_stiffness(bulk_modulus: float, face_area: float, cell_volume: float) -> float: ...
def total_surface_pressure(contact_pressure: float, gas_pressure: float) -> float: ...
def crack_volume_contribution(relocation_strain: float, cell_volume: float) -> float: ...
def dish_volume_contribution(dish_fraction: float, cell_volume: float) -> float: ...
def interpolate_clamped(table: list[tuple[float, float]], x: float) -> float: ...
def auto_axial_levels(axial_coordinates: list[float], precision: float) -> list[float]: ...
def axial_coordinate(position: outram_foam_basic_lib.Vector3, pin_direction: outram_foam_basic_lib.Vector3) -> float: ...
def round_to(z: float, precision: float) -> float: ...
def matpro_zircaloy_shear_modulus(t: float, state: MaterialState) -> float: ...
def deviator(sigma: outram_foam_basic_lib.SymmTensor) -> outram_foam_basic_lib.SymmTensor: ...
def equivalent_mode_i_factor(g: float, elastic: LinearElasticConstants, state: CrackPlaneState) -> float: ...
def equivalent_stress(sigma: outram_foam_basic_lib.SymmTensor) -> float: ...
def irwin_energy_release_rate(k: StressIntensityFactors, elastic: LinearElasticConstants, state: CrackPlaneState) -> float: ...
def irwin_mode_split(k: StressIntensityFactors, elastic: LinearElasticConstants, state: CrackPlaneState) -> ModeEnergyRelease: ...
def max_principal_stress(sigma: outram_foam_basic_lib.SymmTensor) -> float: ...
def mean_stress(sigma: outram_foam_basic_lib.SymmTensor) -> float: ...
def near_tip_stress(field: NearTipField, elastic: LinearElasticConstants, state: CrackPlaneState) -> outram_foam_basic_lib.SymmTensor: ...
def perturbed_default() -> float: ...
def scaled_hoop_stress(k1: float, k2: float, theta: float) -> float: ...
def von_mises_of_deviator(s: outram_foam_basic_lib.SymmTensor) -> float: ...
def equivalent_strain(strain: outram_foam_basic_lib.SymmTensor) -> float: ...
def von_mises(stress: outram_foam_basic_lib.SymmTensor) -> float: ...
ENERGY_PER_FISSION_J: float
FLUENCE_PER_CM2_TO_PER_M2: float
JOULES_PER_MEGAWATT_DAY: float
MWD_PER_KGHM_PER_PERCENT_FIMA: float
SECONDS_PER_DAY: float
UO2_HEAVY_METAL_MASS_FRACTION: float
UO2_THEORETICAL_DENSITY: float
PILLING_BEDWORTH_ZIRCONIUM: float
DEFAULT_ALPHA: float
DEFAULT_DIAGONAL_FACTOR: float
HYDROGEN_ATOMIC_MASS: float
HYDROGEN_ATOMS_PER_ZIRCONIUM: float
HYDROGEN_PER_OXIDE_THICKNESS: float
ZIRCONIUM_ATOMIC_MASS: float
LOW_HIGH_SWITCH_TEMPERATURE: float
TRANSITION_THICKNESS: float
AVOGADRO: float
FISSION_GAS_ATOMS_PER_FISSION: float
KRYPTON_ATOMS_PER_FISSION: float
MOLAR_GAS_CONSTANT: float
REFERENCE_PRESSURE: float
REFERENCE_TEMPERATURE: float
XENON_ATOMS_PER_FISSION: float
JUMP_DISTANCE_COEFFICIENT: float
JUMP_DISTANCE_MULTIPLIER: float
MEYER_HARDNESS_ZIRCALOY: float
PRESSURE_TO_KGF_PER_CM2: float
ROUGHNESS_OFFSET: float
ROUGHNESS_PRESSURE_COEFFICIENT: float
SMALL: float
STEFAN_BOLTZMANN: float
ACCOMMODATION_T_CAP: float
GAS_CONSTANT: float
N_SPECIES: int
SLICE_BOUNDARY_TOLERANCE: float
MOLYBDENUM_DENSITY: float
SCHUMANN_1515TI_REFERENCE_DENSITY: float
UO2_DEFAULT_DENSITY_FRACTION: float
UO2_THEORETICAL_DENSITY: float
UPUO2_DEFAULT_DENSITY_FRACTION: float
UPUO2_THEORETICAL_DENSITY: float
MOLYBDENUM_EMISSIVITY: float
ZY_EMISSIVITY: float
POISSON_RATIO_MAX: float
POISSON_RATIO_MIN: float
PARFUME_PYC_DEFAULT_ANISOTROPY: float
PARFUME_SIC_ALPHA: float
PU_ATOM_TO_MASS_FRACTION: float
MATPRO_MAX_POROSITY: float
PARFUME_SATURATION_FLUENCE: float
ASTER_POWER_LINEARISATION_STRAIN: float
IRRAD3M_PROOF_STRAIN: float
LEMAITRE_CHABOCHE_DAMAGE_MAX: float
MAX_LEGENDRE_FRONT_DEGREE: int
RKDCHA_ALPHA2_USES_D1: bool
SLOPE_SINGULARITY_OFFSET: float
INTERNAL_VARIABLE_COUNT: int
ODE_EQUATION_COUNT: int
