"""Type stubs for `outram_park.outram_mc_libs`, generated from the Rust API.

Physical quantities cross this boundary as `float` in SI base units.
"""

class DepletionMatrix:
    @staticmethod
    def zeros(order: int) -> DepletionMatrix: ...
    def order(self) -> int: ...
    def get(self, row: int, col: int) -> float: ...
    def set(self, row: int, col: int, val: float) -> None: ...
    def add(self, row: int, col: int, val: float) -> None: ...
    def mat_vec(self, n_vec: list[float]) -> list[float]: ...
    def as_slice(self) -> list[float]: ...

class MicroRate:
    gamma: float
    fission: float
    n2n: float
    def total_removal(self) -> float: ...
    def __init__(self, gamma: float | None = None, fission: float | None = None, n2n: float | None = None) -> None: ...
    @staticmethod
    def default() -> MicroRate: ...

class ReactionRates:
    flux: float
    @staticmethod
    def zero() -> ReactionRates: ...
    def rate_for(self, nuclide: str) -> MicroRate: ...
    def set(self, nuclide: str, rate: MicroRate) -> None: ...
    def __init__(self) -> None: ...
    @staticmethod
    def default() -> ReactionRates: ...

class DecayBranch:
    target: str
    branching: float
    def __init__(self, target: str, branching: float) -> None: ...

class DepletionChain:
    @staticmethod
    def simple() -> DepletionChain: ...
    @staticmethod
    def simple_from_data() -> DepletionChain: ...
    def nuclide_names(self) -> list[str]: ...
    def len(self) -> int: ...
    def is_empty(self) -> bool: ...
    def index_of(self, name: str) -> int | None: ...
    def decay_constant_of(self, name: str) -> float | None: ...
    def build_matrix(self, rates: ReactionRates) -> DepletionMatrix: ...
    def decay_matrix(self) -> DepletionMatrix: ...

class NeutronReaction:
    kind: ReactionKind
    target: str | None
    def __init__(self, kind: ReactionKind, target: str | None) -> None: ...

class NuclideData:
    name: str
    half_life_seconds: float | None
    decays: list[DecayBranch]
    reactions: list[NeutronReaction]
    fission_yields: list[tuple[str, float]]
    fission_q_ev: float | None
    def __init__(self, name: str, half_life_seconds: float | None, decays: list[DecayBranch], reactions: list[NeutronReaction], fission_yields: list[tuple[str, float]], fission_q_ev: float | None) -> None: ...

class ReactionKind:
    @staticmethod
    def Gamma() -> ReactionKind: ...
    @staticmethod
    def Fission() -> ReactionKind: ...
    @staticmethod
    def TwoN() -> ReactionKind: ...
    def variant(self) -> str: ...

class BurnupResult:
    steps: list[BurnupStep]
    def bol(self) -> BurnupStep: ...
    def eol(self) -> BurnupStep: ...
    def history(self, nuclide: str) -> list[tuple[float, float]]: ...
    def __init__(self, steps: list[BurnupStep]) -> None: ...

class BurnupSettings:
    power_watts: float
    fuel_volume_cm3: float
    step_days: float
    n_steps: int
    temperature_k: float
    one_group_energy_ev: float
    def __init__(self, power_watts: float | None = None, fuel_volume_cm3: float | None = None, step_days: float | None = None, n_steps: int | None = None, temperature_k: float | None = None, one_group_energy_ev: float | None = None) -> None: ...
    @staticmethod
    def default() -> BurnupSettings: ...

class BurnupStep:
    step: int
    time_days: float
    flux: float
    k_inf: float
    densities: list[tuple[str, float]]
    def density(self, nuclide: str) -> float: ...
    def __init__(self, step: int, time_days: float, flux: float, k_inf: float, densities: list[tuple[str, float]]) -> None: ...

class LatticeType:
    @staticmethod
    def Rect() -> LatticeType: ...
    @staticmethod
    def Hex() -> LatticeType: ...
    def variant(self) -> str: ...

class Plane:
    a: float
    b: float
    c: float
    d: float
    bc: BoundaryType
    def __init__(self, a: float, b: float, c: float, d: float, bc: BoundaryType) -> None: ...

class Quadric:
    a: float
    b: float
    c: float
    d: float
    e: float
    f: float
    g: float
    h: float
    j: float
    k: float
    bc: BoundaryType
    def __init__(self, a: float, b: float, c: float, d: float, e: float, f: float, g: float, h: float, j: float, k: float, bc: BoundaryType) -> None: ...

class XCone:
    x0: float
    y0: float
    z0: float
    r_sq: float
    bc: BoundaryType
    def __init__(self, x0: float, y0: float, z0: float, r_sq: float, bc: BoundaryType) -> None: ...

class XCylinder:
    y0: float
    z0: float
    r: float
    bc: BoundaryType
    def __init__(self, y0: float, z0: float, r: float, bc: BoundaryType) -> None: ...

class XTorus:
    x0: float
    y0: float
    z0: float
    a: float
    b: float
    c: float
    bc: BoundaryType
    def __init__(self, x0: float, y0: float, z0: float, a: float, b: float, c: float, bc: BoundaryType) -> None: ...

class YCone:
    x0: float
    y0: float
    z0: float
    r_sq: float
    bc: BoundaryType
    def __init__(self, x0: float, y0: float, z0: float, r_sq: float, bc: BoundaryType) -> None: ...

class YCylinder:
    x0: float
    z0: float
    r: float
    bc: BoundaryType
    def __init__(self, x0: float, z0: float, r: float, bc: BoundaryType) -> None: ...

class YTorus:
    x0: float
    y0: float
    z0: float
    a: float
    b: float
    c: float
    bc: BoundaryType
    def __init__(self, x0: float, y0: float, z0: float, a: float, b: float, c: float, bc: BoundaryType) -> None: ...

class ZCone:
    x0: float
    y0: float
    z0: float
    r_sq: float
    bc: BoundaryType
    def __init__(self, x0: float, y0: float, z0: float, r_sq: float, bc: BoundaryType) -> None: ...

class ZTorus:
    x0: float
    y0: float
    z0: float
    a: float
    b: float
    c: float
    bc: BoundaryType
    def __init__(self, x0: float, y0: float, z0: float, a: float, b: float, c: float, bc: BoundaryType) -> None: ...

class GpuContext:
    limits: GpuLimits
    def capabilities(self) -> HardwareCapabilities: ...

class DeviceClass:
    @staticmethod
    def Discrete() -> DeviceClass: ...
    @staticmethod
    def Integrated() -> DeviceClass: ...
    @staticmethod
    def Virtual() -> DeviceClass: ...
    @staticmethod
    def Cpu() -> DeviceClass: ...
    @staticmethod
    def Other() -> DeviceClass: ...
    def variant(self) -> str: ...

class GpuLimits:
    adapter_name: str
    backend: str
    max_storage_buffers_per_shader_stage: int
    max_storage_buffer_binding_size: int
    max_buffer_size: int
    max_compute_invocations_per_workgroup: int
    max_compute_workgroups_per_dimension: int
    def supports_storage_buffers(self, n: int) -> bool: ...
    def max_items_per_binding(self, stride: int) -> int: ...
    def max_invocations_per_dispatch(self, workgroup_size: int) -> int: ...
    def max_chunk_items(self, stride: int, workgroup_size: int) -> int: ...

class HardwareCapabilities:
    gpu: GpuLimits | None
    cpu_threads: int
    @staticmethod
    def with_gpu(gpu: GpuLimits | None) -> HardwareCapabilities: ...
    def gpu_supports_storage_buffers(self, n: int) -> bool: ...
    def __init__(self, gpu: GpuLimits | None, cpu_threads: int) -> None: ...

class SplitPolicy:
    @staticmethod
    def auto_fraction(caps: HardwareCapabilities) -> float: ...
    def gpu_fraction(self, caps: HardwareCapabilities) -> float: ...
    @staticmethod
    def CpuOnly() -> SplitPolicy: ...
    @staticmethod
    def GpuOnly() -> SplitPolicy: ...
    @staticmethod
    def GpuFraction(a0: float) -> SplitPolicy: ...
    @staticmethod
    def Auto() -> SplitPolicy: ...
    def variant(self) -> str: ...

class SplitReason:
    @staticmethod
    def NoGpu() -> SplitReason: ...
    @staticmethod
    def InsufficientStorageBuffers() -> SplitReason: ...
    @staticmethod
    def PolicyCpuOnly() -> SplitReason: ...
    @staticmethod
    def Split() -> SplitReason: ...
    def variant(self) -> str: ...

class WorkSplit:
    gpu_items: int
    cpu_items: int
    gpu_chunk_items: int
    reason: SplitReason
    def total(self) -> int: ...
    def uses_gpu(self) -> bool: ...
    def __init__(self, gpu_items: int, cpu_items: int, gpu_chunk_items: int, reason: SplitReason) -> None: ...

class UnionTotalXs:
    grid: list[float]
    sigma_total: list[float]
    temperature_k: float
    def lookup_cpu(self, queries_ev: list[float]) -> list[float]: ...
    def __init__(self, grid: list[float], sigma_total: list[float], temperature_k: float) -> None: ...

class NuclideComponent:
    nuclide_idx: int
    atom_density: float
    def __init__(self, nuclide_idx: int, atom_density: float) -> None: ...

class Inelastic:
    @staticmethod
    def Level(q: float) -> Inelastic: ...
    @staticmethod
    def Continuum() -> Inelastic: ...
    def variant(self) -> str: ...

class ReactionMT:
    def mt_number(self) -> int: ...
    @staticmethod
    def Elastic() -> ReactionMT: ...
    @staticmethod
    def Fission() -> ReactionMT: ...
    @staticmethod
    def Capture() -> ReactionMT: ...
    @staticmethod
    def Inelastic() -> ReactionMT: ...
    @staticmethod
    def N2N() -> ReactionMT: ...
    @staticmethod
    def N3N() -> ReactionMT: ...
    @staticmethod
    def Total() -> ReactionMT: ...
    @staticmethod
    def Other(a0: int) -> ReactionMT: ...
    def variant(self) -> str: ...

class Bank:
    sites: list[BankSite]
    def __init__(self, ) -> None: ...
    def push(self, site: BankSite) -> None: ...
    def len(self) -> int: ...
    def clear(self) -> None: ...
    @staticmethod
    def default() -> Bank: ...

class BankSite:
    r: Position
    u: Direction
    e: float
    wgt: float
    seed: int
    def __init__(self, r: Position, u: Direction, e: float, wgt: float, seed: int) -> None: ...

class TallyEvent:
    @staticmethod
    def None_() -> TallyEvent: ...
    @staticmethod
    def Scatter() -> TallyEvent: ...
    @staticmethod
    def Fission() -> TallyEvent: ...
    @staticmethod
    def Absorption() -> TallyEvent: ...
    @staticmethod
    def Surface() -> TallyEvent: ...
    @staticmethod
    def Leak() -> TallyEvent: ...
    def variant(self) -> str: ...

class Reference:
    authors: str
    title: str
    journal: str
    year: int
    doi: str
    def to_bibtex(self) -> str: ...

class PackingError:
    @staticmethod
    def NotImplemented(a0: PackingMethod) -> PackingError: ...
    @staticmethod
    def PackingTooDense(requested: float, limit: float) -> PackingError: ...
    @staticmethod
    def PlacementFailed(placed: int, target: int, attempts: int) -> PackingError: ...
    @staticmethod
    def DomainTooSmall(half_width: float, radius: float) -> PackingError: ...
    def variant(self) -> str: ...

class Sphere:
    center: Position
    radius: float
    def __init__(self, center: Position, radius: float) -> None: ...

class HardwareInfo:
    gpu: str | None
    cpu_logical_cores: int
    os: str
    @staticmethod
    def detect() -> HardwareInfo: ...
    def headline(self) -> str: ...
    def __init__(self, gpu: str | None, cpu_logical_cores: int, os: str) -> None: ...

class PerfReport:
    title: str
    hardware: HardwareInfo
    rows: list[PerfRow]
    date: str
    def __init__(self, title: str, date: str) -> None: ...
    def push(self, row: PerfRow) -> None: ...
    def render_markdown(self) -> str: ...
    def to_csv(self) -> str: ...

class PerfRow:
    batch_size: int
    backend: str
    wall_time_s: float
    k_mean: float
    k_std: float
    histories_total: int
    def throughput_hps(self) -> float: ...
    def __init__(self, batch_size: int, backend: str, wall_time_s: float, k_mean: float, k_std: float, histories_total: int) -> None: ...

class MgSettings:
    n_particles: int
    n_inactive: int
    n_active: int
    seed: int
    def __init__(self, n_particles: int | None = None, n_inactive: int | None = None, n_active: int | None = None, seed: int | None = None) -> None: ...
    @staticmethod
    def default() -> MgSettings: ...

class Mgxs:
    name: str
    n_groups: int
    total: list[float]
    absorption: list[float]
    fission: list[float]
    nu_fission: list[float]
    chi: list[float]
    scatter: list[float]
    def __init__(self, name: str, total: list[float], absorption: list[float], fission: list[float], nu_fission: list[float], chi: list[float], scatter: list[float]) -> None: ...
    def scatter_out(self, g: int) -> float: ...
    def consistency_residual(self) -> float: ...
    def nu_bar(self, g: int) -> float: ...
    def is_fissile(self) -> bool: ...

class MgxsLibrary:
    materials: list[Mgxs]
    def __init__(self, materials: list[Mgxs]) -> None: ...
    def n_groups(self) -> int: ...
    def material(self, i: int) -> Mgxs: ...

class AbsorptionBenchmark:
    domain_half_width: float
    particle_radius: float
    packing_fraction: float
    scatter_mfp: float
    max_collisions: int
    histories: int
    def compare(self, seed: int) -> list[BenchmarkResult]: ...
    def __init__(self, domain_half_width: float, particle_radius: float, packing_fraction: float, scatter_mfp: float, max_collisions: int, histories: int) -> None: ...

class AdaptiveRadius:
    def __init__(self, initial_mfp: float, alpha: float, largest_radius: float, min_radius: float, max_radius: float) -> None: ...
    def radius(self) -> float: ...
    def mean_track(self) -> float: ...
    def update(self, track_length: float) -> float: ...

class BenchmarkResult:
    model: str
    absorption_probability: float
    leakage_probability: float
    histories: int

class BoundaryHit:
    distance: float
    crossing: Crossing
    coord_level: int
    def __init__(self, distance: float, crossing: Crossing, coord_level: int) -> None: ...

class BoundaryType:
    @staticmethod
    def Transmissive() -> BoundaryType: ...
    @staticmethod
    def Vacuum() -> BoundaryType: ...
    @staticmethod
    def Reflective() -> BoundaryType: ...
    @staticmethod
    def Periodic() -> BoundaryType: ...
    @staticmethod
    def White() -> BoundaryType: ...
    def variant(self) -> str: ...

class BruteForceIndex:
    def __init__(self, ) -> None: ...
    @staticmethod
    def from_histories(histories: list[ParticleHistory]) -> BruteForceIndex: ...
    def insert(self, history: ParticleHistory) -> None: ...
    def clear(self) -> None: ...
    def len(self) -> int: ...
    def is_empty(self) -> bool: ...
    def histories(self) -> list[ParticleHistory]: ...
    def find_containing(self, p: Position) -> ParticleHistory | None: ...
    def query_within(self, p: Position, radius: float) -> list[int]: ...
    @staticmethod
    def default() -> BruteForceIndex: ...

class BuildReport:
    unregistered: list[int]
    radius_exceeds_pitch: list[int]
    registrations: int
    def __init__(self, unregistered: list[int] | None = None, radius_exceeds_pitch: list[int] | None = None, registrations: int | None = None) -> None: ...
    @staticmethod
    def default() -> BuildReport: ...

class Cell:
    id: int
    region: list[RegionToken]
    fill: CellFill
    temperature: float
    translation: Position
    @staticmethod
    def material(id: int, region: list[RegionToken], material_idx: int, temperature: float) -> Cell: ...
    def __init__(self, id: int, region: list[RegionToken], fill: CellFill, temperature: float, translation: Position) -> None: ...

class CellFill:
    @staticmethod
    def Material(a0: int) -> CellFill: ...
    @staticmethod
    def Universe(a0: int) -> CellFill: ...
    @staticmethod
    def Lattice(a0: int) -> CellFill: ...
    @staticmethod
    def Void() -> CellFill: ...
    def variant(self) -> str: ...

class CellFilter:
    cell_indices: list[int]
    def __init__(self, cell_indices: list[int]) -> None: ...

class ClsMedium:
    def __init__(self, inclusion_radius: float, packing_fraction: float, inclusion: MaterialId, matrix: MaterialId) -> None: ...
    def begin_flight(self) -> None: ...
    def in_inclusion(self) -> bool | None: ...
    def inclusion_radius(self) -> float: ...
    def packing_fraction(self) -> float: ...
    def inclusion_material(self) -> MaterialId: ...
    def matrix_material(self) -> MaterialId: ...
    def mean_chord_inclusion(self) -> float: ...
    def mean_chord_matrix(self) -> float: ...

class CoherentElasticTable:
    def cross_section(self, e: float) -> float: ...
    def bragg_cutoff_ev(self) -> float: ...

class CollisionTables:
    grid: list[float]
    macro_total: list[float]
    n_nuclides: int
    micro_total: list[float]
    micro_fission: list[float]
    micro_absorption: list[float]
    micro_inelastic: list[float]
    micro_nu_fission: list[float]
    micro_mubar: list[float]
    atom_density: list[float]
    awr: list[float]
    e_max: list[float]
    temperature_k: float
    def n_grid(self) -> int: ...
    def __init__(self, grid: list[float], macro_total: list[float], n_nuclides: int, micro_total: list[float], micro_fission: list[float], micro_absorption: list[float], micro_inelastic: list[float], micro_nu_fission: list[float], micro_mubar: list[float], atom_density: list[float], awr: list[float], e_max: list[float], temperature_k: float) -> None: ...

class ComputeType:
    @staticmethod
    def CpuSingleThread() -> ComputeType: ...
    @staticmethod
    def CpuMultiThread(a0: ThreadCount) -> ComputeType: ...
    @staticmethod
    def Gpu() -> ComputeType: ...
    def variant(self) -> str: ...
    @staticmethod
    def default() -> ComputeType: ...

class Coord:
    universe: int
    cell: int
    r: Position
    u: Direction
    lattice: int | None
    lattice_index: list[int]

class Crossing:
    @staticmethod
    def Surface(a0: int) -> Crossing: ...
    @staticmethod
    def Lattice() -> Crossing: ...
    @staticmethod
    def None_() -> Crossing: ...
    def variant(self) -> str: ...

class CrpError:
    @staticmethod
    def DomainTooSmall(half_width: float, radius: float) -> CrpError: ...
    @staticmethod
    def PackingTooDense(requested: float, limit: float) -> CrpError: ...
    @staticmethod
    def DidNotConverge(iterations: int, achieved: float, target: float, pf_reached: float) -> CrpError: ...
    def variant(self) -> str: ...

class DeltaEvent:
    @staticmethod
    def Real() -> DeltaEvent: ...
    @staticmethod
    def Virtual() -> DeltaEvent: ...
    def variant(self) -> str: ...

class DeltaFlight:
    position: Position
    distance: float
    virtual_collisions: int
    escaped: bool
    def __init__(self, position: Position, distance: float, virtual_collisions: int, escaped: bool) -> None: ...

class DerivedTally:
    values: list[float]
    std_devs: list[float]
    def __init__(self, values: list[float], std_devs: list[float]) -> None: ...
    def len(self) -> int: ...
    def is_empty(self) -> bool: ...
    def get(self, i: int) -> tuple[float, float]: ...
    def slice(self, start: int, end: int) -> DerivedTally: ...
    def add(self, other: DerivedTally) -> DerivedTally: ...
    def sub(self, other: DerivedTally) -> DerivedTally: ...
    def mul(self, other: DerivedTally) -> DerivedTally: ...
    def div(self, other: DerivedTally) -> DerivedTally: ...
    def scalar_mul(self, k: float) -> DerivedTally: ...
    def sum(self) -> tuple[float, float]: ...

class Direction:
    u: float
    v: float
    w: float
    def __init__(self, u: float, v: float, w: float) -> None: ...
    @staticmethod
    def from_unnormalised(x: float, y: float, z: float) -> Direction: ...
    def dot_pos(self, p: Position) -> float: ...

class EncodedSurfaces:
    tags: list[int]
    coeffs: list[float]
    def len(self) -> int: ...
    def is_empty(self) -> bool: ...
    def __init__(self, tags: list[int], coeffs: list[float]) -> None: ...

class EnergyFilter:
    bins: list[float]
    def __init__(self, bins: list[float]) -> None: ...

class EventBatch:
    pos: list[float]
    dir: list[float]
    energy: list[float]
    seed_lo: list[int]
    seed_hi: list[int]
    alive: list[int]
    fiss_nuc: list[int]
    production: list[float]
    def len(self) -> int: ...
    def is_empty(self) -> bool: ...
    def n_alive(self) -> int: ...
    def __init__(self, pos: list[float], dir: list[float], energy: list[float], seed_lo: list[int], seed_hi: list[int], alive: list[int], fiss_nuc: list[int], production: list[float]) -> None: ...

class EventSphere:
    x0: float
    y0: float
    z0: float
    r: float
    def __init__(self, x0: float, y0: float, z0: float, r: float) -> None: ...

class EventTablesF32:
    xs: list[float]
    n_grid: int
    n_nuclide: int
    def __init__(self, xs: list[float], n_grid: int, n_nuclide: int) -> None: ...

class FixedSource:
    @staticmethod
    def Point(r: Position, energy_ev: float) -> FixedSource: ...
    @staticmethod
    def Box(lower: Position, upper: Position, energy_ev: float) -> FixedSource: ...
    def variant(self) -> str: ...

class FixedSourceResult:
    source_particles: int
    total_histories: int
    multiplication: float
    def __init__(self, source_particles: int, total_histories: int, multiplication: float) -> None: ...

class FixedSourceSettings:
    n_particles: int
    n_batches: int
    temperature_k: float
    seed: int
    max_secondaries: int
    def __init__(self, n_particles: int | None = None, n_batches: int | None = None, temperature_k: float | None = None, seed: int | None = None, max_secondaries: int | None = None) -> None: ...
    @staticmethod
    def default() -> FixedSourceSettings: ...

class FlightBatch:
    pos: list[float]
    dir: list[float]
    energy: list[float]
    rng_hi: list[int]
    rng_lo: list[int]
    def len(self) -> int: ...
    def is_empty(self) -> bool: ...
    def __init__(self, pos: list[float], dir: list[float], energy: list[float], rng_hi: list[int], rng_lo: list[int]) -> None: ...

class FlightOutcome:
    @staticmethod
    def Leaked() -> FlightOutcome: ...
    @staticmethod
    def Collided() -> FlightOutcome: ...
    def variant(self) -> str: ...

class FlightSegment:
    start: Position
    end: Position
    def __init__(self, start: Position, end: Position) -> None: ...
    def length(self) -> float: ...

class FlightSphere:
    x0: float
    y0: float
    z0: float
    r: float
    def __init__(self, x0: float, y0: float, z0: float, r: float) -> None: ...

class Geometry:
    root_universe: int
    def locate(self, r: Position, u: Direction, on_surface: int) -> GeometryPath | None: ...
    def cross_surface(self, i_surf: int, r: Position, u: Direction) -> tuple[Position, Direction, bool]: ...

class GeometryPath:
    levels: list[Coord]
    material: int | None
    on_surface: int
    def leaf(self) -> Coord: ...
    def __init__(self, levels: list[Coord], material: int | None, on_surface: int) -> None: ...

class HalfSpaceSense:
    @staticmethod
    def Inside() -> HalfSpaceSense: ...
    @staticmethod
    def Outside() -> HalfSpaceSense: ...
    def variant(self) -> str: ...

class HexLattice:
    id: int
    orientation: HexOrientation
    n_rings: int
    n_axial: int
    center: Position
    pitch: list[float]
    universes: list[int]
    outer: int | None
    def get_indices(self, r: Position, u: Direction) -> list[int]: ...
    @staticmethod
    def from_rings(id: int, orientation: HexOrientation, center: Position, radial_pitch: float, rings: list[list[int]], outer: int | None) -> HexLattice: ...
    @staticmethod
    def from_rings_3d(id: int, orientation: HexOrientation, center: Position, radial_pitch: float, axial_pitch: float, levels: list[list[list[int]]], outer: int | None) -> HexLattice: ...

class HexOrientation:
    @staticmethod
    def Y() -> HexOrientation: ...
    @staticmethod
    def X() -> HexOrientation: ...
    def variant(self) -> str: ...

class InclusionSphere:
    center: Position
    radius: float
    def __init__(self, center: Position, transport_mfp: float, largest_inclusion_radius: float) -> None: ...
    def contains(self, p: Position) -> bool: ...
    def overlaps(self, center: Position, radius: float) -> bool: ...
    def recenter(self, new_center: Position) -> None: ...

class IncoherentElasticTable:
    def cross_section(self, e: float) -> float: ...

class IndexError:
    def variant(self) -> str: ...

class KdTreeIndex:
    @staticmethod
    def build(histories: list[ParticleHistory]) -> KdTreeIndex: ...
    def len(self) -> int: ...
    def is_empty(self) -> bool: ...
    def find_containing(self, p: Position) -> ParticleHistory | None: ...
    def query_within(self, p: Position, radius: float) -> list[int]: ...
    def __init__(self) -> None: ...
    @staticmethod
    def default() -> KdTreeIndex: ...

class KeffResult:
    k_mean: float
    k_std: float
    k_by_generation: list[float]
    def __init__(self, k_mean: float, k_std: float, k_by_generation: list[float]) -> None: ...

class KeffSettings:
    n_particles: int
    n_inactive: int
    n_active: int
    temperature_k: float
    seed: int
    watt_a: float
    watt_b: float
    compute: ComputeType
    def with_compute(self, compute: ComputeType) -> KeffSettings: ...
    def __init__(self, n_particles: int | None = None, n_inactive: int | None = None, n_active: int | None = None, temperature_k: float | None = None, seed: int | None = None, watt_a: float | None = None, watt_b: float | None = None, compute: ComputeType | None = None) -> None: ...
    @staticmethod
    def default() -> KeffSettings: ...

class Lattice:
    def id(self) -> int: ...
    def get_indices(self, r: Position, u: Direction) -> list[int]: ...
    def variant(self) -> str: ...

class LegendreAxis:
    @staticmethod
    def X() -> LegendreAxis: ...
    @staticmethod
    def Y() -> LegendreAxis: ...
    @staticmethod
    def Z() -> LegendreAxis: ...
    def variant(self) -> str: ...

class MacroXs:
    total: float
    elastic: float
    fission: float
    nu_fission: float
    def __init__(self, total: float | None = None, elastic: float | None = None, fission: float | None = None, nu_fission: float | None = None) -> None: ...
    @staticmethod
    def default() -> MacroXs: ...

class Majorant:
    @staticmethod
    def uniform(sigma_max: float) -> Majorant: ...
    def at(self, e: float) -> float: ...
    def __init__(self) -> None: ...
    @staticmethod
    def default() -> Majorant: ...

class Material:
    id: int
    name: str
    components: list[NuclideComponent]
    temperature: float
    def __init__(self, id: int, name: str, components: list[NuclideComponent], temperature: float) -> None: ...

class MaterialFilter:
    material_indices: list[int]
    def __init__(self, material_indices: list[int]) -> None: ...

class MaterialId:
    def index(self) -> int: ...

class MediumError:
    def variant(self) -> str: ...

class MeshFilter:
    mesh: RegularMesh
    def __init__(self, mesh: RegularMesh) -> None: ...

class MicroXS:
    total: float
    elastic: float
    fission: float
    absorption: float
    inelastic: float
    n2n: float
    nu_fission: float
    def __init__(self, total: float | None = None, elastic: float | None = None, fission: float | None = None, absorption: float | None = None, inelastic: float | None = None, n2n: float | None = None, nu_fission: float | None = None) -> None: ...
    @staticmethod
    def default() -> MicroXS: ...

class Nuclide:
    name: str
    awr: float
    @staticmethod
    def from_core(name: str) -> Nuclide: ...
    def xs_at_energy(self, e: float, temp_k: float) -> MicroXS: ...
    def elastic_mubar(self, e: float) -> float: ...
    def e_max_ev(self) -> float: ...
    def native_energy_grid(self, e_min_ev: float, e_max_ev: float) -> list[float]: ...

class PackedSpheres:
    @staticmethod
    def pack(radius: float, half_width: float, packing_fraction: float, seed: int) -> PackedSpheres: ...
    @staticmethod
    def from_spheres(spheres: list[Sphere], half_width: float, radius: float) -> PackedSpheres: ...
    def is_inside_kernel(self, p: Position) -> bool: ...
    def spheres(self) -> list[Sphere]: ...
    def len(self) -> int: ...
    def is_empty(self) -> bool: ...
    def half_width(self) -> float: ...
    def radius(self) -> float: ...
    def packing_fraction(self) -> float: ...
    def min_center_distance(self) -> float | None: ...

class PackingConfig:
    particle_radius: float
    packing_fraction: float
    domain_half_width: float
    method: PackingMethod
    seed: int
    def generate(self) -> list[Sphere]: ...
    def __init__(self, particle_radius: float, packing_fraction: float, domain_half_width: float, method: PackingMethod, seed: int) -> None: ...

class PackingMethod:
    @staticmethod
    def Rsa() -> PackingMethod: ...
    @staticmethod
    def RsaDem() -> PackingMethod: ...
    @staticmethod
    def OdrDem() -> PackingMethod: ...
    def variant(self) -> str: ...

class Particle:
    r: Position
    u: Direction
    e: float
    wgt: float
    cell: int
    material: int
    surface: int
    seed: int
    particle_type: ParticleType
    alive: bool
    event: TallyEvent
    n_collision: int
    def __init__(self, r: Position, u: Direction, e: float, wgt: float, seed: int) -> None: ...

class ParticleHistory:
    center: Position
    radius: float
    material_id: MaterialId
    def __init__(self, center: Position, radius: float, material_id: MaterialId) -> None: ...
    def contains(self, p: Position) -> bool: ...

class ParticleType:
    @staticmethod
    def Neutron() -> ParticleType: ...
    @staticmethod
    def Photon() -> ParticleType: ...
    @staticmethod
    def Electron() -> ParticleType: ...
    @staticmethod
    def Positron() -> ParticleType: ...
    def variant(self) -> str: ...

class Position:
    x: float
    y: float
    z: float
    def __init__(self, x: float, y: float, z: float) -> None: ...
    def dot(self, other: Position) -> float: ...
    def norm_sqr(self) -> float: ...
    def norm(self) -> float: ...
    def distance(self, other: Position) -> float: ...
    @staticmethod
    def default() -> Position: ...

class RectLattice:
    id: int
    n: list[int]
    lower_left: Position
    pitch: list[float]
    universes: list[int]
    outer: int | None
    def get_indices(self, r: Position, u: Direction) -> list[int]: ...
    def distance(self, r: Position, u: Direction) -> tuple[float, list[int]]: ...

class RegionToken:
    @staticmethod
    def HalfSpace(surface_idx: int, sense: HalfSpaceSense) -> RegionToken: ...
    @staticmethod
    def Intersection() -> RegionToken: ...
    @staticmethod
    def Union() -> RegionToken: ...
    @staticmethod
    def Complement() -> RegionToken: ...
    def variant(self) -> str: ...

class RegularMesh:
    lower_left: list[float]
    upper_right: list[float]
    dimension: list[int]
    def width(self) -> list[float]: ...
    def n_bins(self) -> int: ...
    def get_bin(self, p: Position) -> int | None: ...

class RsaMedium:
    def __init__(self, packing: PackedSpheres, inclusion: MaterialId, matrix: MaterialId) -> None: ...
    def material_at(self, p: Position) -> MaterialId: ...
    def packing(self) -> PackedSpheres: ...
    def inclusion_material(self) -> MaterialId: ...
    def matrix_material(self) -> MaterialId: ...

class SclsMedium:
    def __init__(self, cls: ClsMedium, start: Position, transport_mfp: float) -> None: ...
    def cls(self) -> ClsMedium: ...
    def sphere(self) -> InclusionSphere: ...
    def histories(self) -> list[ParticleHistory]: ...
    def flights(self) -> list[FlightSegment]: ...
    def remember_inclusion(self, history: ParticleHistory) -> None: ...
    def remember_flight(self, segment: FlightSegment) -> None: ...
    def advance_to(self, new_position: Position) -> int: ...
    def set_sphere_radius(self, radius: float) -> None: ...
    def retained_material_at(self, p: Position) -> MaterialId | None: ...
    def begin_flight(self) -> None: ...
    def in_inclusion(self) -> bool | None: ...

class ScoreType:
    @staticmethod
    def Flux() -> ScoreType: ...
    @staticmethod
    def Total() -> ScoreType: ...
    @staticmethod
    def Fission() -> ScoreType: ...
    @staticmethod
    def Absorption() -> ScoreType: ...
    @staticmethod
    def NuFission() -> ScoreType: ...
    @staticmethod
    def KappaFission() -> ScoreType: ...
    @staticmethod
    def ScatterN() -> ScoreType: ...
    @staticmethod
    def Current() -> ScoreType: ...
    @staticmethod
    def Events() -> ScoreType: ...
    def variant(self) -> str: ...

class SearchError:
    @staticmethod
    def BracketDoesNotStraddle(k_lo: float, k_hi: float, target: float) -> SearchError: ...
    @staticmethod
    def InvalidBracket(lo: float, hi: float) -> SearchError: ...
    def variant(self) -> str: ...

class SearchIteration:
    parameter: float
    keff: float
    keff_std: float
    def __init__(self, parameter: float, keff: float, keff_std: float) -> None: ...

class SearchMethod:
    @staticmethod
    def Bisect() -> SearchMethod: ...
    @staticmethod
    def Secant() -> SearchMethod: ...
    def variant(self) -> str: ...

class SearchResult:
    parameter: float
    keff: float
    keff_std: float
    converged: bool
    iterations: list[SearchIteration]
    def __init__(self, parameter: float, keff: float, keff_std: float, converged: bool, iterations: list[SearchIteration]) -> None: ...

class SearchSettings:
    target: float
    tol: float
    k_tol: float
    max_iterations: int
    method: SearchMethod
    def __init__(self, target: float | None = None, tol: float | None = None, k_tol: float | None = None, max_iterations: int | None = None, method: SearchMethod | None = None) -> None: ...
    @staticmethod
    def default() -> SearchSettings: ...

class SourceBox:
    lower: Position
    upper: Position
    def __init__(self, lower: Position, upper: Position) -> None: ...

class SpatialIndex:
    @staticmethod
    def brute_force(histories: list[ParticleHistory]) -> SpatialIndex: ...
    @staticmethod
    def kd_tree(histories: list[ParticleHistory]) -> SpatialIndex: ...
    def name(self) -> str: ...
    def find_containing(self, p: Position) -> ParticleHistory | None: ...
    def query_within(self, p: Position, radius: float) -> list[int]: ...
    def len(self) -> int: ...
    def is_empty(self) -> bool: ...
    @staticmethod
    def BruteForce(a0: BruteForceIndex) -> SpatialIndex: ...
    @staticmethod
    def KdTree(a0: KdTreeIndex) -> SpatialIndex: ...
    @staticmethod
    def RTree() -> SpatialIndex: ...
    def variant(self) -> str: ...

class SpatialLegendreFilter:
    order: int
    axis: LegendreAxis
    min: float
    max: float
    def __init__(self, order: int, axis: LegendreAxis, min: float, max: float) -> None: ...

class prelude_Sphere:
    x0: float
    y0: float
    z0: float
    r: float
    bc: BoundaryType
    def __init__(self, x0: float, y0: float, z0: float, r: float, bc: BoundaryType) -> None: ...

class StochasticMedium:
    def begin_flight(self) -> None: ...
    def name(self) -> str: ...
    def is_exact(self) -> bool: ...
    @staticmethod
    def Rsa(a0: RsaMedium) -> StochasticMedium: ...
    @staticmethod
    def Cls(a0: ClsMedium) -> StochasticMedium: ...
    @staticmethod
    def Scls(a0: SclsMedium) -> StochasticMedium: ...
    def variant(self) -> str: ...

class SurfaceKind:
    def evaluate(self, r: Position) -> float: ...
    def sense(self, r: Position) -> bool: ...
    def distance(self, r: Position, u: Direction, coincident: bool) -> float: ...
    def normal(self, r: Position) -> Direction: ...
    def reflect(self, r: Position, u: Direction) -> Direction: ...
    def bc(self) -> BoundaryType: ...
    def sphere_centre_radius(self) -> tuple[list[float], float] | None: ...
    def variant(self) -> str: ...

class SurfaceQuery:
    surface: int
    coincident: bool
    r: Position
    u: Direction
    def __init__(self, surface: int, coincident: bool, r: Position, u: Direction) -> None: ...

class Tally:
    id: int
    name: str
    scores: list[ScoreType]
    bins: list[TallyBin]
    def n_bins(self) -> int: ...

class TallyBin:
    sum: float
    sum_sq: float
    count: int
    def score(self, value: float) -> None: ...
    def mean(self, n_realizations: int) -> float: ...
    def rel_std_dev(self, n_realizations: int) -> float: ...
    def __init__(self, sum: float | None = None, sum_sq: float | None = None, count: int | None = None) -> None: ...
    @staticmethod
    def default() -> TallyBin: ...

class ThermalElastic:
    def cross_section(self, e: float) -> float: ...
    def kind_name(self) -> str: ...
    @staticmethod
    def None_() -> ThermalElastic: ...
    def variant(self) -> str: ...

class ThermalScattering:
    name: str
    @staticmethod
    def from_endf_file(path: str, mat: int, temperature_k: float, name: str) -> ThermalScattering: ...
    @staticmethod
    def from_leapr(material: njoy_outram_park_fork.SabMaterial, temperature_k: float, name: str) -> ThermalScattering: ...
    def cutoff_ev(self) -> float: ...
    def selected_temperature_k(self) -> float: ...
    def elastic_xs(self, e: float) -> float: ...
    def total_xs(self, e: float) -> float: ...
    def inelastic_xs(self, e: float) -> float: ...

class ThreadCount:
    def resolve(self) -> int: ...
    @staticmethod
    def Auto() -> ThreadCount: ...
    @staticmethod
    def Fixed(a0: int) -> ThreadCount: ...
    @staticmethod
    def Fraction(a0: float) -> ThreadCount: ...
    def variant(self) -> str: ...
    @staticmethod
    def default() -> ThreadCount: ...

class TrisoMaterials:
    kernel: int
    buffer: int
    ipyc: int
    sic: int
    opyc: int
    matrix: int
    def __init__(self, kernel: int, buffer: int, ipyc: int, sic: int, opyc: int, matrix: int) -> None: ...

class TrisoRadii:
    kernel: float
    buffer: float
    ipyc: float
    sic: float
    opyc: float
    def as_array(self) -> list[float]: ...
    def is_strictly_increasing(self) -> bool: ...
    def __init__(self, kernel: float, buffer: float, ipyc: float, sic: float, opyc: float) -> None: ...

class Universe:
    id: int
    cell_indices: list[int]
    def __init__(self, id: int, cell_indices: list[int]) -> None: ...

class UniverseFilter:
    universe_indices: list[int]
    def __init__(self, universe_indices: list[int]) -> None: ...

class VirtualLattice:
    lower_left: list[float]
    pitch: list[float]
    shape: list[int]
    def n_voxels(self) -> int: ...
    def indices_at(self, r: Position) -> list[int]: ...
    def clamped_indices_at(self, r: Position) -> list[int]: ...

class XPlane:
    x0: float
    bc: BoundaryType
    def __init__(self, x0: float, bc: BoundaryType) -> None: ...

class YPlane:
    y0: float
    bc: BoundaryType
    def __init__(self, y0: float, bc: BoundaryType) -> None: ...

class ZCylinder:
    x0: float
    y0: float
    r: float
    bc: BoundaryType
    def __init__(self, x0: float, y0: float, r: float, bc: BoundaryType) -> None: ...

class ZPlane:
    z0: float
    bc: BoundaryType
    def __init__(self, z0: float, bc: BoundaryType) -> None: ...

class Lcg64:
    def __init__(self, seed: int) -> None: ...
    def rand_float(self) -> float: ...
    def rand_u64(self) -> int: ...

class MonodirectionalAngle:
    d: Direction
    def __init__(self, d: Direction) -> None: ...

class MaxwellSpectrum:
    theta: float
    def __init__(self, theta: float) -> None: ...

class Monoenergetic:
    e: float
    def __init__(self, e: float) -> None: ...

class TabulatedEnergy:
    energies: list[float]
    cdf: list[float]
    def __init__(self, energies: list[float], cdf: list[float]) -> None: ...

class WattSpectrum:
    a: float
    b: float
    def __init__(self, a: float, b: float) -> None: ...

class IndependentSource:
    strength: float

class SourceSite:
    r: Position
    u: Direction
    e: float
    wgt: float
    def __init__(self, r: Position, u: Direction, e: float, wgt: float) -> None: ...

class BoxSource:
    lower_left: Position
    upper_right: Position
    def __init__(self, lower_left: Position, upper_right: Position) -> None: ...

class PointSource:
    r: Position
    def __init__(self, r: Position) -> None: ...

class SphericalSource:
    center: Position
    r_inner: float
    r_outer: float
    def __init__(self, center: Position, r_inner: float, r_outer: float) -> None: ...

class FilterEvent:
    cell_idx: int
    material_idx: int
    universe_idx: int
    energy: float
    surface_idx: int
    position: Position
    def __init__(self, cell_idx: int, material_idx: int, universe_idx: int, energy: float, surface_idx: int, position: Position) -> None: ...

def cram16(a: DepletionMatrix, n0: list[float], dt_seconds: float) -> list[float]: ...
def cram48(a: DepletionMatrix, n0: list[float], dt_seconds: float) -> list[float]: ...
def deplete_predictor(chain: DepletionChain, initial: list[tuple[str, float]], settings: BurnupSettings) -> BurnupResult: ...
def mc_keff_of_actinide_sphere(inventory: list[tuple[str, float]], radius_cm: float, settings: KeffSettings) -> KeffResult: ...
def stream(pos: Position, dir: Direction, distance: float) -> Position: ...
def cpu_threads() -> int: ...
def measured_gpu_fraction(gpu_items_per_second: float, cpu_items_per_second: float) -> float: ...
def plan_split(total: int, caps: HardwareCapabilities, policy: SplitPolicy, storage_buffers_needed: int, stride: int, workgroup_size: int) -> WorkSplit: ...
def probe() -> GpuContext | None: ...
def build_triso_particle(center: Position, radii: TrisoRadii, materials: TrisoMaterials, temperature: float, universe_id: int, surface_base: int, cell_base: int) -> TrisoParticle: ...
def future_seed(n: int, seed: int) -> int: ...
def init_seed(id: int, offset: int, master_seed: int) -> int: ...
def interp_xs_cpu(grid: list[float], sigma: list[float], queries: list[float]) -> list[float]: ...
def matrix_mean_chord_length(radius: float, packing_fraction: float) -> float: ...
def mean_chord_length_sphere(radius: float) -> float: ...
def pack_spheres(radius: float, half_width: float, packing_fraction: float, seed: int) -> list[Sphere]: ...
def pack_spheres_crp(radius: float, half_width: float, packing_fraction: float, seed: int) -> list[Sphere]: ...
def triso_particle(center: Position, radii: TrisoRadii, materials: TrisoMaterials, temperature: float) -> TrisoParticle: ...
HEX_NONE: int
QUERY_STRIDE_BYTES: int
STORAGE_BUFFERS_NEEDED: int
WORKGROUP_SIZE: int
DEFAULT_THERMAL_CUTOFF_EV: float
MAX_PF_RSA: float
LOCAL_PERF_DIR: str
FISS_NONE: int
MAX_PF_CRP: float
MISS: float
Q_FISSION_J: float
SURF_STRIDE: int
DEFAULT_STRIDE: int
INC: int
MULT: int
