"""Type stubs for `outram_park.raffles`, generated from the Rust API.

Physical quantities cross this boundary as `float` in SI base units.
"""

class RafflesError:
    @staticmethod
    def InvalidParameter(parameter: str, value: float, reason: str) -> RafflesError: ...
    @staticmethod
    def DimensionMismatch(expected: int, found: int) -> RafflesError: ...
    def variant(self) -> str: ...

class Beta:
    def alpha(self) -> float: ...
    def beta(self) -> float: ...
    def low(self) -> float: ...
    def high(self) -> float: ...
    def scale(self) -> float: ...

class Distribution:
    @staticmethod
    def Uniform(a0: Uniform) -> Distribution: ...
    @staticmethod
    def Normal(a0: Normal) -> Distribution: ...
    @staticmethod
    def LogNormal(a0: LogNormal) -> Distribution: ...
    @staticmethod
    def Triangular(a0: Triangular) -> Distribution: ...
    @staticmethod
    def Exponential(a0: Exponential) -> Distribution: ...
    @staticmethod
    def Weibull(a0: Weibull) -> Distribution: ...
    @staticmethod
    def Gamma(a0: Gamma) -> Distribution: ...
    @staticmethod
    def Beta(a0: Beta) -> Distribution: ...
    def variant(self) -> str: ...

class Exponential:
    def low(self) -> float: ...

class Gamma:
    def alpha(self) -> float: ...
    def beta(self) -> float: ...
    def low(self) -> float: ...

class LogNormal:
    def mu(self) -> float: ...
    def sigma(self) -> float: ...
    def low(self) -> float: ...

class Normal:
    def mu(self) -> float: ...
    def sigma(self) -> float: ...

class Triangular:
    def lower(self) -> float: ...
    def apex(self) -> float: ...
    def upper(self) -> float: ...

class Truncated:
    def base(self) -> Distribution: ...
    def lower(self) -> float: ...
    def upper(self) -> float: ...
    def retained_mass(self) -> float: ...

class Uniform:
    def lower(self) -> float: ...
    def upper(self) -> float: ...

class Weibull:
    def k(self) -> float: ...
    def low(self) -> float: ...

class GridSampler:
    def levels(self) -> list[list[float]]: ...

class Sampler:
    def dimensions(self) -> int: ...
    def sample_count(self) -> int: ...
    def generate(self, master_seed: int) -> list[list[float]]: ...
    @staticmethod
    def MonteCarlo(a0: MonteCarlo) -> Sampler: ...
    @staticmethod
    def LatinHypercube(a0: LatinHypercube) -> Sampler: ...
    @staticmethod
    def Grid(a0: GridSampler) -> Sampler: ...
    def variant(self) -> str: ...

class CorrelationKind:
    @staticmethod
    def Pearson() -> CorrelationKind: ...
    @staticmethod
    def Spearman() -> CorrelationKind: ...
    def variant(self) -> str: ...

class SobolIndices:
    first_order: list[float]
    total_effect: list[float]
    mean: float
    total_variance: float
    layout: SobolSampleLayout
    def __init__(self, first_order: list[float], total_effect: list[float], mean: float, total_variance: float, layout: SobolSampleLayout) -> None: ...

class SobolSampleLayout:
    def inputs(self) -> int: ...
    def base_samples(self) -> int: ...
    def model_evaluations(self) -> int: ...

def stream_seed(master_seed: int, stream: int) -> int: ...
