"""Type stubs for `outram_park.raffles`, generated from the Rust API.

Physical quantities cross this boundary as `float` in SI base units.
"""

class RafflesError:
    @staticmethod
    def InvalidParameter(parameter: str, value: float, reason: str) -> RafflesError: ...
    @staticmethod
    def DimensionMismatch(expected: int, found: int) -> RafflesError: ...
    def variant(self) -> str: ...

class Beta:
    def __init__(self, alpha: float, beta: float, low: float, high: float) -> None: ...
    def alpha(self) -> float: ...
    def beta(self) -> float: ...
    def low(self) -> float: ...
    def high(self) -> float: ...
    def scale(self) -> float: ...

class Distribution:
    @staticmethod
    def Uniform(a0: Uniform) -> Distribution: ...
    @staticmethod
    def Normal(a0: Normal) -> Distribution: ...
    @staticmethod
    def LogNormal(a0: LogNormal) -> Distribution: ...
    @staticmethod
    def Triangular(a0: Triangular) -> Distribution: ...
    @staticmethod
    def Exponential(a0: Exponential) -> Distribution: ...
    @staticmethod
    def Weibull(a0: Weibull) -> Distribution: ...
    @staticmethod
    def Gamma(a0: Gamma) -> Distribution: ...
    @staticmethod
    def Beta(a0: Beta) -> Distribution: ...
    def variant(self) -> str: ...

class Exponential:
    def __init__(self, lambda_: float, low: float) -> None: ...
    def low(self) -> float: ...

class Gamma:
    def __init__(self, alpha: float, beta: float, low: float) -> None: ...
    def alpha(self) -> float: ...
    def beta(self) -> float: ...
    def low(self) -> float: ...

class LogNormal:
    def __init__(self, mu: float, sigma: float, low: float) -> None: ...
    def mu(self) -> float: ...
    def sigma(self) -> float: ...
    def low(self) -> float: ...

class Normal:
    def __init__(self, mu: float, sigma: float) -> None: ...
    def mu(self) -> float: ...
    def sigma(self) -> float: ...

class Triangular:
    def __init__(self, lower: float, apex: float, upper: float) -> None: ...
    def lower(self) -> float: ...
    def apex(self) -> float: ...
    def upper(self) -> float: ...

class Truncated:
    def __init__(self, base: Distribution, lower: float, upper: float) -> None: ...
    def base(self) -> Distribution: ...
    def lower(self) -> float: ...
    def upper(self) -> float: ...
    def retained_mass(self) -> float: ...

class Uniform:
    def __init__(self, lower: float, upper: float) -> None: ...
    def lower(self) -> float: ...
    def upper(self) -> float: ...

class Weibull:
    def __init__(self, k: float, lambda_: float, low: float) -> None: ...
    def k(self) -> float: ...
    def low(self) -> float: ...

class GridSampler:
    @staticmethod
    def with_levels(levels: list[list[float]]) -> GridSampler: ...
    @staticmethod
    def equally_spaced(dimensions: int, steps: int, lower: float, upper: float) -> GridSampler: ...
    def levels(self) -> list[list[float]]: ...

class LatinHypercube:
    def __init__(self, samples: int, dimensions: int) -> None: ...

class MonteCarlo:
    def __init__(self, samples: int, dimensions: int) -> None: ...

class Sampler:
    def dimensions(self) -> int: ...
    def sample_count(self) -> int: ...
    def generate(self, master_seed: int) -> list[list[float]]: ...
    @staticmethod
    def MonteCarlo(a0: MonteCarlo) -> Sampler: ...
    @staticmethod
    def LatinHypercube(a0: LatinHypercube) -> Sampler: ...
    @staticmethod
    def Grid(a0: GridSampler) -> Sampler: ...
    def variant(self) -> str: ...

class CorrelationKind:
    def correlation(self, x: list[float], y: list[float]) -> float: ...
    @staticmethod
    def Pearson() -> CorrelationKind: ...
    @staticmethod
    def Spearman() -> CorrelationKind: ...
    def variant(self) -> str: ...

class SobolIndices:
    first_order: list[float]
    total_effect: list[float]
    mean: float
    total_variance: float
    layout: SobolSampleLayout
    def __init__(self, first_order: list[float], total_effect: list[float], mean: float, total_variance: float, layout: SobolSampleLayout) -> None: ...

class SobolSampleLayout:
    def __init__(self, inputs: int, base_samples: int) -> None: ...
    def inputs(self) -> int: ...
    def base_samples(self) -> int: ...
    def model_evaluations(self) -> int: ...
    def build_design(self, a: list[float], b: list[float]) -> list[float]: ...

def stream_seed(master_seed: int, stream: int) -> int: ...
def average_ranks(x: list[float]) -> list[float]: ...
def input_output_correlations(inputs_row_major: list[float], inputs: int, outputs: list[float], kind: CorrelationKind) -> list[float]: ...
def pearson_correlation(x: list[float], y: list[float]) -> float: ...
def sample_mean(x: list[float]) -> float: ...
def sample_variance(x: list[float]) -> float: ...
def sobol_indices(layout: SobolSampleLayout, outputs: list[float]) -> SobolIndices: ...
def spearman_correlation(x: list[float], y: list[float]) -> float: ...
