"""Type stubs for `outram_park.tampines_steam_tables`, generated from the Rust API.

Physical quantities cross this boundary as `float` in SI base units.
"""

class AdvectionTerminalState:
    @staticmethod
    def ZeroGradientExtrapolated() -> AdvectionTerminalState: ...
    @staticmethod
    def Junction(a0: float) -> AdvectionTerminalState: ...
    def variant(self) -> str: ...
    @staticmethod
    def default() -> AdvectionTerminalState: ...

class SolverMode:
    @staticmethod
    def Pimple() -> SolverMode: ...
    @staticmethod
    def HybridAllMach() -> SolverMode: ...
    def variant(self) -> str: ...
    @staticmethod
    def default() -> SolverMode: ...

class TampinesSteamArray:
    delta_t: float
    n_outer_correctors: int
    n_inner_correctors: int
    p_under_relaxation: float
    u_under_relaxation: float
    p_min: float
    p_max: float
    mode: SolverMode
    ma_blend_lo: float
    ma_blend_hi: float
    xs_area: float
    wetted_perimeter: float
    incline_angle: float
    mass_flowrate: float
    inlet_mass_flowrate: float | None
    inlet_terminal: AdvectionTerminalState
    outlet_terminal: AdvectionTerminalState
    pressure_loss: float
    internal_pressure_source: float
    lateral_adjacent_array_temperature_vector: list[list[float]]
    lateral_adjacent_array_conductance_vector: list[list[float]]
    q_vector: list[float]
    q_fraction_vector: list[list[float]]
    def lateral_link_new_temperature_vector_avg_conductance(self, average_thermal_conductance: float, temperature_vec: list[float]) -> None: ...
    def lateral_link_new_power_vector(self, power_source: float, q_fraction_vec: list[float]) -> None: ...
    def clear_vectors(self) -> None: ...
    def get_hydraulic_diameter(self) -> float: ...
    def get_temperature_vector(self) -> list[float]: ...
    def set_temperature_vector(self, temperature_vec: list[float]) -> None: ...
    def set_uniform_velocity_field(self, velocity: float) -> None: ...
    def set_inlet_velocity(self, velocity: float) -> None: ...
    def clear_inlet_mass_flowrate(self) -> None: ...
    def set_inlet_enthalpy(self, h: float) -> None: ...
    def clear_inlet_enthalpy(self) -> None: ...
    def set_outlet_enthalpy(self, h: float) -> None: ...
    def clear_outlet_enthalpy(self) -> None: ...
    def set_outlet_velocity(self, velocity: float) -> None: ...
    def set_outlet_pressure(self, p: float) -> None: ...
    def get_outlet_pressure(self) -> float: ...
    def get_outlet_enthalpy(self) -> float: ...
    def get_outlet_temperature(self) -> float: ...
    def __init__(self, length: float, xs_area: float, number_of_cells: int, delta_t: float) -> None: ...
    def correct_thermo(self) -> None: ...
    def axial_peclet_numbers(self) -> list[float]: ...
    def peak_axial_conduction_rate(self) -> float: ...
    def advance_timestep(self, timestep: float) -> None: ...
    def step(self) -> None: ...
    def run(self, n_steps: int) -> None: ...
    def get_pressure_under_relaxation(self) -> float: ...
    def set_pressure_under_relaxation(self, alpha: float) -> None: ...
    def get_velocity_under_relaxation(self) -> float: ...
    def set_velocity_under_relaxation(self, alpha: float) -> None: ...
    def set_piso_algorithm(self, n_correctors: int) -> None: ...
    def set_simple_algorithm(self, n_outer_iterations: int) -> None: ...
    def set_pimple_algorithm(self, n_outer_correctors: int, n_inner_correctors: int, pressure_under_relaxation: float, velocity_under_relaxation: float) -> None: ...
    def get_pressure_bounds(self) -> tuple[float, float]: ...
    def set_pressure_bounds(self, p_min: float, p_max: float) -> None: ...
    def get_solver_mode(self) -> SolverMode: ...
    def set_solver_mode(self, mode: SolverMode) -> None: ...
    def get_mach_blend_window(self) -> tuple[float, float]: ...
    def set_mach_blend_window(self, lo: float, hi: float) -> None: ...

class TampinesSteamArrayError:
    @staticmethod
    def InvalidTimestep(seconds: float) -> TampinesSteamArrayError: ...
    def variant(self) -> str: ...

class RhoHFitPiece:
    @staticmethod
    def R1_0() -> RhoHFitPiece: ...
    @staticmethod
    def R1_1() -> RhoHFitPiece: ...
    @staticmethod
    def R1_2() -> RhoHFitPiece: ...
    @staticmethod
    def R2_0() -> RhoHFitPiece: ...
    @staticmethod
    def R2_1() -> RhoHFitPiece: ...
    @staticmethod
    def R2_2() -> RhoHFitPiece: ...
    @staticmethod
    def R2_3() -> RhoHFitPiece: ...
    @staticmethod
    def R2_4() -> RhoHFitPiece: ...
    @staticmethod
    def R2_5() -> RhoHFitPiece: ...
    @staticmethod
    def R3_0() -> RhoHFitPiece: ...
    @staticmethod
    def R3_1() -> RhoHFitPiece: ...
    @staticmethod
    def R3_2() -> RhoHFitPiece: ...
    @staticmethod
    def R4_0() -> RhoHFitPiece: ...
    @staticmethod
    def R4_1() -> RhoHFitPiece: ...
    @staticmethod
    def R4_2() -> RhoHFitPiece: ...
    @staticmethod
    def R4_3() -> RhoHFitPiece: ...
    @staticmethod
    def R4_4() -> RhoHFitPiece: ...
    @staticmethod
    def R4_5() -> RhoHFitPiece: ...
    @staticmethod
    def R4_6() -> RhoHFitPiece: ...
    @staticmethod
    def R4_7() -> RhoHFitPiece: ...
    @staticmethod
    def R4_8() -> RhoHFitPiece: ...
    @staticmethod
    def R4_9() -> RhoHFitPiece: ...
    @staticmethod
    def R4_10() -> RhoHFitPiece: ...
    @staticmethod
    def R5() -> RhoHFitPiece: ...
    def variant(self) -> str: ...

class RhoHRegion:
    @staticmethod
    def Region1() -> RhoHRegion: ...
    @staticmethod
    def Region2() -> RhoHRegion: ...
    @staticmethod
    def Region3() -> RhoHRegion: ...
    @staticmethod
    def Region4() -> RhoHRegion: ...
    @staticmethod
    def Region5() -> RhoHRegion: ...
    def variant(self) -> str: ...

class CvMassEnthalpyChanges:
    def __init__(self, ) -> None: ...
    def add_mass(self, mass: float, specific_enthalpy: float) -> None: ...
    def remove_mass(self, mass: float, specific_enthalpy: float) -> None: ...
    def clear(self) -> None: ...
    def is_empty(self) -> bool: ...
    def len(self) -> int: ...
    def total_mass_change(self) -> float: ...
    def total_enthalpy_change(self) -> float: ...
    @staticmethod
    def default() -> CvMassEnthalpyChanges: ...

class TampinesSteamTableCV:
    def advance_timestep(self, changes: CvMassEnthalpyChanges) -> None: ...
    def set_tpx(self, t: float, p: float, x: float) -> None: ...
    def set_ph(self, p: float, h: float) -> None: ...
    def set_ps(self, p: float, s: float) -> None: ...
    def compress_isentropically(self, new_p: float) -> None: ...
    def expand_isentropically(self, new_p: float) -> None: ...
    def add_heat_isobaric(self, heat_added_per_kg: float) -> None: ...
    def remove_heat_isobaric(self, heat_removed_per_kg: float) -> None: ...
    def add_heat_isobaric_extensive(self, total_heat_added: float) -> None: ...
    def remove_heat_isobaric_extensive(self, total_heat_removed: float) -> None: ...
    def compress_with_work_extensive(self, total_work_input: float, outlet_pressure: float) -> None: ...
    def expand_with_work_extensive(self, total_work_output: float, outlet_pressure: float) -> None: ...
    def get_pressure(self) -> float: ...
    def get_temperature(self) -> float: ...
    def get_specific_volume(self) -> float: ...
    def get_specific_enthalpy(self) -> float: ...
    def get_specific_entropy(self) -> float: ...
    def get_volume(self) -> float: ...
    def get_mass(self) -> float: ...
    def get_viscosity(self) -> float: ...
    def get_speed_of_sound(self) -> float: ...
    def get_mach_number(self, v: float) -> float: ...
    def get_specific_heat_ratio(self) -> float: ...
    def get_cp(self) -> float: ...
    def get_cv(self) -> float: ...
    def get_thermal_conductivity(self) -> float: ...
    def get_critical_pressure_ratio_ideal_gas(self) -> float: ...
    def get_critical_pressure_ratio_pure_vapour(self) -> float: ...
    def get_crit_pressure_and_massflux(self) -> tuple[float, float]: ...
    def get_critical_pressure_vle(self) -> float: ...
    def get_critical_pressure_pure_vapour(self) -> float: ...
    def get_rho(self) -> float: ...
    def get_region(self) -> FwdEqnRegion: ...
    def get_metastable_steam_specific_volume(self) -> float | None: ...
    def get_metastable_steam_specific_enthalpy(self) -> float | None: ...
    def get_metastable_steam_internal_energy(self) -> float | None: ...
    def get_metastable_steam_specific_entropy(self) -> float | None: ...
    def get_metastable_steam_cp(self) -> float | None: ...
    def get_metastable_steam_cv(self) -> float | None: ...
    def get_metastable_steam_speed_of_sound(self) -> float | None: ...
    def get_quality(self) -> float: ...
    def try_new_tsat_based_on_pressure(self) -> float | None: ...
    def try_new_psat_based_on_temperature(self) -> float | None: ...
    @staticmethod
    def try_get_tsat(p: float) -> float | None: ...
    @staticmethod
    def try_get_psat(t: float) -> float | None: ...
    @staticmethod
    def get_ref_vol() -> float: ...
    def get_stagnation_critical_mass_flux(self) -> float: ...
    @staticmethod
    def new_from_tp_quality(temperature: float, pressure: float, volume: float, x: float) -> TampinesSteamTableCV: ...
    @staticmethod
    def new_from_tp_quality_1(temperature: float, pressure: float, volume: float) -> TampinesSteamTableCV: ...
    @staticmethod
    def new_from_tp_quality_0(temperature: float, pressure: float, volume: float) -> TampinesSteamTableCV: ...
    @staticmethod
    def new_from_ph(p: float, h: float, volume: float) -> TampinesSteamTableCV: ...
    @staticmethod
    def new_from_ps(p: float, s: float, volume: float) -> TampinesSteamTableCV: ...
    @staticmethod
    def new_from_hs(h: float, s: float, volume: float) -> TampinesSteamTableCV: ...
    @staticmethod
    def new_from_sat_pressure_quality(p: float, x: float, volume: float) -> TampinesSteamTableCV: ...
    @staticmethod
    def new_from_sat_temp_quality(t: float, x: float, volume: float) -> TampinesSteamTableCV: ...

class SteamTablesError:
    @staticmethod
    def SaturatedTpUnderdetermined(t_kelvin: float, p_pascal: float) -> SteamTablesError: ...
    @staticmethod
    def QualityOutOfRange(x: float) -> SteamTablesError: ...
    def variant(self) -> str: ...

class BackwdEqnSubRegion:
    @staticmethod
    def Region1() -> BackwdEqnSubRegion: ...
    @staticmethod
    def Region2a() -> BackwdEqnSubRegion: ...
    @staticmethod
    def Region2b() -> BackwdEqnSubRegion: ...
    @staticmethod
    def Region2c() -> BackwdEqnSubRegion: ...
    @staticmethod
    def Region3a() -> BackwdEqnSubRegion: ...
    @staticmethod
    def Region3b() -> BackwdEqnSubRegion: ...
    @staticmethod
    def Region4() -> BackwdEqnSubRegion: ...
    @staticmethod
    def Region5() -> BackwdEqnSubRegion: ...
    def variant(self) -> str: ...

class FwdEqnRegion:
    @staticmethod
    def Region1() -> FwdEqnRegion: ...
    @staticmethod
    def Region2() -> FwdEqnRegion: ...
    @staticmethod
    def Region3() -> FwdEqnRegion: ...
    @staticmethod
    def Region4() -> FwdEqnRegion: ...
    @staticmethod
    def Region5() -> FwdEqnRegion: ...
    def variant(self) -> str: ...

class ThreePhaseElectricGeneratorTurbine:
    @staticmethod
    def new_250_megawatt_generator() -> ThreePhaseElectricGeneratorTurbine: ...
    def __init__(self, B: float, A: float, N: int, I: float, eta: float, omega: float) -> None: ...
    def calculate_new_angular_velocity(self, source: float, load_resistance: float, current_time: float, delta_t: float) -> float: ...
    def advance_timestep(self, torque_source: float, load_resistance: float, current_time: float, delta_t: float) -> None: ...
    def set_magnetic_field(self, B: float) -> None: ...
    def get_emf_1(self, t: float) -> float: ...
    def get_emf_2(self, t: float) -> float: ...
    def get_emf_3(self, t: float) -> float: ...
    def get_power(self, load_resistance: float, t: float) -> float: ...
    def get_current_1(self, load_resistance: float, t: float) -> float: ...
    def get_current_2(self, load_resistance: float, t: float) -> float: ...
    def get_current_3(self, load_resistance: float, t: float) -> float: ...
    def set_omega(self, omega: float) -> None: ...
    def get_omega(self) -> float: ...

class TabulatedData:
    def isobar(self, p: float, tolerance_relative: float) -> list[TabulatedState]: ...
    def isobar_default_tolerance(self, p: float) -> list[TabulatedState]: ...
    def isotherm(self, t: float, tolerance_kelvin: float) -> list[TabulatedState]: ...
    def isotherm_default_tolerance(self, t: float) -> list[TabulatedState]: ...
    def cross_section(self, quantity: TabulatedQuantity) -> list[TabulatedState]: ...
    def saturation_curve(self) -> list[TabulatedSaturationState]: ...
    def __init__(self) -> None: ...
    @staticmethod
    def default() -> TabulatedData: ...

class TabulatedQuantity:
    @staticmethod
    def Isobar(a0: float) -> TabulatedQuantity: ...
    @staticmethod
    def Isotherm(a0: float) -> TabulatedQuantity: ...
    def variant(self) -> str: ...

class TabulatedSaturationState:
    temperature: float
    pressure: float
    liquid_enthalpy: float
    vapour_enthalpy: float
    liquid_entropy: float
    vapour_entropy: float
    def __init__(self, temperature: float, pressure: float, liquid_enthalpy: float, vapour_enthalpy: float, liquid_entropy: float, vapour_entropy: float) -> None: ...

class TabulatedState:
    pressure: float
    temperature: float
    specific_enthalpy: float
    specific_entropy: float
    def __init__(self, pressure: float, temperature: float, specific_enthalpy: float, specific_entropy: float) -> None: ...

def fit_piece_for_region(region: RhoHRegion, rho_kg_m3: float, h_kj_kg: float) -> RhoHFitPiece: ...
def p_rho_h_classified(rho: float, h: float) -> float: ...
def p_rho_h_in_region(region: RhoHRegion, rho: float, h: float) -> float: ...
def p_rho_h_in_region_explicit(region: RhoHRegion, rho_kg_m3: float, h_kj_kg: float) -> float: ...
def p_rho_h_piece_explicit(piece: RhoHFitPiece, rho_kg_m3: float, h_kj_kg: float) -> float: ...
def region_1_piece_from_h(h_kj_kg: float) -> RhoHFitPiece: ...
def region_2_piece_from_rho(rho_kg_m3: float) -> RhoHFitPiece: ...
def region_3_piece_from_rho(rho_kg_m3: float) -> RhoHFitPiece: ...
def region_4_piece_from_rho(rho_kg_m3: float) -> RhoHFitPiece: ...
def rho_h_region_candidate(rho_kg_m3: float, h_kj_kg: float) -> RhoHRegion: ...
def rho_h_region_scores(rho_kg_m3: float, h_kj_kg: float) -> list[float]: ...
def h_f_near_critical_explicit(t_kelvin: float) -> float: ...
def h_g_near_critical_explicit(t_kelvin: float) -> float: ...
def p_hs_4_near_critical(h: float, s: float) -> float: ...
def p_hs_4_near_critical_explicit(h_kj_kg: float, s_kj_kg_k: float) -> float: ...
def x_hs_4_near_critical(h: float, s: float) -> float: ...
def x_hs_4_near_critical_explicit(h_kj_kg: float, s_kj_kg_k: float) -> float: ...
def t_ph_5(p: float, h: float) -> float: ...
def t_ph_5_explicit(p_mpa: float, h_kj_kg: float) -> float: ...
def t_ps_5(p: float, s: float) -> float: ...
def t_ps_5_explicit(p_mpa: float, s_kj_kg_k: float) -> float: ...
def hb13_s_boundary_enthalpy(s: float) -> float: ...
def tb23_s_boundary_enthalpy(s: float, h: float) -> float: ...
def h1_prime_s_boundary_enthalpy(s: float) -> float: ...
def h3a_prime_s_boundary_enthalpy(s: float) -> float: ...
def h2ab_double_prime_s_boundary_enthalpy(s: float) -> float: ...
def h2c3b_prime_s_boundary_enthalpy(s: float) -> float: ...
def p_s3_h(h: float) -> float: ...
def p_s3_s(s: float) -> float: ...
def boltzmann_constant_k() -> float: ...
def molecular_dipole_moment_mu() -> float: ...
def p_crit_water() -> float: ...
def permittivity_of_vacuum_eps_0() -> float: ...
def rho_crit_water() -> float: ...
def s_crit_water() -> float: ...
def specific_gas_constant_of_water() -> float: ...
def t_crit_water() -> float: ...
def water_dielectric_const_rho_t(rho: float, t: float) -> float: ...
def mu_ph_eqm(p: float, h: float) -> float: ...
def mu_rho_t_eqm(t: float, rho: float) -> float: ...
def mu_tp_eqm_single_phase(t: float, p: float) -> float: ...
def mu_tp_eqm_two_phase(t: float, p: float, x: float) -> float: ...
def cp_hs_eqm(h: float, s: float) -> float: ...
def find_pressure_from_hs_region_4(h_target: float, s_target: float) -> float: ...
def hs_flash_region(h: float, s: float) -> BackwdEqnSubRegion: ...
def kappa_hs_eqm(h: float, s: float) -> float: ...
def lambda_hs_eqm(h: float, s: float) -> float: ...
def mu_hs_eqm(h: float, s: float) -> float: ...
def p_hs_eqm(h: float, s: float) -> float: ...
def t_hs_eqm(h: float, s: float) -> float: ...
def tpvx_hs_flash_eqm(h: float, s: float) -> tuple[float, float, float, float]: ...
def v_hs_eqm(h: float, s: float) -> float: ...
def hs_is_above_isotherm_t_273_15_kelvin(h: float, s: float) -> bool: ...
def hs_is_below_isobar_p_100_mpa_in_region1(h: float, s: float) -> bool: ...
def w_hs_eqm(h: float, s: float) -> float: ...
def x_hs_eqm(h: float, s: float) -> float: ...
def alpha_v_ph_eqm(p: float, h: float) -> float: ...
def cp_ph_eqm(p: float, h: float) -> float: ...
def cv_ph_eqm(p: float, h: float) -> float: ...
def kappa_ph_eqm(p: float, h: float) -> float: ...
def lambda_ph_eqm(p: float, h: float) -> float: ...
def ph_flash_region(p: float, h: float) -> FwdEqnRegion: ...
def s_ph_eqm(p: float, h: float) -> float: ...
def t_ph_eqm(p: float, h: float) -> float: ...
def u_ph_eqm(p: float, h: float) -> float: ...
def v_ph_eqm(p: float, h: float) -> float: ...
def w_ph_wood_wallis(p: float, h: float) -> float: ...
def w_two_phase_homogeneous_wood_wallis(steam_quality: float, w_liq: float, w_vap: float, rho_liq: float, rho_vap: float) -> float: ...
def x_ph_flash(p: float, h: float) -> float: ...
def alpha_v_ps_eqm(p: float, s: float) -> float: ...
def cp_ps_eqm(p: float, s: float) -> float: ...
def cv_ps_eqm(p: float, s: float) -> float: ...
def h_ps_eqm(p: float, s: float) -> float: ...
def kappa_ps_eqm(p: float, s: float) -> float: ...
def mass_flux_ps_eqm_throat(p: float, s: float) -> float: ...
def ps_flash_region(p: float, s: float) -> FwdEqnRegion: ...
def t_ps_eqm(p: float, s: float) -> float: ...
def u_ps_eqm(p: float, s: float) -> float: ...
def v_ps_eqm(p: float, s: float) -> float: ...
def w_ps_wood_wallis(p: float, s: float) -> float: ...
def x_ps_flash(p: float, s: float) -> float: ...
def alpha_v_tp_eqm_single_phase(t: float, p: float) -> float: ...
def cp_tp_eqm_single_phase(t: float, p: float) -> float: ...
def cv_tp_eqm_single_phase(t: float, p: float) -> float: ...
def h_tp_eqm_single_phase(t: float, p: float) -> float: ...
def kappa_tp_eqm_single_phase(t: float, p: float) -> float: ...
def alpha_v_tp_eqm_two_phase(t: float, p: float, x: float) -> float: ...
def cp_tp_eqm_two_phase(t: float, p: float, x: float) -> float: ...
def cv_tp_eqm_two_phase(t: float, p: float, x: float) -> float: ...
def h_tp_eqm_two_phase(t: float, p: float, x: float) -> float: ...
def kappa_tp_eqm_two_phase(t: float, p: float, x: float) -> float: ...
def region_fwd_eqn_two_phase(t: float, p: float, steam_quality: float) -> FwdEqnRegion: ...
def s_tp_eqm_two_phase(t: float, p: float, x: float) -> float: ...
def u_tp_eqm_two_phase(t: float, p: float, x: float) -> float: ...
def v_tp_eqm_two_phase(t: float, p: float, x: float) -> float: ...
def w_tp_eqm_two_phase(t: float, p: float, x: float) -> float: ...
def region_fwd_eqn_single_phase(t: float, p: float) -> FwdEqnRegion: ...
def s_tp_eqm_single_phase(t: float, p: float) -> float: ...
def u_tp_eqm_single_phase(t: float, p: float) -> float: ...
def v_tp_eqm_single_phase(t: float, p: float) -> float: ...
def w_tp_eqm_single_phase(t: float, p: float) -> float: ...
def w_tpx_eqm(t: float, p: float, x: float) -> float: ...
def get_choked_flow_massrate_and_state_from_stagnation_properties_and_area(p0: float, h0: float, a_throat: float) -> tuple[float, TampinesSteamTableCV]: ...
def p_hs_1(h: float, s: float) -> float: ...
def eta_1_back(h: float) -> float: ...
def pi_1_back(p: float) -> float: ...
def t_ph_1(p: float, h: float) -> float: ...
def theta_ph_1(p: float, h: float) -> float: ...
def t_ps_1(p: float, s: float) -> float: ...
def gamma_pi_1(t: float, p: float) -> float: ...
def gamma_pi_pi_1(t: float, p: float) -> float: ...
def gamma_pi_tau_1(t: float, p: float) -> float: ...
def gamma_tau_1(t: float, p: float) -> float: ...
def gamma_tau_tau_1(t: float, p: float) -> float: ...
def gamma_1(t: float, p: float) -> float: ...
def alpha_v_tp_1(t: float, p: float) -> float: ...
def cp_tp_1(t: float, p: float) -> float: ...
def cv_tp_1(t: float, p: float) -> float: ...
def h_tp_1(t: float, p: float) -> float: ...
def kappa_tp_1(t: float, p: float) -> float: ...
def s_tp_1(t: float, p: float) -> float: ...
def u_tp_1(t: float, p: float) -> float: ...
def v_tp_1(t: float, p: float) -> float: ...
def w_tp_1(t: float, p: float) -> float: ...
def pi_1(p: float) -> float: ...
def tau_1(t: float) -> float: ...
def h_2a2b(s: float) -> float: ...
def p_hs_2(h: float, s: float) -> float: ...
def h_2b2c(p: float) -> float: ...
def p_2b2c(h: float) -> float: ...
def t_ph_2(p: float, h: float) -> float: ...
def t_ph_2a(pi: float, eta: float) -> float: ...
def t_ph_2b(pi: float, eta: float) -> float: ...
def t_ph_2c(pi: float, eta: float) -> float: ...
def t_ps_2(p: float, s: float) -> float: ...
def pi_2(p: float) -> float: ...
def tau_2(t: float) -> float: ...
def gamma_2_ideal(t: float, p: float) -> float: ...
def gamma_pi_2_ideal(_t: float, p: float) -> float: ...
def gamma_tau_2_ideal(t: float, _p: float) -> float: ...
def gamma_tau_tau_2_ideal(t: float, _p: float) -> float: ...
def gamma_2_res(t: float, p: float) -> float: ...
def gamma_pi_2_res(t: float, p: float) -> float: ...
def gamma_pi_pi_2_res(t: float, p: float) -> float: ...
def gamma_pi_tau_2_res(t: float, p: float) -> float: ...
def gamma_tau_2_res(t: float, p: float) -> float: ...
def gamma_tau_tau_2_res(t: float, p: float) -> float: ...
def alpha_v_tp_2(t: float, p: float) -> float: ...
def cp_tp_2(t: float, p: float) -> float: ...
def cv_tp_2(t: float, p: float) -> float: ...
def h_tp_2(t: float, p: float) -> float: ...
def kappa_tp_2(t: float, p: float) -> float: ...
def s_tp_2(t: float, p: float) -> float: ...
def u_tp_2(t: float, p: float) -> float: ...
def v_tp_2(t: float, p: float) -> float: ...
def w_tp_2(t: float, p: float) -> float: ...
def alpha_v_tp_2_metastable(t: float, p: float) -> float: ...
def cp_tp_2_metastable(t: float, p: float) -> float: ...
def cv_tp_2_metastable(t: float, p: float) -> float: ...
def h_tp_2_metastable(t: float, p: float) -> float: ...
def kappa_tp_2_metastable(t: float, p: float) -> float: ...
def s_tp_2_metastable(t: float, p: float) -> float: ...
def u_tp_2_metastable(t: float, p: float) -> float: ...
def v_tp_2_metastable(t: float, p: float) -> float: ...
def w_tp_2_metastable(t: float, p: float) -> float: ...
def gamma_metastable_2_ideal(t: float, p: float) -> float: ...
def gamma_metastable_pi_2_ideal(_t: float, p: float) -> float: ...
def gamma_metastable_tau_2_ideal(t: float, _p: float) -> float: ...
def gamma_metastable_tau_tau_2_ideal(t: float, _p: float) -> float: ...
def gamma_metastable_2_res(t: float, p: float) -> float: ...
def gamma_metastable_pi_2_res(t: float, p: float) -> float: ...
def gamma_metastable_pi_pi_2_res(t: float, p: float) -> float: ...
def gamma_metastable_pi_tau_2_res(t: float, p: float) -> float: ...
def gamma_metastable_tau_2_res(t: float, p: float) -> float: ...
def gamma_metastable_tau_tau_2_res(t: float, p: float) -> float: ...
def p_boundary_2_3(t: float) -> float: ...
def t_boundary_2_3(p: float) -> float: ...
def p_hs_3(h: float, s: float) -> float: ...
def h_3a3b_backwards_ph_boundary(p: float) -> float: ...
def t_ph_3(p: float, h: float) -> float: ...
def t_ph_3a(p: float, h: float) -> float: ...
def t_ph_3b(p: float, h: float) -> float: ...
def v_ph_3(p: float, h: float) -> float: ...
def v_ph_3a(p: float, h: float) -> float: ...
def v_ph_3b(p: float, h: float) -> float: ...
def s_3a3b_backwards_ps_boundary() -> float: ...
def t_ps_3(p: float, s: float) -> float: ...
def v_ps_3(p: float, s: float) -> float: ...
def alpha_v_tp_3(t: float, p: float) -> float: ...
def cp_tp_3(t: float, p: float) -> float: ...
def cv_tp_3(t: float, p: float) -> float: ...
def h_tp_3(t: float, p: float) -> float: ...
def kappa_tp_3(t: float, p: float) -> float: ...
def s_tp_3(t: float, p: float) -> float: ...
def u_tp_3(t: float, p: float) -> float: ...
def w_tp_3(t: float, p: float) -> float: ...
def v_tp_3(t: float, p: float) -> float: ...
def v_tp_3c(t: float, p: float) -> float: ...
def v_tp_3r(t: float, p: float) -> float: ...
def v_tp_3s(t: float, p: float) -> float: ...
def v_tp_3t(t: float, p: float) -> float: ...
def v_tp_3u(t: float, p: float) -> float: ...
def v_tp_3x(t: float, p: float) -> float: ...
def v_tp_3y(t: float, p: float) -> float: ...
def v_tp_3z(t: float, p: float) -> float: ...
def delta_3(rho: float) -> float: ...
def tau_3(t: float) -> float: ...
def alpha_p_rho_t_3(rho: float, t: float) -> float: ...
def alpha_v_rho_t_3(rho: float, t: float) -> float: ...
def beta_p_rho_t_3(rho: float, t: float) -> float: ...
def cp_rho_t_3(rho: float, t: float) -> float: ...
def cv_rho_t_3(rho: float, t: float) -> float: ...
def h_rho_t_3(rho: float, t: float) -> float: ...
def kappa_rho_t_3(rho: float, t: float) -> float: ...
def p_rho_t_3(rho: float, t: float) -> float: ...
def s_rho_t_3(rho: float, t: float) -> float: ...
def u_rho_t_3(rho: float, t: float) -> float: ...
def w_rho_t_3(rho: float, t: float) -> float: ...
def phi_delta_3(rho: float, t: float) -> float: ...
def phi_delta_delta_3(rho: float, t: float) -> float: ...
def phi_delta_tau_3(rho: float, t: float) -> float: ...
def phi_tau_3(rho: float, t: float) -> float: ...
def phi_tau_tau_3(rho: float, t: float) -> float: ...
def phi_3(rho: float, t: float) -> float: ...
def tsat_hs_4(h: float, s: float) -> float: ...
def beta_dimensionless_pressure_4(p: float) -> float: ...
def sat_pressure_4(t: float) -> float: ...
def sat_temp_4(p: float) -> float: ...
def w_ps_eqm_region4_finite_diff_vol(p: float, s: float) -> float: ...
def w_ps_eqm_region4_kieffer(p: float, s: float) -> float: ...
def theta_dimensionless_temp_4(t: float) -> float: ...
def pi_5(p: float) -> float: ...
def tau_5(t: float) -> float: ...
def gamma_5_ideal(t: float, p: float) -> float: ...
def gamma_pi_5_ideal(_t: float, p: float) -> float: ...
def gamma_tau_5_ideal(t: float, _p: float) -> float: ...
def gamma_tau_tau_5_ideal(t: float, _p: float) -> float: ...
def gamma_5_res(t: float, p: float) -> float: ...
def gamma_pi_5_res(t: float, p: float) -> float: ...
def gamma_pi_pi_5_res(t: float, p: float) -> float: ...
def gamma_pi_tau_5_res(t: float, p: float) -> float: ...
def gamma_tau_5_res(t: float, p: float) -> float: ...
def gamma_tau_tau_5_res(t: float, p: float) -> float: ...
def alpha_v_tp_5(t: float, p: float) -> float: ...
def cp_tp_5(t: float, p: float) -> float: ...
def cv_tp_5(t: float, p: float) -> float: ...
def h_tp_5(t: float, p: float) -> float: ...
def kappa_tp_5(t: float, p: float) -> float: ...
def s_tp_5(t: float, p: float) -> float: ...
def u_tp_5(t: float, p: float) -> float: ...
def v_tp_5(t: float, p: float) -> float: ...
def w_tp_5(t: float, p: float) -> float: ...
def calculate_velocity_mass_flowrate_and_state_in_cd_nozzle(p1: float, h1: float, v1: float, a_throat: float, a2: float, p2: float) -> tuple[float, float, TampinesSteamTableCV]: ...
def bubble_point_pressure_from_entropy(s0: float) -> float: ...
def bubble_point_pressure_ph(p0: float, h0: float) -> float: ...
def dew_point_pressure_from_entropy(s0: float) -> float: ...
def dew_point_pressure_ph(p0: float, h0: float) -> float: ...
def get_stagnation_conditions_from_throat_ph(p_t: float, h_t: float) -> tuple[float, float, float]: ...
def get_stagnation_conditions_from_throat_ps(p_t: float, s_t: float) -> tuple[float, float, float]: ...
def g_max_hem_analytical_ph(p: float, h: float) -> float: ...
def g_max_hem_analytical_ps(p: float, s: float) -> float: ...
def get_critical_pressure_and_mass_flux_multiphase_ph(p0: float, h0: float) -> tuple[float, float]: ...
def get_critical_pressure_and_mass_flux_with_stagnation_props(s0: float, h0: float, p0: float) -> tuple[float, float]: ...
def isentropic_pressure_scan_of_mass_flux(s0: float, p0: float) -> None: ...
def get_choked_flow_nozzle_area(p0: float, h0: float, mass_flowrate: float) -> float: ...
def get_choked_flow_state_for_nozzle_subsonic_to_sonic(p1: float, h1: float, a1: float, a2: float, v1: float) -> tuple[float, float, float]: ...
def get_choked_flow_supersonic_nozzle_exit_area_and_state(p_throat: float, h_throat: float, p_exit: float, mass_flowrate: float) -> tuple[float, float, float]: ...
def get_critical_pressure_pure_vapour_ph_stagnation_properties(p0: float, h0: float, s0_opt: float | None) -> float: ...
def get_critical_pressure_ratio_ideal_gas_using_throat_ph(p: float, h: float) -> float: ...
def get_critical_pressure_and_mass_flux_subcooled_liquid_ph(p0: float, h0: float) -> tuple[float, float]: ...
def get_critical_pressure_and_mass_flux_superheated_vapour_ph(p0: float, h0: float) -> tuple[float, float]: ...
def get_critical_pressure_and_mass_flux_ph_vle_dome(p0: float, h0: float) -> tuple[float, float]: ...
def calculate_isentropic_exit_pressure_velocity_and_state_subsonic(inlet_stagnation_state: TampinesSteamTableCV, a_exit: float, mass_flowrate_choked: float) -> tuple[float, float, TampinesSteamTableCV]: ...
def calculate_isentropic_exit_pressure_velocity_and_state_supersonic(inlet_stagnation_state: TampinesSteamTableCV, a_exit: float, mass_flowrate_choked: float) -> tuple[float, float, TampinesSteamTableCV]: ...
def guess_velocity_and_state_for_diverge_nozzle_from_choked_throat(h0: float, s0: float, p2: float, a_exit: float, mass_rate_throat: float, state_throat: TampinesSteamTableCV) -> tuple[float, TampinesSteamTableCV]: ...
def guess_massrate_and_state_for_converge_nozzle_from_stagnation(p0: float, h0: float, v_throat: float, a_throat: float) -> tuple[float, TampinesSteamTableCV]: ...
def get_outlet_velocity_and_state_joule_thomson(p1: float, h1: float, p2: float, mass_flowrate_ref: float, a1: float) -> tuple[float, TampinesSteamTableCV]: ...
def water_surf_tension(t: float) -> float: ...
def lambda_tp_eqm_single_phase(t: float, p: float) -> float: ...
def lambda_tp_eqm_two_phase(t: float, p: float, x: float) -> float: ...
REGION_5_BACK_P_MAX_MPA: float
REGION_5_BACK_P_MIN_MPA: float
REGION_5_BACK_T_MAX_KELVIN: float
REGION_5_BACK_T_MIN_KELVIN: float
MOLAR_MASS_WATER_G_PER_GMOL: float
P_C_MPA: float
P_NORMAL_BP_MPA: float
P_TRIPLE_PT_PASCAL: float
RHO_C_KG_PER_M3: float
R_KJ_PER_KG_KELVIN: float
R_M_J_PER_MOL_KELVIN: float
S_C_KJ_PER_KG_K: float
T_C_KELVIN: float
T_NORMAL_BP_KELVIN: float
T_TRIPLE_PT_KELVIN: float
DEEP_SUBCOOLING_RATIO: float
DEFAULT_ISOBAR_TOLERANCE_RELATIVE: float
DEFAULT_ISOTHERM_TOLERANCE_KELVIN: float
SAT_COL_H_LIQ: int
SAT_COL_H_VAP: int
SAT_COL_P_BAR: int
SAT_COL_S_LIQ: int
SAT_COL_S_VAP: int
SAT_COL_T_DEGC: int
