"""Type stubs for `outram_park.tampines`, generated from the Rust API.

Physical quantities cross this boundary as `float` in SI base units.
"""

class TampinesError:
    @staticmethod
    def InvalidInput(a0: str) -> TampinesError: ...
    @staticmethod
    def Unphysical(a0: str) -> TampinesError: ...
    @staticmethod
    def Numerical(a0: str) -> TampinesError: ...
    def variant(self) -> str: ...

class TampinesFluid:
    @staticmethod
    def CoolProp(a0: outram_park_fork_coolprop.Fluid) -> TampinesFluid: ...
    @staticmethod
    def Steam() -> TampinesFluid: ...
    def variant(self) -> str: ...

class Condenser:
    pressure: float
    target_outlet_quality: float
    def __init__(self, pressure: float, target_outlet_quality: float) -> None: ...
    def condense(self, _inlet: tampines_steam_tables.TampinesSteamTableCV) -> tampines_steam_tables.TampinesSteamTableCV: ...

class HeatExchanger:
    arrangement: outram_park_fork_dwsim_libs.FlowArrangement
    area: float
    overall_coefficient: float
    def __init__(self, arrangement: outram_park_fork_dwsim_libs.FlowArrangement, area: float, overall_coefficient: float) -> None: ...
    def calculate(self, _t_hot_in: float, _t_cold_in: float) -> tuple[float, float, float]: ...

class Pump:
    specification: outram_park_fork_dwsim_libs.PumpSpecification
    efficiency: float
    def __init__(self, specification: outram_park_fork_dwsim_libs.PumpSpecification, efficiency: float) -> None: ...
    def evaluate(self, _inlet: outram_park_fork_dwsim_libs.PumpInlet) -> outram_park_fork_dwsim_libs.PumpResult: ...

class RankineCycle:
    steam_generator: SteamGenerator
    turbine: Turbine
    condenser: Condenser
    feedwater_pump: Pump
    def __init__(self, steam_generator: SteamGenerator, turbine: Turbine, condenser: Condenser, feedwater_pump: Pump) -> None: ...

class SteamGenerator:
    heat_exchanger: HeatExchanger
    secondary_side: tampines_steam_tables.TampinesSteamTableCV
    def __init__(self, heat_exchanger: HeatExchanger, secondary_side: tampines_steam_tables.TampinesSteamTableCV) -> None: ...
    def step(self, _primary_duty: float) -> None: ...

class Turbine:
    inlet: tampines_steam_tables.TampinesSteamTableCV
    adiabatic_efficiency: float
    def __init__(self, inlet: tampines_steam_tables.TampinesSteamTableCV, adiabatic_efficiency: float) -> None: ...
    def expand_to(self, _outlet_pressure: float) -> tampines_steam_tables.TampinesSteamTableCV: ...

class Valve:
    kv_max: outram_park_fork_dwsim_libs.ValveFlowCoefficient
    opening_characteristic: outram_park_fork_dwsim_libs.OpeningCharacteristic
    opening_percent: float
    def __init__(self, kv_max: outram_park_fork_dwsim_libs.ValveFlowCoefficient, opening_characteristic: outram_park_fork_dwsim_libs.OpeningCharacteristic, opening_percent: float) -> None: ...
    def current_kv(self) -> outram_park_fork_dwsim_libs.ValveFlowCoefficient: ...
    def mass_flow(self, _p1: float, _p2: float) -> float: ...

class CoolingTower:
    air_inlet: HumidAirState
    water_inlet_temperature: float
    water_flow_rate: float
    target_approach: float
    def __init__(self, air_inlet: HumidAirState, water_inlet_temperature: float, water_flow_rate: float, target_approach: float) -> None: ...
    def evaluate(self) -> tuple[float, HumidAirState]: ...

class Pipe:
    backend: PipeBackend
    diameter: float
    length: float
    roughness: float
    inclination: float
    two_phase_correlation: outram_park_fork_dwsim_libs.PipeFlowCorrelation
    def __init__(self, backend: PipeBackend, diameter: float, length: float, roughness: float, inclination: float) -> None: ...
    def step(self, dt: float) -> None: ...

class PipeBackend:
    @staticmethod
    def Lumped(a0: tuas_boussinesq_solver.FluidArray) -> PipeBackend: ...
    @staticmethod
    def Compressible(a0: outram_park_fork_coolprop.OPCPFluidArray) -> PipeBackend: ...
    @staticmethod
    def SteamHem(a0: tampines_steam_tables.TampinesSteamArray) -> PipeBackend: ...
    @staticmethod
    def InsulatedPipe(a0: tuas_boussinesq_solver.InsulatedFluidComponent) -> PipeBackend: ...
    def variant(self) -> str: ...

class Circulator:
    duty: CirculatorDuty
    isentropic_efficiency: float
    @staticmethod
    def new_fixed_pressure_rise(rise: float, isentropic_efficiency: float) -> Circulator: ...
    @staticmethod
    def new_fixed_pressure_ratio(ratio_pp: float, isentropic_efficiency: float) -> Circulator: ...
    def outlet_pressure(self, inlet_pressure: float) -> float: ...
    def compress_helium(self, mass_flow: float, inlet_temperature: float, inlet_pressure: float) -> CirculatorResult: ...
    def __init__(self, duty: CirculatorDuty, isentropic_efficiency: float) -> None: ...

class CirculatorDuty:
    @staticmethod
    def PressureRise(a0: float) -> CirculatorDuty: ...
    @staticmethod
    def PressureRatio(a0: float) -> CirculatorDuty: ...
    def variant(self) -> str: ...

class GasDuct:
    hydraulic_diameter: float
    flow_area: float
    wetted_perimeter: float
    length: float
    roughness: float
    heat_transfer: HeatTransferCorrelation
    @staticmethod
    def new_circular(diameter: float, length: float, roughness: float) -> GasDuct: ...
    def wall_area(self) -> float: ...
    def relative_roughness(self) -> float: ...
    def solve_helium(self, mass_flow: float, inlet_temperature: float, inlet_pressure: float, boundary: DuctThermalBoundary) -> GasDuctResult: ...
    def __init__(self, hydraulic_diameter: float, flow_area: float, wetted_perimeter: float, length: float, roughness: float, heat_transfer: HeatTransferCorrelation) -> None: ...

class GasDuctResult:
    inlet: HeliumState
    outlet: HeliumState
    pressure_drop: float
    friction_pressure_drop: float
    acceleration_pressure_drop: float
    reynolds: float
    prandtl: float
    darcy_friction_factor: float
    nusselt: float
    heat_transfer_coefficient: float
    heat_duty: float
    inlet_velocity: float
    outlet_velocity: float
    outlet_mach: float
    def heat_transfer_correlation_in_range(self, correlation: HeatTransferCorrelation) -> bool: ...

class HeatTransferCorrelation:
    @staticmethod
    def Gnielinski() -> HeatTransferCorrelation: ...
    @staticmethod
    def DittusBoelterHeating() -> HeatTransferCorrelation: ...
    @staticmethod
    def DittusBoelterCooling() -> HeatTransferCorrelation: ...
    def variant(self) -> str: ...
    @staticmethod
    def default() -> HeatTransferCorrelation: ...

class HeliumState:
    temperature: float
    pressure: float
    density: float
    dynamic_viscosity: float
    thermal_conductivity: float
    specific_heat_cp: float
    speed_of_sound: float
    def prandtl(self) -> float: ...
    def kinematic_viscosity_m2_per_s(self) -> float: ...

class KtaBed:
    porosity: float
    pebble_diameter: float
    cross_section: float
    def __init__(self, porosity: float, pebble_diameter: float, cross_section: float) -> None: ...
    @staticmethod
    def htr10() -> KtaBed: ...
    def free_flow_area(self) -> float: ...
    def pressure_gradient_detailed(self, mass_flow: float, density: float, dynamic_viscosity: float) -> KtaBedResult: ...
    def pressure_drop(self, mass_flow: float, density: float, dynamic_viscosity: float, bed_height: float) -> float: ...
    def pressure_drop_helium_marched(self, mass_flow: float, pressure: float, inlet_temperature: float, outlet_temperature: float, bed_height: float, n_slices: int) -> float: ...

class KtaBedResult:
    reynolds: float
    modified_reynolds: float
    friction_factor: float

class CirculatorResult:
    inlet: HeliumState
    outlet: HeliumState
    isentropic_outlet_temperature: float
    shaft_power: float
    temperature_rise_kelvin: float

class DuctThermalBoundary:
    @staticmethod
    def Adiabatic() -> DuctThermalBoundary: ...
    @staticmethod
    def HeatInput(a0: float) -> DuctThermalBoundary: ...
    @staticmethod
    def WallTemperature(a0: float) -> DuctThermalBoundary: ...
    def variant(self) -> str: ...

class HumidAirState:
    t_dry_bulb: float
    pressure: float
    water_mole_fraction: float
    humidity_ratio: float
    relative_humidity: float
    enthalpy: float
    entropy: float
    volume: float
    def __init__(self, t_dry_bulb: float, pressure: float, water_mole_fraction: float, humidity_ratio: float, relative_humidity: float, enthalpy: float, entropy: float, volume: float) -> None: ...

class DispersedPhase:
    def is_vapour_dispersed(self) -> bool: ...
    @staticmethod
    def Vapour() -> DispersedPhase: ...
    @staticmethod
    def Liquid() -> DispersedPhase: ...
    def variant(self) -> str: ...

class DriftFlux1d:
    def set_temperature_profile(self, temperatures: list[float]) -> None: ...
    def set_left_boundary(self, bc: AxialBoundary) -> None: ...
    def set_right_boundary(self, bc: AxialBoundary) -> None: ...
    def vapour_relaxation_time(self) -> float: ...
    def set_vapour_relaxation_time(self, tau: float) -> None: ...
    def set_outer_correctors(self, n: int) -> None: ...
    def outer_correctors(self) -> int: ...
    def set_pressure_under_relaxation(self, alpha: float) -> None: ...
    def time(self) -> float: ...
    def pressure(self) -> list[float]: ...
    def void_fraction(self) -> list[float]: ...
    def density(self) -> list[float]: ...
    def enthalpy(self) -> list[float]: ...
    def face_velocity(self) -> list[float]: ...
    def pipe(self) -> Pipe1d: ...
    def temperature(self, cell: int) -> float: ...
    def inventory(self) -> float: ...
    def outlet_mass_flow(self) -> float: ...
    def phase_velocities(self) -> tuple[list[float], list[float]]: ...
    def step(self) -> DriftFluxReport: ...

class DriftFluxReport:
    time: float
    outlet_mass_flow: float
    outlet_choked: bool
    inventory: float
    max_void_fraction: float
    max_courant: float
    def __init__(self, time: float, outlet_mass_flow: float, outlet_choked: bool, inventory: float, max_void_fraction: float, max_courant: float) -> None: ...

class InterfacialCellState:
    pressure: float
    void_fraction: float
    vapour_enthalpy: float
    liquid_enthalpy: float
    vapour_velocity: float
    liquid_velocity: float
    def __init__(self, pressure: float, void_fraction: float, vapour_enthalpy: float, liquid_enthalpy: float, vapour_velocity: float, liquid_velocity: float) -> None: ...
    def slip_velocity(self) -> float: ...

class InterfacialExchange:
    @staticmethod
    def bubbly(diameter: float) -> InterfacialExchange: ...
    @staticmethod
    def droplet(diameter: float) -> InterfacialExchange: ...
    def dispersed_phase(self) -> DispersedPhase: ...
    def continuous_side_model(self) -> outram_foam_multiphase.InterfacialHeatTransfer: ...
    def dispersed_side_model(self) -> outram_foam_multiphase.InterfacialHeatTransfer: ...
    def diameter(self) -> float: ...
    def residual_alpha(self) -> float: ...
    def sources_si(self, cell: InterfacialCellState) -> InterfacialSources: ...
    def sources_with_properties(self, cell: InterfacialCellState, saturated: SaturatedProperties, transport: SaturatedTransport) -> InterfacialSources: ...

class InterfacialSources:
    volumetric_drag_coefficient: float
    drag_force_on_vapour: float
    vapour_heat: float
    liquid_heat: float
    mass_transfer: float
    interface_temperature: float
    vapour_temperature: float
    liquid_temperature: float
    slip_reynolds_number: float
    def drag_force_on_liquid(self) -> float: ...
    def vapour_heat_density(self) -> float: ...
    def liquid_heat_density(self) -> float: ...
    def saturation_temperature(self) -> float: ...
    def net_heat_to_interface(self) -> float: ...
    def is_evaporating(self) -> bool: ...
    def __init__(self, volumetric_drag_coefficient: float, drag_force_on_vapour: float, vapour_heat: float, liquid_heat: float, mass_transfer: float, interface_temperature: float, vapour_temperature: float, liquid_temperature: float, slip_reynolds_number: float) -> None: ...

class PhaseCouplingBlock:
    vapour_vapour: float
    vapour_liquid: float
    liquid_vapour: float
    liquid_liquid: float
    vapour_diagonal: float
    liquid_diagonal: float
    tapered_virtual_mass_vapour: float
    tapered_virtual_mass_liquid: float
    @staticmethod
    def assemble(inputs: PhaseCouplingInputs) -> PhaseCouplingBlock: ...
    def determinant(self) -> float: ...
    def solve(self, b_vapour: float, b_liquid: float) -> tuple[float, float]: ...
    def pressure_coefficients(self, alpha_g: float, alpha_l: float) -> tuple[float, float]: ...
    def __init__(self, vapour_vapour: float, vapour_liquid: float, liquid_vapour: float, liquid_liquid: float, vapour_diagonal: float, liquid_diagonal: float, tapered_virtual_mass_vapour: float, tapered_virtual_mass_liquid: float) -> None: ...

class PhaseCouplingInputs:
    alpha_g: float
    alpha_l: float
    rho_g: float
    rho_l: float
    k_d: float
    c_vm: float
    dispersed: DispersedPhase
    residual_alpha: float
    dt: float
    def __init__(self, alpha_g: float, alpha_l: float, rho_g: float, rho_l: float, k_d: float, c_vm: float, dispersed: DispersedPhase, residual_alpha: float, dt: float) -> None: ...

class Pipe1d:
    def __init__(self, length: float, flow_area: float, hydraulic_diameter: float, incline: float, n_cells: int) -> None: ...
    @staticmethod
    def circular(length: float, inside_diameter: float, incline: float, n_cells: int) -> Pipe1d: ...
    def length(self) -> float: ...
    def flow_area(self) -> float: ...
    def hydraulic_diameter(self) -> float: ...
    def incline(self) -> float: ...
    def n_cells(self) -> int: ...
    def dx(self) -> float: ...
    def cell_volume(self) -> float: ...
    def area_si(self) -> float: ...
    def hydraulic_diameter_si(self) -> float: ...
    def axial_gravity(self) -> float: ...
    def cell_centre(self, i: int) -> float: ...
    def nearest_cell(self, x: float) -> int: ...

class SaturatedProperties:
    pressure: float
    t_sat: float
    h_f: float
    h_g: float
    rho_f: float
    rho_g: float
    mu_f: float
    mu_g: float
    @staticmethod
    def at(p: float) -> SaturatedProperties: ...
    def h_fg(self) -> float: ...
    def is_stale_for(self, p: float) -> bool: ...
    def saturation_temperature(self) -> float: ...
    def liquid_density(self) -> float: ...
    def vapour_density(self) -> float: ...
    def latent_heat(self) -> float: ...
    def __init__(self, pressure: float, t_sat: float, h_f: float, h_g: float, rho_f: float, rho_g: float, mu_f: float, mu_g: float) -> None: ...

class TwoFluid1d:
    @staticmethod
    def bubbly(pipe: Pipe1d, pressure: float, temperature: float, dt: float) -> TwoFluid1d: ...
    def set_temperature_profile(self, temperatures: list[float]) -> None: ...
    def set_left_boundary(self, bc: TwoFluidBoundary) -> None: ...
    def set_right_boundary(self, bc: TwoFluidBoundary) -> None: ...
    def virtual_mass_coefficient(self) -> float: ...
    def set_virtual_mass_coefficient(self, c_vm: float) -> None: ...
    def residual_alpha(self) -> float: ...
    def set_residual_alpha(self, residual_alpha: float) -> None: ...
    def initial_void_fraction(self) -> float: ...
    def set_initial_void_fraction(self, alpha: float) -> None: ...
    def set_outer_correctors(self, n: int) -> None: ...
    def outer_correctors(self) -> int: ...
    def set_pressure_under_relaxation(self, alpha: float) -> None: ...
    def time(self) -> float: ...
    def pipe(self) -> Pipe1d: ...
    def pressure(self) -> list[float]: ...
    def void_fraction(self) -> list[float]: ...
    def liquid_fraction(self) -> list[float]: ...
    def vapour_density(self) -> list[float]: ...
    def liquid_density(self) -> list[float]: ...
    def vapour_enthalpy(self) -> list[float]: ...
    def liquid_enthalpy(self) -> list[float]: ...
    def vapour_temperature(self) -> list[float]: ...
    def liquid_temperature(self) -> list[float]: ...
    def saturation_temperature(self) -> list[float]: ...
    def vapour_face_velocity(self) -> list[float]: ...
    def liquid_face_velocity(self) -> list[float]: ...
    def slip_velocity(self) -> list[float]: ...
    def mixture_density(self) -> list[float]: ...
    def inventory(self) -> float: ...
    def total_enthalpy(self) -> float: ...
    def outlet_mass_flow(self) -> float: ...
    def cell_vapour_density(self, i: int) -> float: ...
    def cell_liquid_enthalpy(self, i: int) -> float: ...
    def cell_vapour_temperature(self, i: int) -> float: ...
    def cell_liquid_temperature(self, i: int) -> float: ...
    def step(self) -> TwoFluidReport: ...

class TwoFluidBoundary:
    @staticmethod
    def Closed() -> TwoFluidBoundary: ...
    @staticmethod
    def PrescribedVelocity(a0: float) -> TwoFluidBoundary: ...
    @staticmethod
    def ChokedOutlet(area_fraction: float, ambient_pressure: float) -> TwoFluidBoundary: ...
    def variant(self) -> str: ...

class TwoFluidReport:
    time: float
    outlet_mass_flow: float
    max_void_fraction: float
    max_thermal_nonequilibrium: float
    min_void_fraction: float
    max_slip: float
    inventory: float
    max_courant: float
    max_volume_residual: float
    outer_correctors_used: int
    outlet_choked: bool
    mass_transfer_limited_cells: int
    residual_alpha_floor_events: int
    def __init__(self, time: float, outlet_mass_flow: float, max_void_fraction: float, max_thermal_nonequilibrium: float, min_void_fraction: float, max_slip: float, inventory: float, max_courant: float, max_volume_residual: float, outer_correctors_used: int, outlet_choked: bool, mass_transfer_limited_cells: int, residual_alpha_floor_events: int) -> None: ...

class TwoPhaseState:
    pressure: float
    enthalpy: float
    quality: float
    void_fraction: float
    density: float
    temperature: float
    @staticmethod
    def flash(p: float, h: float, saturated: SaturatedProperties) -> TwoPhaseState: ...
    def compressibility(self, relative_step: float) -> float: ...
    def __init__(self, pressure: float, enthalpy: float, quality: float, void_fraction: float, density: float, temperature: float) -> None: ...

class AxialBoundary:
    @staticmethod
    def Closed() -> AxialBoundary: ...
    @staticmethod
    def PrescribedVelocity(a0: float) -> AxialBoundary: ...
    @staticmethod
    def ChokedOutlet(area_fraction: float, ambient_pressure: float) -> AxialBoundary: ...
    @staticmethod
    def ReservoirInlet(stagnation_pressure: float, stagnation_enthalpy: float) -> AxialBoundary: ...
    @staticmethod
    def PressureOutlet(pressure: float) -> AxialBoundary: ...
    def variant(self) -> str: ...

class PhaseState:
    pressure: float
    enthalpy: float
    temperature: float
    density: float
    metastable_departure: float
    @staticmethod
    def liquid_at(p: float, h: float, saturated: SaturatedProperties) -> PhaseState: ...
    @staticmethod
    def vapour_at(p: float, h: float, saturated: SaturatedProperties) -> PhaseState: ...
    def thermodynamic_temperature(self) -> float: ...
    def mass_density(self) -> float: ...
    def __init__(self, pressure: float, enthalpy: float, temperature: float, density: float, metastable_departure: float) -> None: ...

class SaturatedTransport:
    pressure: float
    lambda_f: float
    lambda_g: float
    cp_f: float
    cp_g: float
    @staticmethod
    def at(p: float) -> SaturatedTransport: ...
    def is_stale_for(self, p: float) -> bool: ...
    def liquid_prandtl(self, saturated: SaturatedProperties) -> float: ...
    def vapour_prandtl(self, saturated: SaturatedProperties) -> float: ...
    def liquid_conductivity(self) -> float: ...
    def vapour_conductivity(self) -> float: ...
    def __init__(self, pressure: float, lambda_f: float, lambda_g: float, cp_f: float, cp_g: float) -> None: ...

class DispersionModel:
    def effective_conductivity(self, matrix_conductivity: float, particle_conductivity: float, particle_volume_fraction: float) -> float: ...
    @staticmethod
    def MaxwellEucken() -> DispersionModel: ...
    @staticmethod
    def ChiewGlandt() -> DispersionModel: ...
    def variant(self) -> str: ...

class GraphiteModeratorFeedback:
    moderator_temperature: float
    reference_temperature: float
    graphite_mass: float
    def temperature_excursion(self) -> float: ...
    def reactivity(self) -> float: ...
    def reactivity_pcm(self) -> float: ...
    def specific_heat_capacity(self) -> float: ...
    def thermal_capacity(self) -> float: ...
    def step(self, heat_in: float, heat_out: float, timestep: float) -> float: ...
    def thermal_time_constant(self, conductance: float) -> float: ...
    def thermal_time_constant_from_coefficient(self, heat_transfer_coefficient: float, area: float) -> float: ...

class PackedBedConvection:
    pebble_diameter: float
    porosity: float
    def __init__(self, pebble_diameter: float, porosity: float) -> None: ...
    @staticmethod
    def htr10() -> PackedBedConvection: ...
    def reynolds_number(self, superficial_velocity: float, density: float, dynamic_viscosity: float) -> float: ...
    def is_within_validity_range(self, reynolds: float) -> bool: ...
    def nusselt_number(self, reynolds: float, prandtl: float) -> float: ...
    def heat_transfer_coefficient(self, reynolds: float, prandtl: float, fluid_conductivity: float) -> float: ...

class Pebble:
    outer_radius: float
    fuelled_zone_radius: float
    particle: TrisoParticle
    particles_per_pebble: float
    dispersion_model: DispersionModel
    def __init__(self, outer_radius: float, fuelled_zone_radius: float, particle: TrisoParticle, particles_per_pebble: float, dispersion_model: DispersionModel) -> None: ...
    @staticmethod
    def htr10() -> Pebble: ...
    def fuelled_zone_volume(self) -> float: ...
    def pebble_volume(self) -> float: ...
    def triso_volume_fraction(self) -> float: ...

class PebbleTemperatureProfile:
    centre: float
    fuelled_zone_boundary: float
    surface: float
    peak_kernel_centre: float
    hottest_particle: TrisoTemperatureProfile
    def total_rise(self) -> float: ...
    def matrix_rise(self) -> float: ...
    def __init__(self, centre: float, fuelled_zone_boundary: float, surface: float, peak_kernel_centre: float, hottest_particle: TrisoTemperatureProfile) -> None: ...

class TrisoLayer:
    @staticmethod
    def Kernel() -> TrisoLayer: ...
    @staticmethod
    def Buffer() -> TrisoLayer: ...
    @staticmethod
    def InnerPyC() -> TrisoLayer: ...
    @staticmethod
    def SiliconCarbide() -> TrisoLayer: ...
    @staticmethod
    def OuterPyC() -> TrisoLayer: ...
    def variant(self) -> str: ...

class TrisoParticle:
    kernel_radius: float
    buffer_outer_radius: float
    inner_pyc_outer_radius: float
    silicon_carbide_outer_radius: float
    outer_pyc_outer_radius: float
    buffer_density: float
    pyrocarbon_density: float
    def __init__(self, kernel_radius: float, buffer_outer_radius: float, inner_pyc_outer_radius: float, silicon_carbide_outer_radius: float, outer_pyc_outer_radius: float, buffer_density: float, pyrocarbon_density: float) -> None: ...
    @staticmethod
    def htr10() -> TrisoParticle: ...
    @staticmethod
    def from_boon_lay_cell(cell: boon_lay.TrisoCell, buffer_density: float, pyrocarbon_density: float) -> TrisoParticle: ...
    def to_boon_lay_cell(self) -> boon_lay.TrisoCell: ...
    def layer_outer_radius(self, layer: TrisoLayer) -> float: ...
    def layer_inner_radius(self, layer: TrisoLayer) -> float: ...
    def layer_volume(self, layer: TrisoLayer) -> float: ...
    def particle_volume(self) -> float: ...
    def layer_volume_fraction(self, layer: TrisoLayer) -> float: ...

class TrisoTemperatureProfile:
    kernel_centre: float
    kernel_surface: float
    buffer_outer: float
    inner_pyc_outer: float
    silicon_carbide_outer: float
    particle_surface: float
    def total_rise(self) -> float: ...
    def __init__(self, kernel_centre: float, kernel_surface: float, buffer_outer: float, inner_pyc_outer: float, silicon_carbide_outer: float, particle_surface: float) -> None: ...

class ZbsBed:
    porosity: float
    pebble_diameter: float
    emissivity: float
    contact_area_fraction: float
    shape_factor_c: float
    def __init__(self, porosity: float, pebble_diameter: float, emissivity: float) -> None: ...
    @staticmethod
    def htr10() -> ZbsBed: ...
    def deformation_factor(self) -> float: ...
    def radiation_ratio(self, fluid_conductivity: float, temperature: float) -> float: ...
    def effective_conductivity(self, solid_conductivity: float, fluid_conductivity: float, temperature: float) -> float: ...
    def stagnant_conductivity(self, solid_conductivity: float, fluid_conductivity: float) -> float: ...
    def wall_region_porosity(self, distance_from_wall: float) -> float: ...
    def with_porosity(self, porosity: float) -> ZbsBed: ...

def merkel_ntu_effectiveness() -> None: ...
def helium_cp(t: float, p: float) -> float: ...
def helium_density(t: float, p: float) -> float: ...
def helium_prandtl(t: float, p: float) -> float: ...
def helium_state(t: float, p: float) -> HeliumState: ...
def helium_thermal_conductivity(t: float, p: float) -> float: ...
def helium_viscosity(t: float, p: float) -> float: ...
def kta_friction_factor(reynolds: float, porosity: float) -> float: ...
def churchill_friction_factor(reynolds: float, relative_roughness: float) -> float: ...
def nusselt_number(correlation: HeatTransferCorrelation, reynolds: float, prandtl: float, darcy_friction_factor: float) -> float: ...
def core_inlet_temperature() -> float: ...
def core_outlet_temperature() -> float: ...
def mass_flow_rate() -> float: ...
def pressure() -> float: ...
def thermal_power() -> float: ...
def reynolds_number(mass_flux_kg_per_m2_s: float, hydraulic_diameter: float, dynamic_viscosity: float) -> float: ...
def state_from_t_p_r(t: float, p: float, r: float) -> HumidAirState: ...
def state_from_t_p_w(t: float, p: float, w: float) -> HumidAirState: ...
def as_velocity(u_si: float) -> float: ...
def cell_position(pipe: Pipe1d, cell: int) -> float: ...
def thomas_solve(a: list[float], b: list[float], c: list[float], d: list[float]) -> list[float]: ...
def as_velocity(u_si: float) -> float: ...
def region_4_safe_pressure(p: float) -> float: ...
def virtual_mass_coefficient(alpha_dispersed: float, rho_continuous: float, c_vm: float, residual_alpha: float) -> float: ...
def coated_particles_per_pebble(heavy_metal_mass: float, kernel_radius: float, uranium_dioxide_density: float, enrichment: float) -> float: ...
def htr10_enrichment() -> float: ...
def htr10_heavy_metal_per_pebble() -> float: ...
def htr10_uranium_dioxide_density() -> float: ...
def uranium_dioxide_heavy_metal_fraction(enrichment: float) -> float: ...
def temperature_difference(hotter: float, colder: float) -> float: ...
def solid_sphere_centre_temperature_rise(power: float, radius: float, conductivity: float) -> float: ...
def spherical_shell_temperature_rise(power: float, inner_radius: float, outer_radius: float, conductivity: float) -> float: ...
def uranium_dioxide_thermal_conductivity(temperature: float) -> float: ...
COMPRESSIBILITY_STEP: float
DEFAULT_OUTER_CORRECTORS: int
DEFAULT_OUTER_TOLERANCE: float
DEFAULT_PRESSURE_UNDER_RELAXATION: float
DEFAULT_VAPOUR_RELAXATION_TIME: float
MIN_LATENT_HEAT_FOR_MASS_TRANSFER: float
P_CRITICAL_WATER: float
MAX_METASTABLE_LIQUID_SUPERHEAT: float
MAX_METASTABLE_VAPOUR_SUBCOOLING: float
P_MAX_IF97: float
P_MIN_IF97: float
SATURATION_CACHE_TOLERANCE: float
TRANSPORT_CACHE_TOLERANCE: float
T_MAX_REGION_1: float
T_MAX_REGION_2: float
T_MIN_IF97: float
COMPRESSIBILITY_STEP: float
DEFAULT_BUBBLE_DIAMETER: float
DEFAULT_INITIAL_VOID_FRACTION: float
DEFAULT_OUTER_CORRECTORS: int
DEFAULT_OUTER_TOLERANCE: float
DEFAULT_PRESSURE_UNDER_RELAXATION: float
DEFAULT_RESIDUAL_ALPHA: float
DEFAULT_VIRTUAL_MASS_COEFFICIENT: float
DEFAULT_VOLUME_RESIDUAL_TOLERANCE: float
MAX_MASS_TRANSFER_FRACTION_PER_STEP: float
MAX_REGION_4_NUDGE: float
MAX_VOLUME_RESIDUAL: float
PHASE_FLOOR_TRIGGER: float
WAKAO_MAX_REYNOLDS: float
WAKAO_MIN_REYNOLDS: float
MOLAR_MASS_OXYGEN_G_PER_MOL: float
MOLAR_MASS_U235_G_PER_MOL: float
MOLAR_MASS_U238_G_PER_MOL: float
MAX_TEMPERATURE_KELVIN: float
MIN_TEMPERATURE_KELVIN: float
THEORETICAL_CARBON_DENSITY_KG_PER_M3: float
