"""Type stubs for `outram_park.teh_o_prke`, generated from the Rust API.

Physical quantities cross this boundary as `float` in SI base units.
"""

class DecayHeat:
    def __init__(self, nuclide: FissioningNuclide) -> None: ...
    @staticmethod
    def new_at_equilibrium(nuclide: FissioningNuclide, fission_power: float) -> DecayHeat: ...
    def with_energy_per_fission(self, energy_per_fission: float) -> DecayHeat: ...
    def nuclide(self) -> FissioningNuclide: ...
    def advance_timestep(self, fission_power: float, timestep: float) -> None: ...
    def total_decay_heat_power(self) -> float: ...
    def prompt_power_fraction(self) -> float: ...
    def group_power(self, group_index: int) -> float | None: ...
    @staticmethod
    def default() -> DecayHeat: ...

class FissioningNuclide:
    def parameters(self) -> list[tuple[float, float]]: ...
    def total_decay_energy_per_fission(self) -> float: ...
    @staticmethod
    def U235Thermal() -> FissioningNuclide: ...
    @staticmethod
    def U238Fast() -> FissioningNuclide: ...
    @staticmethod
    def Pu239Thermal() -> FissioningNuclide: ...
    def variant(self) -> str: ...

class DelayedNeutronLayer:
    @staticmethod
    def u235_five_group(prompt_generation_time: float) -> DelayedNeutronLayer: ...
    def total_delayed_neutron_fraction(self) -> float: ...
    def prompt_generation_time(self) -> float: ...
    def decay_constants(self) -> list[float]: ...
    def delayed_fractions(self) -> list[float]: ...
    def last_delayed_increment(self) -> float: ...
    def advance(self, reactor_power: float, dt: float) -> float: ...

class SixFactorFormulaFeedback:
    p_tnl: float
    p_fnl: float
    epsilon: float
    p: float
    f: float
    eta: float
    def calc_keff(self) -> float: ...
    def calc_rho(self) -> float: ...
    def __init__(self, p_tnl: float | None = None, p_fnl: float | None = None, epsilon: float | None = None, p: float | None = None, f: float | None = None, eta: float | None = None) -> None: ...
    @staticmethod
    def default() -> SixFactorFormulaFeedback: ...

class Xenon135Poisoning:
    iodine_135_num_density: float
    xenon_135_num_density: float
    @staticmethod
    def fp_yield_iodine_135_from_u235_thermal_fission() -> float: ...
    @staticmethod
    def fp_yield_xe_135_from_u235_thermal_fission() -> float: ...
    @staticmethod
    def fp_yield_iodine_135_from_u233_thermal_fission() -> float: ...
    @staticmethod
    def fp_yield_xe_135_from_u233_thermal_fission() -> float: ...
    @staticmethod
    def fp_yield_iodine_135_from_pu239_thermal_fission() -> float: ...
    @staticmethod
    def fp_yield_xe_135_from_pu239_thermal_fission() -> float: ...
    @staticmethod
    def iodine_135_decay_const() -> float: ...
    @staticmethod
    def xe_135_decay_const() -> float: ...
    @staticmethod
    def xe135_thermal_abs_xs() -> float: ...
    def calc_xe_135_and_return_num_density(self, timestep: float, fission_rate: float, fissioning_nuclide: FissioningNuclideType, thermal_neutron_conc: float) -> float: ...
    @staticmethod
    def simplified_poison_concentration_feedback(poison_conc: float) -> float: ...
    def get_current_xe135_conc(self) -> float: ...
    @staticmethod
    def gaseous_xe135_density_estimate() -> float: ...
    @staticmethod
    def gaseous_xe135_molar_mass() -> float: ...
    @staticmethod
    def u235_thermal_abs_xs() -> float: ...
    @staticmethod
    def u238_thermal_abs_xs() -> float: ...
    @staticmethod
    def uranium_number_density_est_in_uo2() -> float: ...
    def __init__(self, iodine_135_num_density: float | None = None, xenon_135_num_density: float | None = None) -> None: ...
    @staticmethod
    def default() -> Xenon135Poisoning: ...

class SimpleFuelTemperatureFeedback:
    fuel_specific_heat_capacity: float
    fuel_density: float
    fuel_volume: float
    fuel_temperature: float
    convection_heat_trf_coeff: float
    convection_heat_trf_area: float
    alpha_coefficient: float
    def set_fuel_alpha_coefficient(self, alpha_coefficient: float) -> None: ...
    def add_fission_heat(self, fission_power: float, timestep: float) -> None: ...
    def remove_convection_heat(self, coolant_temperature: float, timestep: float) -> None: ...
    def obtain_fuel_temperature_delta_rho(self, reference_temperature: float) -> float: ...
    def __init__(self, fuel_specific_heat_capacity: float | None = None, fuel_density: float | None = None, fuel_volume: float | None = None, fuel_temperature: float | None = None, convection_heat_trf_coeff: float | None = None, convection_heat_trf_area: float | None = None, alpha_coefficient: float | None = None) -> None: ...
    @staticmethod
    def default() -> SimpleFuelTemperatureFeedback: ...

class MatrixError:
    @staticmethod
    def Singular(col: int) -> MatrixError: ...
    def variant(self) -> str: ...

class SquareMatrix:
    def __init__(self, n: int) -> None: ...
    def n(self) -> int: ...
    def get(self, i: int, j: int) -> float: ...
    def set(self, i: int, j: int, v: float) -> None: ...
    def add(self, i: int, j: int, v: float) -> None: ...
    def fill_zero(self) -> None: ...
    def lu_decompose(self) -> list[int]: ...
    def solve(self, rhs: list[float]) -> list[float]: ...

class NordheimFuchsExactTimestepper:
    prompt_neutron_generation_time: float
    delayed_neutron_fraction: float
    fuel_heat_capacity: float
    fuel_feedback_coefficient: float
    fuel_reference_temperature: float
    fuel_temperature: float
    power: float
    external_reactivity: float
    def __init__(self, prompt_neutron_generation_time: float, delayed_neutron_fraction: float, fuel_heat_capacity: float, fuel_feedback_coefficient: float, fuel_reference_temperature: float, initial_fuel_temperature: float, initial_power: float) -> None: ...
    def reactivity_margin(self) -> float: ...
    def step(self, dt: float) -> None: ...
    @staticmethod
    def default() -> NordheimFuchsExactTimestepper: ...

class TehOPrkeError:
    @staticmethod
    def ShapeMismatch(a0: str) -> TehOPrkeError: ...
    @staticmethod
    def GenericStringError(a0: str) -> TehOPrkeError: ...
    @staticmethod
    def NonNegativeFuelFeedbackCoefficient(a0: float) -> TehOPrkeError: ...
    @staticmethod
    def NonPositivePromptNeutronGenerationTime(a0: float) -> TehOPrkeError: ...
    @staticmethod
    def NonPositiveFuelHeatCapacity(a0: float) -> TehOPrkeError: ...
    @staticmethod
    def NonPositiveDelayedDecayConstant(a0: float) -> TehOPrkeError: ...
    def variant(self) -> str: ...

class SixGroupPRKE:
    delayed_fraction_array: list[float]
    delayed_group_mode: FissioningNuclideType
    precursor_and_neutron_pop_and_source_array: list[float]
    def get_current_neutron_population_density(self) -> float: ...
    def get_total_delayed_fraction(self) -> float: ...
    @staticmethod
    def get_keff_from_reactivity(reactivity: float) -> float: ...
    def __init__(self) -> None: ...
    @staticmethod
    def default() -> SixGroupPRKE: ...

class FissioningNuclideType:
    def get_delayed_fraction_array(self) -> list[float]: ...
    @staticmethod
    def U233() -> FissioningNuclideType: ...
    @staticmethod
    def U235() -> FissioningNuclideType: ...
    @staticmethod
    def Pu239() -> FissioningNuclideType: ...
    def variant(self) -> str: ...

def obtain_rod_worth_cylinder(cylinder_height: float, insertion_length: float, rod_worth: float) -> float: ...
def obtain_fuel_temperature_feedback_coeff_thermal_spectrum(alpha_coefficient: float, temperature: float) -> float: ...
def obtain_fuel_temperature_reactivity_feedback_thermal_spectrum(alpha_coefficient: float, temperature: float, reference_temperature: float) -> float: ...
def new_pu239_delayed_neutron_fraction_array() -> list[float]: ...
def new_u233_delayed_neutron_fraction_array() -> list[float]: ...
def new_u235_delayed_neutron_fraction_array() -> list[float]: ...
DECAY_HEAT_GROUPS: int
NOMINAL_ENERGY_PER_FISSION_MEV: float
NUM_DELAYED_GROUPS: int
