"""Type stubs for `outram_park.tuas_boussinesq_solver`, generated from the Rust API.

Physical quantities cross this boundary as `float` in SI base units.
"""

class DimensionlessDarcyLossCorrelations:
    @staticmethod
    def new_pipe(pipe_length: float, surface_roughness: float, hydraulic_diameter: float, form_loss: float) -> DimensionlessDarcyLossCorrelations: ...
    @staticmethod
    def new_simple_reynolds_power_component(a: float, b: float, c: float) -> DimensionlessDarcyLossCorrelations: ...
    def fldk_based_on_darcy_friction_factor(self, reynolds_input: float) -> float: ...
    def darcy_friction_factor(self, reynolds_input: float) -> float: ...
    def get_bejan_number_from_reynolds(self, reynolds_input: float) -> float: ...
    def get_reynolds_number_from_bejan(self, bejan_input: float) -> float: ...
    def get_pressure_loss_from_reynolds(self, reynolds_input: float, hydraulic_diameter: float, fluid_density: float, fluid_viscosity: float) -> float: ...
    def get_reynolds_from_pressure_loss(self, pressure_loss_input: float, hydraulic_diameter: float, fluid_density: float, fluid_viscosity: float) -> float: ...
    @staticmethod
    def Pipe(a0: float, a1: float, a2: float) -> DimensionlessDarcyLossCorrelations: ...
    @staticmethod
    def SimpleReynoldsPower(a0: float, a1: float, a2: float) -> DimensionlessDarcyLossCorrelations: ...
    @staticmethod
    def Ergun() -> DimensionlessDarcyLossCorrelations: ...
    def variant(self) -> str: ...
    @staticmethod
    def default() -> DimensionlessDarcyLossCorrelations: ...

class FluidComponent:
    @staticmethod
    def FluidArray(a0: FluidArray) -> FluidComponent: ...
    @staticmethod
    def ParallelUniformFluidArray(a0: FluidArray, a1: int) -> FluidComponent: ...
    def variant(self) -> str: ...

class FluidComponentCollection:
    components: list[FluidComponent]
    orientation: FluidComponentCollectionOreintation
    def get_immutable_fluid_component_vector(self) -> list[FluidComponent]: ...
    def set_fluid_component_vector(self, fluid_component_vector: list[FluidComponent]) -> None: ...
    def add_fluid_component(self, fluid_component: FluidComponent) -> None: ...
    def remove_fluid_component(self, component_index: int) -> None: ...
    def get_fluid_component(self, component_index: int) -> FluidComponent: ...
    def update_fluid_component(self, component_index: int, fluid_component: FluidComponent) -> None: ...
    @staticmethod
    def new_series_component_collection() -> FluidComponentCollection: ...
    @staticmethod
    def new_parallel_component_collection() -> FluidComponentCollection: ...
    def empty_vector(self) -> None: ...
    def __init__(self, components: list[FluidComponent], orientation: FluidComponentCollectionOreintation) -> None: ...

class FluidComponentCollectionOreintation:
    @staticmethod
    def Parallel() -> FluidComponentCollectionOreintation: ...
    @staticmethod
    def Series() -> FluidComponentCollectionOreintation: ...
    def variant(self) -> str: ...

class FluidComponentSuperCollection:
    fluid_component_super_vector: list[FluidComponentCollection]
    orientation: FluidComponentCollectionOreintation
    def get_immutable_vector(self) -> list[FluidComponentCollection]: ...
    def set_vector(self, fluid_component_super_vector: list[FluidComponentCollection]) -> None: ...
    def add_collection_to_vector(self, fluid_component_super_vector: list[FluidComponentCollection], fluid_component_vector: FluidComponentCollection) -> None: ...
    def remove_collection_by_index(self, fluid_component_super_vector: list[FluidComponentCollection], component_index: int) -> None: ...
    def get_collection_by_index(self, component_index: int) -> FluidComponentCollection: ...
    def update_collection_by_index(self, component_index: int, fluid_component_super_vector: list[FluidComponentCollection], fluid_component_collection: FluidComponentCollection) -> None: ...
    def set_orientation_to_series(self) -> None: ...
    def set_orientation_to_parallel(self) -> None: ...
    def get_mass_flowrate_across_each_parallel_branch(self, pressure_change_across_each_branch: float) -> list[float]: ...
    def __init__(self, fluid_component_super_vector: list[FluidComponentCollection] | None = None, orientation: FluidComponentCollectionOreintation | None = None) -> None: ...
    @staticmethod
    def default() -> FluidComponentSuperCollection: ...

class CartesianConduction1DArray:
    inner_single_cv: SingleCVNode
    outer_single_cv: SingleCVNode
    material_control_volume: Material
    pressure_control_volume: float
    def get_max_timestep(self, max_temperature_change: float) -> float: ...
    def get_temperature_vector(self) -> list[float]: ...
    def advance_timestep(self, timestep: float) -> None: ...
    def __init__(self, material: Material, initial_uniform_temperature: float, uniform_pressure: float, inner_nodes: int, total_length: float) -> None: ...
    def get_bulk_temperature(self) -> float: ...
    @staticmethod
    def default() -> CartesianConduction1DArray: ...

class BCType:
    @staticmethod
    def new_const_temperature(temperature: float) -> BCType: ...
    @staticmethod
    def new_const_heat_flux(heat_flux: float) -> BCType: ...
    @staticmethod
    def new_const_heat_addition(heat_addition: float) -> BCType: ...
    @staticmethod
    def new_adiabatic_bc() -> BCType: ...
    @staticmethod
    def UserSpecifiedTemperature(a0: float) -> BCType: ...
    @staticmethod
    def UserSpecifiedHeatFlux(a0: float) -> BCType: ...
    @staticmethod
    def UserSpecifiedHeatAddition(a0: float) -> BCType: ...
    def variant(self) -> str: ...

class LiquidMaterial:
    def try_get_nu_momentum_diffusivity(self, fluid_temp: float, pressure: float) -> float: ...
    def try_get_thermal_conductivity(self, fluid_temp: float) -> float: ...
    def try_get_alpha_thermal_diffusivity(self, fluid_temp: float, pressure: float) -> float: ...
    def try_get_density(self, fluid_temp: float) -> float: ...
    def try_get_dynamic_viscosity(self, fluid_temp: float) -> float: ...
    def try_get_prandtl_liquid(self, temperature: float, pressure: float) -> float: ...
    def try_get_cp(self, fluid_temp: float) -> float: ...
    def max_temperature(self) -> float: ...
    def min_temperature(self) -> float: ...
    @staticmethod
    def TherminolVP1() -> LiquidMaterial: ...
    @staticmethod
    def DowthermA() -> LiquidMaterial: ...
    @staticmethod
    def HITEC() -> LiquidMaterial: ...
    @staticmethod
    def YD325() -> LiquidMaterial: ...
    @staticmethod
    def FLiBe() -> LiquidMaterial: ...
    @staticmethod
    def FLiNaK() -> LiquidMaterial: ...
    def variant(self) -> str: ...

class Material:
    def surface_roughness(self) -> float: ...
    def max_temperature(self) -> float: ...
    def min_temperature(self) -> float: ...
    def try_get_thermal_conductivity(self, temperature: float) -> float: ...
    def density(self, temperature: float, _pressure: float) -> float: ...
    @staticmethod
    def Solid(a0: SolidMaterial) -> Material: ...
    @staticmethod
    def Liquid(a0: LiquidMaterial) -> Material: ...
    def variant(self) -> str: ...
    @staticmethod
    def default() -> Material: ...

class SolidMaterial:
    def try_get_cp(self, solid_temp: float) -> float: ...
    def try_get_thermal_conductivity(self, solid_temp: float) -> float: ...
    def surface_roughness(self) -> float: ...
    def max_temperature(self) -> float: ...
    def min_temperature(self) -> float: ...
    def try_get_alpha_thermal_diffusivity(self, solid_temp: float, pressure: float) -> float: ...
    @staticmethod
    def SteelSS304L() -> SolidMaterial: ...
    @staticmethod
    def SteelSS304LHighTemp() -> SolidMaterial: ...
    @staticmethod
    def Copper() -> SolidMaterial: ...
    @staticmethod
    def Fiberglass() -> SolidMaterial: ...
    @staticmethod
    def PyrogelHPS() -> SolidMaterial: ...
    @staticmethod
    def NuclearGraphiteMatrixA3() -> SolidMaterial: ...
    @staticmethod
    def NuclearGraphiteIG110() -> SolidMaterial: ...
    def variant(self) -> str: ...

class CylindricalAndSphericalSolidFluidArrangement:
    @staticmethod
    def FluidOnInnerSurfaceOfSolidShell() -> CylindricalAndSphericalSolidFluidArrangement: ...
    @staticmethod
    def FluidOnOuterSurfaceOfSolidShell() -> CylindricalAndSphericalSolidFluidArrangement: ...
    def variant(self) -> str: ...

class DataDualCartesianThermalConductanceThreeDimension:
    material_1: Material
    material_2: Material
    xs_area: CrossSectionalArea
    thickness_1: XThicknessThermalConduction
    thickness_2: XThicknessThermalConduction
    def __init__(self, material_1: Material, material_2: Material, xs_area: CrossSectionalArea, thickness_1: XThicknessThermalConduction, thickness_2: XThicknessThermalConduction) -> None: ...

class NusseltCorrelation:
    def try_get_nusselt(self) -> float: ...
    def estimate_based_on_prandtl_darcy_and_reynolds_no_wall_correction(self, bulk_prandtl_number_input: float, darcy_friction_factor: float, reynolds_number_input: float) -> float: ...
    def estimate_based_on_prandtl_and_reynolds_no_wall_correction(self, bulk_prandtl_number_input: float, reynolds_number_input: float) -> float: ...
    def estimate_based_on_prandtl_reynolds_and_wall_correction(self, bulk_prandtl_number_input: float, wall_prandtl_number_input: float, reynolds_number_input: float) -> float: ...
    def estimate_based_on_prandtl_darcy_and_reynolds_wall_correction(self, bulk_prandtl_number_input: float, wall_prandtl_number_input: float, darcy_friction_factor: float, reynolds_number_input: float) -> float: ...
    @staticmethod
    def PipeGnielinskiGeneric(a0: GnielinskiData) -> NusseltCorrelation: ...
    @staticmethod
    def PipeGnielinskiCalibrated(a0: GnielinskiData, a1: float) -> NusseltCorrelation: ...
    @staticmethod
    def PipeGnielinskiGenericPrandtlFilm(a0: GnielinskiData) -> NusseltCorrelation: ...
    @staticmethod
    def CustomGnielinskiGenericPrandtlFilm(a0: GnielinskiData, a1: float, a2: float) -> NusseltCorrelation: ...
    @staticmethod
    def CustomGnielinskiGenericPrandtlBulk(a0: GnielinskiData, a1: float, a2: float) -> NusseltCorrelation: ...
    @staticmethod
    def PipeGnielinskiTurbulentPrandtlBulk(a0: GnielinskiData) -> NusseltCorrelation: ...
    @staticmethod
    def Wakao(a0: WakaoData) -> NusseltCorrelation: ...
    @staticmethod
    def ReynoldsPrandtl(a0: NusseltPrandtlReynoldsData) -> NusseltCorrelation: ...
    @staticmethod
    def PipeConstantHeatFluxFullyDeveloped() -> NusseltCorrelation: ...
    @staticmethod
    def PipeConstantTemperatureFullyDeveloped() -> NusseltCorrelation: ...
    @staticmethod
    def CIETHeaterVersion2(a0: NusseltPrandtlReynoldsData) -> NusseltCorrelation: ...
    @staticmethod
    def IdealNusseltOneBillion() -> NusseltCorrelation: ...
    @staticmethod
    def FixedNusselt(a0: float) -> NusseltCorrelation: ...
    def variant(self) -> str: ...
    @staticmethod
    def default() -> NusseltCorrelation: ...

class GnielinskiData:
    reynolds: float
    prandtl_bulk: float
    prandtl_wall: float
    darcy_friction_factor: float
    length_to_diameter: float
    def get_nusselt_for_developing_flow_bulk_fluid_prandtl(self) -> float: ...
    def get_nusselt_for_developing_flow(self) -> float: ...
    def get_nusselt_for_custom_developing_flow_prandtl_film(self, correlation_coefficient_c: float, reynolds_exponent_m: float) -> float: ...
    def get_nusselt_for_custom_developing_flow_prandtl_bulk(self, correlation_coefficient_c: float, reynolds_exponent_m: float) -> float: ...
    def __init__(self, reynolds: float | None = None, prandtl_bulk: float | None = None, prandtl_wall: float | None = None, darcy_friction_factor: float | None = None, length_to_diameter: float | None = None) -> None: ...
    @staticmethod
    def default() -> GnielinskiData: ...

class NusseltPrandtlReynoldsData:
    reynolds: float
    prandtl_bulk: float
    prandtl_wall: float
    constant: float
    reynolds_prandtl_coefficient: float
    reynolds_power: float
    prandtl_power: float
    prandtl_correction_factor_power: float
    def custom_reynolds_prandtl(self) -> float: ...
    def ciet_version_2_heater_uncorrected(self) -> float: ...
    def ciet_version_2_heater_prandtl_corrected(self) -> float: ...
    def __init__(self, reynolds: float | None = None, prandtl_bulk: float | None = None, prandtl_wall: float | None = None, constant: float | None = None, reynolds_prandtl_coefficient: float | None = None, reynolds_power: float | None = None, prandtl_power: float | None = None, prandtl_correction_factor_power: float | None = None) -> None: ...
    @staticmethod
    def default() -> NusseltPrandtlReynoldsData: ...

class WakaoData:
    reynolds: float
    prandtl_bulk: float
    def get(self) -> float: ...
    def __init__(self, reynolds: float | None = None, prandtl_bulk: float | None = None) -> None: ...
    @staticmethod
    def default() -> WakaoData: ...

class MatrixError:
    @staticmethod
    def Singular(col: int) -> MatrixError: ...
    def variant(self) -> str: ...

class SquareMatrix:
    def __init__(self, n: int) -> None: ...
    def n(self) -> int: ...
    def get(self, i: int, j: int) -> float: ...
    def set(self, i: int, j: int, v: float) -> None: ...
    def add(self, i: int, j: int, v: float) -> None: ...
    def fill_zero(self) -> None: ...
    def lu_decompose(self) -> list[int]: ...
    def solve(self, rhs: list[float]) -> list[float]: ...

class CVType:
    def get_material(self) -> Material: ...
    def get_temperature_vector(self) -> list[float]: ...
    @staticmethod
    def SingleCV(a0: SingleCVNode) -> CVType: ...
    @staticmethod
    def FluidArrayCV(a0: FluidArray) -> CVType: ...
    @staticmethod
    def SolidArrayCV(a0: SolidColumn) -> CVType: ...
    def variant(self) -> str: ...

class InsulatedFluidComponent:
    pipe_shell: HeatTransferEntity
    pipe_fluid_array: HeatTransferEntity
    insulation: HeatTransferEntity
    ambient_temperature: float
    heat_transfer_to_ambient: float
    tube_od: float
    tube_id: float
    darcy_loss_correlation: DimensionlessDarcyLossCorrelations
    def advance_timestep(self, timestep: float) -> None: ...
    def calibrate_insulation_thickness(self, insulation_thickness: float) -> None: ...
    def get_insulation_thickness(self) -> float: ...
    def calibrate_heat_transfer_to_ambient(self, ambient_htc: float) -> None: ...
    def try_calibrate_gnielinski_nusselt(self, calibration_ratio: float) -> None: ...
    @staticmethod
    def new_insulated_pipe(initial_temperature: float, ambient_temperature: float, fluid_pressure: float, solid_pressure: float, flow_area: float, incline_angle: float, form_loss: float, shell_id: float, shell_od: float, insulation_thickness: float, pipe_length: float, hydraulic_diameter: float, pipe_shell_material: SolidMaterial, insulation_material: SolidMaterial, pipe_fluid: LiquidMaterial, htc_to_ambient: float, user_specified_inner_nodes: int, surface_roughness: float) -> InsulatedFluidComponent: ...
    @staticmethod
    def new_custom_component(initial_temperature: float, ambient_temperature: float, fluid_pressure: float, solid_pressure: float, flow_area: float, incline_angle: float, form_loss: float, reynolds_coefficient: float, reynolds_power: float, shell_id: float, shell_od: float, insulation_thickness: float, component_length: float, hydraulic_diameter: float, pipe_shell_material: SolidMaterial, insulation_material: SolidMaterial, pipe_fluid: LiquidMaterial, htc_to_ambient: float, user_specified_inner_nodes: int) -> InsulatedFluidComponent: ...
    def pipe_shell_temperature(self) -> list[float]: ...
    def pipe_fluid_array_temperature(self) -> list[float]: ...
    def insulation_array_temperature(self) -> list[float]: ...
    def lateral_and_miscellaneous_connections_no_wall_correction(self, mass_flowrate: float, heater_power: float) -> None: ...
    def lateral_and_miscellaneous_connections_wall_correction(self, mass_flowrate: float, heater_power: float) -> None: ...
    def lateral_and_miscellaneous_connections(self, mass_flowrate: float, heater_power: float, correct_prandtl_for_wall_temperatures: bool) -> None: ...
    def get_ambient_surroundings_to_insulation_nodalised_thermal_conductance(self, h_air_to_pipe_surf: float) -> float: ...
    def get_fluid_array_node_to_pipe_shell_conductance(self, correct_prandtl_for_wall_temperatures: bool) -> float: ...
    def get_reynolds_based_on_hydraulic_diameter_and_flow_area(self, mass_flowrate: float, temperature: float) -> float: ...
    def get_pipe_shell_to_insulation_nodal_conductance(self) -> float: ...

class NonInsulatedFluidComponent:
    pipe_shell: HeatTransferEntity
    pipe_fluid_array: HeatTransferEntity
    ambient_temperature: float
    heat_transfer_to_ambient: float
    od: float
    id: float
    flow_area: float
    custom_component_loss_correlation: DimensionlessDarcyLossCorrelations
    def pipe_shell_temperature(self) -> list[float]: ...
    def pipe_fluid_array_temperature(self) -> list[float]: ...
    @staticmethod
    def new_bare_pipe(initial_temperature: float, ambient_temperature: float, fluid_pressure: float, solid_pressure: float, flow_area: float, incline_angle: float, form_loss: float, id: float, od: float, pipe_length: float, hydraulic_diameter: float, surface_roughness: float, pipe_shell_material: SolidMaterial, pipe_fluid: LiquidMaterial, htc_to_ambient: float, user_specified_inner_nodes: int) -> NonInsulatedFluidComponent: ...
    @staticmethod
    def new_dewet_model_heater_v2_no_twisted_tape(initial_temperature: float, ambient_temperature: float, user_specified_inner_nodes: int) -> NonInsulatedFluidComponent: ...
    @staticmethod
    def new_custom_component(initial_temperature: float, ambient_temperature: float, fluid_pressure: float, solid_pressure: float, flow_area: float, incline_angle: float, form_loss: float, reynolds_coefficient: float, reynolds_power: float, shell_id: float, shell_od: float, component_length: float, hydraulic_diameter: float, pipe_shell_material: SolidMaterial, pipe_fluid: LiquidMaterial, htc_to_ambient: float, user_specified_inner_nodes: int) -> NonInsulatedFluidComponent: ...
    def calibrate_nusselt_correlation_for_fluid_within_pipe(self, nusselt_correlation_user_set: NusseltCorrelation) -> None: ...
    def lateral_and_miscellaneous_connections_no_wall_correction(self, mass_flowrate: float, heater_power: float) -> None: ...
    def lateral_and_miscellaneous_connections_wall_correction(self, mass_flowrate: float, heater_power: float) -> None: ...
    def lateral_and_miscellaneous_connections(self, mass_flowrate: float, heater_power: float, correct_prandtl_for_wall_temperatures: bool) -> None: ...
    def get_air_shell_nodal_shell_conductance(self, h_air_to_pipe_surf: float) -> float: ...
    def get_fluid_array_node_pipe_shell_conductance(self, correct_prandtl_for_wall_temperatures: bool) -> float: ...
    def get_reynolds_based_on_hydraulic_diameter_and_flow_area(self, mass_flowrate: float, temperature: float) -> float: ...
    def advance_timestep(self, timestep: float) -> None: ...

class NonInsulatedParallelFluidComponent:
    pipe_shell: HeatTransferEntity
    pipe_fluid_array: HeatTransferEntity
    ambient_temperature: float
    heat_transfer_to_ambient: float
    single_tube_od: float
    single_tube_id: float
    single_tube_flow_area: float
    custom_component_loss_correlation: DimensionlessDarcyLossCorrelations
    number_of_tubes: int
    def lateral_and_miscellaneous_connections_no_wall_correction(self, mass_flowrate_over_all_tubes: float, heater_power_over_all_tubes: float) -> None: ...
    def lateral_and_miscellaneous_connections_wall_correction(self, mass_flowrate_over_all_tubes: float, heater_power_over_all_tubes: float) -> None: ...
    def lateral_and_miscellaneous_connections(self, mass_flowrate_over_all_tubes: float, heater_power_over_all_tubes: float, correct_prandtl_for_wall_temperatures: bool) -> None: ...
    def get_air_to_single_shell_nodal_shell_conductance(self, h_air_to_pipe_surf: float) -> float: ...
    def get_single_tube_fluid_array_node_pipe_shell_conductance(self, correct_prandtl_for_wall_temperatures: bool) -> float: ...
    def get_reynolds_based_on_hydraulic_diameter_and_flow_area(self, mass_flowrate: float, temperature: float) -> float: ...
    def advance_timestep(self, timestep: float) -> None: ...
    def pipe_shell_temperature(self) -> list[float]: ...
    def pipe_fluid_array_temperature(self) -> list[float]: ...
    @staticmethod
    def new_bare_pipe_parallel_array(initial_temperature: float, ambient_temperature: float, fluid_pressure: float, solid_pressure: float, flow_area: float, incline_angle: float, form_loss: float, id: float, od: float, pipe_length: float, hydraulic_diameter: float, surface_roughness: float, pipe_shell_material: SolidMaterial, pipe_fluid: LiquidMaterial, htc_to_ambient: float, user_specified_inner_nodes: int, number_of_parallel_tubes: int) -> NonInsulatedParallelFluidComponent: ...
    @staticmethod
    def new_custom_component_parallel_array(initial_temperature: float, ambient_temperature: float, fluid_pressure: float, solid_pressure: float, flow_area: float, incline_angle: float, form_loss: float, reynolds_coefficient: float, reynolds_power: float, shell_id: float, shell_od: float, component_length: float, hydraulic_diameter: float, pipe_shell_material: SolidMaterial, pipe_fluid: LiquidMaterial, htc_to_ambient: float, user_specified_inner_nodes: int, number_of_parallel_tubes: int) -> NonInsulatedParallelFluidComponent: ...

class SolidStructure:
    solid_array: HeatTransferEntity
    strucutre_length: float
    cross_sectional_area: float
    def link_mixed_boundary_condition_laterally(self, solid_array_to_ambient_nodal_conductance: float, ambient_temp: float, total_power_input_into_column: float) -> None: ...
    def link_ambient_temperature_boundary_condition_laterally(self, solid_array_to_ambient_nodal_conductance: float, ambient_temp: float) -> None: ...
    def get_ambient_surroundings_to_cylinder_thermal_conductance(self, h_air_to_pipe_surf: float, cylinder_diameter: float, ambient_temp: float) -> float: ...
    def get_ambient_surroundings_to_hollow_cylinder_thermal_conductance(self, h_air_to_pipe_surf: float, cylinder_id: float, cylinder_od: float, ambient_temp: float) -> float: ...
    def advance_timestep(self, timestep: float) -> None: ...
    @staticmethod
    def new_hollow_cylinder(initial_temperature: float, solid_pressure: float, cross_sectional_area: float, shell_id: float, shell_od: float, cylinder_length: float, pipe_shell_material: SolidMaterial, user_specified_inner_nodes: int) -> SolidStructure: ...
    def array_temperature(self) -> list[float]: ...

class SimpleShellAndTubeHeatExchanger:
    inner_pipe_shell_array_for_single_tube: HeatTransferEntity
    tube_side_fluid_array_for_single_tube: HeatTransferEntity
    shell_side_fluid_array: HeatTransferEntity
    outer_shell: HeatTransferEntity
    ambient_temperature: float
    heat_transfer_to_ambient: float
    insulation_array: HeatTransferEntity
    heat_exchanger_has_insulation: bool
    tube_side_od: float
    tube_side_id: float
    tube_side_flow_area: float
    tube_side_custom_component_loss_correlation: DimensionlessDarcyLossCorrelations
    shell_side_custom_component_loss_correlation: DimensionlessDarcyLossCorrelations
    number_of_tubes: int
    shell_side_id: float
    shell_side_od: float
    shell_side_flow_area: float
    shell_side_nusselt_correlation_to_tubes: NusseltCorrelation
    shell_side_nusselt_correlation_parasitic: NusseltCorrelation
    tube_side_nusselt_correlation: NusseltCorrelation
    insulation_thickness: float
    def try_get_insulation_cylindrical_thermal_resistance(self) -> float: ...
    def get_outer_shell_cylindrical_thermal_resistance(self) -> float: ...
    def get_inner_tubes_cylindrical_thermal_resistance(self) -> float: ...
    def get_convective_thermal_resistance_to_ambient(self) -> float: ...
    def get_inner_tubes_convective_thermal_resistance_based_on_wetted_perimeter(self) -> float: ...
    def get_shell_side_convective_thermal_resistance_cylindrical(self) -> float: ...
    def get_shell_side_parasitic_convective_thermal_resistance_cylindrical(self) -> float: ...
    def get_shell_side_heat_rate_based_on_mass_flowrate(self, shell_inlet_temperature: float, shell_outlet_temeprature: float, shell_mass_flowrate: float) -> float: ...
    def get_shell_side_heat_rate_based_on_vol_flowrate(self, shell_inlet_temperature: float, shell_outlet_temeprature: float, vol_flowrate: float) -> float: ...
    def get_tube_side_heat_rate_based_on_mass_flowrate(self, tube_inlet_temperature: float, tube_outlet_temeprature: float, tube_mass_flowrate: float) -> float: ...
    def get_tube_side_heat_rate_based_on_vol_flowrate(self, tube_inlet_temperature: float, tube_outlet_temeprature: float, vol_flowrate: float) -> float: ...
    def get_ua_based_on_mass_flowrates_and_temperature_differences(self, tube_inlet_temperature: float, tube_outlet_temeprature: float, tube_mass_flowrate: float, shell_inlet_temperature: float, shell_outlet_temeprature: float, shell_mass_flowrate: float, is_counter_current: bool) -> float: ...
    @staticmethod
    def get_ua_based_on_heat_transfer_and_temperature_differences(heat_transfer_rate: float, tube_inlet_temperature: float, tube_outlet_temeprature: float, shell_inlet_temperature: float, shell_outlet_temeprature: float, is_counter_current: bool) -> float: ...
    def obtain_shell_side_nusselt_number_based_on_expt_data(self, tube_inlet_temperature: float, tube_outlet_temeprature: float, tube_mass_flowrate: float, shell_inlet_temperature: float, shell_outlet_temeprature: float, shell_mass_flowrate: float, is_counter_current: bool) -> float: ...
    def obtain_shell_side_nusselt_number_based_on_expt_data_and_heat_rate(self, sthe_heat_transfer_rate: float, tube_inlet_temperature: float, tube_outlet_temeprature: float, shell_inlet_temperature: float, shell_outlet_temeprature: float, is_counter_current: bool) -> float: ...
    def obtain_tube_side_nusselt_number_based_on_expt_data(self, tube_inlet_temperature: float, tube_outlet_temeprature: float, tube_mass_flowrate: float, shell_inlet_temperature: float, shell_outlet_temeprature: float, shell_mass_flowrate: float, is_counter_current: bool) -> float: ...
    def obtain_parasitic_nusselt_number_based_on_expt_data(self, tube_inlet_temperature: float, tube_outlet_temeprature: float, tube_mass_flowrate: float, shell_inlet_temperature: float, shell_outlet_temeprature: float, shell_mass_flowrate: float) -> float: ...
    def obtain_parasitic_thermal_resistance_based_on_expt_data(self, tube_inlet_temperature: float, tube_outlet_temeprature: float, tube_mass_flowrate: float, shell_inlet_temperature: float, shell_outlet_temeprature: float, shell_mass_flowrate: float) -> float: ...
    def obtain_parasitic_heat_loss_rate_based_on_expt_data(self, tube_inlet_temperature: float, tube_outlet_temeprature: float, tube_mass_flowrate: float, shell_inlet_temperature: float, shell_outlet_temeprature: float, shell_mass_flowrate: float) -> float: ...
    def lateral_and_miscellaneous_connections(self, prandtl_wall_correction_setting: bool, tube_side_total_mass_flowrate: float, shell_side_total_mass_flowrate: float) -> None: ...
    def get_air_to_outer_sthe_layer_nodal_conductance(self, h_air_to_pipe_surf: float) -> float: ...
    def get_single_tube_side_fluid_array_node_to_inner_pipe_shell_nodal_conductance(self, correct_prandtl_for_wall_temperatures: bool) -> float: ...
    def get_shell_side_fluid_to_single_inner_pipe_shell_nodal_conductance(self, correct_prandtl_for_wall_temperatures: bool) -> float: ...
    def get_shell_side_fluid_to_outer_pipe_shell_nodal_conductance(self, correct_prandtl_for_wall_temperatures: bool) -> float: ...
    def get_outer_pipe_shell_to_insulation_conductance(self) -> float: ...
    def calibrate_insulation_thickness(self, insulation_thickness: float) -> None: ...
    @staticmethod
    def new_custom_circular_single_pass_sthe_with_insulation(number_of_tubes: int, number_of_inner_nodes: int, fluid_pressure: float, solid_pressure: float, tube_side_od: float, tube_side_id: float, tube_side_hydraulic_diameter: float, tube_side_flow_area_single_tube: float, shell_side_od: float, shell_side_id: float, shell_side_hydraulic_diameter: float, shell_side_flow_area: float, sthe_length: float, tube_side_form_loss: float, shell_side_form_loss: float, insulation_thickness: float, tube_side_incline_angle: float, shell_side_incline_angle: float, shell_side_liquid: LiquidMaterial, tube_side_liquid: LiquidMaterial, inner_tube_material: SolidMaterial, outer_tube_material: SolidMaterial, insulation_material: SolidMaterial, ambient_temperature: float, heat_transfer_to_ambient: float, tube_side_initial_temperature: float, shell_side_initial_temperature: float, shell_loss_correlations: DimensionlessDarcyLossCorrelations, tube_loss_correlations: DimensionlessDarcyLossCorrelations, tube_side_nusselt_correlation: NusseltCorrelation, shell_side_nusselt_correlation_to_tubes: NusseltCorrelation, shell_side_nusselt_correlation_to_outer_shell: NusseltCorrelation) -> SimpleShellAndTubeHeatExchanger: ...
    @staticmethod
    def new_du_et_al_sthe() -> SimpleShellAndTubeHeatExchanger: ...
    def inner_pipe_shell_temperature(self) -> list[float]: ...
    def inner_tube_fluid_array_temperature(self) -> list[float]: ...
    def shell_side_fluid_array_temperature(self) -> list[float]: ...
    def shell_side_outer_tube_array_temperature(self) -> list[float]: ...
    def insulation_array_temperature(self) -> list[float]: ...
    def overall_htc_based_on_conductance(self, correct_for_prandtl_wall_temperatures: bool, tube_side_total_mass_flowrate: float, shell_side_total_mass_flowrate: float) -> float: ...
    def overall_heat_transfer_coeff_u_shell_side(self, correct_for_prandtl_wall_temperatures: bool) -> float: ...
    def nusselt_tube_side(self) -> float: ...
    def reynolds_tube_side_single_tube(self) -> float: ...
    def bulk_prandtl_number_tube_side(self) -> tuple[float, float]: ...
    def nusselt_number_shell_side_to_tubes(self) -> float: ...
    def reynolds_shell_side(self) -> float: ...
    def bulk_prandtl_number_shell_side(self) -> float: ...
    def wall_prandtl_number_shell_side_fluid_for_inner_tube(self) -> float: ...
    def wall_prandtl_number_shell_side_fluid_for_outer_tube(self) -> float: ...
    def nusselt_number_shell_side_parasitic(self) -> float: ...
    def circular_tube_bundle_heat_transfer_area_shell_side(self) -> float: ...
    def parasitic_heat_transfer_area_shell_side(self) -> float: ...
    def circular_tube_bundle_heat_transfer_area_tube_side(self) -> float: ...
    def get_clone_of_shell_side_fluid_component(self) -> FluidComponent: ...
    def get_clone_of_tube_side_parallel_tube_fluid_component(self) -> FluidComponent: ...
    def set_tube_side_total_mass_flowrate(self, mass_flowrate_over_all_tubes: float) -> None: ...
    def set_shell_side_total_mass_flowrate(self, mass_flowrate_through_shell: float) -> None: ...
    def get_tube_side_hydraulic_diameter_circular_tube(self) -> float: ...
    def get_shell_side_hydraulic_diameter(self) -> float: ...
    def get_effective_length(self) -> float: ...
    def get_shell_side_cross_sectional_area(self) -> float: ...
    def get_shell_side_fluid_thermal_conductivity(self) -> float: ...
    def advance_timestep(self, timestep: float) -> None: ...

class DataAdvection:
    mass_flowrate: float
    fluid_density_heat_transfer_entity_1: float
    fluid_density_heat_transfer_entity_2: float
    @staticmethod
    def new_from_temperature_and_liquid_material(user_input_mass_flowrate: float, fluid_material: LiquidMaterial, temperature_1: float, temperature_2: float) -> DataAdvection: ...
    def __init__(self, mass_flowrate: float, fluid_density_heat_transfer_entity_1: float, fluid_density_heat_transfer_entity_2: float) -> None: ...

class DataUserSpecifiedConvectionResistance:
    surf_area: SurfaceArea
    heat_transfer_coeff: float
    def __init__(self, surf_area: SurfaceArea, heat_transfer_coeff: float) -> None: ...

class FluidArray:
    back_single_cv: SingleCVNode
    front_single_cv: SingleCVNode
    material_control_volume: Material
    pressure_control_volume: float
    fluid_component_loss_properties: DimensionlessDarcyLossCorrelations
    nusselt_correlation: NusseltCorrelation
    q_vector: list[float]
    def advance_timestep(self, timestep: float) -> None: ...
    def advance_timestep_with_mass_flowrate(self, timestep: float, mass_flowrate: float) -> None: ...
    def clear_vectors(self) -> None: ...
    def lateral_link_new_temperature_vector_avg_conductance(self, average_thermal_conductance: float, temperature_vec: list[float]) -> None: ...
    def get_max_timestep(self, max_temperature_change: float, mass_flowrate: float) -> float: ...
    def try_get_bulk_temperature(self) -> float: ...
    def get_reynolds(self, mass_flowrate: float) -> float: ...
    def get_nusselt(self, reynolds: float, prandtl_bulk: float, prandtl_wall: float) -> float: ...
    def link_heat_flux_bc_to_front_of_this_cv(self, heat_flux_into_control_vol: float, interaction: HeatTransferInteractionType) -> None: ...
    def link_heat_flux_bc_to_back_of_this_cv(self, heat_flux_into_control_vol: float, interaction: HeatTransferInteractionType) -> None: ...
    def link_heat_addition_to_front_of_this_cv(self, heat_rate: float, interaction: HeatTransferInteractionType) -> None: ...
    def link_heat_addition_to_back_of_this_cv(self, heat_rate: float, interaction: HeatTransferInteractionType) -> None: ...
    def link_constant_temperature_to_front_of_this_cv(self, bc_temperature: float, interaction: HeatTransferInteractionType) -> None: ...
    def link_constant_temperature_to_back_of_this_cv(self, bc_temperature: float, interaction: HeatTransferInteractionType) -> None: ...
    def set_temperature_vector(self, temperature_vec: list[float]) -> None: ...
    def len(self) -> int: ...
    def __init__(self, ) -> None: ...
    @staticmethod
    def new_cylinder(length: float, hydraulic_diameter: float, initial_temperature: float, initial_pressure: float, adjacent_solid_material: SolidMaterial, liquid_material: LiquidMaterial, pipe_form_loss: float, user_specified_inner_nodes: int, pipe_incline_angle: float) -> FluidArray: ...
    @staticmethod
    def new_annular_cylinder(length: float, inner_diameter: float, outer_diameter: float, initial_temperature: float, initial_pressure: float, adjacent_solid_material: SolidMaterial, liquid_material: LiquidMaterial, pipe_form_loss: float, user_specified_inner_nodes: int, pipe_incline_angle: float) -> FluidArray: ...
    @staticmethod
    def new_odd_shaped_pipe(length: float, hydraulic_diameter: float, cross_sectional_area: float, initial_temperature: float, initial_pressure: float, adjacent_solid_material: SolidMaterial, liquid_material: LiquidMaterial, pipe_form_loss: float, user_specified_inner_nodes: int, pipe_incline_angle: float) -> FluidArray: ...
    @staticmethod
    def new_custom_component(length: float, hydraulic_diameter: float, cross_sectional_area: float, initial_temperature: float, initial_pressure: float, liquid_material: LiquidMaterial, a: float, b: float, c: float, user_specified_inner_nodes: int, pipe_incline_angle: float) -> FluidArray: ...
    def get_temperature_vector(self) -> list[float]: ...
    def get_reverse_temperature_vector(self) -> list[float]: ...
    def get_mass_flowrate(self) -> float: ...
    def set_mass_flowrate(self, mass_flowrate: float) -> None: ...
    def get_mass_flowrate_from_pressure_loss_immutable(self, pressure_loss: float) -> float: ...
    def get_pressure_loss(self) -> float: ...
    def set_pressure_loss(self, pressure_loss: float) -> None: ...
    def get_pressure_loss_immutable(self, mass_flowrate: float) -> float: ...
    def get_cross_sectional_area(self) -> float: ...
    def get_cross_sectional_area_immutable(self) -> float: ...
    def get_hydraulic_diameter(self) -> float: ...
    def get_hydraulic_diameter_immutable(self) -> float: ...
    def get_fluid_viscosity(self) -> float: ...
    def get_fluid_viscosity_immutable(self) -> float: ...
    def get_fluid_density(self) -> float: ...
    def get_fluid_density_immutable(self) -> float: ...
    def get_component_length(self) -> float: ...
    def get_component_length_immutable(self) -> float: ...
    def get_incline_angle(self) -> float: ...
    def get_incline_angle_immutable(self) -> float: ...
    def get_internal_pressure_source(self) -> float: ...
    def get_internal_pressure_source_immutable(self) -> float: ...
    def set_internal_pressure_source(self, internal_pressure: float) -> None: ...
    @staticmethod
    def default() -> FluidArray: ...

class HeatTransferEntity:
    def set(self, user_input_hte: HeatTransferEntity) -> None: ...
    def try_set_flowrate_for_fluid_array(self, mass_flowrate: float) -> None: ...
    def advance_timestep_mut_self(self, timestep: float) -> None: ...
    @staticmethod
    def new_const_temperature_bc(temperature: float) -> HeatTransferEntity: ...
    @staticmethod
    def new_const_heat_flux_bc(heat_flux: float) -> HeatTransferEntity: ...
    @staticmethod
    def new_const_heat_addition(heat_addition: float) -> HeatTransferEntity: ...
    @staticmethod
    def new_adiabatic_bc() -> HeatTransferEntity: ...
    def try_get_bulk_temperature(self) -> float: ...
    def get_temperature_vector(self) -> list[float]: ...
    @staticmethod
    def ControlVolume(a0: CVType) -> HeatTransferEntity: ...
    @staticmethod
    def BoundaryConditions(a0: BCType) -> HeatTransferEntity: ...
    def variant(self) -> str: ...

class HeatTransferInteractionType:
    def get_thermal_conductance_based_on_interaction(self, temperature_1: float, temperature_2: float, pressure_1: float, pressure_2: float) -> float: ...
    @staticmethod
    def new_advection_interaction(mass_flowrate: float, fluid_density_heat_transfer_entity_1: float, fluid_density_heat_transfer_entity_2: float) -> HeatTransferInteractionType: ...
    @staticmethod
    def UserSpecifiedThermalConductance(a0: float) -> HeatTransferInteractionType: ...
    @staticmethod
    def SingleCartesianThermalConductanceOneDimension(a0: Material, a1: XThicknessThermalConduction) -> HeatTransferInteractionType: ...
    @staticmethod
    def DualCartesianThermalConductanceThreeDimension(a0: DataDualCartesianThermalConductanceThreeDimension) -> HeatTransferInteractionType: ...
    @staticmethod
    def DualCartesianThermalConductance(a0: tuple[Material, XThicknessThermalConduction], a1: tuple[Material, XThicknessThermalConduction]) -> HeatTransferInteractionType: ...
    @staticmethod
    def DualCylindricalThermalConductance(a0: tuple[Material, RadialCylindricalThicknessThermalConduction], a1: tuple[Material, RadialCylindricalThicknessThermalConduction], a2: tuple[InnerDiameterThermalConduction, OuterDiameterThermalConduction, CylinderLengthThermalConduction]) -> HeatTransferInteractionType: ...
    @staticmethod
    def CylindricalConductionConvectionLiquidOutside(a0: tuple[Material, RadialCylindricalThicknessThermalConduction, float, float], a1: tuple[float, OuterDiameterThermalConduction, CylinderLengthThermalConduction]) -> HeatTransferInteractionType: ...
    @staticmethod
    def CylindricalConductionConvectionLiquidInside(a0: tuple[Material, RadialCylindricalThicknessThermalConduction, float, float], a1: tuple[float, InnerDiameterThermalConduction, CylinderLengthThermalConduction]) -> HeatTransferInteractionType: ...
    @staticmethod
    def UserSpecifiedHeatAddition() -> HeatTransferInteractionType: ...
    @staticmethod
    def UserSpecifiedHeatFluxCustomArea(a0: float) -> HeatTransferInteractionType: ...
    @staticmethod
    def UserSpecifiedHeatFluxCylindricalOuterArea(a0: CylinderLengthThermalConduction, a1: OuterDiameterThermalConduction) -> HeatTransferInteractionType: ...
    @staticmethod
    def UserSpecifiedHeatFluxCylindricalInnerArea(a0: CylinderLengthThermalConduction, a1: InnerDiameterThermalConduction) -> HeatTransferInteractionType: ...
    @staticmethod
    def UserSpecifiedConvectionResistance(a0: DataUserSpecifiedConvectionResistance) -> HeatTransferInteractionType: ...
    @staticmethod
    def Advection(a0: DataAdvection) -> HeatTransferInteractionType: ...
    @staticmethod
    def SimpleRadiation(a0: float) -> HeatTransferInteractionType: ...
    def variant(self) -> str: ...

class HeaterTopBottomHead:
    twisted_tape_interior: HeatTransferEntity
    steel_shell: HeatTransferEntity
    therminol_array: HeatTransferEntity
    ambient_temperature: float
    heat_transfer_to_air: float
    def _advance_timestep(self, timestep: float) -> None: ...
    def _advance_timestep_parallel_buggy(self, timestep: float) -> None: ...
    def steel_shell_temperature(self) -> list[float]: ...
    def therminol_array_temperature(self) -> list[float]: ...
    def twisted_tape_temperature(self) -> list[float]: ...
    def lateral_and_miscellaneous_connections(self, mass_flowrate: float) -> None: ...
    def get_air_steel_shell_conductance(self, h_air_to_steel_surf: float) -> float: ...
    def get_therminol_node_steel_shell_conductance(self) -> float: ...
    def heater_v2_hydraulic_diameter_reynolds(self, mass_flowrate: float, temperature: float) -> float: ...
    def get_therminol_node_twisted_tape_conductance(self) -> float: ...
    @staticmethod
    def new_top_head(initial_temperature: float, ambient_temperature: float) -> HeaterTopBottomHead: ...
    @staticmethod
    def _new_user_callibrated_top_head(initial_temperature: float, ambient_temperature: float, h_to_air: float) -> HeaterTopBottomHead: ...
    @staticmethod
    def new_bottom_head(initial_temperature: float, ambient_temperature: float) -> HeaterTopBottomHead: ...
    @staticmethod
    def _new_user_callibrated_bottom_head(initial_temperature: float, ambient_temperature: float, h_to_air: float) -> HeaterTopBottomHead: ...

class InsulatedPorousMediaFluidComponent:
    insulation_array: HeatTransferEntity
    interior_solid_array_for_porous_media: HeatTransferEntity
    pipe_shell: HeatTransferEntity
    pipe_fluid_array: HeatTransferEntity
    ambient_temperature: float
    heat_transfer_to_ambient: float
    darcy_loss_correlation: DimensionlessDarcyLossCorrelations
    thermal_conductance_lengthscale_pipe_shell_to_insulation_pipe_interface: float
    thermal_conductance_lengthscale_pipe_shell_to_fluid: float
    thermal_conductance_lengthscale_fluid_to_porous_media_internal: float
    thermal_conductance_lengthscale_insulation_to_insulation_pipe_interface: float
    thermal_conductance_lengthscale_insulation_to_ambient: float
    nusselt_correlation_fluid_to_pipe_shell: NusseltCorrelation
    nusselt_correlation_lengthscale_fluid_to_pipe_shell: float
    convection_heat_transfer_area_insulation_to_ambient: float
    nusselt_correlation_fluid_to_porous_media_interior: NusseltCorrelation
    nusselt_correlation_lengthscale_fluid_to_porous_media_interior: float
    convection_heat_transfer_area_fluid_to_pipe_shell: float
    convection_heat_transfer_area_fluid_to_interior: float
    def lateral_and_miscellaneous_connections_mx10(self, mass_flowrate: float) -> None: ...
    def get_air_insulation_shell_conductance_mx10(self, h_air_to_insulation_surf: float) -> float: ...
    def get_therminol_node_steel_shell_conductance_mx10(self) -> float: ...
    def mx10_hydraulic_diameter_reynolds(self, mass_flowrate: float, temperature: float) -> float: ...
    def get_steel_to_fiberglass_conductance_mx10_nodal(self) -> float: ...
    def calibrate_insulation_thickness(self, pipe_length: float, insulation_id: float, insulation_thickness: float) -> None: ...
    def advance_timestep(self, timestep: float) -> None: ...
    def _advance_timestep_parallel_buggy(self, timestep: float) -> None: ...
    def pipe_shell_temperature(self) -> list[float]: ...
    def pipe_fluid_array_temperature(self) -> list[float]: ...
    def insulation_array_temperature(self) -> list[float]: ...
    def interior_solid_array_temperature(self) -> list[float]: ...
    def number_of_nodes(self) -> int: ...
    @staticmethod
    def new_annular_pipe(initial_temperature: float, ambient_temperature: float, fluid_pressure: float, solid_pressure: float, pipe_shell_id: float, pipe_length: float, flow_area: float, incline_angle: float, form_loss: float, outer_pipe_thickness: float, inner_pipe_id: float, inner_pipe_od: float, insulation_thickness: float, insulation_material: SolidMaterial, pipe_shell_material: SolidMaterial, inner_annular_pipe_material: SolidMaterial, pipe_fluid_material: LiquidMaterial, htc_to_ambient: float, user_specificed_number_of_nodes: int) -> InsulatedPorousMediaFluidComponent: ...
    @staticmethod
    def new_ciet_heater_v1_with_annular_pipe(initial_temperature: float, ambient_temperature: float, user_specified_inner_nodes: int) -> InsulatedPorousMediaFluidComponent: ...
    @staticmethod
    def new_ciet_heater_v1_top_head(initial_temperature: float, ambient_temperature: float, user_specified_inner_nodes: int) -> InsulatedPorousMediaFluidComponent: ...
    @staticmethod
    def new_ciet_heater_v1_bottom_head(initial_temperature: float, ambient_temperature: float, user_specified_inner_nodes: int) -> InsulatedPorousMediaFluidComponent: ...
    @staticmethod
    def new_dewet_model_heater_v2_insulated(initial_temperature: float, ambient_temperature: float, user_specified_inner_nodes: int) -> InsulatedPorousMediaFluidComponent: ...
    @staticmethod
    def new_static_mixer_23_mx20(initial_temperature: float, ambient_temperature: float) -> InsulatedPorousMediaFluidComponent: ...
    @staticmethod
    def new_static_mixer_25_mx21(initial_temperature: float, ambient_temperature: float) -> InsulatedPorousMediaFluidComponent: ...
    @staticmethod
    def new_static_mixer_2_mx10(initial_temperature: float, ambient_temperature: float) -> InsulatedPorousMediaFluidComponent: ...
    @staticmethod
    def new_static_mixer_pipe_2a_mx10(initial_temperature: float, ambient_temperature: float) -> InsulatedPorousMediaFluidComponent: ...
    @staticmethod
    def new_static_mixer_pipe_25a_mx21(initial_temperature: float, ambient_temperature: float) -> InsulatedPorousMediaFluidComponent: ...
    @staticmethod
    def new_static_mixer_pipe_23a_mx20(initial_temperature: float, ambient_temperature: float) -> InsulatedPorousMediaFluidComponent: ...
    def lateral_and_miscellaneous_connections(self, prandtl_wall_correction_setting: bool, mass_flowrate: float, shell_side_steady_state_power: float, porous_media_side_steady_state_power: float) -> None: ...
    def get_ambient_to_insulation_nodal_conductance(self, heat_transfer_to_ambient: float) -> float: ...
    def get_pipe_shell_to_insulation_nodal_conductance(self) -> float: ...
    def get_pipe_shell_to_fluid_nodal_conductance(self, prandtl_wall_correction_setting: bool) -> float: ...
    def get_interior_to_fluid_nodal_conductance(self, prandtl_wall_correction_setting: bool) -> float: ...

class NonInsulatedPorousMediaFluidComponent:
    interior_solid_array_for_porous_media: HeatTransferEntity
    pipe_shell: HeatTransferEntity
    pipe_fluid_array: HeatTransferEntity
    ambient_temperature: float
    heat_transfer_to_ambient: float
    darcy_loss_correlation: DimensionlessDarcyLossCorrelations
    solid_side_thermal_conductance_lengthscale_pipe_to_ambient: float
    solid_side_thermal_conductance_lengthscale_pipe_to_fluid: float
    solid_side_thermal_conductance_lengthscale_fluid_to_porous_media_internal: float
    nusselt_correlation_to_pipe_shell: NusseltCorrelation
    nusselt_correlation_lengthscale_to_ambient: float
    convection_heat_transfer_area_to_ambient: float
    nusselt_correlation_to_porous_media_interior: NusseltCorrelation
    nusselt_correlation_lengthscale_to_porous_media_interior: float
    convection_heat_transfer_area_to_pipe: float
    convection_heat_transfer_area_to_interior: float
    @staticmethod
    def new_dewet_model_heater_v2(initial_temperature: float, ambient_temperature: float, user_specified_inner_nodes: int) -> NonInsulatedPorousMediaFluidComponent: ...
    @staticmethod
    def _new_six_watts_per_m2_kelvin_model_heater_v2_model(initial_temperature: float, ambient_temperature: float, user_specified_inner_nodes: int) -> NonInsulatedPorousMediaFluidComponent: ...
    @staticmethod
    def ciet_heater_v2_generic_model(initial_temperature: float, ambient_temperature: float, user_specified_inner_nodes: int, h_to_air: float) -> NonInsulatedPorousMediaFluidComponent: ...
    def advance_timestep(self, timestep: float) -> None: ...
    def _advance_timestep_parallel_buggy(self, timestep: float) -> None: ...
    def ciet_heater_v2_lateral_and_miscellaneous_connections(self, mass_flowrate: float, heater_steady_state_power: float) -> None: ...
    def ciet_heater_v2_get_air_steel_nodal_shell_conductance(self, h_air_to_steel_surf: float) -> float: ...
    def ciet_heater_v2_get_therminol_node_steel_shell_conductance(self) -> float: ...
    @staticmethod
    def heater_v2_hydraulic_diameter_reynolds(mass_flowrate: float, temperature: float) -> float: ...
    def ciet_heater_v2_get_therminol_node_twisted_tape_conductance(self) -> float: ...
    def pipe_shell_temperature(self) -> list[float]: ...
    def pipe_fluid_array_temperature(self) -> list[float]: ...
    def interior_solid_array_temperature(self) -> list[float]: ...
    def lateral_and_miscellaneous_connections(self, prandtl_wall_correction_setting: bool, mass_flowrate: float, shell_side_steady_state_power: float, porous_media_side_steady_state_power: float) -> None: ...
    def get_ambient_to_pipe_shell_nodal_conductance(self, heat_transfer_to_ambient: float) -> float: ...
    def get_interior_to_fluid_nodal_conductance(self, prandtl_wall_correction_setting: bool) -> float: ...
    def get_pipe_shell_to_fluid_nodal_conductance(self, prandtl_wall_correction_setting: bool) -> float: ...

class SolidColumn:
    back_single_cv: SingleCVNode
    front_single_cv: SingleCVNode
    total_length: float
    material_control_volume: Material
    pressure_control_volume: float
    q_vector: list[float]
    def get_temperature_vector(self) -> list[float]: ...
    def get_reverse_temperature_vector(self) -> list[float]: ...
    def lateral_link_new_temperature_vector_avg_conductance(self, average_thermal_conductance: float, temperature_vec: list[float]) -> None: ...
    def set_temperature_vector(self, temperature_vec: list[float]) -> None: ...
    def len(self) -> int: ...
    def link_heat_flux_bc_to_front_of_this_cv(self, heat_flux_into_control_vol: float, interaction: HeatTransferInteractionType) -> None: ...
    def link_heat_flux_bc_to_back_of_this_cv(self, heat_flux_into_control_vol: float, interaction: HeatTransferInteractionType) -> None: ...
    def link_heat_addition_to_front_of_this_cv(self, heat_rate: float, interaction: HeatTransferInteractionType) -> None: ...
    def link_heat_addition_to_back_of_this_cv(self, heat_rate: float, interaction: HeatTransferInteractionType) -> None: ...
    def link_constant_temperature_to_front_of_this_cv(self, bc_temperature: float, interaction: HeatTransferInteractionType) -> None: ...
    def link_constant_temperature_to_back_of_this_cv(self, bc_temperature: float, interaction: HeatTransferInteractionType) -> None: ...
    def __init__(self, ) -> None: ...
    @staticmethod
    def new_block(length: float, thickness: float, width: float, initial_temperature: float, initial_pressure: float, solid_material: SolidMaterial, user_specified_inner_nodes: int) -> SolidColumn: ...
    @staticmethod
    def new_one_dimension_volume(length: float, initial_temperature: float, initial_pressure: float, solid_material: SolidMaterial, user_specified_inner_nodes: int) -> SolidColumn: ...
    @staticmethod
    def new_cylinder(length: float, diameter: float, initial_temperature: float, initial_pressure: float, solid_material: SolidMaterial, user_specified_inner_nodes: int) -> SolidColumn: ...
    @staticmethod
    def new_cylindrical_shell(length: float, inner_diameter: float, outer_diameter: float, initial_temperature: float, initial_pressure: float, solid_material: SolidMaterial, user_specified_inner_nodes: int) -> SolidColumn: ...
    def get_max_timestep(self, max_temperature_change: float) -> float: ...
    def try_get_bulk_temperature(self) -> float: ...
    def get_component_length(self) -> float: ...
    def get_component_xs_area(self) -> float: ...
    def advance_timestep(self, timestep: float) -> None: ...
    def clear_vectors(self) -> None: ...
    @staticmethod
    def default() -> SolidColumn: ...

class StructuralSupport:
    support_array: HeatTransferEntity
    ambient_temperature: float
    heat_transfer_to_air: float
    total_lateral_surface_area: float
    def get_temperature_array(self) -> list[float]: ...
    def lateral_and_miscellaneous_connections(self) -> None: ...
    def get_air_to_steel_array_conductance(self, h_air_to_insulation_surf: float) -> float: ...
    def get_axial_node_to_bc_conductance(self) -> float: ...
    def _advance_timestep(self, timestep: float) -> None: ...
    @staticmethod
    def new_steel_support_cylinder(component_length: float, diameter: float, initial_temperature: float, ambient_temperature: float) -> StructuralSupport: ...

class SingleCVNode:
    current_timestep_control_volume_specific_enthalpy: float
    next_timestep_specific_enthalpy: float
    rate_enthalpy_change_vector: list[float]
    mass_control_volume: float
    material_control_volume: Material
    pressure_control_volume: float
    volume: float
    max_timestep_vector: list[float]
    mesh_stability_lengthscale_vector: list[float]
    volumetric_flowrate_vector: list[float]
    temperature: float
    def calculate_cv_front_bc_back_advection_non_set_temperature(self, advection_data: DataAdvection) -> None: ...
    def calculate_bc_front_cv_back_advection_non_set_temperature(self, advection_data: DataAdvection) -> None: ...
    def calculate_cv_front_bc_back_advection_set_temperature(self, boundary_condition_temperature: float, advection_data: DataAdvection) -> None: ...
    def calculate_bc_front_cv_back_advection_set_temperature(self, boundary_condition_temperature: float, advection_data: DataAdvection) -> None: ...
    def calculate_single_cv_node_constant_temperature_conductance(self, boundary_condition_temperature: float, interaction: HeatTransferInteractionType) -> None: ...
    def calculate_mesh_stability_conduction_timestep_for_single_node_and_bc(self, interaction: HeatTransferInteractionType) -> float: ...
    def calculate_conduction_timestep(self) -> float: ...
    def calculate_courant_number_timestep(self, max_courant_number: float) -> float: ...
    def append_conduction_mesh_stability_timestep(self, lengthscale: float) -> float: ...
    def get_max_timestep(self, max_temperature_change: float) -> float: ...
    def __init__(self, cv_temperature: float, cv_material: Material, cv_mass: float, cv_volume: float) -> None: ...
    def get_temperature_from_enthalpy_and_set(self) -> float: ...
    @staticmethod
    def new_sphere(diameter: float, material: Material, cv_temperature: float, pressure: float) -> SingleCVNode: ...
    @staticmethod
    def new_one_dimension_volume(length: float, material: Material, cv_temperature: float, pressure: float) -> SingleCVNode: ...
    @staticmethod
    def new_block(z: float, width: float, thickness: float, material: Material, cv_temperature: float, pressure: float) -> SingleCVNode: ...
    @staticmethod
    def new_cylinder(z: float, diameter: float, material: Material, cv_temperature: float, pressure: float) -> SingleCVNode: ...
    @staticmethod
    def new_cylindrical_shell(z: float, id: InnerDiameterThermalConduction, od: OuterDiameterThermalConduction, material: Material, cv_temperature: float, pressure: float) -> SingleCVNode: ...
    @staticmethod
    def new_odd_shaped_pipe(z: float, cross_sectional_area: float, material: Material, cv_temperature: float, pressure: float) -> SingleCVNode: ...
    def advance_timestep(self, timestep: float) -> None: ...
    def clear_vectors(self) -> None: ...
    @staticmethod
    def default() -> SingleCVNode: ...

class TuasLibError:
    @staticmethod
    def ShapeMismatch(a0: str) -> TuasLibError: ...
    @staticmethod
    def CourantMassFlowVectorEmpty() -> TuasLibError: ...
    @staticmethod
    def GenericStringError(a0: str) -> TuasLibError: ...
    @staticmethod
    def NotImplementedForBoundaryConditions(a0: str) -> TuasLibError: ...
    @staticmethod
    def TypeConversionErrorHeatTransferEntity() -> TuasLibError: ...
    @staticmethod
    def TypeConversionErrorMaterial() -> TuasLibError: ...
    @staticmethod
    def ThermophysicalPropertyTemperatureRangeError(material: str, temperature: float, lower_bound: float, upper_bound: float) -> TuasLibError: ...
    @staticmethod
    def CorrelationRangeError(parameter: str, value: float, lower_bound: float, upper_bound: float, units: str) -> TuasLibError: ...
    @staticmethod
    def ThermophysicalPropertyError() -> TuasLibError: ...
    @staticmethod
    def WrongHeatTransferInteractionType() -> TuasLibError: ...
    def variant(self) -> str: ...

def get_dowtherm_a_constant_pressure_specific_heat_capacity(fluid_temp: float) -> float: ...
def get_dowtherm_a_density(fluid_temp: float) -> float: ...
def get_dowtherm_a_enthalpy(fluid_temp: float) -> float: ...
def get_dowtherm_a_thermal_conductivity(fluid_temp: float) -> float: ...
def get_dowtherm_a_viscosity(fluid_temp: float) -> float: ...
def get_temperature_from_enthalpy(fluid_enthalpy: float) -> float: ...
def max_temp_dowtherm_a() -> float: ...
def min_temp_dowtherm_a() -> float: ...
def range_check_dowtherm_a(fluid_temp: float) -> bool: ...
def get_flibe_constant_pressure_specific_heat_capacity(fluid_temp: float) -> float: ...
def get_flibe_density(fluid_temp: float) -> float: ...
def get_flibe_dynamic_viscosity(fluid_temp: float) -> float: ...
def get_flibe_specific_enthalpy(fluid_temp: float) -> float: ...
def get_flibe_thermal_conductivity(fluid_temp: float) -> float: ...
def get_temperature_from_enthalpy(fluid_enthalpy: float) -> float: ...
def max_temp_flibe() -> float: ...
def min_temp_flibe() -> float: ...
def range_check_flibe_salt(fluid_temp: float) -> bool: ...
def get_flinak_constant_pressure_specific_heat_capacity(fluid_temp: float) -> float: ...
def get_flinak_density(fluid_temp: float) -> float: ...
def get_flinak_dynamic_viscosity(fluid_temp: float) -> float: ...
def get_flinak_specific_enthalpy(fluid_temp: float) -> float: ...
def get_flinak_thermal_conductivity(fluid_temp: float) -> float: ...
def get_temperature_from_enthalpy(fluid_enthalpy: float) -> float: ...
def max_temp_flinak() -> float: ...
def min_temp_flinak() -> float: ...
def range_check_flinak_salt(fluid_temp: float) -> bool: ...
def get_hitec_constant_pressure_specific_heat_capacity(fluid_temp: float) -> float: ...
def get_hitec_density(fluid_temp: float) -> float: ...
def get_hitec_dynamic_viscosity(fluid_temp: float) -> float: ...
def get_hitec_specific_enthalpy(fluid_temp: float) -> float: ...
def get_hitec_thermal_conductivity(fluid_temp: float) -> float: ...
def get_temperature_from_enthalpy(fluid_enthalpy: float) -> float: ...
def max_temp_hitec() -> float: ...
def min_temp_hitec() -> float: ...
def range_check_hitec_salt(fluid_temp: float) -> bool: ...
def get_temperature_from_enthalpy(fluid_enthalpy: float) -> float: ...
def get_yd325_constant_pressure_specific_heat_capacity(fluid_temp: float) -> float: ...
def get_yd325_density(fluid_temp: float) -> float: ...
def get_yd325_dynamic_viscosity(fluid_temp: float) -> float: ...
def get_yd325_specific_enthalpy(fluid_temp: float) -> float: ...
def get_yd325_thermal_conductivity(fluid_temp: float) -> float: ...
def max_temp_yd325_oil() -> float: ...
def min_temp_yd325_oil() -> float: ...
def range_check_yd325_oil(fluid_temp: float) -> bool: ...
def try_get_nu_momentum_diffusivity(material: Material, temperature: float, pressure: float) -> float: ...
def range_check(material: Material, material_temperature: float, upper_temperature_limit: float, lower_temperature_limit: float) -> bool: ...
def copper_density() -> float: ...
def copper_specific_enthalpy(temperature: float) -> float: ...
def copper_specific_heat_capacity_zou_zweibaum_spline(temperature: float) -> float: ...
def copper_surf_roughness() -> float: ...
def copper_thermal_conductivity_zou_zweibaum_spline(temperature: float) -> float: ...
def max_temp_copper_zou_zweibaum_spline() -> float: ...
def min_temp_copper_zou_zweibaum_spline() -> float: ...
def fiberglass_density() -> float: ...
def fiberglass_specific_enthalpy(temperature: float) -> float: ...
def fiberglass_specific_heat_capacity(_temperature: float) -> float: ...
def fiberglass_surf_roughness() -> float: ...
def fiberglass_thermal_conductivity_zou_zweibaum_spline(temperature: float) -> float: ...
def max_temp_fiberglass_zou_zweibaum_spline() -> float: ...
def min_temp_fiberglass_zou_zweibaum_spline() -> float: ...
def max_temp_nuclear_graphite() -> float: ...
def min_temp_nuclear_graphite() -> float: ...
def nuclear_graphite_fluence_damage_factor(fluence: float) -> float: ...
def nuclear_graphite_ig_110_density() -> float: ...
def nuclear_graphite_ig_110_thermal_conductivity_fluence_dependent(temperature: float, fluence: float) -> float: ...
def nuclear_graphite_ig_110_thermal_conductivity_unirradiated(temperature: float) -> float: ...
def nuclear_graphite_matrix_a3_density() -> float: ...
def nuclear_graphite_matrix_a3_thermal_conductivity_fluence_dependent(temperature: float, fluence: float) -> float: ...
def nuclear_graphite_matrix_a3_thermal_conductivity_zero_fluence(temperature: float) -> float: ...
def nuclear_graphite_specific_enthalpy(temperature: float) -> float: ...
def nuclear_graphite_specific_heat_capacity_butland_maddison_spline(temperature: float) -> float: ...
def nuclear_graphite_surf_roughness() -> float: ...
def ground_pyrogel_hps_dsc_spline_data(temperature: float) -> float: ...
def max_temp_pyrogel_hps() -> float: ...
def min_temp_pyrogel_hps() -> float: ...
def pryogel_hps_specific_heat_capacity_rough_estimate(temperature: float) -> float: ...
def pryogel_hps_specific_heat_capacity_spline_low_temp(temperature: float) -> float: ...
def pyrogel_hps_density() -> float: ...
def pyrogel_hps_specific_enthalpy(temperature: float) -> float: ...
def pyrogel_hps_surf_roughness() -> float: ...
def pyrogel_thermal_conductivity_commercial_factsheet_spline(temperature: float) -> float: ...
def max_temp_ss_304l_zou_zweibaum_spline() -> float: ...
def min_temp_ss_304l_zou_zweibaum_spline() -> float: ...
def steel_304_l_libreoffice_spline_specific_heat_capacity_ciet_zweibaum(temperature: float) -> float: ...
def steel_304_l_libreoffice_spline_thermal_conductivity_zweibaum(temperature: float) -> float: ...
def steel_304_l_spline_specific_enthalpy_ciet_zweibaum(temperature: float) -> float: ...
def steel_304_l_spline_specific_heat_capacity_ciet_zweibaum(temperature: float) -> float: ...
def steel_304_l_spline_thermal_conductivity(temperature: float) -> float: ...
def steel_ss_304_l_density() -> float: ...
def steel_ss_304_l_ornl_specific_enthalpy_graves(temperature: float) -> float: ...
def steel_ss_304_l_ornl_specific_heat_capacity(temperature: float) -> float: ...
def steel_ss_304_l_ornl_thermal_conductivity(temperature: float) -> float: ...
def steel_surf_roughness() -> float: ...
def max_temp_ss_304l_high_temp_kim() -> float: ...
def melting_and_liquid_region_notes() -> None: ...
def min_temp_ss_304l_high_temp_kim() -> float: ...
def steel_304_l_high_temp_density_kim(temperature: float) -> float: ...
def steel_304_l_high_temp_specific_enthalpy_kim(temperature: float) -> float: ...
def steel_304_l_high_temp_specific_heat_capacity_kim(temperature: float) -> float: ...
def steel_304_l_high_temp_temp_from_specific_enthalpy_kim(h_steel: float) -> float: ...
def steel_304_l_high_temp_thermal_conductivity_kim(temperature: float) -> float: ...
def try_get_h(material: Material, temperature: float, _pressure: float) -> float: ...
def try_get_temperature_from_h(material: Material, material_enthalpy: float, _pressure: float) -> float: ...
def try_get_cp(material: Material, temperature: float, _pressure: float) -> float: ...
def try_get_alpha_thermal_diffusivity(material: Material, temperature: float, pressure: float) -> float: ...
def try_get_rho_cp(material: Material, temperature: float, pressure: float) -> float: ...
def courant_number_3d_openfoam_algorithm_velocity(control_volume_volume: float, timestep: float, face_area_vector: list[float], velocity_vector: list[float], angle_between_area_normals_and_velocity_vector: list[float]) -> float: ...
def courant_number_3d_openfoam_algorithm_vol_flowrate(control_volume_volume: float, timestep: float, volume_flowrate_vector: list[float]) -> float: ...
def fourier_number_heat_conduction(alpha_thermal_diffusivity: float, timestep: float, mesh_length: float) -> float: ...
def fourier_number_heat_convection(heat_transfer_coeffcient_for_external_fluid: float, control_volume_thermal_conductivity: float, volume_cv_to_surface_area_cv_ratio: float, alpha_thermal_diffusivity: float, timestep: float) -> float: ...
def get_fluid_courant_number_one_dimension(fluid_velocity: float, timestep: float, cell_length_scale: float) -> float: ...
def single_face_courant_number_enthalpy_flow(mass_flowrate: float, control_volume_mass: float, timestep: float) -> float: ...
def darcy(reynolds_number: float, roughness_ratio: float) -> float: ...
def calc_bejan_from_pressure(fluid_pressure: float, hydraulic_diameter: float, fluid_density: float, fluid_viscosity: float) -> float: ...
def calc_bejan_to_pressure(bejan_d: float, hydraulic_diameter: float, fluid_density: float, fluid_viscosity: float) -> float: ...
def calc_reynolds_from_mass_rate(fluid_mass_flowrate: float, cross_sectional_area: float, hydraulic_diameter: float, fluid_viscosity: float) -> float: ...
def calc_reynolds_from_velocity(fluid_density: float, velocity: float, hydraulic_diameter: float, fluid_viscosity: float) -> float: ...
def calc_reynolds_to_mass_rate(cross_sectional_area: float, reynolds_number: float, hydraulic_diameter: float, fluid_viscosity: float) -> float: ...
def fldk(reynolds_number: float, roughness_ratio: float, length_to_diameter_ratio: float, k: float) -> float: ...
def get_bejan_d(reynolds_number: float, roughness_ratio: float, length_to_diameter_ratio: float, k: float) -> float: ...
def get_reynolds_number(bejan_d: float, roughness_ratio: float, length_to_diameter: float, form_loss_k: float) -> float: ...
def moody(reynolds_number: float, roughness_ratio: float) -> float: ...
def pipe_calc_mass_flowrate(pressure_loss: float, cross_sectional_area: float, hydraulic_diameter: float, fluid_viscosity: float, fluid_density: float, pipe_length: float, absolute_roughness: float, form_loss_k: float) -> float: ...
def pipe_calc_pressure_loss(fluid_mass_flowrate: float, cross_sectional_area: float, hydraulic_diameter: float, fluid_viscosity: float, fluid_density: float, pipe_length: float, absolute_roughness: float, form_loss_k: float) -> float: ...
def advection_heat_rate(mass_flow_from_a_to_b: float, specific_enthalpy_of_a: float, specific_enthalpy_of_b: float) -> float: ...
def get_conductance_cylindrical_radial_two_materials(material_inner_shell: Material, material_outer_shell: Material, material_temperature_inner_shell: float, material_temperature_outer_shell: float, material_pressure_inner_shell: float, material_pressure_outer_shell: float, id: InnerDiameterThermalConduction, inner_shell_thickness: RadialCylindricalThicknessThermalConduction, outer_shell_thickness: RadialCylindricalThicknessThermalConduction, l: CylinderLengthThermalConduction) -> float: ...
def get_conductance_dual_cartesian_three_dimensions(material_1: Material, material_2: Material, material_temperature_1: float, material_temperature_2: float, material_pressure_1: float, material_pressure_2: float, xs_area: CrossSectionalArea, thickness_1: XThicknessThermalConduction, thickness_2: XThicknessThermalConduction) -> float: ...
def get_conductance_single_cartesian_one_dimension(material: Material, material_temperature_1: float, material_temperature_2: float, material_pressure_1: float, material_pressure_2: float, thickness: XThicknessThermalConduction) -> float: ...
def get_conductance_single_cylindrical_radial_solid_liquid(solid: Material, solid_temperature: float, solid_pressure: float, h: float, id: InnerDiameterThermalConduction, od: OuterDiameterThermalConduction, l: CylinderLengthThermalConduction, solid_liquid_arrangement: CylindricalAndSphericalSolidFluidArrangement) -> float: ...
def simple_radiation_conductance(area_coeff: float, hot_temperature: float, cold_temperature: float) -> float: ...
def custom_gnielinski_correlation_interpolated_uniform_heat_flux_liquids_developing(correlation_coefficient_c: float, reynolds_exponent_m: float, prandtl_number_film: float, prandtl_number_fluid: float, prandtl_number_wall: float, reynolds_number: float, length_to_diameter_ratio: float) -> float: ...
def custom_gnielinski_turbulent_nusselt_correlation(correlation_coefficient_c: float, reynolds_exponent_m: float, prandtl_number_film: float, prandtl_number_fluid: float, prandtl_number_wall: float, reynolds_number: float, length_to_diameter_ratio: float) -> float: ...
def dittus_boelter_correlation(reynolds_number: float, prandtl_number: float, heating: bool) -> float: ...
def gnielinski_correlation_interpolated_uniform_heat_flux_liquids_developing(reynolds_number_film: float, prandtl_number_bulk_fluid: float, prandtl_number_film: float, prandtl_number_wall: float, darcy_friction_factor: float, length_to_diameter_ratio: float) -> float: ...
def gnielinski_correlation_interpolated_uniform_heat_flux_liquids_developing_bulk_fluid_prandtl(reynolds: float, prandtl_number_fluid: float, prandtl_number_wall: float, darcy_friction_factor: float, length_to_diameter_ratio: float) -> float: ...
def gnielinski_correlation_liquids_fully_developed(reynolds_number: float, prandtl_number_bulk_fluid: float, prandtl_number_wall: float, darcy_friction_factor: float) -> float: ...
def gnielinski_turbulent_correlation_liquids_developing(reynolds_number_film: float, prandtl_number_bulk_fluid: float, prandtl_number_film: float, prandtl_number_wall: float, darcy_friction_factor: float, length_to_diameter_ratio: float) -> float: ...
def gnielinski_turbulent_correlation_liquids_developing_bulk_fluid_prandtl(reynolds_number: float, prandtl_number_bulk_fluid: float, prandtl_number_wall: float, darcy_friction_factor: float, length_to_diameter_ratio: float) -> float: ...
def laminar_nusselt_uniform_heat_flux_developing(reynolds_number: float, prandtl_number: float, length_to_diameter_ratio: float) -> float: ...
def laminar_nusselt_uniform_heat_flux_fully_developed(reynolds_number: float) -> float: ...
def laminar_nusselt_uniform_wall_temperature_developing(reynolds_number: float, prandtl_number: float, length_to_diameter_ratio: float) -> float: ...
def laminar_nusselt_uniform_wall_temperature_fully_developed(reynolds_number: float) -> float: ...
def nusselt_ciet_heater_v1_0(reynolds_number: float) -> float: ...
def sieder_tate_correlation(reynolds_number: float, prandtl_number: float, viscosity_ratio_fluid_over_wall: float) -> float: ...
def calculate_lmtd_heat_flux_based_on_ambient_temp(overall_heat_transfer_coeff: float, ambient_temperature: float, fluid_temperature_in: float, fluid_temperature_out: float, surface_area: float) -> float: ...
def log_mean_temperature_difference(temp_cold_fluid_a: float, temp_cold_fluid_b: float, temp_hot_fluid_a: float, temp_hot_fluid_b: float) -> float: ...
def obtain_power_one_convection_one_conduction_thermal_resistance(temperature_of_heat_recipient: float, temperature_of_heat_source: float, average_surface_area_1: float, heat_transfer_coefficient_1: float, average_thermal_conductivity: float, average_surface_area: float, length_of_wall: float) -> float: ...
def obtain_power_through_double_convection_thermal_resistance(temperature_of_heat_recipient: float, temperature_of_heat_source: float, average_surface_area_1: float, heat_transfer_coefficient_1: float, average_surface_area_2: float, heat_transfer_coefficient_2: float) -> float: ...
def obtain_power_through_single_convection_thermal_resistance(temperature_of_heat_recipient: float, temperature_of_heat_source: float, average_surface_area: float, heat_transfer_coefficient: float) -> float: ...
def obtain_power_through_two_layer_wall_thermal_resistance(temperature_of_heat_recipient: float, temperature_of_heat_source: float, average_thermal_conductivity_layer_1: float, average_thermal_conductivity_layer_2: float, average_surface_area_1: float, average_surface_area_2: float, length_of_wall_1: float, length_of_wall_2: float) -> float: ...
def obtain_power_through_wall_thermal_resistance(temperature_of_heat_recipient: float, temperature_of_heat_source: float, average_thermal_conductivity: float, average_surface_area: float, length_of_wall: float) -> float: ...
def obtain_power_two_convection_one_conduction_thermal_resistance(temperature_of_heat_recipient: float, temperature_of_heat_source: float, average_surface_area_1: float, heat_transfer_coefficient_1: float, average_surface_area_2: float, heat_transfer_coefficient_2: float, average_thermal_conductivity: float, average_surface_area_thermal_cond: float, length_of_wall: float) -> float: ...
def obtain_power_two_convection_two_conduction_thermal_resistance(temperature_of_heat_recipient: float, temperature_of_heat_source: float, average_surface_area_1: float, heat_transfer_coefficient_1: float, average_surface_area_2: float, heat_transfer_coefficient_2: float, average_thermal_conductivity_layer_1: float, average_wall_surface_area_1: float, length_of_wall_1: float, average_thermal_conductivity_layer_2: float, average_wall_surface_area_2: float, length_of_wall_2: float) -> float: ...
def subtract_two_thermodynamic_temperatures(t1: float, t2: float) -> float: ...
def try_get_thermal_conductance_annular_cylinder(inner_diameter: float, outer_diameter: float, cylinder_length: float, k: float) -> float: ...
def inner_cylinder_to_annular_end_ring_view_factor(inner_diameter: float, outer_diameter: float, cylinder_height: float) -> float: ...
def inner_cylinder_to_outer_cylinder_view_factor(inner_diameter: float, outer_diameter: float, cylinder_height: float) -> float: ...
def outer_cylinder_self_view_factor(inner_diameter: float, outer_diameter: float, cylinder_height: float) -> float: ...
def outer_cylinder_to_annular_end_ring_view_factor(inner_diameter: float, outer_diameter: float, cylinder_height: float) -> float: ...
def outer_cylinder_to_inner_cylinder_view_factor(inner_diameter: float, outer_diameter: float, cylinder_height: float) -> float: ...
def ctah_branch_builder_isothermal_test(pump_pressure: float, initial_temperature: float) -> FluidComponentCollection: ...
def dhx_branch_builder_isothermal_test(initial_temperature: float) -> FluidComponentCollection: ...
def heater_branch_builder_isothermal_test(initial_temperature: float) -> FluidComponentCollection: ...
def new_branch_17(initial_temperature: float) -> InsulatedFluidComponent: ...
def new_branch_17a(initial_temperature: float) -> InsulatedFluidComponent: ...
def new_branch_17b(initial_temperature: float) -> InsulatedFluidComponent: ...
def new_branch_5(initial_temperature: float) -> InsulatedFluidComponent: ...
def new_branch_5a(initial_temperature: float) -> InsulatedFluidComponent: ...
def new_branch_5b(initial_temperature: float) -> InsulatedFluidComponent: ...
def new_ctah_pump(initial_temperature: float) -> NonInsulatedFluidComponent: ...
def new_flowmeter_20_label_21a(initial_temperature: float) -> NonInsulatedFluidComponent: ...
def new_flowmeter_40_14a(initial_temperature: float) -> NonInsulatedFluidComponent: ...
def new_heated_section_version_1_label_1_without_inner_annular_pipe(initial_temperature: float) -> InsulatedFluidComponent: ...
def new_heater_bottom_head_1b(initial_temperature: float) -> InsulatedFluidComponent: ...
def new_heater_top_head_1a(initial_temperature: float) -> InsulatedFluidComponent: ...
def new_inactive_ctah_horizontal(initial_temperature: float) -> NonInsulatedFluidComponent: ...
def new_inactive_ctah_vertical(initial_temperature: float) -> NonInsulatedFluidComponent: ...
def new_inactive_dhx_shell_side_heat_exchanger(initial_temperature: float) -> InsulatedFluidComponent: ...
def new_pipe_10(initial_temperature: float) -> InsulatedFluidComponent: ...
def new_pipe_11(initial_temperature: float) -> InsulatedFluidComponent: ...
def new_pipe_12(initial_temperature: float) -> InsulatedFluidComponent: ...
def new_pipe_13(initial_temperature: float) -> InsulatedFluidComponent: ...
def new_pipe_14(initial_temperature: float) -> InsulatedFluidComponent: ...
def new_pipe_15(initial_temperature: float) -> InsulatedFluidComponent: ...
def new_pipe_16(initial_temperature: float) -> InsulatedFluidComponent: ...
def new_pipe_18(initial_temperature: float) -> InsulatedFluidComponent: ...
def new_pipe_19(initial_temperature: float) -> InsulatedFluidComponent: ...
def new_pipe_20(initial_temperature: float) -> InsulatedFluidComponent: ...
def new_pipe_21(initial_temperature: float) -> InsulatedFluidComponent: ...
def new_pipe_22_relap_model(initial_temperature: float) -> InsulatedFluidComponent: ...
def new_pipe_22_sam_model(initial_temperature: float) -> InsulatedFluidComponent: ...
def new_pipe_23a(initial_temperature: float) -> InsulatedFluidComponent: ...
def new_pipe_25a(initial_temperature: float) -> InsulatedFluidComponent: ...
def new_pipe_26(initial_temperature: float) -> InsulatedFluidComponent: ...
def new_pipe_2a(initial_temperature: float) -> InsulatedFluidComponent: ...
def new_pipe_3_relap_model(initial_temperature: float) -> InsulatedFluidComponent: ...
def new_pipe_3_sam_model(initial_temperature: float) -> InsulatedFluidComponent: ...
def new_pipe_4(initial_temperature: float) -> InsulatedFluidComponent: ...
def new_pipe_6a(initial_temperature: float) -> InsulatedFluidComponent: ...
def new_pipe_8a(initial_temperature: float) -> InsulatedFluidComponent: ...
def new_pipe_9(initial_temperature: float) -> InsulatedFluidComponent: ...
def new_static_mixer_10_label_2(initial_temperature: float) -> InsulatedFluidComponent: ...
def new_static_mixer_20_label_23(initial_temperature: float) -> InsulatedFluidComponent: ...
def new_static_mixer_21_label_25(initial_temperature: float) -> InsulatedFluidComponent: ...
def new_static_mixer_40_label_8(initial_temperature: float) -> InsulatedFluidComponent: ...
def new_static_mixer_41_label_6(initial_temperature: float) -> InsulatedFluidComponent: ...
def new_dhx_sthe_version_1(initial_temperature: float) -> SimpleShellAndTubeHeatExchanger: ...
def new_dhx_sthe_version_1_mesh_refined(initial_temperature: float) -> SimpleShellAndTubeHeatExchanger: ...
def coupled_dracs_fluid_mechanics_calc_abs_mass_rate_no_tchx_calibration(pipe_34: InsulatedFluidComponent, pipe_33: InsulatedFluidComponent, pipe_32: InsulatedFluidComponent, pipe_31a: InsulatedFluidComponent, static_mixer_61_label_31: InsulatedFluidComponent, dhx_tube_side_30b: NonInsulatedFluidComponent, dhx_tube_side_heat_exchanger_30: FluidComponent, dhx_tube_side_30a: NonInsulatedFluidComponent, tchx_35a: NonInsulatedFluidComponent, tchx_35b: NonInsulatedFluidComponent, static_mixer_60_label_36: InsulatedFluidComponent, pipe_36a: InsulatedFluidComponent, pipe_37: InsulatedFluidComponent, flowmeter_60_37a: NonInsulatedFluidComponent, pipe_38: InsulatedFluidComponent, pipe_39: InsulatedFluidComponent) -> float: ...
def get_abs_mass_flowrate_across_two_branches(dracs_branches: FluidComponentSuperCollection) -> float: ...
def coupled_dracs_fluid_mechanics_calc_abs_mass_rate_sam_tchx_calibration(pipe_34: InsulatedFluidComponent, pipe_33: InsulatedFluidComponent, pipe_32: InsulatedFluidComponent, pipe_31a: InsulatedFluidComponent, static_mixer_61_label_31: InsulatedFluidComponent, dhx_tube_side_30b: NonInsulatedFluidComponent, dhx_tube_side_heat_exchanger_30: FluidComponent, dhx_tube_side_30a: NonInsulatedFluidComponent, tchx_35a: NonInsulatedFluidComponent, tchx_35b_1: NonInsulatedFluidComponent, tchx_35b_2: NonInsulatedFluidComponent, static_mixer_60_label_36: InsulatedFluidComponent, pipe_36a: InsulatedFluidComponent, pipe_37: InsulatedFluidComponent, flowmeter_60_37a: NonInsulatedFluidComponent, pipe_38: InsulatedFluidComponent, pipe_39: InsulatedFluidComponent) -> float: ...
def get_abs_mass_flowrate_across_two_branches(dracs_branches: FluidComponentSuperCollection) -> float: ...
def coupled_dracs_pri_loop_branches_fluid_mechanics_calc_abs_mass_rate(pipe_4: InsulatedFluidComponent, pipe_3: InsulatedFluidComponent, pipe_2a: InsulatedFluidComponent, static_mixer_10_label_2: InsulatedFluidComponent, heater_top_head_1a: InsulatedFluidComponent, heater_version1_1: InsulatedFluidComponent, heater_bottom_head_1b: InsulatedFluidComponent, pipe_18: InsulatedFluidComponent, pipe_5a: InsulatedFluidComponent, pipe_26: InsulatedFluidComponent, pipe_25a: InsulatedFluidComponent, static_mixer_21_label_25: InsulatedFluidComponent, dhx_shell_side_pipe_24: FluidComponent, static_mixer_20_label_23: InsulatedFluidComponent, pipe_23a: InsulatedFluidComponent, pipe_22: InsulatedFluidComponent, flowmeter_20_21a: NonInsulatedFluidComponent, pipe_21: InsulatedFluidComponent, pipe_20: InsulatedFluidComponent, pipe_19: InsulatedFluidComponent, pipe_17b: InsulatedFluidComponent) -> float: ...
def get_abs_mass_flowrate_across_two_branches(dhx_and_heater_branches: FluidComponentSuperCollection) -> float: ...
def new_dhx_tube_side_30a(initial_temperature: float) -> NonInsulatedFluidComponent: ...
def new_dhx_tube_side_30b(initial_temperature: float) -> NonInsulatedFluidComponent: ...
def new_flowmeter_60_37a(initial_temperature: float) -> NonInsulatedFluidComponent: ...
def new_isolated_dhx_tube_side_30(initial_temperature: float) -> NonInsulatedFluidComponent: ...
def new_isolated_dhx_tube_side_30_parallel_tubes(initial_temperature: float) -> NonInsulatedParallelFluidComponent: ...
def new_ndhx_tchx_horizontal_35a(initial_temperature: float) -> NonInsulatedFluidComponent: ...
def new_ndhx_tchx_vertical_35b(initial_temperature: float) -> NonInsulatedFluidComponent: ...
def new_ndhx_tchx_vertical_35b_1(initial_temperature: float) -> NonInsulatedFluidComponent: ...
def new_ndhx_tchx_vertical_35b_2(initial_temperature: float) -> NonInsulatedFluidComponent: ...
def new_pipe_31a(initial_temperature: float) -> InsulatedFluidComponent: ...
def new_pipe_32(initial_temperature: float) -> InsulatedFluidComponent: ...
def new_pipe_33(initial_temperature: float) -> InsulatedFluidComponent: ...
def new_pipe_34(initial_temperature: float) -> InsulatedFluidComponent: ...
def new_pipe_36a(initial_temperature: float) -> InsulatedFluidComponent: ...
def new_pipe_37(initial_temperature: float) -> InsulatedFluidComponent: ...
def new_pipe_38(initial_temperature: float) -> InsulatedFluidComponent: ...
def new_pipe_38_sam_model(initial_temperature: float) -> InsulatedFluidComponent: ...
def new_pipe_39(initial_temperature: float) -> InsulatedFluidComponent: ...
def new_static_mixer_60_label_36(initial_temperature: float) -> InsulatedFluidComponent: ...
def new_static_mixer_61_label_31(initial_temperature: float) -> InsulatedFluidComponent: ...
def dracs_cold_branch_builder(initial_temperature: float) -> FluidComponentCollection: ...
def dracs_hot_branch_builder(initial_temperature: float) -> FluidComponentCollection: ...
def new_active_ctah_horizontal(initial_temperature: float) -> NonInsulatedFluidComponent: ...
def new_active_ctah_vertical(initial_temperature: float) -> NonInsulatedFluidComponent: ...
def coupled_dracs_fluid_mechanics_calc_abs_mass_rate_sam_tchx_calibration(pipe_34: InsulatedFluidComponent, pipe_33: InsulatedFluidComponent, pipe_32: InsulatedFluidComponent, pipe_31a: InsulatedFluidComponent, static_mixer_61_label_31: InsulatedFluidComponent, dhx_tube_side_30b: NonInsulatedFluidComponent, dhx_tube_side_heat_exchanger_30: FluidComponent, dhx_tube_side_30a: NonInsulatedFluidComponent, tchx_35a: NonInsulatedFluidComponent, tchx_35b_1: NonInsulatedFluidComponent, tchx_35b_2: NonInsulatedFluidComponent, static_mixer_60_label_36: InsulatedFluidComponent, pipe_36a: InsulatedFluidComponent, pipe_37: InsulatedFluidComponent, flowmeter_60_37a: NonInsulatedFluidComponent, pipe_38: InsulatedFluidComponent, pipe_39: InsulatedFluidComponent) -> float: ...
def get_abs_mass_flowrate_across_dracs_branches(dracs_branches: FluidComponentSuperCollection) -> float: ...
def get_mass_flowrate_two_branches(dracs_branches: FluidComponentSuperCollection) -> tuple[float, float]: ...
def get_mass_flowrate_vector_for_dhx_heater_and_ctah_branches(pri_loop_branches: FluidComponentSuperCollection) -> tuple[float, float, float]: ...
def three_branch_pri_loop_flowrates(pump_pressure: float, ctah_branch_blocked: bool, dhx_branch_blocked: bool, pipe_4: InsulatedFluidComponent, pipe_3: InsulatedFluidComponent, pipe_2a: InsulatedFluidComponent, static_mixer_10_label_2: InsulatedFluidComponent, heater_top_head_1a: InsulatedFluidComponent, heater_ver_1: InsulatedFluidComponent, heater_bottom_head_1b: InsulatedFluidComponent, pipe_18: InsulatedFluidComponent, pipe_5a: InsulatedFluidComponent, pipe_26: InsulatedFluidComponent, pipe_25a: InsulatedFluidComponent, static_mixer_21_label_25: InsulatedFluidComponent, dhx_shell_side_pipe_24: FluidComponent, static_mixer_20_label_23: InsulatedFluidComponent, pipe_23a: InsulatedFluidComponent, pipe_22: InsulatedFluidComponent, flowmeter_20_21a: NonInsulatedFluidComponent, pipe_21: InsulatedFluidComponent, pipe_20: InsulatedFluidComponent, pipe_19: InsulatedFluidComponent, pipe_17b: InsulatedFluidComponent, pipe_5b: InsulatedFluidComponent, static_mixer_41_label_6: InsulatedFluidComponent, pipe_6a: InsulatedFluidComponent, ctah_vertical_label_7a: NonInsulatedFluidComponent, ctah_horizontal_label_7b: NonInsulatedFluidComponent, pipe_8a: InsulatedFluidComponent, static_mixer_40_label_8: InsulatedFluidComponent, pipe_9: InsulatedFluidComponent, pipe_10: InsulatedFluidComponent, pipe_11: InsulatedFluidComponent, pipe_12: InsulatedFluidComponent, ctah_pump: NonInsulatedFluidComponent, pipe_13: InsulatedFluidComponent, pipe_14: InsulatedFluidComponent, flowmeter_40_14a: NonInsulatedFluidComponent, pipe_15: InsulatedFluidComponent, pipe_16: InsulatedFluidComponent, pipe_17a: InsulatedFluidComponent) -> tuple[float, float, float]: ...
def three_branch_pri_loop_flowrates_parallel(pump_pressure: float, ctah_branch_blocked: bool, dhx_branch_blocked: bool, pipe_4: InsulatedFluidComponent, pipe_3: InsulatedFluidComponent, pipe_2a: InsulatedFluidComponent, static_mixer_10_label_2: InsulatedFluidComponent, heater_top_head_1a: InsulatedFluidComponent, heater_ver_1: InsulatedFluidComponent, heater_bottom_head_1b: InsulatedFluidComponent, pipe_18: InsulatedFluidComponent, pipe_5a: InsulatedFluidComponent, pipe_26: InsulatedFluidComponent, pipe_25a: InsulatedFluidComponent, static_mixer_21_label_25: InsulatedFluidComponent, dhx_shell_side_pipe_24: FluidComponent, static_mixer_20_label_23: InsulatedFluidComponent, pipe_23a: InsulatedFluidComponent, pipe_22: InsulatedFluidComponent, flowmeter_20_21a: NonInsulatedFluidComponent, pipe_21: InsulatedFluidComponent, pipe_20: InsulatedFluidComponent, pipe_19: InsulatedFluidComponent, pipe_17b: InsulatedFluidComponent, pipe_5b: InsulatedFluidComponent, static_mixer_41_label_6: InsulatedFluidComponent, pipe_6a: InsulatedFluidComponent, ctah_vertical_label_7a: NonInsulatedFluidComponent, ctah_horizontal_label_7b: NonInsulatedFluidComponent, pipe_8a: InsulatedFluidComponent, static_mixer_40_label_8: InsulatedFluidComponent, pipe_9: InsulatedFluidComponent, pipe_10: InsulatedFluidComponent, pipe_11: InsulatedFluidComponent, pipe_12: InsulatedFluidComponent, ctah_pump: NonInsulatedFluidComponent, pipe_13: InsulatedFluidComponent, pipe_14: InsulatedFluidComponent, flowmeter_40_14a: NonInsulatedFluidComponent, pipe_15: InsulatedFluidComponent, pipe_16: InsulatedFluidComponent, pipe_17a: InsulatedFluidComponent) -> tuple[float, float, float]: ...
def try_get_kappa_thermal_conductivity(material: Material, temperature: float, _pressure: float) -> float: ...
def try_get_mu_viscosity(material: Material, temperature: float, _pressure: float) -> float: ...
def try_get_prandtl(material: Material, temperature: float, pressure: float) -> float: ...
def try_get_rho(material: Material, temperature: float, _pressure: float) -> float: ...
MAX_MEASURED_DATA_TEMPERATURE_KELVIN: float
UNIT_AREA_SQ_METER_FOR_ONE_DIMENSIONAL_CALCS: float
